Repository nextcloud/server, pull requests merged in 2018-12, with the labels that each got.

#12762 Polishing of various modal dialogs
  core/css/jquery.ocdialog.scss
  core/js/js.js
  core/js/oc-dialogs.js
  settings/css/settings.scss
Labels: 3. to review, backport-request, bug, design

#12786 Fix activatable/deactivatable 2fa provider interface typos
  lib/public/Authentication/TwoFactorAuth/IActivatableByAdmin.php
  lib/public/Authentication/TwoFactorAuth/IDeactivatableByAdmin.php
Labels: 3. to review, backport-request, bug, technical debt

#11718 Bump jquery-ui from 1.10 to 1.12.1
  bower.json
  core/js/core.json
  core/vendor/.gitignore
  core/vendor/jquery-ui/.bower.json
  core/vendor/jquery-ui/MIT-LICENSE.txt
  core/vendor/jquery-ui/jquery-ui.min.js
  core/vendor/jquery-ui/themes/base/images/animated-overlay.gif
  core/vendor/jquery-ui/themes/base/images/ui-icons_222222_256x240.png
  core/vendor/jquery-ui/themes/base/jquery-ui.css
  core/vendor/jquery-ui/ui/minified/jquery-ui.custom.min.js
Labels: 3. to review, technical debt

#12808 Only run the AnonymousOptionsPlugion on Anonymous requests
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
Labels: 4. to release, backport-request, bug, high, regression

#12748 [stable14] Fix interaction with groups that contain a slash
  apps/provisioning_api/appinfo/routes.php
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/routes.php
  settings/src/router.js
Labels: 3. to review, bug, feature: users and groups, regression

#12813 Fix the system address book
  apps/dav/lib/CardDAV/AddressBook.php
Labels: 3. to review, backport-request, bug, regression

#12711 Smaller icon and h2 in emptycontent inside the header
  core/css/header.scss
Labels: 3. to review, bug, design

#12822 PHP module is named mbstring
  lib/private/legacy/util.php
Labels: 3. to review, backport-request, bug

#12626 Unshare from mail activity is missing
  apps/sharebymail/lib/Activity.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
Labels: 3. to review, bug, feature: activity and notification, feature: sharing

#12823 Fix layout of "i" in admin settings of federated sharing
  apps/federatedfilesharing/css/settings-admin.css
  apps/federatedfilesharing/templates/settings-admin.php
  settings/css/settings.scss
Labels: 4. to release, backport-request, bug, design

#12819 PHP 7.0 is end of life
  settings/Controller/CheckSetupController.php
Labels: 4. to release, backport-request

#12624 Validate all rich objects
  apps/dav/lib/CalDAV/Activity/Provider/Base.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/BaseTest.php
  apps/files_sharing/lib/Activity/Providers/Groups.php
  lib/private/RichObjectStrings/Validator.php
Labels: 3. to review, bug, feature: activity and notification

#12831 Do not update child all child shares on group share update
  lib/private/Share20/DefaultShareProvider.php
Labels: 3. to review, bug, feature: sharing

#12821 Add setup check for recommended PHP modules (i.e. Imagick, intl)
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 4. to release, backport-request

#12757 make a button out of 'What's new' so it's obvious it can be clicked on
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/root.vue
Labels: 4. to release, feature: settings, papercut

#12846 Fix typo in "incoming"
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/CapabilitiesTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, bug

#12824 Add setup check for pending bigint conversion
  core/Command/Db/ConvertFilecacheBigInt.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 4. to release, backport-request, enhancement

#12849 [stable15] Fix missing click event on update button
  settings/js/4.js
  settings/js/4.js.map
  settings/js/5.js.map
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js.map
  settings/src/components/appDetails.vue
Labels: 3. to review, bug, feature: apps management

#12814 No user enumeration on DAV if disabled
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CardDAV/SystemAddressbook.php
  apps/dav/lib/CardDAV/UserAddressBooks.php
Labels: 3. to review, backport-request

#12850 [stable14] Fix missing click event on update button
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/appDetails.vue
Labels: 3. to review, bug, feature: apps management

#12855 Only execute query in propagateChange once
  lib/private/Files/Cache/Propagator.php
Labels: 4. to release, backport-request

#12854 Log and continue on Dav reader failure (repair uid)
  lib/private/Repair.php
  lib/private/Repair/NC15/SetVcardDatabaseUID.php
  tests/lib/Repair/SetVcardDatabaseUIDTest.php
Labels: 4. to release, backport-request, bug, high

#12857 Emit write update only once on touch
  lib/private/Files/View.php
Labels: 4. to release, backport-request

#12863 [stable15] Fix password confirmation lib for ie11
  settings/js/4.js.map
  settings/js/5.js.map
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/package-lock.json
  settings/package.json
Labels: 4. to release, bug, feature: settings, feature: users and groups, regression

#12865 No need to propogate changes in appdata
  lib/private/Files/Cache/Propagator.php
  lib/private/Files/Storage/Common.php
Labels: 3. to review, backport-request, enhancement

#12860 [stable14] Fix password confirmation lib for ie11
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/package-lock.json
  settings/package.json
Labels: 3. to review, bug, feature: settings, feature: users and groups, regression

#12866 Do not show general warning on free space error
  apps/files/js/file-upload.js
  apps/files/tests/js/fileUploadSpec.js
Labels: 4. to release, backport-request, bug

#12847 15.0.0 RC 3
  version.php
Labels: 4. to release

#12884 Fail gracefull if an unkown oauth2 client tries to authenticate
  apps/oauth2/lib/Controller/LoginRedirectorController.php
  apps/oauth2/tests/Controller/LoginRedirectorControllerTest.php
Labels: 4. to release, enhancement

#12887 Abstract appframework mapper exceptions
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/Db/DoesNotExistException.php
  lib/public/AppFramework/Db/IMapperException.php
  lib/public/AppFramework/Db/MultipleObjectsReturnedException.php
Labels: 3. to review, enhancement

#12895 Read openssl error and log
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: 3. to review, enhancement

#12891 more caching for theming
  lib/private/Template/IconsCacher.php
  tests/lib/Template/IconsCacherTest.php
Labels: 4. to release, enhancement

#12902 Add labels to issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: 3. to review

#12886 Move OAuth2 db code to QBMapper and make it strict
  apps/oauth2/lib/Db/AccessTokenMapper.php
  apps/oauth2/lib/Db/ClientMapper.php
Labels: 3. to review, enhancement, technical debt

#12889 Fix logo path in non-themed instance
  core/css/variables.scss
Labels: 4. to release, backport-request

#12912 Switch to nextcloud-axios for oauth2 app
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/oauth2/package-lock.json
  apps/oauth2/package.json
  apps/oauth2/src/App.vue
Labels: 3. to review, javascript, technical debt

#12897 Fix unread comment icon not shown for the sharee
  apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/bootstrap/FileListContext.php
Labels: 4. to release, backport-request, bug, feature: comments, feature: dav, high

#12910 Make OAuth2 app strict
  apps/oauth2/lib/Controller/LoginRedirectorController.php
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/lib/Exceptions/AccessTokenNotFoundException.php
  apps/oauth2/lib/Exceptions/ClientNotFoundException.php
  apps/oauth2/lib/Migration/SetTokenExpiration.php
Labels: 3. to review, technical debt

#12907 Remove deprecated functions from SecureRandom
  apps/encryption/tests/Crypto/EncryptAllTest.php
  apps/federation/tests/Controller/OCSAuthAPIControllerTest.php
  lib/private/Security/SecureRandom.php
  lib/public/Security/ISecureRandom.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, technical debt

#12739 [stable14] Make sure to always load the latest icons-vars.css file
  lib/private/Template/IconsCacher.php
  tests/lib/Template/IconsCacherTest.php
Labels: 4. to release, bug

#12749 [stable14] Add pipe mode for sendmail
  config/config.sample.php
  lib/private/Mail/Mailer.php
  lib/private/Settings/Admin/Mail.php
  settings/Controller/MailSettingsController.php
  settings/js/admin.js
  settings/templates/settings/admin/additional-mail.php
  tests/Settings/Controller/MailSettingsControllerTest.php
  tests/lib/Mail/MailerTest.php
  tests/lib/Settings/Admin/MailTest.php
Labels: 3. to review, enhancement

#12959 Bump to 15.0.0 final
  version.php
Labels: 3. to review

#12963 Change doc link for 15
  lib/private/legacy/defaults.php
Labels: 3. to review

#12896 Use version from config to generate doclink
  lib/private/legacy/defaults.php
Labels: 4. to release, backport-request, bug

#12920 OAuth2: Move to migrations
  apps/oauth2/appinfo/database.xml
  apps/oauth2/composer/composer/autoload_classmap.php
  apps/oauth2/composer/composer/autoload_static.php
  apps/oauth2/lib/Migration/Version010401Date20181207190718.php
Labels: 3. to review, technical debt

#12982 Use strengthify.min on personal settings page
  settings/templates/settings/personal/security.php
Labels: 4. to release, backport-request, bug, javascript

#12919 OAuth2: move to scoped css in vue app
  apps/oauth2/css/setting-admin.css
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/oauth2/package-lock.json
  apps/oauth2/src/components/OAuthItem.vue
  apps/oauth2/templates/admin.php
  apps/oauth2/webpack.common.js
Labels: 4. to release, enhancement, technical debt

#12985 Rebuild core.js after jquery-ui merge
  core/vendor/core.js
Labels: 3. to review

#12988 Move to handlebars.runtime.min
  core/js/core.json
  core/vendor/.gitignore
  core/vendor/core.js
  core/vendor/handlebars/handlebars.min.js
  core/vendor/handlebars/handlebars.runtime.min.js
Labels: 4. to release, enhancement, javascript, technical debt

#12961 Only run PUSH drone runs on stable15 branch
  .drone.yml
Labels: 3. to review, enhancement

#13003 Use default cursor for disabled primary buttons
  core/css/inputs.scss
Labels: 3. to review, backport-request, bug, design

#13009 Better activities for systemtags that are removed by CLI
  apps/systemtags/lib/Activity/Provider.php
Labels: 3. to review, backport-request, bug, feature: activity and notification, feature: tags

#13037 [stable14] Settings ie11 fixes
  settings/.babelrc.js
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/package-lock.json
  settings/package.json
  settings/src/main.js
Labels: 3. to review, bug, feature: dependencies, feature: users and groups, high

#12923 Fixes the share autocomplete layout
  core/css/jquery-ui-fixes.scss
  core/js/sharedialogview.js
Labels: 4. to release, bug, design, regression

#13033 fixes issue #12383
  core/js/lostpassword.js
Labels: 3. to review, bug

#13073 Ie11 compatibility accessibility
  apps/accessibility/.babelrc
  apps/accessibility/.babelrc.js
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/package-lock.json
  apps/accessibility/webpack.common.js
Labels: 4. to release, backport-request, enhancement, feature: accessibility

#13070 Ie11 compatibility updatenotifications
  apps/updatenotification/.babelrc.js
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/package-lock.json
  apps/updatenotification/package.json
  apps/updatenotification/webpack.common.js
Labels: 4. to release, backport-request, bug, feature: vue apps

#12693 fix exception on LDAP mapping during login
  .drone.yml
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/HookManager.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/AppInfo/Application.php
  apps/user_ldap/lib/Command/SetConfig.php
  apps/user_ldap/lib/Controller/ConfigAPIController.php
Labels: 4. to release, backport-request, bug, feature: ldap

#13118 Fix SAML Client login flow on Apple devices
  core/Controller/ClientFlowLoginController.php
Labels: 3. to review, backport-request, bug, client: 🤖🍏 mobile

#12883 try to grab the appdata folder directly without going trough the whole tree
  lib/private/Files/AppData/AppData.php
  lib/private/Files/AppData/Factory.php
  tests/lib/Files/AppData/AppDataTest.php
  tests/lib/Preview/BackgroundCleanupJobTest.php
Labels: 4. to release

#12766 Expose Swift Mailer streaming options in config, fixes #12702
  config/config.sample.php
  lib/private/Mail/Mailer.php
  tests/lib/Mail/MailerTest.php
Labels: 3. to review, enhancement, feature: emails

#13120 [stable14] fix exception on LDAP mapping during login
  .drone.yml
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/HookManager.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/AppInfo/Application.php
  apps/user_ldap/lib/Command/SetConfig.php
  apps/user_ldap/lib/Controller/ConfigAPIController.php
Labels: 3. to review, bug, feature: ldap

#12678 Allow to disable the signature check
  apps/encryption/lib/Crypto/Crypt.php
Labels: 2. developing, enhancement, feature: encryption (server-side)

#13116 Only trust the X-FORWARDED-HOST header for trusted proxies
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3. to review, backport-request, enhancement

#13163 Make the footer "Get your own free account" translatable
  core/templates/layout.public.php
Labels: 3. to review, backport-request, bug

#13155 [15.0.1] allow content provider to generate new Index
  lib/private/FullTextSearch/FullTextSearchManager.php
  lib/public/FullTextSearch/Service/IIndexService.php
Labels: 3. to review, backport-request

#13171 Use a case insensitive search for email
  lib/private/AllConfig.php
  lib/private/User/Manager.php
  tests/lib/User/ManagerTest.php
Labels: 4. to release, bug

#13183 Only check whatsnew once per hour
  apps/files/js/app.js
Labels: 3. to review, enhancement

#13154 Fix ie11 checkboxes
  core/css/inputs.scss
Labels: 4. to release, backport-request, bug

#13185 SCSS cache buster is a combination of apps/theming/scc_vars
  lib/private/TemplateLayout.php
Labels: 3. to review, backport-request, bug

#13187 do not forgot to store the second displayname portion
  apps/user_ldap/lib/User/User.php
Labels: 3. to review, backport-request, bug, feature: ldap

#13212 Files list not rendering if user has favorites navigation unfolded
  apps/files/js/navigation.js
Labels: 4. to release, backport-request, bug, high

#13210 Followup 12883, gracefully handle the getting of /
  lib/private/Files/AppData/AppData.php
Labels: 4. to release, bug

#13122 NC16 is php >= 7.1
  .drone.yml
  lib/versioncheck.php
Labels: 2. developing, pending documentation, technical debt

#13240 Add default values when parsing account data
  lib/private/Accounts/AccountManager.php
Labels: 3. to review, backport-request, bug

#13227 Fix opening search results for comments
  apps/comments/js/search.js
  tests/acceptance/config/behat.yml
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/bootstrap/FileListContext.php
  tests/acceptance/features/bootstrap/SearchContext.php
Labels: 3. to review, backport-request, bug, feature: comments, feature: search

#13086 Fetch lastInsertId only when id null
  lib/public/AppFramework/Db/QBMapper.php
Labels: 3. to review, bug
