Repository nextcloud/server, pull requests merged in 2018-03, with the labels that each got.

#8582 Show icon in security settings for desktop clients
  settings/js/authtoken_view.js
Labels: 2. developing

#8574 Fixed breadcrumb menu flashing
  apps/files/js/breadcrumb.js
Labels: 3. to review, bug, design, feature: files, papercut

#8298 Fix activities for e2e encryption
  apps/files/lib/Activity/Provider.php
  apps/files/tests/Activity/ProviderTest.php
Labels: 3. to review, backport-request, bug, feature: activity and notification, feature: encryption (client-side)

#8595 [stable13] Fix upload button visible on read-only folders
  apps/files/css/files.scss
Labels: 3. to review, bug, design, regression

#8561 [stable13] Ext storage error warning
  apps/files_external/js/settings.js
  apps/files_external/templates/list.php
  apps/files_external/templates/settings.php
Labels: 3. to review, design, feature: external storage, regression

#8585 Prevent double selection of avatar and loading fix
  settings/js/settings/personalInfo.js
Labels: 4. to release, bug, design, feature: settings, papercut

#8587 Fixed email form on new user
  settings/js/users/users.js
  settings/templates/users/part.userlist.php
Labels: 4. to release, design, enhancement, papercut

#8588 Fix breadcrumbs width calculation
  apps/files/js/breadcrumb.js
  apps/files/tests/js/breadcrumbSpec.js
Labels: 4. to release, backport-request, bug

#8573 Fixed app navigation for IE11
  core/css/apps.scss
Labels: 4. to release, backport-request, design, high, regression

#8284 External storage test: log exceptions
  lib/private/Files/Storage/Common.php
Labels: 3. to review

#8605 Ellipsize long values in the user management
  settings/css/settings.scss
Labels: 3. to review, 4. to release, bug, feature: users and groups, papercut

#8616 [stable12] Fix comments (and systemtags) when involving users with numerical ids
  apps/comments/lib/Activity/Listener.php
  apps/comments/tests/Unit/Activity/ListenerTest.php
  apps/systemtags/lib/Activity/Listener.php
  build/integration/features/comments.feature
  build/integration/features/tags.feature
Labels: 3. to review, bug, feature: comments, feature: users and groups

#8615 [stable13] Fix comments (and systemtags) when involving users with numerical ids
  apps/comments/lib/Activity/Listener.php
  apps/comments/tests/Unit/Activity/ListenerTest.php
  apps/systemtags/lib/Activity/Listener.php
  build/integration/features/comments.feature
  build/integration/features/tags.feature
Labels: 3. to review, bug, feature: comments, feature: users and groups

#8622 [stable12] Update commentstabview.js
  apps/comments/js/commentstabview.js
Labels: 3. to review

#8621 [stable13] Update commentstabview.js
  apps/comments/js/commentstabview.js
Labels: 4. to release

#8289 AppData hardening
  lib/private/Files/SimpleFS/SimpleFile.php
  lib/public/Files/SimpleFS/ISimpleFile.php
  tests/lib/Files/SimpleFS/SimpleFileTest.php
Labels: 3. to review, enhancement

#8606 Unify look of the strengthify password hint
  core/css/guest.css
  core/css/styles.scss
  settings/css/settings.scss
Labels: 3. to review, design, papercut

#6805 Can not change encryption directory
  core/Command/Encryption/ChangeKeyStorageRoot.php
  tests/Core/Command/Encryption/ChangeKeyStorageRootTest.php
Labels: 1. to develop, bug, feature: encryption (server-side)

#8619 Use correct input type for the url entry
  apps/theming/templates/settings-admin.php
Labels: 3. to review, feature: theming, papercut

#8609 [stable13] Fixed app navigation for IE11
  core/css/apps.scss
Labels: 3. to review, bug, design, regression

#8614 Make \OCP\Mail strict
  lib/private/Mail/Attachment.php
  lib/private/Mail/EMailTemplate.php
  lib/private/Mail/Mailer.php
  lib/private/Mail/Message.php
  lib/public/Mail/IAttachment.php
  lib/public/Mail/IEMailTemplate.php
  lib/public/Mail/IMailer.php
  lib/public/Mail/IMessage.php
  tests/lib/Mail/MailerTest.php
  tests/lib/Mail/MessageTest.php
Labels: 3. to review, technical debt

#8590 Sharing: redirect to download after authentification if requested
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  core/routes.php
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/bootstrap/FilesSharingAppContext.php
Labels: 3. to review, enhancement, feature: sharing, papercut

#8603 kill old encryption migration steps
  apps/encryption/appinfo/app.php
  apps/encryption/appinfo/info.xml
  apps/encryption/composer/composer/autoload_classmap.php
  apps/encryption/composer/composer/autoload_static.php
  apps/encryption/lib/AppInfo/Application.php
  apps/encryption/lib/Command/MigrateKeys.php
  apps/encryption/lib/Controller/StatusController.php
  apps/encryption/lib/Migration.php
  apps/encryption/lib/Session.php
  apps/encryption/tests/Controller/StatusControllerTest.php
  apps/encryption/tests/MigrationTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Encryption/Manager.php
  settings/Controller/EncryptionController.php
  tests/Settings/ApplicationTest.php
  tests/Settings/Controller/EncryptionControllerTest.php
Labels: 3. to review, feature: encryption (server-side)

#8601 Remove too restrict check for background image/color
  apps/theming/css/theming.scss
Labels: 3. to review, backport-request, bug, feature: theming

#8630 use hash algo that's robust against collisions
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Proxy.php
Labels: backport-request, bug, feature: ldap

#8632 [12] Properly encapsulate require_once for app.php
  lib/private/legacy/app.php
Labels: 3. to review, bug, technical debt

#8631 [13] Properly encapsulate require_once for app.php
  lib/private/legacy/app.php
Labels: 3. to review, bug, technical debt

#8636 [stable13] AppData hardening
  lib/private/Files/SimpleFS/SimpleFile.php
  lib/public/Files/SimpleFS/ISimpleFile.php
  tests/lib/Files/SimpleFS/SimpleFileTest.php
Labels: 3. to review, enhancement

#8654 [stable13] use hash algo that's robust against collisions
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Proxy.php
Labels: 4. to release, bug, feature: ldap

#8655 [stable12] use hash algo that's robust against collisions
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Proxy.php
Labels: 4. to release, bug, feature: ldap

#8611 [stable12] Use apps versions to generate suffix when possible
  lib/private/TemplateLayout.php
Labels: 3. to review, enhancement, medium, technical debt

#8661 Make OC\Security\CSP strict
  lib/private/Security/CSP/ContentSecurityPolicy.php
  lib/private/Security/CSP/ContentSecurityPolicyManager.php
  lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php
Labels: 3. to review, technical debt

#8650 Fixed date/time picker on IE11
  core/css/styles.scss
Labels: 3. to review, bug, design, medium, regression

#8659 Make \OC\Security\CSRF strict
  lib/private/Security/CSRF/CsrfToken.php
  lib/private/Security/CSRF/CsrfTokenGenerator.php
  lib/private/Security/CSRF/CsrfTokenManager.php
  lib/private/Security/CSRF/TokenStorage/SessionStorage.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3. to review, technical debt

#8664 Set the correct active navigation entry
  settings/Controller/AdminSettingsController.php
  settings/Controller/CommonSettingsTrait.php
  settings/Controller/PersonalSettingsController.php
Labels: 3. to review, backport-request, bug, feature: settings

#8663 [stable13] Fixed date/time picker on IE11
  core/css/styles.scss
Labels: 3. to review, bug, design, medium, regression

#8634 do not create empty userid when attribute does not have allowed chars
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/AccessTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#8610 [stable13] Fix breadcrumbs width calculation
  apps/files/js/breadcrumb.js
  apps/files/tests/js/breadcrumbSpec.js
Labels: 3. to review, bug

#8669 [stable13] Display the proper language strings in setttings
  lib/private/Settings/Personal/PersonalInfo.php
Labels: 3. to review, bug

#8675 [13] Remove too restrict check for background image/color
  apps/theming/css/theming.scss
Labels: 3. to review, bug, feature: theming

#8673 [stable13] do not create empty userid when attribute does not have allowed chars
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/AccessTest.php
Labels: 3. to review, bug, feature: ldap

#8676 [stable13] Fix example regex for user agent matching
  apps/workflowengine/js/requestuseragentplugin.js
Labels: 4. to release, bug, feature: workflow engine

#8674 [stable12] do not create empty userid when attribute does not have allowed chars
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/AccessTest.php
Labels: 3. to review, bug, feature: ldap

#8677 [stable12] Fix example regex for user agent matching
  apps/workflowengine/js/requestuseragentplugin.js
Labels: 4. to release, bug, feature: workflow engine

#8680 [stable13] Don't use double quotes in MySQL queries
  lib/private/Repair/Collation.php
Labels: 3. to review

#8681 [stable12] Don't use double quotes in MySQL queries
  lib/private/Repair/Collation.php
Labels: 3. to review

#8682 [stable12] Log exceptions that happen when writing the app store reply to storage
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: 3. to review

#8678 [stable13] generate different UIDs for Birthday, Anniversary and Death event
  apps/dav/lib/CalDAV/BirthdayService.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
Labels: 3. to review

#8679 [stable12] generate different UIDs for Birthday, Anniversary and Death event
  apps/dav/lib/CalDAV/BirthdayService.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
Labels: 3. to review

#8667 [stable13] Use a more widely available method to test s3 settings
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review, enhancement

#8683 [stable13] Log exceptions that happen when writing the app store reply to storage
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: 3. to review

#8685 [stable13] Set the correct active navigation entry
  settings/Controller/AdminSettingsController.php
  settings/Controller/CommonSettingsTrait.php
  settings/Controller/PersonalSettingsController.php
Labels: 3. to review, bug, feature: settings

#8688 [stable13] Fix check if theming defaults instance is available
  lib/private/URLGenerator.php
Labels: 4. to release

#8687 [stable13] Filter out the current user when searching for emails too
  lib/private/Collaboration/Collaborators/MailPlugin.php
Labels: 4. to release, bug, feature: sharing

#8666 Make \OC\Security\IdentityProof strict
  lib/private/Security/IdentityProof/Key.php
  lib/private/Security/IdentityProof/Manager.php
  lib/private/Security/IdentityProof/Signer.php
Labels: 4. to release, technical debt

#5833 Run repair steps on uninstall in all cases
  apps/files_sharing/tests/UpdaterTest.php
  apps/files_trashbin/tests/TrashbinTest.php
  lib/base.php
  lib/private/App/AppManager.php
  lib/private/Updater.php
  lib/private/legacy/app.php
  settings/ajax/disableapp.php
Labels: 3. to review

#8689 [stable12] Fix 500 on setup page
  lib/private/TemplateLayout.php
Labels: 3. to review

#8692 [stable12] Add missing import
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: 4. to release, bug

#8693 [stable13] Fix undefined index problem
  lib/private/AppConfig.php
Labels: 3. to review

#8579 Display a list of unavailable apps for updates (aka. merge "Can I update?")
  .gitignore
  apps/updatenotification/appinfo/routes.php
  apps/updatenotification/composer/composer/autoload_classmap.php
  apps/updatenotification/composer/composer/autoload_static.php
  apps/updatenotification/css/admin.css
  apps/updatenotification/js-src/components/root.vue
  apps/updatenotification/lib/Controller/APIController.php
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: 3. to review, enhancement, feature: apps management, feature: install and update

#7419 Fixes #7175 - Allow to search for email address in user management
  .htaccess
  lib/private/DB/Connection.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/MySqlExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/SqliteExpressionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/User/Database.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/ExpressionBuilderTest.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
  tests/lib/User/Backend.php
  tests/lib/User/DatabaseTest.php
Labels: 3. to review, enhancement, feature: users and groups

#8596 Also array_slice wide email matches of local users
  lib/private/Collaboration/Collaborators/MailPlugin.php
Labels: 3. to review, backport-request, bug

#8686 [stable13] Fix activities for end2end encryption
  apps/files/lib/Activity/Provider.php
  apps/files/tests/Activity/ProviderTest.php
Labels: 3. to review, bug, feature: activity and notification, feature: encryption (client-side)

#8652 Add ETag to NavigationController
  core/Controller/NavigationController.php
  tests/Core/Controller/NavigationControllerTest.php
Labels: 3. to review, enhancement

#8696 Fix PHPDoc for public API
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
Labels: 3. to review

#8373 New standard for top right header
  apps/files_sharing/css/public.scss
  apps/files_sharing/lib/Template/LinkMenuAction.php
  core/css/header.scss
  core/css/mobile.scss
  core/css/public.scss
  core/js/contactsmenu.js
  core/js/js.js
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: 3. to review, design, enhancement, standardisation

#8714 Check if the cached js file exists
  lib/private/Template/JSCombiner.php
  tests/lib/Template/JSCombinerTest.php
Labels: 3. to review, backport-request, bug

#8662 Better debugging for "Your test case is not allowed to access the dat…
  lib/private/AppFramework/Utility/SimpleContainer.php
Labels: 3. to review, bug

#8711 don't read existing file when overwriting using object store
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review

#8593 Allow public page access to apps with group restrictions
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
Labels: 3. to review, bug, feature: apps management

#8221 Apply ldapUserFilter on members of group
  apps/user_ldap/lib/Access.php
Labels: 3. to review, enhancement, feature: ldap

#8715 disable part files for object stores
  apps/dav/lib/Connector/Sabre/File.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review, feature: filesystem

#8575 Updated popover rules to allow form inputs and added input submit for…
  apps/files/css/files.scss
  apps/files/js/newfilemenu.js
  apps/files/tests/js/newfilemenuSpec.js
  apps/files_sharing/css/public.scss
  apps/files_sharing/js/public.js
  apps/files_sharing/lib/Template/ExternalShareMenuAction.php
  core/css/apps.scss
  core/css/icons.scss
  core/css/inputs.scss
  core/css/styles.scss
  core/img/actions/confirm-fade.svg
Labels: 3. to review, design, low, papercut, standardisation

#8716 Remove base url from global cache prefix
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/ThemingDefaultsTest.php
  lib/private/Server.php
  lib/private/Template/JSCombiner.php
  lib/private/Template/SCSSCacher.php
  lib/private/TemplateLayout.php
  tests/lib/Template/CSSResourceLocatorTest.php
  tests/lib/Template/JSCombinerTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/SCSSCacherTest.php
Labels: 3. to review, backport-request, bug, feature: scss

#8648 Use session heartbeat to update CSRF token
  core/Controller/CSRFTokenController.php
  core/js/js.js
  core/js/tests/specs/coreSpec.js
  core/routes.php
  tests/Core/Controller/CSRFTokenControllerTest.php
Labels: 3. to review, enhancement, security

#8741 Fix autoloader
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review

#8738 [stable13] Better handling of invisible elements in acceptance tests
  tests/acceptance/features/core/ElementWrapper.php
Labels: 3. to review

#8739 [stable12] Better handling of invisible elements in acceptance tests
  tests/acceptance/features/core/ElementWrapper.php
Labels: 3. to review

#8736 Update login.php
  core/templates/login.php
Labels: 3. to review

#8742 OCP\AppFramework\App strict
  lib/private/AppFramework/App.php
  lib/public/AppFramework/App.php
Labels: 3. to review, technical debt

#8112 Fix integer overflow in ChunkingPlugin
  apps/dav/lib/Upload/ChunkingPlugin.php
Labels: 3. to review, backport-request, bug

#8725 [13] disable part files for object stores
  apps/dav/lib/Connector/Sabre/File.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review

#8746 [stable13] Check if the cached js file exists
  lib/private/Template/JSCombiner.php
  tests/lib/Template/JSCombinerTest.php
Labels: 3. to review, bug

#8594 Add acceptance tests for permissions on public shared folders
  tests/acceptance/config/behat.yml
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/bootstrap/FileListAncestorSetter.php
  tests/acceptance/features/bootstrap/FileListContext.php
  tests/acceptance/features/bootstrap/FilesAppContext.php
  tests/acceptance/features/bootstrap/FilesSharingAppContext.php
  tests/acceptance/features/bootstrap/WaitFor.php
  tests/acceptance/features/core/Actor.php
  tests/acceptance/features/core/ActorContext.php
Labels: 3. to review, backport-request

#8710 Tests for email collaborators pagination
  lib/private/Collaboration/Collaborators/MailPlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
Labels: 3. to review, bug

#8752 [stable13] Fix integer overflow in ChunkingPlugin
  apps/dav/lib/Upload/ChunkingPlugin.php
Labels: 3. to review

#8749 [stable13] Sharee email matches not limited
  lib/private/Collaboration/Collaborators/MailPlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
Labels: 3. to review, bug

#8755 [stable13] Revert wording back to updates
  settings/js/apps.js
Labels: 3. to review, bug, feature: apps management

#8747 Revert wording back to updates
  settings/js/apps.js
Labels: 3. to review, bug, feature: apps management

#8726 [12] disable part files for object stores
  apps/dav/lib/Connector/Sabre/File.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review

#8758 [stable13] Add acceptance tests for permissions on public shared folders
  tests/acceptance/config/behat.yml
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/bootstrap/FileListAncestorSetter.php
  tests/acceptance/features/bootstrap/FileListContext.php
  tests/acceptance/features/bootstrap/FilesAppContext.php
  tests/acceptance/features/bootstrap/FilesSharingAppContext.php
  tests/acceptance/features/bootstrap/WaitFor.php
  tests/acceptance/features/core/Actor.php
  tests/acceptance/features/core/ActorContext.php
Labels: 4. to release

#8745 [13] Remove base url from global cache prefix
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/ThemingDefaultsTest.php
  lib/private/Server.php
  lib/private/Template/JSCombiner.php
  lib/private/Template/SCSSCacher.php
  lib/private/TemplateLayout.php
  tests/lib/Template/CSSResourceLocatorTest.php
  tests/lib/Template/JSCombinerTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/SCSSCacherTest.php
Labels: 4. to release, bug, feature: scss

#8757 Move search to proper Controller
  core/Controller/SearchController.php
  core/routes.php
  core/search/ajax/search.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review, enhancement, technical debt

#8751 11.0.8 RC 1
  version.php
Labels: 4. to release

#8750 12.0.6 RC 1
  version.php
Labels: 4. to release

#8731 Header acceptance features
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/access-levels.feature
  tests/acceptance/features/bootstrap/ContactsMenuContext.php
  tests/acceptance/features/bootstrap/SettingsMenuContext.php
  tests/acceptance/features/core/ElementWrapper.php
  tests/acceptance/features/header.feature
Labels: 3. to review

#8748 13.0.1 RC1
  version.php
Labels: 3. to review

#8633 Improved translation strings
  apps/files_external/js/settings.js
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/user_ldap/js/wizard/wizardTabElementary.js
Labels: 3. to review, enhancement, feature: language l10n and translations

#8772 [stable12] Add acceptance tests for permissions on public shared folders
  tests/acceptance/config/behat.yml
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/bootstrap/FileListAncestorSetter.php
  tests/acceptance/features/bootstrap/FileListContext.php
  tests/acceptance/features/bootstrap/FilesAppContext.php
  tests/acceptance/features/bootstrap/FilesSharingAppContext.php
  tests/acceptance/features/bootstrap/WaitFor.php
  tests/acceptance/features/core/Actor.php
  tests/acceptance/features/core/ActorContext.php
Labels: 3. to review

#8769 Make admin_audit strict
  apps/admin_audit/appinfo/app.php
  apps/admin_audit/lib/Actions/Action.php
  apps/admin_audit/lib/Actions/AppManagement.php
  apps/admin_audit/lib/Actions/Auth.php
  apps/admin_audit/lib/Actions/Console.php
  apps/admin_audit/lib/Actions/Files.php
  apps/admin_audit/lib/Actions/GroupManagement.php
  apps/admin_audit/lib/Actions/Sharing.php
  apps/admin_audit/lib/Actions/Trashbin.php
  apps/admin_audit/lib/Actions/UserManagement.php
  apps/admin_audit/lib/Actions/Versions.php
  apps/admin_audit/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#8743 Strict settings
  settings/Controller/ChangePasswordController.php
  settings/Controller/UsersController.php
  tests/Settings/Controller/UsersControllerTest.php
Labels: 3. to review, technical debt

#8782 Use proper method to format absolute timestamp
  lib/private/legacy/util.php
  settings/templates/settings/admin/server.php
  tests/lib/UtilTest.php
Labels: 3. to review, technical debt

#8783 Remove unused and deprecated methods from OCP\Util
  lib/public/IServerContainer.php
  lib/public/Util.php
Labels: 3. to review, technical debt

#8784 Remove unused and deprecated class and interface AppHelper
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/App/CodeChecker/DeprecationCheck.php
  lib/private/AppHelper.php
  lib/private/Server.php
  lib/public/IHelper.php
  lib/public/IServerContainer.php
  tests/lib/ServerTest.php
Labels: 3. to review, technical debt

#8787 Remove deprecated and unsused methods of OCP\DB
  apps/user_ldap/lib/Helper.php
  lib/private/Tags.php
  lib/public/DB.php
Labels: 3. to review, technical debt

#8786 Use insertIfNotExist of the new interface
  lib/private/Tags.php
  lib/public/DB.php
  tests/lib/DB/ConnectionTest.php
  tests/lib/DB/LegacyDBTest.php
  tests/lib/DB/MDB2SchemaReaderTest.php
  tests/lib/DB/testschema.xml
Labels: 4. to release, technical debt

#8789 Use proper method to log exceptions
  apps/files/ajax/list.php
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  apps/files_external/lib/config.php
  lib/base.php
Labels: 4. to release, technical debt

#8788 Remove unused methods and constants from legacy OC_API
  lib/private/legacy/api.php
  tests/lib/APITest.php
Labels: 3. to review, technical debt

#8792 Remove unused methods of OC_Response
  apps/files_sharing/public.php
  lib/private/legacy/response.php
  lib/public/Response.php
Labels: 3. to review, technical debt

#8797 Inject public IGroupManager instead of private GroupManager
  settings/Controller/ChangePasswordController.php
  settings/Controller/UsersController.php
Labels: 3. to review, bug, feature: settings, regression

#8794 Properly cache swift v3 token
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review, enhancement

#8781 Remove old code to be compatible with Nextcloud 9 and before
  apps/federatedfilesharing/lib/Controller/MountPublicLinkController.php
Labels: 3. to review, technical debt

#8800 Move storagestats endpoint to proper controller
  apps/files/ajax/getstoragestats.php
  apps/files/appinfo/routes.php
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/Controller/AjaxController.php
Labels: 3. to review, technical debt

#8796 Make QueryBuilder varadic
  lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/public/DB/QueryBuilder/IExpressionBuilder.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
Labels: 3. to review, enhancement, technical debt

#8807 [stable13] 13.0.1
  version.php
Labels: 3. to review

#8808 [stable12] 12.0.6
  version.php
Labels: 3. to review

#8809 [stable11] 11.0.8
  version.php
Labels: 3. to review

#8806 Properly provide local memcache check to ICacheFactory
  lib/private/Memcache/Factory.php
  lib/private/Server.php
  lib/public/ICacheFactory.php
Labels: 3. to review, technical debt

#8804 Remove deprecated HTTPHelper
  apps/federatedfilesharing/tests/Controller/RequestHandlerControllerTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/HTTPHelper.php
  lib/private/Server.php
  lib/private/Share/Share.php
  lib/public/IServerContainer.php
  tests/lib/HTTPHelperTest.php
  tests/lib/ServerTest.php
  tests/lib/Share/ShareTest.php
Labels: 3. to review, technical debt

#8811 Remove deprecated URL functions for OCP\Util
  apps/files/ajax/list.php
  apps/files_sharing/templates/public.php
  apps/files_trashbin/lib/Trashbin.php
  core/templates/untrustedDomain.php
  lib/public/Util.php
Labels: 3. to review, technical debt

#8816 Remove deprecated OCP\Contacts
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Contacts.php
  tests/lib/PublicNamespace/ContactsTest.php
  tests/lib/PublicNamespace/UtilTest.php
Labels: 4. to release, technical debt

#8818 Remove "Alternative logins" title on login page
  core/templates/login.php
Labels: 4. to release, design, papercut

#8828 Fix configuration values matched in user searches
  lib/private/User/Database.php
Labels: 3. to review, bug, regression

#8793 Swift uses `containter` not `bucket`
  config/config.sample.php
  lib/private/Files/ObjectStore/Swift.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review

#8255 Full implement group display names
  apps/dav/lib/CalDAV/Activity/Provider/Base.php
  apps/dav/lib/CalDAV/Activity/Provider/Calendar.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/BaseTest.php
  apps/files_sharing/lib/Activity/Providers/Groups.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/workflowengine/js/admin.js
  apps/workflowengine/js/usergroupmembershipplugin.js
  lib/private/Group/Manager.php
  lib/private/Group/MetaData.php
  lib/private/Settings/Personal/PersonalInfo.php
  lib/private/SubAdmin.php
  settings/Controller/GroupsController.php
  settings/Controller/UsersController.php
  settings/js/apps.js
  settings/js/settings.js
  settings/js/users/groups.js
  settings/js/users/users.js
  settings/templates/users/main.php
  settings/templates/users/part.grouplist.php
  tests/Settings/Controller/GroupsControllerTest.php
  tests/Settings/Controller/UsersControllerTest.php
  tests/lib/Group/MetaDataTest.php
Labels: 3. to review, enhancement, help wanted

#8830 Emit read for nodes
  lib/private/Files/Node/HookConnector.php
Labels: 3. to review, enhancement, feature: files, feature: filesystem

#8835 group existence check works without attribute (like with users)
  apps/user_ldap/lib/Access.php
Labels: 3. to review, backport-request, bug, feature: ldap

#8850 [stable12] group existence check works without attribute (like with users)
  apps/user_ldap/lib/Access.php
Labels: 3. to review, bug, feature: ldap

#8849 [stable13] group existence check works without attribute (like with users)
  apps/user_ldap/lib/Access.php
Labels: 3. to review, bug, feature: ldap

#8843 Set "share with" field to the ID of the circle
  apps/files_sharing/lib/Controller/ShareAPIController.php
  core/js/sharedialogshareelistview.js
  core/js/sharedialogview.js
Labels: 3. to review, backport-request, bug, feature: sharing

#8853 Remove unused resolveReshare of old sharing code
  lib/private/Share/Share.php
  lib/public/Share.php
Labels: 3. to review, feature: sharing, technical debt

#8857 verify cached swift token
  apps/files_external/lib/Lib/Storage/Swift.php
  lib/private/Files/ObjectStore/Swift.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review

#8815 Provide a description of the update channels inline
  .gitignore
  apps/updatenotification/css/admin.css
  apps/updatenotification/js-src/components/root.vue
Labels: 4. to release, design, enhancement, feature: install and update

#8877 Remove old deprecated function from the BackgroundJob
  lib/public/BackgroundJob.php
Labels: 3. to review, enhancement, technical debt

#8879 Remove unused deprecated functions from OCP\JSON
  lib/private/legacy/json.php
  lib/public/JSON.php
Labels: 3. to review, enhancement, technical debt

#8878 Remove deprecated tmpFile/tmpFolder
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  apps/files_external/lib/Lib/Storage/FTP.php
  apps/files_external/lib/Lib/Storage/SMB.php
  apps/files_external/lib/Lib/Storage/Swift.php
  lib/private/Archive/TAR.php
  lib/private/Archive/ZIP.php
  lib/private/Files/Storage/Flysystem.php
  lib/public/Files.php
  tests/lib/Archive/TARTest.php
  tests/lib/Archive/TestBase.php
  tests/lib/Archive/ZIPTest.php
  tests/lib/UtilTest.php
Labels: 4. to release, enhancement, technical debt

#8875 [swift13] Fix bucket and container usage
  config/config.sample.php
  lib/private/Files/ObjectStore/Swift.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review

#8874 [swfit 13] Properly cache swift v3 token
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review

#8881 Store setUserValue as string in cache
  lib/private/AllConfig.php
Labels: 3. to review, enhancement

#8880 Remove unused download.php
  apps/files/appinfo/routes.php
  apps/files/download.php
Labels: 3. to review, technical debt

#8822 the FN is optional, carrying the displayname if present
  lib/private/Collaboration/Collaborators/MailPlugin.php
Labels: 3. to review, backport-request, bug

#8887 Add min width of two icons to the app menu
  core/css/header.scss
Labels: 3. to review, design, papercut

#8864 Allow empty emails provisioning api
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review, papercut

#8893 [stable12] Fix undefined index problem
  lib/private/AppConfig.php
Labels: 3. to review, bug

#8883 Make the swift code up to date to master on 13-swift
  lib/private/Files/ObjectStore/Swift.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review

#8861 Update ThemingController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/tests/Controller/ThemingControllerTest.php
Labels: 2. developing

#8847 Add userdetails to ocs api
  apps/provisioning_api/appinfo/routes.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 3. to review, feature: users and groups

#8821 Show EOL warning in the update section
  apps/updatenotification/css/admin.css
  apps/updatenotification/js-src/app.js
  apps/updatenotification/js-src/components/root.vue
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/lib/UpdateChecker.php
  apps/updatenotification/tests/Settings/AdminTest.php
  apps/updatenotification/tests/UpdateCheckerTest.php
  lib/private/Updater/VersionCheck.php
  tests/lib/Updater/VersionCheckTest.php
Labels: 3. to review, enhancement, feature: install and update

#8900 [stable13] the FN is optional, carrying the displayname if present
  lib/private/Collaboration/Collaborators/MailPlugin.php
Labels: 3. to review, bug, feature: dav

#8905 [stable13] Set "share with" field to the ID of the circle
  apps/files_sharing/lib/Controller/ShareAPIController.php
  core/js/sharedialogshareelistview.js
  core/js/sharedialogview.js
Labels: 3. to review, bug, feature: sharing
