Repository nextcloud/server, pull requests merged in 2018-02, with the labels that each got.

#8286 [13] Fix styling issues of guest pages #8155
  apps/theming/css/theming.scss
  lib/private/TemplateLayout.php
Labels: 3. to review, bug, feature: theming

#8287 [13] Remove jquery ui background image
  core/css/jquery-ui-fixes.scss
Labels: 3. to review, bug, design

#8297 Fix example regex for user agent matching
  apps/workflowengine/js/requestuseragentplugin.js
Labels: 3. to review, bug, feature: workflow engine

#8308 Show open graph preview in WhatsApp
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 3. to review, backport-request, enhancement, feature: previews and thumbnails

#8309 [stable13] Show open graph preview in WhatsApp
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 3. to review, enhancement

#8261 [13] Fix deleting folders when using s3 external storage
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review

#8262 [12] Fix deleting folders when using s3 external storage
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review

#8338 Simplify return statement
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Upload/UploadHome.php
  apps/encryption/lib/Crypto/Crypt.php
  apps/files_sharing/lib/Helper.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Jobs/CleanUp.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 4. to release, technical debt

#8337 Use non aliased method instead
  apps/workflowengine/lib/Check/RequestRemoteAddress.php
  core/Command/Config/System/DeleteConfig.php
  core/Command/Config/System/SetConfig.php
  core/Command/L10n/CreateJs.php
  lib/private/App/Platform.php
  lib/private/Collaboration/Collaborators/GroupPlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  lib/private/Share/Share.php
Labels: 3. to review, technical debt

#8328 Filter out the current user when searching for emails too
  lib/private/Collaboration/Collaborators/MailPlugin.php
Labels: 3. to review, backport-request, bug

#8365 Fix typo in PHPDoc
  settings/Controller/CheckSetupController.php
Labels: 4. to release

#7754 Add icons to devices/sessions
  core/css/icons.scss
  core/img/clients/desktop.svg
  core/img/clients/phone.svg
  core/img/clients/tablet.svg
  settings/css/settings.scss
  settings/js/authtoken_view.js
  settings/templates/settings/personal/security.php
Labels: 3. to review, design, enhancement

#8277 Show share owner avatars on all file lists
  apps/files_sharing/js/share.js
Labels: 3. to review, design, feature: files, feature: sharing

#8280 Correct input type for email
  settings/templates/users/part.createuser.php
Labels: 4. to release, enhancement

#8372 Properly encapsulate require_once for app.php
  lib/private/legacy/app.php
Labels: 4. to release, backport-request, bug, technical debt

#8376 Fix edit tag textbox size
  core/css/systemtags.scss
Labels: 3. to review, bug, design, feature: tags

#8095 Expose navigation entries as API endpoint
  core/Controller/NavigationController.php
  core/routes.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/NavigationManager.php
  lib/private/TemplateLayout.php
  lib/private/legacy/app.php
  lib/public/INavigationManager.php
  settings/ajax/navigationdetect.php
  tests/Core/Controller/NavigationControllerTest.php
  tests/lib/NavigationManagerTest.php
Labels: 3. to review, enhancement

#8382 Make acceptance tests for comments more consistent with the others
  .drone.yml
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/bootstrap/CommentsAppContext.php
Labels: 3. to review, feature: comments

#8396 Fix typo in build matrix of ".drone.yml"
  .drone.yml
Labels: 3. to review, bug

#8395 [stable13] Make acceptance tests for comments more consistent with the others
  .drone.yml
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/bootstrap/CommentsAppContext.php
Labels: 3. to review, feature: comments

#8391 Don't use double quotes in MySQL queries
  lib/private/Repair/Collation.php
Labels: 3. to review, backport-request

#8408 [stable12] Fix edit tag textbox size
  core/css/systemtags.scss
Labels: 3. to review

#8407 [stable13] Fix edit tag textbox size
  core/css/systemtags.scss
Labels: 3. to review

#8411 Add strict types to OC_App
  apps/user_ldap/tests/Integration/ExceptionOnLostConnection.php
  lib/private/App/AppManager.php
  lib/private/Installer.php
  lib/private/Updater.php
  lib/private/legacy/app.php
  lib/public/App/IAppManager.php
  settings/ajax/enableapp.php
  tests/lib/AppTest.php
Labels: 4. to release, technical debt

#8366 Use normal header() calls instead of private method calls
  apps/files/download.php
  apps/files_versions/download.php
  lib/private/App/CodeChecker/DeprecationCheck.php
  lib/private/legacy/files.php
  lib/private/legacy/response.php
  lib/public/Response.php
Labels: 4. to release, technical debt

#8334 Make lib/autoloader.php strictly typed and p…
  lib/autoloader.php
Labels: 3. to review

#8426 Remove unused var in OC.Notification.showTemporary
  core/js/js.js
Labels: 3. to review, technical debt

#8424 Fix updating an app
  lib/private/Updater.php
  lib/private/legacy/app.php
Labels: 3. to review, bug, regression

#8158 Use a more widely available method to test s3 settings
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review

#8428 Use TTF fonts for avatar generation
  core/fonts/OpenSans-Light.ttf
  core/fonts/OpenSans-Semibold.ttf
  lib/private/Avatar.php
Labels: 3. to review, backport-request, feature: previews and thumbnails

#8336 Cleanup unused parameter
  core/Controller/AutoCompleteController.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  settings/Controller/MailSettingsController.php
  settings/Controller/UsersController.php
  tests/Core/Controller/AutoCompleteControllerTest.php
  tests/Settings/Controller/UsersControllerTest.php
Labels: 3. to review, technical debt

#8206 Better result handling of email search
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/RemotePluginTest.php
Labels: 3. to review, bug

#8267 [stable13] Better result handling of email search
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/RemotePluginTest.php
Labels: 3. to review, bug

#8465 Make AppFramework/Http/Dispatcher strict
  lib/private/AppFramework/Http/Dispatcher.php
Labels: 3. to review, enhancement, technical debt

#8471 getIncompatibleApps needs a string not an array
  lib/base.php
  lib/private/App/AppManager.php
Labels: 4. to release, bug, regression

#8470 [stable13] Use mb_* string methods to extract first character for generated avatars
  lib/private/Avatar.php
Labels: 4. to release

#8466 Make the middlewareDispatcher strict
  lib/private/AppFramework/Http/Dispatcher.php
  lib/private/AppFramework/Middleware/MiddlewareDispatcher.php
  lib/public/AppFramework/Http/Response.php
  tests/lib/AppFramework/Http/DispatcherTest.php
  tests/lib/AppFramework/Middleware/MiddlewareDispatcherTest.php
Labels: 3. to review, enhancement, technical debt

#8456 Use phpunit's directory feature
  autotest.sh
Labels: 3. to review, enhancement, technical debt

#8474 Log exceptions that happen when writing the app store reply to storage
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: 3. to review, backport-request, bug

#8205 [stable12] Better result handling of email search
  apps/files_sharing/lib/Controller/ShareesAPIController.php
Labels: 3. to review, bug, feature: sharing

#8473 Strict OCP\AppFramework\Utility\IControllerMethodReflector
  lib/private/AppFramework/Utility/ControllerMethodReflector.php
  lib/public/AppFramework/Utility/IControllerMethodReflector.php
Labels: 4. to release, technical debt

#8490 Make SystemTag strict
  apps/systemtags/lib/Activity/Listener.php
  lib/private/SystemTag/ManagerFactory.php
  lib/private/SystemTag/SystemTag.php
  lib/private/SystemTag/SystemTagManager.php
  lib/private/SystemTag/SystemTagObjectMapper.php
  lib/public/SystemTag/ISystemTag.php
  lib/public/SystemTag/ISystemTagManager.php
  lib/public/SystemTag/ISystemTagManagerFactory.php
  lib/public/SystemTag/ISystemTagObjectMapper.php
  lib/public/SystemTag/ManagerEvent.php
  lib/public/SystemTag/MapperEvent.php
  lib/public/SystemTag/SystemTagsEntityEvent.php
  lib/public/SystemTag/TagAlreadyExistsException.php
  lib/public/SystemTag/TagNotFoundException.php
Labels: 2. developing, technical debt

#8472 Make OC\IntegrityCheck strict
  lib/private/IntegrityCheck/Checker.php
  lib/private/IntegrityCheck/Helpers/AppLocator.php
  lib/private/IntegrityCheck/Helpers/EnvironmentHelper.php
  lib/private/IntegrityCheck/Helpers/FileAccessHelper.php
  lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
  lib/private/IntegrityCheck/Iterator/ExcludeFoldersByPathFilterIterator.php
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: 2. developing, technical debt

#8476 Make OCP\IL10N strict
  core/templates/installation.php
  lib/private/App/DependencyAnalyzer.php
  lib/private/L10N/L10N.php
  lib/public/IL10N.php
Labels: 3. to review, technical debt

#8495 2nd parameter to t() must be array
  apps/user_ldap/templates/part.wizard-groupfilter.php
  apps/user_ldap/templates/part.wizard-loginfilter.php
  apps/user_ldap/templates/part.wizard-userfilter.php
  apps/user_ldap/templates/settings.php
Labels: 3. to review, bug, feature: ldap

#8416 Fix hiding and event propagation issues with the user management popover
  settings/js/users/users.js
  settings/templates/users/part.userlist.php
Labels: 3. to review, backport-request, bug

#8499 Avoid fruitless login attempts
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/tests/ConnectionTest.php
  core/Controller/LoginController.php
Labels: 3. to review, backport-request, bug, feature: ldap, feature: users and groups

#8502 Show hint in OCS API for user creation
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review, backport-request

#8507 Add some whitespace around change.svg icon
  apps/files/img/change.png
  apps/files/img/change.svg
  settings/img/change.svg
Labels: 3. to review, design

#8517 [stable13] Fix hiding and event propagation issues with the user management popover
  settings/js/users/users.js
  settings/templates/users/part.userlist.php
Labels: 3. to review, bug

#8519 Use array in t() calls in exception template
  core/templates/exception.php
Labels: 4. to release, bug

#8515 [stable13] Show hint in OCS API for user creation
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review

#8516 [stable12] Show hint in OCS API for user creation
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review

#8518 Add some whitespace around change.svg icon (stable13)
  apps/files/img/change.png
  apps/files/img/change.svg
  settings/img/change.svg
Labels: 3. to review

#8520 Add some whitespace around change.svg icon (stable12)
  apps/files/img/change.png
  apps/files/img/change.svg
  settings/img/change.svg
Labels: 3. to review

#8497 Relax what t accepts so we don't break it all
  lib/private/L10N/L10N.php
  lib/public/IL10N.php
Labels: 3. to review

#8522 Fix retrieval of group members with numerical uids from LDAP
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#8491 Make Request strict
  apps/dav/tests/unit/ServerTest.php
  lib/private/AppFramework/Http/Request.php
  lib/private/Server.php
  lib/public/IRequest.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3. to review, technical debt

#8533 [stable12] don't try login with the same name that just failed
  core/Controller/LoginController.php
Labels: 3. to review, bug, feature: users and groups

#8026 Allow custom HTML in HTML Emails
  apps/sharebymail/lib/ShareByMailProvider.php
  core/Controller/LostController.php
  lib/private/Mail/EMailTemplate.php
  lib/private/Share20/Manager.php
  lib/public/Mail/IEMailTemplate.php
Labels: 3. to review, enhancement, feature: emails

#8537 [stable12] Fix retrieval of group members with numerical uids from LDAP
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: 4. to release, bug, feature: ldap

#8536 [stable13] Fix retrieval of group members with numerical uids from LDAP
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: 3. to review, bug, feature: ldap

#8532 [stable13] Avoid fruitless login attempts
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/tests/ConnectionTest.php
  core/Controller/LoginController.php
Labels: 3. to review, bug, feature: ldap, feature: users and groups

#8511 Ext storage error warning fix
  apps/files_external/js/settings.js
  apps/files_external/templates/list.php
  apps/files_external/templates/settings.php
Labels: 3. to review, backport-request, feature: external storage

#8203 Split move and copy operations
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
  apps/files/templates/list.php
  apps/files/tests/js/fileactionsmenuSpec.js
  apps/files/tests/js/filelistSpec.js
Labels: 3. to review, enhancement

#8390 Add indeterminate state to share permission checkbox
  core/js/sharedialogshareelistview.js
  core/js/shareitemmodel.js
  core/js/tests/specs/sharedialogshareelistview.js
Labels: 3. to review, design, enhancement

#8538 [stable11] Fix retrieval of group members with numerical uids from LDAP
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: 3. to review, bug, feature: ldap

#8355 Fix comments (and systemtags) when involving users with numerical ids
  apps/comments/lib/Activity/Listener.php
  apps/comments/tests/Unit/Activity/ListenerTest.php
  apps/systemtags/lib/Activity/Listener.php
  build/integration/features/comments.feature
  build/integration/features/tags.feature
Labels: 3. to review, backport-request, bug, feature: comments, feature: users and groups

#8455 Properly set the mount type for external storages
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Lib/PersonalMount.php
Labels: 3. to review, enhancement, feature: external storage

#8541 Provide translated error message for permission error
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/Exceptions/NotAdminException.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  settings/Middleware/SubadminMiddleware.php
  tests/Settings/Middleware/SubadminMiddlewareTest.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
Labels: 4. to release, papercut

#8463 theming: handle not being in the serverroot
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/tests/Controller/ThemingControllerTest.php
Labels: 3. to review, backport-request, bug, feature: theming

#7933 Migrate Update notifications to Vue.js
  .gitignore
  apps/updatenotification/Makefile
  apps/updatenotification/css/admin.css
  apps/updatenotification/js-src/app.js
  apps/updatenotification/js-src/components/root.vue
  apps/updatenotification/js-src/init.js
  apps/updatenotification/js-src/webpack.config.js
  apps/updatenotification/js/admin.js
  apps/updatenotification/js/legacy-notification.js
  apps/updatenotification/lib/AppInfo/Application.php
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/package-lock.json
  apps/updatenotification/package.json
  apps/updatenotification/templates/admin.php
  apps/updatenotification/tests/Settings/AdminTest.php
  core/css/apps.scss
  core/css/inputs.scss
Labels: 4. to release, enhancement, feature: activity and notification, feature: install and update

#8485 Rename dialog closed when not active
  apps/files/js/filelist.js
Labels: 3. to review, feature: files

#8548 fix: change 'sqlite' to 'sqlite3'
  config/config.sample.php
Labels: 3. to review, enhancement

#8544 [stable12] Allow upgrading from OC 10.0.6 & 10.0.7
  version.php
Labels: 3. to review, feature: owncloud migration

#8557 Fix check if theming defaults instance is available
  lib/private/URLGenerator.php
Labels: 4. to release, backport-request

#8552 Make ISession strict
  lib/private/Session/CryptoSessionData.php
  lib/private/Session/Internal.php
  lib/private/Session/Memory.php
  lib/private/Session/Session.php
  lib/public/ISession.php
Labels: 3. to review, enhancement, technical debt

#8553 Make ILogger strict
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
  lib/private/Log.php
  lib/public/ILogger.php
  tests/lib/TempManagerTest.php
Labels: 3. to review, enhancement, technical debt

#8475 Empty name not allowed in theming app
  apps/theming/js/settings-admin.js
Labels: 4. to release, bug, feature: theming

#8285 Make SMB module more fault-tolerant
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review, enhancement

#8051 Public page template response
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/css/public.scss
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/lib/Template/ExternalShareMenuAction.php
  apps/files_sharing/lib/Template/LinkMenuAction.php
  apps/files_sharing/templates/public.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  core/css/public.scss
  core/css/server.scss
  core/js/core.json
  core/js/public/publicpage.js
  core/templates/layout.public.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Template/Base.php
  lib/private/TemplateLayout.php
  lib/private/legacy/template.php
  lib/public/AppFramework/Http/Template/IMenuAction.php
  lib/public/AppFramework/Http/Template/PublicTemplateResponse.php
  lib/public/AppFramework/Http/Template/SimpleMenuAction.php
  lib/public/AppFramework/Http/TemplateResponse.php
  tests/acceptance/features/bootstrap/FilesSharingAppContext.php
  tests/lib/AppFramework/Http/PublicTemplateResponseTest.php
Labels: 4. to release, enhancement, feature: sharing

#7363 Let the admin configure the default share permissions
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  core/Controller/OCJSController.php
  core/js/js.js
  core/js/shareitemmodel.js
  core/js/tests/specs/shareitemmodelSpec.js
  lib/private/Settings/Admin/Sharing.php
  lib/private/Settings/Manager.php
  lib/private/Template/JSConfigHelper.php
  lib/private/TemplateLayout.php
  settings/css/settings.scss
  settings/js/admin.js
  settings/templates/settings/admin/sharing.php
  tests/lib/Settings/Admin/SharingTest.php
  tests/lib/Settings/ManagerTest.php
Labels: 4. to release, downstream, feature: sharing

#8219 Fix proper overwrite URL on CLI install
  lib/private/Setup.php
Labels: 4. to release

#8496 External storage design fixes and update
  apps/files_external/css/settings.scss
  apps/files_external/js/settings.js
  apps/files_external/templates/settings.php
  apps/files_external/tests/js/settingsSpec.js
  core/css/apps.scss
  settings/css/settings.scss
Labels: 4. to release, design, enhancement, feature: external storage, low, papercut

#8130 [stable12] Fix own avatar not updated when display name is changed
  lib/private/AvatarManager.php
  tests/lib/AvatarManagerTest.php
Labels: 3. to review, bug

#8565 Make the Outlook and Thunderbird addons identifyable
  apps/workflowengine/lib/Check/RequestUserAgent.php
  apps/workflowengine/tests/Check/RequestUserAgentTest.php
  lib/public/IRequest.php
Labels: 3. to review, backport-request, enhancement

#7600 New user button to sidebar
  core/css/apps.scss
  core/css/inputs.scss
  core/css/multiselect.scss
  settings/css/settings.scss
  settings/js/users/users.js
  settings/templates/users/main.php
  settings/templates/users/part.createuser.php
  settings/templates/users/part.userlist.php
  tests/acceptance/features/bootstrap/UsersSettingsContext.php
  tests/acceptance/features/login.feature
Labels: 4. to release, design, enhancement, feature: users and groups, medium, papercut, standardisation

#8569 Remove unused static sharing helper code
  apps/files_sharing/lib/Helper.php
Labels: 3. to review, feature: sharing, technical debt

#8566 Make the provisioning api app strict
  apps/provisioning_api/lib/Controller/AppConfigController.php
  apps/provisioning_api/lib/Controller/AppsController.php
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/lib/Middleware/ProvisioningApiMiddleware.php
  apps/provisioning_api/tests/Controller/AppConfigControllerTest.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 3. to review, enhancement, technical debt

#8099 [stable13] Don't perform CSRF check on OCS routes with Bearer auth
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
Labels: 3. to review, enhancement, security

#8577 [stable13] Set autocomplete=new-password for mail share password
  core/js/sharedialogshareelistview.js
Labels: 4. to release, feature: sharing

#8581 Correct mistaken regex wildcard in .htaccess
  .htaccess
  lib/private/Setup.php
Labels: 3. to review
