Repository nextcloud/server, pull requests merged in 2018-04, with the labels that each got.

#9020 [stable13] Clear any theming prefixed cache on cache buster increase
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/ThemingDefaultsTest.php
Labels: 3. to review, bug, feature: theming, regression

#9014 update icewind/smb to 2.0.5
  apps/files_external/3rdparty/.gitignore
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Connection.php
  apps/files_external/3rdparty/icewind/smb/src/Exception/InvalidArgumentException.php
  apps/files_external/3rdparty/icewind/smb/src/Parser.php
Labels: 3. to review

#9015 [stable13] Use app version to generate scss filename
  lib/private/Template/SCSSCacher.php
  tests/lib/Template/SCSSCacherTest.php
Labels: 3. to review, bug, feature: scss, high

#9019 [stable13] Fix search text overlapping close button
  core/css/styles.scss
Labels: 3. to review, bug, design, papercut

#8945 Fixed files copy/move when in favorites or recent section
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
Labels: 4. to release, backport-request, bug, feature: files, high

#9006 Do not treat is-encrypted as custom property
  apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php
Labels: 3. to review, backport-request, enhancement

#8996 Fix webdav support for OneNote clients
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
Labels: 3. to review, feature: dav

#9008 Do not fail hard if no appinfo is returned during update
  lib/private/App/AppManager.php
  lib/private/Updater.php
Labels: 4. to release, bug, feature: install and update

#9018 reset encryptionVersion to '1' if a file was stream copied
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 4. to release, backport-request, bug, feature: encryption (server-side)

#9064 [stable13] reset encryptionVersion to '1' if a file was stream copied
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 3. to review, bug, feature: encryption (server-side)

#9070 When formatting a share node an Empty target is invalid
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review, backport-request, bug, feature: sharing

#8995 Improve mountmanager
  lib/private/Files/Filesystem.php
  lib/private/Files/Mount/Manager.php
  lib/public/Files/Mount/IMountManager.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 4. to release, enhancement

#9072 [stable13] Fix proper permissions for multiple file access
  lib/private/Files/Node/Folder.php
  tests/lib/Files/Node/FolderTest.php
Labels: 3. to review, bug

#9017 [13] update icewind/smb to 2.0.5
  apps/files_external/3rdparty/.gitignore
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Connection.php
  apps/files_external/3rdparty/icewind/smb/src/Exception/InvalidArgumentException.php
  apps/files_external/3rdparty/icewind/smb/src/Parser.php
  apps/files_external/3rdparty/icewind/smb/src/Share.php
Labels: 3. to review

#9063 Move on with the next user if we found the user on one user back-end
  lib/private/User/Manager.php
Labels: 3. to review, bug

#9078 [stable12] Set new-password as autocomplete on the link password
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, bug

#9077 [stable13] Move on with the next user if we found the user on one user back-end
  lib/private/User/Manager.php
Labels: 3. to review

#9071 [stable13] Do not treat is-encrypted as custom property
  apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php
Labels: 3. to review, enhancement

#9081 Fix Array to String conversion in QueryBuilder
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 4. to release, bug

#9085 Fix progress bar hidden before the upload ends
  apps/files/js/file-upload.js
Labels: 4. to release, backport-request, bug, feature: files

#9088 [stable12] Allow usage of Windows 10 WebDav Netdrive
  lib/base.php
Labels: 4. to release, enhancement

#9082 Show the new dav url in the web UI
  apps/files/lib/Controller/ViewController.php
  apps/files/templates/appnavigation.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: 4. to release, enhancement

#9092 Add more logging for the object storage during creation of the buckets
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 3. to review

#9094 [stable13] Add more logging for the object storage during creation of the buckets
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 3. to review

#9096 Ping more privacy respecting organizations
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3. to review, enhancement

#9100 Do not convert email addresses with idn_to_ascii if INTL_IDNA_VARIANT…
  lib/private/Mail/Mailer.php
  lib/private/Mail/Message.php
Labels: 3. to review, bug, enhancement

#8904 Api: return users details by groups
  apps/provisioning_api/appinfo/routes.php
  apps/provisioning_api/composer/composer/autoload_classmap.php
  apps/provisioning_api/composer/composer/autoload_static.php
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  build/autoloaderchecker.sh
  build/integration/features/provisioning-v1.feature
Labels: 3. to review, feature: users and groups

#9095 Do not convert email addresses with idn_to_ascii if…
  lib/private/Mail/Mailer.php
  lib/private/Mail/Message.php
Labels: 4. to release, bug, enhancement

#9084 Public page template enhancements
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/css/mobile.scss
  apps/files_sharing/css/public.scss
  apps/files_sharing/js/public.js
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/templates/public.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  core/css/public.scss
  core/js/public/publicpage.js
  core/templates/layout.public.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/Http/Template/ExternalShareMenuAction.php
  lib/public/AppFramework/Http/Template/LinkMenuAction.php
  lib/public/AppFramework/Http/Template/PublicTemplateResponse.php
  tests/acceptance/features/bootstrap/FilesSharingAppContext.php
Labels: 3. to review, enhancement, feature: sharing

#8779 [stable13] Show group display names
  apps/dav/lib/CalDAV/Activity/Provider/Base.php
  apps/dav/lib/CalDAV/Activity/Provider/Calendar.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/BaseTest.php
  apps/files_sharing/lib/Activity/Providers/Groups.php
  lib/private/Group/MetaData.php
  lib/private/Settings/Personal/PersonalInfo.php
  settings/Controller/GroupsController.php
  tests/Settings/Controller/GroupsControllerTest.php
  tests/lib/Group/MetaDataTest.php
Labels: 3. to review, bug, feature: activity and notification

#9109 Always remember me
  core/Controller/LoginController.php
  core/templates/login.php
  tests/Core/Controller/LoginControllerTest.php
Labels: 3. to review, enhancement

#9118 Add video switch icon
  core/css/icons.scss
  core/img/actions/video-switch.svg
Labels: 4. to release, design, enhancement

#9115 Improve login flow
  core/Controller/ClientFlowLoginController.php
  core/routes.php
  core/templates/loginflow/authpicker.php
  core/templates/loginflow/grant.php
Labels: 3. to review, enhancement, feature: authentication

#9090 parameter provided to L10N::n() could have been a string
  apps/user_ldap/lib/Wizard.php
Labels: 3. to review, bug, feature: ldap

#9114 Make possible to provide acceptance tests for apps
  tests/acceptance/composer.json
  tests/acceptance/config/behat.yml
  tests/acceptance/run-local.sh
  tests/acceptance/run.sh
Labels: 3. to review, enhancement

#9108 Allow user creation with subadmins and quota
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review, enhancement

#7972 Use zip32 if possible
  .drone.yml
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/Download.php
  build/integration/features/download.feature
  build/integration/run.sh
  lib/private/Streamer.php
  lib/private/legacy/files.php
Labels: 3. to review, enhancement

#9111 Return proper boolean and do not save enabled state in db
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  lib/private/User/User.php
  lib/public/IUser.php
  tests/lib/User/UserTest.php
Labels: 2. developing, bug

#9127 Make possible to run acceptance tests on Apache
  .drone.yml
  tests/acceptance/features/core/NextcloudTestServerContext.php
  tests/acceptance/features/core/NextcloudTestServerLocalApacheHelper.php
  tests/acceptance/features/core/NextcloudTestServerLocalBuiltInHelper.php
  tests/acceptance/run-local.sh
  tests/acceptance/run.sh
Labels: 3. to review, enhancement

#9002 More whitespace: Increase header height from 45px to 50
  core/css/header.scss
  core/css/mobile.scss
  core/css/styles.scss
  core/js/js.js
Labels: 3. to review, design, enhancement

#9130 Fix AppFetcher::setVersion phpdoc
  lib/private/App/AppStore/Fetcher/AppFetcher.php
Labels: 4. to release, bug

#9132 Replace the ajax navigationdetect endpoint with the new one from NavigationController
  settings/ajax/navigationdetect.php
  settings/js/apps.js
  settings/routes.php
Labels: 3. to review, technical debt

#9073 [stable13] When formatting a share node an Empty target is invalid
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review, bug, feature: sharing

#9128 Also make the uid_lower migration work on oracle
  core/Migrations/Version14000Date20180404140050.php
Labels: 4. to release, bug

#8833 add anounce- and (pre/|post)RevokeUser signals for non-native backends
  apps/admin_audit/lib/Actions/UserManagement.php
  apps/admin_audit/lib/AppInfo/Application.php
  apps/dav/lib/HookManager.php
  apps/user_ldap/ajax/clearMappings.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/AccessFactory.php
  apps/user_ldap/lib/Jobs/Sync.php
  apps/user_ldap/lib/Jobs/UpdateGroups.php
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/lib/Proxy.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/Mapping/AbstractMappingTest.php
  lib/private/User/Manager.php
  lib/private/User/Session.php
  lib/public/IUserManager.php
Labels: 3. to review, enhancement, feature: ldap, feature: users and groups

#8910 Avoid to leak a user ID that is not a string to reach a user backend
  core/Controller/LoginController.php
Labels: 4. to release

#9137 Set the default log rotate size to 100 MB
  config/config.sample.php
  core/Command/Log/File.php
  lib/private/Log/Rotate.php
  tests/Core/Command/Log/FileTest.php
Labels: 4. to release, enhancement

#9136 The integrationtests expect a string
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 4. to release, bug

#9074 Add ARGON2I support to the hasher
  lib/private/Security/Hasher.php
  tests/lib/Security/HasherTest.php
Labels: 3. to review, enhancement, security

#9143 Disable unreliable swift tests
  .drone.yml
Labels: 4. to release

#8946 Log exceptions as nested array instead of encoded json
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
  lib/private/Log.php
  lib/private/Log/File.php
  tests/lib/LoggerTest.php
Labels: 3. to review

#9147 log previous exception
  lib/private/Log.php
Labels: 3. to review

#7800 Fixes the usability issues with the comment section delete and edit
  apps/comments/css/comments.scss
  apps/comments/js/commentsmodifymenu.js
  apps/comments/js/commentstabview.js
  apps/comments/js/merged.json
  apps/comments/tests/js/commentstabviewSpec.js
  tests/karma.config.js
Labels: 3. to review, design, enhancement

#9024 Fix version comparison with minor and patch level requirements
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/CompareVersion.php
  tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
  tests/lib/App/CompareVersionTest.php
Labels: 3. to review, bug, feature: apps management

#9097 Use multibyte substring
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, backport-request, bug

#9148 transform exception during file read to sabre exceptions
  apps/dav/lib/Connector/Sabre/File.php
Labels: 4. to release

#9145 Add auth token to github requests
  .drone.yml
  build/signed-off-checker.php
Labels: 4. to release

#8452 Descend into newly created folder by clicking enter again
  apps/files/js/filelist.js
Labels: 3. to review, design, papercut

#8820 Sorts filepicker files by modified date
  core/js/oc-dialogs.js
Labels: 3. to review, enhancement

#9134 dont keep shared database locks when running cli scripts
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/Lock/DBLockingProvider.php
  lib/private/Server.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
  tests/lib/Lock/DBLockingProviderTest.php
  tests/lib/Lock/NonCachingDBLockingProviderTest.php
Labels: 3. to review

#8535 New color generator algorithm
  core/js/placeholder.js
  lib/private/Avatar.php
Labels: 3. to review, design, enhancement, papercut

#9164 Fix autoloader
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Avatar.php
  lib/private/Color.php
Labels: 3. to review

#9172 Fix js tests with placeholder
  core/js/placeholder.js
Labels: 3. to review, bug, high, regression

#9168 Return proper boolean user enabled state api
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  build/integration/features/bootstrap/Provisioning.php
Labels: 3. to review

#9205 Provide an option to disable HTML emails
  config/config.sample.php
  lib/private/Mail/Mailer.php
  lib/private/Mail/Message.php
  tests/lib/Mail/MailerTest.php
  tests/lib/Mail/MessageTest.php
Labels: 4. to release, backport-request, enhancement

#9206 Fix user selectable text for public links for text files
  apps/files_sharing/css/public.scss
Labels: 3. to review, backport-request

#9184 Fixes issue with the large cursor on Safari in the comment section.
  apps/comments/css/comments.scss
Labels: 3. to review

#9162 Add language support for user creation
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 4. to release

#9203 Declare func() as safe method in phan
  build/.phan/plugin-checker.php
  build/.phan/plugins/SqlInjectionCheckerPlugin.php
Labels: 3. to review

#9159 fix appinfo parsing when a single localized option is provided
  lib/private/legacy/app.php
  tests/data/app/description-multi-lang.xml
  tests/data/app/description-single-lang.xml
  tests/lib/AppTest.php
Labels: 4. to release

#9214 [stable12] Update CRL to include old quicknotes cert
  resources/codesigning/root.crl
Labels: 3. to review, security

#9177 Log classnames of arguments in exception trace
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Log.php
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review

#9211 Update CRL to include old quicknotes cert
  resources/codesigning/root.crl
Labels: 3. to review, security

#9213 [stable13] Update CRL to include old quicknotes cert
  resources/codesigning/root.crl
Labels: 3. to review, security

#9174 log more information about insufficient storage in dav plugin
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
Labels: 3. to review

#9218 Move personal settings to css grid layout
  settings/css/settings.scss
  settings/templates/settings/personal/personal.info.php
Labels: 3. to review, design, enhancement

#9234 [stable13] Use multibyte substring
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review

#9230 [stable13] Fix user selectable text for public links for text files
  apps/files_sharing/css/public.scss
Labels: 3. to review

#9235 [stable12] Use multibyte substring
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review

#8987 [stable12] Show EOL warning in the update section
  apps/updatenotification/css/admin.css
  apps/updatenotification/lib/Controller/AdminController.php
  apps/updatenotification/lib/UpdateChecker.php
  apps/updatenotification/templates/admin.php
  apps/updatenotification/tests/Controller/AdminControllerTest.php
  apps/updatenotification/tests/UpdateCheckerTest.php
  lib/private/Updater/VersionCheck.php
  tests/lib/Updater/VersionCheckTest.php
Labels: 3. to review, enhancement, feature: install and update

#8986 [stable13] Show EOL warning in the update section
  apps/updatenotification/css/admin.css
  apps/updatenotification/lib/Controller/AdminController.php
  apps/updatenotification/lib/UpdateChecker.php
  apps/updatenotification/templates/admin.php
  apps/updatenotification/tests/Controller/AdminControllerTest.php
  apps/updatenotification/tests/UpdateCheckerTest.php
  lib/private/Updater/VersionCheck.php
  tests/lib/Updater/VersionCheckTest.php
Labels: 3. to review, enhancement, feature: install and update

#9233 [stable13] fix appinfo parsing when a single localized option is provided
  lib/private/legacy/app.php
  tests/data/app/description-multi-lang.xml
  tests/data/app/description-single-lang.xml
  tests/lib/AppTest.php
Labels: 3. to review

#9106 Run federated discoverjob in cron
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/BackgroundJob/FederatedSharesDiscoverJob.php
  lib/private/OCS/DiscoveryService.php
  lib/public/OCS/IDiscoveryService.php
Labels: 3. to review, enhancement, feature: federation, feature: sharing

#9231 [stable13] Provide an option to disable HTML emails
  config/config.sample.php
  lib/private/Mail/Mailer.php
  lib/private/Mail/Message.php
  tests/lib/Mail/MailerTest.php
  tests/lib/Mail/MessageTest.php
Labels: 3. to review

#9236 [stable13] Fix webdav support for OneNote clients
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
Labels: 3. to review

#9238 [stable13] Fixed files copy/move when in favorites or recent section
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
Labels: 3. to review

#9232 [stable12] Provide an option to disable HTML emails
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
  config/config.sample.php
  lib/private/Mail/Mailer.php
  lib/private/Mail/Message.php
  tests/lib/Mail/MailerTest.php
  tests/lib/Mail/MessageTest.php
Labels: 4. to release

#9228 13.0.2 RC 1
  version.php
Labels: 3. to review

#9229 12.0.7 RC 1
  version.php
Labels: 3. to review

#9237 Fix ids of permission checkboxes for shares
  core/js/sharedialogshareelistview.js
  core/js/tests/specs/sharedialogshareelistview.js
Labels: 3. to review, backport-request, bug, feature: sharing

#9224 Add labels for Contacts menu and Settings, thanks to @MarcoZehe
  apps/files/css/detailsView.scss
  apps/files/css/files.scss
  apps/files/js/filelist.js
  core/css/variables.scss
  core/js/js.js
  core/templates/layout.base.php
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
  core/templates/login.php
Labels: 3. to review, bug, design

#9254 Also adjust app sidebar offset to new header height
  core/css/apps.scss
Labels: 3. to review, bug, design

#9225 Allow IPv6 database hosts
  lib/private/DB/ConnectionFactory.php
  tests/lib/DB/ConnectionFactoryTest.php
Labels: 3. to review, backport-request, bug, feature: install and update

#9129 Add proper comment offset support
  lib/private/Comments/Manager.php
  lib/public/Comments/ICommentsManager.php
  tests/lib/Comments/FakeManager.php
  tests/lib/Comments/ManagerTest.php
Labels: 3. to review, enhancement, feature: comments

#9255 Less deprecated calls to OCP\Util::writeLog
  apps/dav/lib/Connector/Sabre/File.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/files_external/lib/Service/LegacyStoragesService.php
  apps/files_sharing/lib/ShareBackend/File.php
  apps/files_sharing/lib/SharedMount.php
  apps/files_trashbin/lib/Trashbin.php
  apps/files_versions/lib/Storage.php
  cron.php
Labels: 3. to review, technical debt

#9245 Fix race condition when preparing upload folder
  apps/files/js/file-upload.js
Labels: 3. to review, backport-request, bug, feature: files

#9269 Fix DI for federated file sharing controller
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/tests/Controller/RequestHandlerControllerTest.php
Labels: 4. to release, technical debt

#9275 Make the group backends also possible using interfaces
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Group/Database.php
  lib/public/Group/Backend/ABackend.php
  lib/public/Group/Backend/IAddToGroupBackend.php
  lib/public/Group/Backend/ICountUsersBackend.php
  lib/public/Group/Backend/ICreateGroupBackend.php
  lib/public/Group/Backend/IDeleteGroupBackend.php
  lib/public/Group/Backend/IGroupDetailsBackend.php
  lib/public/Group/Backend/IIsAdminBackend.php
  lib/public/Group/Backend/IRemoveFromGroupBackend.php
Labels: 4. to release, enhancement, technical debt

#9271 Fix undefined variable - found by Phan
  lib/private/Files/ObjectStore/SwiftFactory.php
  lib/private/Files/Storage/DAV.php
  lib/private/Installer.php
Labels: 3. to review, backport-request, bug

#9276 Remove unused config option
  config/config.sample.php
Labels: 4. to release

#9272 Only query last comment info, when there is one
  lib/private/Comments/Manager.php
Labels: 3. to review, bug, feature: comments

#9278 Access needs UserManager, missed to add in #8833
  apps/user_ldap/ajax/wizard.php
  apps/user_ldap/lib/Access.php
Labels: 4. to release, bug, feature: ldap

#9280 Swift v3 requires setting a scope
  config/config.sample.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review, bug

#9287 [swift] Swift v3 requires setting a scope
  config/config.sample.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review, bug

#9282 Make the ShareAPIController strict
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: 3. to review, bug, feature: sharing

#9292 Cast retrieved DB fields to string
  lib/private/User/Database.php
Labels: 4. to release, bug

#9248 Fix ellipsis in filename column
  apps/files/css/files.scss
  apps/files/css/mobile.scss
Labels: 4. to release, backport-request, bug, design, high

#8540 Add option for header logo and favicon in theming app
  apps/theming/appinfo/routes.php
  apps/theming/css/settings-admin.css
  apps/theming/css/settings-admin.scss
  apps/theming/css/theming.scss
  apps/theming/js/settings-admin.js
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/ImageManager.php
  apps/theming/lib/Settings/Admin.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/templates/settings-admin.php
  apps/theming/tests/Controller/IconControllerTest.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/ImageManagerTest.php
  apps/theming/tests/Settings/AdminTest.php
  apps/theming/tests/ThemingDefaultsTest.php
  lib/private/Server.php
Labels: 3. to review, enhancement, feature: theming

#9284 Make ShareesAPIController strict
  apps/files_sharing/lib/Controller/ShareesAPIController.php
Labels: 3. to review, bug, feature: sharing

#9296 Migrate groups fetch to ocs api
  apps/workflowengine/js/admin.js
  settings/js/settings.js
Labels: 4. to release, feature: settings, feature: users and groups

#9256 improve error reporting and move format parameter to the options
  apps/federation/lib/BackgroundJob/GetSharedSecret.php
  apps/federation/lib/BackgroundJob/RequestSharedSecret.php
  apps/federation/lib/Controller/OCSAuthAPIController.php
  apps/federation/tests/BackgroundJob/GetSharedSecretTest.php
  apps/federation/tests/BackgroundJob/RequestSharedSecretTest.php
  apps/federation/tests/Controller/OCSAuthAPIControllerTest.php
Labels: 4. to release, backport-request, feature: federation

#9301 12.0.7
  version.php
Labels: 3. to review

#9302 Improve phan config
  build/.phan/config.php
Labels: 3. to review

#9323 [swift] Better swift V3 token handling
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review

#9322 Better swift V3 token handling
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review, backport-request, bug

#9321 Actually return the root folder when traversing up the tree
  lib/private/Files/Node/Node.php
Labels: 3. to review, bug, enhancement

#9325 Fix for unbound cloned LDAP connections
  apps/user_ldap/lib/Connection.php
Labels: 3. to review, backport-request, bug, feature: ldap

#9309 Do not add sharePermission logic in JS
  apps/files_sharing/js/share.js
  apps/files_sharing/tests/js/sharedfilelistSpec.js
  core/js/files/client.js
  core/js/files/fileinfo.js
Labels: 3. to review, enhancement, feature: sharing

#9348 Replace deprecated sinon reset() call with resetHistory()
  settings/tests/js/users/deleteHandlerSpec.js
Labels: 4. to release, backport-request, bug
