Repository nextcloud/server, pull requests merged in 2018-06, with the labels that each got.

#9550 allow admins to disable FreeBusy without modifying ShareAPI capabilities
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_versions/lib/AppInfo/Application.php
Labels: 3. to review, backport-request

#9707 [stable13] allow admins to override FreeBusy capabilities without modifying ShareAPI capabilities
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
Labels: 3. to review

#9695 [stable12] Make sure the log doesn't try to read from PUT if it can't
  lib/private/Log.php
Labels: 3. to review, bug

#9694 [stable13] Make sure the log doesn't try to read from PUT if it can't
  lib/private/Log.php
Labels: 3. to review, bug

#9610 [stable13] send invitations for shared calendars
  apps/dav/lib/CalDAV/Schedule/Plugin.php
Labels: 3. to review

#9611 [stable12] send invitations for shared calendars
  apps/dav/lib/CalDAV/Schedule/Plugin.php
Labels: 3. to review

#9609 send invitations for shared calendars
  apps/dav/lib/CalDAV/Schedule/Plugin.php
Labels: 3. to review

#9702 12.0.8 RC 1
  .drone.yml
  version.php
Labels: 4. to release

#9711 Fix the master unit tests
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: 4. to release

#9712 [stable13] Fix the unit tests
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: 3. to review

#9700 13.0.3 RC 1
  version.php
Labels: 4. to release

#9542 Add sabre plugin to allow anonymous options requests to the dav root
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/DAV/AnonymousOptionsTest.php
Labels: 3. to review

#9425 Check connection status and attempt to reconnect each each minute
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/DB/Connection.php
  lib/private/DB/ReconnectWrapper.php
Labels: 3. to review

#9727 [stable13] Fix header nav
  core/css/header.scss
Labels: 3. to review, bug, design, regression

#9725 Fix local users check in contacts menu
  lib/private/Contacts/ContactsMenu/ContactsStore.php
Labels: 3. to review, bug, feature: contacts menu

#9721 Add referrer policy setup check
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review, enhancement

#9724 Add parent index to share table
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review, backport-request, enhancement, feature: sharing

#9732 [stable13] Fix local users check in contacts menu
  lib/private/Contacts/ContactsMenu/ContactsStore.php
Labels: 3. to review

#9731 13.0.3 RC 2
  version.php
Labels: 4. to release

#9692 Make sure the log doesn't try to read from PUT if it can't
  lib/private/Log.php
Labels: 3. to review, bug

#9735 Add a hint that some indexes are not added yet
  core/Application.php
  core/js/setupchecks.js
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/DB/MissingIndexInformation.php
  lib/public/IDBConnection.php
  settings/Controller/CheckSetupController.php
  settings/css/settings.scss
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 4. to release, enhancement, feature: settings, papercut

#9565 Migrate apps management to Vue.js
  lib/private/App/AppManager.php
  lib/private/legacy/app.php
  lib/public/App/IAppManager.php
  settings/Controller/AppSettingsController.php
  settings/ajax/disableapp.php
  settings/ajax/enableapp.php
  settings/ajax/uninstallapp.php
  settings/ajax/updateapp.php
  settings/css/settings.scss
  settings/js/apps.js
  settings/js/main.js
  settings/routes.php
  settings/src/components/appDetails.vue
  settings/src/components/appList.vue
  settings/src/components/appList/appItem.vue
  settings/src/components/appList/appScore.vue
  settings/src/components/appManagement.vue
  settings/src/components/appNavigation.vue
  settings/src/components/prefixMixin.vue
  settings/src/router.js
  settings/src/store/apps.js
  settings/src/store/index.js
  settings/src/store/users.js
  settings/src/views/Apps.vue
  settings/templates/apps.php
  settings/tests/js/appsSpec.js
  tests/Settings/Controller/AppSettingsControllerTest.php
Labels: 3. to review, enhancement, feature: apps management

#9768 Fix style of password button on protected link shares
  core/css/guest.css
Labels: 3. to review, design, papercut

#9771 Missing svg filter mixin for apps management
  settings/src/components/svgFilterMixin.vue
Labels: 4. to release, bug, feature: apps management

#9762 Add visual indicator for setup checks
  settings/css/settings.scss
  settings/js/admin.js
  settings/templates/settings/admin/overview.php
Labels: 4. to release, design, feature: settings, papercut

#9766 Add vue apps build tests
  .drone.yml
  .gitignore
  apps/updatenotification/Makefile
  apps/updatenotification/js-src/app.js
  apps/updatenotification/js-src/components/root.vue
  apps/updatenotification/js-src/init.js
  apps/updatenotification/js-src/webpack.common.js
  apps/updatenotification/js-src/webpack.config.js
  apps/updatenotification/js-src/webpack.dev.js
  apps/updatenotification/js-src/webpack.prod.js
  apps/updatenotification/js/merged.js
  apps/updatenotification/js/merged.js.map
  apps/updatenotification/package-lock.json
  apps/updatenotification/package.json
  build/vue-builds.sh
  settings/js/main.js
  settings/js/main.js.map
  settings/package-lock.json
  settings/package.json
  settings/webpack.common.js
Labels: 3. to review, bug, enhancement, feature: dependencies, feature: vue apps, regression

#9778 13.0.3
  version.php
Labels: 4. to release

#9779 12.0.8
  version.php
Labels: 4. to release

#9780 Mock the timefactory in the theming tests
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/tests/Controller/ThemingControllerTest.php
Labels: 4. to release, enhancement

#9616 Allow 0 quota by provisioning api
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/UsersController.php
  lib/private/Files/Storage/Wrapper/Quota.php
  settings/js/main.js
  settings/js/main.js.map
  settings/src/components/userList.vue
  settings/src/components/userList/userRow.vue
  settings/src/store/users.js
  settings/src/views/Users.vue
  tests/acceptance/features/users.feature
Labels: 3. to review, bug, feature: users and groups, regression

#9772 Move samesite cookie opt-out to config.php
  config/config.sample.php
  lib/base.php
Labels: 3. to review, enhancement

#9787 allow setting notify credentials in environment
  apps/files_external/lib/Command/Notify.php
Labels: 3. to review

#9788 [13] allow setting notify credentials in environment
  apps/files_external/lib/Command/Notify.php
Labels: 3. to review

#9793 Fix mentions regex
  lib/private/Comments/Comment.php
  tests/lib/Comments/CommentTest.php
Labels: 4. to release, feature: comments

#9803 [stable13] Make the token expiration also work for autocasting 0
  lib/private/Authentication/Token/DefaultTokenProvider.php
Labels: 3. to review, bug

#9798 enable caldav for webdav subtree public-calendars
  apps/dav/lib/Server.php
Labels: 3. to review

#9804 [stable12] Make the token expiration also work for autocasting 0
  lib/private/Authentication/Token/DefaultTokenProvider.php
Labels: 3. to review, bug

#9807 Fix highlighting of the upload drop zone
  apps/files/js/file-upload.js
  apps/files/js/jquery.fileupload.js
Labels: 3. to review, backport-request, bug, feature: files

#9810 Acceptance tests for apps management and minor fixes
  .drone.yml
  settings/Controller/AppSettingsController.php
  settings/js/main.js
  settings/js/main.js.map
  settings/src/components/appList.vue
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apps.feature
  tests/acceptance/features/bootstrap/AppsManagementContext.php
  tests/acceptance/features/bootstrap/SettingsMenuContext.php
  tests/acceptance/run.sh
Labels: 3. to review, bug, feature: apps management

#9814 Make the DELETION of groups match greedy on the groupID
  apps/provisioning_api/appinfo/routes.php
Labels: 3. to review, bug

#9820 [stable13] enable caldav for webdav subtree public-calendars
  apps/dav/lib/Server.php
Labels: 4. to release, bug, feature: dav

#9821 13.0.4
  version.php
Labels: 4. to release

#9822 12.0.9
  version.php
Labels: 4. to release

#9558 Previews on for all trashbin files
  apps/files_trashbin/appinfo/routes.php
  apps/files_trashbin/js/filelist.js
  apps/files_trashbin/lib/Controller/PreviewController.php
  apps/files_trashbin/lib/Helper.php
  apps/files_trashbin/tests/Controller/PreviewControllerTest.php
Labels: 3. to review, enhancement, feature: previews and thumbnails, feature: trashbin

#9473 properly lock the target file on dav upload when not using part files
  apps/dav/lib/Connector/Sabre/File.php
Labels: 2. developing

#9828 Fix listing s3 objects when using google cloud aws compatibility
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 3. to review

#9841 [stable13] Make the DELETION of groups match greedy on the groupID
  apps/provisioning_api/appinfo/routes.php
Labels: 3. to review, bug

#9842 [stable12] Make the DELETION of groups match greedy on the groupID
  apps/provisioning_api/appinfo/routes.php
Labels: 3. to review, bug

#9844 [stable13] Remove unused config option
  config/config.sample.php
Labels: 3. to review

#9845 [stable12] Remove unused config option
  config/config.sample.php
Labels: 3. to review

#9839 [stable13] Apply ldapUserFilter on members of group
  apps/user_ldap/lib/Access.php
Labels: bug, feature: ldap

#9837 [stable13] Fix highlighting of the upload drop zone
  apps/files/js/file-upload.js
  apps/files/js/jquery.fileupload.js
Labels: 3. to review, bug, feature: files

#9850 Fix wrong hint about missing indexes
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  lib/private/DB/MissingIndexInformation.php
  settings/Controller/CheckSetupController.php
Labels: 4. to release, bug

#9836 Merge tips & tricks section into setup checks
  core/js/setupchecks.js
  core/js/tests/specHelper.js
  core/js/tests/specs/setupchecksSpec.js
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Settings/Admin/TipsTricks.php
  lib/private/Settings/Manager.php
  settings/Controller/CheckSetupController.php
  settings/css/settings.scss
  settings/templates/settings/admin/overview.php
  settings/templates/settings/admin/tipstricks.php
  tests/Settings/Controller/AdminSettingsControllerTest.php
  tests/Settings/Controller/CheckSetupControllerTest.php
  tests/lib/Settings/Admin/TipsTricksTest.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, papercut

#9852 Merge all setup checks into one controller
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  lib/private/Settings/Admin/Overview.php
  lib/private/Settings/Manager.php
  settings/Controller/CheckSetupController.php
  settings/css/settings.scss
  settings/templates/settings/admin/overview.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3. to review, enhancement, feature: settings

#9855 Background job to clean up old backups of the updater
  core/BackgroundJobs/BackgroundCleanupUpdaterBackupsJob.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/AddCleanupUpdaterBackupsJob.php
Labels: 4. to release, enhancement, feature: install and update

#9859 Fix possible test timing issues in IconController
  apps/theming/lib/Controller/IconController.php
  apps/theming/tests/Controller/IconControllerTest.php
Labels: 3. to review

#9873 Fix HTTP client given options being overriden by default options
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 3. to review, bug, regression

#9875 Fix #9864: Decrease $maxDelay in Throttler.php
  lib/private/Security/Bruteforce/Throttler.php
Labels: 3. to review, enhancement, papercut, security

#9197 Fix avatar generator centering
  core/Controller/AvatarController.php
  core/js/placeholder.js
  lib/private/Avatar.php
  lib/public/IAvatar.php
  tests/lib/AvatarTest.php
Labels: 4. to release, bug, design, feature: previews and thumbnails, regression

#9258 Convert theming app logo to PNG to show it properly in emails
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/IconBuilder.php
  apps/theming/lib/ImageManager.php
  apps/theming/lib/Settings/Admin.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/Controller/IconControllerTest.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/IconBuilderTest.php
  apps/theming/tests/ImageManagerTest.php
  apps/theming/tests/ThemingDefaultsTest.php
  lib/private/Server.php
Labels: 3. to review, enhancement, feature: theming

#9883 Return groups IDs and not Names
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 4. to release, bug, feature: users and groups, high, regression

#9717 New Feature/actions file menu
  apps/files/css/files.scss
  apps/files/css/mobile.scss
  apps/files/js/app.js
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
  apps/files/js/filemultiselectmenu.js
  apps/files/js/merged-index.json
  apps/files/templates/list.php
  apps/files/templates/recentlist.php
  apps/files/templates/simplelist.php
  apps/files/tests/js/filelistSpec.js
  apps/files_trashbin/js/app.js
  apps/files_trashbin/js/filelist.js
  apps/files_trashbin/templates/index.php
  apps/files_trashbin/tests/js/filelistSpec.js
  core/css/mobile.scss
Labels: 4. to release, design, feature: files, papercut

#9884 Add search to users details groups
  apps/provisioning_api/lib/Controller/GroupsController.php
  lib/private/Group/Group.php
  tests/lib/Group/GroupTest.php
Labels: 3. to review, enhancement, feature: users and groups, papercut

#9893 Update message shown when unsharing a file
  apps/files_sharing/lib/Activity/Providers/Users.php
Labels: 4. to release, backport-request

#9914 Fixed English grammatical error on Settings page - template
  settings/templates/settings/personal/personal.info.php
Labels: 3. to review, enhancement

#9881 use query builder in all places in the db user backend
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/User/Database.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
Labels: 3. to review

#9843 [stable13] Add parent index to share table
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review, enhancement

#9920 If cronErros is empty json_decode will return NULL
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 4. to release, bug, enhancement

#9919 Don't pretend we can add/remove users to/from groups when we can't
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
  core/css/inputs.scss
  lib/private/Group/Group.php
  lib/private/Group/MetaData.php
  lib/public/IGroup.php
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/userList.vue
  settings/src/components/userList/userRow.vue
Labels: 4. to release

#9912 New search standard and user search
  .drone.yml
  apps/files/css/files.scss
  apps/files/js/search.js
  core/css/styles.scss
  core/img/actions/checkmark-color.svg
  core/search/css/results.css
  core/search/css/results.scss
  core/search/js/search.js
  core/search/js/searchprovider.js
  core/search/templates/part.results.html
  core/templates/layout.user.php
  lib/private/legacy/template.php
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/userList.vue
  settings/src/main.js
  settings/src/views/Apps.vue
Labels: 4. to release, enhancement, feature: search, feature: users and groups

#9930 Add vue build for oauth2 app to drone
  .drone.yml
  .gitignore
  apps/oauth2/Makefile
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/oauth2/package-lock.json
  apps/oauth2/package.json
  apps/oauth2/webpack.common.js
  apps/oauth2/webpack.dev.js
  apps/oauth2/webpack.prod.js
Labels: 4. to release, feature: vue apps

#9900 Wait for cron to finish before running upgrade command
  core/Command/Upgrade.php
  core/ajax/update.php
  lib/private/BackgroundJob/JobList.php
  lib/private/Updater.php
  tests/lib/UpdaterTest.php
Labels: 3. to review, backport-request, feature: install and update

#9723 Css4 variables migration
  apps/comments/css/autocomplete.scss
  apps/comments/css/comments.scss
  apps/files/css/detailsView.scss
  apps/files/css/files.scss
  apps/files/css/upload.scss
  apps/files_sharing/css/public.scss
  apps/theming/css/settings-admin.scss
  apps/theming/css/theming.scss
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/ThemingDefaultsTest.php
  core/css/apps.scss
  core/css/css-variables.scss
  core/css/fixes.scss
  core/css/fonts.scss
  core/css/header.scss
  core/css/icons.scss
  core/css/inputs.scss
  core/css/jquery-ui-fixes.scss
  core/css/jquery.ocdialog.scss
  core/css/mobile.scss
  core/css/multiselect.scss
  core/css/public.scss
  core/css/share.scss
  core/css/styles.scss
  core/css/tooltip.scss
  core/css/variables.scss
  core/js/core.json
  core/js/js.js
  core/vendor/.gitignore
  core/vendor/css-vars-ponyfill/LICENSE
  core/vendor/css-vars-ponyfill/dist/css-vars-ponyfill.min.js
  core/vendor/css-vars-ponyfill/dist/css-vars-ponyfill.min.js.map
  lib/private/legacy/template.php
  settings/css/settings.scss
  settings/templates/settings/frame.php
  settings/templates/settings/personal/personal.info.php
  tests/acceptance/features/app-theming.feature
  tests/acceptance/features/bootstrap/SettingsMenuContext.php
  tests/acceptance/features/bootstrap/ThemingAppContext.php
Labels: 4. to release, enhancement, feature: scss

#9518 Public share middleware & controller
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/js/public.js
  apps/files_sharing/lib/Controller/PublicPreviewController.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/lib/Middleware/SharingCheckMiddleware.php
  apps/files_sharing/tests/Controller/PublicPreviewControllerTest.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  apps/files_sharing/tests/Middleware/SharingCheckMiddlewareTest.php
  core/css/publicshareauth.css
  core/js/publicshareauth.js
  core/templates/publicshareauth.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/PublicShare/Exceptions/NeedAuthenticationException.php
  lib/private/AppFramework/Middleware/PublicShare/PublicShareMiddleware.php
  lib/private/legacy/template/functions.php
  lib/public/AppFramework/AuthPublicShareController.php
  lib/public/AppFramework/PublicShareController.php
  tests/acceptance/features/bootstrap/FilesSharingAppContext.php
  tests/lib/AppFramework/Controller/AuthPublicShareControllerTest.php
  tests/lib/AppFramework/Controller/PublicShareControllerTest.php
  tests/lib/AppFramework/Middleware/PublicShare/PublicShareMiddlewareTest.php
Labels: 4. to release, enhancement, feature: sharing

#9941 Add browserstack logo
  README.md
Labels: 3. to review

#9946 Fix files_external settings layout
  apps/files_external/css/settings.scss
  apps/files_external/templates/settings.php
Labels: 4. to release, design, feature: external storage, papercut

#9951 Fix navigation keyboard accessibility
  core/css/apps.scss
Labels: 3. to review, bug, design, feature: accessibility

#9925 Select only searched files
  apps/files/js/filelist.js
Labels: 3. to review, bug, feature: search, high

#9868 make table name configurable for db user backend
  lib/private/User/Database.php
Labels: 3. to review

#9578 update icewind/smb to 3.0.0
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/README.md
  apps/files_external/3rdparty/icewind/smb/composer.json
  apps/files_external/3rdparty/icewind/smb/src/AbstractServer.php
  apps/files_external/3rdparty/icewind/smb/src/AnonymousAuth.php
  apps/files_external/3rdparty/icewind/smb/src/BasicAuth.php
  apps/files_external/3rdparty/icewind/smb/src/IAuth.php
  apps/files_external/3rdparty/icewind/smb/src/IFileInfo.php
  apps/files_external/3rdparty/icewind/smb/src/IServer.php
  apps/files_external/3rdparty/icewind/smb/src/KerberosAuth.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeReadStream.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeServer.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeStream.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeWriteStream.php
  apps/files_external/3rdparty/icewind/smb/src/Server.php
  apps/files_external/3rdparty/icewind/smb/src/ServerFactory.php
  apps/files_external/3rdparty/icewind/smb/src/System.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Connection.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/ErrorCodes.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/FileInfo.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/NotifyHandler.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Parser.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/RawConnection.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Server.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php
  apps/files_external/lib/Lib/Storage/SMB.php
  apps/files_external/tests/Service/StoragesServiceTest.php
Labels: 2. developing

#9954 Prevent search form submit
  core/search/js/search.js
Labels: 3. to review, bug, feature: search, regression

#9921 prefill userid for login after password reset
  core/Controller/LostController.php
  core/js/lostpassword.js
  tests/Core/Controller/LostControllerTest.php
Labels: 3. to review

#9958 [stable13] Log full exception in cron instead of only the message
  cron.php
Labels: 4. to release

#9962 Added icons to users list and improved design
  core/css/icons.scss
  core/img/actions/disabled-user.svg
  core/img/actions/disabled-users.svg
  core/img/actions/user-admin.svg
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/appNavigation/navigationItem.vue
  settings/src/views/Users.vue
Labels: 3. to review, design, enhancement, feature: users and groups, papercut

#9964 Use ellipsis instead of triple dot
  core/Command/Upgrade.php
  core/ajax/update.php
Labels: 3. to review

#9965 Use info log level to inform about a deleted user and thus the verification is not needed anymore
  settings/BackgroundJobs/VerifyUserData.php
Labels: 3. to review

#9955 Request a valid property for DAV opendir
  lib/private/Files/Storage/DAV.php
Labels: 3. to review, backport-request, bug

#9967 Replace "wd_host" directly in "behat.yml" instead of through "BEHAT_PARAMS"
  tests/acceptance/config/behat.yml
  tests/acceptance/run-local.sh
Labels: 3. to review

#9526 allow shallow (non-recursive) scan when scanning file storage
  apps/files/lib/Command/Scan.php
  lib/private/Files/Utils/Scanner.php
  tests/lib/Files/Utils/ScannerTest.php
Labels: 3. to review, enhancement, feature: files, feature: occ

#9970 Fixed multi line in users list
  settings/css/settings.scss
  settings/js/settings-vue.js.map
  settings/src/components/userList/userRow.vue
Labels: 3. to review, bug, design, feature: users and groups

#9632 Stateful 2fa providers
  core/Command/TwoFactorAuth/State.php
  core/Controller/LoginController.php
  core/Controller/TwoFactorChallengeController.php
  core/Migrations/Version14000Date20180522074438.php
  core/register_command.php
  core/templates/twofactorselectchallenge.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  lib/private/Authentication/TwoFactorAuth/ProviderLoader.php
  lib/private/Authentication/TwoFactorAuth/ProviderSet.php
  lib/private/Authentication/TwoFactorAuth/Registry.php
  lib/private/Server.php
  lib/public/Authentication/TwoFactorAuth/IRegistry.php
  tests/Core/Controller/LoginControllerTest.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
  tests/lib/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDaoTest.php
  tests/lib/Authentication/TwoFactorAuth/ManagerTest.php
  tests/lib/Authentication/TwoFactorAuth/ProviderLoaderTest.php
  tests/lib/Authentication/TwoFactorAuth/ProviderSetTest.php
  tests/lib/Authentication/TwoFactorAuth/RegistryTest.php
  version.php
Labels: 4. to release, enhancement, feature: authentication

#9626 Workaround for interrupting expired files deletion
  apps/files_trashbin/lib/Trashbin.php
Labels: 3. to review, feature: trashbin

#9977 No more extra padding for the app settings
  core/css/apps.scss
Labels: 3. to review, design, enhancement, papercut

#9956 Add focus indicator to File Details tabs view
  apps/files/js/detailsview.js
  core/css/apps.scss
Labels: 4. to release, bug, design, feature: accessibility

#9991 Use a placeholder instead of magic string concatenation
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/appDetails.vue
Labels: 4. to release, bug, feature: language l10n and translations

#9862 Accessibility ♿
  .drone.yml
  .gitignore
  apps/accessibility/.babelrc
  apps/accessibility/.editorconfig
  apps/accessibility/.eslintrc.js
  apps/accessibility/.gitignore
  apps/accessibility/.jshintrc
  apps/accessibility/Makefile
  apps/accessibility/README.md
  apps/accessibility/appinfo/app.php
  apps/accessibility/appinfo/info.xml
  apps/accessibility/appinfo/routes.php
  apps/accessibility/css/fontdyslexic.scss
  apps/accessibility/css/style.scss
  apps/accessibility/css/themedark.scss
  apps/accessibility/css/themehighcontrast.scss
  apps/accessibility/fonts/OpenDyslexic-Bold.ttf
  apps/accessibility/fonts/OpenDyslexic-Bold.woff
  apps/accessibility/fonts/OpenDyslexic-Regular.ttf
  apps/accessibility/fonts/OpenDyslexic-Regular.woff
  apps/accessibility/img/app-dark.svg
  apps/accessibility/img/app.svg
  apps/accessibility/img/font-highcontrast.jpg
  apps/accessibility/img/font-opendyslexic.jpg
  apps/accessibility/img/font-opendyslexic2.jpg
  apps/accessibility/img/theme-dark.jpg
  apps/accessibility/img/theme-highcontrast.jpg
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/lib/AccessibilityProvider.php
  apps/accessibility/lib/AppInfo/Application.php
  apps/accessibility/lib/Controller/AccessibilityController.php
  apps/accessibility/lib/Controller/ConfigController.php
  apps/accessibility/lib/Settings/Personal.php
  apps/accessibility/lib/Settings/PersonalSection.php
  apps/accessibility/package-lock.json
  apps/accessibility/package.json
  apps/accessibility/src/App.vue
  apps/accessibility/src/components/itemPreview.vue
  apps/accessibility/src/main.js
  apps/accessibility/templates/settings-personal.php
  apps/accessibility/webpack.common.js
  apps/accessibility/webpack.dev.js
  apps/accessibility/webpack.prod.js
  build/integration/features/provisioning-v1.feature
  core/css/header.scss
  core/css/styles.scss
  core/fonts/OpenSans-Bold.ttf
  core/fonts/OpenSans-Bold.woff
  core/fonts/OpenSans-Light.ttf
  core/fonts/OpenSans-Light.woff
  core/fonts/OpenSans-Regular.ttf
  core/fonts/OpenSans-Regular.woff
  core/fonts/OpenSans-Semibold.ttf
  core/fonts/OpenSans-Semibold.woff
  core/shipped.json
Labels: 4. to release, enhancement, feature: accessibility

#9986 [13] properly lock the target file on dav upload when not using part files
  apps/dav/lib/Connector/Sabre/File.php
Labels: 3. to review

#9996 Change status code when config is write protected
  lib/base.php
  lib/private/legacy/util.php
Labels: 4. to release, enhancement

#9966 Resend activation email for new users as admin
  settings/css/settings.scss
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/package-lock.json
  settings/package.json
  settings/src/components/userList/userRow.vue
  settings/src/store/users.js
Labels: 3. to review, enhancement, feature: users and groups, feature: vue apps

#9995 Server error/hint pages with a 500 error code to avoid it being seen …
  index.php
  lib/base.php
  lib/private/legacy/files.php
  lib/private/legacy/template.php
  public.php
  remote.php
Labels: 3. to review, bug

#9635 Add support for using kerberos ticket to authenticate to smb servers
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Lib/Auth/AuthMechanism.php
  apps/files_external/lib/Lib/Auth/SMB/KerberosAuth.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#10002 Add resource type phpDoc for putContent methods
  lib/private/Files/Node/File.php
  lib/private/Files/SimpleFS/SimpleFile.php
  lib/private/Files/View.php
  lib/public/Files/File.php
  lib/public/Files/SimpleFS/ISimpleFile.php
Labels: 3. to review, feature: filesystem

#10003 Fix deps security
  apps/accessibility/appinfo/info.xml
  apps/accessibility/package-lock.json
  apps/accessibility/package.json
  apps/accessibility/webpack.common.js
Labels: 4. to release, feature: dependencies, feature: vue apps, security

#10006 Fix groupExists when a backend provides group details
  lib/private/Group/Manager.php
Labels: 4. to release

#10004 Add skip navigation / skip to content links for accessibility
  core/css/header.scss
  core/templates/layout.user.php
Labels: 4. to release, design, enhancement, feature: accessibility

#10007 Validate OAuth2 redirect uri
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/oauth2/lib/Controller/SettingsController.php
  apps/oauth2/src/App.vue
  apps/oauth2/tests/Controller/SettingsControllerTest.php
Labels: 4. to release, enhancement

#10005 show error message when group exists
  apps/provisioning_api/lib/Controller/GroupsController.php
Labels: 3. to review

#10019 Make skip navigation links translatable
  core/templates/layout.user.php
Labels: 3. to review, bug, design, feature: accessibility

#10009 Replace hard coded HTTP status codes with proper calls to http_response_code
  apps/files/ajax/list.php
  apps/files_sharing/public.php
  apps/files_trashbin/ajax/list.php
  apps/files_versions/download.php
  index.php
  lib/base.php
  lib/private/legacy/api.php
  lib/private/legacy/files.php
  lib/private/legacy/response.php
  ocs/v1.php
  public.php
  remote.php
  status.php
Labels: 3. to review, technical debt

#10023 Use the correct Base class
  core/Command/TwoFactorAuth/State.php
Labels: 3. to review, bug

#10027 Add groupware settings section
  apps/dav/lib/Settings/CalDAVSettings.php
  apps/dav/tests/unit/Settings/CalDAVSettingsTest.php
  lib/private/Settings/Manager.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, enhancement, feature: dav, feature: settings

#10018 Update root.vue
  apps/updatenotification/js-src/components/root.vue
  apps/updatenotification/js/merged.js
  apps/updatenotification/js/merged.js.map
Labels: 4. to release, backport-request

#10020 Fix "parsing" of email-addresses in comments and chat messages
  core/js/public/comments.js
Labels: 3. to review, backport-request, bug, feature: comments

#10031 LDAP backup server should not be queried when auth fails
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/tests/ConnectionTest.php
Labels: 3. to review, bug, feature: ldap

#10032 [stable13] LDAP backup server should not be queried when auth fails
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/tests/ConnectionTest.php
Labels: 3. to review, bug, feature: ldap

#10036 Log path of file that failed to be parsed
  lib/private/Preview/Bitmap.php
Labels: 4. to release, enhancement

#10039 Disable codecov status and comment
  .codecov.yml
Labels: 3. to review, backport-request

#10042 Fix variable not replaced in "behat.yml" when default value was used
  tests/acceptance/run-local.sh
Labels: 3. to review

#10040 Fix filenames in sharing integration tests
  build/integration/features/sharing-v1-part2.feature
Labels: 3. to review

#10034 lower log level for quota manipulation cases
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/User/UserTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#10043 Run mergejs to add css-vars-ponyfill
  core/vendor/core.js
Labels: 3. to review, bug

#5623 Add user locale/region setting
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  config/config.sample.php
  core/css/icons.scss
  core/img/actions/timezone.svg
  core/js/js.js
  core/templates/layout.user.php
  lib/private/L10N/Factory.php
  lib/private/L10N/L10N.php
  lib/private/Settings/Personal/PersonalInfo.php
  lib/private/TemplateLayout.php
  lib/public/IL10N.php
  lib/public/L10N/IFactory.php
  resources/locales.json
  settings/css/settings.scss
  settings/js/settings/personalInfo.js
  settings/templates/settings/personal/personal.info.php
  tests/lib/L10N/L10nTest.php
Labels: 3. to review, feature: settings

#10044 [stable13] Fix filenames in sharing integration tests
  build/integration/features/sharing-v1-part2.feature
Labels: 3. to review

#10037 Fix search related results in OPTIONS requests
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/lib/Files/LazySearchBackend.php
  apps/dav/lib/Server.php
Labels: 3. to review

#8854 Get rid of shareItem
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/BackendTest.php
  lib/private/Share/Share.php
  tests/lib/Share/ShareTest.php
  tests/lib/TagsTest.php
Labels: 3. to review, feature: sharing, technical debt

#10049 Fix code integrity check-warning link
  core/js/integritycheck-failed-notification.js
Labels: 4. to release, bug

#10045 Fix new group selection
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/userList.vue
  settings/src/components/userList/userRow.vue
  settings/src/store/users.js
Labels: 4. to release, bug, feature: users and groups

#10046 Fix getting the information of a group share as a sharee
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/features/sharing-v1-part2.feature
Labels: 3. to review, bug, feature: sharing

#10028 Fix some minor settings UI issues
  apps/systemtags/css/settings.css
  apps/systemtags/js/admin.js
  apps/systemtags/templates/admin.php
  apps/workflowengine/css/admin.css
  apps/workflowengine/templates/admin.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Settings/Manager.php
  lib/private/Settings/Personal/ServerDevNotice.php
  settings/css/settings.scss
  settings/templates/settings/admin/server.development.notice.php
  settings/templates/settings/personal/development.notice.php
  tests/Settings/Controller/AdminSettingsControllerTest.php
Labels: 3. to review, design, feature: settings, papercut

#10053 Move password change to security settings
  lib/private/Settings/Manager.php
  lib/private/Settings/Personal/PersonalInfo.php
  lib/private/Settings/Personal/Security.php
  settings/css/settings.scss
  settings/js/security_password.js
  settings/js/settings/personalInfo.js
  settings/templates/settings/personal/personal.info.php
  settings/templates/settings/personal/security.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, design, enhancement, feature: settings

#10038 Add option to only scan the home storage
  apps/files/lib/Command/Scan.php
  lib/private/Files/Utils/Scanner.php
Labels: 3. to review

#10054 Fix controls background
  core/css/styles.scss
Labels: 3. to review, design, regression

#10041 Safe default behaviour when no users are specified on trashbin:cleanup
  apps/files_trashbin/lib/Command/CleanUp.php
  apps/files_trashbin/tests/Command/CleanUpTest.php
Labels: 3. to review, enhancement, feature: trashbin

#10048 Systemd Logger
  .drone.yml
  config/config.sample.php
  core/Command/Log/Manage.php
  index.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Log/LogFactory.php
  lib/private/Log/Syslog.php
  lib/private/Log/Systemdlog.php
  lib/private/legacy/template.php
  lib/public/Log/ILogFactory.php
  tests/lib/Log/LogFactoryTest.php
  tests/lib/TestCase.php
Labels: 4. to release, enhancement, feature: logging
