Repository nextcloud/server, pull requests merged in 2018-08, with the labels that each got.

#10448 Only lower opacity of the avatar if the checkbox is checked on the content-list
  core/css/apps.scss
Labels: 4. to release, bug, design

#10466 Fixed tiny grammar issue
  lib/public/Federation/Exceptions/ProviderAlreadyExistsException.php
Labels: 4. to release

#10471 Improve URL detection
  core/js/public/comments.js
  core/js/tests/specs/public/commentsSpec.js
Labels: 3. to review, backport-request, bug, feature: comments

#10483 No margin left if the navigation is hidden
  core/css/apps.scss
Labels: 4. to release, design, regression, standardisation

#10474 Set emptyText depending on filepicker type
  core/js/oc-dialogs.js
Labels: 4. to release, design, papercut

#10479 Use icon classes in personal settings
  settings/js/federationscopemenu.js
Labels: 14-beta-feedback, 3. to review, design, regression

#10484 Append cache bump parameter to scss files URL
  lib/private/Template/SCSSCacher.php
  tests/lib/Template/SCSSCacherTest.php
Labels: bug, feature: theming

#10481 Make the info available if the avatar was uploaded or generated
  core/Controller/AvatarController.php
  lib/private/Avatar.php
  lib/public/IAvatar.php
  tests/Core/Controller/AvatarControllerTest.php
Labels: 4. to release, enhancement

#10486 Mobile fixes
  core/css/mobile.scss
Labels: 14-beta-feedback, 4. to release, design

#10465 Fix state propragation of the backup codes provider
  apps/twofactor_backupcodes/composer/composer/autoload_classmap.php
  apps/twofactor_backupcodes/composer/composer/autoload_static.php
  apps/twofactor_backupcodes/lib/AppInfo/Application.php
  apps/twofactor_backupcodes/lib/Event/CodesGenerated.php
  apps/twofactor_backupcodes/lib/Listener/ActivityPublisher.php
  apps/twofactor_backupcodes/lib/Listener/IListener.php
  apps/twofactor_backupcodes/lib/Listener/RegistryUpdater.php
  apps/twofactor_backupcodes/lib/Service/BackupCodeStorage.php
  apps/twofactor_backupcodes/tests/Unit/Event/CodesGeneratedTest.php
  apps/twofactor_backupcodes/tests/Unit/Listener/ActivityPublisherTest.php
  apps/twofactor_backupcodes/tests/Unit/Listener/RegistryUpdaterTest.php
  apps/twofactor_backupcodes/tests/Unit/Service/BackupCodeStorageTest.php
Labels: 3. to review, bug, feature: authentication, high

#10495 14 Beta 2
  version.php
Labels: 3. to review

#10482 Only show checkbox on hover/focus + accessibility fixes
  core/css/apps.scss
Labels: 4. to release, design, enhancement, feature: accessibility, standardisation

#10508 Fix app management not providing updates for apps which got disabled
  lib/private/Installer.php
  settings/Controller/AppSettingsController.php
Labels: 4. to release, bug, feature: apps management

#10506 Not all apps are from the appstore
  settings/Controller/AppSettingsController.php
Labels: 4. to release, bug

#10515 Fixed design zindex
  core/css/apps.scss
  core/css/styles.scss
Labels: 14-beta-feedback, 4. to release, bug, design

#10519 Min height 100% on content-wrapper
  core/css/apps.scss
Labels: 14-beta-feedback, 4. to release, design, enhancement

#10509 Always replace the app sidebar view when switching from a different file list
  apps/files/js/detailsview.js
  apps/files/js/filelist.js
  tests/acceptance/features/app-files.feature
Labels: 14-beta-feedback, 3. to review, bug, feature: files

#10485 Fix design of update error page
  core/css/guest.css
  core/img/actions/error-white.svg
  core/js/update.js
  core/templates/update.admin.php
Labels: 4. to release, bug, design, feature: install and update

#10530 Fix issues when using the public layout without a PublicTemplateResponse
  core/css/public.scss
  core/templates/layout.base.php
  core/templates/layout.public.php
Labels: 14-beta-feedback, 4. to release, bug, regression

#10523 Adding test for table schedulingobjects and fixing postgres LOB
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 3. to review, backport-request, bug

#10550 Do not log to error loglevel when converting the error
  lib/private/Files/Storage/DAV.php
Labels: 3. to review, enhancement

#10558 A failing federation sync job is not an error
  apps/federation/lib/SyncJob.php
Labels: 3. to review, enhancement

#10569 get avatar custom status from user config
  lib/private/Avatar.php
Labels: 3. to review

#10572 Fix security settings if password change is disabled
  settings/templates/settings/personal/security.php
Labels: 3. to review, feature: settings, high, regression

#10525 Fixed notifications position
  core/css/styles.scss
Labels: 14-beta-feedback, 4. to release, bug, design, regression

#10578 Fix 2FA provider registry population on login
  lib/private/Authentication/TwoFactorAuth/Manager.php
  tests/lib/Authentication/TwoFactorAuth/ManagerTest.php
Labels: 14-beta-feedback, 3. to review, bug, feature: authentication, high, regression, security

#10320 Cleanup of leftover-sorting-code from quickaccess-feature #9714 #9720
  apps/files/appinfo/routes.php
  apps/files/js/navigation.js
  apps/files/lib/Controller/ApiController.php
Labels: 4. to release, feature: files

#10582 Fix `this` context for enter-key handler on app tokens
  settings/js/authtoken_view.js
Labels: 14-beta-feedback, 3. to review, bug, feature: authentication

#10586 Check if HTTP_USER_AGENT is set before using it
  lib/private/legacy/util.php
Labels: 4. to release, enhancement

#10553 Disable Oracle enforcement for now until the following issues are sol…
  lib/private/DB/MigrationService.php
  tests/lib/DB/MigrationsTest.php
Labels: 14-beta-feedback, 3. to review, bug

#10397 make file cache updates more robust
  apps/encryption/lib/Crypto/Encryption.php
  lib/private/Files/Stream/Encryption.php
  tests/lib/Files/Stream/EncryptionTest.php
Labels: 3. to review, backport-request, bug, feature: encryption (server-side)

#10548 Update icewind/streams
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/streams/.travis.yml
  apps/files_external/3rdparty/icewind/streams/README.md
  apps/files_external/3rdparty/icewind/streams/src/CountWrapper.php
  apps/files_external/3rdparty/icewind/streams/src/Wrapper.php
Labels: 14-beta-feedback, 3. to review, bug, regression

#10599 Fix app code checker to ignore `build` directory
  lib/private/App/CodeChecker/CodeChecker.php
Labels: 3. to review, bug

#10597 Restores the guest icons
  core/img/actions/checkmark-white.svg
  core/img/actions/confirm-white.svg
  core/img/actions/info-white.svg
Labels: 3. to review, bug, design, regression

#8690 [Part2] Make thunderbird and outlook addons identifyable
  apps/workflowengine/js/requestuseragentplugin.js
Labels: 3. to review, backport-request, enhancement, feature: workflow engine

#10537 Fix multiSelectMenu for public shares #10536
  apps/files_sharing/js/public.js
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 14-beta-feedback, 3. to review, bug

#10255 Add support for room shares
  apps/admin_audit/lib/Actions/Sharing.php
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
  apps/files/lib/Command/TransferOwnership.php
  apps/files/lib/Controller/ApiController.php
  apps/files_sharing/js/share.js
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/Updater.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/files_sharing/tests/MountProviderTest.php
  apps/files_sharing/tests/js/shareSpec.js
  build/integration/features/bootstrap/Provisioning.php
  build/integration/features/sharing-v1.feature
  core/js/share.js
  core/js/sharedialogresharerinfoview.js
  core/js/sharedialogshareelistview.js
  lib/private/Share/Constants.php
  lib/private/Share20/Manager.php
  lib/private/Share20/ProviderFactory.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, enhancement, feature: sharing

#10604 Nextcloud 14.0.0 beta3
  version.php
Labels: 3. to review

#10588 Fix login redirection if only one 2FA provider is active
  core/Controller/LoginController.php
  lib/private/Authentication/TwoFactorAuth/ProviderSet.php
  tests/Core/Controller/LoginControllerTest.php
  tests/lib/Authentication/TwoFactorAuth/ProviderSetTest.php
Labels: 14-beta-feedback, 4. to release, bug, regression

#10611 Fix duplicate key violation in 2FA provider registry DAO
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
  tests/lib/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDaoTest.php
Labels: 3. to review, bug, feature: authentication, high

#10598 Removed unused variable isFile
  core/js/files/client.js
Labels: 3. to review, technical debt

#10626 Fix quickaccess active indicator for folders with spaces
  apps/files/js/navigation.js
Labels: 3. to review, bug, feature: files

#10614 Do not use file as template parameter
  core/templates/403.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
Labels: 3. to review, bug

#10581 make file cache updates more robust
  apps/encryption/lib/Crypto/Encryption.php
  lib/private/Files/Stream/Encryption.php
  tests/lib/Files/Stream/EncryptionTest.php
Labels: bug, feature: encryption (server-side)

#10546 Popovermenu fix and token settings design fixes
  core/css/apps.scss
  settings/css/settings.scss
  settings/js/authtoken_view.js
Labels: 3. to review, bug, design, papercut

#10618 use insertIfNotExists to store new mimetypes.
  lib/private/Files/Type/Loader.php
Labels: 3. to review

#10636 Fix 2FA being enforced if only backup codes provider is active
  lib/private/Authentication/TwoFactorAuth/Manager.php
  tests/lib/Authentication/TwoFactorAuth/ManagerTest.php
Labels: 14-beta-feedback, 3. to review, bug, feature: authentication, regression

#10619 Redirect to the same page after an update
  core/js/update.js
Labels: 4. to release, feature: install and update, papercut

#10623 Apply flex-basis to right header
  core/css/header.scss
Labels: 3. to review, bug, design

#10543 Do not show deactivated users in sharees and contacts
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/tests/unit/CardDAV/SyncServiceTest.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: 3. to review, bug, feature: contacts menu, feature: users and groups

#10615 Fix trashbin file actions
  apps/files_trashbin/js/app.js
Labels: 3. to review

#10642 Bump autoloaders
  apps/admin_audit/composer/composer/ClassLoader.php
  apps/comments/composer/composer/ClassLoader.php
  apps/dav/composer/composer/ClassLoader.php
  apps/encryption/composer/composer/ClassLoader.php
  apps/federatedfilesharing/composer/composer/ClassLoader.php
  apps/federation/composer/composer/ClassLoader.php
  apps/files/composer/composer/ClassLoader.php
  apps/files_sharing/composer/composer/ClassLoader.php
  apps/files_trashbin/composer/composer/ClassLoader.php
  apps/files_versions/composer/composer/ClassLoader.php
  apps/lookup_server_connector/composer/composer/ClassLoader.php
  apps/oauth2/composer/composer/ClassLoader.php
  apps/provisioning_api/composer/composer/ClassLoader.php
  apps/sharebymail/composer/composer/ClassLoader.php
  apps/systemtags/composer/composer/ClassLoader.php
  apps/testing/composer/composer/ClassLoader.php
  apps/twofactor_backupcodes/composer/composer/ClassLoader.php
  apps/updatenotification/composer/composer/ClassLoader.php
  apps/user_ldap/composer/composer/ClassLoader.php
  lib/composer/composer/ClassLoader.php
Labels: 4. to release

#10639 Fix apps management sorting and app removal
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/appDetails.vue
  settings/src/components/appList.vue
Labels: 14-beta-feedback, 3. to review, bug, feature: apps management

#10610 do not trigger counting on LDAP
  settings/Controller/UsersController.php
Labels: 14-beta-feedback, bug, feature: ldap, feature: users and groups, regression

#10666 Another CRL bump
  resources/codesigning/root.crl
Labels: 3. to review

#10659 Drop support for xcache
  config/config.sample.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Memcache/XCache.php
  lib/private/legacy/util.php
  tests/lib/Memcache/XCacheTest.php
Labels: 3. to review, technical debt

#10592 Allow external actions to users list
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/components/userList.vue
  settings/src/components/userList/userRow.vue
  settings/src/views/Users.vue
Labels: 4. to release, enhancement, feature: users and groups, feature: vue apps

#10621 Add the ToS app to the enterprise bundle
  lib/private/App/AppStore/Bundles/EnterpriseBundle.php
  tests/lib/App/AppStore/Bundles/EnterpriseBundleTest.php
Labels: 14-beta-feedback, 3. to review, enhancement, feature: apps management

#10660 Pass HttpHeader as array
  build/signed-off-checker.php
Labels: 3. to review

#10620 [13] use insertIfNotExists to store new mimetypes.
  lib/private/Files/Type/Loader.php
Labels: 3. to review

#10680 Update the scope of the lockdownmanager
  lib/private/User/Session.php
Labels: 4. to release, enhancement

#8855 behat integration tests for LDAP
  .drone.yml
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestAccessGroupsMatchFilter.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestBackupServer.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestBatchApplyUserAttributes.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestConnect.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestPaging.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestUserHome.php
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/LDAPContext.php
  build/integration/features/provisioning-v1.feature
  build/integration/ldap_features/ldap-openldap.feature
  build/integration/ldap_features/openldap-uid-username.feature
  build/integration/run.sh
Labels: 3. to review

#10682 [stable13] Update the scope of the lockdownmanager
  lib/private/User/Session.php
Labels: 3. to review

#10683 [stable12] Update the scope of the lockdownmanager
  lib/private/User/Session.php
Labels: 3. to review

#10689 Add default theming into accessibility compiler
  apps/accessibility/lib/Controller/AccessibilityController.php
Labels: 14-beta-feedback, 3. to review, bug, feature: accessibility, feature: theming, regression

#10691 Various beta14 design fixes
  apps/files_sharing/css/sharetabview.scss
  apps/theming/css/settings-admin.scss
  core/css/jquery-ui-fixes.scss
  core/css/public.scss
  core/css/styles.scss
  core/templates/layout.public.php
Labels: 14-beta-feedback, 3. to review, bug, design

#10645 only warn about data lose on password reset if per-user keys are used
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3. to review, backport-request, feature: encryption (server-side)

#10701 Fix timepicker z-index to be above the sidebar
  core/css/styles.scss
Labels: 3. to review, bug, design

#10646 [stable13] only warn about data lose on password reset if per-user keys are used
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3. to review, feature: encryption (server-side)

#10702 Fix missing actions menu on small screens in the user management
  settings/css/settings.scss
Labels: 14-beta-feedback, 3. to review, bug, design

#10692 Do not show action menu if no actions are available
  apps/files/js/fileactions.js
  apps/files_sharing/js/share.js
Labels: 14-beta-feedback, 4. to release, bug, feature: files, feature: sharing

#10695 Fix password enforce on public links
  apps/files_sharing/css/sharetabview.scss
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, bug, feature: sharing, high, regression

#10608 Fix header menu & contact popover
  core/css/apps.scss
  core/css/header.scss
  core/js/jquery.contactsmenu.js
  core/js/tests/specs/jquery.contactsmenuSpec.js
Labels: 3. to review, bug, design, papercut

#10703 Nextcloud 14 Beta 4
  version.php
Labels: 4. to release

#10715 fix wrong return value of filtered whats new info
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/tests/Settings/AdminTest.php
  core/css/whatsnew.scss
Labels: 14-beta-feedback, 4. to release, bug

#10718 add occ command to recover encrypted files in case of password lost
  apps/encryption/appinfo/info.xml
  apps/encryption/composer/composer/autoload_classmap.php
  apps/encryption/composer/composer/autoload_static.php
  apps/encryption/lib/Command/RecoverUser.php
  apps/encryption/lib/Hooks/UserHooks.php
  apps/encryption/tests/Hooks/UserHooksTest.php
Labels: 3. to review, feature: encryption (server-side)

#10731 add deck and mail to the groupware bundle, remove talk
  lib/private/App/AppStore/Bundles/GroupwareBundle.php
  tests/lib/App/AppStore/Bundles/GroupwareBundleTest.php
Labels: 4. to release

#10707 Fix public pages background
  apps/files_sharing/css/public.scss
Labels: 3. to review, bug, design, feature: accessibility

#10744 Update help.php
  settings/templates/help.php
Labels: 14-beta-feedback, 3. to review

#10755 Fix comment style in config sample
  config/config.sample.php
Labels: 4. to release, backport-request

#10687 don't blame randome people for background email updates
  apps/admin_audit/lib/Actions/UserManagement.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/User_LDAPTest.php
  settings/Hooks.php
Labels: 3. to review, backport-request, bug

#10759 [stable13] Fix comment style in config sample
  config/config.sample.php
Labels: 3. to review

#10761 [stable13] Fix call to OC.generateUrl for caldav birthday calendar on/off
  apps/dav/js/settings-admin-caldav.js
Labels: 3. to review

#10735 [stable13] Forgotten pass fix link
  core/js/lostpassword.js
Labels: 3. to review, bug

#10697 log entries that are hidden during file listing
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#10565 [stable13] Fix transfering ownership of a share to user with same id as receiver
  apps/files/lib/Command/TransferOwnership.php
  build/integration/features/transfer-ownership.feature
Labels: 3. to review, bug

#10698 [13] log entries that are hidden during file listing
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#10566 [stable12] Fix transfering ownership of a share to user with same id as receiver
  apps/files/lib/Command/TransferOwnership.php
  build/integration/features/transfer-ownership.feature
Labels: 3. to review, bug

#10738 Only send an update sort order request if there is an user
  apps/files/js/filelist.js
  apps/files/tests/js/filelistSpec.js
Labels: 3. to review, bug, regression

#10552 [stable13] Adding test for table schedulingobjects and fixing postgres LOB
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 3. to review, bug

#10747 Adds a vendor prefix for position sticky
  core/css/apps.scss
  core/css/functions.scss
  core/css/styles.scss
  settings/css/settings.scss
Labels: 3. to review, bug, design

#10760 [stable13] Make sure error_log() always receives a string
  lib/private/Log/File.php
Labels: 3. to review

#10628 Adds a permission check for app directories
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3. to review, feature: apps management

#10700 Fix share dialog sidebar in share views
  apps/files_sharing/js/sharedfilelist.js
  core/js/shareitemmodel.js
  core/js/tests/specs/shareitemmodelSpec.js
Labels: 3. to review, backport-request, bug, feature: sharing

#10710 Fix typo in IUserManager::createUser doc
  lib/public/IUserManager.php
Labels: 3. to review, low, technical debt

#10772 Fix generated migration class code
  core/Command/Db/Migrations/GenerateCommand.php
Labels: 4. to release, bug, technical debt

#10539 Adds a setup and cli check for the recommended memory limit
  console.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Console/Application.php
  lib/private/MemoryInfo.php
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
  tests/lib/MemoryInfoTest.php
Labels: 3. to review, enhancement, papercut

#10771 Fix backup codes column length for Argon2 values
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/twofactor_backupcodes/composer/composer/autoload_classmap.php
  apps/twofactor_backupcodes/composer/composer/autoload_static.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20180821043638.php
  apps/twofactor_backupcodes/tests/Db/BackupCodeMapperTest.php
  apps/twofactor_backupcodes/tests/Service/BackupCodeStorageTest.php
Labels: 14-beta-feedback, 3. to review, bug, feature: authentication

#10775 Resolve all group memberships properly
  apps/user_ldap/lib/Group_LDAP.php
Labels: 3. to review, bug, feature: ldap

#10763 [stable13] don't blame randome people for background email updates
  apps/admin_audit/lib/Actions/UserManagement.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/User_LDAPTest.php
  settings/Hooks.php
Labels: 3. to review, bug

#10789 Fix loading providers of 2FA app with more than one provider
  lib/private/App/InfoParser.php
Labels: 14-beta-feedback, 3. to review, bug, feature: authentication

#10783 [stable13] Resolve all group memberships properly
  apps/user_ldap/lib/Group_LDAP.php
Labels: 3. to review, bug, feature: ldap

#10526 Support HEIC for previews
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Preview/HEIC.php
  lib/private/PreviewManager.php
  resources/config/mimetypemapping.dist.json
  tests/data/testimage.heic
  tests/lib/Preview/HEICTest.php
Labels: 3. to review

#10787 Fixes the app menu
  core/css/header.scss
  core/js/js.js
Labels: 14-beta-feedback, 3. to review, bug

#10815 returning of $tr is expected, otherwise ending up in a JS error
  apps/files_sharing/js/sharedfilelist.js
Labels: 3. to review, bug, feature: sharing

#10816 [stable13] remove unexecutable code
  apps/files_sharing/js/sharedfilelist.js
Labels: 3. to review, bug

#10821 [stable13] Improve URL detection
  core/js/public/comments.js
  core/js/tests/specs/public/commentsSpec.js
Labels: 3. to review, bug, feature: comments

#10822 Show link to simple sign up page
  config/config.sample.php
  core/css/public.scss
  core/templates/layout.public.php
  lib/private/TemplateLayout.php
Labels: 4. to release, enhancement

#10823 [stable13] MySQL 8.0+ and MariaDB 10.3+ are large prefix and barracuda by default
  lib/private/DB/MySqlTools.php
Labels: 3. to review, bug

#10285 [13] Add sabre plugin to allow anonymous options requests to the dav root
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Files/LazySearchBackend.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/DAV/AnonymousOptionsTest.php
Labels: 3. to review

#10591 [13] retry smb stat on timeout
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#10801 Add sample config for HEIC image previews
  config/config.sample.php
Labels: 4. to release

#10589 retry smb stat on timeout
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#10792 12.0.11 RC 1
  lib/composer/composer/ClassLoader.php
  version.php
Labels: 3. to review

#10334 Add options to create/remove groups via occ
  core/Command/Group/Add.php
  core/Command/Group/Delete.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  tests/Core/Command/Group/AddTest.php
  tests/Core/Command/Group/DeleteTest.php
Labels: 3. to review, enhancement

#10670 Fix max length requirements for the throttler metadata
  core/Controller/LoginController.php
Labels: 3. to review, bug

#10724 Improve performance when dealing with large numbers of shares
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/SharedMount.php
  apps/files_sharing/lib/SharedStorage.php
  lib/private/Files/Config/UserMountCache.php
  lib/private/Files/Mount/Manager.php
  lib/private/Files/View.php
  lib/private/Share20/Manager.php
Labels: 3. to review

#10837 [13] disallow negative mtime in dav search
  apps/dav/lib/Files/FileSearchBackend.php
Labels: 3. to review

#10773 Accessibility theme fixes
  apps/accessibility/css/themehighcontrast.scss
  core/css/apps.scss
Labels: 14-beta-feedback, 3. to review, design, feature: accessibility

#10841 also catch exceptions when loading apps
  lib/private/legacy/app.php
Labels: 4. to release

#10803 prefer using dir instead of allinfo for getting smb file info
  apps/files_external/3rdparty/icewind/smb/src/TimeZoneProvider.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php
Labels: 4. to release

#10835 disallow negative mtime in dav search
  apps/dav/lib/Files/FileSearchBackend.php
Labels: 4. to release

#10834 Add support for room shares
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/tests/Controller/ShareesAPIControllerTest.php
  core/js/sharedialogview.js
Labels: 3. to review

#10820 [LDAP] The WebUI Wizard also should not assign empty config IDs
  apps/user_ldap/lib/Settings/Admin.php
  apps/user_ldap/templates/part.wizard-server.php
  apps/user_ldap/tests/Settings/AdminTest.php
Labels: 3. to review, bug, feature: ldap, papercut

#10827 HEIC previews as JPG rather than PNGs to save space.
  lib/private/Preview/HEIC.php
Labels: 3. to review, feature: previews and thumbnails

#10844 14.0.0 RC 1
  version.php
Labels: 3. to review

#10846 Add the new share type
  resources/app-info-shipped.xsd
  resources/app-info.xsd
Labels: 3. to review, bug, feature: apps management

#10856 Fix contactsmenu for mentioned users in comments
  apps/comments/css/comments.scss
Labels: bug, design, feature: comments, feature: contacts menu

#10858 Fix public pages conflicting
  core/css/guest.css
Labels: 3. to review, bug, design, regression

#10867 Use empty alt tag for avatars since there is always the name next to it
  core/css/inputs.scss
  core/js/jquery.avatar.js
Labels: 4. to release, bug, feature: accessibility

#10875 Theming: Only link Entity in footer if a url is set
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/ThemingDefaultsTest.php
  core/css/guest.css
Labels: 4. to release, feature: theming, papercut

#10881 Makes the notifications area width equal to the contents
  core/css/mobile.scss
  core/css/styles.scss
Labels: 3. to review, design, papercut

#10892 Fix drag shadow in Files app
  apps/files/css/files.scss
Labels: 3. to review, bug, design, feature: files, regression

#10871 cast timestamps older than unix epoch to 0
  apps/dav/lib/Files/FileSearchBackend.php
Labels: 3. to review

#10854 Allow same section class for multiple section types (fix #10764)
  lib/private/Settings/Manager.php
  tests/lib/Settings/ManagerTest.php
Labels: 14-beta-feedback, 3. to review, regression

#10876 Theming: apply proper size to the remove background button
  apps/theming/css/settings-admin.scss
Labels: 3. to review, feature: theming, papercut

#10932 13.0.6
  version.php
Labels: 3. to review

#10933 12.0.11
  version.php
Labels: 3. to review

#10853 Fix apps menu on mobile
  core/css/header.scss
  core/css/mobile.scss
Labels: 3. to review, design, regression

#10924 Fix SCSS variable management with the theming app
  apps/accessibility/lib/Controller/AccessibilityController.php
  apps/theming/css/theming.scss
  apps/theming/lib/Util.php
  apps/theming/tests/CapabilitiesTest.php
  apps/theming/tests/UtilTest.php
  core/css/variables.scss
  lib/private/Template/SCSSCacher.php
Labels: 4. to release, bug, feature: theming

#10913 Do not parse HTML in user id and display name
  apps/comments/js/commentstabview.js
Labels: 3. to review, bug, feature: comments

#10925 Use main text color for editable divs and text areas
  core/css/inputs.scss
Labels: 4. to release, design

#10936 Make possible to pick both files and folders
  core/js/jquery.ocdialog.js
  core/js/oc-dialogs.js
Labels: 3. to review, bug, feature: filepicker

#10906 ensure we always return an array from `Request::getParams`
  lib/private/AppFramework/Http/Request.php
Labels: 3. to review

#10939 Fix path when app has wrong permission
  settings/Controller/CheckSetupController.php
Labels: 3. to review, bug

#10902 [13] cast timestamps older than unix epoch to 0
  apps/dav/lib/Files/FileSearchBackend.php
Labels: 3. to review

#10942 Change password expiration time from 12h to 7d
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: 4. to release, feature: authentication

#10943 Fix handlng of concurrent inserts of the 2FA provider registry DAO
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
Labels: 14-beta-feedback, bug, feature: authentication, high

#10861 14.0.0 RC 2
  version.php
Labels: 3. to review
