Repository nextcloud/server, pull requests merged in 2019-03, with the labels that each got.

#14392 Move personal auth token settings to Vue
  package-lock.json
  package.json
  settings/css/settings.scss
  settings/js/authtoken.js
  settings/js/authtoken_collection.js
  settings/js/authtoken_view.js
  settings/js/settings/authtoken-init.js
  settings/js/templates.js
  settings/js/templates/authtoken.handlebars
  settings/js/vue-0.js
  settings/js/vue-1.js
  settings/js/vue-1.js.map
  settings/js/vue-2.js
  settings/js/vue-2.js.map
  settings/js/vue-3.js.map
  settings/js/vue-4.js
  settings/js/vue-4.js.map
  settings/js/vue-5.js
  settings/js/vue-5.js.map
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-7.js
  settings/js/vue-7.js.map
  settings/js/vue-8.js
  settings/js/vue-8.js.map
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/src/components/AuthToken.vue
  settings/src/components/AuthTokenList.vue
  settings/src/components/AuthTokenSection.vue
  settings/src/components/AuthTokenSetupDialogue.vue
  settings/src/main-admin-security.js
  settings/src/main-personal-security.js
  settings/templates/settings/personal/security.php
  settings/webpack.js
Labels: 3. to review, enhancement

#14397 Allow search unregister
  core/search/js/search.js
Labels: 4. to release, enhancement, feature: search

#14449 Allow apps to redirect to the default app
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/Http/RedirectToDefaultAppResponse.php
Labels: 4. to release, enhancement, technical debt

#14454 Use node API for trash bin with special flag for getSize()
  apps/files_trashbin/lib/Trashbin.php
Labels: 3. to review

#14254 Dont check Bucket Name in Nextcloud
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 3. to review, bug, feature: filesystem

#14450 Add app token QR codes for mobile apps
  package-lock.json
  package.json
  settings/js/vue-0.js
  settings/js/vue-1.js
  settings/js/vue-1.js.map
  settings/js/vue-3.js
  settings/js/vue-4.js
  settings/js/vue-5.js
  settings/js/vue-6.js
  settings/js/vue-7.js
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/src/components/AuthTokenSetupDialogue.vue
Labels: 4. to release, client: 💻 desktop, enhancement, integration

#14456 Fix a bug with smb notify having leading slash when it should not
  apps/files_external/lib/Command/Notify.php
Labels: 3. to review, backport-request, bug

#14405 Improve multiselect handling on twofactor settings
  settings/js/vue-0.js
  settings/js/vue-6.js
  settings/js/vue-7.js
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/src/components/AdminTwoFactor.vue
Labels: 4. to release, bug, feature: settings

#14448 Convert value of timestamp metadata key in swift files_external
  apps/files_external/lib/Lib/Storage/Swift.php
Labels: 3. to review, bug, feature: external storage

#14457 Load auth tokens with the initial state API
  lib/private/Settings/Personal/Security.php
  package-lock.json
  settings/Controller/AuthSettingsController.php
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/src/components/AuthTokenList.vue
  settings/src/components/AuthTokenSection.vue
  settings/src/main-personal-security.js
  tests/Settings/Controller/AuthSettingsControllerTest.php
  tests/lib/Settings/Personal/SecurityTest.php
Labels: 4. to release, enhancement, feature: authentication, feature: settings, technical debt

#14489 Add accessibility translations
  .tx/config
Labels: 3. to review, bug, feature: accessibility, feature: language l10n and translations

#14488 Fix dav has-photo plugin extend
  apps/dav/lib/CardDAV/HasPhotoPlugin.php
Labels: 3. to review, bug, feature: dav

#14468 Fix default input element height
  core/css/fixes.scss
  core/css/inputs.scss
  settings/css/settings.scss
Labels: 3. to review, bug, design

#14484 Fix/users and groups/vue multiselect
  settings/js/vue-1.js.map
  settings/js/vue-2.js
  settings/js/vue-2.js.map
  settings/js/vue-7.js
  settings/js/vue-7.js.map
  settings/src/components/popoverMenu/popoverItem.vue
  settings/src/components/userList.vue
  settings/src/components/userList/userRow.vue
Labels: 3. to review, bug, design

#14494 Make header.feature more robust by running it on apache
  tests/acceptance/features/header.feature
Labels: 3. to review, backport-request

#14493 Remove unused php5 config from .htaccess
  .htaccess
  tests/data/integritycheck/htaccessWithValidModifiedContent/.htaccess
  tests/data/setUploadLimit/htaccess
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: 4. to release, technical debt

#14472 Fix for issue #13319: load oc-backbone-webdav before loading versions app
  apps/files_versions/lib/Hooks.php
Labels: 3. to review, bug

#12978 Add note to dav endpoint
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Connector/Sabre/Node.php
Labels: 3. to review, enhancement, feature: dav, feature: sharing

#14430 Remove the upload and memory setting
  .htaccess
  .user.ini
  apps/files/appinfo/info.xml
  apps/files/appinfo/routes.php
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/js/admin.js
  apps/files/lib/Controller/SettingsController.php
  apps/files/lib/Settings/Admin.php
  apps/files/templates/admin.php
  apps/files/tests/Settings/AdminTest.php
  lib/private/IntegrityCheck/Checker.php
  lib/private/legacy/files.php
  lib/private/legacy/helper.php
  tests/data/integritycheck/htaccessWithValidModifiedContent/.htaccess
  tests/data/integritycheck/htaccessWithValidModifiedContent/.user.ini
  tests/lib/FilesTest.php
  tests/lib/IntegrityCheck/CheckerTest.php
  tests/lib/LegacyHelperTest.php
Labels: 4. to release, bug, feature: settings

#13401 improve lookup server behaviour
  apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php
  apps/lookup_server_connector/lib/UpdateLookupServer.php
Labels: 3. to review, bug

#14510 update icewind/smb to 3.1.1
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Connection.php
Labels: 3. to review

#14504 [stable14] Fix expire date change eventhandler
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, bug

#14503 [stable15] Fix expire date change eventhandler
  core/js/sharedialoglinkshareview.js
Labels: 4. to release, bug

#14499 Do not cut full color on accessibility svg color invert
  apps/accessibility/lib/Controller/AccessibilityController.php
Labels: 3. to review, backport-request, bug, feature: accessibility

#13871 dav: Fix handling of chunked WebDAV upload
  apps/dav/lib/Connector/Sabre/File.php
Labels: 3. to review, feature: dav

#14512 update icewind/smb to 3.0.2
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Connection.php
Labels: 4. to release

#14514 Do not just write foobar
  apps/dav/lib/Connector/Sabre/File.php
Labels: 3. to review, backport-request, bug

#14513 update icewind/smb to 3.0.2
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Connection.php
Labels: 4. to release

#14480 Reconnect to DB after timeout for Notify command. Fixes #14479
  apps/files_external/lib/Command/Notify.php
Labels: 3. to review, feature: external storage

#14501 16.0.0 Alpha 1
  version.php
Labels: 2. developing

#14470 use node API for free space calculation in versions app
  apps/files_versions/lib/Storage.php
Labels: 3. to review, enhancement

#14519 Fix Undefined property: OCA\LookupServerConnector\UpdateLookupServer::$config
  apps/lookup_server_connector/lib/UpdateLookupServer.php
Labels: 4. to release, bug

#14528 Fix database configuration
  autotest.sh
Labels: 3. to review, bug

#14529 Fix missing $config dependency in RetryJob
  apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php
Labels: 4. to release

#14302 nc16/fulltetsearch: moving final class to private, new interface in public
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/FullTextSearch/Model/DocumentAccess.php
  lib/private/FullTextSearch/Model/IndexDocument.php
  lib/private/FullTextSearch/Model/SearchOption.php
  lib/private/FullTextSearch/Model/SearchTemplate.php
  lib/public/Files_FullTextSearch/Model/AFilesDocument.php
  lib/public/FullTextSearch/IFullTextSearchPlatform.php
  lib/public/FullTextSearch/IFullTextSearchProvider.php
  lib/public/FullTextSearch/Model/IDocumentAccess.php
  lib/public/FullTextSearch/Model/IIndex.php
  lib/public/FullTextSearch/Model/IIndexDocument.php
  lib/public/FullTextSearch/Model/ISearchOption.php
  lib/public/FullTextSearch/Model/ISearchResult.php
  lib/public/FullTextSearch/Model/ISearchTemplate.php
Labels: 3. to review

#14502 Add activities for group membership changes
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  settings/Activity/GroupProvider.php
  settings/Activity/GroupSetting.php
  settings/Application.php
  settings/Hooks.php
Labels: 4. to release, backport-request, feature: activity and notification, feature: users and groups

#14451 Check if password can be changed for the users backend in OCS api
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 2. developing, backport-request, bug, feature: users and groups

#14544 Remove leftover input that causes undefined index errors
  settings/templates/settings/admin/security.php
Labels: 4. to release, bug

#14373 Add test for updated CA bundle
  autotest-checkers.sh
  build/ca-bundle-checker.sh
Labels: 3. to review, backport-request

#14175 Fix ObjectStorage expired token (v3)
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review, bug

#14535 Reduce errors in checker tests
  autotest-checkers.sh
Labels: 3. to review

#14541 Disable fragile tests for now
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/login.feature
  tests/acceptance/features/users.feature
Labels: 4. to release

#13790 Fix for crashing occ files:scan
  apps/files_sharing/lib/External/Manager.php
Labels: 3. to review, bug, feature: sharing

#14553 Clear backupcode reminder when no 2fa
  apps/twofactor_backupcodes/composer/composer/autoload_classmap.php
  apps/twofactor_backupcodes/composer/composer/autoload_static.php
  apps/twofactor_backupcodes/lib/AppInfo/Application.php
  apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php
  apps/twofactor_backupcodes/lib/Listener/ProviderDisabled.php
  apps/twofactor_backupcodes/tests/Unit/BackgroundJob/RememberBackupCodesJobTest.php
  apps/twofactor_backupcodes/tests/Unit/Listener/ProviderDisabledTest.php
Labels: 4. to release, backport-request, bug, enhancement

#13327 Allow bracket IPv6 address format inside IPAdress Normalizer
  lib/private/Security/Normalizer/IpAddress.php
  tests/lib/Security/Normalizer/IpAddressTest.php
Labels: 4. to release, php, security

#14558 Fix unnecessary boolean cast
  apps/files_sharing/lib/External/Manager.php
Labels: 4. to release, bug

#14560 Fully check compliant apps
  autotest-checkers.sh
Labels: 4. to release

#14567 Update generated webpack files to .l10nignore
  apps/files_sharing/.l10nignore
  settings/.l10nignore
Labels: 3. to review

#14563 Pin the jquery version to 2.1.4
  core/js/dist/main.js
  core/js/dist/main.js.map
  package-lock.json
  package.json
Labels: 4. to release, bug, regression

#14424 Use a tmp file for swift writes
  lib/private/Files/ObjectStore/Swift.php
Labels: 3. to review, regression

#14569 Fix transifex sync for files_sharing
  apps/files_sharing/.l10nignore
Labels: 4. to release

#14568 Cleanup some PHPDoc leftovers and unused variables
  lib/private/Archive/Archive.php
  lib/private/Collaboration/Collaborators/RemoteGroupPlugin.php
  lib/private/Server.php
  lib/private/Setup/PostgreSQL.php
  lib/private/Share20/Manager.php
  lib/private/Template/Base.php
Labels: 4. to release, technical debt

#14579 Have streams of files_external in sync
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php
Labels: 3. to review, backport-request, bug

#14580 [stable15] Have streams of files_external in sync
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php
Labels: 3. to review, bug

#14464 resolve user and groups in nested groups first before filtering the results
  .drone.yml
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
  build/integration/features/bootstrap/LDAPContext.php
  build/integration/ldap_features/ldap-openldap.feature
  build/integration/ldap_features/openldap-numerical-id.feature
Labels: 4. to release, backport-request, bug, feature: ldap

#14583 Remove Google+ federation usersettings
  apps/federatedfilesharing/css/settings-personal.scss
  apps/federatedfilesharing/img/social-googleplus.svg
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 3. to review, feature: federation

#14587 Remove Google+ from Social Sharing Bundle
  lib/private/App/AppStore/Bundles/SocialSharingBundle.php
  tests/lib/App/AppStore/Bundles/SocialSharingBundleTest.php
Labels: 3. to review, backport-request, feature: apps management

#14425 Do not calculate folder size for parent that also needs proper scan, fixes #3524
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
  tests/lib/Files/Cache/ScannerTest.php
Labels: 3. to review, bug, feature: filesystem

#14589 Add preview data as optional data for files
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review, enhancement, feature: activity and notification

#14585 Mention Open Cloud Mesh in Federated User Settings
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 3. to review, feature: federation

#14534 [stable15] Add activities for group membership changes
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  settings/Activity/GroupProvider.php
  settings/Activity/GroupSetting.php
  settings/Application.php
  settings/Hooks.php
Labels: 4. to release, enhancement, feature: activity and notification, feature: users and groups

#14548 Avoid duplicate App container creation
  apps/dav/lib/AppInfo/Application.php
  apps/dav/tests/unit/AppInfo/ApplicationTest.php
  lib/private/ServerContainer.php
  lib/public/AppFramework/App.php
Labels: 3. to review, bug

#14592 [stable14] resolve user and groups in nested groups first before filtering the results
  .drone.yml
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
  build/integration/features/bootstrap/LDAPContext.php
  build/integration/ldap_features/ldap-openldap.feature
Labels: 3. to review, bug, feature: ldap

#14591 [stable15] resolve user and groups in nested groups first before filtering the results
  .drone.yml
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
  build/integration/features/bootstrap/LDAPContext.php
  build/integration/ldap_features/ldap-openldap.feature
  build/integration/ldap_features/openldap-numerical-id.feature
Labels: 3. to review, bug, feature: ldap

#14603 Show a setup warning in case S3 object storage is used as primary storage
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3. to review, backport-request, enhancement, feature: install and update

#14620 Fix unneeded doc link to unrelated resource
  core/js/setupchecks.js
Labels: 4. to release, bug

#14623 Fix acceptance tests for wrong password message due to changed message
  tests/acceptance/features/bootstrap/LoginPageContext.php
Labels: 4. to release, bug

#14586 Add hint to user documentation (Federation)
  apps/federatedfilesharing/css/settings-personal.scss
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 4. to release, feature: federation

#14626 Make sure urlparams are correctly injected in global routes
  core/routes.php
  lib/private/AppFramework/App.php
  lib/private/AppFramework/Routing/RouteConfig.php
Labels: 3. to review, bug, regression

#6512 Change CALDAV to allow calendars be shared with circles.
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_versions/lib/AppInfo/Application.php
Labels: 4. to release, enhancement

#14644 Remove sensitive SMB arguments from exception log
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review, backport-request, bug

#14656 prevent recursion when moving a file to the trashbin
  apps/files_trashbin/lib/Trash/TrashManager.php
Labels: 3. to review, backport-request

#14640 Disable fragile tests
  apps/files_external/tests/Storage/SmbTest.php
  apps/files_trashbin/tests/TrashbinTest.php
  build/integration/federation_features/federated.feature
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/app-files-tags.feature
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/apps.feature
  tests/acceptance/features/login.feature
  tests/acceptance/features/users.feature
Labels: 3. to review

#14663 remove user_external example from config.sample.php
  config/config.sample.php
Labels: 3. to review

#14670 Use SCSS variables since CSS vars are not loaded on public pages
  apps/theming/css/theming.scss
Labels: 3. to review, backport-request, bug, feature: theming

#12119 Add Circle to Caldav and Filepanel
  apps/dav/lib/Connector/Sabre/FilesReportPlugin.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/PublicCalendarRootTest.php
  apps/dav/tests/unit/Connector/Sabre/FilesReportPluginTest.php
  core/js/files/client.js
Labels: 4. to release, enhancement, high

#14652 Do not allow invalid users to be created
  lib/private/User/Manager.php
Labels: 4. to release, enhancement

#14668 Make appstore app:enable test more robust by repeating if it fails on the first try
  tests/Core/Command/Apps/AppsEnableTest.php
Labels: 4. to release, backport-request

#14683 add casting to string for postgresql query builder
  lib/private/DB/QueryBuilder/ExpressionBuilder/PgSqlExpressionBuilder.php
Labels: 4. to release

#14679 Fix translation sync for accessibiltiy
  apps/accessibility/.l10nignore
  apps/accessibility/l10n/.gitkeep
  apps/files_external/tests/Storage/SmbTest.php
Labels: 4. to release

#14684 handle long etags from dav external storage
  lib/private/Files/Storage/DAV.php
Labels: 4. to release, backport-request

#14687 add an integration test that ensures deletion of LDAP users
  build/integration/ldap_features/openldap-uid-username.feature
Labels: 3. to review, backport-request, feature: ldap

#14693 dont try to restore a trashbin item to a readonly target
  apps/files_trashbin/lib/Trashbin.php
Labels: 4. to release, backport-request

#14690 throw a proper error if rename fails in dav
  apps/dav/lib/Connector/Sabre/Node.php
Labels: 4. to release, backport-request

#14702 Fixed Uppercase of Product name
  apps/accessibility/appinfo/info.xml
Labels: 4. to release

#14681 Disable fragile tests - part 2
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/apps.feature
Labels: 4. to release

#14686 Add correct method for hardcoded `/f/{fileid}`
  apps/files/lib/Controller/ViewController.php
Labels: 4. to release, bug, feature: files, regression

#14637 Add border around previews
  apps/files/css/files.scss
Labels: 4. to release, design, enhancement

#14673 [stable14] Disable fragile tests
  apps/files_external/tests/Storage/SmbTest.php
  apps/files_trashbin/tests/TrashbinTest.php
  build/integration/federation_features/federated.feature
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/app-files-tags.feature
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/apps.feature
  tests/acceptance/features/login.feature
  tests/acceptance/features/users.feature
Labels: 4. to release

#14672 [stable15] Disable fragile tests
  apps/files_external/tests/Storage/SmbTest.php
  apps/files_trashbin/tests/TrashbinTest.php
  build/integration/federation_features/federated.feature
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/app-files-tags.feature
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/apps.feature
  tests/acceptance/features/login.feature
  tests/acceptance/features/users.feature
Labels: 4. to release

#14682 Using SQLite should sound more scary 😈
  core/templates/installation.php
Labels: 3. to review, feature: install and update

#14628 Fix plural rule detection for languages
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/OC/l10n.js
  settings/js/vue-1.js.map
  settings/js/vue-2.js.map
Labels: 4. to release, backport-request, bug, feature: language l10n and translations, high

#14641 make assemblystream seekable
  apps/dav/lib/Upload/AssemblyStream.php
  apps/dav/tests/unit/Upload/AssemblyStreamTest.php
Labels: 3. to review

#14712 Remove spaming debug logs
  lib/private/Files/View.php
  lib/private/Template/CSSResourceLocator.php
Labels: 3. to review, bug

#14706 Fix language of SQLite warning, follow-up to #14682
  core/templates/installation.php
Labels: 3. to review, feature: install and update

#14689 allow renaming the root of a movable mount even if the parent folder …
  lib/private/Files/Node/Node.php
Labels: 4. to release

#14705 Deprecate marked, escapeHTML, formatDate, getURLParameter, humanFileS…
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/globals.js
Labels: 4. to release

#14643 fix database select styling in setup page
  core/css/guest.css
  core/templates/installation.php
Labels: 4. to release, design, feature: install and update

#14719 Use higher preview resolution in trashbin
  apps/files_trashbin/lib/Controller/PreviewController.php
Labels: 3. to review, papercut

#14721 Trashbin: Delete => Delete permanently
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/src/app.js
Labels: 3. to review, papercut

#14666 Don't show 'Personal' header in settings when Admin section is not there
  settings/templates/settings/frame.php
  tests/acceptance/features/access-levels.feature
  tests/acceptance/features/bootstrap/SettingsMenuContext.php
Labels: 4. to release, design, enhancement, feature: settings

#14724 CSP: set nonce for iframes
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
Labels: 3. to review, enhancement

#14736 Fix showpassword loads
  apps/user_ldap/templates/renewpassword.php
  core/templates/installation.php
  settings/templates/settings/personal/security.php
Labels: 4. to release, bug

#14737 Improve startup speed of acceptance tests
  tests/acceptance/run.sh
Labels: 3. to review, bug

#14571 Use index to mark parent as outdated, fixes: #14537
  apps/files_external/lib/Command/Notify.php
Labels: 3. to review, feature: external storage

#14739 Style of navigation links in header is too catchy
  core/css/header.scss
  core/templates/layout.user.php
Labels: 3. to review, bug, feature: activity and notification

#14744 Always register the Notifier
  apps/updatenotification/lib/AppInfo/Application.php
Labels: 3. to review, backport-request, bug, feature: activity and notification

#14747 Fix getting the access list on external storage
  lib/private/Share20/Manager.php
Labels: 3. to review, backport-request, bug

#14664 Replace the icon-class with an absolute link to an image
  .gitattributes
  apps/files/lib/Collaboration/Resources/ResourceProvider.php
  apps/files_sharing/appinfo/app.php
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/collaboration.js
  apps/files_sharing/js/dist/collaboration.js.map
  apps/files_sharing/js/dist/files_sharing.3.js
  apps/files_sharing/js/dist/files_sharing.3.js.map
  apps/files_sharing/js/dist/files_sharing.4.js
  apps/files_sharing/js/dist/files_sharing.4.js.map
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/list.php
  apps/files_sharing/src/additionalScripts.js
  apps/files_sharing/src/collaborationresourceshandler.js
  apps/files_sharing/src/views/CollaborationView.vue
  apps/files_sharing/webpack.js
  core/Controller/CollaborationResourcesController.php
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/OCP/collaboration.js
  lib/private/Collaboration/Resources/Manager.php
  lib/private/Collaboration/Resources/Resource.php
  lib/public/Collaboration/Resources/IProvider.php
  lib/public/Collaboration/Resources/IResource.php
  package-lock.json
  package.json
Labels: 3. to review, bug, feature: sharing

#14691 always allow moving mountpoints inside the same mountpoint
  lib/private/Files/View.php
Labels: 4. to release, backport-request

#14674 [app:files] Use current directory for hashing.
  apps/files/js/file-upload.js
Labels: 3. to review, backport-request, bug

#14713 Collapse 2FA admin detail settings if disabled
  settings/js/vue-1.js.map
  settings/js/vue-2.js.map
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/src/components/AdminTwoFactor.vue
Labels: 16-feedback, 4. to release

#14709 groupname like username - allow share with both
  lib/private/Share20/Manager.php
Labels: 4. to release, backport-request, bug, feature: sharing

#14753 Revert "Where is your data?"
  apps/theming/appinfo/info.xml
  apps/theming/lib/Settings/Section.php
  apps/theming/tests/ServicesTest.php
  apps/theming/tests/Settings/SectionTest.php
  core/css/styles.scss
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Settings/Manager.php
  lib/private/Settings/Personal/PersonalInfo.php
  lib/private/Settings/Theming/ServerInfo.php
  settings/Controller/ServerInfoSettingsController.php
  settings/css/_server-info.scss
  settings/css/_where-is-your-data.scss
  settings/css/settings.scss
  settings/img/theming-dark.svg
  settings/js/admin.js
  settings/routes.php
  settings/templates/settings/admin/server-info.php
  settings/templates/settings/personal/partials/where-is-your-data.php
  settings/templates/settings/personal/personal.info.php
  tests/Settings/Controller/ServerInfoSettingsControllerTest.php
  tests/lib/Settings/ManagerTest.php
Labels: 4. to release

#14578 Force enable apps
  apps/updatenotification/lib/Controller/APIController.php
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/tests/Settings/AdminTest.php
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/DependencyAnalyzer.php
  lib/private/Installer.php
  lib/private/legacy/app.php
  settings/Controller/AppSettingsController.php
  settings/js/vue-0.js
  settings/js/vue-1.js
  settings/js/vue-3.js
  settings/js/vue-3.js.map
  settings/js/vue-4.js
  settings/js/vue-4.js.map
  settings/js/vue-5.js
  settings/js/vue-5.js.map
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/routes.php
  settings/src/components/appDetails.vue
  settings/src/components/appList/appItem.vue
  settings/src/components/appManagement.vue
  settings/src/main-apps-users-management.js
  settings/src/store/apps.js
  tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
Labels: 4. to release, enhancement, feature: apps management

#14774 Temp disable bundle tests
  tests/acceptance/features/apps.feature
Labels: 4. to release

#14606 Make check for empty trusted proxies more strict
  settings/Controller/CheckSetupController.php
Labels: 3. to review, enhancement

#14695 Show sharing in menu in grid view
  apps/files/css/files.scss
  apps/files/js/fileactionsmenu.js
  apps/files/js/templates.js
  apps/files/js/templates/fileactionsmenu.handlebars
  apps/files/tests/js/fileactionsmenuSpec.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing.0.js
  apps/files_sharing/js/dist/files_sharing.0.js.map
  apps/files_sharing/js/dist/files_sharing.1.js
  apps/files_sharing/js/dist/files_sharing.1.js.map
  apps/files_sharing/src/share.js
  apps/files_sharing/tests/js/shareSpec.js
Labels: 4. to release, bug, design, feature: files, feature: sharing

#14776 Use max contrast variable to cap the generated colours
  apps/files/js/filelist.js
Labels: 4. to release, bug, design

#14778 Fix user creation using LDAP Plugin
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/UserPluginManager.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/User_LDAPTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#14786 Remove unused member "util"
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 4. to release, bug

#14790 Fix setup checks for ocm/ocs-provider
  settings/js/admin.js
Labels: 3. to review

#13721 Issue 12729 postgresql duplicate key value
  lib/private/DB/Adapter.php
  lib/private/DB/AdapterPgSql.php
  lib/private/DB/Connection.php
  lib/private/Lock/DBLockingProvider.php
  lib/public/IDBConnection.php
Labels: 3. to review, feature: locking

#14315 implement principal property search for calendar user address set property
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/DAV/GroupPrincipalBackend.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/AbstractPrincipalBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
Labels: 4. to release

#14058 Avoid replacement by user object
  lib/private/Files/Mount/ObjectHomeMountProvider.php
Labels: 4. to release, backport-request, bug, feature: filesystem

#14573 16.0.0 Beta 1
  version.php
Labels: 4. to release

#14802 Use monospaced font when printing twofactor backup codes.
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/src/service/PrintService.js
Labels: 4. to release, enhancement, feature: authentication

#14810 Select the username input after creating a user successfully
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/src/components/userList.vue
Labels: 16-feedback, 3. to review, enhancement, feature: users and groups, papercut

#14798 Allow string to be translated
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/collaboration.js
  apps/files_sharing/js/dist/collaboration.js.map
  apps/files_sharing/src/collaborationresourceshandler.js
Labels: 4. to release

#14805 Properly inject EventDispatched in BackgroundRepair
  lib/private/Migration/BackgroundRepair.php
  tests/lib/Migration/BackgroundRepairTest.php
Labels: 4. to release, bug

#14812 Force boolean type for access parameter
  lib/private/Collaboration/Resources/Manager.php
Labels: 4. to release, bug

#14813 Check if elements are set in installer
  lib/private/Installer.php
Labels: 3. to review, bug

#14809 Fix selecting an accessibility theme with the keyboard
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/src/components/itemPreview.vue
Labels: 16-feedback, 3. to review, bug, feature: accessibility, feature: settings, feature: theming

#14808 Fix personal settings fed scope tabindex
  settings/css/settings.scss
  settings/js/federationscopemenu.js
  settings/js/federationsettingsview.js
  settings/js/templates.js
  settings/js/templates/federationscopemenu.handlebars
  settings/templates/settings/personal/personal.info.php
Labels: 3. to review, feature: accessibility, feature: settings

#14801 Fetch proper translations
  lib/private/Settings/Admin/Sharing.php
  tests/lib/Settings/Admin/SharingTest.php
Labels: 4. to release

#14804 Make all filepicker strings translatable
  core/js/oc-dialogs.js
  core/templates/filepicker.html
Labels: 3. to review, feature: filepicker, feature: language l10n and translations

#14825 Set parameter type in QBMapper
  lib/public/AppFramework/Db/QBMapper.php
  tests/lib/AppFramework/Db/QBMapperTest.php
Labels: 4. to release, bug, feature: install and update

#14806 Fix filepicker's add button design
  core/css/styles.scss
Labels: 3. to review, bug, design, feature: filepicker

#14833 Bump strenghify to v0.5.8
  core/js/dist/main.js
  core/js/dist/main.js.map
  package-lock.json
  package.json
Labels: 4. to release, bug

#14838 Fix placeholder in disable message
  lib/base.php
Labels: 3. to review, backport-request, bug

#14852 Exclude compiled assets of files_sharing for transifex
  apps/files_sharing/.l10nignore
Labels: 3. to review

#14853 Make regions translatable
  settings/templates/settings/personal/personal.info.php
Labels: 4. to release, backport-request

#14854 [stable15] Fix setup checks for ocm/ocs-provider
  settings/js/admin.js
Labels: 4. to release

#14855 [stable15] Remove Google+ federation usersettings
  apps/federatedfilesharing/css/settings-personal.css
  apps/federatedfilesharing/img/social-googleplus.svg
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 3. to review

#14856 [stable14] Remove Google+ federation usersettings
  apps/federatedfilesharing/css/settings-personal.css
  apps/federatedfilesharing/img/social-googleplus.svg
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 4. to release

#14868 [stable14] Avoid replacement by user object
  lib/private/Files/Mount/ObjectHomeMountProvider.php
Labels: 3. to review

#14880 Fix settings translation sync
  settings/l10n/.gitkeep
Labels: 4. to release

#14882 [stable15] Fix translations of settings
  settings/l10n/.gitkeep
Labels: 4. to release

#14876 Always show full previews
  apps/files/css/detailsView.scss
  apps/files/js/sidebarpreviewmanager.js
Labels: 3. to review, bug, feature: files, feature: previews and thumbnails

#14878 Make sure all tables have named indexes
  apps/dav/lib/Migration/Version1004Date20170924124212.php
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version14000Date20180626223656.php
  core/Migrations/Version16000Date20190212081545.php
Labels: 3. to review, bug
