Repository nextcloud/server, pull requests merged in 2019-06, with the labels that each got.

#15868 Update JS bundle
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  settings/js/vue-0.js
  settings/js/vue-0.js.map
  settings/js/vue-4.js
  settings/js/vue-5.js
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
Labels: 3. to review

#15816 Do not autoload built in types
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/tests/unit/AppInfo/PluginManagerTest.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/ServerContainer.php
  lib/public/IContainer.php
  tests/lib/Contacts/ContactsMenu/ActionProviderStoreTest.php
Labels: 4. to release, enhancement

#15873 Add stale config
  .github/stale.yml
Labels: 3. to review

#15862 [stable14] Don't notify admins if no potentially over exposing links found
  lib/private/Repair/RemoveLinkShares.php
Labels: 3. to review, enhancement

#15861 [stable15] Don't notify admins if no potentially over exposing links found
  lib/private/Repair/RemoveLinkShares.php
Labels: 3. to review, enhancement

#15909 Fix missing login hook wih Apache/SAML login
  lib/private/legacy/user.php
Labels: 3. to review, backport-request, bug, integration

#15913 Fix mobile menu over app-content
  core/css/mobile.scss
Labels: 3. to review, backport-request, bug, design

#15912 Fix userid casting in notifications
  lib/private/Notification/Notification.php
  lib/private/Repair/RemoveLinkShares.php
  lib/public/Notification/INotification.php
Labels: 16-feedback, 4. to release, backport-request, bug

#15830 Show share settings only if incoming federated shares are allowed
  apps/federatedfilesharing/lib/Settings/Personal.php
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 4. to release, backport-request, bug

#15783 Run repair steps when enabling an app that has already been installed
  lib/private/Installer.php
Labels: 4. to release, bug

#15875 Properly theme folder icons that are accessed though imagePath
  apps/theming/lib/ThemingDefaults.php
Labels: 4. to release, bug, feature: theming

#15928 [stable15] Make accessibility app translatable
  apps/accessibility/.l10nignore
  apps/accessibility/l10n/.gitkeep
Labels: 4. to release, bug

#15933 30 issues per run on stale bot
  .github/stale.yml
Labels: 3. to review

#15931 Add documentation to config.php for share_folder
  config/config.sample.php
Labels: 4. to release, enhancement

#15937 Fix download entry shown on public share menu when not in mobile
  apps/files_sharing/css/public.scss
  tests/acceptance/features/bootstrap/PublicShareContext.php
Labels: 4. to release, bug, regression

#15938 Adjust acceptance tests to notifications based on toastify
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: 4. to release

#15947 Add core/js/dist/ to l10nignore
  core/.l10nignore
Labels: 3. to review, backport-request, bug

#15866 allow non integer version ids
  apps/files_versions/lib/Controller/PreviewController.php
  apps/files_versions/lib/Versions/IVersion.php
  apps/files_versions/lib/Versions/IVersionBackend.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/lib/Versions/Version.php
  apps/files_versions/lib/Versions/VersionManager.php
Labels: 3. to review

#15949 [stable16] Temporary fix for project translations
  core/js/dist/main.js.map
  core/src/OCP/collaboration.js
Labels: 4. to release, bug

#15935 Add strict type on Notifications tests
  apps/comments/tests/Unit/Controller/NotificationsTest.php
  lib/private/Notification/Notification.php
  lib/public/Notification/INotification.php
  tests/lib/Notification/NotificationTest.php
Labels: 4. to release, bug

#15975 One month is enough
  .github/stale.yml
Labels: 3. to review

#15961 Sharing in list: Use .hidden-visually instead of display:none for accessibility, fix #11661
  apps/files/css/files.scss
  apps/files/css/mobile.scss
Labels: 4. to release, backport-request, bug, feature: accessibility, feature: sharing, high

#15858 add LDAP integr. test for receiving share candidates with group limitation
  apps/user_ldap/lib/Group_LDAP.php
  build/integration/config/behat.yml
  build/integration/features/bootstrap/AppConfiguration.php
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/CalDavContext.php
  build/integration/features/bootstrap/LDAPContext.php
  build/integration/features/bootstrap/ShareesContext.php
  build/integration/features/bootstrap/Sharing.php
  build/integration/features/bootstrap/WebDav.php
  build/integration/ldap_features/openldap-uid-username.feature
Labels: 4. to release, backport-request, bug, enhancement, feature: ldap, regression

#15963 Remove precomposed from apple-touch-icon-precomposed
  core/templates/layout.base.php
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: 4. to release, enhancement

#15987 cache the displayname after an LDAP plugin set it
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/User_LDAPTest.php
Labels: 4. to release, backport-request, bug, feature: ldap

#16006 Allow to access source maps on apache
  lib/private/Setup.php
Labels: 4. to release, enhancement

#15993 Properly redirect if accessing invalid file though /f/ entrypoint
  apps/files/lib/Controller/ViewController.php
Labels: 4. to release, bug, feature: files

#16005 Avoid scrolling to the hidden input when toggling grid/list view
  apps/files/css/files.scss
Labels: 3. to review, backport-request, bug, feature: files

#15922 Add extendedSupport to Subscription
  core/Controller/OCSController.php
  lib/private/Support/Subscription/Registry.php
  lib/public/Support/Subscription/IRegistry.php
  lib/public/Support/Subscription/ISubscription.php
  lib/public/Util.php
  status.php
  tests/Core/Controller/OCSControllerTest.php
  tests/lib/Support/Subscription/RegistryTest.php
Labels: 4. to release, enhancement

#15960 Remove auto focus of share input field on dialog open, fix #15261
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogview.js
Labels: 4. to release, backport-request, bug, design, feature: sharing, papercut

#15869 fix loading multiple version backends from one app
  apps/files_versions/lib/AppInfo/Application.php
Labels: 3. to review

#15988 Use shared browserslist config
  .babelrc
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  package-lock.json
  package.json
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
Labels: 4. to release, enhancement, technical debt

#16011 (LDAP) API: return one base properly when multiple are configured
  apps/user_ldap/lib/ILDAPUserPlugin.php
  apps/user_ldap/lib/LDAPProvider.php
  apps/user_ldap/tests/LDAPProviderTest.php
Labels: 4. to release, backport-request, bug, feature: ldap

#16012 Add make clean
  Makefile
Labels: 4. to release

#16009 Fix window scroll container
  apps/files/js/filelist.js
Labels: 4. to release, backport-request, bug, feature: files

#15774 Let the user confirm the remote wipe
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/src/components/AuthTokenSection.vue
Labels: 4. to release, enhancement

#15964 Opt-in for generation userid, requiring email addresses
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/User_LDAPTest.php
  settings/Controller/UsersController.php
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/components/userList.vue
  settings/src/store/users.js
Labels: 3. to review, enhancement, feature: ldap, feature: users and groups

#15540 Prevent faulty logs from nested setupFS calls
  lib/private/legacy/util.php
Labels: 3. to review, backport-request, bug, feature: filesystem

#15889 handle storage exceptions when trying to set mtime
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
Labels: 3. to review, backport-request

#15997 Add sidebar icon we use in Talk and Viewer already
  core/css/icons.scss
  core/img/actions/menu-sidebar.svg
Labels: 3. to review, backport-request, design, enhancement

#16036 changes the returned key from UserID to id, in accordance with getUserData
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/store/users.js
Labels: 3. to review, enhancement, feature: users and groups

#16033 fix LDAP Wizard forgetting groups on select with search
  apps/user_ldap/js/wizard/wizardFilterOnType.js
  apps/user_ldap/js/wizard/wizardTabAbstractFilter.js
  apps/user_ldap/js/wizard/wizardTabGeneric.js
Labels: 4. to release, backport-request, bug, feature: ldap

#15888 log inner exception during dav write
  apps/dav/lib/Connector/Sabre/File.php
Labels: 4. to release, enhancement

#16068 Revert "[stable16] Fix userid casting in notifications"
  lib/private/Notification/Notification.php
  lib/public/Notification/INotification.php
Labels: 3. to review, bug

#16024 Forward OCSException to initiator
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 4. to release, backport-request, bug

#15870 Add new Provider interface for preview providers
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Preview/BMP.php
  lib/private/Preview/Bitmap.php
  lib/private/Preview/Font.php
  lib/private/Preview/GIF.php
  lib/private/Preview/Generator.php
  lib/private/Preview/GeneratorHelper.php
  lib/private/Preview/HEIC.php
  lib/private/Preview/Illustrator.php
  lib/private/Preview/Image.php
  lib/private/Preview/JPEG.php
  lib/private/Preview/MP3.php
  lib/private/Preview/MSOffice2003.php
  lib/private/Preview/MSOffice2007.php
  lib/private/Preview/MSOfficeDoc.php
  lib/private/Preview/MarkDown.php
  lib/private/Preview/Movie.php
  lib/private/Preview/Office.php
  lib/private/Preview/OpenDocument.php
  lib/private/Preview/PDF.php
  lib/private/Preview/PNG.php
  lib/private/Preview/Photoshop.php
  lib/private/Preview/Postscript.php
  lib/private/Preview/ProviderV1Adapter.php
  lib/private/Preview/ProviderV2.php
  lib/private/Preview/SVG.php
  lib/private/Preview/StarOffice.php
  lib/private/Preview/TIFF.php
  lib/private/Preview/TXT.php
  lib/private/Preview/XBitmap.php
  lib/private/PreviewManager.php
  lib/public/Preview/IProvider.php
  lib/public/Preview/IProviderV2.php
  tests/lib/Preview/GeneratorTest.php
  tests/lib/Preview/Provider.php
Labels: 3. to review

#16013 fix previews of versions with non numeric version ids
  apps/files_versions/js/files_versions.js
  apps/files_versions/js/files_versions.js.map
  apps/files_versions/src/templates/item.handlebars
  apps/files_versions/src/versioncollection.js
  apps/files_versions/src/versionmodel.js
  apps/files_versions/src/versionstabview.js
Labels: 3. to review

#15956 Fix appid argument for integrity:check-app
  core/Command/Integrity/CheckApp.php
Labels: 4. to release, backport-request

#15832 Fix full text search for groupfolders
  lib/private/Files/View.php
  lib/private/Share20/Manager.php
Labels: 3. to review, backport-request, bug

#15927 [stable15] Show share settings only if incoming federated shares are allowed
  apps/federatedfilesharing/lib/Settings/Personal.php
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 3. to review, bug

#16027 Check if uploading to lookup server is enabled before verifying
  settings/BackgroundJobs/VerifyUserData.php
Labels: 3. to review, bug, feature: federation

#16021 Fall back to black for non-color values
  core/Controller/SvgController.php
  lib/private/Template/IconsCacher.php
Labels: 3. to review, bug, feature: theming, security

#16055 Use native font stack
  apps/accessibility/css/fontdyslexic.scss
  apps/user_ldap/css/renewPassword.css
  core/css/fonts.scss
  core/css/guest.css
  core/css/server.scss
  core/css/tooltip.scss
  core/css/variables.scss
  core/fonts/LICENSE_OFL.txt
  core/fonts/NotoSans-Bold-cyrillic-ext.woff2
  core/fonts/NotoSans-Bold-cyrillic.woff2
  core/fonts/NotoSans-Bold-devanagari.woff2
  core/fonts/NotoSans-Bold-greek-ext.woff2
  core/fonts/NotoSans-Bold-greek.woff2
  core/fonts/NotoSans-Bold-latin-ext.woff2
  core/fonts/NotoSans-Bold-latin.woff2
  core/fonts/NotoSans-Bold-vietnamese.woff2
  core/fonts/NotoSans-Bold.ttf
  core/fonts/NotoSans-Regular-cyrillic-ext.woff2
  core/fonts/NotoSans-Regular-cyrillic.woff2
  core/fonts/NotoSans-Regular-devanagari.woff2
  core/fonts/NotoSans-Regular-greek-ext.woff2
  core/fonts/NotoSans-Regular-greek.woff2
  core/fonts/NotoSans-Regular-latin-ext.woff2
  core/fonts/NotoSans-Regular-latin.woff2
  core/fonts/NotoSans-Regular-vietnamese.woff2
  core/fonts/NotoSans-Regular.ttf
  core/fonts/Nunito-Bold-latin-ext.woff2
  core/fonts/Nunito-Bold.ttf
  core/fonts/Nunito-Bold.woff2
  core/fonts/Nunito-Regular-latin-ext.woff2
  core/fonts/Nunito-Regular.ttf
  core/fonts/Nunito-Regular.woff2
  core/js/tests/specs/setupchecksSpec.js
  lib/private/Avatar/Avatar.php
  lib/private/Preview/TXT.php
  settings/js/admin.js
  tests/lib/Avatar/UserAvatarTest.php
Labels: 3. to review, design, enhancement

#16040 Move font from Nunito to Noto Sans for character set compatibility
  apps/accessibility/css/fontdyslexic.scss
  apps/user_ldap/css/renewPassword.css
  core/css/fonts.scss
  core/css/guest.css
  core/css/tooltip.scss
  core/css/variables.scss
  core/fonts/LICENSE_OFL.txt
  core/fonts/NotoSans-Bold-cyrillic-ext.woff2
  core/fonts/NotoSans-Bold-cyrillic.woff2
  core/fonts/NotoSans-Bold-devanagari.woff2
  core/fonts/NotoSans-Bold-greek-ext.woff2
  core/fonts/NotoSans-Bold-greek.woff2
  core/fonts/NotoSans-Bold-latin-ext.woff2
  core/fonts/NotoSans-Bold-latin.woff2
  core/fonts/NotoSans-Bold-vietnamese.woff2
  core/fonts/NotoSans-Bold.ttf
  core/fonts/NotoSans-Regular-cyrillic-ext.woff2
  core/fonts/NotoSans-Regular-cyrillic.woff2
  core/fonts/NotoSans-Regular-devanagari.woff2
  core/fonts/NotoSans-Regular-greek-ext.woff2
  core/fonts/NotoSans-Regular-greek.woff2
  core/fonts/NotoSans-Regular-latin-ext.woff2
  core/fonts/NotoSans-Regular-latin.woff2
  core/fonts/NotoSans-Regular-vietnamese.woff2
  core/fonts/NotoSans-Regular.ttf
  core/fonts/Nunito-Bold-latin-ext.woff2
  core/fonts/Nunito-Bold.ttf
  core/fonts/Nunito-Bold.woff2
  core/fonts/Nunito-Regular-latin-ext.woff2
  core/fonts/Nunito-Regular.ttf
  core/fonts/Nunito-Regular.woff2
  core/js/tests/specs/setupchecksSpec.js
  lib/private/Avatar/Avatar.php
  lib/private/Preview/TXT.php
  settings/js/admin.js
  tests/lib/Avatar/UserAvatarTest.php
Labels: 3. to review, design, enhancement, regression

#16084 Fix file checkbox margin causing layout issues in file list
  apps/files/css/files.scss
Labels: 3. to review, bug, design

#16093 Update comments icon to use updated core one
  apps/comments/img/comments-dark.svg
  apps/comments/img/comments.svg
Labels: 3. to review, design, enhancement

#16095 Only return link to themed icon if file exists
  apps/theming/lib/ThemingDefaults.php
Labels: 3. to review, bug, feature: theming

#16096 [stable14] Fall back to black for non-color values
  core/Controller/SvgController.php
Labels: 3. to review, bug

#16088 Allow apps to store longer messages in the comments API
  lib/private/Comments/Comment.php
  lib/public/Comments/IComment.php
Labels: 3. to review, backport-request, enhancement, feature: comments

#16101 invalidates user when plugin reported deletion success
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/User_LDAPTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#16117 Use correct test avatar
  tests/data/guest_avatar_einstein_32.png
Labels: 4. to release, bug, regression

#16110 [stable15] (LDAP) API: return one base properly when multiple are configured
  apps/user_ldap/lib/ILDAPUserPlugin.php
  apps/user_ldap/lib/LDAPProvider.php
  apps/user_ldap/tests/LDAPProviderTest.php
Labels: 3. to review, bug, feature: ldap

#16118 Fix placement of icon in public share page for audio files
  apps/files_sharing/css/public.scss
  apps/files_sharing/js/public.js
Labels: 4. to release, bug, design

#16114 Fix download link included in public share page with hidden download
  apps/files_sharing/js/public.js
Labels: 3. to review, backport-request, bug

#16097 Better check reshare permissions
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/features/sharing-v1-part2.feature
  build/integration/features/sharing-v1-part3.feature
Labels: 3. to review, backport-request

#16107 verify that paths are valid for recursive local move
  lib/private/Files/Storage/Local.php
Labels: 3. to review, backport-request

#16122 Remove duplicate close-icon
  settings/js/vue-4.js
  settings/js/vue-4.js.map
  settings/src/components/appDetails.vue
  settings/src/views/Apps.vue
Labels: 4. to release, bug, design

#16121 Don't allow to disable encryption via the API
  apps/provisioning_api/lib/Controller/AppConfigController.php
Labels: 3. to review, backport-request, bug, feature: encryption (server-side)

#16010 Remove auto focus of share input field on dialog open, fix #15261
  apps/files_sharing/js/additionalScripts.js.map
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogview.js
  package-lock.json
  settings/js/vue-1.js
  settings/js/vue-1.js.map
  settings/js/vue-2.js
  settings/js/vue-2.js.map
  settings/js/vue-3.js
  settings/js/vue-3.js.map
  settings/js/vue-8.js
  settings/js/vue-8.js.map
Labels: 4. to release, bug, design, feature: sharing

#16094 [stable14] Check if uploading to lookup server is enabled before verifying
  settings/BackgroundJobs/VerifyUserData.php
Labels: 3. to review, bug, feature: settings

#16070 Do not show a internet connectivity warning if internet access is dis…
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3. to review, backport-request, bug

#16147 Move OAuth down in admin security settings
  apps/oauth2/lib/Settings/Admin.php
Labels: 4. to release, enhancement

#16145 Mark files_rightclick as shipped so it's marked as official
  core/shipped.json
Labels: 4. to release, bug, feature: apps management

#16143 [stabel 14] Better check reshare permissions
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/features/sharing-v1-part2.feature
  build/integration/features/sharing-v1-part3.feature
Labels: 3. to review

#16142 [stable15] Better check reshare permissions
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/features/sharing-v1-part2.feature
  build/integration/features/sharing-v1-part3.feature
Labels: 3. to review

#16148 Mark text as shipped so it's marked as official
  core/shipped.json
Labels: 3. to review, bug, feature: apps management

#16064 16.0.2 RC1
  version.php
Labels: 3. to review

#16063 15.0.9 RC1
  version.php
Labels: 3. to review

#16062 14.0.13 RC1
  version.php
Labels: 3. to review
