Repository nextcloud/server, pull requests merged in 2019-09, with the labels that each got.

#16961 Fix JS error on personal security page
  settings/templates/settings/personal/security.php
Labels: 4. to release

#16930 Fix npm audit warning in build
  build/package-lock.json
Labels: 3. to review

#16968 Define a guest type so Talk can use it in it's notifications
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review, bug, feature: activity and notification, high, regression

#16964 Fix sanity checks #16963
  lib/private/legacy/image.php
Labels: 4. to release, bug

#16969 When you click on thumbnail of a file, it should open the file not the sidebar
  apps/files/js/filelist.js
Labels: 4. to release, papercut

#16928 Remove reflect method form public interface
  lib/public/AppFramework/Utility/IControllerMethodReflector.php
Labels: 4. to release, technical debt

#16981 No need to wait 10 minutes for the DB to get up.
  autotest.sh
Labels: 4. to release

#16982 Only run code coverage CI on merge
  .drone.yml
Labels: 4. to release

#16990 Do not run every possible DB combo on PRs
  .drone.yml
Labels: 4. to release, enhancement

#16972 Set a default request timeout
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 4. to release, enhancement

#16975 Add clean-git target to makefile
  Makefile
Labels: 4. to release

#16980 Change the save credentials button label
  settings/css/settings.scss
  settings/templates/settings/admin/additional-mail.php
Labels: 4. to release, design, enhancement

#16932 Be sure to get the jailed path if the storage is a jail
  apps/workflowengine/lib/Manager.php
Labels: 4. to release, backport-request, bug

#16454 Dont show menu automatically when share link is clicked
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialoglinkshareview.js
  tests/acceptance/features/bootstrap/FilesAppSharingContext.php
Labels: 3. to review, bug

#16231 +nodeinfo public service
  .htaccess
  public.php
  settings/Application.php
  settings/js/admin.js
Labels: 3. to review, backport-request

#16882 Allow rotation of apppasswords
  core/Controller/AppPasswordController.php
  core/routes.php
Labels: 3. to review, enhancement

#16835 Remove orphaned calendar data from deleted subscriptions
  apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
Labels: 3. to review, backport-request, bug

#16753 [stable16] Fix tracking of auto disabled apps in Updater
  lib/private/App/AppManager.php
  lib/private/Updater.php
  lib/private/legacy/app.php
  lib/public/App/IAppManager.php
Labels: 3. to review, backport-request, bug, high

#16534 dont try to copy trash items to user if the user has not enough free space
  apps/files_trashbin/lib/Trashbin.php
Labels: 3. to review

#16970 Make push notifications for calendar reminders opt-in
  apps/dav/js/settings-admin-caldav.js
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
  apps/dav/lib/Settings/CalDAVSettings.php
  apps/dav/templates/settings-admin-caldav.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/PushProviderTest.php
Labels: 3. to review

#16999 Return the proper jailed path when requesting the root path
  lib/private/Files/Storage/Wrapper/Jail.php
Labels: 3. to review, bug

#17007 CapabilitiesTests are not DB tests
  apps/theming/tests/CapabilitiesTest.php
Labels: 4. to release, enhancement

#16919 17 Beta 4
  version.php
Labels: 3. to review, overview

#17009 Download composer packages in parallel in integration tests
  .drone.yml
Labels: 3. to review, enhancement

#17008 Log/FileTest does not require the DB
  tests/lib/Log/FileTest.php
Labels: 4. to release, enhancement

#17011 Development is 18 now!
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 3. to review

#16984 Warn user before closing when uploading a file on a upload only link
  apps/files_sharing/js/files_drop.js
Labels: bug, feature: files

#16664 Emit moveToTrash event only for the deleting user
  apps/files_trashbin/lib/Storage.php
  apps/files_trashbin/tests/StorageTest.php
Labels: 3. to review, bug, feature: files

#17006 add MAX and MIN to functionbuilder
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
Labels: 3. to review

#16977 Use different jsonpFunction for entry points
  apps/accessibility/webpack.js
  apps/comments/webpack.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing.3.js
  apps/files_sharing/js/dist/files_sharing.3.js.map
  apps/files_sharing/js/dist/files_sharing.4.js
  apps/files_sharing/js/dist/files_sharing.4.js.map
  apps/files_sharing/webpack.js
  apps/files_trashbin/webpack.js
  apps/files_versions/webpack.js
  apps/oauth2/webpack.js
  apps/systemtags/webpack.js
  apps/twofactor_backupcodes/webpack.js
  apps/updatenotification/webpack.js
  apps/workflowengine/webpack.js
  core/webpack.js
  settings/js/vue-0.js
  settings/js/vue-0.js.map
  settings/js/vue-4.js
  settings/js/vue-4.js.map
  settings/js/vue-5.js
  settings/js/vue-5.js.map
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/webpack.js
Labels: 3. to review, bug

#16997 returns 404
  public.php
  settings/js/admin.js
Labels: backport-request

#16962 Kill repair step for cypress
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC16/RemoveCypressFiles.php
Labels: 3. to review, enhancement

#16859 Add IAppManager::getAppWebPath()
  lib/private/App/AppManager.php
  lib/private/legacy/app.php
  lib/public/App/IAppManager.php
Labels: 3. to review

#16985 Properly initialize the CacheJail for sharing
  apps/files_sharing/lib/Cache.php
Labels: 3. to review, backport-request, bug

#17039 Simplify and even external icon
  core/img/actions/external.svg
Labels: 3. to review, bug, design

#16836 Fix SMB availability status + higher delay on auth issues
  apps/files_external/lib/Lib/Storage/SMB.php
  config/config.sample.php
  lib/private/Files/Cache/Storage.php
  lib/private/Files/Storage/Wrapper/Availability.php
  tests/lib/Files/Storage/Wrapper/AvailabilityTest.php
Labels: 3. to review, backport-request, bug, feature: external storage

#17078 set default CSP on NotFoundResponse
  lib/public/AppFramework/Http/NotFoundResponse.php
Labels: 3. to review, backport-request, bug

#17080 No need to test against EOL dbs
  .drone.yml
Labels: 4. to release

#16790 Allow admin configured mounts to use user configured global credentials
  apps/files_external/js/statusmanager.js
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Controller/UserGlobalStoragesController.php
  apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
  apps/files_external/templates/settings.php
Labels: 3. to review, backport-request, enhancement, feature: external storage

#16832 Add tab if alternate login present
  core/css/guest.css
  core/templates/login.php
Labels: 3. to review, enhancement, feature: authentication

#17021 Bye Spreed namespace, hello Talk!
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  lib/private/Share20/ProviderFactory.php
Labels: 3. to review, technical debt

#17084 Use the new Symfony event dispatcher signature
  lib/private/EventDispatcher/EventDispatcher.php
Labels: 3. to review, technical debt

#17067 17 RC 1
  version.php
Labels: 2. developing, overview

#17106 Add Symfony inspired typed event dispatcher method
  lib/private/EventDispatcher/EventDispatcher.php
  lib/public/EventDispatcher/IEventDispatcher.php
Labels: 3. to review, enhancement

#17116 Remove unused backupscode function
  apps/twofactor_backupcodes/appinfo/routes.php
  apps/twofactor_backupcodes/lib/Controller/SettingsController.php
Labels: 4. to release, enhancement, technical debt

#17141 Remove leftover unit test
  apps/twofactor_backupcodes/tests/Unit/Controller/SettingsControllerTest.php
Labels: 4. to release

#17074 Harden identityproof key generation
  lib/private/Security/IdentityProof/Manager.php
  lib/private/Server.php
  tests/lib/Security/IdentityProof/ManagerTest.php
Labels: 4. to release, bug

#17110 Position fixed for .toastify.toast
  core/css/toast.scss
Labels: 3. to review, design, enhancement

#17103 [stable16] Fix opening apps with Ctrl+click
  core/js/js.js
Labels: 4. to release, bug

#15936 Disable app token creation for impersonated people, ref #15539
  apps/encryption/lib/Hooks/UserHooks.php
  apps/encryption/lib/Recovery.php
  apps/encryption/tests/Controller/SettingsControllerTest.php
  apps/encryption/tests/Hooks/UserHooksTest.php
  apps/encryption/tests/RecoveryTest.php
  apps/encryption/tests/UtilTest.php
  apps/files_external/lib/Migration/DummyUserSession.php
  lib/private/User/Session.php
  lib/public/IUserSession.php
  settings/Controller/AuthSettingsController.php
  settings/Settings/Personal/Security.php
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/src/components/AuthTokenSection.vue
  settings/src/main-personal-security.js
  tests/Settings/Controller/AuthSettingsControllerTest.php
  tests/lib/Settings/Personal/SecurityTest.php
Labels: 4. to release, bug

#17151 Remove deprecated function createPreview
  lib/private/PreviewManager.php
  lib/public/IPreview.php
Labels: 3. to review, technical debt

#16976 Always use the folder icon depending on the mount type if not a share mount
  apps/files/js/mainfileinfodetailview.js
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/share.js
Labels: 4. to release, backport-request, bug

#12990 Allow options to be passed to `FileList.createFile`
  apps/files/js/filelist.js
Labels: 4. to release, enhancement

#17159 Sabre/VObject returns a DateAndOrTime object now, so adapt to it in Birthday service
  apps/dav/lib/CalDAV/BirthdayService.php
Labels: 3. to review, backport-request

#17138 Workflowengine: Fix check listing
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/store.js
Labels: 4. to release, bug

#17098 Create color-primary-light variable
  apps/theming/css/theming.scss
  core/css/css-variables.scss
  core/css/variables.scss
Labels: 4. to release, design, enhancement

#17174 properly mark birthday calendars as not shareable for now
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/Publishing/PublishPlugin.php
Labels: 3. to review, backport-request

#17162 Fix the recent/favorite/shared filename problem
  apps/files/css/mobile.scss
Labels: 3. to review, bug

#17178 Add space between dots in more-icon
  core/img/actions/more.svg
Labels: 4. to release, design, enhancement

#16929 Add theme class to body and fix for theme selection
  apps/accessibility/appinfo/info.xml
  apps/accessibility/composer/composer/autoload_classmap.php
  apps/accessibility/composer/composer/autoload_static.php
  apps/accessibility/css/dark.scss
  apps/accessibility/css/highcontrast.scss
  apps/accessibility/css/highcontrastdark.scss
  apps/accessibility/img/mode-highcontrast.jpg
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/lib/AccessibilityProvider.php
  apps/accessibility/lib/AppInfo/Application.php
  apps/accessibility/lib/Controller/AccessibilityController.php
  apps/accessibility/lib/Controller/ConfigController.php
  apps/accessibility/lib/Migration/RepairUserConfig.php
  apps/accessibility/lib/Settings/Personal.php
  apps/accessibility/src/App.vue
  apps/accessibility/src/components/itemPreview.vue
Labels: 3. to review, enhancement, feature: accessibility

#17175 Fix getById for files in appdata and the root mount
  lib/private/Files/Node/Folder.php
Labels: 3. to review, bug, feature: filesystem, technical debt

#17194 Add uid to delete temp token query
  lib/private/Authentication/Token/PublicKeyTokenMapper.php
Labels: 3. to review, bug

#17201 Use the actual password to update the tokens
  lib/private/Authentication/Login/CreateSessionTokenCommand.php
  tests/lib/Authentication/Login/CreateSessionTokenCommandTest.php
Labels: 3. to review, backport-request, bug

#17155 [stable16] Always use the folder icon depending on the mount type if not a share mount
  apps/files/js/mainfileinfodetailview.js
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/share.js
Labels: 4. to release, bug

#17177 17 RC 2
  version.php
Labels: 3. to review, overview

#17207 Fix l10n in federated file sharing
  lib/private/Share20/ProviderFactory.php
Labels: 3. to review, backport-request, bug, feature: language l10n and translations, feature: sharing

#17112 15.0.12 RC 1
  version.php
Labels: 3. to review

#17111 16.0.5 RC 1
  version.php
Labels: 3. to review, overview

#17206 catch exceptions that occur during logging
  lib/private/Log.php
Labels: 3. to review

#17017 fix "create folder" icon overlaying home icon
  core/css/styles.scss
Labels: 4. to release, backport-request, bug

#17163 Print error on data dir error
  lib/base.php
  lib/private/legacy/template.php
Labels: 3. to review, regression

#16641 Files additionalscripts to real event
  apps/comments/composer/composer/autoload_classmap.php
  apps/comments/composer/composer/autoload_static.php
  apps/comments/lib/AppInfo/Application.php
  apps/comments/lib/Listener/LoadAdditionalScripts.php
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/AppInfo/Application.php
  apps/files/lib/Controller/ViewController.php
  apps/files/lib/Event/LoadAdditionalScriptsEvent.php
  apps/files/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: 4. to release, enhancement

#17253 Fix apptoken creation
  settings/Settings/Personal/Security.php
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/src/components/AuthToken.vue
  settings/src/components/AuthTokenSection.vue
Labels: 3. to review, regression

#17240 Fix spaces being collapsed in move dialog
  core/css/styles.scss
Labels: 4. to release, backport-request, bug

#17250 Nextcloud 16.0.5
  version.php
Labels: 2. developing, overview

#17251 Nextcloud 15.0.12
  version.php
Labels: 2. developing, overview

#17249 Nextcloud 17
  version.php
Labels: 2. developing, overview

#17181 Add talk-attachment as a rich object type
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review, enhancement, technical debt

#17262 dont delete cache entries if deleting an object from object store failed
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  tests/lib/Files/ObjectStore/FailDeleteObjectStore.php
  tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php
Labels: 3. to review

#17252 Fix user with id 0 to be able to comment
  lib/private/Comments/Comment.php
  lib/private/Comments/Manager.php
Labels: 4. to release, bug, feature: comments

#14913 Fix directory detection for s3
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 4. to release, backport-request, bug

#17264 handle moveFromStorage within the same storage even when storage wrap…
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Wrapper/Jail.php
  tests/lib/Files/Storage/CommonTest.php
Labels: 3. to review

#17245 Fix "Cannot add a NOT NULL column with default value NULL"
  apps/workflowengine/composer/composer/autoload_classmap.php
  apps/workflowengine/composer/composer/autoload_static.php
  apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
Labels: 4. to release, bug

#17286 Correctly detect the mimetype from uploads
  apps/workflowengine/lib/Check/FileMimeType.php
Labels: 3. to review, backport-request, bug, feature: workflows

#17258 add (hidden) option to configure smb timeout
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review, backport-request

#15557 Fix fetching additional search results on scrolling down
  core/search/js/searchprovider.js
Labels: 4. to release, backport-request, bug, regression

#17228 Bring the default font size up to 15px
  core/css/guest.css
  core/css/styles.scss
Labels: 4. to release, design, enhancement

#17330 Revert "[stable17] Bring the default font size up to 15px"
  core/css/guest.css
  core/css/styles.scss
Labels: 4. to release, design
