Repository nextcloud/server, pull requests merged in 2019-10, with the labels that each got.

#17340 Use handlebars from node_modules (on CI)
  .drone.yml
  build/compile-handlebars-templates.sh
Labels: 3. to review, backport-request, bug, technical debt

#17348 [stable17] Use handlebars from node_modules (on CI)
  .drone.yml
  build/compile-handlebars-templates.sh
Labels: 3. to review, bug, technical debt

#17347 [stable16] Use handlebars from node_modules (on CI)
  .drone.yml
  build/compile-handlebars-templates.sh
Labels: 4. to release, bug, technical debt

#17001 reduce adressbook change events and handling
  apps/user_ldap/lib/User_Proxy.php
  lib/private/Avatar/UserAvatar.php
  tests/lib/Avatar/UserAvatarTest.php
Labels: 3. to review, backport-request, bug

#17353 Fix typo in "which"
  core/templates/twofactorsetupselection.php
Labels: 3. to review, backport-request, bug, papercut

#17350 Bring the font size down to 14px
  core/css/guest.css
  core/css/styles.scss
Labels: 4. to release, design, enhancement

#17366 Fix DB usersInGroups fetching
  lib/private/Group/Database.php
Labels: 4. to release, bug

#17002 Don't process known avatars from LDAP
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/User/UserTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#17360 Remove users management settings cleaning leftovers
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/appDetails.vue
  apps/settings/src/components/appList.vue
  apps/settings/src/components/appList/appItem.vue
  apps/settings/src/components/appList/appScore.vue
  apps/settings/src/components/appManagement.vue
  apps/settings/src/components/prefixMixin.vue
  apps/settings/src/components/svgFilterMixin.vue
  apps/settings/src/components/userList.vue
Labels: 4. to release, bug, feature: users and groups

#17388 Don't use an undefined index if not needed
  core/templates/loginflowv2/done.php
Labels: 4. to release, bug

#17363 Add Fatal logging option
  core/Command/Log/Manage.php
  tests/Core/Command/Log/ManageTest.php
Labels: 4. to release, enhancement

#16629 Use same settings for mail share as link shares
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 4. to release, bug, feature: sharing, security

#17359 Don't call basename on null
  apps/workflowengine/lib/Check/FileName.php
Labels: 4. to release, bug, feature: workflows, regression

#17357 Import router in oauth js
  apps/oauth2/src/App.vue
  package-lock.json
  package.json
Labels: 3. to review, enhancement, javascript

#17310 [stable16] Append / to data(path) for folder content request
  core/js/oc-dialogs.js
Labels: 3. to review, bug

#17311 [stable17] Append / to data(path) for folder content request
  core/src/OC/dialogs.js
Labels: 3. to review, bug

#16761 Fix shares read permissions
  .drone.yml
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  build/integration/config/behat.yml
  build/integration/features/bootstrap/Sharing.php
  build/integration/features/bootstrap/SharingContext.php
  build/integration/run-docker.sh
  build/integration/sharing_features/sharing-v1-part2.feature
  build/integration/sharing_features/sharing-v1-part3.feature
  build/integration/sharing_features/sharing-v1.feature
Labels: 4. to release, bug, feature: sharing

#17374 allow trash backends to overwrite the tooltip for trash items
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/lib/Sabre/AbstractTrash.php
  apps/files_trashbin/lib/Sabre/ITrash.php
  apps/files_trashbin/lib/Sabre/PropfindPlugin.php
  apps/files_trashbin/lib/Trash/ITrashItem.php
  apps/files_trashbin/lib/Trash/TrashItem.php
  apps/files_trashbin/src/filelist.js
Labels: 4. to release, enhancement

#17397 Fix updating and deleting authtokens
  apps/settings/lib/Controller/AuthSettingsController.php
  apps/settings/tests/Controller/AuthSettingsControllerTest.php
Labels: 4. to release, backport-request, bug

#17370 Update README.md
  README.md
Labels: 3. to review, enhancement

#17387 Allow removing federated shares of locally reshared files
  apps/federatedfilesharing/lib/FederatedShareProvider.php
Labels: 4. to release, bug, feature: federation, feature: sharing

#17411 Fix oauth client redirect
  core/Controller/ClientFlowLoginController.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
Labels: 3. to review, bug, feature: authentication

#17448 Do not follow symlinks with webpack
  webpack.common.js
Labels: 4. to release, bug

#17449 Increase server version to trigger latest migration
  version.php
Labels: 4. to release, technical debt

#17414 Show Delete Icon in Breadcrumb in Trashbin
  apps/files/js/breadcrumb.js
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/src/filelist.js
  core/css/icons.scss
  core/css/styles.scss
Labels: 4. to release, design, enhancement

#17451 Remove duplicate code
  lib/private/AppFramework/Http/Request.php
Labels: 4. to release, enhancement

#17440 Do not escape slashes in log json
  lib/private/Log/LogDetails.php
Labels: 3. to review, enhancement

#17431 make TrustedDomainHelper case insensitive
  lib/private/Security/TrustedDomainHelper.php
  tests/lib/Security/TrustedDomainHelperTest.php
Labels: 3. to review, enhancement

#17454 Kill ui-regression ci job
  .drone.yml
Labels: 4. to release

#17429 Add index on calendarid for calendarobject_props table
  core/Application.php
  core/Command/Db/AddMissingIndices.php
Labels: 3. to review, feature: dav

#17445 Add index on principaluri for schedulingobjects table
  core/Application.php
  core/Command/Db/AddMissingIndices.php
Labels: 4. to release, feature: dav

#17463 Cache the public key tokens
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: 2. developing

#17471 Raised public txt file truncation size to 10kb (#15951)
  apps/files_sharing/js/public.js
Labels: 3. to review, enhancement

#17475 Run composer install in parallel
  .drone.yml
Labels: 3. to review, enhancement

#17480 Remove unnecessary submodules steps
  .drone.yml
Labels: 3. to review, enhancement

#17458 Make renewSessionToken return the new token
  lib/private/Authentication/Token/DefaultTokenProvider.php
  lib/private/Authentication/Token/IProvider.php
  lib/private/Authentication/Token/Manager.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 4. to release, enhancement

#17276 Get single storage id using `eq` instead of `in`
  lib/private/Files/Cache/Storage.php
  lib/private/Files/Cache/StorageGlobal.php
Labels: 3. to review

#17488 Remove settings/ from phan
  build/.phan/config.php
Labels: 4. to release, enhancement

#17484 Always use the latest timestamp for merged activities
  lib/private/Activity/EventMerger.php
Labels: 3. to review, bug

#17500 [stable16] Force hide tooltips on sidebar close
  apps/files/js/filelist.js
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/OC/apps.js
Labels: 3. to review, 4. to release, bug, feature: files

#17505 Increase contast between text and placeholder in input fields
  core/css/inputs.scss
Labels: 4. to release, design, papercut

#17522 Fix ReflectionType::__toString() is deprecated
  lib/private/AppFramework/Utility/ControllerMethodReflector.php
Labels: 4. to release, technical debt

#17382 Initial state for accessibility
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/src/Accessibility.vue
  apps/accessibility/src/components/ItemPreview.vue
  apps/accessibility/src/main.js
  package-lock.json
Labels: 3. to review, enhancement, feature: accessibility

#17535 Remove deprecated legacy file actions
  apps/files/js/app.js
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
  apps/files/tests/js/appSpec.js
  apps/files/tests/js/favoritespluginspec.js
  apps/files_sharing/js/public.js
  apps/files_sharing/tests/js/appSpec.js
Labels: 3. to review, technical debt

#17433 NavigationDuplicated: catch uncaught (in promise)
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/AppList/AppItem.vue
Labels: 17-feedback, 3. to review, bug

#17332 Only cache the mimetype if the file exists
  apps/workflowengine/lib/Check/FileMimeType.php
Labels: 4. to release, backport-request, bug, feature: workflows

#17503 Set the proper filename for version downloads
  apps/files_versions/appinfo/info.xml
  apps/files_versions/composer/composer/autoload_classmap.php
  apps/files_versions/composer/composer/autoload_static.php
  apps/files_versions/lib/Sabre/Plugin.php
  apps/files_versions/lib/Sabre/VersionFile.php
Labels: 3. to review, bug, enhancement, feature: dav

#17501 List share download activity under sharing
  apps/files_sharing/lib/Activity/Filter.php
Labels: 3. to review, bug, feature: activity and notification

#17559 Deprecate TemplateManager
  apps/files/appinfo/app.php
  core/templates/filetemplates/template.html
  lib/private/Files/Type/TemplateManager.php
  lib/private/legacy/helper.php
Labels: 3. to review, technical debt

#17548 Pass on direct query parameter during login
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/LoginForm.vue
  core/src/login.js
  core/src/views/Login.vue
Labels: 4. to release, backport-request, bug

#17570 Merge all babelrc into one file
  .babelrc
  .babelrc.js
  apps/files_sharing/.babelrc.js
  apps/settings/.babelrc.js
  apps/updatenotification/.babelrc.js
  build/files-checker.php
Labels: 3. to review, bug

#17569 Allow DI in middleware
  apps/files_sharing/lib/AppInfo/Application.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
Labels: 3. to review, enhancement, technical debt

#17543 Let SCSS cleanup only run once
  lib/private/Template/SCSSCacher.php
Labels: 4. to release, bug

#17576 Add detailed users listing in occ user:info command
  core/Command/User/ListCommand.php
  core/register_command.php
Labels: 3. to review, enhancement, feature: occ, feature: users and groups

#17511 [stable16] Correctly handle emtpy string in proxyuserpwd config
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 3. to review, bug

#17557 Allow building single webpack modules
  webpack.common.js
Labels: 3. to review

#17585 added documentation links on settings pages
  apps/files_external/templates/settings.php
  apps/settings/templates/settings/admin/overview.php
  apps/settings/templates/settings/admin/security.php
  apps/theming/templates/settings-admin.php
Labels: 4. to release, backport-request, enhancement

#17575 Include the share in the Files_Sharing::loadAdditionalScripts event
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
Labels: 3. to review, backport-request, feature: sharing

#17545 Ignore unavailable entity/operation classes
  apps/workflowengine/lib/AppInfo/Application.php
Labels: 3. to review, bug, feature: workflows

#17547 Do not escape slashes for logged exceptions
  lib/private/Log.php
Labels: 3. to review, enhancement, feature: logging

#17577 Migrate help to a Controller
  apps/settings/appinfo/routes.php
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/help.php
  apps/settings/lib/Controller/HelpController.php
  apps/settings/templates/help.php
Labels: 4. to release, enhancement, technical debt

#17450 hide strange Everyone and Disabled group numbers with LDAP
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/lib/Controller/UsersController.php
  apps/settings/src/store/users.js
  apps/settings/src/views/Users.vue
Labels: 4. to release, backport-request, bug, feature: users and groups

#17595 treat LDAP error 50 as auth issue, prevents lost server connection errors
  apps/user_ldap/lib/Connection.php
Labels: 3. to review, backport-request, bug, feature: ldap

#17593 make sure that the urls for theming images are valid
  apps/theming/lib/ThemingDefaults.php
Labels: 4. to release

#17568 use OCP\EventDispatcher\Event over Symfony's deprecated Event
  apps/dav/tests/unit/Comments/RootCollectionTest.php
  apps/files_trashbin/lib/Events/MoveToTrashEvent.php
  apps/files_versions/lib/Events/CreateVersionEvent.php
  apps/twofactor_backupcodes/tests/Unit/Migration/CheckBackupCodeTest.php
  lib/private/EventDispatcher/SymfonyAdapter.php
  lib/private/Files/Cache/AbstractCacheEvent.php
  lib/public/App/ManagerEvent.php
  lib/public/Comments/CommentsEntityEvent.php
  lib/public/Comments/CommentsEvent.php
  lib/public/Console/ConsoleEvent.php
  lib/public/SabrePluginEvent.php
  lib/public/SystemTag/ManagerEvent.php
  lib/public/SystemTag/MapperEvent.php
  lib/public/SystemTag/SystemTagsEntityEvent.php
Labels: 4. to release, technical debt

#17619 [stable16] fix method scope
  apps/user_ldap/lib/Access.php
Labels: 4. to release, bug, feature: ldap

#17581 [stable17] Pass on direct query parameter during login
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/LoginForm.vue
  core/src/login.js
  core/src/views/Login.vue
Labels: 3. to review, bug

#17621 [stable17] hide strange Everyone and Disabled group numbers with LDAP
  settings/Controller/UsersController.php
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/store/users.js
  settings/src/views/Users.vue
Labels: 3. to review, bug, feature: users and groups

#17622 [stable16] hide strange Everyone and Disabled group numbers with LDAP
  settings/Controller/UsersController.php
  settings/js/vue-7.js
  settings/js/vue-7.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/store/users.js
  settings/src/views/Users.vue
Labels: 3. to review, bug, feature: users and groups

#17628 Only human readbale backup chars
  apps/twofactor_backupcodes/lib/Service/BackupCodeStorage.php
  apps/twofactor_backupcodes/tests/Unit/Service/BackupCodeStorageTest.php
Labels: 4. to release, enhancement

#17639 Add isXXX getter to Entity
  lib/public/AppFramework/Db/Entity.php
Labels: 3. to review, enhancement

#17578 [stable17] Load additional scripts on help page
  settings/help.php
Labels: 3. to review, backport-request, bug

#17156 [stable17] Always use the folder icon depending on the mount type if not a share mount
  apps/files/js/mainfileinfodetailview.js
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/share.js
Labels: 4. to release, bug

#17646 Fix help route in navigation
  lib/private/NavigationManager.php
Labels: 4. to release, bug

#17645 Run acceptance tests on PHP 7.3
  .drone.yml
  tests/acceptance/run.sh
Labels: 3. to review

#17653 [stable16] Reset and init new user form language
  settings/js/vue-7.js
  settings/js/vue-7.js.map
  settings/src/components/userList.vue
Labels: 3. to review, bug, feature: users and groups

#17482 Allow registering header/footer sections in the file lists
  apps/files/js/filelist.js
  apps/files/templates/list.php
Labels: 4. to release, enhancement, feature: files

#17616 Remove superfluous fclose
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review, bug

#17640 Use @nextcloud/browserslist-config
  package-lock.json
  package.json
Labels: 4. to release, technical debt

#17652 [stable15] Reset and init new user form language
  .drone.yml
  apps/workflowengine/lib/Check/FileMimeType.php
  build/package-lock.json
  settings/js/3.js
  settings/js/3.js.map
  settings/js/4.js.map
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js.map
  settings/package-lock.json
  settings/package.json
  settings/src/components/userList.vue
Labels: 4. to release, bug, feature: users and groups

#17469 fix filename overlapping on mobile
  apps/files/css/mobile.scss
Labels: 4. to release, backport-request, enhancement

#17678 Harden middleware check
  core/Controller/TwoFactorChallengeController.php
  core/Middleware/TwoFactorMiddleware.php
  tests/Core/Middleware/TwoFactorMiddlewareTest.php
Labels: 4. to release, enhancement

#17673 Fix jsConfigHelper lang/locale mixup
  apps/theming/lib/ThemingDefaults.php
  lib/private/TemplateLayout.php
  lib/private/legacy/defaults.php
Labels: 3. to review, bug

#17626 Fix weird KDE bug with loginflowv2
  core/Service/LoginFlowV2Service.php
Labels: 4. to release, backport-request, bug

#16789 Cleanup and do not list current user shares in getShares too
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/features/bootstrap/Sharing.php
  build/integration/sharing_features/sharing-v1-part2.feature
  build/integration/sharing_features/sharing-v1.feature
Labels: 4. to release, bug, enhancement, feature: sharing

#17693 Remove unused import Punic\Data
  apps/files_sharing/tests/Controller/PublicPreviewControllerTest.php
Labels: 3. to review, enhancement

#17691 Show first day of the week in correct language
  .eslintrc.js
  apps/settings/js/settings/personalInfo.js
Labels: 4. to release, enhancement

#17173 Make it possible to broadcast events to (web) clients
  core/Command/Broadcast/Test.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Broadcast/Events/BroadcastEvent.php
  lib/private/EventDispatcher/EventDispatcher.php
  lib/public/Broadcast/Events/IBroadcastEvent.php
  lib/public/EventDispatcher/ABroadcastedEvent.php
Labels: 3. to review, enhancement

#17712 Make sure limit is never negative
  lib/private/User/Database.php
Labels: 3. to review, bug, enhancement

#17521 Quickfix #17515
  apps/files/css/files.scss
Labels: 4. to release, backport-request, bug

#17730 Fix DAV mimetype search
  lib/private/Files/Cache/QuerySearchHelper.php
Labels: 3. to review, bug

#17740 Return null from migration to match with typehint
  apps/dav/lib/Migration/Version1012Date20190808122342.php
Labels: 3. to review, backport-request, bug

#17741 Remove constructor from IProvderFactory interface
  lib/public/Share/IProviderFactory.php
Labels: 4. to release, technical debt

#17562 Log an error in development cases when the application class was set …
  lib/public/AppFramework/App.php
Labels: 3. to review, technical debt

#17674 Do not show 'Get your own free account' on services under subscription
  lib/private/TemplateLayout.php
Labels: 3. to review, backport-request, enhancement

#17760 [stable15] Fix to strict typehint in FileMimeType
  apps/workflowengine/lib/Check/FileMimeType.php
Labels: 3. to review

#17721 17.0.1 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review, overview

#17723 15.0.13 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review, overview

#17759 unlink(....): No such file or directory at ..../lib/private/Preview/Movie.php#98
  lib/private/Preview/Movie.php
Labels: 4. to release, bug

#17722 16.0.6 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review, overview

#17756 fix action menu on mobile
  apps/files/css/files.scss
Labels: 4. to release, backport-request, design, feature: files

#17745 Remove unnedeed IE8 CSS
  apps/user_ldap/templates/renewpassword.php
Labels: technical debt

#17739 Get all shares iterable
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/sharebymail/lib/ShareByMailProvider.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  lib/public/Share/IShareProvider.php
  tests/lib/Share20/DefaultShareProviderTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, enhancement

#17683 Polish login flow v2
  core/js/login/grant.js
  core/templates/loginflow/grant.php
  core/templates/loginflowv2/done.php
  core/templates/loginflowv2/grant.php
Labels: 4. to release, enhancement
