Repository nextcloud/server, pull requests merged in 2019-08, with the labels that each got.

#16592 Fix permission check on incoming federated shares
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, bug, feature: federation

#16586 log circles and remote shares in admin_audit
  apps/admin_audit/lib/Actions/Sharing.php
Labels: 4. to release, backport-request, security

#16622 Standardize scrollbar color and width across Webkit and Firefox
  core/css/styles.scss
Labels: 3. to review, bug, design, papercut

#16624 Make sure we only fetch the file by id for the actual owner
  apps/files_versions/lib/Storage.php
Labels: 3. to review, backport-request, bug

#16525 files_external: proper user context for sharing
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Config/SimpleSubstitutionTrait.php
  apps/files_external/lib/Config/UserContext.php
  apps/files_external/lib/Config/UserPlaceholderHandler.php
  apps/files_external/lib/config.php
  apps/files_external/tests/Config/UserPlaceholderHandlerTest.php
  apps/user_ldap/lib/Handler/ExtStorageConfigHandler.php
Labels: 4. to release, backport-request, bug, feature: external storage, feature: sharing

#16633 [stable16] remove unncessary code block in share recommendations, fixed undefined var error
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogview.js
Labels: 3. to review, bug

#16643 Lets use DI where we can
  apps/files/lib/AppInfo/Application.php
Labels: 3. to review, enhancement, technical debt

#16639 Adding comparaison types: +regex +wildcard (fulltextsearch)
  lib/public/FullTextSearch/Model/ISearchRequestSimpleQuery.php
Labels: 3. to review, enhancement

#16498 Allow calendar resources/rooms to provide metadata
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJob.php
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/CalDAV/ResourceBooking/ResourcePrincipalBackend.php
  apps/dav/lib/CalDAV/ResourceBooking/RoomPrincipalBackend.php
  apps/dav/lib/Migration/Version1011Date20190725113607.php
  apps/dav/tests/unit/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJobTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/AbstractPrincipalBackendTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/ResourcePrincipalBackendTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/RoomPrincipalBackendTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Calendar/IMetadataProvider.php
  lib/public/Calendar/Resource/IResourceMetadata.php
  lib/public/Calendar/Room/IRoom.php
  lib/public/Calendar/Room/IRoomMetadata.php
Labels: 3. to review, feature: dav

#16661 prevent the server's app-navigation's css to overrule the scoped css …
  core/css/apps.scss
Labels: 3. to review, enhancement

#16668 [stable16] Fix ie app menu loading click
  core/js/js.js
Labels: 3. to review, bug

#16681 Bump nextcloud-vue to 0.12.0
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing.3.js
  apps/files_sharing/js/dist/files_sharing.3.js.map
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  package-lock.json
  package.json
  settings/js/vue-0.js
  settings/js/vue-0.js.map
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
Labels: 4. to release, feature: dependencies

#16686 Properly return an int in the getId function of the cache
  lib/private/Files/Cache/Cache.php
Labels: 3. to review, bug

#16683 Fix enable/disable user audit message
  apps/admin_audit/lib/Actions/UserManagement.php
Labels: 3. to review, backport-request, bug

#15187 Bugfix: user is not allowed
  lib/private/Setup/PostgreSQL.php
Labels: 3. to review, bug

#16638 delay sending event from app init to when they are needed
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Service/BackendService.php
Labels: 3. to review, backport-request, bug, feature: external storage

#16675 14.0.14 RC1
  version.php
Labels: 3. to review, overview

#16676 15.0.11 RC1
  version.php
Labels: 3. to review, overview

#16677 16.0.4 RC1
  version.php
Labels: 3. to review, overview

#16613 Add Feature-Policy header
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/FeaturePolicyMiddleware.php
  lib/private/AppFramework/OCS/BaseResponse.php
  lib/private/Security/FeaturePolicy/FeaturePolicy.php
  lib/private/Security/FeaturePolicy/FeaturePolicyManager.php
  lib/public/AppFramework/Http/EmptyFeaturePolicy.php
  lib/public/AppFramework/Http/FeaturePolicy.php
  lib/public/AppFramework/Http/Response.php
  lib/public/AppFramework/Http/TemplateResponse.php
  lib/public/Security/FeaturePolicy/AddFeaturePolicyEvent.php
  tests/lib/AppFramework/Controller/ControllerTest.php
  tests/lib/AppFramework/Http/DataResponseTest.php
  tests/lib/AppFramework/Http/EmptyFeaturePolicyTest.php
  tests/lib/AppFramework/Http/FeaturePolicyTest.php
  tests/lib/AppFramework/Http/ResponseTest.php
  tests/lib/AppFramework/Middleware/Security/FeaturePolicyMiddlewareTest.php
  tests/lib/Security/FeaturePolicy/AddFeaturePolicyEventTest.php
  tests/lib/Security/FeaturePolicy/FeaturePolicyManagerTest.php
Labels: 3. to review, enhancement, security

#16179 Add X-Frame-Options header to .htaccess
  .htaccess
  lib/private/legacy/response.php
Labels: 3. to review, enhancement

#16721 Correctly handle emtpy string in proxyuserpwd config
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 4. to release

#16711 Fix login flow form actions
  core/Controller/ClientFlowLoginController.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
Labels: 4. to release, bug, high

#16728 Get the proper UID
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/User/Database.php
  lib/private/User/Manager.php
  lib/public/User/Backend/IGetRealUIDBackend.php
Labels: 4. to release, bug

#14429 Show sharees via propfind
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/ShareeList.php
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
Labels: 3. to review, enhancement, feature: dav, feature: sharing

#16725 Fix loading of the syslog logging class
  lib/private/Log/Syslog.php
  lib/private/Server.php
Labels: 3. to review, bug

#16572 instead of upsert query, fallback to default on PSQL <= 9.4
  lib/private/DB/AdapterPgSql.php
  lib/private/legacy/util.php
Labels: 3. to review, backport-request, bug

#16663 files_trashbin: File can be without extension
  apps/files_trashbin/lib/Controller/PreviewController.php
Labels: 4. to release, bug

#16732 15.0.11
  version.php
Labels: 3. to review

#16733 16.0.4
  version.php
Labels: 3. to review

#16731 14.0.14
  version.php
Labels: 3. to review

#16739 Fix opening office documents from webdav network mounts on windows
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
Labels: 3. to review, bug

#16727 Reset and init new user form language
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/components/userList.vue
Labels: 4. to release, backport-request, bug, feature: users and groups

#12392 Customize presentation of accept/decline buttons in iMip mail
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: 3. to review, enhancement, feature: dav

#16741 Rename delete label to Delete folder/file
  apps/files/js/fileactions.js
Labels: 4. to release, backport-request, enhancement, feature: files

#15946 Update Encryption.php
  lib/private/Files/Stream/Encryption.php
Labels: 3. to review, bug

#16154 Make possible to focus grid/list view toggle via keyboard
  apps/files/css/files.scss
Labels: 3. to review, bug, design, feature: accessibility, feature: files

#16666 Feature/calendar/delegation
  apps/dav/appinfo/info.xml
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/Proxy/Proxy.php
  apps/dav/lib/CalDAV/Proxy/ProxyMapper.php
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/CalDAV/ResourceBooking/ResourcePrincipalBackend.php
  apps/dav/lib/CalDAV/ResourceBooking/RoomPrincipalBackend.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/Migration/Version1011Date20190806104428.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/Server.php
  apps/dav/lib/Traits/PrincipalProxyTrait.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/AbstractPrincipalBackendTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/ResourcePrincipalBackendTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/RoomPrincipalBackendTest.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_versions/lib/AppInfo/Application.php
Labels: 3. to review, enhancement, feature: dav

#16507 Fix tracking of auto disabled apps in Updater
  lib/private/App/AppManager.php
  lib/private/Updater.php
  lib/private/legacy/app.php
  lib/public/App/IAppManager.php
Labels: 3. to review, backport-request

#16408 17.0.0 Beta 1
  version.php
Labels: 2. developing

#16756 Allow Context subclasses in acceptance tests to access parent actor
  tests/acceptance/features/core/ActorAware.php
Labels: 3. to review

#16784 fix foreach error for reminder generator
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
  apps/dav/tests/unit/CalDAV/Reminder/ReminderServiceTest.php
Labels: 4. to release, bug

#16766 frame-src doesn't respect the nonce attribute
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
Labels: 3. to review, bug

#16781 Send new password instead of empty string
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/LoginForm.vue
  core/src/components/login/UpdatePassword.vue
Labels: 4. to release, bug

#16775 Make the warning about wrong permissions more clear.
  cron.php
Labels: 4. to release, enhancement

#16788 Do not enforce the parent constructor of response to be called
  lib/public/AppFramework/Http/Response.php
Labels: 3. to review, enhancement

#16796 Codechecker: removed unused use
  lib/private/App/CodeChecker/CodeChecker.php
Labels: 3. to review, technical debt

#16793 Filter more configs
  lib/private/AppConfig.php
Labels: 4. to release, backport-request, bug

#16808 Undefined variable response when server is no nextcloud anymore
  lib/private/Files/Storage/DAV.php
Labels: 4. to release, bug, feature: dav, feature: federation

#16812 Explicit cast for ProviderV1Adapter
  lib/private/Preview/ProviderV1Adapter.php
Labels: 4. to release, bug, feature: previews and thumbnails

#16811 Correctly remove apps without any releases
  lib/private/App/AppStore/Fetcher/AppFetcher.php
Labels: 4. to release, backport-request, bug, feature: apps management, feature: install and update

#16782 Stop if there is no encrypted token
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3. to review, backport-request, bug

#16822 Only trigger the events with tags that where actually assigned
  lib/private/SystemTag/SystemTagObjectMapper.php
Labels: 3. to review, bug, feature: tags

#16813 autoloader.php could raise Not AllowedException
  lib/private/TemplateLayout.php
Labels: 4. to release, bug

#16820 Change access handling of projects
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Collaboration/Resources/Manager.php
  lib/private/Repair.php
  lib/private/Repair/NC16/ClearCollectionsAccessCache.php
  version.php
Labels: 3. to review, backport-request, bug

#16798 Fix scrolling after switching to grid view
  apps/files/js/filelist.js
Labels: 3. to review, backport-request, bug

#16785 17.0.0 beta 2
  version.php
Labels: 2. developing, overview

#16840 adviced should be advised
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#16846 Always check via http and https whether htaccess is working
  lib/private/legacy/util.php
Labels: 3. to review, bug, feature: install and update, security

#16847 Only add the app-itunes-app tag if the id is set
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: 3. to review, backport-request, bug

#16845 Make the sharing constants publicly available
  lib/private/Share/Constants.php
  lib/public/Share/IShare.php
Labels: 4. to release, bug, feature: sharing

#16795 Fix report of phpstan in Limiter
  lib/private/Security/RateLimiting/Limiter.php
  lib/private/Server.php
  tests/lib/Security/RateLimiting/LimiterTest.php
Labels: 4. to release, enhancement, technical debt

#16723 Add expiration event for shares
  apps/files_sharing/lib/Activity/Providers/Groups.php
  apps/files_sharing/lib/Activity/Providers/Users.php
  lib/private/Share20/Manager.php
  lib/private/Share20/Share.php
  lib/public/Share/IShare.php
Labels: 4. to release, bug, feature: activity and notification, feature: sharing

#16722 Replace coffin emoji with cross
  apps/dav/lib/CalDAV/BirthdayService.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
Labels: 4. to release, enhancement

#16865 Cron should run every 5 mins
  settings/Settings/Admin/Server.php
  settings/templates/settings/admin/server.php
  tests/lib/Settings/Admin/ServerTest.php
Labels: 4. to release, bug, feature: settings

#16871 Fix missing parent constructor call in DAV reminder job
  apps/dav/lib/BackgroundJob/BuildReminderIndexBackgroundJob.php
Labels: 17-feedback, 4. to release, bug, feature: dav

#16875 Use custom client URL in welcome emails
  settings/Mailer/NewUserMailHelper.php
  tests/Settings/Mailer/NewUserMailHelperTest.php
Labels: 3. to review, backport-request, bug, feature: theming

#16879 Only run integration tests when PHP was modified
  .drone.yml
  tests/drone-run-integration-tests.sh
Labels: 4. to release, technical debt

#16615 Make rooms / resources automatically reply to invites
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/tests/unit/CalDAV/Schedule/PluginTest.php
Labels: 3. to review

#16872 Fix left-alignment of other results on search
  core/search/css/results.scss
Labels: 3. to review, design, enhancement

#16912 Make sure they keys are unique
  lib/private/App/CodeChecker/DeprecationCheck.php
Labels: 4. to release, technical debt

#16837 [stable16] Change access handling of projects
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Collaboration/Resources/Manager.php
  lib/private/Repair.php
  lib/private/Repair/NC16/ClearCollectionsAccessCache.php
  version.php
Labels: 3. to review, bug

#16843 17 beta 3
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review, overview

#16913 SessionMiddleware: declare session property
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/SessionMiddleware.php
  tests/lib/AppFramework/Middleware/SessionMiddlewareTest.php
Labels: 3. to review, technical debt

#16924 Add deprecation warning
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
Labels: 3. to review, technical debt

#16921 [stable16] Ignore Enter key up event on menu button toggles
  core/js/js.js
Labels: 3. to review, bug

#16925 Handle throwables in the http dispatcher
  lib/private/AppFramework/Http/Dispatcher.php
Labels: 3. to review, bug
