Repository nextcloud/server, pull requests merged in 2019-12, with the labels that each got.

#18178 Minor typo
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: 3. to review

#18159 Do not call count on null
  build/integration/features/bootstrap/CommentsContext.php
Labels: 4. to release, bug

#18183 [stable16] Trim the login name
  core/Controller/LoginController.php
Labels: 4. to release, bug

#17821 Fix files_sharing app LoadSidebar event
  apps/files_sharing/appinfo/app.php
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/main.js
  apps/files_sharing/js/dist/main.js.map
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Listener/LoadAdditionalListener.php
  apps/files_sharing/lib/Listener/LoadSidebarListener.php
  apps/files_sharing/list.php
  apps/files_sharing/src/index.js
  apps/files_sharing/src/share.js
  apps/files_sharing/tests/TestCase.php
  apps/files_sharing/webpack.js
  apps/files_trashbin/tests/TrashbinTest.php
  apps/files_versions/tests/VersioningTest.php
  tests/karma.config.js
  tests/lib/Files/EtagTest.php
Labels: 3. to review, bug, feature: sharing, high

#18167 Use PHP_VERSION_ID to check for the current php version
  lib/versioncheck.php
Labels: 3. to review, technical debt

#18151 Always return overwritehost if configured
  lib/private/AppFramework/Http/Request.php
Labels: 3. to review, bug

#18189 [stable17] Handle token insert conflicts
  lib/private/Authentication/Token/Manager.php
  tests/lib/Authentication/Token/ManagerTest.php
Labels: 4. to release, backport-request, bug, feature: authentication

#17512 add update all button
  apps/settings/css/settings.scss
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/AppList.vue
  package.json
Labels: 4. to release, feature: apps management

#18028 Add typed create user events
  apps/user_ldap/tests/LDAPProviderTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Server.php
  lib/private/User/Manager.php
  lib/public/User/Events/CreateUserEvent.php
  lib/public/User/Events/UserCreatedEvent.php
  tests/lib/Files/Config/UserMountCacheTest.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/Files/Stream/EncryptionTest.php
  tests/lib/User/ManagerTest.php
  tests/lib/User/SessionTest.php
Labels: 3. to review

#17443 Throw an invalid token exception is token is marked outdated
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Exceptions/TokenPasswordExpiredException.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: 3. to review, enhancement

#15952 Inherited Shares
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/collaboration.js
  apps/files_sharing/js/dist/collaboration.js.map
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/main.js
  apps/files_sharing/js/dist/main.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/Exceptions/SharingRightsException.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryInherited.vue
  apps/files_sharing/src/views/SharingInherited.vue
  apps/files_sharing/src/views/SharingTab.vue
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/sharing_features/sharing-v1.feature
Labels: 4. to release, feature: sharing, high

#18140 Allow inline styles for theming images
  apps/theming/lib/Controller/ThemingController.php
Labels: 4. to release, bug

#18120 respect shareapi_allow_share_dialog_user_enumeration in Principal backend for Sabre/DAV
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_versions/lib/AppInfo/Application.php
Labels: 3. to review, backport-request

#17930 l10n: Triple dot to ellipsis
  apps/files_sharing/src/components/SharingInput.vue
Labels: 4. to release, enhancement, feature: language l10n and translations

#18215 Set last-password-confirmation for setup
  lib/private/Setup.php
Labels: 3. to review, bug

#18212 Fix mixed up message and subject on notifications for file transfer
  apps/files/lib/Notification/Notifier.php
Labels: 4. to release, bug, feature: activity and notification, regression

#18209 Add missing getUser method to direct editing IToken interface
  lib/public/DirectEditing/IToken.php
Labels: 3. to review, bug, feature: files

#17949 Connection::TRANSACTION_READ_COMMITTED is deprecated
  lib/private/DB/Connection.php
Labels: 3. to review, technical debt

#17715 Honor avatar visibility settings
  core/Controller/AvatarController.php
  tests/Core/Controller/AvatarControllerTest.php
Labels: 3. to review, bug

#18220 Fix the theming tests
  apps/theming/tests/Controller/ThemingControllerTest.php
Labels: 3. to review, bug

#18161 fix generation of an url to an absolute ocs route when NC in subfolder
  lib/private/URLGenerator.php
Labels: 4. to release, bug

#17833 dont set folder size to negative values during propagation
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
  lib/private/Files/Cache/Propagator.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
  tests/lib/Files/Cache/PropagatorTest.php
Labels: 4. to release, enhancement

#18213 Fix files app LoadSidebar event
  apps/files/appinfo/app.php
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/merged-index.json
  apps/files/lib/AppInfo/Application.php
  apps/files/lib/Listener/LoadSidebarListener.php
  apps/files/src/sidebar.js
  apps/files/src/views/Sidebar.vue
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/files_sharing_tab.js
Labels: 4. to release, bug, feature: file sidebar

#17913 Catch file transfer error and stop transfer ownership command
  apps/files/lib/Service/OwnershipTransferService.php
Labels: 3. to review, bug

#18222 Properly reload file list on share accept
  apps/files/js/filelist.js
Labels: 4. to release, enhancement, feature: sharing

#18221 [stable17] Mark "Talk" active on /call/token URLs
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
Labels: 4. to release, bug

#18205 [stable17] Backport #18120
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_versions/lib/AppInfo/Application.php
Labels: 3. to review

#18163 fix filename size
  lib/private/Files/Storage/Common.php
Labels: 2. developing, bug

#17920 when a user was deleted remove them from applicable list, unless...
  apps/files_external/appinfo/app.php
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Service/DBConfigService.php
Labels: 3. to review, bug, feature: external storage

#18226 Ignore .phpunit.result.cache
  .gitignore
Labels: 3. to review, bug

#18206 Replaced history icon by the Material one
  core/img/actions/history.png
  core/img/actions/history.svg
Labels: 4. to release, design, enhancement

#18121 Add checkbox to install recommended apps during setup
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/AppList.vue
  apps/settings/src/recommendedApps.js
  apps/settings/src/views/Apps.vue
  core/Controller/SetupController.php
  core/js/setup.js
  core/templates/installation.php
Labels: 4. to release, enhancement

#18228 Fix removing groups that have a slash in the name
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/store/users.js
Labels: 4. to release, backport-request, bug

#18144 Sharee API GS fixes
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/src/components/SharingInput.vue
Labels: 4. to release, bug

#18130 Prevent creating users with existing files
  lib/private/User/Manager.php
  tests/lib/Cache/FileCacheTest.php
Labels: 3. to review, bug

#17989 Remove whitespace above file list ref #17891
  AUTHORS
  apps/files/css/files.scss
Labels: 3. to review, bug, design

#17941 Allow filtering the search results to the users home storage
  apps/dav/lib/Files/FileSearchBackend.php
  apps/dav/tests/unit/Files/FileSearchBackendTest.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/Search/SearchQuery.php
  lib/public/Files/Search/ISearchQuery.php
Labels: 3. to review, feature: dav, feature: users and groups

#18241 Allow to unfavorite all files
  apps/files/js/tagsplugin.js
Labels: 3. to review, 4. to release, backport-request, bug, feature: files

#18234 18 Beta 1
  version.php
Labels: 3. to review

#18250 Fix shipped.json
  core/shipped.json
Labels: 18-feedback, 4. to release, bug

#18242 add id to editor of direct editing
  apps/files/lib/Service/DirectEditingService.php
Labels: 4. to release, bug

#18252 Hide the tooltip if the list row is rerendered
  apps/files/js/filelist.js
Labels: 3. to review, backport-request, bug

#18262 Make sure event names is always an array
  apps/workflowengine/lib/AppInfo/Application.php
  apps/workflowengine/lib/Manager.php
Labels: 18-feedback, 4. to release, bug

#18254 rejig right to left join for sqlite's satisfaction
  apps/files_external/lib/Service/DBConfigService.php
Labels: 4. to release, bug, feature: external storage

#18257 [stable 17] Fix removing groups that have a slash in the name
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/store/users.js
Labels: 4. to release, backport-request, bug

#16057 Fix size of header menus
  core/css/header.scss
Labels: 4. to release, bug, design

#18284 [stable 16] Fix removing groups that have a slash in the name
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/store/users.js
Labels: 3. to review, bug

#18290 Fix: Using assertContains() with string haystacks is deprecated and w…
  tests/Core/Command/Apps/AppsDisableTest.php
  tests/Core/Command/Apps/AppsEnableTest.php
Labels: 3. to review, technical debt

#18285 [stable 15] Fix removing groups that have a slash in the name
  settings/js/3.js.map
  settings/js/4.js.map
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/store/users.js
Labels: 3. to review, bug

#18264 Move away from fixupbot
  .github/workflows/fixup.yml
Labels: 2. developing

#18289 Don't log the stack trace for ConnectException
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: 3. to review, bug

#17325 Decouple resource provider registration
  apps/files/lib/AppInfo/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/Collaboration/Resources/Manager.php
  lib/private/Collaboration/Resources/ProviderManager.php
  lib/private/Server.php
  lib/public/Collaboration/Resources/IManager.php
  lib/public/Collaboration/Resources/IProviderManager.php
  tests/lib/Collaboration/Resources/ManagerTest.php
  tests/lib/Collaboration/Resources/ProviderManagerTest.php
Labels: 4. to release, enhancement

#18292 Fix LDAP application class instance created directly
  apps/user_ldap/appinfo/routes.php
Labels: 3. to review, bug, technical debt

#18294 Fetch the share for the recipient
  apps/files_sharing/lib/Notification/Notifier.php
Labels: 4. to release, bug

#18288 Ensure that we don't merge broken json.
  lib/private/Files/Type/Detection.php
  lib/private/Server.php
  tests/lib/Files/Type/DetectionTest.php
Labels: 3. to review, bug, technical debt

#18287 Add mimetype for keepass database.
  resources/config/mimetypemapping.dist.json
Labels: 3. to review, enhancement

#18263 Fix search limit to home
  lib/private/Files/Cache/Cache.php
Labels: 3. to review, bug

#18231 Fix restoring shared versions
  apps/files_versions/lib/Storage.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/tests/VersioningTest.php
Labels: 3. to review, bug

#18256 Use non-depricated events for loading additional scripts in files app
  apps/files/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
  apps/files_external/lib/Service/BackendService.php
  apps/files_sharing/list.php
  lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
Labels: 3. to review

#18214 [stable15] Correctly remove apps without any releases
  lib/private/App/AppStore/Fetcher/AppFetcher.php
Labels: 3. to review, regression

#18300 Fix Argument 3 passed to OCA\Encryption\Recovery::__construct() must …
  apps/encryption/lib/AppInfo/Application.php
  apps/encryption/lib/Recovery.php
  apps/settings/lib/Controller/ChangePasswordController.php
Labels: 4. to release, regression

#18184 Move overwritehost check to isTrustedDomain
  lib/base.php
  lib/private/Security/TrustedDomainHelper.php
  tests/lib/Security/TrustedDomainHelperTest.php
Labels: 4. to release, backport-request, bug

#18299 Convert various columns in oc_mounts to bigint
  apps/settings/lib/Controller/CheckSetupController.php
  core/Command/Db/ConvertFilecacheBigInt.php
Labels: 3. to review, backport-request

#18301 Verify that is an array before accessing it
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review

#18251 Fix external sharing loading script
  apps/federatedfilesharing/appinfo/app.php
  apps/federatedfilesharing/js/external.js
  apps/federatedfilesharing/lib/AppInfo/Application.php
Labels: 18-feedback, 3. to review, bug, feature: federation, javascript

#18314 Fix ambigious fileID on search
  lib/private/Files/Cache/QuerySearchHelper.php
Labels: 3. to review

#18297 Add interface for notification handler for dimissed events
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Notification/Manager.php
  lib/public/Notification/IDismissableNotifier.php
  lib/public/Notification/IManager.php
Labels: 3. to review, enhancement

#18253 Pick a shorter name for the transfer ownership table
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/Db/TransferOwnershipMapper.php
  apps/files/lib/Migration/Version11301Date20191205150729.php
  lib/private/DB/MigrationService.php
  tests/lib/DB/MigrationsTest.php
Labels: 4. to release, feature: install and update, regression

#18190 [stable15] delay creation of the cert bundle
  lib/private/Files/Storage/DAV.php
Labels: 4. to release, bug, feature: filesystem

#18187 [stable16] delay creation of the cert bundle
  lib/private/Files/Storage/DAV.php
Labels: 4. to release, bug, feature: filesystem

#18186 [stable17] delay creation of the cert bundle
  lib/private/Files/Storage/DAV.php
Labels: 4. to release, bug, feature: filesystem

#18312 Do not disable authentication apps
  lib/private/legacy/app.php
Labels: 17-feedback, 3. to review, backport-request, bug

#18293 Add autocompletion to the ownership transfer UI
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 18-feedback, 3. to review, enhancement, feature: files, feature: users and groups

#18338 Transpile the nextcloud-vue-collection package
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  webpack.common.js
Labels: 4. to release, bug, regression

#18337 [stable17] Sharee API GS fixes
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogview.js
Labels: 4. to release, backport-request, bug

#18334 Viewer should be always enabled
  build/integration/features/provisioning-v1.feature
  core/shipped.json
  tests/lib/App/AppManagerTest.php
  tests/lib/AppTest.php
Labels: 4. to release, enhancement

#18347 [stable16] ShareeAPI GS fixes
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  core/js/sharedialogview.js
Labels: 3. to review, bug

#18342 Add offset for home limited searches
  apps/dav/lib/Files/FileSearchBackend.php
Labels: 3. to review, enhancement

#18349 Deprecate hooks, emitter and Symfony dispatcher mechanisms
  lib/private/Hooks/BasicEmitter.php
  lib/private/Hooks/Emitter.php
  lib/private/Hooks/PublicEmitter.php
  lib/private/Server.php
  lib/private/legacy/hook.php
Labels: 3. to review, technical debt

#18341 handle IPv6 addresses with an explict incoming interface at the end
  lib/private/Security/Normalizer/IpAddress.php
Labels: 3. to review, bug

#18348 Add typed events for all user hooks and legacy events
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Server.php
  lib/private/User/Session.php
  lib/public/User/Events/BeforePasswordUpdatedEvent.php
  lib/public/User/Events/BeforeUserCreatedEvent.php
  lib/public/User/Events/BeforeUserDeletedEvent.php
  lib/public/User/Events/BeforeUserLoggedInEvent.php
  lib/public/User/Events/BeforeUserLoggedInWithCookieEvent.php
  lib/public/User/Events/BeforeUserLoggedOutEvent.php
  lib/public/User/Events/PasswordUpdatedEvent.php
  lib/public/User/Events/UserChangedEvent.php
  lib/public/User/Events/UserDeletedEvent.php
  lib/public/User/Events/UserLoggedInEvent.php
  lib/public/User/Events/UserLoggedInWithCookieEvent.php
  lib/public/User/Events/UserLoggedOutEvent.php
Labels: 4. to release, enhancement, pending documentation, technical debt

#18350 Add typed events for all group hooks and legacy events
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Server.php
  lib/public/Group/Events/BeforeGroupCreatedEvent.php
  lib/public/Group/Events/BeforeGroupDeletedEvent.php
  lib/public/Group/Events/BeforeUserAddedEvent.php
  lib/public/Group/Events/BeforeUserRemovedEvent.php
  lib/public/Group/Events/GroupCreatedEvent.php
  lib/public/Group/Events/GroupDeletedEvent.php
  lib/public/Group/Events/UserAddedEvent.php
  lib/public/Group/Events/UserRemovedEvent.php
Labels: 3. to review, enhancement, technical debt

#17935 adding share type circles
  apps/dav/lib/Connector/PublicAuth.php
  lib/private/Share20/Manager.php
Labels: 3. to review, backport-request, bug, feature: dav, feature: sharing

#18358 [stable17] Fix restoring shared versions
  apps/files_versions/lib/Storage.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/tests/VersioningTest.php
Labels: 3. to review, bug

#18233 Add a dedicated page for the recommended apps installation
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/AppList.vue
  apps/settings/src/recommendedApps.js
  apps/settings/src/views/Apps.vue
  core/Controller/RecommendedAppsController.php
  core/Controller/SetupController.php
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/js/dist/main.js
  core/js/dist/maintenance.js
  core/js/dist/maintenance.js.map
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  core/routes.php
  core/src/components/setup/RecommendedApps.vue
  core/src/logger.js
  core/src/recommendedapps.js
  core/templates/recommendedapps.php
  core/webpack.js
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  package-lock.json
  package.json
Labels: 2. developing, enhancement, feature: install and update

#16642 Add accessibility label to show password checkbox
  core/templates/installation.php
Labels: 4. to release, bug, feature: accessibility

#18364 Support more IPv6 addresses in the RefreshWebcalJob
  apps/dav/lib/BackgroundJob/RefreshWebcalJob.php
  apps/dav/tests/unit/BackgroundJob/RefreshWebcalJobTest.php
Labels: 3. to review, backport-request

#18236 Allow to detect mimetype by content
  apps/workflowengine/lib/Check/FileMimeType.php
  apps/workflowengine/lib/Check/TFileCheck.php
  apps/workflowengine/lib/Service/RuleMatcher.php
  lib/private/Files/Type/Detection.php
  lib/public/Files/IMimeTypeDetector.php
  lib/public/WorkflowEngine/IFileCheck.php
  tests/lib/Files/Type/DetectionTest.php
Labels: 3. to review, bug, feature: workflows

#18343 18 Beta 2
  version.php
Labels: 2. developing, overview

#18365 Bump the CRL
  resources/codesigning/root.crl
Labels: 4. to release, backport-request

#17239 Move users management to multi line
  apps/settings/css/settings.scss
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/AppList.vue
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
  apps/settings/src/mixins/UserRowMixin.js
  tests/acceptance/features/bootstrap/UsersSettingsContext.php
  tests/acceptance/features/users.feature
Labels: 4. to release, design, feature: users and groups

#18372 clarified default permission setting string
  apps/settings/lib/Settings/Admin/Sharing.php
Labels: 4. to release, feature: sharing

#18378 removed unclear wording "non-link shares"
  apps/settings/templates/settings/admin/sharing.php
Labels: 4. to release, enhancement

#17784 Disable Clear-Site-Data for Chrom* (and Opera, Brave, etc)
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: 3. to review, enhancement

#18386 [stable17] Allow to detect mimetype by content
  apps/workflowengine/lib/Check/AbstractStringCheck.php
  apps/workflowengine/lib/Check/FileMimeType.php
  apps/workflowengine/lib/Check/FileName.php
  apps/workflowengine/lib/Check/FileSize.php
  apps/workflowengine/lib/Check/FileSystemTags.php
  apps/workflowengine/lib/Check/RequestRemoteAddress.php
  apps/workflowengine/lib/Check/RequestTime.php
  apps/workflowengine/lib/Check/UserGroupMembership.php
  lib/private/Files/Type/Detection.php
  lib/public/Files/IMimeTypeDetector.php
  lib/public/WorkflowEngine/ICheck.php
  tests/lib/Files/Type/DetectionTest.php
Labels: 3. to review, backport-request, bug, feature: workflows

#18344 17.0.2 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#18345 16.0.7 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#18346 15.0.14 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#18351 Add typed events for the filesystem/scanner
  apps/files/lib/BackgroundJob/ScanFiles.php
  apps/files/lib/Command/Scan.php
  apps/files/lib/Command/ScanAppData.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Utils/Scanner.php
  lib/public/Files/Events/BeforeFileScannedEvent.php
  lib/public/Files/Events/BeforeFolderScannedEvent.php
  lib/public/Files/Events/FileCacheUpdated.php
  lib/public/Files/Events/FileScannedEvent.php
  lib/public/Files/Events/FolderScannedEvent.php
  lib/public/Files/Events/NodeAddedToCache.php
  lib/public/Files/Events/NodeRemovedFromCache.php
  tests/lib/Files/EtagTest.php
  tests/lib/Files/Utils/ScannerTest.php
Labels: 4. to release

#18359 Dismiss transferownership notification cancels transfer
  apps/files/lib/Notification/Notifier.php
Labels: 3. to review, enhancement

#18302 Fix comments search result to work with multibyte strings
  apps/comments/lib/Search/Result.php
Labels: 3. to review, bug

#17494 Return a default user record if json is broken
  lib/private/Accounts/AccountManager.php
  lib/private/Accounts/Hooks.php
  tests/lib/Accounts/AccountsManagerTest.php
Labels: 3. to review, bug

#18401 l10n. Change grammar.
  apps/dav/templates/settings-admin-caldav.php
Labels: enhancement, feature: language l10n and translations

#18384 config.php setting to always accept internal shares
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Listener/GlobalShareAcceptanceListener.php
  config/config.sample.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  lib/public/Share/Events/ShareCreatedEvent.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, enhancement

#18417 Make it possible to find transfer to user by email
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 3. to review

#17018 Allow to force enable apps via CLI
  apps/settings/lib/Controller/AppSettingsController.php
  core/Command/App/Enable.php
  lib/private/App/AppManager.php
  lib/private/Installer.php
  lib/private/Server.php
  lib/public/App/IAppManager.php
  tests/lib/App/AppManagerTest.php
  tests/lib/AppTest.php
Labels: 4. to release, bug, feature: apps management

#18061 Load apps dav plugins on the old webdav route
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/appinfo/v1/webdav.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/tests/unit/Connector/Sabre/RequestTest/RequestTestCase.php
Labels: 3. to review, enhancement

#18425 Cleanup old log and fix share icon sidebar opening in breadcrumbs
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/src/share.js
  apps/files_sharing/src/sharebreadcrumbview.js
Labels: 4. to release, bug, feature: file sidebar, feature: sharing, regression

#18431 query FederatedFileSharing Application instead of creating it
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review, technical debt

#18430 Fix/noid/double flow
  apps/workflowengine/lib/AppInfo/Application.php
  apps/workflowengine/lib/Service/RuleMatcher.php
Labels: 3. to review, bug, feature: workflows

#18438 Remove no longer generated chunks
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
Labels: 3. to review

#18428 Return empty template for default creators
  lib/private/DirectEditing/Manager.php
  tests/lib/DirectEditing/ManagerTest.php
Labels: 3. to review, bug, feature: files

#18270 Transfer ownership function polishing
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/lib/Notification/Notifier.php
  apps/files/lib/Service/OwnershipTransferService.php
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 18-feedback, 4. to release, enhancement, feature: users and groups

#18385 Allow users to accept (internal) shares by default
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/collaboration.js
  apps/files_sharing/js/dist/collaboration.js.map
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/main.js
  apps/files_sharing/js/dist/main.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/SettingsController.php
  apps/files_sharing/lib/Listener/UserShareAcceptanceListener.php
  apps/files_sharing/lib/Settings/Personal.php
  apps/files_sharing/src/components/PersonalSettings.vue
  apps/files_sharing/src/personal-settings.js
  apps/files_sharing/templates/Settings/personal.php
  apps/files_sharing/webpack.js
Labels: 4. to release, enhancement, feature: sharing

#18422 Design fixes for recommended apps
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  core/src/components/setup/RecommendedApps.vue
Labels: 4. to release, bug, design

#18429 add a fallback locale for personal settings page
  apps/settings/lib/Settings/Personal/PersonalInfo.php
Labels: 3. to review

#18443 update app info schema files
  resources/app-info-shipped.xsd
  resources/app-info.xsd
Labels: 4. to release, bug

#18446 Don't overwrite the settings from files
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/personal-settings.js
Labels: 4. to release

#18448 pass the proper storage-internal path
  apps/workflowengine/lib/Entity/File.php
Labels: 4. to release, bug, feature: workflows, regression

#18456 Fix Office preview generation
  lib/private/Preview/Office.php
Labels: 4. to release, bug

#18461 Flows that are managing themselves do not necessarily set the entity
  apps/workflowengine/lib/Service/RuleMatcher.php
Labels: 4. to release, bug, feature: workflows

#18462 Fix listing users in groups with slash in the name
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/store/users.js
Labels: 3. to review, backport-request, bug

#18457 Use the user from the notification
  apps/files_sharing/lib/Notification/Notifier.php
Labels: 3. to review, bug

#18460 15.0.14
  version.php
Labels: 3. to review, overview

#18459 16.0.7
  version.php
Labels: 3. to review, overview

#18447 Wiswedel/inherited shares/design polishing
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryInherited.vue
  apps/files_sharing/src/views/SharingInherited.vue
Labels: 18-feedback, 3. to review, design, feature: sharing

#18469 fix credentials saving success message notification color
  apps/files_external/js/statusmanager.js
Labels: 3. to review, design, feature: external storage

#18458 17.0.2
  version.php
Labels: 2. developing, overview

#18370 18 beta 3
  version.php
Labels: 2. developing, overview

#18470 Only parse php7 code in app code checker
  lib/private/App/CodeChecker/CodeChecker.php
Labels: 4. to release, technical debt

#18449 Fix Sidebar enabled check
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/filelist.js
  apps/files/src/models/Tab.js
  apps/files/src/views/Sidebar.vue
Labels: 4. to release, bug, feature: file sidebar

#16792 Harden data and config protection .htaccess
  config/.htaccess
  lib/private/Setup.php
Labels: 3. to review, security

#18235 confirm auth on share generated by Circles
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/ocm/CloudFederationProviderFiles.php
Labels: 3. to review, enhancement, feature: sharing

#18162 flow file entity to provide the internal URL
  apps/workflowengine/lib/Entity/File.php
Labels: 3. to review, enhancement, feature: workflows

#18467 [stable17] Fix listing users in groups with slash in the name
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/store/users.js
Labels: 4. to release, backport-request, bug

#18433 Use File Node API for more download cases, skip unreadable files
  lib/private/Streamer.php
  lib/private/legacy/files.php
Labels: 4. to release, backport-request, bug, feature: files, feature: filesystem

#18484 Remaining flow frontend polishing
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Check.vue
  apps/workflowengine/src/components/Checks/FileMimeType.vue
  apps/workflowengine/src/components/Checks/file.js
  apps/workflowengine/src/components/Operation.vue
  apps/workflowengine/src/components/Workflow.vue
  apps/workflowengine/src/styles/operation.scss
  apps/workflowengine/src/workflowengine.js
  core/css/icons.scss
  core/img/categories/workflow.svg
Labels: 4. to release, bug, design, feature: workflows

#18010 add create and delete checkbox for sharesidebar
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntry.vue
  tests/acceptance/features/bootstrap/FilesAppSharingContext.php
Labels: 4. to release, feature: file sidebar

#18193 Add tooltips to display name and email
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 4. to release, enhancement

#18486 [stable16] Fix listing users in groups with slash in the name
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/store/users.js
Labels: 4. to release, bug

#18487 [stable 15] Fix listing users in groups with slash in the name
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/src/store/users.js
Labels: 4. to release, bug

#18080 adding timeout param
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Lock/ManuallyLockedException.php
Labels: 4. to release, enhancement

#18505 Always set the generated flag to false when an avatar is being set
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Avatar/UserAvatar.php
  lib/private/Repair.php
  lib/private/Repair/NC18/ResetGeneratedAvatarFlag.php
  version.php
Labels: 18-feedback, 3. to review, bug, regression

#18478 Do not generate tokens for editor IDs that do not exist
  apps/files/lib/Controller/DirectEditingController.php
  lib/private/DirectEditing/Manager.php
Labels: 3. to review, bug

#18534 Bump vue and vue-template-compiler
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  package-lock.json
  package.json
Labels: 2. developing, feature: dependencies, javascript

#18511 Movie#getThumbnail(): compare Movie#generateThumbNail() to null, not false
  lib/private/Preview/Movie.php
Labels: 3. to review, bug

#18504 Only round the real avatars
  core/css/styles.scss
Labels: 18-feedback, 4. to release, bug, regression

#18442 Restore old behavior allowing to set custom appstore
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/AppStore/Fetcher/CategoryFetcher.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
  tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
  tests/lib/App/AppStore/Fetcher/FetcherBase.php
Labels: 3. to review

#18536 Also center vertically when cropping previews
  lib/private/Preview/Generator.php
Labels: 2. developing, 3. to review, enhancement, feature: previews and thumbnails

#18509 Flow: report list of entities without array keys to frontend
  apps/workflowengine/lib/Manager.php
Labels: 3. to review, bug, feature: workflows
