Repository nextcloud/server, pull requests merged in 2019-01, with the labels that each got.

#13315 Use `latest` instead of fixed version number
  README.md
Labels: 3. to review

#13074 improve decrypt all process: list files which could not be decrypted
  lib/private/Encryption/DecryptAll.php
Labels: 3. to review, enhancement, feature: encryption (server-side)

#13316 Update background of favicon-fb.png
  core/img/favicon-fb.png
Labels: 3. to review

#13326 Add caching headers for public previews
  apps/files_sharing/lib/Controller/PublicPreviewController.php
  apps/files_sharing/tests/Controller/PublicPreviewControllerTest.php
Labels: 3. to review, backport-request, bug, feature: previews and thumbnails, feature: sharing

#13225 unbundle user_external to release it via appstore
  core/shipped.json
Labels: backport-request

#13321 [stable14] Force var to be integer
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review, bug

#10555 Only enforce schema limits for supported apps
  lib/private/DB/MigrationService.php
  tests/lib/DB/MigrationsTest.php
Labels: 3. to review, bug

#13161 Rewrite getNumberOfUnreadCommentsForFolder query
  lib/private/Comments/Manager.php
Labels: 3. to review, backport-request, enhancement

#13224 [stable14] Use only app path to get the icon on the svg api
  core/Controller/SvgController.php
Labels: 4. to release, bug

#10887 Implemented short quota-design v2
  apps/files/templates/appnavigation.php
Labels: 3. to review, design, enhancement

#13313 Remove check for outdated caches
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3. to review, technical debt

#13172 fix can change password check in case of encryption is enabled
  settings/Controller/UsersController.php
  tests/Settings/Controller/UsersControllerTest.php
Labels: 3. to review, bug, feature: encryption (server-side), feature: users and groups

#13351 Update the CRL
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#13286 Re add the uploaded file list to file drops
  apps/files_sharing/css/public.scss
  apps/files_sharing/js/files_drop.js
  apps/files_sharing/js/templates.js
  apps/files_sharing/js/templates/files_drop.handlebars
  apps/files_sharing/templates/public.php
Labels: 4. to release, backport-request, bug

#13336 Add note for Docker users running console
  console.php
Labels: 3. to review

#13134 returns a 404 instead of exception if app is not installed - #13088
  core/js/setupchecks.js
  public.php
  settings/js/admin.js
Labels: 3. to review, backport-request, bug

#13359 [stable13] Update the CRL
  resources/codesigning/root.crl
Labels: 3. to review

#13354 check anonymous OPTIONS requests file in root (not in subdir)
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/tests/unit/DAV/AnonymousOptionsTest.php
Labels: 3. to review

#13145 IE fix for apps menu
  core/css/fixes.scss
  core/css/ie.scss
Labels: 15-feedback, 4. to release, backport-request, bug, design

#13358 Install new instances with bigint filecache
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review

#13360 Transpile arrow function for ie11 compatibility
  apps/accessibility/.babelrc
  apps/accessibility/.babelrc.js
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/package-lock.json
  apps/accessibility/webpack.common.js
Labels: 3. to review, bug, feature: accessibility

#13117 Allow URI as data for vcard PHOTO
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/lib/Server.php
Labels: 4. to release, backport-request, bug, feature: dav

#13367 Throttle with correct metadata
  lib/private/User/Session.php
Labels: 4. to release, backport-request, bug

#13363 Fix loginflow with apptoken enter on iOS
  core/Controller/ClientFlowLoginController.php
  core/js/login/authpicker.js
  core/routes.php
  core/templates/loginflow/authpicker.php
Labels: 4. to release, backport-request

#13138 register and show when an LDAP user was detected as unavailable/deleted
  apps/user_ldap/lib/Command/ShowRemnants.php
  apps/user_ldap/lib/User/DeletedUsersIndex.php
  apps/user_ldap/lib/User/OfflineUser.php
  apps/user_ldap/tests/User/DeletedUsersIndexTest.php
Labels: 4. to release, backport-request, enhancement, feature: ldap

#13374 [stable13] Fix loginflow with apptoken enter on iOS
  core/Controller/ClientFlowLoginController.php
  core/js/login/authpicker.js
  core/routes.php
  core/templates/loginflow/authpicker.php
Labels: 3. to review, bug

#13348 13.0.9 RC 1
  version.php
Labels: 4. to release

#13347 14.0.5 RC 1
  version.php
Labels: 4. to release

#13346 15.0.1 RC 1
  version.php
Labels: 4. to release

#12621 Cleanup middleware registering
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  tests/lib/AppFramework/DependencyInjection/DIContainerTest.php
Labels: 3. to review, enhancement, technical debt

#13398 Fix/improve collapsible nav bullet hover
  core/css/apps.scss
Labels: 3. to review, design

#12227 Background job to cleanup leftover chunked uploads
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/UploadCleanup.php
  apps/dav/lib/Migration/ChunkCleanup.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/Upload/CleanupService.php
  apps/dav/lib/Upload/RootCollection.php
  apps/dav/lib/Upload/UploadFolder.php
  apps/dav/lib/Upload/UploadHome.php
Labels: 3. to review, technical debt

#13381 Fix apps menu overlapping
  core/css/header.scss
Labels: 4. to release, backport-request, bug, design

#13402 Use the real logger in the settings
  lib/private/Server.php
  settings/Controller/LogSettingsController.php
Labels: 3. to review, backport-request, bug, feature: logging

#13403 CSP: Allow fonts to be provided in data
  lib/public/AppFramework/Http/ContentSecurityPolicy.php
  tests/lib/AppFramework/Controller/ControllerTest.php
  tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php
  tests/lib/AppFramework/Http/DataResponseTest.php
  tests/lib/AppFramework/Http/ResponseTest.php
  tests/lib/Security/CSP/ContentSecurityPolicyManagerTest.php
Labels: 2. developing, backport-request

#13200 Cleanup of IE11 compatibility for users & apps management
  settings/js/0.js
  settings/js/0.js.map
  settings/js/3.js
  settings/js/3.js.map
  settings/js/4.js
  settings/js/4.js.map
  settings/js/5.js
  settings/js/5.js.map
  settings/js/settings-admin-security.js
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/package.json
  settings/src/main.js
Labels: 3. to review, feature: users and groups, feature: vue apps

#13406 OAuth2 client identifier must be unique
  apps/oauth2/appinfo/info.xml
  apps/oauth2/composer/composer/autoload_classmap.php
  apps/oauth2/composer/composer/autoload_static.php
  apps/oauth2/lib/Migration/Version010402Date20190107124745.php
Labels: 3. to review, enhancement

#12899 Run setupchecks when #security-warnings is present
  settings/js/admin.js
Labels: 4. to release, enhancement

#13418 HttpClient getHeader can return empty string
  lib/private/Http/Client/Response.php
Labels: 3. to review, regression

#13429 Switch around syntax of scour command for SVG image optimization
  build/image-optimization.sh
Labels: 3. to review, design, enhancement, papercut

#13436 Use nextcloud-axios in 2fa backupcodes js
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/package-lock.json
  apps/twofactor_backupcodes/package.json
  apps/twofactor_backupcodes/src/service/BackupCodesService.js
Labels: 4. to release, enhancement, javascript

#13430 Respect classification of calendar events in activity stream
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/Activity/Backend.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/lib/Migration/RemoveClassifiedEventActivity.php
Labels: 3. to review, backport-request, bug, feature: activity and notification, feature: dav, high

#13438 Use the scoped css on the personal page
  apps/twofactor_backupcodes/css/style.css
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/package-lock.json
  apps/twofactor_backupcodes/package.json
  apps/twofactor_backupcodes/src/views/PersonalSettings.vue
  apps/twofactor_backupcodes/templates/personal.php
Labels: 4. to release, enhancement, javascript

#12969 add support for boolean default
  core/Command/Db/Migrations/GenerateFromSchemaFileCommand.php
Labels: 4. to release, backport-request

#13177 Create Folders when moving files
  core/css/styles.scss
  core/js/jquery.ocdialog.js
  core/js/oc-dialogs.js
  core/templates/filepicker.html
Labels: 2. developing, enhancement, feature: filepicker, feature: files

#13439 [stable15] Respect classification of calendar events in activity stream
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/Activity/Backend.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/lib/Migration/RemoveClassifiedEventActivity.php
Labels: 3. to review, bug, feature: activity and notification, feature: dav

#13443 [stable13] Respect classification of calendar events in activity stream
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/ClassLoader.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/Activity/Backend.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/lib/Migration/RemoveClassifiedEventActivity.php
Labels: 4. to release, bug, feature: activity and notification, feature: dav

#13441 [stable14] Respect classification of calendar events in activity stream
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/Activity/Backend.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/lib/Migration/RemoveClassifiedEventActivity.php
Labels: 3. to review, bug, feature: activity and notification, feature: dav

#13452 15.0.1 RC 2
  version.php
Labels: 4. to release

#13453 14.0.5 RC 2
  version.php
Labels: 4. to release

#13467 Show the repair steps and repair info output in the web for better feedback
  core/ajax/update.php
Labels: 3. to review, backport-request

#13473 Don't log parameters on user creation in case of error/exception
  apps/provisioning_api/lib/Controller/UsersController.php
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review, backport-request, bug

#13477 13.0.9
  version.php
Labels: 4. to release

#13475 15.0.1
  version.php
Labels: 4. to release

#13485 Bundle dompurify in settings as well
  settings/js/4.js
  settings/js/4.js.map
  settings/js/5.js
  settings/js/5.js.map
  settings/js/6.js
  settings/js/6.js.map
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/package-lock.json
  settings/package.json
  settings/src/components/appDetails.vue
Labels: 4. to release, enhancement, javascript

#13501 Move accessibility to nextcloud-axios
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/package-lock.json
  apps/accessibility/package.json
  apps/accessibility/src/App.vue
Labels: 4. to release, enhancement, javascript

#13500 Updatenotifications: Include the scss in the vue component
  apps/updatenotification/css/admin.scss
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/package-lock.json
  apps/updatenotification/package.json
  apps/updatenotification/src/components/root.vue
  apps/updatenotification/templates/admin.php
  apps/updatenotification/webpack.common.js
Labels: 4. to release, enhancement, javascript

#13503 RemoveClassifiedEventActivity: check if calendar still exists
  apps/dav/lib/Migration/RemoveClassifiedEventActivity.php
Labels: 3. to review

#13491 Remove unused 'Base64' polyfill
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/main.js
  package-lock.json
  package.json
Labels: 4. to release, enhancement, technical debt

#13517 13.0.10
  version.php
Labels: 3. to review

#13516 14.0.6
  version.php
Labels: 3. to review

#13542 Bump oauth2 js deps
  .gitattributes
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/oauth2/package-lock.json
  apps/oauth2/package.json
Labels: 3. to review

#13544 Bump js deps of settings
  .gitattributes
  settings/js/settings-admin-security.js
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js
  settings/js/settings-vue.js.map
  settings/package-lock.json
  settings/package.json
Labels: 3. to review, feature: dependencies, javascript

#13140 Cache tokens when using swift's v2 authentication
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/ObjectStore/SwiftFactory.php
  lib/private/Files/ObjectStore/SwiftV2CachingAuthService.php
  tests/preseed-config.php
Labels: 3. to review

#12490 improve mail subject for mails to the owner with the password
  apps/sharebymail/lib/ShareByMailProvider.php
Labels: 3. to review, enhancement, feature: sharing

#13571 Fix duplicate select2 dep in package.json
  package.json
Labels: 4. to release, bug, technical debt

#13566 Fix click app names
  core/css/header.scss
  core/templates/layout.user.php
Labels: 3. to review, backport-request, bug

#13573 Principals can be principal/user/<name> or principal/<name> from lega…
  apps/dav/lib/Migration/RemoveClassifiedEventActivity.php
Labels: 4. to release, backport-request, bug, feature: dav

#13492 Use @babel/polyfill instead of es6-shim
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/main.js
  package-lock.json
  package.json
Labels: 4. to release, enhancement, technical debt

#13581 Correctly handle displaynames returned from the sharee API
  core/js/sharedialogview.js
Labels: 4. to release, backport-request, bug, feature: sharing, regression

#13468 don't close input stream when writing in encrypted file
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3. to review, bug

#13586 Some twofactor_backupcodes cleanup
  apps/twofactor_backupcodes/lib/BackgroundJob/CheckBackupCodes.php
  apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php
  apps/twofactor_backupcodes/lib/Db/BackupCodeMapper.php
  apps/twofactor_backupcodes/tests/Unit/BackgroundJob/CheckBackupCodeTest.php
Labels: 4. to release, enhancement

#12173 Ensure filename is possibly centered below file icons in grid view
  apps/files/css/files.scss
Labels: 3. to review, bug, design, feature: files

#13607 Fix integer background job id type error
  lib/private/BackgroundJob/JobList.php
Labels: 3. to review, backport-request, bug

#13595 Generic message on password reset
  core/Controller/LostController.php
  core/js/lostpassword.js
  tests/Core/Controller/LostControllerTest.php
Labels: 2. developing, enhancement

#13481 Provide initial state for backupcodes in template
  .gitattributes
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/lib/Provider/BackupCodesProvider.php
  apps/twofactor_backupcodes/lib/Settings/Personal.php
  apps/twofactor_backupcodes/package-lock.json
  apps/twofactor_backupcodes/package.json
  apps/twofactor_backupcodes/src/service/BackupCodesService.js
  apps/twofactor_backupcodes/src/settings.js
  apps/twofactor_backupcodes/src/store.js
  apps/twofactor_backupcodes/src/views/PersonalSettings.vue
  apps/twofactor_backupcodes/templates/personal.php
Labels: 3. to review, enhancement, javascript

#13618 Move from JSCombiner to webpack: merged-share-backend
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/merged-share-backend.js
  core/js/merged-share-backend.json
  core/webpack.common.js
  core/webpack.dev.js
  core/webpack.prod.js
  lib/private/Share/Share.php
Labels: 4. to release, enhancement, javascript

#13626 Use import instead of require
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/merged-share-backend.js
Labels: 4. to release, enhancement, javascript

#13634 update URL for federation
  apps/federatedfilesharing/lib/Settings/Personal.php
Labels: 3. to review, backport-request

#13511 Remove orphan event and contacts data
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
Labels: 3. to review, bug, feature: dav

#13407 Plain javascript api to asynchronously load javascript or css files
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/js/js.js
  core/src/OCP/index.js
  core/src/OCP/loader.js
  core/src/main.js
Labels: 3. to review, technical debt

#13650 Fix colorizeSvg with transformations that contain a comma (,)
  lib/private/Template/IconsCacher.php
Labels: 4. to release, backport-request, bug, feature: accessibility

#13654 [stable14] Fix colorizeSvg with transformations that contain a comma (,)
  lib/private/Template/IconsCacher.php
Labels: 3. to review, bug, feature: accessibility

#13664 Use warning background color & primary text color for setting warnings
  core/css/styles.scss
Labels: 4. to release, bug, design

#12381 Move/copy file picker: Remeber last destination and start in current folder
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
  core/js/oc-dialogs.js
Labels: 4. to release, enhancement

#13660 Fix template paramter
  core/Controller/ClientFlowLoginController.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
Labels: 4. to release, bug

#13567 Improve the upload progress bar layout
  apps/files/css/upload.scss
Labels: 3. to review, design, enhancement

#13674 Include static search template in JS
  core/search/js/searchprovider.js
  core/search/templates/part.results.html
Labels: 4. to release, enhancement, javascript

#13642 Allow access to addressbook unique uri
  apps/dav/lib/CardDAV/AddressBookImpl.php
  lib/private/ContactsManager.php
  lib/public/Contacts/IManager.php
  lib/public/IAddressBook.php
Labels: 4. to release, bug, feature: contacts menu, feature: dav

#13714 Allow OCS resources as well
  lib/private/AppFramework/Routing/RouteConfig.php
  tests/lib/AppFramework/Routing/RoutingTest.php
Labels: 3. to review, enhancement

#13739 cleanup shared lock if changing to exclusive lock failed
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
Labels: 3. to review, backport-request

#13738 Fix social sharing apps integration
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, backport-request, bug, feature: files, feature: sharing

#13747 Honor remember_login_cookie_lifetime
  config/config.sample.php
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: 3. to review, bug

#13730 Respect user locale in natural sort comparator
  core/js/js.js
Labels: 3. to review, bug, feature: language l10n and translations

#13757 Allow caching of the logout route
  lib/private/legacy/user.php
  tests/lib/NavigationManagerTest.php
Labels: 3. to review, enhancement

#13764 Reduce text size of text file preview, fix #13720
  lib/private/Preview/TXT.php
Labels: 4. to release, design, enhancement, feature: files, feature: previews and thumbnails

#13766 Urlencode the requesttoken
  lib/private/legacy/user.php
  tests/lib/NavigationManagerTest.php
Labels: 3. to review, bug

#13217 Add acceptance tests for moving and copying files
  tests/acceptance/config/behat.yml
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/bootstrap/FileListContext.php
  tests/acceptance/features/bootstrap/FilePickerContext.php
Labels: 3. to review

#13734 Call proper function when fetching link shares in the breadcrumb view
  apps/files_sharing/js/sharebreadcrumbview.js
  apps/files_sharing/tests/js/sharedbreadcrumviewSpec.js
Labels: 4. to release, backport-request, bug, feature: files

#13770 Add isTokenLogin argument to post login hook/event
  lib/private/Server.php
  lib/private/User/Session.php
Labels: 3. to review, feature: authentication

#13652 Fix empty content icons in header on darktheme
  apps/accessibility/css/themedark.scss
Labels: 3. to review, backport-request, bug, feature: accessibility

#13772 Show proper default locale
  lib/private/Settings/Personal/PersonalInfo.php
Labels: 3. to review, backport-request, bug

#13644 ignore non existing users when retrieving details of group members
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
Labels: 3. to review, backport-request, bug, feature: ldap, feature: users and groups

#13786 Remove .css fileending from accessibility user css route
  apps/accessibility/appinfo/routes.php
Labels: 4. to release, backport-request, bug, feature: accessibility

#13742 Add icon to restore activity
  apps/files/lib/Activity/FavoriteProvider.php
  apps/files/lib/Activity/Provider.php
  core/img/actions/history.png
Labels: 4. to release, backport-request, bug, feature: activity and notification, feature: trashbin

#13767 [stable14] Honor remember_login_cookie_lifetime
  config/config.sample.php
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: 3. to review, bug

#13761 [stable15] Fix integration of social sharing into the link popover menu
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, bug, feature: sharing

#13802 Fix long comment in dark theme
  apps/comments/css/comments.scss
  apps/comments/lib/Activity/Provider.php
Labels: 3. to review, backport-request, bug, feature: accessibility, feature: comments

#13810 Fixe links to issue templates
  .github/CONTRIBUTING.md
Labels: 3. to review

#13801 Fix for high contrast theme
  apps/accessibility/css/themehighcontrast.scss
  settings/css/settings.scss
Labels: 3. to review, bug, design, feature: accessibility

#13707 [stable13] Don't log parameters on user creation in case of error/exception
  lib/private/Log.php
Labels: 3. to review, bug

#13798 Remove legacy activity stuff
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Activity/LegacyFilter.php
  lib/private/Activity/LegacySetting.php
  lib/private/Activity/Manager.php
  lib/public/Activity/IExtension.php
  lib/public/Activity/IManager.php
  tests/lib/Activity/ManagerTest.php
Labels: 4. to release, feature: activity and notification, technical debt

#13818 Contain background jobs options in fieldset to improve accessibility
  settings/templates/settings/admin/server.php
Labels: 3. to review, bug, design, feature: accessibility, feature: settings

#13675 Fixed some LGTM alerts
  apps/files/js/filelist.js
  core/js/oc-dialogs.js
  core/js/sharedialoglinkshareview.js
  core/js/sharedialogview.js
Labels: 2. developing, enhancement

#13860 Add OC and OCA namespace declarations to the bundle
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/js/js.js
  core/src/OC/index.js
  core/src/OCA/index.js
  core/src/OCP/index.js
  core/src/globals.js
Labels: 4. to release, technical debt

#5881 Add command to move a calendar from an user to another
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/Command/ListCalendars.php
  apps/dav/lib/Command/MoveCalendar.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/Command/ListCalendarsTest.php
  apps/dav/tests/unit/Command/MoveCalendarTest.php
Labels: 3. to review, enhancement, feature: dav

#13708 [stable14] vcard avatar fixes
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/lib/Server.php
Labels: 3. to review

#13867 Move OCA.Apps to the server bundle
  core/js/apps.js
  core/js/core.json
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/merged-template-prepend.json
  core/src/OC/apps.js
  core/src/OC/index.js
  core/src/main.js
Labels: 3. to review, technical debt

#13855 Throttle getstoragestats.php calls and allow simultaneous uploads
  apps/files/js/file-upload.js
  apps/files/js/files.js
Labels: 3. to review, feature: files

#13791 Do not generate dark version of the view-icons w/ shadows
  core/css/icons.scss
Labels: 4. to release, design, enhancement

#10874 Clears the local storage after logout
  core/Controller/LoginController.php
  core/js/login.js
Labels: 4. to release, enhancement

#13866 always use multipart uploader for s3 uploads
  lib/private/Files/ObjectStore/S3ObjectTrait.php
  tests/lib/Files/ObjectStore/S3Test.php
Labels: 3. to review, feature: filesystem

#13843 Add ico as avatar
  apps/dav/lib/CardDAV/PhotoCache.php
Labels: 3. to review, bug, client: 💻 desktop, client: 🤖🍏 mobile

#13865 fix paged search with multiple bases (LDAP)
  .drone.yml
  apps/user_ldap/lib/Access.php
  build/integration/ldap_features/ldap-openldap.feature
  build/integration/ldap_features/openldap-uid-username.feature
Labels: 3. to review, backport-request, bug, feature: ldap

#13883 Fix dropping a folder on a folder row
  apps/files/js/file-upload.js
Labels: 4. to release, backport-request, bug, feature: files

#13869 Clean pending 2FA authentication on password reset
  core/Controller/LostController.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  tests/Core/Controller/LostControllerTest.php
Labels: 4. to release, backport-request, enhancement

#13880 Expose subadmin to OCP
  apps/dav/tests/unit/CalDAV/Activity/Filter/GenericTest.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Server.php
  lib/private/SubAdmin.php
  lib/public/Group/ISubAdmin.php
  tests/Settings/Controller/AppSettingsControllerTest.php
  tests/lib/SubAdminTest.php
Labels: 4. to release, enhancement

#13886 add fallback for trashbin original location
  apps/files_trashbin/lib/Trash/LegacyTrashBackend.php
Labels: 3. to review, backport-request

#13897 Fix updating the password of a link share when passwords are enforced
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/share/sharedialoglinkshareview_popover_menu.handlebars
  core/js/sharedialoglinkshareview.js
  core/js/sharetemplates.js
Labels: 3. to review, bug, feature: files, feature: sharing, regression

#13830 Allow shared versions again in legacy backend
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
Labels: 4. to release, backport-request, bug, feature: versions

#13237 Improve data directory write checking for NFS mounts
  lib/private/legacy/util.php
Labels: 3. to review, bug, enhancement

#13901 [stable14] Fix updating the password of a link share when passwords are enforced
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, bug, feature: files, feature: sharing, regression

#13900 [stable15] Fix updating the password of a link share when passwords are enforced
  core/js/share/sharedialoglinkshareview_popover_menu.handlebars
  core/js/sharedialoglinkshareview.js
  core/js/sharetemplates.js
Labels: 3. to review, bug, feature: files, feature: sharing, regression

#12364 Ability to select file ranges with mouse or touchscreen
  apps/files/css/files.scss
  apps/files/js/app.js
  apps/files/js/filelist.js
  apps/files/js/filemultiselectmenu.js
Labels: 4. to release, enhancement, feature: files

#13412 forward error message from password policy
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review, backport-request

#13891 Remove warning in case of external storage error
  apps/files_external/js/statusmanager.js
Labels: 4. to release, backport-request, enhancement

#13917 [stable13] Clean pending 2FA authentication on password reset
  core/Controller/LostController.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3. to review

#13916 [stable14] Clean pending 2FA authentication on password reset
  core/Controller/LostController.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  tests/Core/Controller/LostControllerTest.php
Labels: 4. to release

#13903 Move OCP.AppConfig, OCP.Comments and OCP.WhatsNew to the server bundle
  core/js/core.json
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/js/merged-template-prepend.json
  core/js/public/appconfig.js
  core/js/public/comments.js
  core/js/public/whatsnew.js
  core/src/OC/appconfig.js
  core/src/OCP/appconfig.js
  core/src/OCP/comments.js
  core/src/OCP/index.js
  core/src/OCP/whatsnew.js
Labels: 4. to release, technical debt

#13923 [stable14] fix paged search with multiple bases (LDAP)
  .drone.yml
  apps/user_ldap/lib/Access.php
  build/integration/ldap_features/ldap-openldap.feature
  build/integration/ldap_features/openldap-uid-username.feature
Labels: 4. to release, bug, feature: ldap

#12785 Unify headers menu design, fix click area
  core/css/apps.scss
  core/css/header.scss
  core/js/js.js
  core/templates/layout.user.php
Labels: 4. to release, bug, design, enhancement

#13924 Add a key parameter to the new initial state API
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/lib/Provider/BackupCodesProvider.php
  apps/twofactor_backupcodes/src/settings.js
  apps/twofactor_backupcodes/templates/personal.php
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/OCP/index.js
  core/src/OCP/initialstate.js
  lib/private/InitialStateService.php
  lib/public/IInitialStateService.php
  tests/lib/InitialStateServiceTest.php
Labels: 4. to release, enhancement

#13928 [stable14] Remove .css fileending from accessibility user css route
  apps/accessibility/appinfo/routes.php
Labels: 4. to release, bug

#12636 handle mail send error gracefully
  lib/private/Share20/Manager.php
Labels: 4. to release, backport-request, bug, feature: sharing

#13922 [stable14] ignore non existing users when retrieving details of group members
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
Labels: 4. to release, bug, feature: ldap, feature: users and groups

#13914 13.0.11 RC 1
  version.php
Labels: 4. to release

#13913 14.0.7 RC 1
  version.php
Labels: 4. to release

#13912 15.0.3 RC 1
  version.php
Labels: 4. to release

#13894 Allow provider to returns indexeable documents by chunks
  lib/public/FullTextSearch/IFullTextSearchProvider.php
Labels: 4. to release, enhancement

#13899 Emit event to load additionalscripts
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
  lib/public/AppFramework/Http/TemplateResponse.php
  tests/lib/AppFramework/Middleware/AdditionalScriptsMiddlewareTest.php
Labels: 4. to release, enhancement
