Repository nextcloud/server, pull requests merged in 2019-02, with the labels that each got.

#13956 Move OC.Plugins, OC.msg and OC.Notification to the server bundle
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/js/js.js
  core/src/OC/index.js
  core/src/OC/msg.js
  core/src/OC/notification.js
  core/src/OC/plugins.js
Labels: 3. to review, technical debt

#13261 only show "Add to your Nextcloud" on share link if federation is acti…
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 4. to release, feature: federation, feature: sharing

#12917 Added Drozone to favorites quickaccess
  apps/files/css/files.scss
  apps/files/js/filelist.js
  apps/files/js/navigation.js
  core/css/icons.scss
  core/css/variables.scss
Labels: 3. to review, design, enhancement

#13960 Move global helper functions to the bundle and deprecate some of them
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/js/js.js
  core/src/Util/format-date.js
  core/src/Util/get-url-parameter.js
  core/src/Util/relative-modified-date.js
  core/src/globals.js
Labels: 4. to release, technical debt

#13927 Don't call apc_delete_file and apc_clear_cache anymore
  lib/private/Config.php
  lib/private/legacy/util.php
Labels: 3. to review, technical debt

#13947 trim filename in webfrontend for windows compatibility
  apps/files/js/filelist.js
  apps/files/js/newfilemenu.js
Labels: 3. to review, bug, feature: files

#13970 Do not try to load js moved to bundle
  lib/private/legacy/template.php
Labels: 3. to review

#13796 Move calendar settings into basic settings
  apps/dav/templates/settings-admin-caldav.php
  core/css/inputs.scss
Labels: 4. to release, design, enhancement, feature: settings

#13548 Publish event for app token create/update/delete
  settings/Activity/Provider.php
  settings/Controller/AuthSettingsController.php
  tests/Settings/Controller/AuthSettingsControllerTest.php
Labels: 4. to release, enhancement

#13846 Check app path for enableAppForGroups
  lib/private/App/AppManager.php
  tests/lib/App/AppManagerTest.php
Labels: 3. to review, enhancement

#11304 Make the data year in the template dynamic by using date().
  themes/example/defaults.php
Labels: 4. to release, enhancement

#13877 SCSS: add background on app section:hover
  settings/css/settings.scss
Labels: 4. to release, design, enhancement

#14015 No need to explicitly load bundle dependencies
  apps/comments/lib/AppInfo/Application.php
  apps/systemtags/appinfo/app.php
  apps/systemtags/templates/admin.php
  apps/workflowengine/lib/AppInfo/Application.php
Labels: 3. to review, enhancement

#14024 It is getURLParameter not getUrlParameter
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/globals.js
Labels: 4. to release, regression

#13954 Show original path in trashbin
  apps/files_trashbin/js/filelist.js
Labels: 3. to review, backport-request, bug, feature: trashbin, regression

#14030 Fix OC.addStyle and OC.addScript
  core/js/js.js
Labels: 3. to review, regression

#14053 Do not load bundled jstimezonedetect
  apps/workflowengine/lib/AppInfo/Application.php
  core/templates/login.php
Labels: 3. to review, bug

#14057 Ignore compiled assets in settings/
  settings/.l10nignore
Labels: 3. to review

#12573 Do not do redirect handling when loggin out
  core/Controller/LoginController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/Exceptions/ReloadExecutionException.php
  lib/private/AppFramework/Middleware/Security/ReloadExecutionMiddleware.php
Labels: 3. to review

#14063 13.0.11
  version.php
Labels: 3. to review

#14062 14.0.7
  version.php
Labels: 3. to review

#14061 15.0.3
  version.php
Labels: 3. to review

#14076 [stable15] Make external storages browsable again in the web UI
  apps/files_external/js/statusmanager.js
Labels: 3. to review, backport-request, bug, feature: external storage, regression

#14077 15.0.4
  version.php
Labels: 4. to release

#10248 Introduces avatars for guest users
  core/Controller/AvatarController.php
  core/Controller/GuestAvatarController.php
  core/routes.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Avatar/Avatar.php
  lib/private/Avatar/AvatarManager.php
  lib/private/Avatar/GuestAvatar.php
  lib/private/Avatar/UserAvatar.php
  lib/private/Repair.php
  lib/private/Repair/ClearGeneratedAvatarCache.php
  lib/private/Server.php
  lib/public/Files/SimpleFS/InMemoryFile.php
  lib/public/IAvatarManager.php
  tests/Core/Controller/AvatarControllerTest.php
  tests/Core/Controller/GuestAvatarControllerTest.php
  tests/data/guest_avatar_einstein_32.png
  tests/data/guest_avatar_einstein_32.svg
  tests/data/test.pdf
  tests/lib/Avatar/AvatarManagerTest.php
  tests/lib/Avatar/GuestAvatarTest.php
  tests/lib/Avatar/UserAvatarTest.php
  tests/lib/Files/SimpleFS/InMemoryFileTest.php
  tests/lib/Repair/ClearGeneratedAvatarCacheTest.php
  tests/lib/ServerTest.php
Labels: 4. to release, enhancement

#14023 Fix: Check if `$this->params['user']` is an array
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review, bug, feature: filesystem

#13969 No need to emit additonalscript event on public pages
  core/Controller/ClientFlowLoginController.php
  core/Controller/TwoFactorChallengeController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
  lib/public/AppFramework/Http/StandaloneTemplateResponse.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
  tests/lib/AppFramework/Middleware/AdditionalScriptsMiddlewareTest.php
Labels: 3. to review, enhancement

#13748 add event for inserting cache entries
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Storage.php
  lib/public/Files/Cache/CacheInsertEvent.php
  tests/lib/Files/Node/FolderTest.php
Labels: 3. to review

#14069 [14] update icewind/smb to 3.0.1
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/ClassLoader.php
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/System.php
  apps/files_external/3rdparty/icewind/smb/src/TimeZoneProvider.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php
Labels: 3. to review

#14068 [15] update icewind/smb to 3.0.1
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/ClassLoader.php
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/System.php
  apps/files_external/3rdparty/icewind/smb/src/TimeZoneProvider.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php
Labels: 3. to review

#14067 [13] update icewind/smb to 2.0.6
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/ClassLoader.php
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Share.php
  apps/files_external/3rdparty/icewind/smb/src/System.php
  apps/files_external/3rdparty/icewind/smb/src/TimeZoneProvider.php
Labels: 3. to review

#13819 Unify the HTML encoding handling with other ROS apps
  apps/comments/lib/Activity/Provider.php
  lib/public/Activity/IEvent.php
  lib/public/Notification/INotification.php
Labels: 3. to review, bug, client: 💻 desktop, client: 🤖🍏 mobile, feature: activity and notification, technical debt

#13986 Repair step to remove "photo." files created by photocache
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC16/CleanupCardDAVPhotoCache.php
Labels: 4. to release, enhancement

#13702 Make it possible to rename app passwords
  build/integration/features/bootstrap/Auth.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Token/DefaultToken.php
  lib/private/Authentication/Token/INamedToken.php
  lib/private/Authentication/Token/PublicKeyToken.php
  settings/Controller/AuthSettingsController.php
  settings/css/settings.scss
  settings/js/authtoken_view.js
  settings/js/templates.js
  settings/js/templates/authtoken.handlebars
  tests/Settings/Controller/AuthSettingsControllerTest.php
Labels: 3. to review, enhancement

#13982 [stable15] Clean code and fix drop zone shadow
  apps/files/css/files.scss
  apps/files/js/filelist.js
  apps/files/js/navigation.js
  core/css/icons.scss
  core/css/variables.scss
Labels: 3. to review, bug, design

#14060 Use the new method instead of the deprecated wrapper
  apps/files/js/fileactions.js
Labels: 3. to review, bug

#14013 Move core/systemtags to webpack
  apps/systemtags/appinfo/app.php
  core/js/dist/systemtags.js
  core/js/dist/systemtags.js.map
  core/js/systemtags/merged-systemtags.js
  core/js/systemtags/merged.json
  core/webpack.common.js
  package-lock.json
  package.json
Labels: 3. to review, enhancement, javascript

#13097 Where is your data?
  apps/theming/lib/Settings/Section.php
  apps/theming/tests/ServicesTest.php
  apps/theming/tests/Settings/SectionTest.php
  core/css/styles.scss
  lib/private/Settings/Manager.php
  lib/private/Settings/Personal/PersonalInfo.php
  lib/private/Settings/Theming/ServerInfo.php
  settings/Controller/ServerInfoSettingsController.php
  settings/css/_server-info.scss
  settings/css/_where-is-your-data.scss
  settings/css/settings.scss
  settings/img/theming-dark.svg
  settings/js/admin.js
  settings/routes.php
  settings/templates/settings/admin/server-info.php
  settings/templates/settings/personal/partials/where-is-your-data.php
  settings/templates/settings/personal/personal.info.php
  tests/Settings/Controller/ServerInfoSettingsControllerTest.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, design, enhancement, feature: settings

#14144 Update autoloaders
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review, bug

#14143 Add a link to the notification to create the backup codes
  apps/twofactor_backupcodes/lib/Notifications/Notifier.php
  apps/twofactor_backupcodes/tests/Unit/Notification/NotifierTest.php
Labels: 3. to review, bug, feature: activity and notification

#14149 Fix the thorrtler whitelist bitmask
  lib/private/Security/Bruteforce/Throttler.php
  tests/lib/Security/Bruteforce/ThrottlerTest.php
Labels: 3. to review, bug

#14148 Move to single webpack config
  .drone.yml
  apps/oauth2/Makefile
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/oauth2/package-lock.json
  apps/oauth2/package.json
  apps/oauth2/webpack.dev.js
  apps/oauth2/webpack.js
  apps/oauth2/webpack.prod.js
  build/files-checker.php
  core/webpack.js
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 4. to release, enhancement, javascript

#14141 Move files_trashbin to webpack
  apps/files_trashbin/.l10nignore
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/list.php
  apps/files_trashbin/src/app.js
  apps/files_trashbin/src/filelist.js
  apps/files_trashbin/src/files_trashbin.js
  apps/files_trashbin/src/trash.scss
  apps/files_trashbin/webpack.js
  webpack.common.js
Labels: 4. to release, enhancement, javascript

#14177 Fix small glitches in update notification page
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/root.vue
  settings/css/settings.scss
Labels: 4. to release, backport-request

#14035 Fix expiration date changing for file shared by link
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialoglinkshareview.js
Labels: 4. to release, backport-request, bug

#14166 Allow attaching plugins to the ShareTabView and trigger event on render
  apps/files_sharing/js/sharetabview.js
Labels: 3. to review, enhancement, feature: files, feature: sharing

#14005 Move files_versions to webpack
  .gitattributes
  apps/files_versions/.l10nignore
  apps/files_versions/appinfo/app.php
  apps/files_versions/js/files_versions.js
  apps/files_versions/js/files_versions.js.map
  apps/files_versions/js/merged.json
  apps/files_versions/lib/Hooks.php
  apps/files_versions/src/css/versions.css
  apps/files_versions/src/files_versions.js
  apps/files_versions/src/filesplugin.js
  apps/files_versions/src/templates.js
  apps/files_versions/src/templates/item.handlebars
  apps/files_versions/src/templates/template.handlebars
  apps/files_versions/src/versioncollection.js
  apps/files_versions/src/versionmodel.js
  apps/files_versions/src/versionstabview.js
  apps/files_versions/webpack.js
  core/js/core.json
  tests/karma.config.js
  webpack.common.js
Labels: 3. to review, enhancement, feature: versions

#14170 Show more information on app password update
  settings/Activity/Provider.php
  settings/Controller/AuthSettingsController.php
  tests/Settings/Controller/AuthSettingsControllerTest.php
Labels: 3. to review, enhancement

#14168 Improve update channel layout to be a popup menu
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/package-lock.json
  apps/updatenotification/package.json
  apps/updatenotification/src/components/root.vue
  core/css/apps.scss
Labels: 4. to release, design, enhancement, feature: install and update

#14185 Fix recent files
  lib/private/Files/Node/Folder.php
Labels: 3. to review, feature: files, regression

#14183 Remove Nextcloud's Google+ link
  core/img/googleplus.svg
  settings/templates/settings/personal/development.notice.php
Labels: 3. to review

#12652 Operation progress improvements
  apps/files/js/file-upload.js
  apps/files/js/filelist.js
  apps/files/js/merged-index.json
  apps/files/js/operationprogressbar.js
  apps/files/js/semaphore.js
  apps/files/js/templates.js
  apps/files/js/templates/operationprogressbar.handlebars
  apps/files/js/templates/operationprogressbarlabel.handlebars
  apps/files/templates/list.php
  apps/files/tests/js/fileUploadSpec.js
  apps/files/tests/js/filelistSpec.js
  core/js/files/client.js
Labels: 4. to release, enhancement, feature: files

#14160 Update CRL to contain revoked files_external_dropbox, passman & payback
  resources/codesigning/root.crl
  tests/lib/InstallerTest.php
Labels: 3. to review, backport-request

#14200 ensure attribute names are lower cased
  apps/user_ldap/lib/User/Manager.php
  apps/user_ldap/tests/User/ManagerTest.php
Labels: 4. to release, backport-request, bug, feature: ldap

#14207 [stable15] Fix small glitches in update notification page
  apps/updatenotification/css/admin.scss
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/root.vue
  settings/css/settings.scss
Labels: 3. to review

#14205 [stable14] Fix small glitches in update notification page
  apps/updatenotification/css/admin.css
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/root.vue
  settings/css/settings.scss
Labels: 3. to review

#14204 [stable13] Update CRL to contain revoked files_external_dropbox, passman & payback
  resources/codesigning/root.crl
  tests/lib/InstallerTest.php
Labels: 3. to review

#14208 [stable13] ensure attribute names are lower cased
  apps/user_ldap/lib/User/Manager.php
  apps/user_ldap/tests/User/ManagerTest.php
Labels: 3. to review, bug, feature: ldap

#14206 [stable14] ensure attribute names are lower cased
  apps/user_ldap/lib/User/Manager.php
  apps/user_ldap/tests/User/ManagerTest.php
Labels: 3. to review, bug, feature: ldap

#14197 Fix trashbin restore translation
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/src/app.js
Labels: 4. to release, backport-request, bug

#13995 Do not run getRepairSteps in register_commands
  core/Command/Maintenance/Repair.php
  core/register_command.php
  lib/private/Migration/BackgroundRepair.php
  lib/private/Repair.php
  tests/lib/Migration/BackgroundRepairTest.php
Labels: 3. to review, enhancement

#14199 Move 2 always loaded styles to webpack bundle
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/jquery/css/images/ui-bg_diagonals-thick_20_666666_40x40.png
  core/src/jquery/css/images/ui-bg_flat_10_000000_40x100.png
  core/src/jquery/css/images/ui-bg_flat_35_1d2d44_40x100.png
  core/src/jquery/css/images/ui-icons_1d2d44_256x240.png
  core/src/jquery/css/images/ui-icons_ffd27a_256x240.png
  core/src/jquery/css/images/ui-icons_ffffff_256x240.png
  core/src/jquery/css/jquery-ui-fixes.scss
  core/src/jquery/css/jquery.ocdialog.scss
  core/src/jquery/index.js
  core/webpack.js
  lib/private/legacy/template.php
Labels: 3. to review, enhancement

#14186 Move systemtags (app) to webpack
  .gitattributes
  apps/systemtags/.l10nignore
  apps/systemtags/appinfo/app.php
  apps/systemtags/img/tag.svg
  apps/systemtags/js/merged.json
  apps/systemtags/js/systemtags.js
  apps/systemtags/js/systemtags.js.map
  apps/systemtags/src/app.js
  apps/systemtags/src/css/systemtagsfilelist.scss
  apps/systemtags/src/filesplugin.js
  apps/systemtags/src/systemtags.js
  apps/systemtags/src/systemtagsfilelist.js
  apps/systemtags/src/systemtagsinfoview.js
  apps/systemtags/src/systemtagsinfoviewtoggleview.js
  apps/systemtags/webpack.js
  core/css/icons.scss
  tests/karma.config.js
  webpack.common.js
Labels: 3. to review, enhancement, javascript

#14191 Make TestCase->overwriteService() work with App classes
  lib/private/ServerContainer.php
Labels: 3. to review, bug

#14213 [stable15] Fix trashbin restore translation
  apps/files_trashbin/js/app.js
Labels: 3. to review

#14212 [stable15] Fix expiration date changing
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, bug, feature: sharing

#14221 Remove trailing spaces from localized strings
  core/ajax/update.php
Labels: 3. to review, backport-request

#14174 Mount configuration handlers for external storages
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Config/IConfigHandler.php
  apps/files_external/lib/Config/SimpleSubstitutionTrait.php
  apps/files_external/lib/Config/UserPlaceholderHandler.php
  apps/files_external/lib/Lib/Storage/FTP.php
  apps/files_external/lib/Service/BackendService.php
  apps/files_external/lib/config.php
  apps/files_external/tests/Config/UserPlaceholderHandlerTest.php
  apps/files_external/tests/Service/BackendServiceTest.php
  apps/user_ldap/appinfo/app.php
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/js/wizard/wizardTabAdvanced.js
  apps/user_ldap/lib/AppInfo/Application.php
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Exceptions/AttributeNotSet.php
  apps/user_ldap/lib/Handler/ExtStorageConfigHandler.php
  apps/user_ldap/lib/User/Manager.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/templates/settings.php
  apps/user_ldap/tests/ConfigurationTest.php
  apps/user_ldap/tests/User/UserTest.php
Labels: 4. to release, enhancement, feature: external storage, feature: ldap

#14258 Add proper NODE_ENV
  apps/oauth2/js/oauth2.js
  apps/oauth2/js/oauth2.js.map
  apps/oauth2/webpack.js
  package.json
  settings/js/vue-5.js
  settings/js/vue-5.js.map
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/package.json
  settings/webpack.common.js
Labels: 3. to review, enhancement, javascript

#14266 Add guest navigation type
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/ThemingDefaultsTest.php
  lib/private/Server.php
  lib/public/INavigationManager.php
Labels: 3. to review, enhancement

#14223 Use CountWrapper instead of almost identical CountReadStream
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Stream/CountReadStream.php
  tests/lib/Files/Stream/CountReadStreamTest.php
Labels: 3. to review, enhancement

#14248 Fixing phpdoc in FullTextSearch/Model/ISearchResult
  lib/public/FullTextSearch/Model/ISearchResult.php
Labels: 3. to review, backport-request

#14234 Catch Request exception in testRemoteUrl
  apps/files_sharing/lib/External/Storage.php
Labels: 3. to review, backport-request, bug, feature: federation

#14218 Move files_sharing additionalscripts over to webpack
  .gitattributes
  apps/files_sharing/.l10nignore
  apps/files_sharing/appinfo/app.php
  apps/files_sharing/css/mergedAdditionalStyles.scss
  apps/files_sharing/js/additionalScripts.js
  apps/files_sharing/js/additionalScripts.js.map
  apps/files_sharing/js/additionalScripts.json
  apps/files_sharing/src/additionalScripts.js
  apps/files_sharing/src/share.js
  apps/files_sharing/src/sharebreadcrumbview.js
  apps/files_sharing/src/sharetabview.js
  apps/files_sharing/src/style/sharebreadcrumb.scss
  apps/files_sharing/src/style/sharetabview.scss
  apps/files_sharing/webpack.js
  tests/karma.config.js
  webpack.common.js
Labels: 4. to release, enhancement, javascript

#14232 Move updatenotifications to unified webpack
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/package-lock.json
  apps/updatenotification/package.json
  apps/updatenotification/webpack.dev.js
  apps/updatenotification/webpack.js
  apps/updatenotification/webpack.prod.js
  package-lock.json
  package.json
  webpack.common.js
Labels: 4. to release, enhancement, javascript

#14194 Correctly determinate the owner in case of shared external storages
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, backport-request, feature: external storage, feature: sharing

#14261 Warning if x-forwarded-host present but trusted_proxies empty
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3. to review, enhancement

#14264 Set false as default for requirePNG
  lib/private/Activity/Manager.php
Labels: 3. to review, bug

#14279 Fix header label visibility on open menu
  core/css/header.scss
Labels: 3. to review, backport-request, bug, design

#14282 Fix writable public folder share
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 3. to review, bug

#14249 Add hasIndex() to OCP\FullTextSearch\Model\IndexDocument
  lib/public/FullTextSearch/Model/IndexDocument.php
Labels: 4. to release

#14211 Prefix $path for filename for internal file cache
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review, enhancement

#14263 Publish activity if app password created by ocs api or client login flow
  core/Controller/AppPasswordController.php
  core/Controller/ClientFlowLoginController.php
  settings/Application.php
  tests/Core/Controller/AppPasswordControllerTest.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
Labels: 3. to review, enhancement

#14289 Move accessibility to main webpack
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/package-lock.json
  apps/accessibility/package.json
  apps/accessibility/webpack.dev.js
  apps/accessibility/webpack.js
  apps/accessibility/webpack.prod.js
  webpack.common.js
Labels: 3. to review, javascript

#14293 According to the OCM specification the body needs to be JSON encoded
  lib/private/Federation/CloudFederationProviderManager.php
Labels: 3. to review, feature: federation, feature: sharing

#14275 [stable15] Do not do redirect handling when loggin out
  core/Controller/LoginController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/Exceptions/ReloadExecutionException.php
  lib/private/AppFramework/Middleware/Security/ReloadExecutionMiddleware.php
Labels: 3. to review

#11832 set birthday year to 1970 if no year, take X-APPLE-OMIT-YEAR into account
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php
  apps/dav/lib/CalDAV/BirthdayService.php
  apps/dav/lib/Migration/RegenerateBirthdayCalendars.php
  apps/dav/tests/unit/BackgroundJob/GenerateBirthdayCalendarBackgroundJobTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/Migration/RegenerateBirthdayCalendarsTest.php
Labels: 3. to review, bug, feature: dav

#14299 Hanlde writestream not closing source
  apps/dav/lib/Connector/Sabre/File.php
Labels: 3. to review, backport-request, bug, regression

#14291 Change Workflow to Tag Management
  apps/workflowengine/lib/Settings/Section.php
Labels: 3. to review, enhancement

#14300 Use proper scroll container when dragging files
  apps/files/js/files.js
Labels: 3. to review, backport-request, bug, feature: files

#14178 Fix OC.getCurrentUser() on guest pages
  core/templates/layout.guest.php
  lib/private/TemplateLayout.php
Labels: 3. to review, backport-request, bug

#14297 Move settings to main webpack
  .drone.yml
  core/js/dist/main.js
  core/js/dist/main.js.map
  package-lock.json
  package.json
  settings/js/vue-4.js
  settings/js/vue-4.js.map
  settings/js/vue-5.js.map
  settings/js/vue-6.js.map
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js.map
  settings/package-lock.json
  settings/package.json
  settings/webpack.dev.js
  settings/webpack.js
  settings/webpack.prod.js
  webpack.common.js
Labels: 3. to review, enhancement, javascript

#14255 Fix ocm end-point discovery discovery
  apps/cloud_federation_api/lib/Capabilities.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  lib/private/Setup.php
  settings/js/admin.js
Labels: 3. to review, backport-request, bug

#14306 13.0.11 RC 1
  version.php
Labels: 3. to review

#14312 [stable15] Fix ocm end-point discovery discovery
  apps/cloud_federation_api/lib/Capabilities.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  lib/private/Setup.php
  settings/js/admin.js
Labels: 4. to release

#14311 Move twofactor_backupcodes to main webpack bundle
  .drone.yml
  apps/twofactor_backupcodes/Makefile
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/package-lock.json
  apps/twofactor_backupcodes/package.json
  apps/twofactor_backupcodes/webpack.dev.js
  apps/twofactor_backupcodes/webpack.js
  apps/twofactor_backupcodes/webpack.prod.js
  webpack.common.js
Labels: 4. to release, enhancement, javascript

#14304 15.0.5 RC 1
  version.php
Labels: 3. to review

#13850 Enable & disable multiple apps at once
  .drone.yml
  build/integration/run.sh
  core/Command/App/Disable.php
  core/Command/App/Enable.php
  core/register_command.php
  tests/Core/Command/Apps/AppsDisableTest.php
  tests/Core/Command/Apps/AppsEnableTest.php
Labels: 3. to review, enhancement

#14329 Apply theme to 2FA button
  apps/theming/css/theming.scss
Labels: 4. to release, backport-request, bug, feature: theming

#14326 Fix alignment of filelist header
  apps/files/css/files.scss
Labels: 4. to release, design, enhancement

#14066 Get typed system values
  apps/dav/lib/Connector/Sabre/MaintenancePlugin.php
  apps/dav/tests/unit/Connector/Sabre/MaintenancePluginTest.php
  apps/encryption/lib/AppInfo/Application.php
  core/Command/Encryption/DecryptAll.php
  core/Command/Encryption/EncryptAll.php
  core/Command/Maintenance/Mode.php
  core/Command/Maintenance/Repair.php
  core/Command/Upgrade.php
  cron.php
  lib/base.php
  lib/private/AllConfig.php
  lib/private/Console/Application.php
  lib/private/Route/Router.php
  lib/private/Updater.php
  lib/private/legacy/app.php
  lib/public/IConfig.php
  ocs/v1.php
  tests/Core/Command/Encryption/EncryptAllTest.php
  tests/Core/Command/Maintenance/ModeTest.php
Labels: 4. to release, enhancement, technical debt

#13800 Design work on accessibility settings
  apps/accessibility/css/style.scss
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/lib/AccessibilityProvider.php
  apps/accessibility/src/App.vue
  apps/accessibility/src/components/itemPreview.vue
Labels: 2. developing, design, enhancement, feature: accessibility, help wanted

#14337 Fix "Undefined index: user_uid" on login page
  lib/private/TemplateLayout.php
Labels: 4. to release, backport-request, bug, regression

#14332 Fix unsafe array access
  apps/admin_audit/lib/Actions/Console.php
Labels: 3. to review, backport-request, bug

#14338 Properly theme firstrunwizard logo in example theme
  themes/example/core/css/server.css
Labels: 4. to release, enhancement, feature: theming

#14320 Accessibility & design fixes on installation
  core/css/guest.css
  core/css/inputs.scss
  core/css/styles.scss
  core/templates/installation.php
  settings/templates/settings/personal/security.php
Labels: 4. to release, bug, design, feature: accessibility, help wanted

#14161 Desktop login flow V2
  core/BackgroundJobs/CleanupLoginFlowV2.php
  core/Controller/ClientFlowLoginV2Controller.php
  core/Data/LoginFlowV2Credentials.php
  core/Data/LoginFlowV2Tokens.php
  core/Db/LoginFlowV2.php
  core/Db/LoginFlowV2Mapper.php
  core/Exception/LoginFlowV2NotFoundException.php
  core/Migrations/Version16000Date20190212081545.php
  core/Service/LoginFlowV2Service.php
  core/routes.php
  core/templates/loginflowv2/authpicker.php
  core/templates/loginflowv2/done.php
  core/templates/loginflowv2/grant.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC16/AddClenupLoginFlowV2BackgroundJob.php
  tests/Core/Controller/ClientFlowLoginV2ControllerTest.php
  version.php
Labels: 3. to review, client: 💻 desktop, enhancement, security

#14180 Show sharing recommendations
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/tests/Controller/ShareesAPIControllerTest.php
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogview.js
Labels: 4. to release, enhancement, feature: sharing

#14325 Always query lookup server in GS mode
  lib/private/Collaboration/Collaborators/LookupPlugin.php
Labels: 3. to review, backport-request, bug, feature: global scale

#14369 Use latest ca-bundle.crt from https://curl.haxx.se/docs/caextract.html
  resources/config/ca-bundle.crt
Labels: 3. to review, backport-request, security

#14365 Makefile to root folder
  Makefile
  README.md
  build/files-checker.php
Labels: 4. to release, enhancement, javascript

#14370 15.0.2 RC 2
  version.php
Labels: 4. to release

#14375 14.0.8 RC 2
  version.php
Labels: 4. to release

#13514 Fix grid toggle button on public page
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/templates/public.php
Labels: 3. to review, backport-request, bug, design, feature: files, feature: sharing, regression

#14025 Fix authtoken index length
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review, bug

#14347 allow group backends to mark that a group should now be shown in search dialogs
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Collaboration/Collaborators/GroupPlugin.php
  lib/private/Group/Group.php
  lib/public/Group/Backend/IHideFromCollaborationBackend.php
  lib/public/IGroup.php
  tests/lib/Collaboration/Collaborators/GroupPluginTest.php
Labels: 4. to release

#14314 No need to check 2fa state on apptoken logins
  core/Middleware/TwoFactorMiddleware.php
Labels: 3. to review, enhancement

#14377 Fix typo in info log for autoconfig
  core/Controller/SetupController.php
Labels: 4. to release

#14198 Exclude file name patterns; ignore gentoo webapp files
  lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
  tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
Labels: 3. to review, enhancement

#14322 Users management enhancements and fixes
  package-lock.json
  settings/js/vue-1.js
  settings/js/vue-1.js.map
  settings/js/vue-2.js
  settings/js/vue-2.js.map
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/src/components/userList.vue
  settings/src/views/Users.vue
Labels: 3. to review, bug, design, enhancement, feature: users and groups

#14227 Move comments to webpack
  .gitattributes
  apps/comments/.l10nignore
  apps/comments/js/comments.js
  apps/comments/js/comments.js.map
  apps/comments/js/merged.json
  apps/comments/lib/AppInfo/Application.php
  apps/comments/src/activitytabviewplugin.js
  apps/comments/src/app.js
  apps/comments/src/commentcollection.js
  apps/comments/src/commentmodel.js
  apps/comments/src/comments.js
  apps/comments/src/commentsmodifymenu.js
  apps/comments/src/commentstabview.js
  apps/comments/src/commentsummarymodel.js
  apps/comments/src/filesplugin.js
  apps/comments/src/search.js
  apps/comments/src/style/autocomplete.scss
  apps/comments/src/style/comments.scss
  apps/comments/src/templates.js
  apps/comments/src/templates/comment.handlebars
  apps/comments/src/templates/commentsmodifymenu.handlebars
  apps/comments/src/templates/edit_comment.handlebars
  apps/comments/src/templates/filesplugin.handlebars
  apps/comments/src/templates/view.handlebars
  apps/comments/src/vendor/At.js/dist/js/jquery.atwho.min.js
  apps/comments/src/vendor/Caret.js/dist/jquery.caret.min.js
  apps/comments/webpack.js
  tests/karma.config.js
  webpack.common.js
Labels: 2. developing, enhancement, javascript

#14251 Limit number of simultaneous MKCOL requests to server to increase upload reliability
  apps/files/js/file-upload.js
  apps/files/js/operationprogressbar.js
  apps/files/tests/js/fileUploadSpec.js
Labels: 3. to review, enhancement, feature: dav

#14342 Fix occ files:scan elapsed time
  apps/files/lib/Command/Scan.php
  apps/files/lib/Command/ScanAppData.php
Labels: 3. to review, enhancement

#14385 Add an event to the Autocomplete Controller to allow to filter the re…
  core/Controller/AutoCompleteController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Collaboration/AutoComplete/AutoCompleteEvent.php
  tests/Core/Controller/AutoCompleteControllerTest.php
Labels: 4. to release, enhancement

#14333 Search sharees on lookup server when explicitly requested by user
  apps/files_sharing/js/additionalScripts.js
  apps/files_sharing/js/additionalScripts.js.map
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/src/style/sharetabview.scss
  apps/files_sharing/tests/Controller/ShareesAPIControllerTest.php
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogview.js
  core/js/tests/specs/sharedialogviewSpec.js
  lib/private/Collaboration/Collaborators/LookupPlugin.php
  tests/lib/Collaboration/Collaborators/LookupPluginTest.php
Labels: 4. to release, enhancement

#14318 Fix referrer policy meta tags.
  core/templates/layout.base.php
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: 4. to release, backport-request, bug

#14389 Add HasPhoto DAV plugin
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CardDAV/HasPhotoPlugin.php
  apps/dav/lib/Server.php
Labels: 4. to release, enhancement, feature: dav

#14402 Do not register unexisting section
  apps/theming/appinfo/info.xml
Labels: 3. to review, bug, feature: settings, feature: theming

#14399 Fix top margin for info text when non-default updater server URL is used
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/root.vue
Labels: 3. to review, design, papercut

#13844 Bugfix for issue 10862: Trash-bin ignores trashbin_retention_obligation
  apps/files_trashbin/lib/Trashbin.php
Labels: 3. to review, bug, feature: trashbin

#14343 Parse multiple navigation items
  lib/private/App/InfoParser.php
  lib/private/NavigationManager.php
  tests/data/app/navigation-one-item.json
  tests/data/app/navigation-one-item.xml
  tests/data/app/navigation-two-items.json
  tests/data/app/navigation-two-items.xml
  tests/lib/App/InfoParserTest.php
  tests/lib/NavigationManagerTest.php
Labels: 4. to release, backport-request, bug

#14418 Remove/replace missing css var usages
  core/css/mobile.scss
  core/css/styles.scss
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/jquery/css/jquery-ui-fixes.scss
Labels: 3. to review, bug

#14422 13.0.12
  version.php
Labels: 3. to review

#14421 14.0.8
  version.php
Labels: 3. to review

#14420 15.0.5
  version.php
Labels: 3. to review

#14419 Fix closing tags in header
  core/templates/layout.user.php
Labels: 3. to review, bug

#14390 Bugfix/14307/expire date change eventhandler
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialoglinkshareview.js
Labels: 4. to release, bug, feature: files

#14432 Bump jcrop from v0.9.12-npm to v0.9.12-npm3
  package-lock.json
  package.json
Labels: 4. to release, bug

#14433 Fix acceptance tests for tag management
  tests/acceptance/features/app-files-tags.feature
Labels: 4. to release

#13489 Do not load 2fa admin settings async
  lib/private/Settings/Admin/Security.php
  settings/js/vue-0.js
  settings/js/vue-3.js
  settings/js/vue-4.js
  settings/js/vue-5.js
  settings/js/vue-6.js
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/src/components/AdminTwoFactor.vue
  settings/src/main-admin-security.js
  settings/src/store/admin-security.js
  settings/templates/settings/admin/security.php
  tests/lib/Settings/Admin/SecurityTest.php
Labels: 4. to release, enhancement, javascript

#14412 add option to get raw size (without submounts) from fileinfo
  apps/files_trashbin/lib/Trash/TrashItem.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Node/LazyRoot.php
  lib/private/Files/Node/Node.php
  lib/private/Files/Node/NonExistingFile.php
  lib/private/Files/Node/NonExistingFolder.php
  lib/private/Files/Node/Root.php
  lib/public/Files/FileInfo.php
  lib/public/Files/Node.php
Labels: 3. to review

#14442 Remove not used appinfo/classpath.php check
  lib/base.php
Labels: 4. to release, technical debt

#14440 Run tests that fail with "no such process" over to apache server
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/apps.feature
  tests/acceptance/features/login.feature
  tests/acceptance/features/users.feature
Labels: 4. to release

#14400 Remove unneeded sidebar animation
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/OC/apps.js
  package-lock.json
Labels: 4. to release, bug, design

#14398 Add setup check for missing UTF8MB4 on mysql
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 4. to release, enhancement
