Repository nextcloud/server, pull requests merged in 2019-05, with the labels that each got.

#15316 Add mariadb 10.0 ci tests
  .drone.yml
  autotest.sh
Labels: 2. developing

#15321 Add mariadb 10.1 CI job
  .drone.yml
Labels: 2. developing

#15323 CI MariaDB 10.2
  .drone.yml
Labels: 2. developing

#15325 CI MariaDB 10.3
  .drone.yml
Labels: 2. developing

#15326 CI MariaDB 10.4
  .drone.yml
Labels: 2. developing

#15327 CI Postgres 11
  .drone.yml
Labels: 2. developing

#15338 Change oc_config usage to OC.config
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/js.js
  core/js/shareconfigmodel.js
  core/js/sharedialogview.js
  core/js/tests/specs/coreSpec.js
  core/js/tests/specs/sharedialogviewSpec.js
Labels: 4. to release, technical debt

#15122 Check if the data is in the lookup server
  settings/BackgroundJobs/VerifyUserData.php
Labels: 3. to review, backport-request, bug

#15309 Do NOT assume all files are selected if the first checkbox is
  apps/files/js/filelist.js
Labels: 3. to review, backport-request, bug, high

#15359 Handle 0 B default quota properly in the web UI
  settings/js/vue-7.js
  settings/js/vue-7.js.map
  settings/src/views/Users.vue
Labels: 3. to review, backport-request, bug, feature: settings, feature: users and groups

#15311 Add mysql 8.0 CI run
  .drone.yml
Labels: 3. to review, enhancement

#15384 Fix collapse button in app navigation in IE11
  core/css/apps.scss
Labels: 3. to review, backport-request, bug

#15385 Make sure all middlewares are only registered once
  lib/private/AppFramework/DependencyInjection/DIContainer.php
Labels: 3. to review, backport-request, bug, feature: federation, feature: sharing, regression

#15394 Allow to send the password of protected conversations
  core/routes.php
Labels: 3. to review, backport-request, bug, regression

#15407 Remove extra margin from warning messages in authenticate page
  core/css/publicshareauth.css
Labels: 3. to review, backport-request, bug, design

#13929 Create a login bundle for login page scripts
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/js/dist/main.js
  core/js/login.js
  core/js/lostpassword.js
  core/js/merged-login.json
  core/js/visitortimezone.js
  core/src/Util/visitortimezone.js
  core/src/login.js
  core/src/lostpassword.js
  core/templates/login.php
  core/webpack.js
Labels: 4. to release, enhancement, technical debt

#15397 Set Edge < 16 as incompatible with css vars
  core/js/js.js
Labels: 3. to review, backport-request, bug, design

#15413 remove extra param in cache update call
  lib/private/Files/Cache/Cache.php
Labels: 4. to release, backport-request

#15423 [stable14] Set Edge < 16 as incompatible with css vars
  core/js/js.js
Labels: 3. to review, bug

#15421 [stable15] Set Edge < 16 as incompatible with css vars
  core/js/js.js
Labels: 3. to review, bug

#15422 Properly set Edge < 16 as incompatible with css vars
  core/js/js.js
Labels: 3. to review, backport-request, bug

#15365 Refactor complex LoginController logic into a login chain of responsibility
  core/Controller/LoginController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Login/ALoginCommand.php
  lib/private/Authentication/Login/Chain.php
  lib/private/Authentication/Login/ClearLostPasswordTokensCommand.php
  lib/private/Authentication/Login/CompleteLoginCommand.php
  lib/private/Authentication/Login/CreateSessionTokenCommand.php
  lib/private/Authentication/Login/EmailLoginCommand.php
  lib/private/Authentication/Login/FinishRememberedLoginCommand.php
  lib/private/Authentication/Login/LoggedInCheckCommand.php
  lib/private/Authentication/Login/LoginData.php
  lib/private/Authentication/Login/LoginResult.php
  lib/private/Authentication/Login/PreLoginHookCommand.php
  lib/private/Authentication/Login/SetUserTimezoneCommand.php
  lib/private/Authentication/Login/TwoFactorCommand.php
  lib/private/Authentication/Login/UidLoginCommand.php
  lib/private/Authentication/Login/UpdateLastPasswordConfirmCommand.php
  lib/private/Authentication/Login/UserDisabledCheckCommand.php
  lib/private/User/Manager.php
  tests/Core/Controller/LoginControllerTest.php
  tests/lib/Authentication/Login/ALoginCommandTest.php
  tests/lib/Authentication/Login/ClearLostPasswordTokensCommandTest.php
  tests/lib/Authentication/Login/CompleteLoginCommandTest.php
  tests/lib/Authentication/Login/CreateSessionTokenCommandTest.php
  tests/lib/Authentication/Login/EmailLoginCommandTest.php
  tests/lib/Authentication/Login/FinishRememberedLoginCommandTest.php
  tests/lib/Authentication/Login/LoggedInCheckCommandTest.php
  tests/lib/Authentication/Login/PreLoginHookCommandTest.php
  tests/lib/Authentication/Login/SetUserTimezoneCommandTest.php
  tests/lib/Authentication/Login/TwoFactorCommandTest.php
  tests/lib/Authentication/Login/UidLoginCommandTest.php
  tests/lib/Authentication/Login/UpdateLastPasswordConfirmCommandTest.php
  tests/lib/Authentication/Login/UserDisabledCheckCommandTest.php
Labels: 4. to release, technical debt

#15426 Remove unused singleselect script
  core/js/singleselect.js
Labels: 3. to review, technical debt

#15424 [stable16] Handle 0 B default quota properly in the web UI
  settings/js/vue-7.js
  settings/js/vue-7.js.map
  settings/src/views/Users.vue
Labels: 3. to review, bug

#15259 Make access column a real boolean
  core/Migrations/Version16000Date20190427105638.php
  core/Migrations/Version16000Date20190428150708.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Collaboration/Resources/Manager.php
Labels: 3. to review, backport-request, bug

#15301 Fix multiselect min width
  settings/css/settings.scss
Labels: 3. to review, backport-request, bug, design

#15302 Floating files header
  apps/files/css/files.scss
  apps/files/js/filelist.js
Labels: 3. to review, design, enhancement, feature: files

#15425 [stable15] Handle 0 B default quota properly in the web UI
  settings/js/4.js.map
  settings/js/5.js
  settings/js/5.js.map
  settings/js/settings-admin-security.js.map
  settings/js/settings-vue.js.map
  settings/src/views/Users.vue
Labels: 3. to review, bug

#15432 Fix public upload by also load the semaphore method
  apps/files/js/semaphore.js
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 3. to review, backport-request, bug

#15446 Run phan tests only on high memory machines
  .drone.yml
Labels: 3. to review, backport-request

#15430 Use non-absolute logout URL to fix wrong URL in reverse proxy scenario
  lib/private/legacy/user.php
  tests/lib/NavigationManagerTest.php
Labels: 4. to release, backport-request, bug

#15456 [stable15] Use non-absolute logout URL to fix wrong URL in reverse proxy scenario
  lib/private/legacy/user.php
  tests/lib/NavigationManagerTest.php
Labels: 4. to release

#15464 Revert "Run phan tests only on high memory machines"
  .drone.yml
Labels: backport-request

#15454 Bump vue-multiselect from 2.1.4 to 2.1.6
  package-lock.json
  package.json
  settings/js/vue-6.js
  settings/js/vue-6.js.map
Labels: 3. to review, feature: dependencies, javascript

#15468 Remove recommendation for opcache on CLI
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  settings/Controller/CheckSetupController.php
Labels: 4. to release, backport-request

#15469 [Stable16] Fix mobile vertical scrolling
  core/js/dist/main.js
  core/js/dist/main.js.map
  core/src/jquery/css/jquery-ui-fixes.scss
Labels: 4. to release, bug

#15478 Update file-upload.js
  apps/files/js/file-upload.js
Labels: 4. to release, backport-request

#15477 Fix floating header over breadcrumbs
  apps/files/css/files.scss
Labels: 4. to release, bug, design

#15484 [stable14] Update file-upload.js
  apps/files/js/file-upload.js
Labels: 4. to release

#15485 [stable15] Update file-upload.js
  apps/files/js/file-upload.js
Labels: 4. to release

#15429 16.0.1 RC 1
  version.php
Labels: 4. to release

#15221 15.0.8 RC1
  version.php
Labels: 4. to release

#15222 14.0.11 RC 1
  version.php
Labels: 4. to release

#15488 webpackify workflowengine
  .gitattributes
  apps/workflowengine/.l10nignore
  apps/workflowengine/js/templates.js
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/lib/AppInfo/Application.php
  apps/workflowengine/src/admin.js
  apps/workflowengine/src/filemimetypeplugin.js
  apps/workflowengine/src/filenameplugin.js
  apps/workflowengine/src/filesizeplugin.js
  apps/workflowengine/src/filesystemtagsplugin.js
  apps/workflowengine/src/requestremoteaddressplugin.js
  apps/workflowengine/src/requesttimeplugin.js
  apps/workflowengine/src/requesturlplugin.js
  apps/workflowengine/src/requestuseragentplugin.js
  apps/workflowengine/src/templates/operation.handlebars
  apps/workflowengine/src/templates/operations.handlebars
  apps/workflowengine/src/usergroupmembershipplugin.js
  apps/workflowengine/src/workflowengine.js
  apps/workflowengine/webpack.js
  build/compile-handlebars-templates.sh
  webpack.common.js
Labels: 3. to review, enhancement, feature: workflow engine, technical debt

#15495 Add interfaces to interact with subscription from support app
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Server.php
  lib/private/Support/Subscription/Registry.php
  lib/public/Support/Subscription/Exception/AlreadyRegisteredException.php
  lib/public/Support/Subscription/IRegistry.php
  lib/public/Support/Subscription/ISubscription.php
  lib/public/Support/Subscription/ISupportedApps.php
  tests/lib/Support/Subscription/RegistryTest.php
Labels: 4. to release, backport-request, enhancement

#15498 Show supported apps in app management
  lib/private/legacy/app.php
  settings/css/settings.scss
  settings/js/vue-4.js
  settings/js/vue-4.js.map
  settings/src/components/appDetails.vue
  settings/src/components/appList/appItem.vue
Labels: 4. to release, enhancement

#15461 add "askForPassword" on capabilities for sharing
  apps/files_sharing/lib/Capabilities.php
Labels: 4. to release, enhancement, feature: sharing

#15531 Remove OCP (re)declaration from js.js
  core/js/js.js
Labels: 4. to release, technical debt

#15336 Fix Redis with unix socket #730
  lib/private/RedisFactory.php
Labels: 4. to release, enhancement

#15545 14.0.11
  version.php
Labels: 4. to release

#15544 15.0.8
  version.php
Labels: 4. to release

#15543 16.0.1
  version.php
Labels: 4. to release

#15526 fix building WFE Handlebars
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/admin.js
  apps/workflowengine/src/hbs_helpers/getOperators.js
  apps/workflowengine/src/hbs_helpers/selectItem.js
  apps/workflowengine/webpack.js
Labels: 4. to release, bug, feature: workflow engine

#15548 update ca bundle
  resources/config/ca-bundle.crt
Labels: 4. to release, backport-request

#15552 Update ca bundle checker
  build/ca-bundle-checker.sh
Labels: 4. to release, backport-request, bug

#15564 User management/subadmin: rephrase ambiguous error message
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 4. to release, backport-request, bug, feature: users and groups

#15570 DateTime is not yet in 14
  lib/private/Repair/RemoveLinkShares.php
Labels: 4. to release, bug

#15572 [stable15] update ca bundle
  resources/config/ca-bundle.crt
Labels: 3. to review

#15573 [stable14] update ca bundle
  resources/config/ca-bundle.crt
Labels: 3. to review

#15582 Update shipped.json to include privacy and recommendations
  core/shipped.json
Labels: 3. to review, backport-request, bug

#15590 Allow clients to delete their own apptoken
  core/Controller/AppPasswordController.php
  core/routes.php
  tests/Core/Controller/AppPasswordControllerTest.php
Labels: 3. to review, enhancement

#15304 2FA setup during login
  core/Controller/TwoFactorChallengeController.php
  core/Middleware/TwoFactorMiddleware.php
  core/routes.php
  core/templates/twofactorselectchallenge.php
  core/templates/twofactorsetupchallenge.php
  core/templates/twofactorsetupselection.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Login/TwoFactorCommand.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  lib/public/Authentication/TwoFactorAuth/ALoginSetupController.php
  lib/public/Authentication/TwoFactorAuth/IActivatableAtLogin.php
  lib/public/Authentication/TwoFactorAuth/ILoginSetupProvider.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
  tests/Core/Middleware/TwoFactorMiddlewareTest.php
  tests/lib/Authentication/Login/TwoFactorCommandTest.php
  tests/lib/Authentication/TwoFactorAuth/ManagerTest.php
Labels: 4. to release, enhancement, feature: authentication

#15594 14.0.12
  version.php
Labels: 4. to release

#15593 [stable16] Show supported apps in app management
  lib/private/legacy/app.php
  settings/css/settings.scss
  settings/js/vue-4.js
  settings/js/vue-4.js.map
  settings/src/components/appDetails.vue
  settings/src/components/appList/appItem.vue
Labels: 4. to release, feature: apps management

#15626 Update CRL due to revoked cookbook.crt
  resources/codesigning/root.crl
Labels: 4. to release, backport-request, security

#15640 Unbreak browser back button not working
  core/js/js.js
Labels: 3. to review, backport-request, bug

#15104 Remote wipe support
  apps/files_sharing/js/dist/files_sharing.0.js
  apps/files_sharing/js/dist/files_sharing.0.js.map
  apps/files_sharing/js/dist/files_sharing.1.js.map
  core/Application.php
  core/Controller/WipeController.php
  core/routes.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Exceptions/WipeTokenException.php
  lib/private/Authentication/Notifications/Notifier.php
  lib/private/Authentication/Token/IProvider.php
  lib/private/Authentication/Token/IToken.php
  lib/private/Authentication/Token/IWipeableToken.php
  lib/private/Authentication/Token/Manager.php
  lib/private/Authentication/Token/PublicKeyToken.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/Authentication/Token/RemoteWipe.php
  settings/Activity/SecurityProvider.php
  settings/Controller/AuthSettingsController.php
  settings/js/vue-0.js
  settings/js/vue-4.js
  settings/js/vue-5.js
  settings/js/vue-7.js
  settings/js/vue-settings-admin-security.js
  settings/js/vue-settings-admin-security.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/js/vue-settings-personal-security.js
  settings/js/vue-settings-personal-security.js.map
  settings/routes.php
  settings/src/components/AuthToken.vue
  settings/src/components/AuthTokenList.vue
  settings/src/components/AuthTokenSection.vue
  tests/Core/Controller/WipeControllerTest.php
Labels: 4. to release, enhancement, security

#15638 Only show sharing section if it has content
  apps/federatedfilesharing/lib/Settings/Personal.php
  lib/private/Settings/Manager.php
Labels: 3. to review, backport-request, bug, feature: federation

#15499 Add scripts to update server & apps or apps only
  build/update-apps.sh
  build/update.sh
Labels: 3. to review, enhancement, papercut

#15660 add method to get the used object store from the storage
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review

#15659 add way for version backends to programmatically specify if they should be used
  apps/files_versions/lib/Versions/IVersionBackend.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/lib/Versions/VersionManager.php
  apps/files_versions/tests/Versions/VersionManagerTest.php
Labels: 3. to review

#15651 Remove quota feedback if no link set
  apps/files/css/files.scss
Labels: 3. to review, bug, design

#15668 Fix l10n for SettingsManager by injecting the l10n factory
  lib/private/Server.php
  lib/private/Settings/Manager.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, backport-request, bug, feature: language l10n and translations, feature: settings

#15685 Allow redis cluster to use password
  config/config.sample.php
  lib/private/RedisFactory.php
Labels: 4. to release, backport-request, enhancement

#15682 Make the L10N loading lazy
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/L10N/Factory.php
  lib/private/L10N/LazyL10N.php
Labels: 3. to review, enhancement

#15604 fixes possible override of uniqueMember by autodetection
  apps/user_ldap/js/wizard/wizardDetectorUserGroupAssociation.js
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/LDAPProvider.php
  apps/user_ldap/lib/Wizard.php
  build/integration/ldap_features/ldap-openldap.feature
  build/integration/ldap_features/openldap-numerical-id.feature
  lib/public/LDAP/ILDAPProvider.php
Labels: 4. to release, backport-request, bug, feature: ldap

#12114 Stop decryption when maintenance mode is enabled
  core/Command/Encryption/DecryptAll.php
  core/Command/Encryption/ListModules.php
  core/Command/Encryption/SetDefaultModule.php
  core/register_command.php
  tests/Core/Command/Encryption/DecryptAllTest.php
  tests/Core/Command/Encryption/SetDefaultModuleTest.php
Labels: 3. to review, backport-request, enhancement, feature: encryption (server-side)

#15684 make ObjectStoreStorage::getURN public
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review

#15676 Revert "send invitations for shared calendars"
  apps/dav/lib/CalDAV/Schedule/Plugin.php
Labels: 3. to review

#15699 Add funding.yml with Bountysource info
  .github/FUNDING.yml
Labels: 3. to review, enhancement

#15706 add option to show hidden files in SMB shares
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#15715 Allow other code to use the s3 client from object store
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 3. to review

#15679 Make it possible to show admin settings for sub admins
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  lib/private/Settings/Manager.php
  lib/public/Settings/IManager.php
  lib/public/Settings/ISubAdminSettings.php
  settings/Controller/AdminSettingsController.php
  settings/Controller/CommonSettingsTrait.php
  settings/Controller/PersonalSettingsController.php
  tests/Settings/Controller/AdminSettingsControllerTest.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, enhancement, feature: settings

#15697 Don't run repair step for every individual user, outsource that to background job
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/RegisterRegenerateBirthdayCalendars.php
  apps/dav/lib/Migration/RegenerateBirthdayCalendars.php
  apps/dav/tests/unit/BackgroundJob/GenerateBirthdayCalendarBackgroundJobTest.php
  apps/dav/tests/unit/BackgroundJob/RegisterRegenerateBirthdayCalendarsTest.php
  apps/dav/tests/unit/Migration/RegenerateBirthdayCalendarsTest.php
Labels: 3. to review, backport-request

#15700 Redirect to the right token on public shares
  lib/public/AppFramework/AuthPublicShareController.php
Labels: 4. to release, bug, feature: sharing

#15714 Check the actual status code for 204 and 304
  lib/private/AppFramework/App.php
  tests/lib/AppFramework/AppTest.php
Labels: 4. to release, backport-request, bug

#15738 Don't notify admins if no potentially over exposing links found
  lib/private/Repair/RemoveLinkShares.php
Labels: 4. to release, backport-request, enhancement

#15747 Also allow dragging below the file list
  apps/files/js/filelist.js
Labels: 4. to release, backport-request, bug, feature: files

#15704 Group display name support (service level + ldap)
  apps/files_external/ajax/applicable.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Group_Proxy.php
  apps/user_ldap/tests/Group_LDAPTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Group/Group.php
  lib/public/Group/Backend/IGetDisplayNameBackend.php
Labels: 4. to release, enhancement, feature: ldap

#15705 Change text color in search box in darktheme, ref #15598
  apps/accessibility/css/themedark.scss
  core/css/header.scss
  core/templates/layout.user.php
Labels: 2. developing, bug, design

#15691 Remove divider in app content list (Mail, Contacts, …)
  core/css/apps.scss
Labels: 3. to review, design, enhancement

#15767 Hide newFile menu if quota is set to 0B
  apps/files/js/filelist.js
  apps/files/js/files.js
Labels: 3. to review, bug

#15766 Check for free space on touch
  lib/private/Files/Node/Folder.php
  lib/private/Files/Storage/Wrapper/Quota.php
  tests/lib/Files/Storage/Wrapper/QuotaTest.php
Labels: 3. to review, backport-request, bug

#15597 Start fixing 2fa icons in dark theme, ref #13643
  lib/private/Settings/Personal/Security.php
  settings/templates/settings/personal/security.php
Labels: 4. to release, bug, feature: settings

#15781 Remove deprecated function checkAppEnabled
  lib/public/App.php
Labels: 4. to release, technical debt

#15779 Remove deprecatred StringUtils class
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Security/StringUtils.php
Labels: 3. to review, technical debt

#15780 Remove deprecated function callCheck
  lib/public/Util.php
Labels: 4. to release, technical debt

#15789 Fix personal security section tests
  tests/lib/Settings/Personal/SecurityTest.php
Labels: 4. to release, bug

#15790 remove unncessary code block in share recommendations, fixed undefined var error
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogview.js
Labels: 4. to release, backport-request, bug, feature: sharing

#15776 search files by id in shared storages last
  lib/private/Files/View.php
Labels: 4. to release, backport-request

#15812 Move OC\Settings\Admin and OC\Settings\Personal to actual settings
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  settings/Settings/Admin/Mail.php
  settings/Settings/Admin/Overview.php
  settings/Settings/Admin/Security.php
  settings/Settings/Admin/Server.php
  settings/Settings/Admin/Sharing.php
  settings/Settings/Personal/Additional.php
  settings/Settings/Personal/PersonalInfo.php
  settings/Settings/Personal/Security.php
  settings/Settings/Personal/ServerDevNotice.php
Labels: 3. to review, enhancement, technical debt

#15813 Add the legacy classes to the composer classmap
  composer.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_namespaces.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review, technical debt
