Repository nextcloud/server, pull requests merged in 2020-12, with the labels that each got.

#24456 Added check on getBackgroundUrl
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/helpers/getBackgroundUrl.js
Labels: 3. to review, backport-request, bug

#24152 [stable18] circleId too short in some request
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review

#24481 [stable18] Fix the config key on the sharing expire checkbox
  apps/settings/templates/settings/admin/sharing.php
  lib/private/Template/JSConfigHelper.php
Labels: 4. to release

#24499 Harden setup check for TLS version if host is not reachable
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 4. to release, backport-request, bug

#24348 Wrap display_name similarly to email to allow changes via occ
  core/Command/User/Setting.php
Labels: 4. to release, enhancement

#24500 Prevent log_query to mess up regular execution flow
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 3. to review, bug

#23257 Fix file size computation on 32bit platforms
  lib/private/Files/Storage/Local.php
Labels: 2. developing, bug

#23278 Allow subscription to indicate that a userlimit is reached
  build/psalm-baseline.xml
  core/Application.php
  core/Notification/CoreNotifier.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Support/Subscription/Registry.php
  lib/private/User/Manager.php
  lib/public/Support/Subscription/IRegistry.php
  lib/public/Support/Subscription/ISubscription.php
  tests/lib/Support/Subscription/DummySubscription.php
  tests/lib/Support/Subscription/RegistryTest.php
Labels: 3. to review, backport-request, enhancement

#24501 set mountid for personal external storage mounts
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Lib/PersonalMount.php
Labels: 3. to review, backport-request

#24459 Only execute plain mimetype check for directories and do the fallback…
  apps/workflowengine/lib/Check/FileMimeType.php
Labels: 3. to review, backport-request, bug, feature: workflows

#24519 Fix vsprint parameter
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-single-button.html
Labels: 4. to release, bug

#24516 Add icon to user limit notification
  core/Notification/CoreNotifier.php
Labels: 3. to review, backport-request

#24409 Also run repair steps when encryption is disabled but a legacy key is present
  lib/private/Repair/NC20/EncryptionLegacyCipher.php
  lib/private/Repair/NC20/EncryptionMigration.php
Labels: 4. to release, backport-request, bug

#24470 18.0.12 RC1
  version.php
Labels: 4. to release, overview

#24471 19.0.6 RC1
  version.php
Labels: 4. to release, overview

#24472 20.0.3 RC1
  version.php
Labels: 4. to release, overview

#24358 use storage copy implementation when doing dav copy
  apps/dav/lib/Connector/Sabre/Directory.php
Labels: 3. to review, performance 🚀

#24535 Fix the download of multiple files from the webUI
  lib/private/legacy/OC_Files.php
Labels: 4. to release, bug

#24474 Allow unified search results to have attributes
  apps/files/lib/Search/FilesSearchProvider.php
  lib/public/Search/SearchResultEntry.php
Labels: 4. to release, client: 🤖🍏 mobile, feature: search

#24543 Don't log params of imagecreatefromstring
  lib/private/Log/ExceptionSerializer.php
Labels: 4. to release, backport-request

#24545 Always install composer v2
  build/autoloaderchecker.sh
Labels: 3. to review, bug

#24550 Generate a new session id if the decrypting the session data fails
  lib/private/Session/CryptoSessionData.php
Labels: 3. to review, backport-request, enhancement

#24556 Revert "Do not read certificate bundle from data dir by default"
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 3. to review, bug

#24557 [stable20] dont use system composer for autoload checker
  .gitignore
  build/autoloaderchecker.sh
Labels: 3. to review, backport-request, bug

#24552 Remember me is not an app_password
  lib/private/User/Session.php
Labels: 3. to review, enhancement

#24578 Add integration tests for avatars
  .drone.yml
  build/integration/data/coloured-pattern.png
  build/integration/data/green-square-256.png
  build/integration/features/avatar.feature
  build/integration/features/bootstrap/Avatar.php
  build/integration/features/bootstrap/BasicStructure.php
Labels: 3. to review

#24581 Do not load nonexisting setup.js
  core/Controller/SetupController.php
Labels: 3. to review, backport-request, bug

#24586 18.0.12 RC2
  version.php
Labels: 2. developing, overview

#24585 19.0.6 RC2
  version.php
Labels: 2. developing, overview

#24584 20.0.3 RC2
  version.php
Labels: 2. developing, overview

#23780 PHP8 CI
  .drone.yml
  apps/dav/tests/unit/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJobTest.php
  apps/dav/tests/unit/CalDAV/Reminder/NotifierTest.php
  apps/dav/tests/unit/Command/MoveCalendarTest.php
  apps/encryption/lib/Crypto/Crypt.php
  apps/files_sharing/tests/CapabilitiesTest.php
  apps/files_trashbin/tests/ExpirationTest.php
  apps/files_versions/tests/ExpirationTest.php
  apps/user_ldap/tests/AccessTest.php
  build/psalm-baseline.xml
  lib/private/AppConfig.php
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/legacy/OC_Image.php
  tests/lib/App/CodeChecker/CodeCheckerTest.php
  tests/lib/App/CodeChecker/DeprecationCheckTest.php
  tests/lib/App/CodeChecker/NodeVisitorTest.php
  tests/lib/App/CodeChecker/StrongComparisonCheckTest.php
  tests/lib/AppConfigTest.php
  tests/lib/AppFramework/Db/EntityTest.php
  tests/lib/Avatar/UserAvatarTest.php
  tests/lib/ImageTest.php
  tests/lib/IntegrityCheck/CheckerTest.php
  tests/lib/LargeFileHelperGetFileSizeTest.php
  tests/lib/TestCase.php
  tests/lib/Traits/ClientServiceTrait.php
  tests/lib/Traits/EncryptionTrait.php
Labels: 3. to review, enhancement

#24598 Make debugging migration exceptions easier
  lib/private/DB/MigrationService.php
Labels: 3. to review, feature: install and update, technical debt

#24398 Do not update incompatible apps
  lib/private/Updater.php
  lib/private/legacy/OC_App.php
Labels: 4. to release, bug, feature: apps management

#24614 Skip the test if Imagick is misconfigured
  tests/lib/Preview/Provider.php
Labels: 3. to review, technical debt

#24247 Use string for storing a OCM remote id
  apps/federatedfilesharing/composer/composer/autoload_classmap.php
  apps/federatedfilesharing/composer/composer/autoload_static.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Migration/Version1010Date20200630191755.php
  apps/federatedfilesharing/lib/Migration/Version1011Date20201120125158.php
  apps/federatedfilesharing/lib/Notifications.php
  apps/files_sharing/appinfo/database.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/lib/Migration/Version11300Date20201120141438.php
  apps/files_sharing/tests/External/ManagerTest.php
  apps/settings/lib/Controller/CheckSetupController.php
  build/psalm-baseline.xml
  core/Command/Db/ConvertFilecacheBigInt.php
  tests/lib/DB/MigratorTest.php
Labels: 4. to release, bug, feature: federation

#24621 20.0.3
  version.php
Labels: 2. developing, overview

#24622 19.0.6
  version.php
Labels: 3. to review, overview

#24623 18.0.12
  version.php
Labels: 3. to review, overview

#24628 Fix loading order for OCS endpoints
  ocs/v1.php
Labels: 3. to review, bug, regression

#24605 Add deck share provider support
  apps/admin_audit/lib/Actions/Sharing.php
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
  apps/files/lib/Controller/ApiController.php
  apps/files/lib/Service/OwnershipTransferService.php
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/main.js
  apps/files_sharing/js/dist/main.js.map
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/index.js
  apps/files_sharing/src/mixins/ShareTypes.js
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/share.js
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/files_sharing/tests/MountProviderTest.php
  build/psalm-baseline.xml
  lib/private/Share/Constants.php
  lib/private/Share20/Manager.php
  lib/private/Share20/ProviderFactory.php
  lib/public/Share/IManager.php
  lib/public/Share/IProviderFactory.php
  lib/public/Share/IShare.php
  psalm.xml
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, enhancement

#23044 Handle owncloud migration to latest release
  apps/dav/lib/Migration/Version1004Date20170825134824.php
  apps/files_external/lib/Migration/Version1011Date20200630192246.php
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
  core/Migrations/Version13000Date20170919121250.php
  core/Migrations/Version21000Date20201120141228.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/DB/MigrationService.php
  lib/private/Repair.php
  lib/private/Repair/Owncloud/CleanPreviews.php
  lib/private/Repair/Owncloud/CleanPreviewsBackgroundJob.php
  lib/private/Repair/Owncloud/InstallCoreBundle.php
  lib/private/Repair/Owncloud/MoveAvatars.php
  lib/private/Repair/Owncloud/MoveAvatarsBackgroundJob.php
  lib/private/Repair/Owncloud/SaveAccountsTableData.php
  lib/private/Repair/Owncloud/UpdateLanguageCodes.php
  lib/private/Security/Bruteforce/Capabilities.php
  lib/private/Updater.php
  tests/Test/Repair/Owncloud/CleanPreviewsBackgroundJobTest.php
  tests/Test/Repair/Owncloud/CleanPreviewsTest.php
  tests/Test/Repair/Owncloud/InstallCoreBundleTest.php
  tests/Test/Repair/Owncloud/UpdateLanguageCodesTest.php
  version.php
Labels: 3. to review, enhancement, high

#24630 Error: Unknown named parameter $remote_id
  apps/files_sharing/tests/External/ManagerTest.php
Labels: 3. to review, bug

#24416 Check php compatibility of app store app releases
  lib/private/App/AppStore/Fetcher/AppFetcher.php
Labels: 3. to review, bug

#24643 Indicate preview availability in recent file api responses
  apps/files/lib/Controller/ApiController.php
Labels: 3. to review, bug, feature: files

#24635 Show email address for shares that were created by other users
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
Labels: 3. to review, bug

#24588 21 beta1
  version.php
Labels: 2. developing

#24679 Update comment to reflect current CSP policy
  lib/public/AppFramework/Http/ContentSecurityPolicy.php
Labels: 3. to review

#24631 Prevent * and other things in the same query for Oracle
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 3. to review, bug, technical debt

#24636 [stable20] Avoid dashboard crash when accessibility app is not installed
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/helpers/getBackgroundUrl.js
Labels: 3. to review, bug, feature: dashboard, javascript

#23017 Make share results distinguishable if there are more than one with the same display name
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntrySimple.vue
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/views/SharingList.vue
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: 4. to release, backport-request, bug, design, feature: sharing

#24589 Add tel, note, org and title search
  apps/dav/lib/Search/ContactsSearchProvider.php
  apps/dav/tests/unit/Search/ContactsSearchProviderTest.php
Labels: 3. to review, backport-request, bug, regression

#24693 20.0.4
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review, overview

#24695 Add missing parent::__construct() calls to Jobs
  apps/federatedfilesharing/lib/BackgroundJob/RetryJob.php
  apps/federation/lib/BackgroundJob/GetSharedSecret.php
  apps/federation/lib/BackgroundJob/RequestSharedSecret.php
  apps/settings/lib/BackgroundJobs/VerifyUserData.php
Labels: 4. to release, bug, regression, technical debt

#24683 [Fix #24682]: ensure federation cloud id is retruned if FN property not found
  lib/private/Federation/CloudIdManager.php
Labels: 3. to review, backport-request, bug

#24488 add text/org mimetype
  lib/private/Repair/RepairMimeTypes.php
  resources/config/mimetypemapping.dist.json
Labels: 3. to review, enhancement

#24713 Do not include non-required scripts on the upgrade page
  lib/private/legacy/OC_Template.php
Labels: 3. to review, backport-request, bug

#24402 LDAP: fix inGroup for memberUid type of group memberships
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: 3. to review, bug, feature: ldap

#24706 Log an error when setting a custom header on "Not Modified" responses
  lib/public/AppFramework/Http/Response.php
Labels: 4. to release, bug, technical debt

#24659 dav principal search to honour sharing.maxAutocompleteResults setting
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/DAV/GroupPrincipalBackend.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/DAV/GroupPrincipalTest.php
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/src/services/ConfigService.js
  config/config.sample.php
  lib/private/Contacts/ContactsMenu/Manager.php
  lib/private/Template/JSConfigHelper.php
  lib/public/Constants.php
  tests/lib/Contacts/ContactsMenu/ManagerTest.php
Labels: 4. to release, enhancement, feature: dav

#24629 Make $vars and $secureRandom required.
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  lib/base.php
  lib/private/AppFramework/Http/Request.php
Labels: 3. to review, enhancement

#24721 Cancel user search requests to avoid duplicate results being added
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users-6af167634af13765ed18.js
  apps/settings/js/vue-settings-users-6af167634af13765ed18.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users-56bf9f00883bb2b317ca.js
  apps/settings/js/vue-vendors-settings-apps-settings-users-56bf9f00883bb2b317ca.js.map
  apps/settings/js/vue-vendors-settings-users-7d5a89099bb7bbf586db.js
  apps/settings/js/vue-vendors-settings-users-7d5a89099bb7bbf586db.js.map
  apps/settings/src/store/api.js
  apps/settings/src/store/users.js
Labels: 4. to release, bug, feature: users and groups

#24725 Fix untranslated "User disabled" on login screen
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/LoginForm.vue
Labels: 4. to release, bug

#24194 Add action to clear all weather favorites
  apps/weather_status/js/weather-status.js
  apps/weather_status/js/weather-status.js.map
  apps/weather_status/src/App.vue
Labels: 3. to review, enhancement, feature: dashboard

#24717 promoted bad memory_limit check from warning to error as it may break updater
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 4. to release, enhancement, feature: settings

#24740 Improve hints for default_phone_region
  config/config.sample.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review, bug, feature: settings

#24737 Also unset the other possible unused paramters
  lib/private/Route/Router.php
Labels: 3. to review, backport-request, bug

#24685 21 beta2
  version.php
Labels: 2. developing, overview

#24703 enables the file name check also to match name of mountpoints
  apps/workflowengine/lib/Check/FileName.php
Labels: 3. to review, bug, feature: workflows

#24515 fixes sharing to group ids with characters that are being url encoded
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/DAV/GroupPrincipalBackend.php
  apps/dav/lib/DAV/Sharing/Backend.php
Labels: 3. to review, bug, feature: dav

#24702 Add well known handlers API
  .htaccess
  apps/settings/js/admin.js
  apps/settings/lib/AppInfo/Application.php
  core/Controller/WellKnownController.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  core/routes.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Http/WellKnown/RequestManager.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/Http/WellKnown/GenericResponse.php
  lib/public/Http/WellKnown/IHandler.php
  lib/public/Http/WellKnown/IRequestContext.php
  lib/public/Http/WellKnown/IResponse.php
  lib/public/Http/WellKnown/JrdResponse.php
  tests/Core/Controller/WellKnownControllerTest.php
  tests/lib/Http/WellKnown/GenericResponseTest.php
  tests/lib/Http/WellKnown/JrdResponseTest.php
  tests/lib/Http/WellKnown/RequestManagerTest.php
Labels: 3. to review, enhancement, integration, pending documentation

#24715 Limit getIncomplete query to one row
  lib/private/Files/Cache/Cache.php
Labels: 3. to review, technical debt

#23319 Fix Argon2 descriptions
  config/config.sample.php
Labels: 3. to review, security

#24730 Fix IPv6 localhost regex
  lib/private/AppFramework/Http/Request.php
Labels: 3. to review

#24796 Actually set the TTL on redis set
  lib/private/Memcache/Redis.php
Labels: 4. to release, backport-request, bug

#24732 Add another of my emails to mailmap
  .mailmap
Labels: 3. to review

#24604 Allow to force rename a conflicting calendar
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/Command/MoveCalendar.php
Labels: 3. to review, backport-request, feature: dav, pending documentation

#24594 files: Local#writeStream should use it's own file_put_contents
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/DAV.php
  lib/private/Files/Storage/Flysystem.php
  lib/private/Files/Storage/Local.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
Labels: 3. to review, enhancement

#22085 adding social profile to search index
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 3. to review, feature: dav

#22916 Unify links to php.net
  apps/files/lib/Command/Scan.php
  apps/files/lib/Command/ScanAppData.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php
  apps/files_sharing/lib/SharedStorage.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/templates/settings/admin/server.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/ILDAPWrapper.php
  apps/user_ldap/lib/LDAP.php
  build/stubs/gd.php
  build/stubs/imagick.php
  build/stubs/intl.php
  build/stubs/memcached.php
  config/config.sample.php
  console.php
  cron.php
  lib/private/AppFramework/Http/Request.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/private/Preview/HEIC.php
  lib/private/Share/SearchResultSorter.php
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_Image.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
  lib/public/Util.php
Labels: 3. to review, enhancement

#22222 re-index contacts with social profiles
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Migration/BuildSocialSearchIndex.php
  apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
Labels: 2. developing, 3. to review, enhancement, feature: dav

#24819 Update the Psalm baseline
  build/psalm-baseline.xml
Labels: 4. to release, technical debt

#24824 Catch the error on heartbeat update
  apps/user_status/js/user-status-menu.js
  apps/user_status/js/user-status-menu.js.map
  apps/user_status/src/UserStatus.vue
Labels: 3. to review, bug

#24610 adding a ShareDeletedEvent
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Share20/Manager.php
  lib/public/Share/Events/ShareDeletedEvent.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, enhancement

#24830 Add README section for committing back-end code
  README.md
Labels: 3. to review, bug

#24765 21 beta3
  resources/config/ca-bundle.crt
  version.php
Labels: overview

#19942 Add mindmap type file icon
  core/img/filetypes/mindmap.svg
  tests/data/integritycheck/mimetypeListModified/core/js/mimetypelist.js
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: 3. to review, enhancement

#24832 Make oc_files_trash.auto_id a bigint
  apps/files_trashbin/lib/Migration/Version1010Date20200630192639.php
  core/Command/Db/ConvertFilecacheBigInt.php
Labels: 3. to review, enhancement

#24833 Fix total upload size overwritten by next upload
  apps/files/js/file-upload.js
Labels: 3. to review, backport-request, bug, feature: files, regression

#24856 Add whitelist for apps inside of the server repo
  psalm.xml
Labels: 3. to review

#24872 Run jsunit with chromium/puppeteer
  .drone.yml
  .github/workflows/node.yml
  build/package-lock.json
  build/package.json
  core/js/core.json
  core/js/tests/specHelper.js
  core/js/tests/specs/jquery.avatarSpec.js
  tests/karma.config.js
Labels: 3. to review, technical debt

#24874 Avoid huge exception argument logging
  lib/private/Log.php
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review, enhancement

#24857 [stable18] Fix total upload size overwritten by next upload
  apps/files/js/file-upload.js
Labels: 3. to review, bug, regression

#22921 dont apply encryption wrapper for root mount
  lib/private/Encryption/EncryptionWrapper.php
Labels: 4. to release, bug

#24865 Cleanup bundle files before checking the rebuild
  .github/workflows/node.yml
Labels: 3. to review

#24860 Make sure we properly ass well-known paths to index.php
  .htaccess
Labels: 3. to review, bug

#24895 Make integration tests work with both PHP 7.3 and 7.4
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/FeatureContext.php
  build/integration/features/bootstrap/SharingContext.php
  build/integration/features/bootstrap/Trashbin.php
Labels: 3. to review, bug

#24903 Add dedicated baseline for OCP
  .github/workflows/static-code-analysis.yml
  build/psalm-baseline-ocp.xml
  psalm-ocp.xml
Labels: 3. to review, enhancement

#24852 21 beta4
  version.php
Labels: 2. developing, overview

#24864 Also include external share results in recommendations
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingInput.vue
Labels: 3. to review, enhancement
