Repository nextcloud/server, pull requests merged in 2020-04, with the labels that each got.

#20209 Add a shared php coding style fixer config
  .gitignore
  .php_cs.dist
  build/files-checker.php
  composer.json
  composer.lock
Labels: 3. to review, pending documentation, technical debt

#19781 Dont always use the current users quota when calculating storage info
  lib/private/legacy/helper.php
  lib/private/legacy/util.php
Labels: 3. to review, bug

#19890 Add optional comments reference_id
  apps/dav/tests/unit/Comments/CommentsNodeTest.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/Application.php
  core/Command/Db/AddMissingColumns.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Comments/Comment.php
  lib/private/Comments/Manager.php
  lib/private/DB/MissingColumnInformation.php
  lib/public/Comments/IComment.php
  lib/public/IDBConnection.php
Labels: 4. to release, enhancement, feature: comments, technical debt

#20268 Remove unneeded babel config variable
  babel.config.js
Labels: 4. to release

#20215 Align password reset arrow
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/ResetPassword.vue
Labels: 4. to release, bug, design

#20274 silence LDAP deprecation logs in NC 18
  apps/user_ldap/lib/LDAP.php
Labels: 4. to release, bug, feature: ldap

#19672 Fix cursor on click inputs and their descendants
  core/css/inputs.scss
Labels: 3. to review, bug, design

#19486 Improve performance of file scanner
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Storage/Local.php
  tests/lib/Files/ViewTest.php
Labels: 3. to review

#20275 Query Application class on publicwebdav
  apps/dav/appinfo/v1/publicwebdav.php
Labels: 4. to release, bug

#20244 Add basic progressbar to public upload page
  apps/files_sharing/css/public.scss
  apps/files_sharing/js/files_drop.js
  apps/files_sharing/js/templates.js
  apps/files_sharing/js/templates/files_drop.handlebars
  apps/files_sharing/templates/public.php
Labels: 4. to release, enhancement

#19913 Remove user name from public sharing page
  apps/files_sharing/css/public.scss
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/templates/public.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
Labels: 3. to review, bug, feature: sharing

#20257 19 beta 1
  version.php
Labels: 3. to review

#20293 fixes the return type of BeforeUserLoggedInEvent
  lib/public/User/Events/BeforeUserLoggedInEvent.php
Labels: 3. to review, backport-request, bug

#20284 Properly catch NoUserException during upload cleanup
  apps/dav/lib/BackgroundJob/UploadCleanup.php
  lib/private/Files/Node/Root.php
  lib/public/Files/IRootFolder.php
Labels: 4. to release, bug

#20139 Unify default value for restricting user enumeration with settings
  apps/dav/lib/CardDAV/SystemAddressbook.php
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  tests/acceptance/features/bootstrap/SettingsContext.php
  tests/acceptance/features/header.feature
  tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
Labels: 3. to review, bug

#20155 [stable18] Close updatenotification channel selector on click outside
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/UpdateNotification.vue
Labels: 3. to review, bug

#20157 [stable17] Close updatenotification channel selector on click outside
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/root.vue
Labels: 4. to release, bug

#20308 l10n: Changed spelling of WebAuthn
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/src/components/WebAuthn/AddDevice.vue
  apps/settings/src/components/WebAuthn/Section.vue
Labels: 3. to review, bug

#20309 l10n: Triple dot to ellipsis.
  apps/files_sharing/js/files_drop.js
Labels: 3. to review, bug

#19761 Add missing index to original migration
  apps/dav/lib/Migration/Version1004Date20170825134824.php
  apps/dav/lib/Migration/Version1006Date20180628111625.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review

#20276 allow setting tooltips for external storage config options
  apps/files_external/js/settings.js
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/tests/DefinitionParameterTest.php
Labels: 2. developing

#20331 Remove freenode badges
  README.md
Labels: 4. to release

#20033 Enable fseek for files in S3 storage
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
  lib/private/Files/Stream/SeekableHttpStream.php
  tests/lib/Files/ObjectStore/ObjectStoreTest.php
  tests/lib/Files/ObjectStore/S3Test.php
Labels: 3. to review

#20265 Move legacy classes from PSR0 to PSR4
  composer.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_namespaces.php
  lib/composer/composer/autoload_psr4.php
  lib/composer/composer/autoload_static.php
  lib/private/legacy/OC_API.php
  lib/private/legacy/OC_App.php
  lib/private/legacy/OC_DB.php
  lib/private/legacy/OC_DB_StatementWrapper.php
  lib/private/legacy/OC_Defaults.php
  lib/private/legacy/OC_EventSource.php
  lib/private/legacy/OC_FileChunking.php
  lib/private/legacy/OC_Files.php
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_Hook.php
  lib/private/legacy/OC_Image.php
  lib/private/legacy/OC_JSON.php
  lib/private/legacy/OC_Response.php
  lib/private/legacy/OC_Template.php
  lib/private/legacy/OC_User.php
  lib/private/legacy/OC_Util.php
  tests/lib/TemplateFunctionsTest.php
Labels: 3. to review, technical debt

#20188 Add default titles for titleless events in invitations
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: 3. to review, feature: dav

#20347 tests: fix failing header acceptance test
  tests/acceptance/features/bootstrap/ContactsMenuContext.php
Labels: 3. to review, bug

#18200 Add a PSR-3 logger adapter and make it injectable
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Log/PsrLoggerAdapter.php
  lib/private/Server.php
Labels: 3. to review, enhancement, pending documentation

#20299 fixes the throttler not checking the user state on postLogin
  lib/base.php
Labels: 3. to review, bug

#20343 Default to dark background in dark mode and better themed navbar
  core/css/header.scss
  core/css/styles.scss
Labels: 3. to review, bug, design, papercut

#20319 Use embedded previews of ZIP-like files
  config/config.sample.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Preview/Bundled.php
  lib/private/Preview/Krita.php
  lib/private/Preview/OpenDocument.php
  lib/private/PreviewManager.php
Labels: 4. to release, enhancement, feature: previews and thumbnails

#20360 Try to use the display name of file transfers
  apps/files/lib/Notification/Notifier.php
  apps/files/lib/Service/OwnershipTransferService.php
  lib/private/Files/Filesystem.php
Labels: 3. to review, backport-request, bug, feature: files

#20321 Check for triple dots in translations in CI
  autotest-checkers.sh
  build/triple-dot-checker.php
Labels: 3. to review, enhancement

#16035 dont show remote and email options if we have an exact match for local user email
  lib/private/Collaboration/Collaborators/Search.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: 3. to review, bug, enhancement, feature: federation, feature: sharing

#20363 update icewind/smb to 3.2.3
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Exception/ConnectionAbortedException.php
  apps/files_external/3rdparty/icewind/smb/src/Exception/ConnectionResetException.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeStream.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeWriteStream.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php
Labels: 3. to review, backport-request

#20303 19 beta 2
  version.php
Labels: 2. developing, overview

#20355 Clear comment on successful post
  apps/comments/js/comments.js
  apps/comments/js/comments.js.map
  apps/comments/src/commentstabview.js
Labels: 18-feedback, 3. to review, backport-request, bug, feature: comments, regression

#20376 Fix systemtags overflow
  core/css/systemtags.scss
  core/js/dist/systemtags.js
  core/js/dist/systemtags.js.map
Labels: 18-feedback, 4. to release, backport-request, bug, design

#20384 Use php keywords in lowercase
  apps/dav/tests/unit/CalDAV/ResourceBooking/ResourcePrincipalBackendTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/RoomPrincipalBackendTest.php
  apps/files_external/lib/Controller/UserStoragesController.php
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  core/Controller/SetupController.php
  core/templates/installation.php
  lib/private/ContactsManager.php
  lib/private/Group/Backend.php
  lib/private/Group/Group.php
  lib/private/Session/CryptoSessionData.php
  lib/private/User/Backend.php
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_User.php
Labels: 3. to review, technical debt

#20390 Do not use closing tags
  apps/settings/templates/settings/empty.php
Labels: 3. to review, technical debt

#20385 harden seekable http stream a bit against failures
  lib/private/Files/Stream/SeekableHttpStream.php
Labels: 3. to review

#20382 [stable18] Clear comment on successful post
  apps/comments/js/comments.js
  apps/comments/js/comments.js.map
  apps/comments/src/commentstabview.js
Labels: 18-feedback, 3. to review, bug, feature: comments, regression

#20387 [stable18] Fix systemtags overflow
  core/css/systemtags.scss
  core/js/dist/systemtags.js
  core/js/dist/systemtags.js.map
Labels: 18-feedback, 3. to review, bug, design, feature: tags

#19495 optimize batch generation of previews
  lib/private/Preview/Generator.php
  lib/private/PreviewManager.php
  lib/private/legacy/OC_Image.php
  lib/public/IImage.php
  lib/public/IPreview.php
  tests/lib/Preview/GeneratorTest.php
Labels: 2. developing, enhancement

#20185 Modify do_action so default ctrl-click opens tab
  apps/files/js/fileactions.js
  apps/files/js/fileactionsmenu.js
  apps/files/js/filelist.js
  apps/files/tests/js/filelistSpec.js
  apps/files_sharing/js/public.js
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/src/filelist.js
Labels: 4. to release, enhancement

#20035 Make sure group management works with all types of group names
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
  apps/settings/src/store/users.js
  apps/settings/src/views/Users.vue
Labels: 4. to release, backport-request, bug, feature: users and groups

#20439 Changing the translation catalog for "Share"
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/components/PersonalSettings.vue
Labels: 3. to review, bug, design, feature: sharing

#20421 Show setup check for recommended php modules
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 2. developing, enhancement

#20427 Fix password reset saying Admin changed my password when reset from login page
  apps/settings/lib/Activity/Provider.php
  apps/settings/lib/Hooks.php
Labels: 3. to review, bug

#20460 Fix app not listed in provisioning integration test
  build/integration/features/provisioning-v1.feature
Labels: 4. to release, bug

#20420 [18] Use a normal string to translate.
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/src/Accessibility.vue
Labels: 4. to release, bug

#20469 Properly display share error messages
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/mixins/SharesMixin.js
Labels: 18-feedback, 4. to release, backport-request, bug, design, feature: file sidebar, feature: sharing

#20189 [stable17] fix OCA\DAV\CalDAV\CalDavBackend search $options
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 4. to release, bug, feature: dav

#20190 [stable16] fix OCA\DAV\CalDAV\CalDavBackend search $options
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 4. to release, bug, feature: dav

#20470 Fix jsunit tests
  build/package-lock.json
  build/package.json
  tests/karma.config.js
Labels: 4. to release, bug, feature: dependencies

#20472 Verify that destination is not a directory.
  apps/dav/lib/Upload/ChunkingPlugin.php
  apps/dav/tests/unit/Upload/ChunkingPluginTest.php
Labels: 3. to review, bug

#20181 Also bail out when the path is actually null
  lib/private/Share20/DefaultShareProvider.php
Labels: 3. to review, bug, feature: sharing

#19936 Handle unset owner in sharing
  lib/private/Share20/Manager.php
Labels: 3. to review, bug, feature: filesystem

#20474 Update root.crl due to revocation of spgverein.crt
  resources/codesigning/root.crl
Labels: 3. to review, backport-request, security

#20476 Add php-cs check action
  .github/workflows/lint.yml
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
Labels: 4. to release, technical debt

#19351 Return hashes of uploaded content for dav uploads
  apps/dav/lib/Connector/Sabre/File.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Stream/HashWrapper.php
  tests/lib/Files/Stream/HashWrapperTest.php
Labels: 3. to review, enhancement

#20361 Close the streams in `writeStream` even when there is an exception
  lib/private/Files/Storage/Common.php
Labels: 3. to review, backport-request

#19191 Improve Opcache detection
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 4. to release, enhancement

#20401 Fix absolute redirect
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: 3. to review, backport-request, bug

#20138 Make remote checking more generic
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/RefreshWebcalServiceTest.php
  apps/files_sharing/lib/Controller/ExternalSharesController.php
  apps/files_sharing/tests/Controller/ExternalShareControllerTest.php
  build/integration/run.sh
  config/config.sample.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Http/Client/Client.php
  lib/private/Http/Client/ClientService.php
  lib/private/Server.php
  lib/public/Http/Client/LocalServerException.php
  tests/lib/Http/Client/ClientServiceTest.php
  tests/lib/Http/Client/ClientTest.php
Labels: 4. to release, bug, feature: federation

#20050 Make sure MySQL is not saying 'this' = 'this ' is true
  lib/private/DB/QueryBuilder/ExpressionBuilder/MySqlExpressionBuilder.php
  lib/private/User/Manager.php
Labels: 3. to review, bug

#20481 Add mindmap mimetype.
  core/js/mimetypelist.js
  resources/config/mimetypealiases.dist.json
  resources/config/mimetypemapping.dist.json
Labels: 3. to review

#19540 Fix issues with Keystone auth v3 in files_external app
  apps/files_external/lib/Lib/Auth/OpenStack/OpenStackV3.php
  apps/files_external/lib/Lib/Backend/Swift.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 4. to release, bug

#20500 Update editor config for .yml files
  .editorconfig
Labels: 3. to review, technical debt

#20037 do not use deprecated API for LDAP paged results
  .drone.yml
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Command/CheckUser.php
  apps/user_ldap/lib/ILDAPWrapper.php
  apps/user_ldap/lib/LDAP.php
  apps/user_ldap/lib/PagedResults/IAdapter.php
  apps/user_ldap/lib/PagedResults/Php54.php
  apps/user_ldap/lib/PagedResults/Php73.php
  apps/user_ldap/lib/PagedResults/TLinkId.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/LDAPTest.php
  apps/user_ldap/tests/User/UserTest.php
  build/integration/ldap_features/openldap-uid-username.feature
Labels: 3. to review, bug, enhancement, feature: ldap, technical debt

#20502 Print diff in cs:check command
  composer.json
Labels: 4. to release, enhancement, technical debt

#20458 16.0.10 RC1
  version.php
Labels: 4. to release, overview

#20457 17.0.6 RC1
  version.php
Labels: 2. developing, overview

#20456 18.0.4 RC1
  version.php
Labels: 2. developing, overview

#20501 Run cs:fix and fix HashWrapper code
  lib/private/Files/Stream/HashWrapper.php
  tests/lib/Files/Stream/HashWrapperTest.php
Labels: 3. to review

#20386 19 beta 3
  version.php
Labels: overview

#20503 DAV's exception logger should deal with any Throwable
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
Labels: 4. to release, bug, feature: dav

#20509 Revert "Make sure MySQL is not saying 'this' = 'this ' is true"
  lib/private/DB/QueryBuilder/ExpressionBuilder/MySqlExpressionBuilder.php
  lib/private/User/Manager.php
Labels: 3. to review, bug, high

#20506 19 beta 4
  version.php
Labels: 2. developing, overview

#20246 Provide the proper language to the mailer
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  apps/theming/lib/ThemingDefaults.php
  lib/private/Mail/EMailTemplate.php
  lib/private/Mail/Mailer.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  lib/private/legacy/OC_Defaults.php
  lib/public/Defaults.php
  lib/public/Mail/IEMailTemplate.php
  tests/lib/Mail/EMailTemplateTest.php
  tests/lib/Mail/MailerTest.php
Labels: 3. to review, backport-request, bug

#16946 Increase max read
  lib/private/Files/View.php
Labels: 3. to review, enhancement, feature: external storage, feature: object storage

#20511 PHP-CS-Fixer green
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/LDAP.php
  apps/user_ldap/lib/PagedResults/IAdapter.php
  apps/user_ldap/lib/PagedResults/Php54.php
  apps/user_ldap/lib/PagedResults/Php73.php
  apps/user_ldap/lib/PagedResults/TLinkId.php
  apps/user_ldap/tests/User/UserTest.php
  lib/public/Http/Client/LocalServerException.php
Labels: 4. to release

#20505 do not advertise nulled userId for for systemwide credentials
  lib/private/Security/CredentialsManager.php
  lib/public/Security/ICredentialsManager.php
  tests/lib/Security/CredentialsManagerTest.php
Labels: 3. to review, backport-request, bug

#20523 Rename updatenotifications webpack module to updatenotification
  webpack.common.js
Labels: 3. to review, bug

#20381 Allow to edit admin user
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 4. to release, backport-request

#20447 Increase max-height on button in welcome email template
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email.html
Labels: 4. to release, bug, design, feature: emails

#20529 Update list of multiple properties
  apps/dav/lib/CardDAV/AddressBookImpl.php
  apps/dav/tests/unit/CardDAV/AddressBookImplTest.php
Labels: 4. to release, backport-request, bug, feature: dav

#19901 Improved vcard photo handling
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/CardDAV/HasPhotoPlugin.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: 3. to review, bug, feature: dav

#20537 allow local remote access in external storage ci
  autotest-external.sh
Labels: 3. to review

#20540 Fix mailer test
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  tests/data/emails/new-account-email-single-button.html
Labels: 3. to review

#20449 Array offset error due to empty file versions array
  apps/files_versions/lib/Storage.php
  apps/files_versions/tests/VersioningTest.php
Labels: 4. to release, backport-request, bug

#19214 Move to subfolders for preview files
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Preview/BackgroundCleanupJob.php
  lib/private/Preview/Storage/Root.php
  lib/private/Server.php
  tests/lib/Preview/BackgroundCleanupJobTest.php
Labels: 3. to review, enhancement, feature: previews and thumbnails

#20530 [18] Allow to edit admin user
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 3. to review

#20547 16.0.10 RC2
  version.php
Labels: 2. developing, overview

#20545 18.0.4 RC2
  version.php
Labels: 2. developing, overview

#20546 17.0.6 RC2
  version.php
Labels: 2. developing, overview

#20232 Add method to storage backends to get directory content with metadata
  apps/files_external/lib/Lib/Storage/SMB.php
  apps/files_sharing/lib/External/Scanner.php
  apps/files_sharing/lib/Scanner.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/ObjectStore/NoopScanner.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Local.php
  lib/private/Files/Storage/Storage.php
  lib/private/Files/Storage/Wrapper/Availability.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/PermissionsMask.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
Labels: 3. to review

#20564 Set fileInfo correctly for LegacyTabs
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/components/LegacyTab.vue
Labels: 3. to review, bug, feature: file sidebar

#20577 Fix usages of afterMethod -> afterMethod:*
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/lib/Connector/Sabre/LockPlugin.php
Labels: 4. to release

#20552 Disable autocapitalize for username field on login / reset password pages
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/LoginForm.vue
  core/src/components/login/ResetPassword.vue
Labels: 4. to release, enhancement

#20590 [stable16] Fix MariaDB/MySQL version check
  lib/private/Setup/MySQL.php
Labels: 4. to release, bug, feature: install and update

#20536 do not run paged results against ldap_read ops on PHP7.3+
  apps/user_ldap/lib/PagedResults/Php73.php
Labels: 4. to release, bug, feature: ldap

#20591 Fix settings routing
  apps/settings/appinfo/routes.php
  lib/private/AppFramework/Routing/RouteConfig.php
  tests/lib/AppFramework/Routing/RoutingTest.php
Labels: 3. to review

#20575 Fix Sharing recommendation user display
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/src/components/SharingInput.vue
Labels: 3. to review, backport-request, bug, feature: file sidebar, feature: sharing

#20580 18.0.4
  version.php
Labels: 2. developing, overview

#20581 17.0.6
  version.php
Labels: 2. developing, overview

#20582 16.0.10
  version.php
Labels: 2. developing, overview

#20595 Fix IE11 upload fallback methods
  apps/files/js/file-upload.js
Labels: 4. to release, backport-request, bug, feature: files

#20576 Make sure that OC-ETag is set again
  apps/dav/lib/Connector/Sabre/CopyEtagHeaderPlugin.php
Labels: 4. to release, bug

#19399 Add option to check share ACL's when listing directories
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#20510 19 Beta 5
  version.php
Labels: 2. developing, overview

#20599 filter out blacklisted files in getDirectoryContent
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  lib/private/Files/Storage/Common.php
Labels: 3. to review, feature: filesystem

#20618 Fix workflow UI
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Check.vue
  apps/workflowengine/src/components/Checks/FileMimeType.vue
  apps/workflowengine/src/components/Checks/MultiselectTag/MultiselectTag.vue
  apps/workflowengine/src/components/Checks/RequestTime.vue
  apps/workflowengine/src/components/Checks/RequestURL.vue
  apps/workflowengine/src/components/Checks/RequestUserAgent.vue
  apps/workflowengine/src/components/Checks/RequestUserGroup.vue
  apps/workflowengine/src/components/Event.vue
  apps/workflowengine/src/components/Rule.vue
Labels: 4. to release, bug, feature: workflows, high, regression

#20621 [stable16] Fix jsunit tests
  build/package-lock.json
  build/package.json
Labels: 3. to review, bug

#18816 Use paginated search for contacts
  apps/dav/lib/CardDAV/AddressBookImpl.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  lib/private/ContactsManager.php
  lib/public/Contacts/IManager.php
  lib/public/IAddressBook.php
Labels: 4. to release, bug, performance 🚀

#19919 LDAP Group Backend optimizations
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Group_Proxy.php
  apps/user_ldap/lib/Helper.php
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/lib/Mapping/GroupMapping.php
  apps/user_ldap/lib/Mapping/UserMapping.php
  apps/user_ldap/lib/Proxy.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: 4. to release, enhancement, feature: ldap

#20626 Add folder argument to files:scan-app-data
  apps/files/lib/Command/ScanAppData.php
Labels: 3. to review, enhancement

#20627 Remove obsolete repair steps for logo and updater channel
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC17/SetEnterpriseLogo.php
  lib/private/Repair/NC17/SwitchUpdateChannel.php
Labels: 3. to review, backport-request

#17623 Add support for download share on old android browser
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 3. to review, enhancement

#20570 Use a proper upload file so propfinds return 404
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Upload/UploadFile.php
  apps/dav/lib/Upload/UploadFolder.php
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/TagsPluginTest.php
Labels: 3. to review, bug

#20587 Allow specifying a default expiration date
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, enhancement, feature: sharing

#19002 Fix security header setting in .htaccess by adding 'onsuccess unset'
  .htaccess
Labels: 3. to review, enhancement

#20678 Fix missing argument in JSConfigHelper
  core/Controller/OCJSController.php
Labels: 3. to review, bug, high, regression

#20632 Only catch anonymous OPTIONS for Office
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/tests/unit/DAV/AnonymousOptionsTest.php
Labels: 3. to review, backport-request, bug

#19084 Make it possible to resolve svg's outside \OC::$SERVERROOT
  core/Controller/SvgController.php
  tests/Core/Controller/SvgControllerTest.php
  tests/data/svg/files-app-red.svg
  tests/data/svg/settings-admin-red.svg
  tests/lib/App/AppManagerTest.php
Labels: 4. to release, bug

#19514 Already enabled apps
  core/Command/App/Enable.php
  tests/Core/Command/Apps/AppsEnableTest.php
Labels: 4. to release, bug

#19793 Fix resharing of federated shares that were created out of links
  apps/federatedfilesharing/lib/Controller/MountPublicLinkController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  build/integration/sharing_features/sharing-v1.feature
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, bug

#19929 Delete avatar if a user is deleted
  lib/private/Avatar/AvatarManager.php
  lib/private/User/User.php
Labels: 4. to release, bug, feature: users and groups

#20650 Adhere to EMailTemplate interface in constructor call.
  lib/private/Mail/Mailer.php
Labels: 3. to review, bug, high

#20673 Set exit code if something went wrong.
  apps/files/lib/Command/ScanAppData.php
Labels: 4. to release, enhancement

#20676 Don't remove last user in ldap group when limit is -1
  apps/user_ldap/lib/Group_LDAP.php
Labels: 3. to review, backport-request, bug, feature: ldap

#20620 [stable17] Fix jsunit tests
  build/package-lock.json
  build/package.json
Labels: 3. to review, bug

#20636 Add tests for update notification controller for non-default updater …
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/tests/Settings/AdminTest.php
Labels: 3. to review

#20262 Allow to navigate to others with access from the sidebar
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/collaboration.js
  apps/files_sharing/js/dist/collaboration.js.map
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/main.js
  apps/files_sharing/js/dist/main.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntryInherited.vue
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/views/SharingInherited.vue
Labels: 3. to review

#20720 Temporary fix contacts search
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 3. to review, bug, high

#20717 Define getSystemValueBool/Int/String function default parameter with correct type
  lib/private/AllConfig.php
Labels: 3. to review

#18883 Optimize Openstack Swift files download
  lib/private/Files/ObjectStore/Swift.php
  lib/private/Files/ObjectStore/SwiftFactory.php
Labels: 3. to review, enhancement

#19039 Provide links to calendar in event creation/update activities
  apps/dav/lib/CalDAV/Activity/Backend.php
  apps/dav/lib/CalDAV/Activity/Provider/Base.php
  apps/dav/lib/CalDAV/Activity/Provider/Calendar.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/tests/unit/CalDAV/Activity/BackendTest.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/BaseTest.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/EventTest.php
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review

#19436 Do not include mountpoints when calculating quota usage on WebDAV
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
Labels: 3. to review, bug

#20640 Correctly hide table headers in filepicker
  core/css/mobile.scss
Labels: 3. to review, bug, design, feature: filepicker

#20677 Scaling user provisioning for subadmins with many groups
  apps/provisioning_api/lib/Controller/UsersController.php
  lib/private/SubAdmin.php
Labels: 3. to review, enhancement, feature: users and groups

#20718 Add a wrapper to fall back to the share owner on public shares
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Storage/PublicOwnerWrapper.php
Labels: 3. to review, bug

#20742 Run the cs fixer for green ci
  lib/private/Files/ObjectStore/Swift.php
Labels: 4. to release

#20710 Fix Argon2 options checks
  lib/private/Security/Hasher.php
  tests/lib/Security/HasherTest.php
Labels: 4. to release, bug

#20611 19 beta 6
  version.php
Labels: 2. developing, overview

#20744 Fix public layout header title & description
  apps/files_sharing/css/public.scss
  core/css/header.scss
  core/templates/layout.public.php
Labels: 4. to release, backport-request, bug, design, feature: sharing

#20725 Fix getDirectoryContent implementation for Jail wrapper
  lib/private/Files/ObjectStore/SwiftFactory.php
  lib/private/Files/Storage/Wrapper/Jail.php
  tests/lib/Files/Storage/Storage.php
Labels: 3. to review

#20538 Fix share expiration date not shown
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
Labels: 4. to release, bug
