Repository nextcloud/server, pull requests merged in 2020-05, with the labels that each got.

#20291 Fix focus for user actionmenu
  apps/settings/css/settings.scss
  apps/settings/js/vue-1.js
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-editor-collab.js
  apps/settings/js/vue-editor-collab.js.map
  apps/settings/js/vue-editor-guest.js
  apps/settings/js/vue-editor-guest.js.map
  apps/settings/js/vue-editor-rich.js
  apps/settings/js/vue-editor-rich.js.map
  apps/settings/js/vue-editor.js
  apps/settings/js/vue-editor.js.map
  apps/settings/js/vue-files-modal.js
  apps/settings/js/vue-files-modal.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-vendors-editor-collab-editor-guest.js
  apps/settings/js/vue-vendors-editor-collab-editor-guest.js.map
  apps/settings/js/vue-vendors-files-modal.js
  apps/settings/js/vue-vendors-files-modal.js.map
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 4. to release, bug, feature: accessibility, feature: users and groups

#20380 Fix design and layout of notification mails
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email-single-button.html
  tests/data/emails/new-account-email.html
Labels: 3. to review, bug, design, feature: emails

#20761 Fix owner on publicownerwrapper
  apps/dav/lib/Storage/PublicOwnerWrapper.php
Labels: 4. to release

#20716 Add index to properties table
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review

#20759 Update education bundle
  lib/private/App/AppStore/Bundles/EducationBundle.php
  tests/lib/App/AppStore/Bundles/EducationBundleTest.php
Labels: 3. to review

#20767 Apply Argon2 options for Argon2id hashing as well
  lib/private/Security/Hasher.php
Labels: 3. to review, enhancement

#20771 Do not process the same shares twice
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/views/SharingTab.vue
Labels: 3. to review, bug, feature: sharing, high

#20762 Fix expiry datepicker allowing all dates
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
Labels: 3. to review, bug

#20779 Comply with php-cs for CI
  core/templates/layout.public.php
Labels: 3. to review, bug

#19124 Exclude groups from sharing: Skip delete groups
  apps/settings/js/settings.js
Labels: 3. to review, bug

#20787 Fix OC_Image new resize functions
  lib/private/legacy/OC_Image.php
Labels: 4. to release, bug, feature: previews and thumbnails

#20722 Set etag for capabilities endpoint
  core/Controller/OCSController.php
  tests/Core/Controller/OCSControllerTest.php
Labels: 4. to release, enhancement

#20807 clarified trash bin retention by storage shortage override in config.sample.php
  config/config.sample.php
Labels: 3. to review, backport-request

#20726 Fix federated link sharing permissions
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
Labels: 19-feedback, 2. developing, bug, feature: federation, feature: sharing, high

#20754 19 beta 7
  version.php
Labels: 2. developing, overview

#20825 Fix filtering our owner & current user from shares
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingInput.vue
Labels: 4. to release, backport-request, feature: sharing, high, regression

#18955 Large Object support for OpenStack Swift
  lib/private/Files/ObjectStore/Swift.php
Labels: 4. to release

#20832 Do not filter id matching userId on non-user-share shares
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntry.vue
Labels: 3. to review, backport-request, feature: sharing, high, regression

#20837 Fix syntax
  core/Command/Maintenance/UpdateTheme.php
Labels: 3. to review, bug

#20841 add locking to resolve concurent move to trashbin conflicts
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/tests/StorageTest.php
Labels: 4. to release

#20823 19 RC1
  version.php
Labels: 2. developing, overview

#20782 Simple AppConfig wrapper for the AppFramework
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Services/AppConfig.php
  lib/public/AppFramework/Services/IAppConfig.php
Labels: 3. to review, enhancement

#20831 Do not process the same FileInfo twice
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/views/SharingTab.vue
Labels: 3. to review, bug

#20849 20 in development now
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 3. to review

#20853 Fix color-text-maxcontrast not passing WCAG AA
  core/css/variables.scss
Labels: 3. to review, backport-request, bug, design, feature: accessibility

#20859 Validate app password on alternative login
  core/Controller/ClientFlowLoginController.php
Labels: 3. to review, enhancement

#20864 Install page app naming
  core/templates/installation.php
Labels: 3. to review, enhancement

#20868 Fix linter warnings for the updatenotification
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/UpdateNotification.vue
Labels: 3. to review, enhancement, javascript

#20867 Fix linter warnings in workflowengine
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Checks/FileMimeType.vue
  apps/workflowengine/src/components/Checks/RequestUserGroup.vue
  apps/workflowengine/src/helpers/api.js
Labels: 3. to review, enhancement

#20719 Fix languages empty array
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  apps/settings/lib/Controller/UsersController.php
  lib/private/L10N/Factory.php
Labels: 4. to release, backport-request, bug, feature: language l10n and translations, feature: users and groups

#20815 get only groupids in default share backend
  lib/private/Share20/DefaultShareProvider.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 4. to release, enhancement, feature: sharing

#20860 macOS contacts: prefer personal over app generated
  apps/contactsinteraction/lib/AddressBook.php
  apps/contactsinteraction/lib/Card.php
  apps/contactsinteraction/lib/Db/RecentContactMapper.php
  apps/dav/lib/CardDAV/Integration/ExternalAddressBook.php
Labels: 3. to review

#20852 Add InitialState Appframework service
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Services/InitialState.php
  lib/public/AppFramework/Services/IInitialState.php
Labels: 4. to release, enhancement, pending documentation

#20875 Fix linter warnings on twofactor_backupcodes
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/src/service/BackupCodesService.js
Labels: 4. to release, enhancement, javascript

#20786 DI Cleanup
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/Server.php
Labels: 3. to review, enhancement

#20844 Translate the maintenance mode message in webdav
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/appinfo/v1/webdav.php
  apps/dav/appinfo/v2/direct.php
  apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php
  apps/dav/lib/Connector/Sabre/MaintenancePlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Direct/ServerFactory.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/MaintenancePluginTest.php
  apps/dav/tests/unit/Connector/Sabre/RequestTest/RequestTestCase.php
Labels: 3. to review, enhancement

#20915 Use random_bytes
  lib/private/Security/Crypto.php
  tests/lib/Security/CryptoTest.php
Labels: 3. to review, backport-request, enhancement

#20901 Fix some js linter warnings in comments
  apps/comments/js/comments.js.map
  apps/comments/src/commentmodel.js
  apps/comments/src/commentsummarymodel.js
  apps/comments/src/filesplugin.js
Labels: 3. to review, enhancement, javascript

#20876 Fix some linter warnings in settings
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-8.js
  apps/settings/js/vue-8.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/src/components/AdminTwoFactor.vue
  apps/settings/src/components/AppList/AppScore.vue
  apps/settings/src/components/AuthTokenSection.vue
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  apps/settings/src/components/WebAuthn/AddDevice.vue
  apps/settings/src/components/WebAuthn/Section.vue
  apps/settings/src/mixins/UserRowMixin.js
  apps/settings/src/router.js
  apps/settings/src/store/api.js
  apps/settings/src/store/apps.js
  apps/settings/src/store/oc.js
  apps/settings/src/store/users.js
Labels: 3. to review, enhancement, javascript

#20270 Add AppFramework compression middleware to gzip responses
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/CompressionMiddleware.php
  tests/lib/AppFramework/Middleware/CompressionMiddlewareTest.php
Labels: 4. to release, enhancement

#20858 Remember the webauthn name of devices
  lib/private/Authentication/WebAuthn/CredentialRepository.php
Labels: 3. to review, bug

#20813 generalize the "lazy folder" concept
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/LazyRoot.php
Labels: 4. to release, enhancement

#20933 Move the password confirmation form template to post
  core/templates/layout.user.php
Labels: 3. to review, enhancement

#20943 Cache the avatar for a day
  core/Controller/AvatarController.php
Labels: 3. to review, enhancement

#20897 Proxy server could cache http response when it is not private
  lib/public/AppFramework/Http/Response.php
  tests/lib/AppFramework/Http/ResponseTest.php
Labels: 2. developing

#20939 Move not modified check to the middleware
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Http.php
  lib/private/AppFramework/Http/Dispatcher.php
  lib/private/AppFramework/Middleware/NotModifiedMiddleware.php
  tests/lib/AppFramework/Http/DispatcherTest.php
  tests/lib/AppFramework/Http/HttpTest.php
  tests/lib/AppFramework/Middleware/NotModifiedMiddlewareTest.php
Labels: 4. to release, enhancement, technical debt

#20946 Declare ext-json as dependency in composer.json
  composer.json
  composer.lock
Labels: 4. to release, enhancement, technical debt

#20951 Trailing comma's in functin arguments break on 7.2
  core/Controller/OCJSController.php
Labels: 4. to release, backport-request, bug

#20952 Respect exit code of lint run - changed from -exec to xargs as this exits properly
  composer.json
  lib/private/AppFramework/Services/AppConfig.php
Labels: 4. to release, backport-request

#20958 Allow links to conversations
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review, bug, feature: activity and notification

#20956 l10n: Adding "The" to the description
  core/ajax/update.php
Labels: 4. to release, design

#20932 l10n: Changing the word "These" to "Following"
  core/templates/update.admin.php
Labels: 3. to review, design

#20960 [stable19] Respect exit code of lint run - changed from -exec to xargs as this e…
  composer.json
Labels: 3. to review

#20850 19 RC2
  version.php
Labels: 2. developing, overview

#20947 Bump yargs-parser
  package-lock.json
Labels: 4. to release, backport-request, feature: dependencies, security

#20955 [stable18] Proxy server could cache http response when it is not private
  lib/public/AppFramework/Http/Response.php
  tests/lib/AppFramework/Http/ResponseTest.php
Labels: 4. to release, backport-request

#20941 update icewind/smb to 3.2.4
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php
Labels: 3. to review, backport-request

#20987 Allow TemplateResponse to be compressed
  lib/private/AppFramework/Middleware/CompressionMiddleware.php
Labels: 3. to review, enhancement, performance 🚀

#20957 l10n: Adding "The" before "Following"
  lib/private/App/DependencyAnalyzer.php
  tests/lib/App/DependencyAnalyzerTest.php
Labels: 3. to review, design

#20629 Don't load text file preview when text app is available (Fixes: #20615)
  apps/files_sharing/js/public.js
Labels: 4. to release, bug, feature: previews and thumbnails, feature: sharing

#21003 Remove entries from locales.json incompatible with punic
  resources/locales.json
  resources/update-locales.php
Labels: 3. to review, bug

#21017 Remove group from excluded_groups_list after delete
  lib/private/Share20/Manager.php
Labels: 3. to review, technical debt

#20846 Link permissions
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  build/integration/sharing_features/sharing-v1.feature
Labels: 4. to release, backport-request, bug, feature: sharing

#21033 Provide capabilities via initialstate
  lib/private/Template/JSConfigHelper.php
Labels: 3. to review, enhancement, javascript

#21044 Add a message to the log entry of an app being disabled
  lib/private/legacy/OC_App.php
Labels: 4. to release

#21041 Copy over the ETag and LastModified when formatting a Dataresponse
  lib/public/AppFramework/Controller.php
Labels: 3. to review, enhancement

#21050 Caching and compression for app store requests
  lib/private/App/AppStore/Fetcher/Fetcher.php
  tests/lib/App/AppStore/Fetcher/FetcherBase.php
Labels: 3. to review, backport-request, bug

#21054 Allow gzip encoded requests by default
  lib/private/App/AppStore/Fetcher/Fetcher.php
  lib/private/Http/Client/Client.php
  tests/lib/App/AppStore/Fetcher/FetcherBase.php
  tests/lib/Http/Client/ClientTest.php
Labels: 4. to release, enhancement

#20964 19 RC3
  version.php
Labels: 2. developing, overview

#21018 Create account structure also for empty record
  lib/private/Accounts/AccountManager.php
Labels: 3. to review, bug

#20586 Improve build/image-optimization.sh
  build/image-optimization.sh
Labels: 3. to review, technical debt

#20814 dont get the group details if we only ask for the id
  lib/private/Group/Manager.php
  tests/lib/Group/ManagerTest.php
Labels: 3. to review, enhancement

#20776 Improve group queries
  lib/private/Group/Database.php
Labels: 4. to release, enhancement

#21065 Clear the statscache before fetching the metadata
  lib/private/Files/Storage/Local.php
Labels: 3. to review, bug

#20005 Implement occ command to reset bruteforce attemps from a given IP address
  core/Command/Security/ResetBruteforceAttempts.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Security/Bruteforce/Throttler.php
Labels: 3. to review, enhancement

#21090 Do not read certificate bundle from data dir by default
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 4. to release, backport-request, bug

#21092 Update recommended apps
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  core/src/components/setup/RecommendedApps.vue
  lib/private/App/AppStore/Bundles/HubBundle.php
  lib/private/Setup.php
Labels: 3. to review, backport-request, enhancement

#21105 Update recommended apps
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  core/src/components/setup/RecommendedApps.vue
  lib/private/App/AppStore/Bundles/HubBundle.php
  lib/private/Setup.php
Labels: 4. to release, enhancement

#21060 19 Final
  version.php
Labels: 2. developing, overview

#21108 fixes infinitely repeating LDPA search results with PHP <= 7.2
  apps/user_ldap/lib/Access.php
Labels: 3. to review, backport-request, bug, feature: ldap, regression

#21106 use the loginname to verify the old password in user password changes
  apps/settings/lib/Controller/ChangePasswordController.php
  tests/Core/Controller/ChangePasswordControllerTest.php
Labels: 4. to release, backport-request, bug, feature: users and groups

#21117 Simplify text variables from 4 to 2, map -lighter to -maxcontrast
  core/css/css-variables.scss
  core/css/variables.scss
Labels: 3. to review, design, enhancement

#21112 Remove db prefix option from cli install command
  autotest-external.sh
  autotest.sh
  core/Command/Maintenance/Install.php
Labels: 3. to review, feature: install and update, technical debt

#21123 simplify getGroups, fixing wrong chunking logic
  apps/user_ldap/lib/Group_LDAP.php
Labels: 4. to release, backport-request, bug, feature: ldap

#21122 Improve traces of invalid token exceptions
  lib/private/Authentication/Exceptions/InvalidTokenException.php
  lib/private/Authentication/Token/DefaultTokenProvider.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/User/Session.php
Labels: 4. to release

#21124 Add a capability when file comments are enabled
  apps/comments/composer/composer/autoload_classmap.php
  apps/comments/composer/composer/autoload_static.php
  apps/comments/lib/AppInfo/Application.php
  apps/comments/lib/Capabilities.php
Labels: 4. to release, enhancement, feature: comments

#20597 Add lazy events for the Node API
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Node/HookConnector.php
  lib/private/Server.php
  lib/public/Files/Events/Node/AbstractNodeEvent.php
  lib/public/Files/Events/Node/AbstractNodesEvent.php
  lib/public/Files/Events/Node/BeforeNodeCopiedEvent.php
  lib/public/Files/Events/Node/BeforeNodeCreatedEvent.php
  lib/public/Files/Events/Node/BeforeNodeDeletedEvent.php
  lib/public/Files/Events/Node/BeforeNodeReadEvent.php
  lib/public/Files/Events/Node/BeforeNodeRenamedEvent.php
  lib/public/Files/Events/Node/BeforeNodeTouchedEvent.php
  lib/public/Files/Events/Node/BeforeNodeWrittenEvent.php
  lib/public/Files/Events/Node/NodeCopiedEvent.php
  lib/public/Files/Events/Node/NodeCreatedEvent.php
  lib/public/Files/Events/Node/NodeDeletedEvent.php
  lib/public/Files/Events/Node/NodeRenamedEvent.php
  lib/public/Files/Events/Node/NodeTouchedEvent.php
  lib/public/Files/Events/Node/NodeWrittenEvent.php
  tests/lib/Files/Node/HookConnectorTest.php
Labels: 4. to release, enhancement, pending documentation

#21063 16.0.11 RC1
  version.php
Labels: 3. to review, overview

#21110 [stable17] Fix resharing of federated shares that were created out of links
  apps/federatedfilesharing/lib/Controller/MountPublicLinkController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  build/integration/features/sharing-v1.feature
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, bug, feature: federation, feature: sharing

#21062 17.0.7 RC1
  version.php
Labels: 2. developing, overview

#21109 [stable18] Fix resharing of federated shares that were created out of links
  apps/federatedfilesharing/lib/Controller/MountPublicLinkController.php
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/tests/ApiTest.php
  build/integration/sharing_features/sharing-v1.feature
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, bug, feature: federation, feature: sharing

#21061 18.0.5 RC1
  version.php
Labels: 2. developing, overview

#21140 Document \OC_App::getAllApps return type
  lib/private/legacy/OC_App.php
Labels: 4. to release, enhancement

#21146 Fix reference to wrong class name
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 4. to release, backport-request, bug, feature: sharing

#21118 Move systemtags to a proper location
  apps/systemtags/templates/admin.php
  apps/workflowengine/lib/AppInfo/Application.php
  core/js/core.json
  core/js/dist/systemtags.js
  core/js/dist/systemtags.js.map
  core/js/systemtags/templates.js
  core/src/systemtags/merged-systemtags.js
  core/src/systemtags/systemtagmodel.js
  core/src/systemtags/systemtags.js
  core/src/systemtags/systemtagscollection.js
  core/src/systemtags/systemtagsinputfield.js
  core/src/systemtags/systemtagsmappingcollection.js
  core/src/systemtags/templates/result.handlebars
  core/src/systemtags/templates/result_form.handlebars
  core/src/systemtags/templates/selection.handlebars
  core/webpack.js
  tests/karma.config.js
Labels: 3. to review, technical debt

#21143 Fix password changes in link and mail shares
  .drone.yml
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  build/integration/config/behat.yml
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/FakeSMTPHelper.php
  build/integration/features/bootstrap/Mail.php
  build/integration/features/bootstrap/Sharing.php
  build/integration/features/bootstrap/SharingContext.php
  build/integration/features/bootstrap/TalkContext.php
  build/integration/sharing_features/sharing-v1-video-verification.feature
  build/integration/sharing_features/sharing-v1.feature
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, backport-request, bug, feature: sharing

#21141 List ext-pdo as hard requirement for composer
  composer.json
  composer.lock
Labels: 3. to review, enhancement, technical debt

#21156 Do not clone the whole Talk repository for integration tests
  .drone.yml
Labels: 3. to review, bug

#21154 Fix the loading order of the js files_info and files_client
  lib/private/legacy/OC_Template.php
Labels: 4. to release, bug
