Repository nextcloud/server, pull requests merged in 2020-07, with the labels that each got.

#19646 Change OAuth2 redirect link to relative link
  core/templates/loginflow/authpicker.php
Labels: 3. to review, bug

#21652 Log deprecated events as debug
  lib/private/EventDispatcher/SymfonyAdapter.php
Labels: 3. to review, enhancement

#21653 Fix IPv6 remote addresses from X_FORWARDED_FOR headers before validating
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3. to review, bug

#21599 Replace TYPE with TYPES
  apps/dav/lib/Migration/Version1005Date20180413093149.php
  apps/dav/lib/Migration/Version1005Date20180530124431.php
  apps/dav/lib/Migration/Version1006Date20180619154313.php
  apps/dav/lib/Migration/Version1006Date20180628111625.php
  apps/dav/lib/Migration/Version1008Date20181030113700.php
  apps/dav/lib/Migration/Version1008Date20181105104826.php
  apps/dav/lib/Migration/Version1008Date20181105110300.php
  apps/dav/lib/Migration/Version1011Date20190725113607.php
  apps/dav/lib/Migration/Version1011Date20190806104428.php
  apps/dav/lib/Migration/Version1012Date20190808122342.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20170607104347.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20170919123342.php
  apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
  core/Command/Db/ConvertFilecacheBigInt.php
  core/Migrations/Version13000Date20170705121758.php
  core/Migrations/Version13000Date20170718121200.php
  core/Migrations/Version14000Date20180710092004.php
  core/Migrations/Version16000Date20190207141427.php
  core/Migrations/Version16000Date20190212081545.php
  core/Migrations/Version16000Date20190428150708.php
  core/Migrations/Version17000Date20190514105811.php
  core/Migrations/Version18000Date20190920085628.php
  core/Migrations/Version18000Date20191014105105.php
  lib/private/DB/MigrationService.php
  lib/public/Migration/BigIntMigration.php
  tests/lib/DB/OCPostgreSqlPlatformTest.php
Labels: 2. developing, pending documentation, technical debt

#21657 Check if debugMode is defined before using it
  core/templates/exception.php
Labels: 3. to review, backport-request, bug, enhancement

#21590 Remove unused method.
  apps/workflowengine/lib/Service/RuleMatcher.php
Labels: 3. to review, technical debt

#21580 Add audio formats to htaccess
  lib/private/Setup.php
Labels: 3. to review, enhancement, pending documentation

#21547 Migrate WFE to the new bootstrap mechanism
  apps/workflowengine/appinfo/app.php
  apps/workflowengine/composer/composer/autoload_classmap.php
  apps/workflowengine/composer/composer/autoload_static.php
  apps/workflowengine/lib/AppInfo/Application.php
  apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php
Labels: 3. to review, enhancement

#21360 prevent the root storage from accidentally scanning user folders
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/LocalRootScanner.php
  lib/private/Files/Storage/LocalRootStorage.php
  lib/private/legacy/OC_Util.php
  tests/lib/Files/Cache/LocalRootScannerTest.php
Labels: 3. to review

#21591 Pass $path to ocmPermissions2ncPermissions
  apps/files_sharing/lib/External/Storage.php
Labels: 3. to review, technical debt

#21644 Fix typo in variable name and make check more accurate
  build/image-optimization.sh
Labels: 3. to review, bug, technical debt

#21431 Filter out search results that have invalid encoding
  core/Controller/SearchController.php
Labels: 3. to review

#21439 Move AutoComplete::filterResults to new event dispatcher and GenericE…
  core/Controller/AutoCompleteController.php
  lib/public/Collaboration/AutoComplete/AutoCompleteEvent.php
  tests/Core/Controller/AutoCompleteControllerTest.php
Labels: 4. to release, enhancement, pending documentation, technical debt

#20198 Send coverage to codecov again
  .drone.yml
Labels: 3. to review, enhancement, technical debt

#21662 Fix static method call for s3 bucket compat check
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 4. to release, backport-request, bug, feature: object storage

#21587 [stable17] Fix federated link sharing permissions
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialoglinkshareview.js
Labels: 3. to review, bug, feature: sharing

#21533 Techdebt/noid/dedicated method to get a users language
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/AbstractProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  apps/settings/lib/Hooks.php
  apps/settings/lib/Mailer/NewUserMailHelper.php
  lib/private/L10N/Factory.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/public/L10N/IFactory.php
Labels: 4. to release, feature: language l10n and translations, pending documentation

#21626 Callable parameter injection
  apps/accessibility/lib/AppInfo/Application.php
  apps/admin_audit/lib/AppInfo/Application.php
  apps/dav/lib/AppInfo/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/BootContext.php
  lib/private/AppFramework/Bootstrap/FunctionInjector.php
  lib/public/AppFramework/Bootstrap/IBootContext.php
  tests/lib/AppFramework/Bootstrap/FunctionInjectorTest.php
  tests/lib/AppFramework/Utility/SimpleContainerTest.php
Labels: 3. to review, enhancement, pending documentation

#21636 add proper paths to locking exceptions
  lib/private/Files/Storage/Common.php
  lib/private/Lock/DBLockingProvider.php
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/Lock/NoopLockingProvider.php
  lib/public/Lock/ILockingProvider.php
  lib/public/Lock/LockedException.php
Labels: 3. to review

#21264 build: Fix some typos (most of them found by codespell)
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  build/integration/features/bootstrap/CommandLineContext.php
  build/integration/features/external-storage.feature
  build/integration/features/transfer-ownership.feature
  build/integration/features/webdav-related.feature
Labels: 3. to review, technical debt

#21692 Cleanup share by mail a bit
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/services/ConfigService.js
  apps/sharebymail/appinfo/app.php
  apps/sharebymail/composer/composer/autoload_classmap.php
  apps/sharebymail/composer/composer/autoload_static.php
  apps/sharebymail/lib/AppInfo/Application.php
  apps/sharebymail/lib/Capabilities.php
  apps/sharebymail/lib/Settings.php
  apps/sharebymail/lib/Settings/SettingsManager.php
Labels: 4. to release, feature: sharing, technical debt

#21669 Revert "[stable17] Do not read certificate bundle from data dir by de…
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 3. to review

#21670 Revert "[stable18] Do not read certificate bundle from data dir by default"
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 3. to review

#21671 Revert "[stable19] Do not read certificate bundle from data dir by default"
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 3. to review

#21665 Fix wrong phpdoc for execute method
  lib/private/BackgroundJob/Job.php
  lib/private/BackgroundJob/TimedJob.php
  lib/public/BackgroundJob/IJob.php
Labels: 4. to release, technical debt

#18895 Changes the Birthday calendar color to slightly brighter one
  apps/dav/lib/CalDAV/BirthdayService.php
Labels: 3. to review, backport-request, feature: dav

#21238 Allow notification apps to defer and flush the sending
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Notification/Manager.php
  lib/public/Notification/IDeferrableApp.php
  lib/public/Notification/IManager.php
Labels: 3. to review, enhancement, feature: activity and notification, technical debt

#21222 Reduce contacts search load
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: 3. to review, bug, feature: dav

#21171 tidy up Group_LDAP
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: 3. to review, enhancement, feature: ldap, technical debt

#21074 Fix releasing a shared lock multiple times
  apps/dav/lib/Connector/Sabre/LockPlugin.php
  lib/private/Lock/MemcacheLockingProvider.php
Labels: 3. to review, bug

#21704 Fix unit tests from #18895
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
Labels: 3. to review, backport-request

#21713 Deprecate registerRoutes
  lib/public/AppFramework/App.php
Labels: 4. to release, technical debt

#21706 Add a clear message why you could end up there
  core/templates/loginflow/authpicker.php
  core/templates/loginflowv2/authpicker.php
Labels: 4. to release, bug, feature: authentication, security

#20729 Tags.php and the old sharing mechanism
  lib/private/Share/Share.php
  lib/private/TagManager.php
  lib/private/Tags.php
  lib/public/ITagManager.php
  tests/lib/TagsTest.php
Labels: 4. to release, technical debt

#21717 Fix sharebymail tests
  apps/sharebymail/tests/CapabilitiesTest.php
  apps/sharebymail/tests/SettingsTest.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
Labels: 3. to review

#18867 Update SecurityMiddleware.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
Labels: 4. to release, bug

#21714 Remove old deprecated getAppFolder
  lib/private/Server.php
  lib/public/IServerContainer.php
Labels: 3. to review, technical debt

#21639 Move away from database xml
  apps/federatedfilesharing/appinfo/database.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federatedfilesharing/composer/composer/autoload_classmap.php
  apps/federatedfilesharing/composer/composer/autoload_static.php
  apps/federatedfilesharing/lib/Migration/Version1010Date20200630191755.php
  apps/federation/appinfo/database.xml
  apps/federation/appinfo/info.xml
  apps/federation/composer/composer/autoload_classmap.php
  apps/federation/composer/composer/autoload_static.php
  apps/federation/lib/Migration/Version1010Date20200630191302.php
  apps/files_external/appinfo/database.xml
  apps/files_external/appinfo/info.xml
  apps/files_external/lib/Migration/Version1011Date20200630192246.php
  apps/files_trashbin/appinfo/database.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_trashbin/composer/composer/autoload_classmap.php
  apps/files_trashbin/composer/composer/autoload_static.php
  apps/files_trashbin/lib/Migration/Version1010Date20200630192639.php
  apps/user_ldap/appinfo/database.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Migration/Version1010Date20200630192842.php
Labels: 3. to review, feature: install and update, pending documentation, technical debt

#21460 Move systemtags to the new bootstrap mechanism
  apps/systemtags/appinfo/app.php
  apps/systemtags/composer/composer/autoload_classmap.php
  apps/systemtags/composer/composer/autoload_static.php
  apps/systemtags/lib/AppInfo/Application.php
Labels: 3. to review, enhancement

#21725 Fix main bundle on IE11
  apps/accessibility/js/accessibility.js
  apps/comments/js/comments.js
  apps/files/js/dist/files-app-settings.js
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/sidebar.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/collaboration.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/main.js
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_trashbin/js/files_trashbin.js
  apps/files_versions/js/files_versions.js
  apps/oauth2/js/oauth2.js
  apps/settings/js/vue-0.js
  apps/settings/js/vue-5.js
  apps/settings/js/vue-6.js
  apps/settings/js/vue-7.js
  apps/settings/js/vue-8.js
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/systemtags/js/systemtags.js
  apps/twofactor_backupcodes/js/settings.js
  apps/updatenotification/js/updatenotification.js
  apps/workflowengine/js/workflowengine.js
  core/js/dist/files_client.js
  core/js/dist/files_fileinfo.js
  core/js/dist/files_iedavclient.js
  core/js/dist/install.js
  core/js/dist/login.js
  core/js/dist/main.js
  core/js/dist/maintenance.js
  core/js/dist/recommendedapps.js
  core/js/dist/systemtags.js
  webpack.prod.js
Labels: 3. to review, bug

#21676 Fix chmod on file descriptor
  lib/private/Log/File.php
Labels: 3. to review, feature: logging, php

#21498 fix #21285 as oneliner
  lib/private/Authentication/LoginCredentials/Store.php
  tests/lib/Authentication/LoginCredentials/StoreTest.php
Labels: 3. to review, feature: authentication, feature: ldap

#21739 Remove hook for initSession
  lib/base.php
Labels: 3. to review, technical debt

#21741 Fix type for $urlGenerator
  apps/settings/lib/Controller/HelpController.php
Labels: 3. to review, technical debt

#21643 Do not create a RouteActionHandler object for each route
  lib/private/AppFramework/Routing/RouteConfig.php
  lib/private/Route/Router.php
  tests/lib/AppFramework/Routing/RoutingTest.php
Labels: 2. developing, enhancement, technical debt

#21749 Move contactsinteraction and comments to bootstrap mechanism
  apps/comments/appinfo/app.php
  apps/contactsinteraction/appinfo/app.php
  apps/contactsinteraction/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21499 fix #21285 as oneliner
  lib/private/Authentication/LoginCredentials/Store.php
  tests/lib/Authentication/LoginCredentials/StoreTest.php
Labels: 4. to release

#21745 Move lookup server connector to bootstrap mechanism
  apps/lookup_server_connector/appinfo/app.php
  apps/lookup_server_connector/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21729 Add removal of mounts without storages to files:cleanup command
  apps/files/lib/Command/DeleteOrphanedFiles.php
  apps/files/tests/Command/DeleteOrphanedFilesTest.php
Labels: 3. to review, enhancement

#21754 Only translate if we need the string
  lib/private/legacy/OC_Util.php
Labels: 3. to review, enhancement, technical debt

#21758 Fix supporting defaults for routes
  lib/private/AppFramework/Routing/RouteConfig.php
  tests/lib/AppFramework/Routing/RoutingTest.php
Labels: 2. developing, bug

#21761 Kill another unneeded translation
  lib/private/legacy/OC_Util.php
Labels: 3. to review, enhancement, technical debt

#21766 Fix regression in return value of OC_Util::checkDataDirectoryPermissi…
  lib/private/legacy/OC_Util.php
Labels: 4. to release, regression

#21746 Move cloud_federation_api to bootstrap mechanism
  apps/cloud_federation_api/appinfo/app.php
  apps/cloud_federation_api/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21767 Lazy register the navigation
  apps/files/lib/AppInfo/Application.php
  apps/files_sharing/lib/AppInfo/Application.php
Labels: 4. to release, enhancement

#21489 Use the correct mountpoint to calculate
  apps/files_sharing/tests/EtagPropagationTest.php
  apps/files_sharing/tests/TestCase.php
  build/integration/sharing_features/sharing-v1-part2.feature
  lib/private/Files/Filesystem.php
  lib/private/Files/Mount/LocalHomeMountProvider.php
  lib/private/Files/Mount/MountPoint.php
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
  tests/lib/TestCase.php
  tests/lib/Traits/MountProviderTrait.php
Labels: 3. to review, feature: sharing

#21733 Update system addressbook card only when there was a change based on a cached etag
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: 4. to release, performance 🚀

#21759 Make the subscription registry lazy
  lib/private/Support/Subscription/Registry.php
  lib/public/Support/Subscription/IRegistry.php
  tests/lib/Support/Subscription/DummySubscription.php
  tests/lib/Support/Subscription/RegistryTest.php
Labels: 3. to review, enhancement

#21778 Set the moment locale even earlier
  core/js/dist/main.js
  core/src/init.js
Labels: 3. to review, backport-request, bug

#21750 Move files_versions to bootstrap mechanism
  apps/files_versions/appinfo/app.php
  apps/files_versions/lib/AppInfo/Application.php
  apps/files_versions/tests/VersioningTest.php
Labels: 3. to review, technical debt

#21771 Clarify the scopes for profile data federation
  apps/settings/js/federationscopemenu.js
Labels: 3. to review, bug, feature: federation

#21777 lower minimum search length to 2 characters
  apps/files/js/search.js
  core/search/js/searchprovider.js
Labels: 3. to review

#21701 17.0.8 RC1
  apps/accessibility/composer/composer/autoload_real.php
  apps/admin_audit/composer/composer/autoload_real.php
  apps/cloud_federation_api/composer/composer/autoload_real.php
  apps/comments/composer/composer/autoload_real.php
  apps/dav/composer/composer/autoload_real.php
  apps/encryption/composer/composer/autoload_real.php
  apps/federatedfilesharing/composer/composer/autoload_real.php
  apps/federation/composer/composer/autoload_real.php
  apps/files/composer/composer/autoload_real.php
  apps/files_sharing/composer/composer/autoload_real.php
  apps/files_trashbin/composer/composer/autoload_real.php
  apps/files_versions/composer/composer/autoload_real.php
  apps/lookup_server_connector/composer/composer/autoload_real.php
  apps/oauth2/composer/composer/autoload_real.php
  apps/provisioning_api/composer/composer/autoload_real.php
  apps/sharebymail/composer/composer/autoload_real.php
  apps/systemtags/composer/composer/autoload_real.php
  apps/testing/composer/composer/autoload_real.php
  apps/twofactor_backupcodes/composer/composer/autoload_real.php
  apps/updatenotification/composer/composer/autoload_real.php
  apps/user_ldap/composer/composer/autoload_real.php
  apps/workflowengine/composer/composer/autoload_real.php
  lib/composer/composer/autoload_real.php
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#21700 18.0.7 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#21699 19.0.1 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#21760 Fix parsing of language code
  core/js/dist/login.js
  core/js/dist/main.js
  core/src/OC/l10n.js
Labels: 4. to release, bug

#21730 Up the limit for the header app menu
  core/js/dist/main.js
  core/src/init.js
Labels: 3. to review, design, enhancement

#21789 filter files containing a hash in the path for ftp storages
  apps/files_external/lib/Lib/Storage/FTP.php
  lib/private/Files/Storage/Common.php
Labels: 3. to review

#21800 Call openssl_pkey_export with $config and log errors.
  core/Service/LoginFlowV2Service.php
Labels: 3. to review, backport-request, bug

#21748 Improve error reporting on sharing errors
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/collaboration.js.map
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/main.js.map
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/mixins/ShareRequests.js
Labels: 3. to review, backport-request, bug, feature: sharing

#21785 Move OC_Mount_Config to proper classname and remove OC::$CLASSPATH us…
  apps/files_external/appinfo/app.php
  apps/files_external/appinfo/routes.php
  apps/files_external/js/settings.js
  apps/files_external/lib/Command/Verify.php
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Controller/ApiController.php
  apps/files_external/lib/Controller/StoragesController.php
  apps/files_external/lib/Lib/Backend/LegacyBackend.php
  apps/files_external/lib/MountConfig.php
  apps/files_external/lib/Service/GlobalStoragesService.php
  apps/files_external/lib/Service/LegacyStoragesService.php
  apps/files_external/lib/Service/UserLegacyStoragesService.php
  apps/files_external/lib/Service/UserStoragesService.php
  apps/files_external/lib/Settings/Admin.php
  apps/files_external/lib/Settings/Personal.php
  apps/files_external/tests/Controller/StoragesControllerTest.php
  apps/files_external/tests/Service/GlobalStoragesServiceTest.php
  apps/files_external/tests/Service/StoragesServiceTest.php
  apps/files_external/tests/Service/UserStoragesServiceTest.php
  apps/files_external/tests/Settings/AdminTest.php
  lib/private/Encryption/File.php
  lib/private/Encryption/Util.php
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review, technical debt

#21819 Use IBootstrap for the app updatenotification
  apps/updatenotification/appinfo/app.php
  apps/updatenotification/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21820 Do not use custom DI object names for user_ldap
  apps/user_ldap/appinfo/app.php
  apps/user_ldap/appinfo/register_command.php
  apps/user_ldap/lib/Command/Search.php
  apps/user_ldap/lib/Helper.php
  apps/user_ldap/lib/Jobs/CleanUp.php
  apps/user_ldap/lib/Jobs/UpdateGroups.php
  apps/user_ldap/lib/Migration/UUIDFixGroup.php
  apps/user_ldap/lib/Migration/UUIDFixUser.php
  apps/user_ldap/tests/Integration/AbstractIntegrationTest.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestAttributeDetection.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestFetchUsersByLoginName.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestPaging.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserAvatar.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserCleanUp.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserDisplayName.php
Labels: 3. to review, feature: ldap, technical debt

#21813 Report php-cs-fixer errors to GitHub
  .github/workflows/lint.yml
Labels: 3. to review, enhancement

#21357 Add Editing for Link Share Labels
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
Labels: 4. to release, enhancement

#21824 Use IBootstrap for the app user_ldap
  apps/user_ldap/appinfo/app.php
  apps/user_ldap/lib/AppInfo/Application.php
Labels: 3. to review, feature: ldap, technical debt

#21827 Make the PSR-3 adapter exception-aware
  lib/private/Log/PsrLoggerAdapter.php
Labels: 4. to release, enhancement, technical debt

#21828 Delegate bootstrap registration lazily
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Search/SearchComposer.php
  tests/lib/AppFramework/Bootstrap/CoordinatorTest.php
Labels: 4. to release, enhancement, technical debt

#21833 Fix PHPDoc of IRequest::getHeader
  lib/private/AppFramework/Http/Request.php
Labels: 3. to review

#21812 Do not load app.php if Application implements IBootstrap
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/legacy/OC_App.php
Labels: 4. to release, enhancement

#21825 Fix AppFramework services
  apps/settings/lib/Settings/Personal/Security/Authtokens.php
  apps/settings/tests/Settings/Personal/Security/AuthtokensTest.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
Labels: 4. to release

#21816 Use IBootstrap for the app federatedfilesharing
  apps/dav/appinfo/v1/publicwebdav.php
  apps/federatedfilesharing/appinfo/app.php
  apps/federatedfilesharing/composer/composer/autoload_classmap.php
  apps/federatedfilesharing/composer/composer/autoload_static.php
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/Listeners/LoadAdditionalScriptsListener.php
  apps/files_sharing/lib/ShareBackend/File.php
  apps/provisioning_api/composer/composer/autoload_classmap.php
  apps/provisioning_api/composer/composer/autoload_static.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/lib/FederatedShareProviderFactory.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  apps/settings/lib/Controller/UsersController.php
  apps/settings/lib/Settings/Personal/PersonalInfo.php
Labels: 3. to review, technical debt

#21838 Do not log RequestedRangeNotSatisfiable exceptions in DAV
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
Labels: 4. to release, backport-request, enhancement, feature: dav

#21839 Move since check to checkers
  autotest-checkers.sh
  autotest.sh
Labels: 4. to release, enhancement

#21346 Dashboard API
  .gitignore
  apps/dashboard/appinfo/info.xml
  apps/dashboard/appinfo/routes.php
  apps/dashboard/img/dashboard.svg
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/lib/Controller/DashboardController.php
  apps/dashboard/src/App.vue
  apps/dashboard/src/main.js
  apps/dashboard/templates/index.php
  apps/dashboard/webpack.js
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Dashboard/Manager.php
  lib/private/Server.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/Dashboard/IDashboardManager.php
  lib/public/Dashboard/IDashboardWidget.php
  lib/public/Dashboard/IManager.php
  lib/public/Dashboard/IPanel.php
  lib/public/Dashboard/Model/IWidgetConfig.php
  lib/public/Dashboard/Model/IWidgetRequest.php
  lib/public/Dashboard/Model/WidgetSetting.php
  lib/public/Dashboard/Model/WidgetSetup.php
  lib/public/Dashboard/Model/WidgetTemplate.php
  lib/public/Dashboard/RegisterPanelEvent.php
  lib/public/Dashboard/Service/IEventsService.php
  lib/public/Dashboard/Service/IWidgetsService.php
  tests/lib/AppFramework/Bootstrap/CoordinatorTest.php
  webpack.common.js
Labels: 3. to review, enhancement

#21720 provide feedback about minimum length needed to trigger search
  apps/files/js/filelist.js
Labels: 4. to release

#21849 Fix integration test due to new dashboard app
  build/integration/features/provisioning-v1.feature
Labels: 4. to release, regression

#21848 Deprecate the internal Symfony dispatcher adapter
  lib/private/EventDispatcher/EventDispatcher.php
  lib/private/EventDispatcher/SymfonyAdapter.php
Labels: 3. to review, technical debt

#21837 Run cs:check a second time to show diff
  .github/workflows/lint.yml
Labels: 3. to review, enhancement

#21728 Reuse cache for directory mtime/size if filesystem changes can be ignored
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 4. to release, bug

#21844 Avoid substr() error when strpos returns false
  lib/private/Files/Type/Detection.php
Labels: 3. to review, bug

#21843 Make translation-checker.php less verbose
  build/translation-checker.php
Labels: 4. to release, enhancement, technical debt

#21822 Add real events to load additionalscripts
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
  lib/public/AppFramework/Http/Events/BeforeTemplateRenderedEvent.php
  lib/public/AppFramework/Http/TemplateResponse.php
  tests/lib/AppFramework/Middleware/AdditionalScriptsMiddlewareTest.php
Labels: 3. to review, enhancement, pending documentation

#21815 Add LoadAdditionalScriptsEvent for files_sharing
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/lib/Event/BeforeTemplateRenderedEvent.php
  apps/files_sharing/lib/Listener/LegacyBeforeTemplateRenderedListener.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
Labels: 4. to release, enhancement, pending documentation, technical debt

#21803 17.0.8 final
  version.php
Labels: 2. developing, overview

#21802 18.0.7 final
  version.php
Labels: 2. developing, overview

#21853 Better event description for BeforeTemplateRenderedEvent in files and files_sharing
  apps/files_sharing/lib/Event/BeforeTemplateRenderedEvent.php
  lib/public/AppFramework/Http/Events/BeforeTemplateRenderedEvent.php
Labels: 3. to review

#21801 19.0.1 final
  version.php
Labels: 2. developing, overview

#21863 Clean up container usage in files trashbin
  apps/files_trashbin/lib/AppInfo/Application.php
Labels: 4. to release

#21855 fix typo in revokeShare()
  apps/federatedfilesharing/lib/FederatedShareProvider.php
Labels: 4. to release, bug

#21874 Add a scoped PSR logger for apps
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/ScopedPsrLogger.php
Labels: 3. to review, enhancement

#21873 Deprecate the server container getters
  lib/private/Server.php
  lib/public/IServerContainer.php
Labels: 3. to review, pending documentation, technical debt

#21869 Add constants for the magic strings of template rendering
  lib/private/TemplateLayout.php
  lib/private/legacy/OC_Template.php
  lib/public/AppFramework/Http/TemplateResponse.php
Labels: 3. to review, papercut, technical debt

#21859 Migrate DAV to the PSR container
  apps/dav/lib/AppInfo/Application.php
Labels: 3. to review, enhancement, technical debt

#21889 Make magic strings of ClientFlowLogin and v2 publicly available
  core/Controller/ClientFlowLoginController.php
  core/Controller/ClientFlowLoginV2Controller.php
Labels: 3. to review, technical debt

#21887 Deprecate the query mothod on the server container
  lib/private/ServerContainer.php
Labels: 4. to release, technical debt

#21891 Undeprecate IAppContainer and IServerContainer
  lib/public/AppFramework/IAppContainer.php
  lib/public/IServerContainer.php
Labels: 3. to review, bug, technical debt

#21880 Discourage webauthn user interaction
  lib/private/Authentication/WebAuthn/Manager.php
Labels: 3. to review, enhancement

#21916 Remove outdated ui-regression tests
  tests/ui-regression/config.js
  tests/ui-regression/helper.js
  tests/ui-regression/out/index.html
  tests/ui-regression/package.json
  tests/ui-regression/runTests.js
  tests/ui-regression/test/appsSpec.js
  tests/ui-regression/test/filesSpec.js
  tests/ui-regression/test/installSpec.js
  tests/ui-regression/test/loginSpec.js
  tests/ui-regression/test/publicSpec.js
  tests/ui-regression/test/settingsSpec.js
Labels: 3. to review

#21850 Allow to register AlternativeLogin on RegistrationContext
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/legacy/OC_App.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/Authentication/IAlternativeLogin.php
Labels: 3. to review, feature: authentication, technical debt

#21866 Migrate LDAP to the PSR container
  apps/user_ldap/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21862 Migrate files sharing to the PSR container
  apps/files_sharing/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21875 Deprecate ILogger in favor of the PSR-3 logger
  apps/contactsinteraction/lib/Listeners/ContactInteractionListener.php
  lib/private/AppFramework/Logger.php
  lib/public/ILogger.php
Labels: 3. to review, pending documentation, technical debt

#21865 Migrate settigns to the PSR container
  apps/settings/lib/AppInfo/Application.php
Labels: 4. to release, technical debt

#21864 Migrate files versions to the PSR container
  apps/files_versions/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21929 Encryption is ready if master key is enabled
  apps/encryption/lib/Crypto/Encryption.php
Labels: 3. to review, backport-request, bug, feature: encryption (server-side)

#21934 Disable fragile comments tests
  .drone.yml
Labels: 3. to review, backport-request, feature: comments

#21941 Move Cantarell before Ubuntu in font stack to fix GNOME + Ubuntu setups
  core/css/variables.scss
Labels: 3. to review, design, enhancement

#21658 allow admin to configure the max trashbin size
  apps/files_trashbin/appinfo/info.xml
  apps/files_trashbin/composer/composer/autoload_classmap.php
  apps/files_trashbin/composer/composer/autoload_static.php
  apps/files_trashbin/lib/Command/Size.php
  apps/files_trashbin/lib/Trashbin.php
  lib/private/Server.php
Labels: 3. to review

#21948 Load accessibilityoca script
  apps/accessibility/lib/AppInfo/Application.php
Labels: 3. to review, bug, feature: accessibility

#21870 Make the bootstrap context return ContainerInterface instances
  apps/admin_audit/lib/AppInfo/Application.php
  apps/comments/lib/AppInfo/Application.php
  apps/comments/lib/JSSettingsHelper.php
  apps/comments/tests/Unit/JSSettingsHelperTest.php
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/files/lib/AppInfo/Application.php
  apps/lookup_server_connector/lib/AppInfo/Application.php
  apps/settings/lib/AppInfo/Application.php
  apps/systemtags/lib/AppInfo/Application.php
  apps/twofactor_backupcodes/lib/AppInfo/Application.php
  apps/updatenotification/lib/AppInfo/Application.php
  apps/user_ldap/lib/AppInfo/Application.php
  apps/workflowengine/lib/AppInfo/Application.php
  lib/private/AppFramework/Bootstrap/BootContext.php
  lib/private/AppFramework/Bootstrap/FunctionInjector.php
  lib/public/AppFramework/Bootstrap/IBootContext.php
  tests/lib/AppFramework/Bootstrap/BootContextTest.php
Labels: 4. to release, technical debt

#21950 Properly fetch translation for remote wipe confirmation dialog
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/AuthTokenSection.vue
Labels: 4. to release, backport-request, bug, feature: language l10n and translations, feature: settings

#21949 update icewind/smb to 3.2.6
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_psr4.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/composer.json
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php
Labels: 3. to review

#21946 Do not double encode the userid in webauthn login
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/PasswordLessLoginForm.vue
Labels: 4. to release, bug, feature: authentication

#21957 Use IBootstrap for the testing app
  apps/testing/appinfo/app.php
  apps/testing/lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#21963 Respect default share permissions
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingInput.vue
Labels: 4. to release, backport-request, bug, feature: sharing, regression

#21966 Allow user backends to specify a custom logout url
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/legacy/OC_User.php
  lib/public/User/Backend/ICustomLogout.php
Labels: 3. to review, enhancement

#21970 Bump @nextcloud/vue from 2.2.1 to 2.3.0
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-8.js
  apps/settings/js/vue-8.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  package-lock.json
  package.json
Labels: 4. to release

#21973 Fix risky test in twofactor_backupcodes
  apps/twofactor_backupcodes/tests/Db/BackupCodeMapperTest.php
Labels: 4. to release, technical debt

#21747 Fix header logo size in notification mails
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email-single-button.html
  tests/data/emails/new-account-email.html
Labels: 4. to release, enhancement

#21628 fix moving files from external storage to object store trashbin
  apps/files_trashbin/lib/Trashbin.php
  lib/private/Files/Cache/Updater.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Local.php
  tests/lib/Files/ViewTest.php
Labels: 2. developing, feature: external storage, feature: object storage, feature: trashbin

#21972 Fix PHPUnit deprecation warnings
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/Command/ListCalendarsTest.php
  apps/dav/tests/unit/Command/MoveCalendarTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  tests/Core/Command/TwoFactorAuth/CleanupTest.php
  tests/Core/Command/TwoFactorAuth/DisableTest.php
  tests/Core/Command/TwoFactorAuth/EnableTest.php
  tests/Core/Command/TwoFactorAuth/EnforceTest.php
  tests/Core/Command/TwoFactorAuth/StateTest.php
  tests/lib/AppFramework/Http/DownloadResponseTest.php
  tests/lib/ConfigTest.php
  tests/lib/DB/DBSchemaTest.php
  tests/lib/L10N/FactoryTest.php
  tests/lib/Template/CSSResourceLocatorTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/ResourceLocatorTest.php
Labels: 4. to release, technical debt

#21814 Move federated_share_added into a typed event
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php
  apps/dav/lib/Events/SabrePluginAuthInitEvent.php
  apps/federatedfilesharing/composer/composer/autoload_classmap.php
  apps/federatedfilesharing/composer/composer/autoload_static.php
  apps/federatedfilesharing/lib/Events/FederatedShareAddedEvent.php
  apps/federatedfilesharing/lib/Notifications.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  apps/federatedfilesharing/tests/NotificationsTest.php
  apps/federation/appinfo/app.php
  apps/federation/composer/composer/autoload_classmap.php
  apps/federation/composer/composer/autoload_static.php
  apps/federation/lib/AppInfo/Application.php
  apps/federation/lib/Listeners/FederatedShareAddedListener.php
  apps/federation/lib/Listeners/SabrePluginAuthInitListener.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/lib/Hooks.php
  apps/files_sharing/tests/External/ManagerTest.php
  lib/private/Share20/ProviderFactory.php
Labels: 3. to review, pending documentation, technical debt

#21940 Revert "Disable fragile tests for now" partially
  tests/acceptance/features/login.feature
  tests/acceptance/features/users.feature
Labels: 3. to review, technical debt

#21987 Move NotFoundResponse to a proper TemplateResponse
  lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
  lib/public/AppFramework/Http/NotFoundResponse.php
Labels: 3. to review, technical debt

#21818 Use IBootstrap for the app theming
  apps/theming/appinfo/app.php
  apps/theming/lib/AppInfo/Application.php
  apps/theming/lib/Listener/BeforeTemplateRenderedListener.php
Labels: 3. to review, technical debt

#21988 Combine body-login rules in theming and fix twofactor and guest styling on bright colors
  apps/theming/css/theming.scss
Labels: 3. to review, bug, feature: theming

#21977 Ignore whitespace in sharing by mail
  lib/private/Collaboration/Collaborators/Search.php
Labels: 3. to review, bug

#22027 Fix overwriteService() for apps
  lib/private/ServerContainer.php
  tests/lib/TestCase.php
Labels: 3. to review, bug, regression, technical debt

#22035 [stable18] Properly fetch translation for remote wipe confirmation dialog
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/AuthTokenSection.vue
Labels: 3. to review, bug, feature: language l10n and translations

#22038 When no user is logged in null is used
  apps/files_sharing/lib/External/Manager.php
Labels: 3. to review, bug, feature: sharing

#22036 [stable19] Properly fetch translation for remote wipe confirmation dialog
  apps/settings/src/components/AuthTokenSection.vue
Labels: 3. to review, bug, feature: language l10n and translations

#22017 Fix PSR-4 compatible namespace
  apps/federation/composer/composer/autoload_classmap.php
  apps/federation/composer/composer/autoload_static.php
  apps/federation/lib/Listener/FederatedShareAddedListener.php
  apps/federation/lib/Listener/SabrePluginAuthInitListener.php
Labels: 3. to review, technical debt

#21542 basic settings system for activity notifications
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Activity/ActivitySettingsAdapter.php
  lib/private/Activity/Event.php
  lib/private/Activity/Manager.php
  lib/private/AppFramework/App.php
  lib/public/Activity/ActivitySettings.php
  lib/public/Activity/IEvent.php
  lib/public/Activity/IExtension.php
  lib/public/Activity/IManager.php
Labels: 3. to review

#22034 parse_url returns null in case a parameter is not found
  lib/private/Http/Client/Client.php
Labels: 3. to review, bug

#22015 Correctly remove usergroup shares on removing group members
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Share20/Hooks.php
  lib/private/Share20/UserRemovedListener.php
Labels: 3. to review, bug, feature: sharing, feature: users and groups

#21993 Log the route not found exception on a lower level
  lib/private/Route/Router.php
Labels: 3. to review, enhancement

#22058 [stable18] Fix PHPUnit deprecation warnings
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/Command/ListCalendarsTest.php
  apps/dav/tests/unit/Command/MoveCalendarTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  tests/Core/Command/TwoFactorAuth/CleanupTest.php
  tests/Core/Command/TwoFactorAuth/DisableTest.php
  tests/Core/Command/TwoFactorAuth/EnableTest.php
  tests/Core/Command/TwoFactorAuth/EnforceTest.php
  tests/Core/Command/TwoFactorAuth/StateTest.php
  tests/lib/AppFramework/Http/DownloadResponseTest.php
  tests/lib/ConfigTest.php
  tests/lib/DB/DBSchemaTest.php
  tests/lib/L10N/FactoryTest.php
  tests/lib/Template/CSSResourceLocatorTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/ResourceLocatorTest.php
Labels: 3. to review, backport-request, technical debt

#22005 Fix height to big for iPhone when using many apps
  core/css/header.scss
Labels: 4. to release, backport-request, bug, design

#22061 fix instanceof ISettings check for activity settings
  lib/private/Activity/Manager.php
Labels: 3. to review
