Repository nextcloud/server, pull requests merged in 2020-03, with the labels that each got.

#19722 Don't try to resize a svg uploaded as background image
  apps/theming/lib/Controller/ThemingController.php
Labels: 3. to review, bug

#19699 Allow single file downloads so the video player works again
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 4. to release, backport-request, bug, feature: sharing

#19702 [stable18] Revive the "send email to new users" toggle for the user form
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/appinfo/routes.php
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/lib/Controller/UsersController.php
  apps/settings/src/views/Users.vue
Labels: 4. to release, enhancement, regression

#19731 Don't try to format deleted shares
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review, bug, feature: sharing

#19742 Add message for DoesNotExistException
  lib/private/Updater/ChangesCheck.php
  tests/lib/Updater/ChangesCheckTest.php
Labels: 3. to review, backport-request, bug

#19755 Fetch translate for Tags from files app
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/views/Sidebar.vue
Labels: 3. to review, backport-request, bug

#19723 Always use status 200 for avatar response
  core/Controller/AvatarController.php
  tests/Core/Controller/AvatarControllerTest.php
Labels: 3. to review, enhancement

#19762 Fetch translate for Tags from files app
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/views/Sidebar.vue
Labels: 3. to review, bug

#19764 Do not allow transfer ownership when the user isn't the owner
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/lib/Controller/TransferOwnershipController.php
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 4. to release, feature: files, feature: users and groups

#19739 Do not use replace on the group id
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/views/Users.vue
Labels: 4. to release, bug

#19768 [stable17] Keep edit permission when toggling share checkbox
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogshareelistview.js
Labels: 3. to review, backport-request, bug, feature: sharing

#19588 [stable17] Move RefreshWebcalJob logic to a proper service so that it may be called independently
  apps/dav/appinfo/app.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/RefreshWebcalJob.php
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/tests/unit/BackgroundJob/RefreshWebcalJobTest.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/RefreshWebcalServiceTest.php
Labels: feature: dav

#19773 [stable18] Do not allow transfer ownership when the user isn't the owner
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/lib/Controller/TransferOwnershipController.php
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 3. to review, feature: files, feature: users and groups

#19767 [stable18] Various user settings fixes
  apps/settings/css/settings.scss
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 3. to review, bug, feature: users and groups

#19743 dont try to update storage mtime if we can't get the mtime
  lib/private/Files/Cache/Updater.php
Labels: 3. to review

#19787 Fix JS regex
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/src/Accessibility.vue
Labels: 4. to release, bug, feature: accessibility

#19703 [stable17] Revive the "send email to new users" toggle for the user form
  apps/provisioning_api/lib/Controller/UsersController.php
  settings/Controller/UsersController.php
  settings/js/vue-6.js
  settings/js/vue-6.js.map
  settings/js/vue-settings-apps-users-management.js
  settings/js/vue-settings-apps-users-management.js.map
  settings/routes.php
  settings/src/views/Users.vue
Labels: 2. developing

#18230 [stable16] respect shareapi_allow_share_dialog_user_enumeration in Principal bac…
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
Labels: 4. to release

#19734 16.0.9 RC1
  version.php
Labels: 3. to review

#19733 17.0.4 RC1
  version.php
Labels: 3. to review

#19732 18.0.2 RC1
  version.php
Labels: 3. to review

#19769 Fix avatar in file list for users with an @ in the uid
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/src/share.js
Labels: 4. to release, backport-request, bug, feature: sharing

#19671 Fix loading icons on replaced elements
  core/css/icons.scss
Labels: 4. to release, bug, design

#19721 Fix regex for office documents
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Checks/FileMimeType.vue
Labels: 4. to release, backport-request, bug

#19440 Fix filename and popover menu misalignment
  apps/files/css/files.scss
  apps/files/css/mobile.scss
Labels: 4. to release, backport-request, regression

#19763 Fix "Error loading the shares list TypeError: "this is undefined"" fo…
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/utils/SharedWithMe.js
Labels: 3. to review, backport-request, feature: sharing, javascript, regression

#19606 Added IPv6 example
  config/config.sample.php
Labels: 4. to release, enhancement

#19815 Prevent self-xss via invalid mysql user name on install screen
  core/templates/installation.php
Labels: 3. to review, backport-request, bug, feature: install and update

#19800 [stable18] Fix regex for office documents
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Checks/FileMimeType.vue
Labels: 4. to release, bug

#19797 [stable16] Keep edit permission when toggling share checkbox
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialogshareelistview.js
Labels: 4. to release, bug, feature: sharing

#19803 [stable18] Fix avatar in file list for users with an @ in the uid
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/src/share.js
Labels: 4. to release, bug, feature: sharing

#19824 [stable18] Fix "Error loading the shares list TypeError: "this is undefined"" fo…
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/utils/SharedWithMe.js
Labels: 3. to review, bug, feature: sharing

#19799 l10n: Fixed typo
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 3. to review

#19844 16.0.9 RC2
  version.php
Labels: 2. developing, overview

#19843 17.0.4 RC2
  version.php
Labels: 2. developing, overview

#19833 18.0.2 RC2
  version.php
Labels: 2. developing, overview

#19819 Fix mismatching doc block parameter types
  lib/private/AppFramework/OCS/BaseResponse.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  lib/private/DB/Migrator.php
  lib/private/DB/MySQLMigrator.php
  lib/private/Preview/GeneratorHelper.php
  lib/public/FullTextSearch/Model/IIndex.php
Labels: 3. to review, technical debt

#19795 Add address book plugins
  apps/dav/appinfo/v1/carddav.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/PluginManager.php
  apps/dav/lib/CardDAV/AddressBookRoot.php
  apps/dav/lib/CardDAV/Integration/ExternalAddressBook.php
  apps/dav/lib/CardDAV/Integration/IAddressBookProvider.php
  apps/dav/lib/CardDAV/UserAddressBooks.php
  apps/dav/lib/RootCollection.php
Labels: 3. to review, enhancement, feature: dav, integration

#19820 Fix mismatching docblock return types
  apps/files_versions/lib/Versions/IVersionBackend.php
  core/Migrations/Version16000Date20190212081545.php
  lib/private/AllConfig.php
  lib/private/Authentication/TwoFactorAuth/EnforcementState.php
  lib/private/Group/Database.php
  lib/private/User/Session.php
Labels: 3. to review, technical debt

#19746 pass the existing locks info when making locked exception with absolu…
  apps/dav/lib/Connector/Sabre/File.php
  lib/private/Files/View.php
  lib/public/Lock/LockedException.php
Labels: 3. to review

#19863 No tabs in translations
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/ResetPassword.vue
Labels: 4. to release, bug, feature: language l10n and translations, feature: sharing

#19704 Fix hostname in Apple configuration profile
  apps/dav/lib/Provisioning/Apple/AppleProvisioningPlugin.php
  apps/dav/tests/unit/Provisioning/Apple/AppleProvisioningPluginTest.php
Labels: 3. to review, bug

#19871 Combine move activities as well
  apps/files/lib/Activity/Provider.php
Labels: 3. to review, bug, feature: activity and notification

#19698 Fix default action for deleted shares
  apps/files/css/files.scss
  apps/files/js/filelist.js
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
Labels: 4. to release, bug

#18555 Allow to edit admin/own user in the user management
  apps/settings/css/settings.scss
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
  apps/settings/src/router.js
  apps/settings/src/views/Users.vue
Labels: 18-feedback, 4. to release, backport-request, bug, feature: users and groups, regression

#19862 Fix editor config for integration test files
  .editorconfig
Labels: 4. to release, technical debt

#19812 Add config flag for subscription and hide server development notice
  apps/settings/lib/Settings/Personal/ServerDevNotice.php
  apps/settings/tests/Controller/AdminSettingsControllerTest.php
  lib/private/Support/Subscription/Registry.php
  tests/lib/Support/Subscription/RegistryTest.php
Labels: 4. to release, enhancement

#19867 Set error_logging correctly. Fixes #19847
  lib/base.php
Labels: 4. to release, enhancement

#19580 Update check for outdated php version.
  apps/settings/lib/Controller/CheckSetupController.php
  core/js/setupchecks.js
Labels: 3. to review, technical debt

#19173 Use contacts name on federated activities
  apps/files/lib/Activity/Provider.php
  apps/files/tests/Activity/ProviderTest.php
  apps/files_sharing/lib/Activity/Providers/Base.php
  apps/files_sharing/lib/Activity/Providers/Groups.php
  apps/files_sharing/lib/Activity/Providers/RemoteShares.php
Labels: 3. to review, backport-request, bug, feature: activity and notification, feature: federation

#19861 Don't break when one remote share is down
  apps/files_sharing/lib/Controller/RemoteController.php
Labels: 3. to review, bug, feature: sharing

#19866 16.0.9
  version.php
Labels: 2. developing, overview

#19865 17.0.4
  version.php
Labels: 2. developing, overview

#19864 18.0.2
  version.php
Labels: 2. developing, overview

#19822 Faster implementation of sftp read and write stream
  apps/files_external/lib/Lib/Storage/SFTP.php
  apps/files_external/lib/Lib/Storage/SFTPReadStream.php
  apps/files_external/lib/Lib/Storage/SFTPWriteStream.php
Labels: 3. to review

#19777 Properly emit Viewer event on files and files_sharing
  apps/files/lib/Controller/ViewController.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/list.php
  apps/files_sharing/public.php
Labels: 18-feedback, 4. to release, backport-request, bug, feature: files, feature: sharing

#19587 Add guidelines for submitting issues
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: 3. to review, enhancement

#19882 [stable18] Allow to edit admin/own user in the user management
  apps/settings/css/settings.scss
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 3. to review, bug, feature: users and groups

#19902 Change Portalm to Portal
  .github/ISSUE_TEMPLATE/config.yml
Labels: 3. to review

#19899 Force compatible EventDispatcher version in integration tests
  build/integration/composer.json
Labels: 3. to review, bug, feature: dependencies, regression

#19888 Get correct mimetype on objectstores
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review, bug

#19914 Properly respect hide download on sharebymail
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
Labels: 3. to review, backport-request, bug

#19910 Do not use the instance name as user part of from mail addresses
  lib/private/Mail/Mailer.php
Labels: 3. to review, bug

#19915 Use placeholder values for password fields in external storage webui
  apps/files_external/lib/Controller/GlobalStoragesController.php
  apps/files_external/lib/Controller/StoragesController.php
  apps/files_external/lib/Controller/UserGlobalStoragesController.php
  apps/files_external/lib/Controller/UserStoragesController.php
  apps/files_external/lib/Lib/Auth/AuthMechanism.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/lib/Lib/FrontendDefinitionTrait.php
  apps/files_external/lib/Service/StoragesService.php
Labels: 3. to review

#19907 Don't allow anchors and queries in remote urls
  apps/files_sharing/lib/Controller/ExternalSharesController.php
  apps/files_sharing/tests/Controller/ExternalShareControllerTest.php
Labels: 4. to release, backport-request, bug, feature: sharing

#19931 fix external storage controller tests
  apps/files_external/tests/Controller/StoragesControllerTest.php
Labels: 3. to review, backport-request

#19937 properly set 'hide_download' as integer
  apps/sharebymail/lib/ShareByMailProvider.php
Labels: 3. to review, backport-request

#19954 fix safari useragent for versions with 3 digits
  lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php
Labels: 3. to review, backport-request, bug

#19968 Hide card for apps store if disabled
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/lib/Settings/ASettings.php
  apps/workflowengine/src/components/Workflow.vue
  apps/workflowengine/src/store.js
Labels: 4. to release, enhancement, feature: workflows

#19995 Default value of lookupServerEnabled should be the same everywhere
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
Labels: 3. to review, backport-request, bug, feature: federation

#19987 Only do regular polling of storage statistics if session_keepalive is enabled
  apps/files/js/files.js
Labels: 4. to release, backport-request, bug

#19982 [stable18] Fix default action for deleted shares
  apps/files/css/files.scss
  apps/files/js/filelist.js
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
Labels: 3. to review

#19989 Fix single "ScopeContext" passed to "setScopes"
  apps/workflowengine/lib/Service/RuleMatcher.php
Labels: 3. to review, backport-request, bug, feature: workflows

#19967 add docs for useJsNonce
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
Labels: 3. to review

#19347 Log untyped server DI requests
  apps/files_trashbin/tests/TrashbinTest.php
  apps/files_versions/tests/VersioningTest.php
  lib/private/Server.php
  tests/lib/User/UserTest.php
Labels: 3. to review, enhancement, pending documentation

#19964 Fix invalid instantiation of TemplateResponse if client not found
  apps/oauth2/lib/Controller/LoginRedirectorController.php
  apps/oauth2/tests/Controller/LoginRedirectorControllerTest.php
Labels: 3. to review, backport-request, bug

#19932 remove the requirement that everything that looks like a placeholder …
  apps/files_external/lib/config.php
  apps/files_external/tests/Config/PlaceholderSubstituteTest.php
Labels: 3. to review

#19813 Fix color-box-shadow variable
  apps/accessibility/css/dark.scss
  core/css/variables.scss
Labels: 4. to release, bug

#19981 Update the target when it isempty after sharing
  lib/private/Share20/Manager.php
Labels: 3. to review, backport-request, enhancement

#19978 Actually check if the owner is not null
  lib/private/Files/View.php
Labels: 3. to review, technical debt

#19983 [stable17] Fix default action for deleted shares
  apps/files/css/files.scss
  apps/files/js/filelist.js
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
Labels: 3. to review

#19984 [stable16] Fix default action for deleted shares
  apps/files/css/files.scss
  apps/files/js/filelist.js
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
Labels: 4. to release

#20003 Annotate $additionalScopes so the IDE knows what type $scopeCandidate is
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/lib/Service/RuleMatcher.php
Labels: 3. to review, enhancement

#19242 Handle long dav property paths by hashing them
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/DAV/CustomPropertiesBackend.php
  apps/dav/tests/unit/Connector/Sabre/CustomPropertiesBackendTest.php
  apps/dav/tests/unit/DAV/CustomPropertiesBackendTest.php
Labels: 3. to review

#20013 Fix recursive calls in logging via server methods
  apps/settings/tests/AppInfo/ApplicationTest.php
  lib/private/Authentication/Token/DefaultTokenProvider.php
  lib/private/Server.php
  tests/lib/AppTest.php
  tests/lib/User/UserTest.php
Labels: 3. to review, regression

#20026 Update autoloaders for composer v1.10.1
  apps/accessibility/composer/composer/autoload_real.php
  apps/admin_audit/composer/composer/autoload_real.php
  apps/cloud_federation_api/composer/composer/autoload_real.php
  apps/comments/composer/composer/autoload_real.php
  apps/dav/composer/composer/autoload_real.php
  apps/encryption/composer/composer/autoload_real.php
  apps/federatedfilesharing/composer/composer/autoload_real.php
  apps/federation/composer/composer/autoload_real.php
  apps/files/composer/composer/autoload_real.php
  apps/files_sharing/composer/composer/autoload_real.php
  apps/files_trashbin/composer/composer/autoload_real.php
  apps/files_versions/composer/composer/autoload_real.php
  apps/lookup_server_connector/composer/composer/autoload_real.php
  apps/oauth2/composer/composer/autoload_real.php
  apps/provisioning_api/composer/composer/autoload_real.php
  apps/settings/composer/composer/autoload_real.php
  apps/sharebymail/composer/composer/autoload_real.php
  apps/systemtags/composer/composer/autoload_real.php
  apps/testing/composer/composer/autoload_real.php
  apps/twofactor_backupcodes/composer/composer/autoload_real.php
  apps/updatenotification/composer/composer/autoload_real.php
  apps/user_ldap/composer/composer/autoload_real.php
  apps/workflowengine/composer/composer/autoload_real.php
  lib/composer/composer/autoload_real.php
Labels: 3. to review, technical debt

#20031 Do not use the deprecated service name
  apps/files_external/lib/AppInfo/Application.php
Labels: 4. to release, bug, technical debt

#19993 Make sure app_install_overwrite is an array
  apps/settings/lib/Controller/AppSettingsController.php
Labels: 3. to review, bug

#19971 Add visual feedback while creating 2fa backup codes
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/src/views/PersonalSettings.vue
Labels: 4. to release, bug, design

#20043 Most of us don't use IRC anymore
  .github/config.yml
Labels: 3. to review

#20039 fixes auto-detecting UUID attributes
  apps/user_ldap/lib/Access.php
Labels: 3. to review, backport-request, bug, feature: ldap, regression

#19569 Restrict sharing user enumeration to groups
  apps/dav/lib/CardDAV/SystemAddressbook.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/tests/Controller/ShareesAPIControllerTest.php
  apps/settings/js/admin.js
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/templates/settings/admin/sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  lib/private/Collaboration/Collaborators/GroupPlugin.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
  tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
Labels: 3. to review, enhancement, feature: sharing

#20049 Force compatible dependency versions in acceptance tests
  tests/acceptance/composer.json
Labels: 3. to review, backport-request, bug, feature: dependencies, regression

#20057 Adjust acceptance tests to incoming shares being accepted by default
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/app-files-sharing.feature
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/bootstrap/SettingsContext.php
Labels: 3. to review, backport-request, bug

#20058 l10n: Ignore compressed js
  apps/twofactor_backupcodes/.l10nignore
Labels: 3. to review, bug

#20055 [17] remove the requirement that everything that looks like a placeholder …
  apps/files_external/lib/config.php
  apps/files_external/tests/Config/PlaceholderSubstituteTest.php
Labels: 3. to review

#19930 Add app config to disable user flows
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/lib/Service/RuleMatcher.php
  apps/workflowengine/lib/Settings/ASettings.php
  apps/workflowengine/lib/Settings/Personal.php
  apps/workflowengine/tests/ManagerTest.php
Labels: 3. to review, bug, feature: workflows, pending documentation

#20042 fix dav browser error page not styled
  apps/dav/lib/Files/BrowserErrorPagePlugin.php
  apps/dav/templates/exception.php
Labels: 4. to release, bug, feature: dav

#20075 Remove unnecessary translation in systemtags
  core/js/dist/systemtags.js
  core/js/dist/systemtags.js.map
  core/js/systemtags/systemtags.js
Labels: 4. to release, bug, feature: language l10n and translations

#17684 Add support for GuzzleHTTP 'no' proxy
  config/config.sample.php
  lib/private/Http/Client/Client.php
  tests/lib/Http/Client/ClientTest.php
Labels: 4. to release, enhancement

#18679 fix OCA\DAV\CalDAV\CalDavBackend search $options
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 4. to release, backport-request, bug, feature: dav

#18556 Add OCA.Files.Settings for Files navigation settings
  apps/files/js/dist/files-app-settings.js
  apps/files/js/dist/files-app-settings.js.map
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/components/Setting.vue
  apps/files/src/files-app-settings.js
  apps/files/src/models/Setting.js
  apps/files/src/services/Settings.js
  apps/files/src/views/Settings.vue
  apps/files/templates/appnavigation.php
  apps/files/webpack.js
Labels: 4. to release, enhancement, feature: files

#20095 Remove legacy js packages
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/AuthTokenSection.vue
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  apps/settings/src/store/api.js
  apps/twofactor_backupcodes/js/settings.js
  apps/twofactor_backupcodes/js/settings.js.map
  apps/twofactor_backupcodes/src/views/PersonalSettings.vue
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Checks/MultiselectTag/api.js
  apps/workflowengine/src/store.js
  package-lock.json
  package.json
Labels: 3. to review

#17692 Add basic reverseproxy misconfig detection to setupchecks
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 4. to release, enhancement

#18818 change quota design
  apps/settings/css/settings.scss
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 4. to release, backport-request, bug, design

#20117 Close updatenotification channel selector on click outside
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/UpdateNotification.vue
Labels: 3. to review, backport-request, bug

#19965 Add text about subscribing issues and sync introduction to feature request
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: 3. to review, enhancement

#20019 Fix language multiselect action
  apps/settings/css/settings.scss
Labels: 4. to release, backport-request, bug

#20128 Remove admin_notifications since it is obsolete since Nextcloud 14
  lib/private/App/AppStore/Bundles/EducationBundle.php
  tests/lib/App/AppStore/Bundles/EducationBundleTest.php
Labels: 4. to release, backport-request, bug

#18788 Translate 'Busy' in CalDAV
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/CalendarObject.php
  apps/dav/lib/CalDAV/PublicCalendar.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
Labels: 3. to review, bug, feature: dav, feature: language l10n and translations

#20127 Check the user on remote wipe
  apps/settings/lib/Controller/AuthSettingsController.php
  apps/settings/tests/Controller/AuthSettingsControllerTest.php
  lib/private/Authentication/Token/RemoteWipe.php
  tests/lib/Authentication/Token/RemoteWipeTest.php
Labels: 4. to release, bug, feature: authentication, security

#20131 [stable17] Fix PDF and video viewers on public links
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 4. to release, backport-request, bug

#20034 [17] Handle long dav property paths by hashing them
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/DAV/CustomPropertiesBackend.php
  apps/dav/tests/unit/Connector/Sabre/CustomPropertiesBackendTest.php
  apps/dav/tests/unit/DAV/CustomPropertiesBackendTest.php
Labels: 3. to review

#19782 Use global used space in quota wrappen when external storage is included
  lib/private/Files/Storage/Wrapper/Quota.php
Labels: 3. to review, bug

#19955 Use a normal string to translate.
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/src/Accessibility.vue
Labels: 4. to release, backport-request, bug

#14722 Add Mailer events
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Mail/Mailer.php
  lib/private/Mail/Message.php
  lib/private/Server.php
  lib/public/Mail/Events/BeforeMessageSent.php
  tests/lib/Mail/MailerTest.php
  tests/lib/Mail/MessageTest.php
Labels: 4. to release, enhancement

#19986 RefreshWebcalService: randomly generate calendar-object uri
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/RefreshWebcalServiceTest.php
Labels: 4. to release, backport-request

#20144 [stable18] change quota design
  apps/settings/css/settings.scss
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 4. to release

#20145 Fix generated avatars and nophoto cache files
  apps/dav/lib/CardDAV/PhotoCache.php
  lib/private/Avatar/UserAvatar.php
Labels: 3. to review, bug, feature: filesystem, regression

#20150 Auto accept group shares for users added to a group
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Listener/UserAddedToGroupListener.php
Labels: 3. to review, backport-request, bug

#20162 Update minimist dependencies
  package-lock.json
Labels: 4. to release, feature: dependencies, security

#19075 Collect recent contact interactions
  .gitignore
  apps/contactsinteraction/appinfo/app.php
  apps/contactsinteraction/appinfo/info.xml
  apps/contactsinteraction/composer/autoload.php
  apps/contactsinteraction/composer/composer.json
  apps/contactsinteraction/composer/composer/ClassLoader.php
  apps/contactsinteraction/composer/composer/LICENSE
  apps/contactsinteraction/composer/composer/autoload_classmap.php
  apps/contactsinteraction/composer/composer/autoload_namespaces.php
  apps/contactsinteraction/composer/composer/autoload_psr4.php
  apps/contactsinteraction/composer/composer/autoload_real.php
  apps/contactsinteraction/composer/composer/autoload_static.php
  apps/contactsinteraction/lib/AddressBook.php
  apps/contactsinteraction/lib/AddressBookProvider.php
  apps/contactsinteraction/lib/AppInfo/Application.php
  apps/contactsinteraction/lib/BackgroundJob/CleanupJob.php
  apps/contactsinteraction/lib/Card.php
  apps/contactsinteraction/lib/Db/CardSearchDao.php
  apps/contactsinteraction/lib/Db/RecentContact.php
  apps/contactsinteraction/lib/Db/RecentContactMapper.php
  apps/contactsinteraction/lib/Listeners/ContactInteractionListener.php
  apps/contactsinteraction/lib/Migration/Version010000Date20200304152605.php
  apps/dav/lib/CardDAV/UserAddressBooks.php
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Listener/ShareInteractionListener.php
  core/Command/App/ListApps.php
  core/shipped.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Contacts/Events/ContactInteractedWithEvent.php
Labels: 4. to release, enhancement, integration, pending documentation

#20169 Use lowercase true, false and null constants
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  build/integration/features/bootstrap/Sharing.php
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Template/JSCombiner.php
  lib/private/legacy/util.php
  lib/public/Util.php
  tests/lib/Avatar/UserAvatarTest.php
  tests/lib/DB/LegacyDBTest.php
  tests/lib/Files/Stream/EncryptionTest.php
  tests/lib/Mail/MessageTest.php
  tests/lib/TagsTest.php
Labels: 3. to review, technical debt

#20123 Bugfix - Prevent PHP Warning for count on null on LDAP
  apps/user_ldap/lib/User/User.php
Labels: 4. to release, bug, feature: ldap

#20194 Bump version on stable17
  version.php
Labels: 4. to release

#20186 Fix "Use this address..." String
  apps/files/templates/appnavigation.php
Labels: 4. to release, enhancement

#20207 update icewind/smb to 3.2.1
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_real.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/.gitignore
  apps/files_external/3rdparty/icewind/smb/README.md
  apps/files_external/3rdparty/icewind/smb/composer.json
  apps/files_external/3rdparty/icewind/smb/src/ACL.php
  apps/files_external/3rdparty/icewind/smb/src/IFileInfo.php
  apps/files_external/3rdparty/icewind/smb/src/ISystem.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php
  apps/files_external/3rdparty/icewind/smb/src/System.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Connection.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/FileInfo.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Parser.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/RawConnection.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php
Labels: 4. to release

#20208 normalize smb path while listing folder contents
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#20227 Update the info.xsd for address book and calendar plugins
  resources/app-info-shipped.xsd
  resources/app-info.xsd
Labels: 4. to release, enhancement

#20234 Remove Acrobat logo from PDF filetype icon
  core/img/filetypes/application-pdf.svg
Labels: 3. to review, backport-request, bug, design

#20245 Add myself to .mailmap
  .mailmap
Labels: 3. to review

#20210 Remove outdated admin-dir_permissions documentation link
  lib/base.php
  lib/private/Config.php
  lib/private/legacy/util.php
Labels: 3. to review, backport-request, pending documentation

#19845 Event for failed login attempts
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Events/LoginFailed.php
  lib/private/Authentication/Listeners/LoginFailedListener.php
  lib/private/Authentication/Login/LoggedInCheckCommand.php
  lib/private/Server.php
  lib/private/User/Session.php
  lib/public/Authentication/Events/LoginFailedEvent.php
  tests/lib/Authentication/Login/LoggedInCheckCommandTest.php
Labels: 2. developing, enhancement
