Repository nextcloud/server, pull requests merged in 2020-09, with the labels that each got.

#16632 Set proper root path for single file shares originating from other storages
  apps/files_sharing/lib/SharedStorage.php
  lib/private/Files/Storage/Wrapper/Jail.php
Labels: 2. developing, bug

#22116 Fix share transfer of single files and on the transfered node
  apps/files/lib/Service/OwnershipTransferService.php
  lib/private/Files/Config/UserMountCache.php
  lib/public/Files/Config/IUserMountCache.php
Labels: 3. to review, bug

#22533 Flow: do not hide "matches" and "does not match" checkers
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Checks/file.js
Labels: 4. to release, feature: workflows, papercut

#22535 Only disable zip64 if the size is known
  lib/private/Streamer.php
Labels: 3. to review, backport-request, bug, feature: external storage

#22423 Do not expose direct editing if no master key is available
  apps/files/lib/Controller/DirectEditingController.php
  apps/files/lib/Service/DirectEditingService.php
  lib/private/DirectEditing/Manager.php
  lib/public/DirectEditing/IManager.php
  tests/lib/DirectEditing/ManagerTest.php
Labels: 4. to release, bug, feature: encryption (server-side)

#22528 Change free space calculation
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/tests/TrashbinTest.php
Labels: 3. to review, bug

#22557 Do not fail if share for mountpoint is no longer available
  apps/files_sharing/lib/External/Manager.php
Labels: 3. to review, backport-request, bug, feature: sharing

#22556 Do not keep the part file if the forbidden exception has no retry set
  apps/dav/lib/Connector/Sabre/File.php
Labels: 3. to review, bug

#22455 20 Beta3
  version.php
Labels: overview

#22524 Fix app password updating out of bounds
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Listeners/UserLoggedInListener.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/Server.php
Labels: 4. to release, bug

#21082 Show changelog in apps management
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-8.js
  apps/settings/js/vue-8.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/lib/Controller/AppSettingsController.php
  apps/settings/src/components/AppDetails.vue
  apps/settings/src/components/Markdown.vue
  apps/settings/src/views/Apps.vue
Labels: 4. to release, enhancement, feature: apps management

#22550 Use the correct root to determinate the webroot for the resource
  lib/private/Template/CSSResourceLocator.php
Labels: 3. to review, feature: caching, feature: scss

#22578 Upgrade icewind/smb to 3.2.7
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php
Labels: 4. to release, backport-request, bug, feature: external storage

#22573 Remove tooltip on customize button in dashboard
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/App.vue
Labels: 3. to review, bug, feature: dashboard

#22585 [stable18] Use the correct root to determinate the webroot for the resource
  lib/private/Template/CSSResourceLocator.php
Labels: 3. to review, bug

#22577 Better error message when blocked by access control
  apps/files/js/file-upload.js
Labels: 3. to review, bug, feature: files, feature: workflows

#22596 Build weather-status to solve design issues
  apps/weather_status/js/weather-status.js
  apps/weather_status/js/weather-status.js.map
  apps/weather_status/src/App.vue
Labels: 4. to release, design, feature: status, regression

#22543 Don't keep menu open for next user after deleting one
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
Labels: 4. to release, bug, feature: settings, feature: users and groups

#17456 iMIP email improvements (take 2)
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  core/img/caldav/attendees.svg
  core/img/caldav/description.svg
  core/img/caldav/link.svg
  core/img/caldav/location.svg
  core/img/caldav/organizer.svg
  core/img/caldav/time.svg
  core/img/caldav/title.svg
  lib/private/Mail/EMailTemplate.php
  lib/public/Mail/IEMailTemplate.php
  tests/data/emails/new-account-email-custom-text-alternative.txt
  tests/data/emails/new-account-email-custom.txt
  tests/data/emails/new-account-email.txt
Labels: 4. to release, design, feature: emails

#22575 18.0.9 RC1
  version.php
Labels: 2. developing, overview

#22574 19.0.3 RC1
  version.php
Labels: 2. developing, overview

#22597 Add missing alias for OCP\Settings\IManager and deprecate the old one
  lib/private/Server.php
Labels: 3. to review, technical debt

#22531 Fix dashboard statuses toggling
  apps/dashboard/lib/Controller/DashboardController.php
Labels: 4. to release, bug, feature: dashboard

#22583 LDAP: remove unused methods and DB values
  apps/user_ldap/appinfo/info.xml
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Migration/RemoveRefreshTime.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/User/UserTest.php
Labels: 4. to release, backport-request, bug, feature: ldap, technical debt

#21945 Changed Content-Disposition header to download Contact Photo with correct extension
  apps/dav/lib/CardDAV/ImageExportPlugin.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  build/integration/features/carddav.feature
Labels: 4. to release, bug, feature: dav

#22637 Fix weather status icon selector with nextcloud/vue update
  apps/weather_status/js/weather-status.js
  apps/weather_status/js/weather-status.js.map
  apps/weather_status/src/App.vue
Labels: 4. to release, bug, feature: dashboard

#22589 Allow additional personal settings via normal registration
  lib/private/Settings/Manager.php
Labels: 3. to review, bug, feature: settings

#22548 Improved status cleanup
  apps/user_status/appinfo/info.xml
  apps/user_status/composer/composer/autoload_classmap.php
  apps/user_status/composer/composer/autoload_static.php
  apps/user_status/lib/BackgroundJob/ClearOldStatusesBackgroundJob.php
  apps/user_status/lib/Connector/UserStatus.php
  apps/user_status/lib/Controller/HeartbeatController.php
  apps/user_status/lib/Controller/StatusesController.php
  apps/user_status/lib/Dashboard/UserStatusWidget.php
  apps/user_status/lib/Db/UserStatusMapper.php
  apps/user_status/lib/Listener/UserLiveStatusListener.php
  apps/user_status/lib/Migration/Version0002Date20200902144824.php
  apps/user_status/lib/Service/JSDataService.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/tests/Unit/BackgroundJob/ClearOldStatusesBackgroundJobTest.php
  apps/user_status/tests/Unit/Db/UserStatusMapperTest.php
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
  lib/public/UserStatus/IUserStatus.php
Labels: 4. to release

#22639 Move unified search to OCS api
  core/Controller/UnifiedSearchController.php
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/routes.php
  core/src/services/UnifiedSearchService.js
  core/src/views/UnifiedSearch.vue
Labels: 4. to release, client: 🤖🍏 mobile, feature: search, technical debt

#22644 Update license headers for Nextcloud 20 (again)
  AUTHORS
  apps/dav/lib/CalDAV/Activity/Setting/CalDAVSetting.php
  apps/dav/lib/CalDAV/Activity/Setting/Calendar.php
  apps/dav/lib/CalDAV/Activity/Setting/Event.php
  apps/dav/lib/CalDAV/Activity/Setting/Todo.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CardDAV/ImageExportPlugin.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  apps/files/lib/Service/OwnershipTransferService.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/tests/TrashbinTest.php
  apps/settings/appinfo/routes.php
  apps/settings/lib/Controller/ReasonsController.php
  apps/settings/lib/Settings/Personal/ServerDevNotice.php
  apps/settings/tests/Controller/AdminSettingsControllerTest.php
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  apps/user_ldap/lib/Migration/RemoveRefreshTime.php
  apps/user_ldap/tests/User/UserTest.php
  build/integration/features/bootstrap/FakeSMTPHelper.php
  lib/private/Authentication/Listeners/UserLoggedInListener.php
  lib/private/Authentication/LoginCredentials/Store.php
  lib/private/Files/Config/UserMountCache.php
  lib/private/Files/Filesystem.php
  lib/private/Mail/EMailTemplate.php
  lib/private/Server.php
  lib/private/User/Session.php
  lib/public/Files/Config/IUserMountCache.php
  lib/public/Mail/IEMailTemplate.php
  lib/public/User/Events/PostLoginEvent.php
Labels: 3. to review, technical debt

#22650 Only load viewer in settings if the viewer app is enabled
  apps/settings/lib/Settings/Personal/ServerDevNotice.php
Labels: 3. to review

#22643 Fix installing on Oracle
  core/Migrations/Version18000Date20190920085628.php
  lib/private/DB/MigrationService.php
Labels: 3. to review, backport-request, bug, feature: install and update

#22642 Move to automated dependabot merging
  .github/dependabot.yml
  .github/workflows/dependabot-approve-merge.yml
Labels: 4. to release, enhancement, feature: dependencies

#22712 Delete dependabot.yml
  .github/dependabot.yml
Labels: 3. to review, bug, feature: dependencies

#22469 Don't use SELECT DISTINCT when to_char() is used in a WHERE statement
  apps/workflowengine/lib/Manager.php
Labels: 4. to release, backport-request, bug, feature: install and update

#22638 Add icon for dashboard app store category
  core/css/icons.scss
  core/img/categories/dashboard.svg
Labels: 3. to review, bug, feature: dashboard

#22641 Fix undefined class property access after upgrade from 19 to 20
  lib/private/Authentication/LoginCredentials/Store.php
  tests/lib/Authentication/LoginCredentials/StoreTest.php
Labels: 20-feedback, 3. to review, bug, feature: authentication

#22647 fix use of removed escapeHTML in settings.js
  apps/settings/js/settings.js
Labels: 3. to review, bug

#22646 Fix detecting text/x-php mimetype and secure mimetype mapping
  lib/private/Files/Type/Detection.php
  resources/config/mimetypemapping.dist.json
Labels: 3. to review, bug

#22649 emit typed event for user management
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Controller/UsersController.php
  apps/settings/lib/Events/BeforeTemplateRenderedEvent.php
  apps/settings/tests/Controller/UsersControllerTest.php
Labels: 3. to review, bug, feature: users and groups

#22729 Run stat less often for objectstorages
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review, feature: object storage

#22636 Make sure that getConfig is still called for browsers that do not support CSPv3
  lib/private/TemplateLayout.php
Labels: 4. to release, backport-request, bug, regression

#22648 Transfer shares if no path provided
  apps/files/lib/Service/OwnershipTransferService.php
Labels: 4. to release, regression

#22725 19.0.3 final
  version.php
Labels: 2. developing, overview

#22726 18.0.9 final
  version.php
Labels: 2. developing, overview

#22714 [stable18] Do not fail if share for mountpoint is no longer available
  apps/files_sharing/lib/External/Manager.php
Labels: 3. to review, bug, feature: sharing

#22713 [stable19] Do not fail if share for mountpoint is no longer available
  apps/files_sharing/lib/External/Manager.php
Labels: 3. to review, bug, feature: sharing

#22564 The privacy setting is only about syncing to other servers
  core/Controller/AvatarController.php
  tests/Core/Controller/AvatarControllerTest.php
Labels: 4. to release, bug

#22657 Check if quota should be applied to path when creating directories
  lib/private/Files/Storage/Wrapper/Quota.php
  tests/lib/Files/Storage/Wrapper/QuotaTest.php
Labels: 3. to review, bug

#22587 Check if var debugMode exists
  core/templates/exception.php
Labels: 3. to review, bug

#22651 Fix reading empty files from objectstorage
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review, bug

#22520 dont use `false` as cache key for non utf8 path in normalizePath
  lib/private/Files/Filesystem.php
Labels: 4. to release, bug

#22614 Increase html body height to full content height
  core/css/styles.scss
Labels: 20-feedback, 4. to release, bug, feature: status

#22744 only get the permissions from the share source if it's not already cached
  apps/files_sharing/lib/Cache.php
Labels: 4. to release

#22762 Don't create a deprecation log in base.php
  lib/private/Server.php
Labels: 4. to release, bug, technical debt

#22765 Allow to get activities for files by email again
  apps/files/lib/Activity/Settings/FileChanged.php
Labels: 4. to release, bug, feature: activity and notification, regression

#22766 Clarify PHP warning in admin settings
  core/js/setupchecks.js
Labels: 4. to release, backport-request

#22747 fix s3 doesDirectoryExist check for empty directories
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review

#22773 Revert "Increase html body height to full content height"
  core/css/styles.scss
Labels: 3. to review, design, regression

#22739 Don't fail if copying a file of 0 byte size
  apps/dav/lib/Connector/Sabre/File.php
  lib/public/Files/Storage/IWriteStreamStorage.php
Labels: 4. to release, backport-request, bug

#22774 Don't break when the IP is empty
  lib/private/Security/Bruteforce/Throttler.php
  tests/lib/Security/Bruteforce/CapabilitiesTest.php
Labels: 4. to release, bug

#22234 Use user mount with matching shared storage only
  lib/private/Share20/Manager.php
Labels: 3. to review, backport-request, bug

#22780 Fix tense of updater logs
  core/Command/Upgrade.php
Labels: 3. to review

#22775 [stable19] makes LDAP's group updater dispatch type events
  apps/user_ldap/lib/Jobs/UpdateGroups.php
  lib/base.php
  lib/private/Share20/Hooks.php
Labels: 3. to review, bug, feature: ldap

#22781 [stable18] makes LDAP's group updater dispatch type events
  apps/user_ldap/lib/Jobs/UpdateGroups.php
  lib/base.php
  lib/private/Share20/Hooks.php
Labels: 3. to review, bug, feature: ldap

#22791 announce added user and group backend later as there might be interdeps
  apps/user_ldap/lib/AppInfo/Application.php
Labels: 3. to review, bug, feature: ldap

#22806 Fix serializing indexed unified search array as object
  lib/public/Search/SearchResult.php
Labels: 20-feedback, 3. to review, bug, feature: search

#22770 Mitigate encoding issue with user principal uri
  apps/dav/lib/Connector/Sabre/Principal.php
Labels: 4. to release

#22808 Dashboard: Add photo credits and background picture requirements to Readme
  apps/dashboard/README.md
Labels: 3. to review, enhancement, feature: dashboard

#22809 Remove unneeded isset check
  lib/private/AllConfig.php
Labels: 3. to review, technical debt

#22797 Fix files search provider
  apps/files/lib/Search/FilesSearchProvider.php
Labels: 4. to release, bug

#22799 Don't log Microsoft WebDAV client trying to tag things
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
Labels: 3. to review, bug, feature: tags

#22761 Extend integration tests for "files:transfer-ownership" command
  build/integration/features/transfer-ownership.feature
Labels: 3. to review, enhancement

#22852 Mention in the settings the side effect of outgoing federated shares
  apps/federatedfilesharing/templates/settings-admin.php
Labels: 4. to release, bug, feature: settings, pending documentation

#22854 Bugfix/noid/unified search
  apps/comments/lib/Search/CommentsSearchProvider.php
  apps/files/lib/Search/FilesSearchProvider.php
  core/Controller/UnifiedSearchController.php
Labels: 3. to review, enhancement, feature: search

#22858 Ignore bundled assets in l10n
  apps/dashboard/.l10nignore
  apps/user_status/.l10nignore
Labels: 3. to review, bug

#22857 It is very highly recommended to set an object for better filtering
  lib/public/Activity/IManager.php
Labels: 3. to review, bug, feature: activity and notification

#22860 Update .l10nignore for apps to exclude bundled JS files
  apps/accessibility/.l10nignore
  apps/comments/.l10nignore
  apps/files_trashbin/.l10nignore
  apps/files_versions/.l10nignore
  apps/oauth2/.l10nignore
  apps/settings/.l10nignore
  apps/theming/.l10nignore
  apps/twofactor_backupcodes/.l10nignore
  apps/weather_status/.l10nignore
  apps/workflowengine/.l10nignore
Labels: 3. to review, bug

#22859 Fix duplicate sentence in 'Reasons to use Nextcloud.pdf'
  apps/settings/data/Reasons to use Nextcloud.pdf
Labels: 3. to review, bug

#22866 Fix recommendation design details
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  core/src/components/setup/RecommendedApps.vue
Labels: 3. to review, bug, design, feature: recommended apps

#22865 Dashboard design detail fixing
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/App.vue
Labels: 3. to review, bug, design, feature: dashboard

#22883 Remove phan config - was replaced by Psalm
  .drone.yml
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/files_external/lib/Service/DBConfigService.php
  build/.phan/config.php
  build/.phan/plugin-checker.php
  build/.phan/plugins/SqlInjectionCheckerPlugin.php
  build/.phan/stubs/APCIterator.php
  build/.phan/stubs/APCUIterator.php
  build/.phan/stubs/apc.php
  build/.phan/stubs/apcu.php
  build/.phan/stubs/memcached.php
  build/.phan/stubs/xcache.php
  build/.phan/tests/SqlInjectionCheckerTest.php
  composer.json
  core/Command/Db/ConvertType.php
  core/Migrations/Version14000Date20180404140050.php
  lib/private/BackgroundJob/JobList.php
  lib/private/Comments/Manager.php
  lib/private/DB/Adapter.php
  lib/private/DB/AdapterPgSql.php
  lib/private/DB/Connection.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Propagator.php
  lib/private/Files/Config/UserMountCache.php
  lib/private/Lock/DBLockingProvider.php
  lib/private/Repair/CleanTags.php
  lib/private/Repair/OldGroupMembershipShares.php
  lib/private/Repair/RepairInvalidShares.php
  lib/private/Security/Bruteforce/Throttler.php
  lib/private/Setup/PostgreSQL.php
  lib/public/AppFramework/Db/QBMapper.php
Labels: 3. to review, technical debt

#22884 Specific version for @deprecated PHPDoc
  lib/private/Server.php
Labels: 4. to release

#22880 Revoke secsignid
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#22888 Remove not needed semicolon and PHPDoc hint
  apps/settings/lib/Controller/UsersController.php
  lib/private/Group/MetaData.php
Labels: 4. to release, technical debt

#22885 Show group display name in workflows
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Checks/RequestUserGroup.vue
Labels: 4. to release, bug, feature: workflows

#22874 l10n: Add parentheses
  apps/federatedfilesharing/templates/settings-admin.php
Labels: 3. to review, bug

#22890 Help static code analysis to understand code
  apps/admin_audit/lib/AppInfo/Application.php
  apps/settings/lib/Controller/ChangePasswordController.php
  apps/settings/lib/Controller/UsersController.php
  build/psalm-baseline.xml
  lib/private/Group/MetaData.php
Labels: 3. to review

#22867 Shared storage optimizations
  apps/files_sharing/lib/SharedStorage.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/NullWatcher.php
  lib/private/Files/View.php
Labels: 3. to review

#22902 Create proper target path for shared storage fopen event
  apps/files_sharing/lib/SharedStorage.php
Labels: 3. to review

#22903 Do not fetch the normalized full path again if it is already available
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3. to review, technical debt

#22898 Fix variable name and add spaces around path in info log line
  apps/files_sharing/lib/SharedStorage.php
  apps/files_trashbin/lib/Storage.php
Labels: 4. to release

#22844 Support architecture limitations for apps and allow richdocumentscode_arm64 though htaccess
  lib/private/App/AppStore/Bundles/HubBundle.php
  lib/private/App/DependencyAnalyzer.php
  lib/private/App/Platform.php
  lib/private/Setup.php
  resources/app-info.xsd
Labels: 3. to review, enhancement

#22920 l10n: Add a dot
  apps/settings/templates/settings/admin/server.php
Labels: 3. to review, bug

#22917 l10n: Add parentheses for unification
  apps/settings/templates/settings/admin/sharing.php
Labels: 3. to review, enhancement

#22910 add event to allow apps to overwrite user quota
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/User/User.php
  lib/public/User/GetQuotaEvent.php
Labels: 3. to review

#22919 Update urls to stackoverflow.com to "HTTPS"
  apps/dav/lib/Upload/AssemblyStream.php
  apps/workflowengine/lib/Check/RequestRemoteAddress.php
Labels: 3. to review, enhancement

#22794 20 RC1
  lib/public/User/GetQuotaEvent.php
  version.php
Labels: 3. to review, overview

#22843 Show filename on share link download
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
Labels: 4. to release, enhancement, feature: sharing

#22915 improve handling of out of space errors for smb
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 4. to release, backport-request, bug, feature: external storage

#22925 Dashboard: Fix accessibility skip links
  apps/dashboard/css/dashboard.scss
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/App.vue
Labels: 4. to release, backport-request, bug, design, feature: accessibility, feature: dashboard

#22767 Master is now Nextcloud 21 runs on PHP 7.3 to 8.0 only
  .drone.yml
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  lib/versioncheck.php
  version.php
Labels: 4. to release

#22911 Allow to run occ preview:repair in parallel
  core/Command/Preview/Repair.php
Labels: 3. to review, enhancement

#22924 Make sure most app names don’t ellipsize, fix #22845, fix #22219
  core/css/header.scss
Labels: 4. to release, backport-request, bug, design, papercut

#22964 l10n: Capital letter of the name of the app
  apps/weather_status/appinfo/info.xml
Labels: 3. to review, enhancement, feature: language l10n and translations

#22940 Never copy the share link when the password is forced
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
Labels: 3. to review, bug, feature: sharing

#23005 add size index for filecache
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review

#23008 Add padding to the empty content and center it
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/views/UnifiedSearch.vue
Labels: 3. to review, backport-request, bug, feature: language l10n and translations, feature: search

#23016 Don't log a known shared section
  lib/private/Settings/Manager.php
Labels: 4. to release, backport-request, bug, integration

#23014 Make 'Reasons to use Nextcloud' button translatable, fix #22977
  apps/settings/templates/settings/personal/development.notice.php
Labels: 3. to review, backport-request, bug, feature: settings

#23000 20 RC2
  version.php
Labels: overview

#23024 Add occ command to set theming values
  apps/theming/appinfo/info.xml
  apps/theming/lib/Command/UpdateConfig.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/ImageManager.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/ImageManagerTest.php
  lib/private/Server.php
Labels: 3. to review, feature: theming

#23023 Delete files that exceed trashbin size immediately
  apps/files_trashbin/lib/Trashbin.php
Labels: 3. to review, bug

#22948 Add more integration tests for "files:transfer-ownership" command
  build/integration/features/bootstrap/CommandLineContext.php
  build/integration/features/bootstrap/Provisioning.php
  build/integration/features/transfer-ownership.feature
Labels: 3. to review, backport-request

#23015 Log slow dashboard widgets
  lib/private/Dashboard/Manager.php
  lib/private/InitialStateService.php
Labels: 3. to review, backport-request, bug, feature: dashboard

#23033 Update autloader
  apps/accessibility/composer/composer/ClassLoader.php
  apps/admin_audit/composer/composer/ClassLoader.php
  apps/cloud_federation_api/composer/composer/ClassLoader.php
  apps/comments/composer/composer/ClassLoader.php
  apps/contactsinteraction/composer/composer/ClassLoader.php
  apps/dav/composer/composer/ClassLoader.php
  apps/encryption/composer/composer/ClassLoader.php
  apps/federatedfilesharing/composer/composer/ClassLoader.php
  apps/federation/composer/composer/ClassLoader.php
  apps/files/composer/composer/ClassLoader.php
  apps/files_sharing/composer/composer/ClassLoader.php
  apps/files_trashbin/composer/composer/ClassLoader.php
  apps/files_versions/composer/composer/ClassLoader.php
  apps/lookup_server_connector/composer/composer/ClassLoader.php
  apps/oauth2/composer/composer/ClassLoader.php
  apps/provisioning_api/composer/composer/ClassLoader.php
  apps/settings/composer/composer/ClassLoader.php
  apps/sharebymail/composer/composer/ClassLoader.php
  apps/systemtags/composer/composer/ClassLoader.php
  apps/testing/composer/composer/ClassLoader.php
  apps/twofactor_backupcodes/composer/composer/ClassLoader.php
  apps/updatenotification/composer/composer/ClassLoader.php
  apps/user_ldap/composer/composer/ClassLoader.php
  apps/user_status/composer/composer/ClassLoader.php
  apps/workflowengine/composer/composer/ClassLoader.php
  lib/composer/composer/ClassLoader.php
Labels: 3. to review

#23038 [stable20] Fix running video verification integration tests in Drone
  .drone.yml
Labels: 3. to review, bug

#23034 Fix numeric folders throwing on markDirty
  apps/dav/lib/Connector/Sabre/CachingTree.php
Labels: 3. to review, bug, feature: dav

#23051 Fix app text going too far down on hover/focus
  core/css/header.scss
Labels: 4. to release, backport-request, bug, design

#23012 Make BeforeTemplateRenderedEvent aware of the actual response
  apps/user_status/lib/Listener/BeforeTemplateRenderedListener.php
  lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
  lib/public/AppFramework/Http/Events/BeforeTemplateRenderedEvent.php
Labels: 3. to review, performance 🚀

#22904 [stable19] Make sure that getConfig is still called for browsers that do not support CSPv3
  lib/private/TemplateLayout.php
Labels: 3. to review

#22804 [stable19] Fix share transfer of single files and on the transfered node
  apps/files/lib/Service/OwnershipTransferService.php
  build/integration/features/bootstrap/CommandLineContext.php
  build/integration/features/bootstrap/Provisioning.php
  build/integration/features/transfer-ownership.feature
  lib/private/Files/Config/UserMountCache.php
  lib/public/Files/Config/IUserMountCache.php
Labels: 3. to review, bug

#22983 Sync all users to the system addresssbook
  apps/dav/lib/CardDAV/SyncService.php
Labels: 3. to review, backport-request, bug, feature: federation

#23013 Show federation and email results also with exact user match unless c…
  lib/private/Collaboration/Collaborators/Search.php
Labels: 3. to review, backport-request, bug, feature: federation, feature: sharing

#23074 Do not match sharees on an empty email address
  lib/private/Collaboration/Collaborators/UserPlugin.php
Labels: 3. to review, backport-request, bug, feature: sharing

#23083 Generate exception to log on php errors
  lib/private/Log/ErrorHandler.php
Labels: 4. to release, bug

#23043 Avoid crash when unauthenticated users make weather-related requests
  apps/weather_status/js/weather-status.js
  apps/weather_status/js/weather-status.js.map
  apps/weather_status/lib/Controller/WeatherStatusController.php
  apps/weather_status/lib/Service/WeatherStatusService.php
  apps/weather_status/src/App.vue
Labels: 3. to review, bug, feature: dashboard

#22999 Adjust scroll container height to make it a proper boundary element for actions
  apps/settings/css/settings.scss
Labels: 3. to review, backport-request, bug, design

#23108 Reset the user status when clearing the custom message
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/tests/Unit/Controller/UserStatusControllerTest.php
Labels: 3. to review, backport-request, bug, feature: status
