Repository nextcloud/server, pull requests merged in 2020-01, with the labels that each got.

#18615 Move scroll container to inner element
  core/css/header.scss
Labels: 3. to review, bug, design

#18628 Fix style of the sharing setting checkbox
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/components/PersonalSettings.vue
Labels: 18-feedback, 4. to release, bug, design

#18630 confirm resharing rights if viewer is current owner
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 4. to release, bug

#18612 Workflow validity checks
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/lib/AppInfo/Application.php
  apps/workflowengine/src/components/Check.vue
  apps/workflowengine/src/components/Checks/RequestTime.vue
  apps/workflowengine/src/components/Rule.vue
  apps/workflowengine/src/store.js
  apps/workflowengine/src/workflowengine.js
Labels: 4. to release, bug, feature: workflows

#18551 Re-open popover on link password save failure
  core/js/dist/share_backend.js
  core/js/dist/share_backend.js.map
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareview.js
Labels: 4. to release, bug, feature: sharing

#18583 Modify regex to match some other chromium browsers
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3. to review, enhancement

#18578 18 RC 1
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#18642 Settings: More spacing for development notice
  apps/settings/templates/settings/personal/development.notice.php
Labels: 4. to release, design, enhancement

#18641 Fix typo in occ
  core/Command/User/Setting.php
  tests/Core/Command/User/SettingTest.php
Labels: 4. to release, bug

#18674 Do not use $_GET
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/tests/Controller/ShareesAPIControllerTest.php
Labels: 4. to release, enhancement

#18660 [#18645] Have custom login images cover the whole page
  apps/theming/css/theming.scss
Labels: 3. to review, bug, feature: theming, regression

#18687 Fix the LoggerTests for phpunit
  tests/lib/LoggerTest.php
Labels: 3. to review, enhancement

#18675 Do not show e-mail suggestions if link shares are disabled
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/services/ConfigService.js
Labels: 4. to release, enhancement

#18672 Don't show link shares in sidebar if disabled
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/views/SharingLinkList.vue
Labels: 3. to review, enhancement, feature: sharing, javascript

#18473 fix overlapping
  apps/files/css/files.scss
Labels: 3. to review, design

#18696 Accept shares when you open mail
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Controller/AcceptController.php
  lib/private/Share20/Manager.php
Labels: 3. to review, bug, feature: sharing

#18692 fix wording log in vs. login
  core/templates/twofactorselectchallenge.php
  core/templates/twofactorsetupchallenge.php
  core/templates/twofactorsetupselection.php
  core/templates/twofactorshowchallenge.php
Labels: 4. to release, design, papercut, standardisation

#18535 Use the new Events in Flow
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/tests/ManagerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/WorkflowEngine/Events/RegisterChecksEvent.php
  lib/public/WorkflowEngine/Events/RegisterEntitiesEvent.php
  lib/public/WorkflowEngine/Events/RegisterOperationsEvent.php
  lib/public/WorkflowEngine/IManager.php
Labels: 3. to review, enhancement, feature: workflows

#18701 Show message if no other users with access are found
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/views/SharingInherited.vue
Labels: 3. to review, enhancement, feature: sharing

#18644 Only allow requesting new CSRF tokens if it passes the SameSite Cooki…
  core/Controller/CSRFTokenController.php
  tests/Core/Controller/CSRFTokenControllerTest.php
Labels: 3. to review, enhancement

#18576 enable option '--no-interaction' for db:convert-type
  core/Command/Db/ConvertType.php
Labels: 4. to release, enhancement

#18718 Only show others with access if you have reshare permissions
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/views/SharingTab.vue
Labels: 4. to release, bug, feature: sharing, papercut

#18707 A pending shares overview
  apps/files/css/files.scss
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/sharedfilelist.js
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 4. to release, enhancement, feature: sharing

#18724 Encode URI for file sidebar
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/views/Sidebar.vue
Labels: 4. to release, bug, feature: file sidebar

#17861 Fix tab navigation of menu in public share pages
  core/css/public.scss
  core/js/public/publicpage.js
  core/templates/layout.public.php
  lib/public/AppFramework/Http/Template/ExternalShareMenuAction.php
Labels: 3. to review, bug

#18728 Trash bin: fix exception triggered if no correct fileId is provided.
  apps/files_trashbin/lib/Controller/PreviewController.php
Labels: 4. to release, bug

#18713 remove non-circles-generated federated shares only
  apps/federatedfilesharing/lib/FederatedShareProvider.php
Labels: 4. to release, bug

#18736 Fix folder permission styling
  apps/files/css/files.scss
Labels: 4. to release, bug, design

#18739 [inherited shares] do not retrieve shares on current folder
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 4. to release, bug

#18733 Wrong email sender fix #18730
  apps/sharebymail/lib/ShareByMailProvider.php
Labels: 3. to review, bug, feature: sharing

#18740 cache group existence early to save useless requests to LDAP
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Group_LDAP.php
Labels: 3. to review, backport-request, bug, enhancement, feature: ldap

#18749 Use @nextcloud/paths for file sidebar
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/views/Sidebar.vue
Labels: 4. to release, bug, feature: file sidebar, high, regression

#18754 Make the transfer ownership input a bit wider
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 4. to release, design, feature: files, feature: users and groups

#18753 Do not rerender the selection menu on show
  apps/files/js/filemultiselectmenu.js
Labels: 4. to release, backport-request, bug, regression

#18726 [#18661] Always include custom login image in theming
  apps/theming/css/theming.scss
Labels: 4. to release, design, enhancement, feature: theming

#18639 18 RC 2
  version.php
Labels: 2. developing, overview

#18757 Combine exact and other matches for transfer ownership
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 4. to release, backport-request

#18738 Clean up 2FA provider registry when a user is deleted
  core/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Listeners/UserDeletedStoreCleanupListener.php
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
  lib/private/Authentication/TwoFactorAuth/Registry.php
  tests/lib/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDaoTest.php
  tests/lib/Authentication/TwoFactorAuth/RegistryTest.php
Labels: 3. to review, backport-request, bug, feature: authentication, feature: users and groups

#18766 Filter disabled operations out of the rule list
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Check.vue
  apps/workflowengine/src/components/Rule.vue
  apps/workflowengine/src/store.js
Labels: 3. to review, backport-request, bug, feature: workflows

#18773 Add more padding in transfer ownership
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 4. to release, backport-request, design, enhancement

#18774 make the mime type checker for flow available to regular users
  apps/workflowengine/lib/Check/FileMimeType.php
Labels: 4. to release, backport-request, bug, feature: workflows

#18777 Set direct login after password reset
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/views/Login.vue
Labels: 4. to release, backport-request, bug

#18780 Tell Safari to watch out for changes of filter
  core/css/apps.scss
Labels: 4. to release, backport-request, bug, design

#18787 Remove reference link for memcached options as domain doesn't exist anymore
  config/config.sample.php
Labels: enhancement

#18783 Init OCA.Files.Sidebar right away
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/sidebar.js
Labels: 4. to release, backport-request, feature: file sidebar

#18752 Fix contacts menu sizing
  core/css/styles.scss
Labels: 4. to release, bug, design

#18795 [stable18] Add more padding in transfer ownership
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 3. to review, design, enhancement

#18771 Fix sharing note placeholder
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/views/SharingLinkList.vue
Labels: 4. to release, backport-request, bug, feature: file sidebar, feature: sharing

#18804 Fix webdav url
  apps/files/lib/Controller/ViewController.php
  apps/files/templates/appnavigation.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: 4. to release, backport-request, bug, feature: dav, feature: files

#18817 Narrow error button styling scope
  core/css/inputs.scss
Labels: 4. to release, backport-request, bug, design, regression

#18806 Set the contactsmenu height without min calculation
  core/css/styles.scss
Labels: 4. to release, backport-request, bug

#18792 [stable17] Set direct login after password reset
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/views/Login.vue
Labels: 4. to release, bug

#18819 Limit the size of the container on guest pages
  core/css/guest.css
  core/templates/update.use-cli.php
Labels: 3. to review, backport-request, design, regression

#18786 AppFetcher: Distinguish between fileName and endpointName
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/AppStore/Fetcher/CategoryFetcher.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
  tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
Labels: 3. to review, backport-request

#18860 Fix license headers
  AUTHORS
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/AcceptController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_trashbin/lib/Controller/PreviewController.php
  apps/settings/lib/Controller/ChangePasswordController.php
  apps/settings/lib/Controller/UsersController.php
  apps/sharebymail/lib/ShareByMailProvider.php
  build/license.php
  core/Command/Db/ConvertType.php
  core/Command/User/Setting.php
  core/Controller/CSRFTokenController.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
  lib/private/Authentication/Listeners/UserDeletedStoreCleanupListener.php
  lib/private/Avatar/UserAvatar.php
  lib/private/DirectEditing/Manager.php
  lib/private/Preview/Movie.php
  lib/public/AppFramework/Http/Template/ExternalShareMenuAction.php
  lib/public/Lock/ManuallyLockedException.php
  lib/public/WorkflowEngine/Events/RegisterChecksEvent.php
  lib/public/WorkflowEngine/Events/RegisterEntitiesEvent.php
  lib/public/WorkflowEngine/Events/RegisterOperationsEvent.php
  lib/public/WorkflowEngine/IManager.php
Labels: 3. to review

#18805 Check if file already exists during file creation
  lib/private/DirectEditing/Manager.php
  tests/lib/DirectEditing/ManagerTest.php
Labels: 4. to release, backport-request, bug

#18862 Register with potentially updated namespace
  lib/private/legacy/app.php
Labels: 4. to release, backport-request, bug, feature: install and update

#18869 Create hover color variable
  core/css/variables.scss
Labels: 3. to review, backport-request

#17717 relax strict getHome behaviour for LDAP users in a shadow state
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/tests/Group_LDAPTest.php
  apps/user_ldap/tests/User_LDAPTest.php
Labels: 3. to review, backport-request, bug, enhancement, feature: ldap

#18859 Add "Password protected by Talk" option to shares
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/models/Share.js
Labels: 3. to review, backport-request, bug, feature: sharing

#18886 use `nodeExists` instead of catching exceptions
  lib/private/DirectEditing/Manager.php
  tests/lib/DirectEditing/ManagerTest.php
Labels: 4. to release

#18898 Fix max width on 2FA pages
  core/css/guest.css
  core/templates/twofactorselectchallenge.php
  core/templates/twofactorshowchallenge.php
Labels: 3. to review, backport-request, bug, design, feature: authentication

#18892 Proper text previews
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/views/Sidebar.vue
  lib/private/Preview/TXT.php
Labels: 4. to release, backport-request, bug

#18873 Install page design fixes
  core/css/guest.css
  core/js/setup.js
  core/templates/installation.php
Labels: 3. to review, backport-request, bug, feature: install and update, high

#18803 Only allow navigation to a folder if you have access
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryInherited.vue
Labels: 3. to review, backport-request, bug

#18799 Do not show link shares in inherited list
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/sharing_features/sharing-v1.feature
Labels: 4. to release, backport-request, feature: sharing

#18732 Sidebar polishing
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/filelist.js
  apps/files/src/views/Sidebar.vue
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/systemtags/js/systemtags.js
  apps/systemtags/js/systemtags.js.map
  apps/systemtags/src/css/systemtagsfilelist.scss
  apps/systemtags/src/filesplugin.js
  apps/systemtags/src/systemtags.js
  apps/systemtags/src/systemtagsinfoview.js
  apps/systemtags/src/systemtagsinfoviewtoggleview.js
  apps/systemtags/tests/js/systemtagsinfoviewtoggleviewSpec.js
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  package-lock.json
  package.json
Labels: 4. to release, backport-request, feature: file sidebar, feature: files, regression

#18909 [stable18] Add "Password protected by Talk" option to shares
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/models/Share.js
Labels: 3. to review, bug, feature: sharing

#18906 [stable18] Proper text previews
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/views/Sidebar.vue
  lib/private/Preview/TXT.php
Labels: 3. to review, bug

#18910 Listen to the right even for auto share accept
  apps/files_sharing/lib/Listener/UserShareAcceptanceListener.php
Labels: 3. to review, backport-request, bug, feature: sharing

#18894 Save sharing note on close or submit
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
Labels: 4. to release, backport-request, bug, feature: sharing

#18919 [stable18] Do not save on update, use submit
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
Labels: 3. to review

#18925 Add color background hover css variable
  core/css/css-variables.scss
Labels: 3. to review, backport-request

#18927 Fix Sidebar legacy FileInfoModel requirement
  apps/files/lib/Listener/LoadSidebarListener.php
Labels: 4. to release, backport-request, bug, feature: file sidebar, high

#18455 fix userlist alignment
  apps/settings/css/settings.scss
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
Labels: 3. to review, bug, design, help wanted

#18945 [stable18] Only allow navigation to a folder if you have access
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryInherited.vue
Labels: 3. to review

#18940 Make the share accept process optional
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Listener/GlobalShareAcceptanceListener.php
  apps/files_sharing/lib/Listener/UserShareAcceptanceListener.php
  apps/files_sharing/lib/Settings/Personal.php
  apps/files_sharing/src/components/PersonalSettings.vue
  config/config.sample.php
Labels: 3. to review, backport-request, bug

#18947 [stable18] fix userlist alignment
  apps/settings/css/settings.scss
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
Labels: 3. to review, bug

#18939 Fix cursor on disabled contenteditable divs
  core/css/inputs.scss
Labels: 4. to release, backport-request, bug

#18924 Make getServerHost more robust to faulty user input
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3. to review, bug

#19017 Increase the timeout for app downloads
  lib/private/Installer.php
Labels: 3. to review, feature: apps management

#19035 Adjust unit test for #19017
  tests/lib/InstallerTest.php
Labels: 3. to review, bug, feature: apps management

#18765 NC 19 development
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 4. to release

#19045 change .editorconfig to not add newline on SVGs
  .editorconfig
Labels: 4. to release

#19053 Fix loaded controller check
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
Labels: 4. to release, backport-request, bug

#19054 Use themed favicon-fb
  apps/theming/lib/ThemingDefaults.php
Labels: 4. to release, bug, feature: theming

#19041 mb substring in audit_log
  apps/admin_audit/lib/AppInfo/Application.php
Labels: 4. to release, bug

#19077 [stable16] when a user was deleted remove them from applicable list, unless...
  apps/files_external/appinfo/app.php
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Service/DBConfigService.php
Labels: 3. to review, bug, feature: external storage

#19076 [stable17] when a user was deleted remove them from applicable list, unless...
  apps/files_external/appinfo/app.php
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Service/DBConfigService.php
Labels: 3. to review, bug, feature: external storage

#19069 [stable17] Fix loaded controller check
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
Labels: 3. to review, bug

#19067 Bump @babel/preset-env from 7.7.7 to 7.8.3
  package-lock.json
  package.json
Labels: 4. to release, feature: dependencies, javascript

#18929 Allow to await the sidebar
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/services/Sidebar.js
  apps/files/src/sidebar.js
  apps/files/src/views/Sidebar.vue
Labels: 4. to release, enhancement, feature: file sidebar, medium

#19081 Bump @babel/plugin-proposal-class-properties from 7.7.4 to 7.8.3
  package-lock.json
  package.json
Labels: 3. to review

#19023 expose Argon2 options (as we did for bcrypt)
  config/config.sample.php
  lib/private/Security/Hasher.php
Labels: 3. to review, backport-request, bug, enhancement, pending documentation

#18440 [stable16] Bump nextcloud-vue-collections to 0.4.2
  apps/files_sharing/js/dist/files_sharing.3.js
  apps/files_sharing/js/dist/files_sharing.3.js.map
  package-lock.json
  package.json
Labels: 3. to review, bug

#19026 17.0.3 RC1
  version.php
Labels: 2. developing, 3. to review, overview

#19027 16.0.8 RC1
  version.php
Labels: 3. to review, overview

#18913 fix multiselect actions for files
  apps/files/css/files.scss
Labels: 3. to review, backport-request, bug, design

#19109 Adjust filelist color handling to new dark theme value
  apps/files/js/filelist.js
Labels: 3. to review, backport-request, bug, design

#19111 New file menu needs to be above the filelist header
  core/css/styles.scss
Labels: 4. to release, backport-request, bug, design

#19113 Do not invert avatar colors when dark theme is enabled
  apps/accessibility/css/dark.scss
Labels: 3. to review, backport-request

#19116 apps can have polyamorous relationships with bundles
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/lib/Controller/AppSettingsController.php
  apps/settings/src/components/AppList.vue
Labels: 3. to review, backport-request, bug, feature: apps management

#19120 Use correct appid for talk
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  core/src/components/setup/RecommendedApps.vue
Labels: 4. to release, bug

#19118 [stable18] Reduce legacy event log level to debug
  lib/private/EventDispatcher/SymfonyAdapter.php
Labels: 4. to release, feature: logging

#19115 Use the target for file notifications
  apps/files_sharing/lib/Notification/Notifier.php
Labels: 3. to review, backport-request, bug

#19105 add hub bundle for easy installation on upgraded instances
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/App/AppStore/Bundles/BundleFetcher.php
  lib/private/App/AppStore/Bundles/HubBundle.php
  tests/lib/App/AppStore/Bundles/BundleFetcherTest.php
Labels: 4. to release, backport-request, enhancement

#19150 [stable18] Use correct appid for talk
  core/js/dist/recommendedapps.js
  core/js/dist/recommendedapps.js.map
  core/src/components/setup/RecommendedApps.vue
Labels: 3. to review, bug

#18745 Change avatar placeholder from single letter to 2 letters
  lib/private/Avatar/Avatar.php
  tests/lib/Avatar/UserAvatarTest.php
Labels: 4. to release, enhancement

#19166 [stable18] apps can have polyamorous relationships with bundles
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/lib/Controller/AppSettingsController.php
  apps/settings/src/components/AppList.vue
Labels: 4. to release, bug, feature: apps management

#19167 Fix tests after #18745
  lib/private/Avatar/Avatar.php
Labels: 3. to review, bug

#19168 Move the Personal sections to the settings app
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Sections/Personal/PersonalInfo.php
  apps/settings/lib/Sections/Personal/Security.php
  apps/settings/lib/Sections/Personal/SyncClients.php
  lib/private/Settings/Manager.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, enhancement

#19159 [stable17] AppFetcher: Distinguish between fileName and endpointName
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/AppStore/Fetcher/CategoryFetcher.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
  tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
Labels: 3. to review

#19178 Make sure the default share provider does not execute for other things
  lib/private/Share20/DefaultShareProvider.php
Labels: 3. to review, bug, feature: sharing

#19174 Move admin sections to settings app
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Sections/Admin/Additional.php
  apps/settings/lib/Sections/Admin/Groupware.php
  apps/settings/lib/Sections/Admin/Overview.php
  apps/settings/lib/Sections/Admin/Security.php
  apps/settings/lib/Sections/Admin/Server.php
  apps/settings/lib/Sections/Admin/Sharing.php
  lib/private/Settings/Manager.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, enhancement

#19186 Fix "Call to undefined method OCA\\WorkflowEngine\\Entity\\File::t()"
  apps/workflowengine/lib/Entity/File.php
Labels: 4. to release, backport-request, bug, feature: workflows

#19029 Add link to help.nextcloud.com and bugbounty
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: 4. to release, enhancement

#19185 Move can create token logic
  apps/settings/lib/Settings/Personal/Security.php
  apps/settings/lib/Settings/Personal/Security/Authtokens.php
  apps/settings/tests/Settings/Personal/Security/AuthtokensTest.php
  apps/settings/tests/Settings/Personal/SecurityTest.php
Labels: 4. to release, enhancement

#19155 16.0.8
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#19154 17.0.3
  resources/config/ca-bundle.crt
  version.php
Labels: 2. developing, overview

#19188 [stable17] Use themed favicon-fb
  apps/theming/lib/ThemingDefaults.php
Labels: 3. to review, bug, feature: theming

#19179 Fix query selector for inverted icons
  apps/accessibility/css/dark.scss
Labels: 3. to review, backport-request, bug, feature: accessibility

#19125 Give the sharing tab a unique id so it also opens properly on other languages
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/filelist.js
  apps/files/src/components/LegacyTab.vue
  apps/files/src/models/Tab.js
  apps/files/src/services/Sidebar.js
  apps/files/src/views/Sidebar.vue
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/views/SharingTab.vue
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  package-lock.json
  package.json
Labels: 4. to release, backport-request, bug

#19192 Move the personal 2FA settings to its settings
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Settings/Personal/Security.php
  apps/settings/lib/Settings/Personal/Security/TwoFactor.php
  apps/settings/templates/settings/personal/security.php
  apps/settings/templates/settings/personal/security/twofactor.php
  apps/settings/tests/Settings/Personal/SecurityTest.php
Labels: 3. to review, enhancement

#19176 Do not encode contacts menu mailto links
  lib/private/Contacts/ContactsMenu/ActionFactory.php
  tests/lib/Contacts/ContactsMenu/ActionFactoryTest.php
Labels: 4. to release, backport-request, bug, feature: contacts menu

#19212 [stable18] Give the sharing tab a unique id so it also opens properly on other languages
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/filelist.js
  apps/files/src/components/LegacyTab.vue
  apps/files/src/models/Tab.js
  apps/files/src/services/Sidebar.js
  apps/files/src/views/Sidebar.vue
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/views/SharingTab.vue
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-3.js
  apps/settings/js/vue-3.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  package-lock.json
  package.json
Labels: 4. to release, bug, feature: file sidebar

#19217 Personal settings cleanup
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Settings/Personal/Additional.php
  apps/settings/lib/Settings/Personal/PersonalInfo.php
  apps/settings/lib/Settings/Personal/Security/Authtokens.php
  apps/settings/lib/Settings/Personal/Security/Password.php
  apps/settings/lib/Settings/Personal/ServerDevNotice.php
  apps/settings/templates/settings/personal/security/password.php
  apps/settings/tests/Controller/AdminSettingsControllerTest.php
  apps/settings/tests/Settings/Personal/Security/AuthtokensTest.php
  apps/settings/tests/Settings/Personal/Security/PasswordTest.php
  lib/private/Settings/Manager.php
  tests/lib/Settings/ManagerTest.php
Labels: 3. to review, enhancement, technical debt

#19215 WebcalRefreshJob: Fix reading refresh rate
  apps/dav/lib/BackgroundJob/RefreshWebcalJob.php
  apps/dav/tests/unit/BackgroundJob/RefreshWebcalJobTest.php
  lib/private/BackgroundJob/JobList.php
Labels: 3. to review, backport-request

#19240 Use activity registration for the settings
  apps/settings/appinfo/info.xml
  apps/settings/lib/AppInfo/Application.php
Labels: 4. to release, technical debt
