Repository nextcloud/server, pull requests merged in 2020-02, with the labels that each got.

#19243 Move Admin Settings also to info.xml
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Settings/Admin/Mail.php
  apps/settings/lib/Settings/Admin/Overview.php
  apps/settings/lib/Settings/Admin/Security.php
  apps/settings/lib/Settings/Admin/Server.php
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/tests/Settings/Admin/MailTest.php
  apps/settings/tests/Settings/Admin/SecurityTest.php
  apps/settings/tests/Settings/Admin/ServerTest.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  lib/private/Settings/Manager.php
  tests/lib/Settings/ManagerTest.php
Labels: 4. to release, technical debt

#19241 Make sure to catch php errors during job execution
  lib/private/BackgroundJob/Job.php
  tests/lib/BackgroundJob/JobTest.php
Labels: 3. to review, backport-request, bug

#19238 Center Buttons
  core/css/guest.css
Labels: 4. to release, bug

#19250 l10n: Changed spelling of "user name" to "username"
  apps/user_ldap/templates/settings.php
Labels: 4. to release, enhancement, feature: language l10n and translations

#19266 Move npm build to github actions
  .drone.yml
  .github/workflows/node.yml
Labels: 4. to release, enhancement

#19268 Use the l10n from settings
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
Labels: 4. to release, backport-request, bug

#19276 Use proper andwhere clause
  apps/federatedfilesharing/lib/FederatedShareProvider.php
Labels: 3. to review, backport-request, bug, feature: sharing

#19273 Bump @babel/core from 7.8.3 to 7.8.4
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  package-lock.json
  package.json
Labels: 3. to review, feature: dependencies

#19275 Bugfix/18626/owner transfer multiselect
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 3. to review, backport-request, bug

#19233 Add move (and firstlogin) option to transferownership service
  apps/files/lib/Command/TransferOwnership.php
  apps/files/lib/Service/OwnershipTransferService.php
Labels: 3. to review, enhancement

#19281 for the DB ot pick an index specify the object_type
  lib/private/Comments/Manager.php
Labels: 4. to release, backport-request, bug, feature: comments

#19286 Use checkout v2 for npm build action
  .github/workflows/node.yml
Labels: 4. to release, enhancement

#19291 [stable18] owner transfer multiselect fixes
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/components/TransferOwnershipDialogue.vue
Labels: 4. to release, bug, feature: files

#19203 Allow respecting PASSWORD_DEFAULT
  config/config.sample.php
  lib/private/Security/Hasher.php
  tests/lib/Security/HasherTest.php
Labels: 4. to release, backport-request, enhancement

#19246 Keep the modification time during decryptFile
  lib/private/Encryption/DecryptAll.php
Labels: 3. to review, bug, feature: encryption (server-side)

#19165 Fix data Apache2 .htaccess typo
  lib/private/Setup.php
Labels: 3. to review, backport-request, bug

#19180 Check for empty authorization headers for office requests
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/tests/unit/DAV/AnonymousOptionsTest.php
Labels: 3. to review, bug

#19219 Fix display of DTEND for multi-day all-day event
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
Labels: 3. to review, backport-request

#19089 [stable18] Allow to await the sidebar
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/services/Sidebar.js
  apps/files/src/sidebar.js
  apps/files/src/views/Sidebar.vue
Labels: 3. to review, enhancement, feature: file sidebar

#19267 18.0.1 RC1
  version.php
Labels: 3. to review, overview

#19312 do not overwrite global user auth credentials with empty values
  apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
Labels: 3. to review, bug, feature: external storage

#19303 Fix occ maintenance:install database connect failure
  core/Command/Maintenance/Install.php
  lib/private/Setup.php
  lib/private/Setup/MySQL.php
Labels: 4. to release, backport-request, bug, feature: install and update

#19320 Fix event type
  apps/files/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
Labels: 18-feedback, 3. to review, backport-request, bug, regression

#19236 Issue 18866
  apps/admin_audit/lib/AppInfo/Application.php
Labels: 3. to review, bug, feature: logging

#17075 Only send samesite cookies
  lib/private/Session/CryptoWrapper.php
  lib/private/Session/Internal.php
Labels: 3. to review, enhancement, security

#18518 Set up a security policy
  SECURITY.md
  apps/updatenotification/Makefile
  build/files-checker.php
Labels: 3. to review, enhancement

#18926 Array access on int will fail on php7.4
  lib/private/AppFramework/OCS/BaseResponse.php
  tests/lib/AppFramework/OCS/BaseResponseTest.php
Labels: 18-feedback, 3. to review, backport-request, bug

#17077 Disable link shares of disabled users
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
Labels: 3. to review, enhancement, feature: sharing

#19331 Removed nested call to beforeunload
  apps/files/js/filelist.js
Labels: 3. to review, bug, javascript

#18897 No more jQuery
  core/js/publicshareauth.js
Labels: 3. to review, bug, javascript, technical debt

#19342 18.0.1 RC2
  version.php
Labels: 2. developing, overview

#19356 Add webpack-based js tests
  .github/workflows/node.yml
  core/src/tests/OC/requesttoken.spec.js
  core/src/tests/setup.js
  core/webpack.test.js
  package-lock.json
  package.json
Labels: 4. to release, enhancement, javascript, technical debt

#19349 Prevent archieved download on secure view
  apps/files_sharing/lib/Controller/ShareController.php
Labels: 4. to release, backport-request, bug, feature: sharing, regression

#19333 Add featured category
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/AppList.vue
  apps/settings/src/views/Apps.vue
Labels: 3. to review, enhancement

#19387 Lets just use the fixup bot
  .github/workflows/fixup.yml
Labels: 3. to review, technical debt

#19384 Lint on github actions
  .drone.yml
  .github/workflows/lint.yml
  composer.json
Labels: 3. to review, enhancement

#19307 Add Argon2id support
  lib/private/Security/Hasher.php
  tests/lib/Security/HasherTest.php
Labels: 3. to review, enhancement, security

#18904 Log Flow activity
  apps/workflowengine/appinfo/info.xml
  apps/workflowengine/composer/composer/autoload_classmap.php
  apps/workflowengine/composer/composer/autoload_static.php
  apps/workflowengine/lib/AppInfo/Application.php
  apps/workflowengine/lib/BackgroundJobs/Rotate.php
  apps/workflowengine/lib/Helper/LogContext.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/lib/Service/Logger.php
  apps/workflowengine/lib/Service/RuleMatcher.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Log.php
  lib/private/Log/LogDetails.php
  lib/public/Log/IDataLogger.php
Labels: 3. to review, backport-request, enhancement, feature: workflows

#19397 18.0.1 RC3
  version.php
Labels: 2. developing, overview

#19417 Allow to serve static webm directly
  lib/private/Setup.php
Labels: 3. to review, backport-request

#19423 Allow to serve static mp4 directly
  lib/private/Setup.php
Labels: 4. to release, backport-request, bug

#19430 disable timeout on app install via cli
  lib/private/Installer.php
  lib/private/Server.php
  tests/lib/InstallerTest.php
Labels: 4. to release, backport-request, bug, feature: apps management, feature: occ

#19422 18.0.1 final
  version.php
Labels: 2. developing, overview

#19437 Do not use translation-concatenation
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/lib/AccessibilityProvider.php
  apps/accessibility/src/Accessibility.vue
  apps/accessibility/src/components/ItemPreview.vue
Labels: 3. to review, bug, feature: language l10n and translations

#19431 Show proper file name when fetching details fails
  apps/files/js/filelist.js
Labels: 3. to review, backport-request, bug

#19424 Don't create invalid users
  lib/private/Files/View.php
Labels: 3. to review, bug, feature: filesystem

#19435 Add text restore after restore icon
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
Labels: 4. to release, bug

#19449 Allow to overwrite the path on the cache event
  lib/private/Files/Cache/AbstractCacheEvent.php
  lib/public/Files/Cache/ICacheEvent.php
Labels: 3. to review, bug, feature: filesystem

#19459 Fix typo
  apps/settings/appinfo/info.xml
Labels: 3. to review, bug

#19460 Replace all link-ends
  apps/accessibility/js/accessibility.js
  apps/accessibility/js/accessibility.js.map
  apps/accessibility/src/Accessibility.vue
Labels: 3. to review

#19465 when we receive intentional empty whats new info, do not try to show it
  lib/private/Updater/ChangesCheck.php
  tests/lib/Updater/ChangesCheckTest.php
Labels: 4. to release, backport-request, enhancement

#19477 Reduce flow logging at INFO level, move to DEBUG
  apps/workflowengine/lib/Service/Logger.php
Labels: 4. to release, backport-request, bug

#19329 Warn admins about delayed cron executions
  apps/settings/lib/Settings/Admin/Server.php
  apps/settings/templates/settings/admin/server.php
  apps/settings/tests/Settings/Admin/ServerTest.php
Labels: 3. to review, enhancement, feature: settings

#19510 Continue with next foreach iteration
  apps/workflowengine/lib/Helper/LogContext.php
Labels: 3. to review, backport-request, bug

#19506 cron: Adapt to 5 minutes recommendation
  cron.php
Labels: 2. developing, bug

#19533 Various user settings fixes
  apps/settings/css/settings.scss
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
Labels: 3. to review, bug, feature: users and groups

#19398 Move RefreshWebcalJob logic to a proper service so that it may be called independently
  apps/dav/appinfo/app.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/RefreshWebcalJob.php
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/tests/unit/BackgroundJob/RefreshWebcalJobTest.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/RefreshWebcalServiceTest.php
Labels: 3. to review, backport-request, feature: dav

#19511 Make sure the secondary view registered for systemtags has an id
  apps/systemtags/js/systemtags.js
  apps/systemtags/js/systemtags.js.map
  apps/systemtags/src/systemtagsinfoview.js
Labels: 4. to release, backport-request, bug, feature: tags

#19392 Introduce a default refresh rate app setting for calendar subscriptions
  apps/dav/lib/BackgroundJob/RefreshWebcalJob.php
  apps/dav/tests/unit/BackgroundJob/RefreshWebcalJobTest.php
Labels: 3. to review, feature: dav

#19518 Use npm ci in Makefile
  Makefile
Labels: 4. to release, enhancement, javascript

#19517 Add a shortcut for Folders mimetype
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/src/components/Checks/FileMimeType.vue
Labels: 4. to release, enhancement, feature: workflows

#19412 Make TAG_FAVORITE public
  apps/files/lib/Service/TagService.php
  apps/files/tests/Service/TagServiceTest.php
  lib/private/Tags.php
  lib/public/ITags.php
Labels: 4. to release, enhancement

#18227 Add event subscriber for transaction isolation level
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/DB/Connection.php
  lib/private/DB/ConnectionFactory.php
  lib/private/DB/SetTransactionIsolationLevel.php
Labels: 4. to release, bug, technical debt

#19528 Strip of users home path from share api message
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, backport-request, bug, feature: sharing

#19566 FIx logging in accessibility controller
  apps/accessibility/lib/Controller/AccessibilityController.php
Labels: 3. to review

#19542 Show the link password when it's set
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
Labels: 4. to release, bug, feature: sharing

#19586 Replace tab character with space
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/src/components/AdminTwoFactor.vue
Labels: 3. to review, backport-request, bug

#19478 Change the route generation of AuthPublicShareController.php
  lib/public/AppFramework/AuthPublicShareController.php
Labels: 3. to review, bug

#19196 Allow apps to provide Calendars in user's calendarHome
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/PluginManager.php
  apps/dav/lib/CalDAV/CalendarHome.php
  apps/dav/lib/CalDAV/Integration/ExternalCalendar.php
  apps/dav/lib/CalDAV/Integration/ICalendarProvider.php
  apps/dav/tests/unit/AppInfo/PluginManagerTest.php
  apps/dav/tests/unit/CalDAV/CalendarHomeTest.php
  apps/dav/tests/unit/CalDAV/Integration/ExternalCalendarTest.php
Labels: 3. to review

#19612 Replace tab character with space
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/src/components/AdminTwoFactor.vue
Labels: 3. to review, bug

#19590 Move Compile Handlebars CI to GitHub Actions
  .drone.yml
  .github/workflows/node.yml
Labels: 4. to release, enhancement

#19578 Set content type for propfind request
  core/js/setupchecks.js
Labels: 3. to review, bug

#19313 l10n: Added plural form to string
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-1.js
  apps/settings/js/vue-1.js.map
  apps/settings/js/vue-2.js
  apps/settings/js/vue-2.js.map
  apps/settings/js/vue-4.js
  apps/settings/js/vue-4.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-6.js
  apps/settings/js/vue-6.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/AppList.vue
  apps/settings/src/main-apps-users-management.js
Labels: 4. to release, bug, feature: language l10n and translations

#19549 remove noise from detectUuid and cache results
  apps/user_ldap/lib/Access.php
Labels: 4. to release, backport-request, bug, feature: ldap

#19621 Make sure that the transfer details are present in the database during the cron run
  apps/files/lib/Controller/TransferOwnershipController.php
Labels: 3. to review, backport-request, bug, regression

#19619 Fix hover state color of drag-n-drop with theming and dark mode
  apps/files/css/files.scss
Labels: 3. to review, backport-request, bug, design, feature: accessibility, feature: files, feature: theming

#19634 Correctly trim long cyrillic note
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 4. to release, backport-request, bug, feature: dav

#19252 Hash event UID to make sure it's not too long for PushProvider notifications
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/PushProviderTest.php
Labels: 3. to review, backport-request, bug, feature: dav

#19433 Fix installing Talk due to hardcoded route
  lib/private/AppFramework/App.php
Labels: 4. to release, bug, feature: apps management

#19589 Make sure quota_preset is using numerical indexes
  apps/settings/lib/Controller/UsersController.php
Labels: 3. to review, bug

#19659 Allow non integer ids in Entity Mapper
  lib/public/AppFramework/Db/QBMapper.php
Labels: 3. to review, technical debt

#19670 Allow to remove listeners
  lib/private/EventDispatcher/EventDispatcher.php
  lib/public/EventDispatcher/IEventDispatcher.php
Labels: 3. to review, pending documentation, technical debt

#19683 Readme: fix typo
  README.md
Labels: 4. to release

#19676 Theme search results
  core/search/css/results.scss
Labels: 3. to review, backport-request, bug, feature: accessibility, feature: search, feature: theming

#19655 Catch NotFoundException when getting the user folder
  apps/dav/lib/BackgroundJob/UploadCleanup.php
Labels: 4. to release, bug

#18885 [stable16] relax strict getHome behaviour for LDAP users in a shadow state
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/tests/User_LDAPTest.php
Labels: 4. to release, bug, enhancement, feature: ldap

#19666 Don't show referrer policy warning if fallback policy set.
  core/js/setupchecks.js
Labels: 3. to review, bug

#19613 Check that username and password are present.
  lib/base.php
Labels: 3. to review, bug

#19694 Also cache avatars when it's not allowed
  core/Controller/AvatarController.php
Labels: 4. to release, backport-request, bug

#19321 Allow to overwrite share target mountpoints
  apps/files_sharing/lib/SharedMount.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Share/Events/VerifyMountPointEvent.php
Labels: 3. to review, enhancement, feature: sharing

#19493 Create SimpleFile only when writing the content
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/Node/LazyRoot.php
  lib/private/Files/Node/NonExistingFolder.php
  lib/private/Files/SimpleFS/NewSimpleFile.php
  lib/private/Files/SimpleFS/SimpleFolder.php
  lib/public/Files/Folder.php
  lib/public/Files/SimpleFS/ISimpleFolder.php
  tests/lib/Files/SimpleFS/SimpleFolderTest.php
Labels: 4. to release

#19664 Revive the "send email to new users" toggle for the user form
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/appinfo/routes.php
  apps/settings/js/vue-0.js
  apps/settings/js/vue-0.js.map
  apps/settings/js/vue-5.js
  apps/settings/js/vue-5.js.map
  apps/settings/js/vue-7.js
  apps/settings/js/vue-7.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/lib/Controller/UsersController.php
  apps/settings/src/views/Users.vue
Labels: 4. to release, backport-request, enhancement, regression

#18884 [stable17] relax strict getHome behaviour for LDAP users in a shadow state
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/tests/User_LDAPTest.php
Labels: 4. to release, bug, enhancement, feature: ldap

#19707 Fix non-centered no javascript message
  core/css/styles.scss
Labels: 3. to review, backport-request, bug
