Repository nextcloud/server, pull requests merged in 2021-10, with the labels that each got.

#28263 Fix Lots of Error: file_exists(): open_basedir restriction in effect.…
  lib/private/Route/Router.php
  lib/private/Template/Base.php
  lib/private/Template/IconsCacher.php
  lib/private/Template/ResourceLocator.php
Labels: bug, 3. to review, backport-request

#29044 Change output format of Psalm to Github
  .github/workflows/static-code-analysis.yml
Labels: enhancement, 3. to review, backport-request

#29048 [stable20] Change output format of Psalm to Github
  .github/workflows/static-code-analysis.yml
Labels: enhancement

#29047 [stable21] Change output format of Psalm to Github
  .github/workflows/static-code-analysis.yml
Labels: enhancement

#28939 Don't further setup disabled users when logging in with apache
  lib/private/legacy/OC_User.php
Labels: 3. to review, backport-request, feature: authentication

#29056 Allow "TwoFactor Nextcloud Notifications" to pull the state of the 2FA again
  core/Middleware/TwoFactorMiddleware.php
  psalm.xml
Labels: bug, 3. to review, backport-request, feature: authentication

#29058 Do not transfer shares for deleted users
  apps/files/lib/Service/OwnershipTransferService.php
Labels: bug, 3. to review, feature: sharing

#29069 [stable20] file-upload: Correctly handle error responses for HTTP2
  apps/files/js/file-upload.js
Labels: bug, 3. to review

#27733 Add IUrlGenerator::linkToDefaultPageUrl()
  build/psalm-baseline-ocp.xml
  core/Controller/LoginController.php
  core/Controller/RecommendedAppsController.php
  core/Controller/SetupController.php
  core/Controller/TwoFactorChallengeController.php
  lib/base.php
  lib/private/URLGenerator.php
  lib/private/legacy/OC_Util.php
  lib/public/AppFramework/Http/RedirectToDefaultAppResponse.php
  lib/public/IURLGenerator.php
  tests/Core/Controller/LoginControllerTest.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
  tests/lib/UrlGeneratorTest.php
  tests/lib/UtilTest.php
Labels: enhancement, 3. to review, technical debt

#29019 Improve log and allow duplicate notifications section
  lib/private/Settings/Manager.php
Labels: enhancement, 3. to review, feature: settings

#29053 Use proper exit code
  lib/versioncheck.php
Labels: 3. to review, technical debt

#29079 Only load screenshots if available from app store releases
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/src/components/AppList/AppItem.vue
  apps/settings/src/views/Apps.vue
Labels: bug, 3. to review, feature: apps management

#29074 [stable21] executeQuery and executeStatement are 22+
  apps/user_ldap/lib/Migration/Version1120Date20210917155206.php
Labels: bug, 3. to review

#29075 [stable21] Fix path of file_get_contents
  lib/private/legacy/OC_Image.php
Labels: bug, 3. to review

#29068 [stable21] file-upload: Correctly handle error responses for HTTP2
  apps/files/js/file-upload.js
Labels: bug, 3. to review

#29070 [stable21] Update psalm baseline
  build/psalm-baseline.xml
Labels: 3. to review, technical debt

#29082 Add a few sensitive config keys
  lib/private/SystemConfig.php
Labels: enhancement, 3. to review, feature: external storage, feature: settings

#29065 Fix missing translations of share folder selection
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/components/SelectShareFolderDialogue.vue
Labels: bug, 3. to review, feature: sharing, feature: settings, feature: language l10n and translations
