Repository nextcloud/server, pull requests merged in 2021-04, with the labels that each got.

#26394 Allow apps to write/update account data
  lib/private/Accounts/AccountManager.php
  lib/public/Accounts/IAccountManager.php
Labels: 3. to review, backport-request, feature: users and groups

#26390 Increase PHP CS speed
  .php_cs.dist
Labels: 4. to release, technical debt

#25605 dont show trusted proxy warning when the proxy and remote are both localhost
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 3. to review

#26403 remove leftover debug @NoCSRFRequired introduced with #26198
  core/Controller/SearchController.php
Labels: 3. to review, backport-request

#26396 Get the parent directory before creating a file from a template
  lib/private/DirectEditing/Manager.php
  lib/private/Files/Template/TemplateManager.php
  tests/lib/DirectEditing/ManagerTest.php
Labels: 3. to review, bug

#26264 [stable19] Handle limit offset and sorting in files search
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/Search/SearchOrder.php
  lib/private/Files/Search/SearchQuery.php
  lib/private/Search/Provider/File.php
  lib/private/Search/Result/File.php
  lib/public/Files/Search/ISearchOrder.php
  lib/public/Files/Search/ISearchQuery.php
  tests/lib/Files/Node/FolderTest.php
Labels: 3. to review

#24055 Enforce no notnull for boolean to store false
  lib/private/DB/MigrationService.php
  tests/lib/DB/MigrationsTest.php
Labels: 3. to review, bug, feature: install and update

#26402 [21] make ILDAPProviderFactory usable when there is no ldap setup
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/LDAP/NullLDAPProviderFactory.php
  lib/private/Server.php
  lib/public/LDAP/ILDAPProviderFactory.php
Labels: 3. to review, backport-request

#26311 19.0.10 RC1
  version.php
Labels: 2. developing, overview

#26312 20.0.9 RC1
  version.php
Labels: 2. developing, overview

#26313 21.0.1 RC1
  version.php
Labels: 2. developing, overview

#24966 avoid fread on directories and unencrypted files
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 3. to review, bug, feature: filesystem

#26451 Revert "[stable21] add a prefix index to filecache.path"
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review

#26452 Revert "add a prefix index to filecache.path"
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review

#26433 Limit size of properties to 2048 characters
  lib/private/Accounts/AccountManager.php
Labels: 3. to review

#26458 Show icon-phone when setting is set to private instead of local
  apps/settings/js/federationsettingsview.js
Labels: 3. to review, backport-request, bug

#26432 Add npm/nodejs/make to .devcontainer
  .devcontainer/Dockerfile
Labels: 3. to review

#26453 21.0.1 final
  version.php
Labels: 2. developing, overview

#26454 20.0.9 final
  version.php
Labels: 2. developing, overview

#26455 19.0.10 final
  version.php
Labels: 2. developing, overview

#26439 Increase subnet matcher
  lib/private/Security/Normalizer/IpAddress.php
  tests/lib/Security/Normalizer/IpAddressTest.php
Labels: 3. to review

#26401 Show informative errors on avatar upload error
  core/Controller/AvatarController.php
Labels: 3. to review, enhancement, feature: settings

#26475 l10n: Correct spelling
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/ResetPassword.vue
Labels: 3. to review

#26477 Remove old unused handlebar systemtags template
  build/compile-handlebars-templates.sh
Labels: 3. to review, enhancement

#26230 l10n: Add word user in FederatedShareProvider.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
Labels: 2. developing, backport-request

#26266 Improve networking checks
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Http/Client/Client.php
  lib/private/Http/Client/ClientService.php
  lib/private/Http/Client/DnsPinMiddleware.php
  lib/private/Http/Client/LocalAddressChecker.php
  lib/private/Http/Client/NegativeDnsCache.php
  lib/private/Server.php
  tests/lib/Http/Client/ClientServiceTest.php
  tests/lib/Http/Client/ClientTest.php
  tests/lib/Http/Client/LocalAddressCheckerTest.php
  tests/lib/Http/Client/NegativeDnsCacheTest.php
Labels: 3. to review, security

#26467 Allow apps to log actions into the audit_log
  apps/admin_audit/composer/composer/autoload_classmap.php
  apps/admin_audit/composer/composer/autoload_static.php
  apps/admin_audit/lib/AppInfo/Application.php
  apps/admin_audit/lib/Listener/CriticalActionPerformedEventListener.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Log/Audit/CriticalActionPerformedEvent.php
Labels: 3. to review, enhancement, feature: admin audit, pending documentation

#26521 Fix accessibility issues on log in screen
  core/css/guest.css
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/LoginForm.vue
  core/src/views/Login.vue
Labels: 3. to review, backport-request, bug, design, feature: accessibility

#26533 Fix undefined error on add-share
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/views/SharingTab.vue
Labels: 3. to review, backport-request, bug, feature: sharing

#26529 Use correct getSystemValue type
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  lib/private/Authentication/Login/CreateSessionTokenCommand.php
  lib/private/Collaboration/Collaborators/LookupPlugin.php
  lib/private/Preview/Generator.php
  lib/private/Preview/Image.php
Labels: 3. to review

#26551 ensure redis returns bool for hasKey
  lib/private/Http/Client/NegativeDnsCache.php
  lib/private/Memcache/Redis.php
Labels: 3. to review, bug

#25320 Implement expiration date for federated shares
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/services/ConfigService.js
  apps/files_sharing/tests/CapabilitiesTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/settings/js/admin.js
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/templates/settings/admin/sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  lib/private/Share20/Manager.php
  lib/private/Template/JSConfigHelper.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release, enhancement, feature: federation

#26558 Dashboard: add missing strict_types
  apps/dashboard/templates/index.php
Labels: 3. to review

#26560 2FA backupcodes: add strict typing
  apps/twofactor_backupcodes/appinfo/routes.php
  apps/twofactor_backupcodes/lib/Activity/Provider.php
  apps/twofactor_backupcodes/lib/Controller/SettingsController.php
  apps/twofactor_backupcodes/lib/Db/BackupCode.php
  apps/twofactor_backupcodes/lib/Db/BackupCodeMapper.php
  apps/twofactor_backupcodes/lib/Event/CodesGenerated.php
  apps/twofactor_backupcodes/lib/Listener/ActivityPublisher.php
  apps/twofactor_backupcodes/lib/Listener/RegistryUpdater.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20170607104347.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20170607113030.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20170919123342.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20170926101419.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20180821043638.php
  apps/twofactor_backupcodes/lib/Provider/BackupCodesProvider.php
  apps/twofactor_backupcodes/lib/Service/BackupCodeStorage.php
  apps/twofactor_backupcodes/lib/Settings/Personal.php
  apps/twofactor_backupcodes/templates/challenge.php
  apps/twofactor_backupcodes/templates/personal.php
  apps/twofactor_backupcodes/tests/Db/BackupCodeMapperTest.php
  apps/twofactor_backupcodes/tests/Service/BackupCodeStorageTest.php
  apps/twofactor_backupcodes/tests/Unit/Activity/ProviderTest.php
  apps/twofactor_backupcodes/tests/Unit/Controller/SettingsControllerTest.php
  apps/twofactor_backupcodes/tests/Unit/Event/CodesGeneratedTest.php
  apps/twofactor_backupcodes/tests/Unit/Listener/ActivityPublisherTest.php
  apps/twofactor_backupcodes/tests/Unit/Listener/RegistryUpdaterTest.php
  apps/twofactor_backupcodes/tests/Unit/Migration/CheckBackupCodeTest.php
  apps/twofactor_backupcodes/tests/Unit/Provider/BackupCodesProviderTest.php
  apps/twofactor_backupcodes/tests/Unit/Service/BackupCodeStorageTest.php
Labels: 3. to review

#26559 Updatenotification: add missing strict_types
  apps/updatenotification/appinfo/routes.php
  apps/updatenotification/lib/Command/Check.php
Labels: 3. to review

#26581 Fix constraint violation detection in QB Mapper
  lib/public/AppFramework/Db/QBMapper.php
Labels: 3. to review, backport-request, bug, regression

#26553 Move NotifierService registration to IBootstrap
  apps/comments/lib/AppInfo/Application.php
  apps/dav/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/files/lib/AppInfo/Application.php
  apps/twofactor_backupcodes/lib/AppInfo/Application.php
  apps/updatenotification/lib/AppInfo/Application.php
  apps/user_ldap/lib/AppInfo/Application.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Notification/Manager.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/Notification/IManager.php
  tests/lib/Notification/ManagerTest.php
Labels: 3. to review, enhancement, pending documentation

#26592 Listen to proper UserDeletedEvent
  apps/twofactor_backupcodes/composer/composer/autoload_classmap.php
  apps/twofactor_backupcodes/composer/composer/autoload_static.php
  apps/twofactor_backupcodes/lib/AppInfo/Application.php
  apps/twofactor_backupcodes/lib/Listener/UserDeleted.php
Labels: 4. to release, enhancement

#26555 Run migrator tests on OCI
  tests/lib/DB/MigratorTest.php
Labels: 3. to review, technical debt

#26614 Update root.crl due to revoked news.crt
  resources/codesigning/root.crl
Labels: 3. to review

#26613 Do not allow adding file drop shares to your own cloud
  apps/federatedfilesharing/lib/Controller/MountPublicLinkController.php
  apps/federatedfilesharing/tests/Controller/MountPublicLinkControllerTest.php
Labels: 3. to review, backport-request, enhancement, feature: sharing

#26615 Require read permissions for federated shares
  apps/federatedfilesharing/lib/FederatedShareProvider.php
Labels: 3. to review, backport-request, enhancement, feature: federation

#26633 Make lookup search explicit
  apps/files_sharing/lib/Controller/ShareesAPIController.php
Labels: 4. to release, enhancement

#26624 Consider read permission in sharing tab
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/models/Share.js
Labels: 3. to review, enhancement, feature: sharing

#26625 [stable21] Fix empty password check for mail shares
  build/psalm-baseline.xml
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, backport-request, bug, feature: sharing

#26639 [stable21] ensure redis returns bool for hasKey
  lib/private/Memcache/Redis.php
Labels: 3. to review, backport-request, bug

#26548 Files & Core accessibility fixes
  apps/files/css/files.scss
  apps/files/templates/appnavigation.php
  apps/files/templates/index.php
  apps/settings/css/settings.scss
  apps/settings/js/settings/personalInfo.js
  apps/settings/js/templates.js
  apps/settings/js/templates/federationscopemenu.handlebars
  apps/settings/templates/settings/personal/personal.info.php
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/views/UnifiedSearch.vue
Labels: 3. to review, backport-request, bug, design, feature: accessibility

#26550 hide mail share if a cloud share is possible – backend only solution
  lib/private/Collaboration/Collaborators/Search.php
  lib/private/Collaboration/Collaborators/SearchResult.php
  lib/public/Collaboration/Collaborators/ISearchResult.php
  tests/lib/Collaboration/Collaborators/SearchTest.php
Labels: 3. to review, bug, enhancement, feature: sharing

#26653 [stable21] Update psalm baseline
  build/psalm-baseline.xml
Labels: 3. to review, technical debt

#26656 [stable20] Update psalm baseline
  apps/files_external/lib/Lib/Storage/SFTP.php
  build/psalm-baseline.xml
Labels: 3. to review, technical debt

#26663 Fix support tests
  tests/lib/Support/Subscription/RegistryTest.php
Labels: 3. to review, bug

#26662 Fix DAV unit tests
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/Controller/InvitationResponseControllerTest.php
  apps/dav/tests/unit/Migration/RefreshWebcalJobRegistrarTest.php
Labels: 3. to review, bug

#26659 Fix update notification tests
  apps/updatenotification/tests/Notification/BackgroundJobTest.php
Labels: 3. to review, bug

#26660 Fix twofactor backup code tests
  apps/twofactor_backupcodes/tests/Unit/Controller/SettingsControllerTest.php
  apps/twofactor_backupcodes/tests/Unit/Listener/ActivityPublisherTest.php
Labels: 3. to review, bug

#26647 Fail when creating new files with an empty path
  lib/private/Files/Node/Folder.php
Labels: 3. to review, bug, feature: object storage

#26646 [stable19] Fix empty password check for mail shares
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, bug, feature: sharing

#26617 Do not check Oracle column constraints in unrelated migrations
  lib/private/DB/MigrationService.php
Labels: 3. to review, bug, regression

#26652 Fix broken Expiration test
  apps/files_trashbin/tests/ExpirationTest.php
Labels: 3. to review, backport-request, bug, feature: trashbin

#26594 Move 2FA registration to IBootstrap
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/twofactor_backupcodes/lib/AppInfo/Application.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Authentication/TwoFactorAuth/ProviderLoader.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  tests/lib/Authentication/TwoFactorAuth/ProviderLoaderTest.php
Labels: 3. to review, enhancement, pending documentation

#26661 Fix LDAP unit tests
  apps/user_ldap/tests/Jobs/UpdateGroupsTest.php
Labels: 3. to review, bug

#26658 Do not stop directory listing when ACL is blocking access
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review, bug

#26654 Fix security credentials manager test
  tests/lib/Security/CredentialsManagerTest.php
Labels: 3. to review, bug

#25991 Update acceptance tests to Selenium 3
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/ContactsMenuContext.php
  tests/acceptance/features/bootstrap/FilesAppSharingContext.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/ThemingAppContext.php
  tests/acceptance/features/bootstrap/UsersSettingsContext.php
  tests/acceptance/features/core/ElementWrapper.php
  tests/acceptance/run.sh
Labels: 4. to release, enhancement, technical debt

#26575 set mimetype for objects uploaded to object storages
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  apps/files_external/lib/Lib/Storage/Swift.php
  lib/private/Files/ObjectStore/Azure.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
  lib/private/Files/ObjectStore/StorageObjectStore.php
  lib/private/Files/ObjectStore/Swift.php
  lib/public/Files/ObjectStore/IObjectStore.php
  tests/lib/Files/ObjectStore/FailDeleteObjectStore.php
  tests/lib/Files/ObjectStore/FailWriteObjectStore.php
  tests/lib/Files/ObjectStore/S3Test.php
Labels: 3. to review

#26474 Mention MariaDB in MySQL support warning
  apps/settings/lib/SetupChecks/SupportedDatabase.php
Labels: 3. to review

#25714 Explicitly check hex2bin input
  lib/private/Security/Crypto.php
Labels: 2. developing

#26692 Redirect users to forum for questions
  .github/ISSUE_TEMPLATE/config.yml
Labels: 3. to review, pending documentation

#26586 Handle device login like an alternative login
  apps/theming/css/theming.scss
  core/Controller/LoginController.php
  core/css/guest.css
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/login.js
  core/src/views/Login.vue
  core/templates/login.php
Labels: 3. to review, bug

#26699 remove undefined parameter, add description
  lib/public/DB/IResult.php
Labels: 3. to review, backport-request, bug

#26700 FIx Oracle by testing on Ubuntu 20.04 until oci8.so is available for …
  .github/workflows/oci.yml
Labels: 3. to review, bug, high

#26627 update icewind/smb to 3.4.1
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/InstalledVersions.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/composer/installed.php
  apps/files_external/3rdparty/icewind/smb/src/AnonymousAuth.php
  apps/files_external/3rdparty/icewind/smb/src/KerberosAuth.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeStream.php
  apps/files_external/3rdparty/icewind/smb/src/StringBuffer.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Server.php
Labels: 3. to review, backport-request

#26375 "Symfony\Component\Translation\PluralizationRules" is deprecated
  build/translation-checker.php
  lib/private/L10N/L10N.php
  lib/private/L10N/L10NString.php
  lib/private/Share20/Manager.php
  tests/data/l10n/de.json
  tests/lib/L10N/L10nTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, bug, feature: language l10n and translations

#26717 Only set copy etag if the destination source can be found
  apps/dav/lib/Connector/Sabre/CopyEtagHeaderPlugin.php
  apps/dav/tests/unit/Connector/Sabre/CopyEtagHeaderPluginTest.php
Labels: 3. to review, bug, feature: dav

#26719 Clean up DB code in the CalDAV backend
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, enhancement

#25417 Fix account data visibility after disabling public addressbook upload
  .drone.yml
  apps/settings/css/settings.scss
  apps/settings/js/federationscopemenu.js
  apps/settings/js/templates.js
  apps/settings/js/templates/federationscopemenu.handlebars
  apps/settings/lib/Controller/UsersController.php
  apps/settings/templates/settings/personal/personal.info.php
  apps/settings/tests/Controller/UsersControllerTest.php
  build/integration/features/bootstrap/ContactsMenu.php
  build/integration/features/bootstrap/FeatureContext.php
  build/integration/features/contacts-menu.feature
  lib/private/Accounts/AccountManager.php
Labels: 3. to review, backport-request, bug, feature: settings

#26721 private cannot be final
  lib/private/FullTextSearch/Model/IndexDocument.php
Labels: backport-request

#26755 Correctly truncate multibyte strings to fit into the database
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 3. to review

#26747 Fix installer deprecation warnings for PHP 8
  lib/private/Installer.php
Labels: 3. to review, backport-request, php

#26259 Validate the website field input to be a valid URL
  apps/settings/lib/Controller/UsersController.php
  lib/private/Accounts/AccountManager.php
  tests/lib/Accounts/AccountManagerTest.php
Labels: 3. to review, bug, feature: settings

#26762 Respect the error level when logging
  lib/private/Log/ErrorHandler.php
Labels: 4. to release, backport-request, bug, feature: logging

#26763 Improve federated permission handling
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
Labels: 4. to release, backport-request, enhancement

#26765 No longer add trusted servers on federated share creation
  apps/federation/appinfo/routes.php
  apps/federation/composer/composer/autoload_classmap.php
  apps/federation/composer/composer/autoload_static.php
  apps/federation/js/settings-admin.js
  apps/federation/lib/AppInfo/Application.php
  apps/federation/lib/Controller/SettingsController.php
  apps/federation/lib/Listener/FederatedShareAddedListener.php
  apps/federation/templates/settings-admin.php
Labels: 4. to release, backport-request, enhancement, technical debt

#26774 removes PagedResults adapter for PHP < 7.3
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/LDAP.php
  apps/user_ldap/lib/PagedResults/Php54.php
Labels: 3. to review, feature: ldap, technical debt

#26764 Add geo location as ROS type
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review, enhancement

#26572 Throw "401 Unauthenticated" when authentication is provided but invalid
  build/integration/features/bootstrap/RemoteContext.php
  build/integration/remoteapi_features/remote.feature
  lib/private/User/Session.php
  tests/lib/Authentication/TwoFactorAuth/ProviderLoaderTest.php
Labels: 3. to review, bug, feature: authentication, security

#26718 Fix ratelimit template
  lib/private/AppFramework/Middleware/Security/RateLimitingMiddleware.php
  lib/private/Template/Base.php
  tests/lib/AppFramework/Middleware/Security/RateLimitingMiddlewareTest.php
Labels: 3. to review, bug

#26591 Less ILogger
  apps/files_sharing/tests/TestCase.php
  console.php
  core/Command/Maintenance/Install.php
  core/Command/Upgrade.php
  core/ajax/update.php
  core/register_command.php
  lib/base.php
  lib/private/App/AppManager.php
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/AppStore/Fetcher/CategoryFetcher.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  lib/private/Avatar/Avatar.php
  lib/private/Avatar/AvatarManager.php
  lib/private/Avatar/GuestAvatar.php
  lib/private/Avatar/PlaceholderAvatar.php
  lib/private/Avatar/UserAvatar.php
  lib/private/CapabilitiesManager.php
  lib/private/Collaboration/Collaborators/LookupPlugin.php
  lib/private/Collaboration/Resources/Manager.php
  lib/private/Collaboration/Resources/ProviderManager.php
  lib/private/Console/Application.php
  lib/private/InitialStateService.php
  lib/private/Installer.php
  lib/private/Server.php
  lib/private/Setup.php
  lib/private/Setup/AbstractDatabase.php
  lib/private/Setup/MySQL.php
  lib/private/Setup/PostgreSQL.php
  lib/private/Updater.php
  lib/private/legacy/OC_Util.php
  tests/lib/App/AppManagerTest.php
  tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
  tests/lib/App/AppStore/Fetcher/FetcherBase.php
  tests/lib/AppFramework/Bootstrap/CoordinatorTest.php
  tests/lib/AppFramework/Bootstrap/RegistrationContextTest.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
  tests/lib/AppTest.php
  tests/lib/Avatar/AvatarManagerTest.php
  tests/lib/Avatar/GuestAvatarTest.php
  tests/lib/Avatar/UserAvatarTest.php
  tests/lib/CapabilitiesManagerTest.php
  tests/lib/Collaboration/Collaborators/LookupPluginTest.php
  tests/lib/Collaboration/Resources/ManagerTest.php
  tests/lib/Collaboration/Resources/ProviderManagerTest.php
  tests/lib/InitialStateServiceTest.php
  tests/lib/InstallerTest.php
  tests/lib/SetupTest.php
  tests/lib/UpdaterTest.php
Labels: 3. to review, technical debt

#26781 More cleaning after auto-add removal
  apps/federation/composer/composer/autoload_classmap.php
  apps/federation/composer/composer/autoload_static.php
  apps/federation/lib/Hooks.php
  apps/federation/lib/Settings/Admin.php
  apps/federation/lib/TrustedServers.php
  apps/federation/tests/HooksTest.php
  apps/federation/tests/Settings/AdminTest.php
  apps/federation/tests/TrustedServersTest.php
Labels: 3. to review, bug, feature: federation

#26785 LDAP: do not bother to search after the last page
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Exceptions/NoMoreResults.php
Labels: 3. to review, backport-request, bug, feature: ldap

#26758 Some more strict_types
  core/BackgroundJobs/BackgroundCleanupUpdaterBackupsJob.php
  core/BackgroundJobs/CheckForUserCertificates.php
  core/BackgroundJobs/CleanupLoginFlowV2.php
  core/register_command.php
  core/routes.php
  core/strings.php
  lib/autoloader.php
  lib/base.php
  lib/private/Updater.php
  lib/public/AutoloadNotAllowedException.php
  lib/public/Constants.php
  lib/public/Defaults.php
  lib/public/PreConditionNotMetException.php
  lib/versioncheck.php
  tests/docker/mysqlmb4.config.php
Labels: 3. to review, technical debt

#26784 l10n: Change to a capital letter
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: 2. developing

#26811 Do not try to contact lookup server if not needed
  apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php
  core/BackgroundJobs/LookupServerSendCheckBackgroundJob.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC22/LookupServerSendCheck.php
  version.php
Labels: 3. to review, enhancement

#26461 Only return display name as editable when the user backend allows it
  apps/provisioning_api/appinfo/routes.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 4. to release, backport-request, bug, feature: users and groups

#26825 [stable19] Do not try to contact lookup server if not needed
  apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php
  core/BackgroundJobs/LookupServerSendCheckBackgroundJob.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC22/LookupServerSendCheck.php
  version.php
Labels: 3. to review, enhancement

#26824 [stable20] Do not try to contact lookup server if not needed
  apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php
  core/BackgroundJobs/LookupServerSendCheckBackgroundJob.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC22/LookupServerSendCheck.php
  version.php
Labels: 3. to review, enhancement

#26826 Exclusively use the typed calendar deletion events for DAV
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/Listener/CalendarDeletionActivityUpdaterListener.php
  apps/dav/lib/Listener/CalendarDeletionDefaultUpdaterListener.php
  apps/dav/lib/Listener/CalendarDeletionReminderUpdaterListener.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  build/psalm-baseline.xml
Labels: 3. to review, enhancement, technical debt

#26542 [stable20] Limit size of properties to 2048 characters
  lib/private/Accounts/AccountManager.php
Labels: 4. to release

#26543 [stable19] Limit size of properties to 2048 characters
  lib/private/Accounts/AccountManager.php
Labels: 4. to release

#26593 Filter mounts for file id before trying to get user information
  lib/private/Files/Config/UserMountCache.php
Labels: 4. to release, performance 🚀

#26835 21.0.2 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: overview

#26836 20.0.10 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: overview

#26837 19.0.11 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: overview
