Repository nextcloud/server, pull requests merged in 2021-08, with the labels that each got.

#28298 22.1.0
  version.php
Labels: 3. to review

#28299 21.0.4
  version.php
Labels: 3. to review

#28300 20.0.12
  version.php
Labels: 3. to review

#28248 [stable20] Fix autocompletion for usernames in comments
  apps/comments/js/comments.js
  apps/comments/js/comments.js.map
  apps/comments/src/commentstabview.js
Labels: 3. to review, bug

#28304 Allow upgrade from 22.1
  version.php
Labels: 3. to review, bug, high

#28306 Allow upgrade from 22.1
  version.php
Labels: 3. to review, bug

#28323 Fixes of logo files in the repository
  core/img/logo/logo-enterprise.png
  core/img/logo/logo-enterprise.svg
  core/img/logo/logo.svg
Labels: 4. to release, bug, design

#28324 Set a maximum level of encoding nested arguments of exception traces
  lib/private/Log/ExceptionSerializer.php
Labels: bug, 4. to release

#28325 autotest.sh: Add PHPUNIT_EXE environment variable
  autotest.sh
Labels: enhancement, 3. to review

#28330 Update Makefile to clean all apps
  Makefile
Labels: 3. to review

#28331 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: 4. to release, dependencies

#28352 Change the concurrent upload limit to less than 10
  apps/files/js/file-upload.js
Labels: 3. to review

#28351 Fix Recent statuses plural/singular
  apps/user_status/lib/Dashboard/UserStatusWidget.php
  apps/user_status/tests/Unit/Dashboard/UserStatusWidgetTest.php
Labels: 3. to review

#28220 fix Folder->getById() when a single storage is mounted multiple times
  lib/private/Files/Node/Folder.php
  tests/lib/Files/Node/FolderTest.php
Labels: bug, 3. to review, backport-request

#28013 Jitter the requests to the appstore and updater server over 3 minutes
  apps/updatenotification/lib/Notification/BackgroundJob.php
  apps/updatenotification/tests/Notification/BackgroundJobTest.php
Labels: bug, 4. to release, feature: install and update, feature: apps management, feature: activity and notification

#28360 Revert "Fix Recent statuses plural/singular"
  apps/user_status/lib/Dashboard/UserStatusWidget.php
  apps/user_status/tests/Unit/Dashboard/UserStatusWidgetTest.php
Labels: 3. to review

#27923 Remove Flysystem storage class
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Storage/Flysystem.php
Labels: 3. to review

#28348 cron: exit 1 on exception
  cron.php
Labels: enhancement, 3. to review

#28318 Make "name" column nullable for workflows
  apps/workflowengine/appinfo/info.xml
  apps/workflowengine/composer/composer/autoload_classmap.php
  apps/workflowengine/composer/composer/autoload_static.php
  apps/workflowengine/lib/Controller/AWorkflowController.php
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
  apps/workflowengine/lib/Migration/Version2200Date20210805101925.php
Labels: bug, 3. to review, feature: workflows

#28062 Gracefully handle smb acls for users without a domain
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: bug, 4. to release, feature: external storage, backport-request

#24185 Properly handle folder deletion on external s3 storage
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  lib/private/Files/Storage/Common.php
Labels: bug, 3. to review

#28211 Improve auto expiration hint for trashbin and file versions
  apps/files_trashbin/lib/Command/ExpireTrash.php
  apps/files_versions/lib/Command/ExpireVersions.php
Labels: enhancement, 3. to review, backport-request, feature: occ

#28303 UnifiedSearchController: strip webroot from URL before finding a route
  core/Controller/UnifiedSearchController.php
  lib/private/URLGenerator.php
  lib/public/IURLGenerator.php
  tests/lib/UrlGeneratorTest.php
Labels: bug, 2. developing, feature: search

#28445 Always add header-right container
  core/templates/layout.public.php
Labels: enhancement, 3. to review

#28461 Disable autofocus of primary Email
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
Labels: bug, 3. to review, backport-request

#28464 Only trap E_ERROR in session handling
  lib/private/Session/Internal.php
Labels: bug, 3. to review

#28486 Add storage info to `user:info` command
  core/Command/User/Info.php
Labels: enhancement, 3. to review, feature: occ

#28413 Emit an error log when the app token login name does not match
  lib/private/User/Session.php
Labels: bug, 3. to review, backport-request

#28481 Hash cache key
  lib/private/User/Manager.php
Labels: bug, 4. to release, backport-request

#28485 Fix #20913: Check image resource before attempting to preserve alpha
  lib/private/legacy/OC_Image.php
Labels: 3. to review

#28479 [stable22] Disable autofocus of primary Email
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
Labels: bug, 3. to review

#28493 Write upgrade/not-installed notices to stderr
  lib/private/Console/Application.php
Labels: bug, 3. to review

#28502 Remove unused method
  lib/private/legacy/OC_Image.php
Labels: 3. to review, technical debt

#27294 Update TwoFactorChallengeController.php
  core/Controller/TwoFactorChallengeController.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
Labels: 3. to review

#28507 Scope composer tools with the bin plugin
  .gitignore
  build/files-checker.php
  composer.json
  composer.lock
  lib/composer/composer/InstalledVersions.php
  lib/composer/composer/installed.php
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: enhancement, 4. to release

#28512 Output exception in cron
  cron.php
Labels: enhancement, 4. to release, backport-request, feature: logging

#27993 [stable22] Manual backport of "No limit in the number of group shares" #27875
  apps/files_sharing/lib/Listener/UserAddedToGroupListener.php
Labels: 3. to review

#28516 [stable20] Output exception in cron
  cron.php
Labels: enhancement, 3. to review, feature: logging

#27637 Use search to get versions list from cache for expiry
  apps/files_versions/lib/Storage.php
  apps/files_versions/tests/StorageTest.php
Labels: 4. to release

#28504 Properly log errors in Movie previews generation
  lib/private/Preview/Generator.php
  lib/private/Preview/Movie.php
Labels: bug, 3. to review, backport-request, feature: previews and thumbnails

#28514 22.1.1 RC1
  version.php
Labels: 3. to review

#28519 Add active user count to occ user:report
  core/Command/User/Report.php
Labels: enhancement, 3. to review

#28518 [stable22] Output exception in cron
  cron.php
Labels: enhancement, 3. to review, feature: logging

#28517 [stable21] Output exception in cron
  cron.php
Labels: enhancement, 3. to review, feature: logging

#28458 Expose user language through DAV
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_versions/lib/AppInfo/Application.php
Labels: 3. to review, feature: dav, feature: language l10n and translations

#28478 Fix SQL type error
  lib/private/Comments/Manager.php
Labels: bug, 3. to review

#28185 Fix folder size contained in S3 buckets
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: bug, 3. to review, feature: filesystem, backport-request

#28452 Set alias for result of cast column function
  apps/workflowengine/lib/Manager.php
Labels: bug, 3. to review, backport-request

#27877 Refactor writeObject to only use MultipartUpload when required
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
  tests/lib/Files/ObjectStore/ObjectStoreTest.php
  tests/lib/Files/ObjectStore/S3Test.php
Labels: bug, 4. to release, feature: object storage

#28532 Do not load versions tab view if the files app is not available
  apps/files_versions/js/files_versions.js
  apps/files_versions/js/files_versions.js.map
  apps/files_versions/src/versionstabview.js
Labels: bug, 4. to release, backport-request

#26584 Update .htaccess (php8+ and mod_lsapi)
  .htaccess
Labels: 3. to review

#28540 Fix "TypeError: e.t0.response is undefined" spam from user_status
  apps/user_status/js/user-status-menu.js
  apps/user_status/js/user-status-menu.js.map
  apps/user_status/src/UserStatus.vue
Labels: bug, 3. to review, feature: status

#28466 Do not retain VerifyUserData job when lookup server is not available
  apps/settings/lib/BackgroundJobs/VerifyUserData.php
Labels: bug, 3. to review

#28256 [stable22] Add quota restrictions options
  apps/provisioning_api/lib/Controller/AppConfigController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/lib/Controller/UsersController.php
  apps/settings/src/components/UserList.vue
  apps/settings/src/views/Users.vue
  lib/private/User/User.php
  tests/lib/User/UserTest.php
Labels: enhancement, 3. to review, feature: files, feature: settings

#28568 [stable22] fix UserController tests
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: bug, 3. to review, feature: files, technical debt

#28566 use getGetUnjailedRoot to determine if jailed search needs the path filter
  lib/private/Files/Cache/Wrapper/CacheJail.php
Labels: 3. to review

#28476 use case insensitive like when limiting search to jail
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/public/Files/Search/ISearchComparison.php
Labels: 4. to release, backport-request, feature: search

#28571 Remove error suppression
  apps/dav/lib/Upload/AssemblyStream.php
Labels: 4. to release

#28574 Log exception message during failed ownership transfer share restore
  apps/files/lib/Service/OwnershipTransferService.php
Labels: bug, 3. to review, backport-request

#28590 22.1.1-rc2
  version.php
Labels: 3. to review

#28399 add event for when a share is mounted
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Event/ShareMountedEvent.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/tests/MountProviderTest.php
Labels: 3. to review

#28473 Fix path of `file_get_contents`
  lib/private/legacy/OC_Image.php
Labels: 3. to review, backport-request

#28459 Allow to open any app in a standalone window
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/Controller/ThemingControllerTest.php
Labels: enhancement, 3. to review, backport-request, feature: theming

#28421 Allow admins to disable 2FA backup codes via occ
  apps/twofactor_backupcodes/lib/Provider/BackupCodesProvider.php
  apps/twofactor_backupcodes/lib/Service/BackupCodeStorage.php
  apps/twofactor_backupcodes/tests/Unit/Provider/BackupCodesProviderTest.php
  apps/twofactor_backupcodes/tests/Unit/Service/BackupCodeStorageTest.php
Labels: enhancement, 3. to review, security

#28262 Fix setting up 2FA providers when 2FA is enforced and bc are generated
  core/Middleware/TwoFactorMiddleware.php
Labels: bug, 3. to review, backport-request, security

#28616 always allow dav move for movable mount root
  apps/dav/lib/Connector/Sabre/Node.php
Labels: 3. to review

#28349 Compress PNGs
  core/img/actions/starred.png
  core/img/favicon-touch.png
  core/img/favicon.png
Labels: 3. to review

#27991 Manual backport of "No limit in the number of group shares" #27875
  apps/files_sharing/lib/Listener/UserAddedToGroupListener.php
Labels: 3. to review

#28332 Only recommand for php-sodium on >= PHP 7.4
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 3. to review, backport-request

#28419 Delete calendar subscriptions as well when deleting user
  apps/dav/lib/HookManager.php
  apps/dav/tests/unit/DAV/HookManagerTest.php
Labels: bug, 3. to review, feature: dav, backport-request, php

#28646 Fix filter declaration in settings appinfo.xml
  apps/settings/appinfo/info.xml
Labels: 3. to review

#28660 Fix position of search bar
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/components/HeaderMenu.vue
  core/templates/layout.user.php
Labels: 4. to release, backport-request
