Repository nextcloud/server, pull requests merged in 2021-11, with the labels that each got.

#29497 Fixed grammar for "trash bin"
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/src/app.js
  apps/files_trashbin/src/filelist.js
Labels: bug, 3. to review

#29465 update crl
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#27378 add dav plugin to trigger recalculating of checksums
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/ChecksumUpdatePlugin.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
  lib/private/Files/View.php
Labels: 2. developing

#29281 Limit parameter count per query in Cache.removeChildren
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheQueryBuilder.php
Labels: bug, 3. to review

#28385 properly handle cases where cache wrappers block access
  build/psalm-baseline.xml
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
Labels: bug, 4. to release

#29502 Revert "add dav plugin to trigger recalculating of checksums"
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/ChecksumUpdatePlugin.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
  lib/private/Files/View.php
Labels: 4. to release

#29479 Fix/images php 8.0
  lib/private/Avatar/UserAvatar.php
  lib/private/Preview/Bitmap.php
  lib/private/Preview/HEIC.php
  lib/private/Preview/SVG.php
  lib/private/legacy/OC_Image.php
  lib/public/IImage.php
  psalm.xml
  tests/lib/Avatar/UserAvatarTest.php
  tests/lib/ImageTest.php
Labels: bug, 3. to review, backport-request

#29524 Fix missing import of ILogger
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
Labels: 3. to review, technical debt

#29528 [stable22] Revert split capability "AccountPropertyScopesFederationEnabled"
  apps/provisioning_api/lib/Capabilities.php
  apps/provisioning_api/tests/CapabilitiesTest.php
Labels: bug, 3. to review, feature: settings, regression

#29525 Allow to inject the trusted domain helper by public interface
  lib/private/Server.php
Labels: bug, 4. to release

#29533 Add IManager::getCalendarsForPrincipal API
  lib/private/Calendar/Manager.php
  lib/public/Calendar/ICalendarProvider.php
  lib/public/Calendar/IManager.php
Labels: enhancement, 4. to release, feature: dav, integration, pending documentation

#29501 23.0.0 beta 3
  version.php
Labels: 3. to review

#29482 Revamp profile visibility section
  apps/settings/js/vue-settings-admin-delegation.js
  apps/settings/js/vue-settings-admin-delegation.js.map
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users.js
  apps/settings/js/vue-vendors-settings-apps-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps.js
  apps/settings/js/vue-vendors-settings-apps.js.map
  apps/settings/js/vue-vendors-settings-users.js
  apps/settings/js/vue-vendors-settings-users.js.map
  apps/settings/lib/Settings/Personal/PersonalInfo.php
  apps/settings/src/components/PersonalInfo/BiographySection/BiographySection.vue
  apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayNameSection.vue
  apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
  apps/settings/src/components/PersonalInfo/HeadlineSection/HeadlineSection.vue
  apps/settings/src/components/PersonalInfo/OrganisationSection/OrganisationSection.vue
  apps/settings/src/components/PersonalInfo/ProfileSection/EditProfileAnchorLink.vue
  apps/settings/src/components/PersonalInfo/ProfileSection/ProfileSection.vue
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/ProfileVisibilitySection.vue
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/VisibilityDropdown.vue
  apps/settings/src/components/PersonalInfo/RoleSection/RoleSection.vue
  apps/settings/src/components/PersonalInfo/shared/VisibilityDropdown.vue
  apps/settings/src/constants/AccountPropertyConstants.js
  apps/settings/src/main-personal-info.js
  apps/settings/templates/settings/personal/personal.info.php
  lib/private/Profile/ProfileManager.php
Labels: enhancement, 3. to review, feature: settings, feature: profile

#29503 [stable22] update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#29538 22.2.1 RC1
  version.php
Labels: 3. to review

#29071 [stable21] Allow "TwoFactor Nextcloud Notifications" to pull the state of the 2F…
  core/Middleware/TwoFactorMiddleware.php
  psalm.xml
Labels: bug, 4. to release

#29504 [stable21] update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#29322 [21] tell mysql to ignore the sort index for search queries
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheQueryBuilder.php
Labels: 3. to review

#29539 21.0.6 RC1
  version.php
Labels: 3. to review

#29072 [stable20] Allow "TwoFactor Nextcloud Notifications" to pull the state of the 2F…
  core/Middleware/TwoFactorMiddleware.php
  psalm.xml
Labels: bug, 3. to review

#29505 [stable20] update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#29540 20.0.14 RC1
  version.php
Labels: 4. to release

#29529 Update update-psalm-baseline workflow
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#29546 Add continue-on-error for update-psalm-baseline workflow
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#29551 Revert "[21] tell mysql to ignore the sort index for search queries"
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheQueryBuilder.php
Labels: bug, 4. to release

#29547 [Automated] Update psalm-baseline.xml
  .github/workflows/update-psalm-baseline.yml
  build/psalm-baseline.xml
  lib/private/Files/View.php
Labels: 4. to release, automated pr

#29549 [stable22] Update update-psalm-baseline workflow
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#29550 [stable21] Update update-psalm-baseline workflow
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#29548 [stable20] Update update-psalm-baseline workflow
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#29555 Update to composer 2.1.11
  apps/accessibility/composer/composer/InstalledVersions.php
  apps/accessibility/composer/composer/installed.php
  apps/admin_audit/composer/composer/InstalledVersions.php
  apps/admin_audit/composer/composer/installed.php
  apps/cloud_federation_api/composer/composer/InstalledVersions.php
  apps/cloud_federation_api/composer/composer/installed.php
  apps/comments/composer/composer/InstalledVersions.php
  apps/comments/composer/composer/installed.php
  apps/contactsinteraction/composer/composer/InstalledVersions.php
  apps/contactsinteraction/composer/composer/installed.php
  apps/dav/composer/composer/InstalledVersions.php
  apps/dav/composer/composer/installed.php
  apps/encryption/composer/composer/InstalledVersions.php
  apps/encryption/composer/composer/installed.php
  apps/federatedfilesharing/composer/composer/InstalledVersions.php
  apps/federatedfilesharing/composer/composer/installed.php
  apps/federation/composer/composer/InstalledVersions.php
  apps/federation/composer/composer/installed.php
  apps/files/composer/composer/InstalledVersions.php
  apps/files/composer/composer/installed.php
  apps/files_sharing/composer/composer/InstalledVersions.php
  apps/files_sharing/composer/composer/installed.php
  apps/files_trashbin/composer/composer/InstalledVersions.php
  apps/files_trashbin/composer/composer/installed.php
  apps/files_versions/composer/composer/InstalledVersions.php
  apps/files_versions/composer/composer/installed.php
  apps/lookup_server_connector/composer/composer/InstalledVersions.php
  apps/lookup_server_connector/composer/composer/installed.php
  apps/oauth2/composer/composer/InstalledVersions.php
  apps/oauth2/composer/composer/installed.php
  apps/provisioning_api/composer/composer/InstalledVersions.php
  apps/provisioning_api/composer/composer/installed.php
  apps/settings/composer/composer/InstalledVersions.php
  apps/settings/composer/composer/installed.php
  apps/sharebymail/composer/composer/InstalledVersions.php
  apps/sharebymail/composer/composer/installed.php
  apps/systemtags/composer/composer/InstalledVersions.php
  apps/systemtags/composer/composer/installed.php
  apps/testing/composer/composer/InstalledVersions.php
  apps/testing/composer/composer/installed.php
  apps/twofactor_backupcodes/composer/composer/InstalledVersions.php
  apps/twofactor_backupcodes/composer/composer/installed.php
  apps/updatenotification/composer/composer/InstalledVersions.php
  apps/updatenotification/composer/composer/installed.php
  apps/user_ldap/composer/composer/InstalledVersions.php
  apps/user_ldap/composer/composer/installed.php
  apps/user_status/composer/composer/InstalledVersions.php
  apps/user_status/composer/composer/installed.php
  apps/workflowengine/composer/composer/InstalledVersions.php
  apps/workflowengine/composer/composer/installed.php
Labels: 4. to release

#29536 Fix missing calendar path for public write on Calendars
  apps/dav/lib/CalDAV/CalendarImpl.php
  build/psalm-baseline.xml
Labels: bug, 4. to release, feature: dav, integration

#29545 Disable unsupported scopes for new account properties
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/shared/FederationControl.vue
  apps/settings/src/constants/AccountPropertyConstants.js
Labels: bug, 3. to review, feature: settings, feature: profile

#25332 Fix removing remote shares when the remote server is unreachable
  build/integration/features/bootstrap/FederationContext.php
  build/integration/federation_features/federated.feature
  build/integration/run.sh
  build/psalm-baseline.xml
  lib/private/Files/Storage/Wrapper/Availability.php
Labels: bug, 3. to review, feature: sharing, feature: federation, backport-request

#29594 Force Calendar Object Change Path to support public write
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/Schedule/Plugin.php
Labels: bug, 4. to release, feature: dav

#29592 Handle empty directory drag-and-drop in Files UI
  apps/files/js/file-upload.js
  apps/files/js/jquery.fileupload.js
Labels: enhancement, 3. to review, feature: files

#29559 Respect user enumeration settings on profile
  apps/files_sharing/tests/CapabilitiesTest.php
  core/Controller/ProfilePageController.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  tests/lib/Share20/ManagerTest.php
Labels: enhancement, 4. to release, privacy, feature: profile

#29611 Show most recently deleted files first in trash can
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/lib/Trash/TrashManager.php
  apps/files_trashbin/src/filelist.js
  apps/files_trashbin/tests/js/filelistSpec.js
Labels: bug, feature: trashbin

#29522 Make sure trusted_proxies is an array
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
Labels: bug, 4. to release, backport-request, feature: settings

#29484 Use unique combination of hostname/bucket/key for external storages
  apps/files_external/appinfo/info.xml
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  apps/files_external/lib/Migration/Version1015Date20211104103506.php
Labels: bug, 3. to review

#29627 20.0.14
  version.php
Labels: 3. to review

#29626 21.0.6
  version.php
Labels: 3. to review

#29624 22.2.1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review

#29595 23.0.0 RC1
  version.php
Labels: 3. to review, overview

#29648 Master is now 24
  .github/dependabot.yml
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 4. to release, technical debt

#29663 Fix loading all principal calendars in the dav app calendar provider
  apps/dav/lib/CalDAV/CalendarProvider.php
Labels: bug, 4. to release, feature: dav, backport-request, integration

#29677 Fix video verification tests
  .drone.yml
Labels: bug, 4. to release

#29682 Fix missing token update
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 3. to review, backport-request, feature: authentication, regression, performance 🚀

#29686 23.0.0 RC2
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review

#29687 22.2.2
  version.php
Labels: 3. to review

#29661 Document and type allowed property names for calendar property searches
  apps/dav/lib/CalDAV/CalDavBackend.php
  lib/public/Calendar/ICalendarQuery.php
Labels: enhancement, 4. to release

#29701 [stable23] Fix branch selection
  .codecov.yml
  README.md
  build/update-apps.sh
  build/update.sh
  tests/acceptance/run-local.sh
Labels: bug, 3. to review

#29679 don't flash external storage mountpoints during the status check
  apps/files_external/css/external.css
  apps/files_external/js/statusmanager.js
Labels: enhancement, 3. to review, feature: external storage, backport-request, feature: files

#29720 22.2.3
  version.php
Labels: 4. to release

#29721 21.0.7
  version.php
Labels: 4. to release

#29683 Fix core depending on theming app
  lib/private/Template/SCSSCacher.php
Labels: bug, 3. to review, backport-request, regression

#29695 Fix missing setlocale with php 8
  lib/private/legacy/OC_Util.php
  tests/lib/UtilTest.php
Labels: bug, 4. to release, backport-request

#29734 Fixed grammar
  apps/files_external/templates/settings.php
Labels: feature: language l10n and translations

#29662 [stable23] Document allowed property names for calendar property searches
  lib/public/Calendar/ICalendarQuery.php
Labels: bug, 3. to review, feature: dav, integration

#29747 Allow to serve static WebAssembly and TensorFlow Lite files
  .htaccess
  lib/private/Setup.php
Labels: bug, 3. to review, backport-request

#29752 Explicitly allow access on some (public) routes also without 2FA
  core/Controller/OCJSController.php
  core/Middleware/TwoFactorMiddleware.php
Labels: 3. to review, pending documentation

#29760 [stable23] Explicitly allow some routes without 2FA
  core/Controller/OCJSController.php
  core/Middleware/TwoFactorMiddleware.php
Labels: 3. to review

#29766 23 RC 3
  version.php
Labels: 3. to review

#29784 App summary is optional
  apps/theming/lib/Controller/ThemingController.php
Labels: bug, 4. to release, backport-request

#29605 Normalize file name before existence check in scanner
  apps/files/lib/Command/Scan.php
  apps/files/lib/Command/ScanAppData.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/EncodingDirectoryWrapper.php
  lib/private/Files/Utils/Scanner.php
  tests/lib/Files/Storage/Wrapper/EncodingTest.php
Labels: bug, 3. to review, feature: external storage

#29788 Fix doc link in sharing settings
  apps/settings/templates/settings/admin/sharing.php
Labels: 4. to release, backport-request, regression

#29758 Check for `disk_free_space`
  lib/private/Files/Storage/Local.php
Labels: bug, 3. to review, backport-request

#29632 fix imagecreatetruecolor() error
  lib/private/legacy/OC_Image.php
Labels: bug, 3. to review, feature: previews and thumbnails

#29622 Implement multibucket shift for ObjectStore
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/ObjectStore/Mapper.php
  tests/lib/Files/Mount/ObjectHomeMountProviderTest.php
  tests/lib/Files/ObjectStore/MapperTest.php
Labels: enhancement, 3. to review, backport-request, feature: object storage

#29708 Do not print verbose info about app updates if there are none
  core/Command/Upgrade.php
  core/ajax/update.php
  lib/private/Updater.php
Labels: 3. to review, backport-request

#29567 Improve sorting of profile visibility dropdowns
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/ProfileVisibilitySection.vue
Labels: enhancement, 3. to review, papercut, feature: profile

#29544 Fix wording on profile page
  core/js/dist/profile.js
  core/js/dist/profile.js.map
  core/src/views/Profile.vue
Labels: enhancement, 3. to review, feature: profile

#29628 [stable22] Show most recently deleted files first in trash can
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/lib/Trash/TrashManager.php
  apps/files_trashbin/src/filelist.js
  apps/files_trashbin/tests/js/filelistSpec.js
Labels: bug, 3. to review, feature: trashbin

#29629 [stable21] Show most recently deleted files first in trash can
  apps/files_trashbin/js/files_trashbin.js
  apps/files_trashbin/js/files_trashbin.js.map
  apps/files_trashbin/lib/Trash/TrashManager.php
  apps/files_trashbin/src/filelist.js
  apps/files_trashbin/tests/js/filelistSpec.js
Labels: bug, 3. to review, feature: trashbin

#29836 Make sure mapping cache is cleared when deleting a user
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/tests/Mapping/AbstractMappingTest.php
Labels: 3. to review

#29835 Fix getting subnet of ipv4 mapped ipv6 addresses
  lib/private/Security/Normalizer/IpAddress.php
  tests/lib/Security/Normalizer/IpAddressTest.php
Labels: 3. to review, backport-request

#29833 make profile page usable on mobile
  core/js/dist/profile.js
  core/js/dist/profile.js.map
  core/src/views/Profile.vue
Labels: bug, design, 4. to release, backport-request

#29763 [stable22] Explicitly allow some routes without 2FA
  core/Controller/OCJSController.php
  core/Middleware/TwoFactorMiddleware.php
Labels: 3. to review

#29791 Fix multiple bugs with user status
  apps/user_status/js/user-status-menu.js
  apps/user_status/js/user-status-menu.js.map
  apps/user_status/js/user-status-modal.js
  apps/user_status/js/user-status-modal.js.map
  apps/user_status/lib/Controller/StatusesController.php
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/src/components/SetStatusModal.vue
Labels: 4. to release, backport-request

#29610 Get rid of user_ldap LogWrapper and use LoggerInterface
  apps/user_ldap/ajax/wizard.php
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/composer/composer/installed.php
  apps/user_ldap/lib/LogWrapper.php
  apps/user_ldap/lib/Proxy.php
  apps/user_ldap/lib/User/Manager.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/Integration/AbstractIntegrationTest.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserAvatar.php
  apps/user_ldap/tests/User/ManagerTest.php
  apps/user_ldap/tests/User/UserTest.php
Labels: 3. to review, feature: ldap, technical debt, standardisation, php

#29864 Allow to fetch the creation time of folders
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
Labels: bug, 3. to review, feature: dav, backport-request

#29869 Hide user status on profile from public
  core/Controller/ProfilePageController.php
Labels: bug, 3. to review, backport-request, privacy, feature: profile

#29764 [stable21] Explicitly allow some routes without 2FA
  core/Controller/OCJSController.php
  core/Middleware/TwoFactorMiddleware.php
Labels: 3. to review

#29826 Personalsettings - fix marginLeft as it breaks the layout
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/ProfileVisibilitySection.vue
Labels: bug, design, 4. to release, backport-request

#29895 Check for invalid characters before trimming
  build/integration/features/bootstrap/WebDav.php
  build/integration/features/webdav-related.feature
  lib/private/Files/Storage/Common.php
Labels: bug, 3. to review, feature: filesystem

#29902 [stable22] Check for invalid characters before trimming
  build/integration/features/bootstrap/WebDav.php
  build/integration/features/webdav-related.feature
  lib/private/Files/Storage/Common.php
Labels: bug, 3. to review, feature: filesystem, backport-request

#29837 Ignore cache in occ ldap:check-ldap command
  apps/user_ldap/lib/Command/CheckUser.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
Labels: 3. to review

#29894 Fix inactive profile parameters being displayed in the Profile visibility section
  lib/private/Profile/ProfileManager.php
Labels: bug, 3. to review, backport-request, feature: settings, feature: profile

#29891 Adjust margin of user status on profile
  core/js/dist/profile.js
  core/js/dist/profile.js.map
  core/src/views/Profile.vue
Labels: design, 3. to review, backport-request, feature: profile

#29906 Use strict comparison to detect usage of redis cluster
  lib/private/RedisFactory.php
Labels: bug, 3. to review, backport-request, feature: caching

#29893 Improve accessibility for personal info settings and profile
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/BiographySection/Biography.vue
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/ProfileSection/EditProfileAnchorLink.vue
  apps/settings/src/components/PersonalInfo/ProfileSection/ProfilePreviewCard.vue
  apps/settings/src/components/PersonalInfo/shared/AddButton.vue
  apps/settings/src/components/PersonalInfo/shared/FederationControl.vue
  core/js/dist/profile.js
  core/js/dist/profile.js.map
  core/src/components/Profile/PrimaryActionButton.vue
  core/src/views/Profile.vue
Labels: enhancement, 3. to review, backport-request, feature: accessibility, feature: profile

#29871 Set number of visibility dropdown rows dynamically
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/ProfileVisibilitySection.vue
Labels: enhancement, design, 3. to review, backport-request, feature: settings, feature: profile

#29926 obey accounts_data column length when inserting and searching
  lib/private/Accounts/AccountManager.php
  lib/public/Util.php
  tests/lib/UtilTest.php
Labels: bug, 4. to release, backport-request, feature: profile

#29925 23.0.0
  apps/settings/templates/settings/admin/overview.php
  version.php
Labels: 4. to release

#29919 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#29470 Avoid use of iconv to get rid of unicode
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/AccessTest.php
Labels: 3. to review, feature: ldap

#29868 Add Drone php8.0 pipelines for MariaDB10.4, MySQL8, PGSQL13
  .drone.yml
Labels: 3. to review

#29830 Add Psalm specific scope type hint for the WFE operation
  lib/public/WorkflowEngine/IOperation.php
Labels: enhancement, 3. to review, feature: workflows

#29951 Interpolate the log message also for logged exceptions
  lib/private/Log.php
Labels: bug, 3. to review, backport-request

#29955 Delete update-psalm-baseline.yml
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#29917 Fix source of translations
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/Contacts/ContactsMenu/Providers/ProfileProvider.php
  lib/private/Profile/Actions/EmailAction.php
  lib/private/Profile/Actions/PhoneAction.php
  lib/private/Profile/Actions/TwitterAction.php
  lib/private/Profile/Actions/WebsiteAction.php
  lib/private/Profile/ProfileManager.php
Labels: bug, 3. to review, backport-request, feature: settings, feature: language l10n and translations, feature: profile

#29870 Prevent your own status from replacing another user's status on profile
  core/js/dist/profile.js
  core/js/dist/profile.js.map
  core/src/views/Profile.vue
Labels: bug, 4. to release, backport-request, feature: profile

#29872 Set profile page title
  core/js/dist/profile.js
  core/js/dist/profile.js.map
  core/src/views/Profile.vue
Labels: enhancement, 3. to review, backport-request, feature: profile

#29974 Let repair step query exceptions bubble up
  lib/private/Repair.php
Labels: bug, 3. to review, backport-request, feature: install and update, feature: apps management

#29670 Update npm and node engines versions
  package.json
Labels: 4. to release, dependencies

#29958 Remove iconv from dependencies and tests
  .github/workflows/oci.yml
  .github/workflows/s3-external.yml
  .github/workflows/update-psalm-baseline.yml
  lib/private/App/PlatformRepository.php
  lib/private/legacy/OC_Util.php
Labels: 3. to review, backport-request, pending documentation
