Repository nextcloud/server, pull requests merged in 2021-07, with the labels that each got.

#26681 Move HintException to OCP
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/federatedfilesharing/lib/AddressHandler.php
  apps/federatedfilesharing/lib/Controller/MountPublicLinkController.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Notifications.php
  apps/federatedfilesharing/lib/Notifier.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  apps/federatedfilesharing/tests/AddressHandlerTest.php
  apps/federatedfilesharing/tests/Controller/MountPublicLinkControllerTest.php
  apps/federation/lib/Controller/SettingsController.php
  apps/federation/lib/DbHandler.php
  apps/federation/lib/Middleware/AddServerMiddleware.php
  apps/federation/lib/TrustedServers.php
  apps/federation/tests/Controller/SettingsControllerTest.php
  apps/federation/tests/Middleware/AddServerMiddlewareTest.php
  apps/federation/tests/TrustedServersTest.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/lib/Controller/ChangePasswordController.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Controller/RenewPasswordController.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/User_LDAPTest.php
  core/Controller/LostController.php
  index.php
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/App.php
  lib/private/Config.php
  lib/private/DatabaseSetupException.php
  lib/private/HintException.php
  lib/private/Installer.php
  lib/private/Log/ExceptionSerializer.php
  lib/private/Log/Systemdlog.php
  lib/private/Memcache/Factory.php
  lib/private/Memcache/Memcached.php
  lib/private/Setup.php
  lib/private/Share20/Manager.php
  lib/private/Updater.php
  lib/private/User/Manager.php
  lib/private/legacy/OC_Hook.php
  lib/private/legacy/OC_Util.php
  lib/public/Encryption/Exceptions/GenericEncryptionException.php
  lib/public/Federation/Exceptions/ActionNotSupportedException.php
  lib/public/Federation/Exceptions/AuthenticationFailedException.php
  lib/public/Federation/Exceptions/BadRequestException.php
  lib/public/Federation/Exceptions/ProviderAlreadyExistsException.php
  lib/public/Federation/Exceptions/ProviderCouldNotAddShareException.php
  lib/public/Federation/Exceptions/ProviderDoesNotExistsException.php
  lib/public/Files/StorageNotAvailableException.php
  lib/public/HintException.php
  lib/public/Share/Exceptions/GenericShareException.php
  tests/Core/Controller/ChangePasswordControllerTest.php
  tests/lib/Memcache/FactoryTest.php
  tests/lib/Share20/ManagerTest.php
  tests/lib/User/DatabaseTest.php
Labels: 3. to review, technical debt

#27739 design fixes to app-settings button
  core/css/apps.scss
Labels: 3. to review, design, enhancement

#27706 22.0.0 RC2
  version.php
Labels: 3. to review, enhancement

#27707 21.0.3
  version.php
Labels: 3. to review, enhancement

#27708 20.0.11
  version.php
Labels: 3. to review, enhancement

#27709 19.0.13
  version.php
Labels: 3. to review, enhancement

#27742 Clarify that federated sharing settings may also affect shares between users on the current instanc
  apps/federatedfilesharing/templates/settings-admin.php
Labels: 4. to release, feature: federation

#27737 make contactsmenu icon bigger
  core/css/styles.scss
Labels: 3. to review, backport-request, design, enhancement

#27586 Reset checksum when writing files to object store
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 4. to release, backport-request, bug, feature: object storage

#27533 Fix scanner mistaking socket files for directories
  lib/private/Files/Storage/Local.php
Labels: 3. to review, bug

#17148 Always provide theme color for default personal calendar
  apps/dav/lib/HookManager.php
  apps/dav/tests/unit/DAV/HookManagerTest.php
Labels: 4. to release, feature: dav, feature: theming

#27771 Add connection check in autotest.sh for pgsql docker
  autotest.sh
Labels: 3. to review, bug

#27750 dont include folder being search in in the results
  lib/private/Files/Node/Folder.php
Labels: 3. to review, backport-request

#27198 Run s3 tests again
  .drone.yml
  tests/drone-wait-objectstore.sh
  tests/lib/Files/ObjectStore/S3Test.php
  tests/preseed-config.php
Labels: 3. to review, backport-request, feature: object storage

#27810 Add a text string to l10n
  core/templates/loginflow/authpicker.php
  core/templates/loginflowv2/authpicker.php
Labels: backport-request

#27796 Check that pdo is installed
  lib/private/Setup.php
Labels: 3. to review, bug

#27758 Fix DnsPinMiddleware resolve pinning bug
  lib/private/Http/Client/DnsPinMiddleware.php
Labels: 3. to review, backport-request, bug

#27799 Throw exception if encrypting the data failed.
  lib/private/Security/Crypto.php
Labels: 3. to review, bug

#27767 Improve maintenance mode info
  lib/private/Console/Application.php
Labels: 3. to review, enhancement, feature: occ

#27794 Clarify that lazy event listeners are built from the server container
  lib/private/EventDispatcher/ServiceEventListener.php
Labels: 4. to release

#27813 22.0.0
  version.php
Labels: 3. to review

#27818 Fix in locking cache check
  lib/private/Memcache/Factory.php
Labels: 3. to review, bug

#27801 Ignore subdomain for soa queries
  lib/private/Http/Client/DnsPinMiddleware.php
Labels: 3. to review, backport-request, enhancement

#27827 add singular and plural in for days in admin sharing settings
  apps/settings/templates/settings/admin/sharing.php
Labels: 3. to review, enhancement, feature: language l10n and translations, feature: settings, feature: sharing

#27830 Refactor getEncryptionModule routine
  lib/private/Encryption/Manager.php
Labels: 3. to review

#27848 Fixes recursion count incrementation
  lib/private/Http/Client/DnsPinMiddleware.php
Labels: 3. to review, backport-request, bug, feature: install and update

#27844 Make search popup usable on mobile, too
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/components/HeaderMenu.vue
Labels: 3. to review, design, enhancement, feature: search

#27835 Cache images on browser
  .htaccess
Labels: 4. to release, backport-request

#27845 Use proper "Share to Diaspora" URL
  apps/federatedfilesharing/templates/settings-personal.php
Labels: 3. to review

#27864 Fix add group button
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-users-7f4f43139d7b1af5f465.js
  apps/settings/js/vue-settings-users-7f4f43139d7b1af5f465.js.map
  apps/settings/js/vue-settings-users-b9836024eef7aa79cd9f.js
  apps/settings/js/vue-settings-users-b9836024eef7aa79cd9f.js.map
  apps/settings/src/views/Users.vue
Labels: 3. to review, backport-request, bug

#27847 Update "Sending password by Nextcloud Talk failed" sentence
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: 3. to review, enhancement, feature: language l10n and translations

#27878 [stable22] Fix add group button
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-users-8a973f1b2b78e43a05ac.js
  apps/settings/js/vue-settings-users-8a973f1b2b78e43a05ac.js.map
  apps/settings/js/vue-settings-users-af6707a7ab3e065b4b6e.js
  apps/settings/js/vue-settings-users-af6707a7ab3e065b4b6e.js.map
  apps/settings/src/views/Users.vue
Labels: 3. to review, bug

#27854 Fix dark theme on public link shares
  apps/accessibility/js/accessibilityoca.js
  apps/accessibility/js/accessibilityoca.js.map
  apps/accessibility/lib/AppInfo/Application.php
  apps/accessibility/lib/Service/JSDataService.php
  apps/accessibility/src/accessibilityoca.js
  core/templates/filepicker.html
Labels: 4. to release, backport-request, bug, design, feature: accessibility, feature: sharing, feature: theming

#27887 make user status usable on mobile
  apps/user_status/js/user-status-menu.js
  apps/user_status/js/user-status-menu.js.map
  apps/user_status/js/user-status-modal.js
  apps/user_status/js/user-status-modal.js.map
  apps/user_status/src/components/ClearAtSelect.vue
  apps/user_status/src/components/SetStatusModal.vue
Labels: 3. to review, design, enhancement, feature: status

#27922 Check if dns_get_record returns non-false
  lib/private/Http/Client/DnsPinMiddleware.php
Labels: 3. to review, backport-request

#27915 Fix Psalm code scanning alerts
  apps/theming/lib/IconBuilder.php
Labels: 3. to review, php

#26728 Wrong warning when running HTTP instance
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#27852 Allow casting query functions
  lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/PgSqlExpressionBuilder.php
  lib/public/DB/QueryBuilder/IExpressionBuilder.php
  tests/lib/DB/QueryBuilder/ExpressionBuilderDBTest.php
Labels: 3. to review, backport-request, bug

#27631 Correctly skip suppressed errors in PHP 8.0
  lib/private/Log/ErrorHandler.php
Labels: 4. to release, bug

#27880 Make integrity commands verbose
  core/Command/Integrity/CheckApp.php
  core/Command/Integrity/CheckCore.php
Labels: 3. to review, technical debt

#27867 fix newfileMenu on public page
  apps/files/css/files.scss
Labels: 3. to review, design, feature: files, feature: sharing

#27912 Do not escape display name in dashboard welcome text
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/App.vue
Labels: 4. to release, backport-request, enhancement, feature: dashboard

#27936 Fix svg icons disapearing in app navigation when text overflows
  core/css/apps.scss
Labels: 3. to review, enhancement, feature: settings

#27946 Show registered breadcrumb detail views in breadcrumb menu
  apps/files/js/breadcrumb.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/src/sharebreadcrumbview.js
Labels: 4. to release, enhancement, feature: files

#27959 Revert "Update guzzlehttp/guzzle requirement from 6.5.2 to 7.3.0 in /build/integration"
  build/integration/composer.json
Labels: 3. to review, bug

#27761 Also hide group from direct matches
  lib/private/Collaboration/Collaborators/GroupPlugin.php
Labels: 3. to review, backport-request, bug, feature: users and groups

#27938 [stable22] Correctly skip suppressed errors in PHP 8.0
  lib/private/Log/ErrorHandler.php
Labels: 3. to review, bug

#27875 No limit in the number of group shares
  apps/files_sharing/lib/Listener/UserAddedToGroupListener.php
Labels: 3. to review

#27939 [stable21] Correctly skip suppressed errors in PHP 8.0
  lib/private/Log/ErrorHandler.php
Labels: 3. to review, bug

#27952 [Accessibility App]: Remove unused parameters in settings class
  apps/accessibility/lib/Settings/Personal.php
Labels: 3. to review

#27973 Fix regression in file sidebar
  core/css/apps.scss
Labels: 4. to release, backport-request

#27970 [stable20] Show registered breadcrumb detail views in breadcrumb menu
  apps/files/js/breadcrumb.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/src/sharebreadcrumbview.js
Labels: 4. to release, bug, feature: files

#27913 [stable20] Do not escape display name in dashboard welcome text
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/App.vue
Labels: 3. to review, enhancement, feature: dashboard

#27884 Allow to get a local cloud id without going through the contacts manager
  apps/federatedfilesharing/tests/AddressHandlerTest.php
  apps/federatedfilesharing/tests/Controller/MountPublicLinkControllerTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/files_sharing/tests/External/CacheTest.php
  apps/files_sharing/tests/External/ManagerTest.php
  lib/private/Federation/CloudIdManager.php
  lib/private/Server.php
  lib/private/User/User.php
  lib/public/Federation/ICloudIdManager.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/RemotePluginTest.php
  tests/lib/Federation/CloudIdManagerTest.php
Labels: 3. to review, performance 🚀

#26463 Fix S3 ObjectStore proxy option
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
Labels: 3. to review, bug

#27967 [stable21] Show registered breadcrumb detail views in breadcrumb menu
  apps/files/js/breadcrumb.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/src/sharebreadcrumbview.js
Labels: 4. to release, bug, feature: files

#27966 [stable22] Show registered breadcrumb detail views in breadcrumb menu
  apps/files/js/breadcrumb.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/src/sharebreadcrumbview.js
Labels: 4. to release, bug, feature: files

#27980 Improve notcreatable permissions hint
  apps/files/css/files.scss
  apps/files/templates/list.php
  core/css/icons.scss
  core/img/actions/alert-outline.svg
Labels: 4. to release, design, enhancement, feature: files

#27997 Update CRL due to revoked twofactor_nextcloud_notification.crt
  resources/codesigning/root.crl
Labels: 3. to review

#27860 Introduce ISecureRandom::CHAR_ALPHANUMERIC
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/Controller/DirectController.php
  apps/dav/tests/unit/Controller/DirectControllerTest.php
  apps/encryption/lib/Crypto/EncryptAll.php
  apps/federatedfilesharing/lib/TokenHandler.php
  apps/federatedfilesharing/tests/TokenHandlerTest.php
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/settings/lib/Mailer/NewUserMailHelper.php
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  lib/private/AppFramework/Http/Request.php
  lib/private/Cache/File.php
  lib/private/Setup/MySQL.php
  lib/private/Setup/PostgreSQL.php
  lib/public/Security/ISecureRandom.php
Labels: 3. to review, security

#27995 some multiselect design fixes
  apps/files/css/files.scss
  core/css/styles.scss
Labels: 4. to release, design, enhancement, feature: files

#27994 Increase footer height for longer menus
  apps/files/css/files.scss
Labels: 3. to review, backport-request, design, enhancement, feature: files

#28046 Add titleTooltip to sidebar
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/views/Sidebar.vue
Labels: 3. to review, backport-request, enhancement, feature: file sidebar

#28051 Mask password for Redis and RedisCluster on connection failure
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review, bug

#27950 Fix missing theming for login button
  apps/theming/css/theming.scss
Labels: 3. to review

#28011 [stable22] some multiselect design fixes
  apps/files/css/files.scss
  core/css/styles.scss
Labels: 4. to release, design, enhancement, feature: files

#28057 Improve Emails UX
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
Labels: 4. to release, backport-request, enhancement

#28015 fix overlapping of elements in certain views
  apps/files/css/files.scss
Labels: 3. to review, design, enhancement, feature: files

#28071 [stable22] Improve Emails UX
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
Labels: 3. to review, enhancement

#28077 Disable HEIC image preview provider for performance concerns
  config/config.sample.php
  lib/private/PreviewManager.php
Labels: backport-request

#28078 Improve provider check
  core/Middleware/TwoFactorMiddleware.php
Labels: 3. to review, backport-request

#28082 Sanitize more functions from the encryption app
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review, backport-request

#27674 hide download button for public preview of audio files
  apps/files_sharing/templates/public.php
Labels: 4. to release, backport-request

#28092 QuotaPlugin expect 1 parameter
  apps/dav/lib/Server.php
Labels: 3. to review, technical debt

#28107 l10n: HTTP in capital letters
  apps/provisioning_api/appinfo/info.xml
Labels: 3. to review

#28101 Fix dark theme in file exists dialog
  apps/files/css/upload.scss
Labels: 4. to release, backport-request, bug, design

#27888 Support redis user password auth and tls encryption
  .drone.yml
  build/psalm-baseline.xml
  build/stubs/redis.php
  build/stubs/redis_cluster.php
  config/config.sample.php
  lib/private/RedisFactory.php
Labels: 4. to release, enhancement, feature: caching

#28122 Let memory limit set in tests fit the used amount
  tests/lib/MemoryInfoTest.php
Labels: 3. to review, backport-request

#28084 Make sure that the dav propfind plugins always use the proper user id
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/FilesPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/FilesReportPluginTest.php
Labels: 4. to release, backport-request, bug

#27968 Remove allmost all deprecation from the files_version app
  apps/files_versions/lib/AppInfo/Application.php
  apps/files_versions/lib/Command/Expire.php
  apps/files_versions/lib/Controller/PreviewController.php
  apps/files_versions/lib/Events/CreateVersionEvent.php
  apps/files_versions/lib/Expiration.php
  apps/files_versions/lib/Hooks.php
  apps/files_versions/lib/Sabre/Plugin.php
  apps/files_versions/lib/Sabre/RootCollection.php
  apps/files_versions/lib/Sabre/VersionCollection.php
  apps/files_versions/lib/Sabre/VersionRoot.php
  apps/files_versions/lib/Storage.php
Labels: 3. to review

#28129 Allow empty Redis config
  lib/private/RedisFactory.php
Labels: 4. to release, backport-request, bug, regression

#28133 add an option to the multiple files selected actions to add and remov…
  apps/files/css/files.scss
  apps/files/js/app.js
  apps/files/js/filelist.js
Labels: 4. to release, backport-request, enhancement, feature: files, feature: tags

#28132 Fix tests in files_versions
  apps/files_versions/tests/Controller/PreviewControllerTest.php
  apps/files_versions/tests/ExpirationTest.php
Labels: 3. to review, bug

#28075 Admin Audit - Sharing: createShare - report the full path
  apps/admin_audit/lib/Actions/Sharing.php
  lib/private/Share20/LegacyHooks.php
  tests/lib/Share20/LegacyHooksTest.php
Labels: 3. to review, enhancement, feature: admin audit

#28164 Fix sort function of files multiple selection actions
  apps/files/js/filelist.js
Labels: 3. to review, backport-request, bug, feature: files

#28166 User management - Add icon to user groups
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-users-f5481c8d25fb5a2d7c1f.js
  apps/settings/js/vue-settings-users-f5481c8d25fb5a2d7c1f.js.map
  apps/settings/src/views/Users.vue
Labels: 3. to review, backport-request, design, enhancement, feature: users and groups

#28173 Fix variable override in file view
  apps/files/lib/Controller/ViewController.php
Labels: 3. to review, bug

#27729 [stable21] Revert "Fix constraint violation detection in QB Mapper"
  lib/public/AppFramework/Db/QBMapper.php
Labels: 3. to review, bug, regression

#27992 Manual backport of "No limit in the number of group shares" #27875
  apps/files_sharing/lib/Listener/UserAddedToGroupListener.php
Labels: 3. to review

#27886 Keep pw based auth tokens valid when pw-less login happens
  lib/private/Authentication/Listeners/UserLoggedInListener.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: 3. to review, bug, feature: authentication

#27893 Fix comments file action sidebar opening
  apps/comments/js/comments.js
  apps/comments/js/comments.js.map
  apps/comments/src/filesplugin.js
  apps/comments/tests/js/filespluginSpec.js
Labels: 4. to release, bug, feature: comments

#27751 Extend pending shares list in frontend to include remote shares
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  apps/files/js/fileactions.js
  apps/files/js/gotoplugin.js
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/sharedfilelist.js
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/lib/Hooks.php
  apps/files_sharing/src/share.js
  apps/files_sharing/tests/External/ManagerTest.php
Labels: 3. to review, enhancement, feature: federation

#28174 Set openfile params when following internal links
  apps/files/lib/Controller/ViewController.php
Labels: 4. to release, enhancement, feature: files

#28218 Revert accidentally dropped lines from Psalm baselines
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, regression

#28214 Fix missing exception class import
  lib/public/AppFramework/Db/QBMapper.php
Labels: 4. to release, bug

#28210 Allow to disable group membership change notification
  apps/settings/lib/Activity/GroupSetting.php
Labels: 3. to review, enhancement

#27920 Fix Files breadcrumbs being hidden even if there is enough space
  apps/files/js/breadcrumb.js
Labels: 3. to review, backport-request, bug, feature: files

#28161 22.1.0 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review, enhancement

#28175 dont apply jail search filter is on the root
  lib/private/Files/Cache/Wrapper/CacheJail.php
  tests/lib/Files/Cache/Wrapper/CacheJailTest.php
Labels: 4. to release, backport-request

#28202 Fix CI failures when building settings app
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-0cc652a346b119349872.js.map
  apps/settings/js/vue-settings-apps-369074b0c04241a9da7c.js
  apps/settings/js/vue-settings-apps-369074b0c04241a9da7c.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users-8c3f890ced94fe52c9e9.js.map
  apps/settings/js/vue-settings-users-911fdc3448ebf18dc7a8.js
  apps/settings/js/vue-settings-users-911fdc3448ebf18dc7a8.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps-3ddb1330e314bc7d85d7.js
  apps/settings/js/vue-vendors-settings-apps-3ddb1330e314bc7d85d7.js.map
  apps/settings/js/vue-vendors-settings-apps-da92959d79ce3c305f02.js
  apps/settings/js/vue-vendors-settings-apps-da92959d79ce3c305f02.js.map
  apps/settings/js/vue-vendors-settings-apps-dd124175230f710dfe88.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users-430eadadf531ef99f517.js
  apps/settings/js/vue-vendors-settings-apps-settings-users-430eadadf531ef99f517.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users-cdfd35d6285d826aa311.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users.js
  apps/settings/js/vue-vendors-settings-apps-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps.js
  apps/settings/js/vue-vendors-settings-apps.js.map
  apps/settings/js/vue-vendors-settings-users-e8590d3870fc8df05e65.js
  apps/settings/js/vue-vendors-settings-users-e8590d3870fc8df05e65.js.map
  apps/settings/js/vue-vendors-settings-users-e93b5a6a8e87ef8bc099.js.map
  apps/settings/js/vue-vendors-settings-users.js
  apps/settings/js/vue-vendors-settings-users.js.map
  apps/settings/webpack.js
Labels: 3. to review

#28191 [stable20] Fix variable override in file view
  apps/files/lib/Controller/ViewController.php
Labels: 3. to review, backport-request, bug

#28159 20.0.12 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review, enhancement

#28192 [stable21] Fix variable override in file view
  apps/files/lib/Controller/ViewController.php
Labels: 3. to review, backport-request, bug

#28238 Fix missing label of Search function
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/components/HeaderMenu.vue
  core/src/views/UnifiedSearch.vue
Labels: 3. to review, backport-request, bug, design, feature: accessibility

#28242 Add missing order attribute to tag multiselect action
  apps/files/js/app.js
Labels: 3. to review, backport-request, bug, feature: files

#28240 Add h2 to personal info page, fixing accessibility issue
  apps/settings/templates/settings/personal/personal.info.php
Labels: 3. to review, backport-request, bug, design, feature: accessibility, feature: settings

#28009 Add quota restrictions options
  apps/provisioning_api/lib/Controller/AppConfigController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/lib/Controller/UsersController.php
  apps/settings/src/components/UserList.vue
  apps/settings/src/views/Users.vue
  lib/private/User/User.php
  tests/lib/User/UserTest.php
Labels: 3. to review, backport-request, enhancement, feature: files, feature: settings, pending documentation

#27764 Extend caldav resource search
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
Labels: 3. to review, enhancement

#28259 Check that php was compiled with argon2 support or that the php-sodium extensions is installed
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 3. to review, enhancement

#28260 fix UserController tests
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 3. to review, bug, feature: files, technical debt
