Repository nextcloud/server, pull requests merged in 2021-06, with the labels that each got.

#27311 Fix loading of delete caldav objet URIs
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, feature: dav, regression

#25658 Dav respect disallow sharing with groups
  apps/dav/lib/DAV/GroupPrincipalBackend.php
  apps/dav/tests/unit/DAV/GroupPrincipalTest.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/tests/Controller/ShareesAPIControllerTest.php
  lib/private/Collaboration/Collaborators/GroupPlugin.php
  tests/lib/Collaboration/Collaborators/GroupPluginTest.php
Labels: 4. to release, bug, php

#27317 l10n: Split sentences
  apps/user_ldap/js/wizard/wizardTabLoginFilter.js
Labels: feature: language l10n and translations

#27331 Add mbstring dependency
  composer.json
  composer.lock
  lib/composer/composer/InstalledVersions.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/installed.php
Labels: 3. to review, technical debt

#27328 emit UserLoggedInEvent on apache auth
  lib/private/legacy/OC_User.php
Labels: 4. to release, backport-request, bug, feature: authentication

#27316 Fix populating the array and closing the cursors
  lib/private/Comments/Manager.php
Labels: 3. to review, bug

#27327 [Fast Review] Fix grammar
  apps/admin_audit/lib/Actions/Sharing.php
Labels: 3. to review

#27329 Propagate throttling on OCS response
  lib/private/AppFramework/OCS/BaseResponse.php
Labels: 3. to review, backport-request

#27291 l10n: Correct spelling
  apps/settings/templates/settings/admin/additional-mail.php
Labels: 3. to review, enhancement, feature: language l10n and translations

#27053 Don't throw when comments is disabled
  lib/private/Comments/Manager.php
Labels: 4. to release, backport-request, bug, feature: comments

#27343 Add missing ACLs for deleted calendar objects to fix deletion
  apps/dav/lib/CalDAV/Trashbin/DeletedCalendarObject.php
  apps/dav/lib/CalDAV/Trashbin/DeletedCalendarObjectsCollection.php
Labels: 4. to release, bug, feature: dav

#26792 better cleanup of user files on user deletion
  core/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Listeners/UserDeletedFilesCleanupListener.php
  lib/private/Files/Storage/Common.php
  lib/private/User/User.php
  tests/lib/User/UserTest.php
Labels: 4. to release

#27265 Replace proposal-class-private-properties by regular properties
  apps/files/js/dist/files-app-settings.js
  apps/files/js/dist/files-app-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/src/models/Setting.js
  apps/files/src/models/Tab.js
  apps/files/src/services/Settings.js
  apps/files/src/services/Sidebar.js
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/services/ExternalLinkActions.js
  apps/files_sharing/src/services/ShareSearch.js
  apps/files_sharing/src/services/TabSections.js
Labels: 4. to release, bug

#27352 Fix translation phpunit test
  apps/settings/tests/Controller/CheckSetupControllerTest.php
Labels: 3. to review, bug, feature: language l10n and translations

#24295 First attempt to check against core routes before loading all app routes
  lib/private/Route/Router.php
Labels: 3. to review, performance 🚀

#27088 Allow removing apps with app store disabled
  lib/private/legacy/OC_App.php
Labels: 3. to review, bug

#27354 Escape filename in Content-Disposition
  lib/public/AppFramework/Http/DownloadResponse.php
  tests/lib/AppFramework/Http/DownloadResponseTest.php
Labels: 3. to review, backport-request

#27346 [stable21] Replace OCSController with OCP\API
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: 3. to review, bug

#27342 22.0.0 beta 3
  version.php
Labels: 3. to review

#27348 Export the CalDAV trash bin retention duration as property
  apps/dav/lib/CalDAV/RetentionService.php
  apps/dav/lib/CalDAV/Trashbin/Plugin.php
  apps/dav/lib/Server.php
Labels: 3. to review, enhancement

#27183 [stable20] Bump patch dependencies
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-vendors-settings-apps-70bd3f68dff7c5e499a6.js
  apps/settings/js/vue-vendors-settings-apps-70bd3f68dff7c5e499a6.js.map
  apps/settings/js/vue-vendors-settings-apps-e4b12ad7c7bc88f94103.js
  apps/settings/js/vue-vendors-settings-apps-e4b12ad7c7bc88f94103.js.map
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/js/dist/main.js
  package-lock.json
  package.json
Labels: 4. to release, feature: dependencies

#27374 Bugfix/noid/adjust unit tests
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  tests/lib/AppFramework/Bootstrap/CoordinatorTest.php
  tests/lib/AppFramework/Bootstrap/RegistrationContextTest.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
  tests/lib/CapabilitiesManagerTest.php
  tests/lib/Collaboration/Resources/ProviderManagerTest.php
Labels: 4. to release, bug, regression

#27325 [stable20] Properly log expiration date removal in audit log
  apps/admin_audit/lib/Actions/Sharing.php
Labels: 3. to review

#27326 [stable19] Properly log expiration date removal in audit log
  apps/admin_audit/lib/Actions/Sharing.php
Labels: 3. to review

#27375 Don't update statuses to offline again and again
  apps/user_status/lib/Db/UserStatusMapper.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/tests/Unit/Db/UserStatusMapperTest.php
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
Labels: 3. to review, backport-request, bug, feature: status

#27015 [stable21] Use parent wrapper to properly handle moves on the same source/target storage
  apps/files_trashbin/lib/Storage.php
Labels: 3. to review, bug

#26397 allow using any ldap property as login name when using external storage login credentials
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
Labels: 3. to review

#26494 Fix some php 8 warnings
  apps/files/lib/Helper.php
  core/Controller/PreviewController.php
  lib/private/Files/Config/CachedMountFileInfo.php
  lib/private/Files/View.php
  lib/public/AppFramework/Http/Template/PublicTemplateResponse.php
Labels: 3. to review

#27189 Extend Accounts with multivalue properties (PropertyCollection)
  build/psalm-baseline.xml
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Accounts/Account.php
  lib/private/Accounts/AccountManager.php
  lib/private/Accounts/AccountPropertyCollection.php
  lib/private/Accounts/TAccountsHelper.php
  lib/public/Accounts/IAccount.php
  lib/public/Accounts/IAccountManager.php
  lib/public/Accounts/IAccountPropertyCollection.php
  tests/lib/Accounts/AccountManagerTest.php
  tests/lib/Accounts/AccountPropertyCollectionTest.php
  tests/lib/Accounts/AccountTest.php
Labels: 3. to review, enhancement, feature: users and groups

#27306 Set local domain for swiftmailer
  lib/private/Mail/Mailer.php
  tests/lib/Mail/MailerTest.php
Labels: 3. to review, enhancement

#27429 Don't pass a column object to addOrderBy
  core/Command/Db/ConvertType.php
Labels: 3. to review, bug

#27436 Allow apps to get photos of VObjects
  apps/dav/lib/CardDAV/PhotoCache.php
Labels: 3. to review, enhancement, feature: dav

#27430 Correctly check the reception of a remote feedback
  apps/federatedfilesharing/lib/Notifications.php
  apps/files_sharing/lib/External/Manager.php
  lib/private/Federation/CloudFederationProviderManager.php
  lib/public/Federation/ICloudFederationProviderManager.php
Labels: 3. to review, bug, feature: activity and notification

#27324 [stable21] Properly log expiration date removal in audit log
  apps/admin_audit/lib/Actions/Sharing.php
Labels: 3. to review

#27089 [ProvisioningAPI] Allow specifying group display name during creation
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
  build/integration/features/bootstrap/Provisioning.php
  build/integration/features/provisioning-v1.feature
Labels: 3. to review, enhancement

#27426 Allow certain custom DAV props to be readable by everyone
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: 3. to review, bug, feature: dav

#27102 Trigger the default action when openfile URL param is set
  apps/files/js/app.js
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
  apps/files/lib/Controller/ViewController.php
  apps/files/lib/Search/FilesSearchProvider.php
  apps/files/src/sidebar.js
  apps/files/src/views/Sidebar.vue
Labels: 3. to review, enhancement, feature: files, high

#27451 Move exception logging to separate field
  lib/private/Log/LogDetails.php
Labels: 3. to review, enhancement, pending documentation

#26421 OCC command to delete calendars
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Command/DeleteCalendar.php
  apps/dav/tests/unit/Command/DeleteCalendarTest.php
Labels: 3. to review, feature: dav

#27051 Add timestamp tooltip
  apps/files/js/dist/files-app-settings.js
  apps/files/js/dist/files-app-settings.js.map
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/dist/templates.js
  apps/files/js/dist/templates.js.map
  apps/files/src/views/Sidebar.vue
Labels: 3. to review

#27506 Fix avatar actions
  apps/settings/js/settings/personalInfo.js
Labels: 3. to review, bug, feature: settings

#27508 Skip deleted calendar objects of deleted calendars
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, bug, feature: dav

#27512 Add return type for writeToCache
  apps/user_ldap/lib/Connection.php
Labels: 3. to review, technical debt

#26874 rework search api to allow searching on multiple caches at once
  apps/files_sharing/lib/Cache.php
  apps/files_trashbin/lib/Trashbin.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/FailedCache.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
  lib/private/Files/Node/Folder.php
  lib/private/Lockdown/Filesystem/NullCache.php
  lib/public/Files/Cache/ICache.php
  tests/lib/Files/Cache/CacheTest.php
  tests/lib/Files/Cache/SearchBuilderTest.php
  tests/lib/Files/Node/FolderTest.php
Labels: 3. to review

#27520 Change reviewers of Psalm baseline update
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#27514 Fix share activity dispatch
  lib/private/Share20/Manager.php
Labels: 3. to review, bug

#25950 Add dedicated product name to OCP\Defaults
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/AuthToken.vue
  apps/theming/lib/ThemingDefaults.php
  core/Controller/WhatsNewController.php
  lib/private/Setup.php
  lib/private/Template/JSConfigHelper.php
  lib/public/Defaults.php
  status.php
Labels: 4. to release, enhancement, feature: theming

#26571 Only allow removing existing shares that would not be allowed due to reshare restrictions
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Updater.php
  apps/files_sharing/src/components/SharingEntryLink.vue
  tests/acceptance/features/bootstrap/FilesAppSharingContext.php
Labels: 3. to review, bug, feature: sharing

#27515 Add method to read multi-value attributes from ldap
  apps/user_ldap/lib/LDAPProvider.php
  apps/user_ldap/tests/LDAPProviderTest.php
  lib/public/LDAP/ILDAPProvider.php
Labels: 3. to review, enhancement

#27529 Fix default product name for old themes
  apps/theming/lib/ThemingDefaults.php
  lib/private/legacy/OC_Defaults.php
Labels: 4. to release, bug

#27190 Deduplicate translations and fix double .
  lib/base.php
Labels: 4. to release, bug, feature: language l10n and translations

#26319 Move files_external to IBootstrap and remove some deprecated stuff in the process
  apps/files_external/appinfo/app.php
  apps/files_external/appinfo/routes.php
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Command/Create.php
  apps/files_external/lib/Command/Import.php
  apps/files_external/lib/Controller/ApiController.php
  apps/files_external/lib/Lib/StorageConfig.php
  apps/files_external/lib/Listener/GroupDeletedListener.php
  apps/files_external/lib/Listener/UserDeletedListener.php
  apps/files_external/lib/MountConfig.php
  apps/files_external/tests/Service/StoragesServiceTest.php
  lib/private/Encryption/File.php
  lib/private/Encryption/Util.php
Labels: 4. to release, feature: external storage

#27098 force 'name' key in array
  lib/private/App/AppManager.php
Labels: 4. to release, bug, low

#27523 [stable20] Activate constraint check for oracle / pqsql also for 20
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 3. to review, bug

#27522 Save a request everytime we send the heartbeat
  apps/user_status/js/user-status-menu.js
  apps/user_status/js/user-status-menu.js.map
  apps/user_status/lib/Controller/HeartbeatController.php
  apps/user_status/src/UserStatus.vue
  apps/user_status/src/services/heartbeatService.js
  apps/user_status/src/store/userStatus.js
Labels: 3. to review, bug, feature: status

#27525 22.0.0 beta 5
  version.php
Labels: 3. to review

#27535 Update shipped info.xsd too
  resources/app-info-shipped.xsd
Labels: 3. to review, bug, feature: apps management

#27537 Allow WebAuthn on localhost as well
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/src/components/WebAuthn/AddDevice.vue
  apps/settings/src/components/WebAuthn/Section.vue
  apps/settings/src/main-personal-webauth.js
  core/js/dist/login.js
  core/js/dist/login.js.map
  core/src/components/login/PasswordLessLoginForm.vue
  core/src/login.js
  core/src/views/Login.vue
Labels: 3. to review, enhancement

#24318 Use proper methods for display name retrieval
  apps/files_sharing/lib/Cache.php
  apps/files_sharing/lib/SharedStorage.php
  lib/private/TemplateLayout.php
  lib/private/legacy/OC_User.php
Labels: 3. to review, technical debt

#27532 Properly cleanup entries of WebAuthn on user deletion
  core/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Listeners/UserDeletedWebAuthnCleanupListener.php
  lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialMapper.php
Labels: 4. to release, backport-request, enhancement

#27540 handle case where storage can't be created in getStorageRootId
  lib/private/Files/Mount/MountPoint.php
Labels: 3. to review

#27544 Phase out the controller reflector
  lib/public/AppFramework/Utility/IControllerMethodReflector.php
Labels: 3. to review, technical debt

#27283 l10n: Spelling unification
  apps/dav/lib/CardDAV/Activity/Provider/Addressbook.php
  apps/dav/lib/CardDAV/Activity/Provider/Card.php
  apps/dav/lib/CardDAV/Activity/Setting.php
Labels: 3. to review

#27596 [stable20] Properly cleanup entries of WebAuthn on user deletion
  core/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Listeners/UserDeletedWebAuthnCleanupListener.php
  lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialMapper.php
Labels: 3. to review, backport-request

#27595 mail-template - don't show hyphen if slogan is empty
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/private/Mail/EMailTemplate.php
Labels: 3. to review, feature: emails, needs info

#27604 Proper opacity on multiselect actions in files
  core/css/styles.scss
Labels: 3. to review, bug, design

#27610 Throttle on public DAV endpoint
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/lib/Connector/PublicAuth.php
  apps/dav/tests/unit/Connector/PublicAuthTest.php
Labels: 4. to release, backport-request

#26323 Use constant for supported formats
  apps/encryption/lib/Crypto/Crypt.php
Labels: 3. to review, feature: encryption (server-side)

#26346 Cleaner removePassword regex
  lib/private/Log/ErrorHandler.php
  tests/lib/ErrorHandlerTest.php
Labels: 3. to review

#27561 allow setting offset for dav search queries not limited to the users home storage
  apps/dav/lib/Files/FileSearchBackend.php
Labels: 4. to release

#27016 [stable20] Use parent wrapper to properly handle moves on the same source/target storage
  apps/files_trashbin/lib/Storage.php
Labels: 3. to review, bug

#26344 Return early if path is root
  lib/private/Files/Filesystem.php
Labels: 4. to release

#27628 Add security.txt
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/WellKnown/SecurityTxtHandler.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/Http/TextPlainResponse.php
Labels: 3. to review, enhancement, security

#27635 Fix usage of DateTime constants
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
  apps/dav/lib/CalDAV/Reminder/Notifier.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/Files/FileSearchBackend.php
  apps/dav/lib/Provisioning/Apple/AppleProvisioningNode.php
  apps/dav/lib/Search/EventsSearchProvider.php
  apps/dav/lib/Search/TasksSearchProvider.php
  core/Command/Security/ListCertificates.php
  core/Command/User/Info.php
  core/Command/User/ListCommand.php
  lib/private/AppFramework/Middleware/NotModifiedMiddleware.php
  lib/private/Console/TimestampFormatter.php
  lib/private/Files/ObjectStore/S3Signature.php
  lib/private/Log/LogDetails.php
  lib/public/AppFramework/Http/Response.php
  tests/lib/AppFramework/Middleware/NotModifiedMiddlewareTest.php
Labels: 4. to release, bug

#27605 Make security warning stand out more
  core/templates/loginflow/authpicker.php
  core/templates/loginflowv2/authpicker.php
Labels: security

#27632 Use ISO8601 timestamps for the CalDAV trashbin
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/Trashbin/Plugin.php
Labels: 3. to review

#27643 [stable19] fix integration-federation_features tests
  apps/federatedfilesharing/lib/AppInfo/Application.php
Labels: 3. to review, bug

#27623 22.0.0 RC1
  version.php
Labels: 3. to review

#27619 19.0.13 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review

#27620 20.0.11 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review

#27621 21.0.3 RC1
  resources/config/ca-bundle.crt
  version.php
Labels: 3. to review

#27648 Master is now 23
  .github/dependabot.yml
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 4. to release, technical debt

#27663 Unshift crash reports when they are loaded, to break the recusion
  lib/private/Support/CrashReport/Registry.php
Labels: 3. to review, backport-request, bug, integration

#27664 Bump app version
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  tests/Core/Command/Apps/AppsDisableTest.php
  tests/Core/Command/Apps/AppsEnableTest.php
Labels: 3. to review, bug

#27675 Validate the theming color also on CLI
  apps/theming/lib/Command/UpdateConfig.php
  apps/theming/lib/ThemingDefaults.php
Labels: 4. to release, backport-request, bug, feature: theming

#27668 Harden bootstrap context registrations when apps are missing
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
Labels: 3. to review, backport-request, bug

#27649 Fix branch selection in stable22
  .codecov.yml
  .drone.yml
  README.md
  build/update-apps.sh
  build/update.sh
  tests/acceptance/run-local.sh
Labels: 3. to review, technical debt

#27697 Auto approve/merge also on stable branches
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review

#27687 Create rebase command
  .github/workflows/command-rebase.yml
Labels: 3. to review

#27676 Localize invitation email subjects
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
Labels: 3. to review, bug, feature: dav, feature: language l10n and translations

#27698 LDAP: determine shares of offline users only when needed
  apps/user_ldap/lib/User/OfflineUser.php
Labels: 3. to review, backport-request, bug, feature: ldap, regression

#27644 Remember current cipher
  apps/encryption/lib/Crypto/Crypt.php
Labels: 4. to release, feature: encryption (server-side), performance 🚀

#27488 Add regex to match Windows 10 calendar user-agent
  apps/dav/lib/CalDAV/WebcalCaching/Plugin.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/PluginTest.php
Labels: 4. to release, feature: dav, php

#27715 Revert "First attempt to check against core routes before loading all app routes"
  lib/private/Route/Router.php
Labels: 4. to release, backport-request, bug, regression

#27474 make Provisioning API aware of multiple mails
  apps/provisioning_api/appinfo/routes.php
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  build/integration/features/bootstrap/Provisioning.php
  build/integration/features/provisioning-v1.feature
  lib/base.php
  lib/private/Accounts/Account.php
  lib/private/Accounts/AccountManager.php
  lib/private/Accounts/AccountPropertyCollection.php
  lib/private/Accounts/Hooks.php
  lib/private/Avatar/AvatarManager.php
  lib/public/Accounts/IAccount.php
  lib/public/Accounts/IAccountPropertyCollection.php
  tests/lib/Accounts/AccountManagerTest.php
  tests/lib/Accounts/HooksTest.php
Labels: 3. to review, enhancement

#27700 Deprecate OCP\Remote
  lib/public/Remote/Api/IApiCollection.php
  lib/public/Remote/Api/IApiFactory.php
  lib/public/Remote/Api/ICapabilitiesApi.php
  lib/public/Remote/Api/IUserApi.php
  lib/public/Remote/ICredentials.php
  lib/public/Remote/IInstance.php
  lib/public/Remote/IInstanceFactory.php
  lib/public/Remote/IUser.php
Labels: 3. to review

#27723 fix incredible off-by-one-typo-error
  apps/provisioning_api/appinfo/routes.php
Labels: 4. to release, bug

#27638 Downstream encryption:fix-encrypted-version for repairing "bad signature" errors
  apps/encryption/appinfo/info.xml
  apps/encryption/composer/composer/autoload_classmap.php
  apps/encryption/composer/composer/autoload_static.php
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
Labels: 3. to review, backport-request, enhancement, feature: encryption (server-side)

#27732 Fix LDAPProviderFactory not found
  apps/user_ldap/appinfo/info.xml
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Migration/UnsetDefaultProvider.php
  lib/private/Server.php
Labels: 4. to release, backport-request, bug, feature: ldap, regression
