Repository nextcloud/server, pull requests merged in 2021-01, with the labels that each got.

#24907 Update license headers
  AUTHORS
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Command/MoveCalendar.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/lib/Migration/BuildSocialSearchIndex.php
  apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
  apps/federation/lib/BackgroundJob/GetSharedSecret.php
  apps/federation/lib/BackgroundJob/RequestSharedSecret.php
  apps/files/lib/Command/Scan.php
  apps/files/lib/Command/ScanAppData.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_trashbin/lib/Migration/Version1010Date20200630192639.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/ILDAPWrapper.php
  apps/user_ldap/lib/LDAP.php
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/Trashbin.php
  console.php
  core/Command/Db/ConvertFilecacheBigInt.php
  core/Controller/WellKnownController.php
  cron.php
  lib/private/AppFramework/Http/Request.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/SimpleFS/NewSimpleFile.php
  lib/private/Files/Storage/DAV.php
  lib/private/Files/Storage/Flysystem.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/private/Http/WellKnown/RequestManager.php
  lib/private/Preview/HEIC.php
  lib/private/Repair/Owncloud/MoveAvatarsBackgroundJob.php
  lib/private/Share/SearchResultSorter.php
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_Image.php
  lib/public/AppFramework/Http/ContentSecurityPolicy.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  lib/public/Files/SimpleFS/ISimpleFile.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
  lib/public/Http/WellKnown/GenericResponse.php
  lib/public/Http/WellKnown/IHandler.php
  lib/public/Http/WellKnown/IRequestContext.php
  lib/public/Http/WellKnown/IResponse.php
  lib/public/Http/WellKnown/JrdResponse.php
  lib/public/Share/Events/ShareDeletedEvent.php
  lib/public/Util.php
Labels: 4. to release

#24762 [stable19] fixes sharing to group ids with characters that are being url encoded
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/DAV/GroupPrincipalBackend.php
  apps/dav/lib/DAV/Sharing/Backend.php
Labels: 3. to review, bug, feature: dav

#24829 Add migration for oc_share_external columns
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Migration/Version11300Date20201120141438.php
  apps/files_sharing/lib/Migration/Version21000Date20201223143245.php
Labels: 3. to review, bug

#24964 Don't throw a 500 when importing a broken ics reminder file
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
Labels: 3. to review, backport-request, bug, feature: dav

#24880 [stable19] Make share results distinguishable if there are more than one with the exact same display name
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntrySimple.vue
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/views/SharingList.vue
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: 3. to review, bug, feature: sharing

#24878 [stable20] Make share results distinguishable if there are more than one with the exact same display name
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntrySimple.vue
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/views/SharingList.vue
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: 4. to release, bug, feature: sharing

#24961 Fix unreliable ViewTest
  lib/private/Files/Storage/Common.php
  tests/lib/Files/ViewTest.php
Labels: 3. to review, backport-request, bug

#24970 Fix dashboard greetings that show 'good morning' after noon
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/App.vue
Labels: 3. to review, enhancement

#24900 Fix updating user settings
  apps/settings/lib/Controller/UsersController.php
Labels: 3. to review, bug, feature: settings, regression

#24317 App password command
  core/Command/User/AddAppPassword.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review, feature: authentication, feature: occ

#24986 Update root.crl due to revocation of transmission.crt
  resources/codesigning/root.crl
Labels: 3. to review, backport-request, security

#24988 Set the JSCombiner cache if needed
  lib/private/Template/JSCombiner.php
Labels: 3. to review, backport-request, performance 🚀

#24993 No need to run mysql5 tests anymore
  .drone.yml
Labels: 3. to review

#24911 Tasks search: make sure we have existing indexes before using them
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, bug, feature: search

#24994 Update postgres version tests
  .drone.yml
Labels: 3. to review

#25004 Fix warning in PHP 8 about optional parameter before mandatory one
  lib/private/Log/File.php
Labels: 3. to review, bug

#25000 Hide client link in welcome mail if an empty customclient_desktop config is set
  apps/settings/lib/Mailer/NewUserMailHelper.php
Labels: 3. to review, enhancement, feature: theming

#25001 Fix column name to check prior to deleting
  core/Migrations/Version21000Date20201120141228.php
Labels: 4. to release, backport-request, bug, feature: owncloud migration, regression

#25003 Fix return types for Archive::getStream
  lib/private/Archive/Archive.php
  lib/private/Archive/TAR.php
  lib/private/Archive/ZIP.php
Labels: 4. to release

#24955 allow using any ldap property as login name when using login credentials
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
Labels: 3. to review

#24881 [stable18] Make share results distinguishable if there are more than one with the exact same display name
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntrySimple.vue
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/views/SharingList.vue
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: 3. to review, bug, feature: sharing

#24958 18.0.13 RC1
  version.php
Labels: 2. developing, overview

#25010 Revert "allow using any ldap property as login name when using login credentials"
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
Labels: 3. to review, feature: external storage, feature: ldap

#24959 19.0.7 RC1
  version.php
Labels: 2. developing, overview

#25011 Catch throwable instead of exception
  lib/private/Encryption/Keys/Storage.php
Labels: 4. to release, backport-request, bug

#24999 Set the user language when adding the footer
  apps/settings/lib/Mailer/NewUserMailHelper.php
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
Labels: 3. to review, backport-request, bug

#25018 Fix name of avatar integration tests in Drone
  .drone.yml
Labels: 3. to review

#24934 Remove useless ini_set calls
  lib/base.php
Labels: 3. to review

#24960 20.0.5 RC1
  version.php
Labels: 2. developing, overview

#24989 ignore files that have no read permissions during scanning
  lib/private/Files/Cache/Scanner.php
Labels: 3. to review

#23261 Expose session based authentication through mount point type
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Config/ExternalMountPoint.php
  apps/files_external/lib/Lib/PersonalMount.php
  apps/files_external/tests/PersonalMountTest.php
Labels: 3. to review, enhancement

#24892 Use the Symfony dispatcher correctly
  lib/private/EventDispatcher/SymfonyAdapter.php
Labels: 3. to review, bug, technical debt

#25021 Print an exception trace for setup exceptions
  core/Command/Maintenance/Install.php
  lib/private/Setup.php
  lib/private/Setup/MySQL.php
  lib/private/Setup/OCI.php
  lib/private/Setup/PostgreSQL.php
Labels: 4. to release, enhancement, feature: install and update

#25020 (LDAP) respect DB limits of arguments in an IN statement
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/tests/Mapping/AbstractMappingTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#25029 Change defaultapp in config.sample.php to dashboard to improve docs and align it to source code
  config/config.sample.php
Labels: 3. to review, backport-request

#25017 Fix clearing the label of a share
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
Labels: 3. to review, backport-request, bug, feature: sharing

#22992 allow authenticating using urlencoded passwords
  build/psalm-baseline.xml
  lib/private/User/Manager.php
Labels: 3. to review

#24951 21 beta5
  version.php
Labels: 2. developing, overview

#24661 dont offer to edit external config settings if we can't edit them
  apps/files_external/js/statusmanager.js
  apps/files_external/lib/Controller/GlobalStoragesController.php
  apps/files_external/lib/Controller/StoragesController.php
  apps/files_external/lib/Controller/UserGlobalStoragesController.php
  apps/files_external/lib/Controller/UserStoragesController.php
  apps/files_external/tests/Controller/GlobalStoragesControllerTest.php
  apps/files_external/tests/Controller/StoragesControllerTest.php
  apps/files_external/tests/Controller/UserStoragesControllerTest.php
Labels: 3. to review

#25066 [stable20] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review

#25069 Don't remove assignable column for now
  core/Migrations/Version21000Date20201120141228.php
Labels: 3. to review, backport-request, bug, regression

#25070 Deck Rich-Object-String definitions for deck boards and cards
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review, enhancement

#25073 Remove unneeded casts that were found by Psalm
  apps/comments/lib/Activity/Provider.php
  apps/dav/lib/CalDAV/Activity/Provider/Calendar.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/lib/CalDAV/Activity/Provider/Todo.php
  apps/dav/lib/CalDAV/Publishing/PublishPlugin.php
  apps/encryption/lib/Controller/RecoveryController.php
  apps/encryption/lib/Controller/SettingsController.php
  apps/encryption/lib/Controller/StatusController.php
  apps/encryption/lib/Crypto/EncryptAll.php
  apps/federatedfilesharing/lib/Notifier.php
  apps/federation/lib/Controller/SettingsController.php
  apps/files/lib/Controller/ApiController.php
  apps/files_external/lib/Controller/GlobalStoragesController.php
  apps/files_external/lib/Controller/StoragesController.php
  apps/files_external/lib/Controller/UserGlobalStoragesController.php
  apps/files_external/lib/Controller/UserStoragesController.php
  apps/files_external/lib/MountConfig.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/sharebymail/lib/Activity.php
  apps/theming/lib/IconBuilder.php
  apps/workflowengine/lib/Check/RequestUserAgent.php
  core/Migrations/Version13000Date20170718121200.php
  core/ajax/update.php
  lib/private/App/AppStore/Bundles/EducationBundle.php
  lib/private/App/AppStore/Bundles/GroupwareBundle.php
  lib/private/App/AppStore/Bundles/SocialSharingBundle.php
  lib/private/App/DependencyAnalyzer.php
  lib/private/AppFramework/Http/Dispatcher.php
  lib/private/AppFramework/Routing/RouteConfig.php
  lib/private/Collaboration/Collaborators/Search.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/L10N/Factory.php
  lib/private/Notification/Notification.php
  lib/private/Preview/TXT.php
  lib/private/Security/Normalizer/IpAddress.php
  lib/private/Template/JSConfigHelper.php
Labels: 3. to review

#25034 Make sure to do priority app upgrades first
  lib/private/Updater.php
Labels: 4. to release, backport-request, bug

#25039 Only use libxml_disable_entity_loader on php older than 8
  lib/private/App/InfoParser.php
Labels: 3. to review, technical debt

#25038 Don't try a transaction for the migrator on MySQL
  lib/private/DB/Migrator.php
  tests/lib/DB/MigratorTest.php
Labels: 4. to release, bug, feature: install and update, technical debt

#25087 Update psalm baseline to remove obsolete stuff
  apps/settings/lib/SetupChecks/SupportedDatabase.php
  build/psalm-baseline.xml
Labels: 3. to review, technical debt

#25080 Fix database connection usage in the files scanner
  apps/files/lib/Command/Scan.php
  apps/files/lib/Command/ScanAppData.php
Labels: 4. to release, bug

#25064 20.0.5 RC2
  version.php
Labels: 2. developing, overview

#24606 Add 'allow Symlinks' as an option to config.php
  config/config.sample.php
  lib/private/Files/Storage/Local.php
Labels: 3. to review, enhancement, feature: filesystem

#25088 Allow installing/updating of apps again
  lib/private/Http/Client/Client.php
  lib/private/Installer.php
  lib/public/Http/Client/IClient.php
  tests/lib/InstallerTest.php
Labels: 4. to release, bug

#25089 Add our own db column types via the public API
  apps/dav/lib/Migration/Version1005Date20180413093149.php
  apps/dav/lib/Migration/Version1005Date20180530124431.php
  apps/dav/lib/Migration/Version1006Date20180619154313.php
  apps/dav/lib/Migration/Version1006Date20180628111625.php
  apps/dav/lib/Migration/Version1008Date20181030113700.php
  apps/dav/lib/Migration/Version1008Date20181105104826.php
  apps/dav/lib/Migration/Version1008Date20181105110300.php
  apps/dav/lib/Migration/Version1011Date20190725113607.php
  apps/dav/lib/Migration/Version1011Date20190806104428.php
  apps/dav/lib/Migration/Version1012Date20190808122342.php
  apps/federatedfilesharing/lib/Migration/Version1010Date20200630191755.php
  apps/federatedfilesharing/lib/Migration/Version1011Date20201120125158.php
  apps/federation/lib/Migration/Version1010Date20200630191302.php
  apps/files_external/lib/Migration/Version1011Date20200630192246.php
  apps/files_sharing/lib/Migration/Version11300Date20201120141438.php
  apps/files_sharing/lib/Migration/Version21000Date20201223143245.php
  apps/files_trashbin/lib/Migration/Version1010Date20200630192639.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/user_ldap/lib/Migration/Version1010Date20200630192842.php
  apps/user_status/lib/Migration/Version0001Date20200602134824.php
  apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
  core/Command/Db/ConvertFilecacheBigInt.php
  core/Command/Db/ConvertType.php
  core/Migrations/Version13000Date20170705121758.php
  core/Migrations/Version13000Date20170718121200.php
  core/Migrations/Version14000Date20180710092004.php
  core/Migrations/Version16000Date20190207141427.php
  core/Migrations/Version16000Date20190212081545.php
  core/Migrations/Version16000Date20190428150708.php
  core/Migrations/Version17000Date20190514105811.php
  core/Migrations/Version18000Date20190920085628.php
  core/Migrations/Version18000Date20191014105105.php
  core/Migrations/Version20000Date20201109081918.php
  core/Migrations/Version21000Date20201202095923.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/DB/Types.php
Labels: 3. to review, enhancement

#25104 18.0.13
  version.php
Labels: overview

#25103 19.0.7
  version.php
Labels: overview

#25102 20.0.5
  version.php
Labels: overview

#25065 21 beta6
  version.php
Labels: 2. developing, overview

#25110 Fix night condition in dashboard greeting
  apps/dashboard/js/dashboard.js
  apps/dashboard/js/dashboard.js.map
  apps/dashboard/src/App.vue
Labels: 3. to review, bug, feature: dashboard

#25036 respect DB restrictions on number of arguments in statements and queries
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/tests/Mapping/AbstractMappingTest.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  tests/lib/DB/QueryBuilder/QueryBuilderTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#25114 Dismiss reminder notifications from passed events
  apps/dav/lib/CalDAV/Reminder/Notifier.php
  apps/dav/tests/unit/CalDAV/Reminder/NotifierTest.php
Labels: 3. to review, feature: activity and notification, feature: dav

#25084 Update DAVx5 in AuthToken.vue
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/src/components/AuthToken.vue
Labels: 4. to release, enhancement

#25091 Add our own DB exception abstraction
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/DB/Adapter.php
  lib/private/DB/Connection.php
  lib/private/DB/ConnectionAdapter.php
  lib/private/DB/Exceptions/DbalException.php
  lib/private/DB/Migrator.php
  lib/public/DB/Exception.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  lib/public/IDBConnection.php
Labels: 3. to review, enhancement, pending documentation, technical debt

#25055 Add "Crop image previews" setting to files
  apps/files/appinfo/routes.php
  apps/files/js/app.js
  apps/files/js/filelist.js
  apps/files/lib/Controller/ApiController.php
  apps/files/lib/Controller/ViewController.php
  apps/files/templates/appnavigation.php
  apps/files/templates/index.php
  apps/files/tests/Controller/ApiControllerTest.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: 4. to release, enhancement, feature: files

#25141 Add a hint about the direction of priority
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/EventDispatcher/IEventDispatcher.php
Labels: 4. to release, backport-request

#25142 Do not redirect to logout after login
  core/Controller/LoginController.php
Labels: 4. to release, enhancement

#25138 Fix comparison of PHP versions
  lib/private/App/AppStore/Fetcher/AppFetcher.php
Labels: 3. to review, backport-request, bug

#25176 Add "composer.lock" for acceptance tests to git
  .gitignore
  tests/acceptance/composer.json
  tests/acceptance/composer.lock
Labels: 3. to review, backport-request, bug

#25177 Only use alphanumeric chars for mysql password
  lib/private/Setup/MySQL.php
Labels: 4. to release, bug, feature: install and update

#25168 Add cards_abiduri index on install
  apps/dav/lib/Migration/Version1004Date20170924124212.php
Labels: 3. to review, enhancement

#25185 Show the actual error on share requests
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/mixins/ShareRequests.js
Labels: 3. to review, bug

#25181 Update CRL due to revoked gravatar.crl
  resources/codesigning/root.crl
Labels: 4. to release, backport-request

#25182 Readd element ID after component mount.
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/components/HeaderMenu.vue
Labels: 3. to review, bug, feature: search

#25186 Don't log keys on checkSignature
  lib/private/Log/ExceptionSerializer.php
Labels: 3. to review, backport-request, bug

#25153 Force signature verification of apps on occ
  core/Command/Integrity/CheckApp.php
  core/Command/Integrity/CheckCore.php
  core/Command/Upgrade.php
  lib/private/IntegrityCheck/Checker.php
  lib/private/Server.php
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: 3. to review, bug, feature: apps management

#25203 20.0.6 RC1
  version.php
Labels: 4. to release, overview

#25204 19.0.8 RC1
  version.php
Labels: 4. to release, overview

#25206 18.0.14 RC 1
  version.php
Labels: 3. to review

#25184 Directly add notifications element
  core/templates/layout.user.php
Labels: 3. to review, bug

#25173 Add support for webp
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Preview/WebP.php
  lib/private/PreviewManager.php
  lib/private/legacy/OC_Image.php
Labels: 3. to review, enhancement

#25216 Bump CA bundle
  resources/config/ca-bundle.crt
Labels: 3. to review, backport-request

#25151 Fix IE 11 dashboard syntax error
  apps/user_status/js/dashboard.js
  apps/user_status/js/dashboard.js.map
  webpack.common.js
Labels: 3. to review, bug

#25225 [stable20] Update handling of user credentials
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Listener/StorePasswordListener.php
  lib/private/Server.php
  lib/public/User/Events/UserLoggedInEvent.php
Labels: 3. to review, bug, feature: external storage

#25224 Update handling of user credentials
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Listener/StorePasswordListener.php
  lib/private/Server.php
  lib/public/User/Events/UserLoggedInEvent.php
Labels: 3. to review, bug, feature: external storage

#25212 Enhance markdown file preview rendering
  lib/private/Preview/MarkDown.php
Labels: 3. to review, enhancement

#25229 Dark mode adjustments for popover
  apps/accessibility/css/dark.scss
Labels: 3. to review

#25236 explicitly set permissions on newly created folders
  lib/private/Files/Storage/Local.php
Labels: 3. to review

#25119 21 beta7
  version.php
Labels: 2. developing, overview

#25240 Re-use fetched dependencies in lib/base.php
  apps/files_sharing/tests/DeleteOrphanedSharesJobTest.php
  apps/files_sharing/tests/ExpireSharesJobTest.php
  apps/files_sharing/tests/TestCase.php
  apps/files_trashbin/tests/TrashbinTest.php
  apps/files_versions/tests/VersioningTest.php
  lib/base.php
  public.php
  tests/lib/Share/ShareTest.php
Labels: 3. to review, technical debt

#25238 Apps folder is defacto in root folder and not above
  lib/base.php
Labels: 3. to review, technical debt

#25255 also use storage copy when dav copying directories
  apps/dav/lib/Connector/Sabre/Directory.php
Labels: 3. to review

#25253 silence log message
  apps/user_ldap/lib/Access.php
Labels: 3. to review, backport-request, bug, feature: ldap

#25128 extend ILDAPProvider to allow reading arbitrairy ldap attributes for users
  apps/user_ldap/lib/LDAPProvider.php
  lib/public/LDAP/ILDAPProvider.php
Labels: 3. to review, backport-request

#25274 Do not obtain userFolder of a federated user
  apps/files_trashbin/lib/Storage.php
Labels: 3. to review, bug

#25279 Fully deprecate the old initial state interface, not just the methods
  lib/public/IInitialStateService.php
Labels: 3. to review, technical debt

#25275 Convert 2FA token type to string
  lib/private/Authentication/TwoFactorAuth/Manager.php
  tests/lib/Authentication/TwoFactorAuth/ManagerTest.php
Labels: 3. to review, bug, technical debt

#25273 Do not show 2FA settings if the user has no providers available
  apps/settings/lib/Settings/Personal/Security/TwoFactor.php
  lib/public/Settings/ISettings.php
Labels: 3. to review, enhancement, security

#25313 Catch NotFoundException when querying quota
  apps/dav/lib/Connector/Sabre/Directory.php
Labels: 3. to review, backport-request, bug

#25295 19.0.8
  version.php
Labels: 2. developing, overview

#25294 20.0.6
  version.php
Labels: 2. developing, overview

#21810 Do not target vue progressbar with server styles
  core/css/inputs.scss
Labels: 3. to review

#25310 [CalDAV] Validate notified emails
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php
Labels: 3. to review, bug, feature: dav

#25309 Add config to specify a default dashboard layout
  apps/dashboard/lib/Controller/DashboardController.php
Labels: 3. to review, enhancement

#24633 Update UpdateNotification.vue
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/src/components/UpdateNotification.vue
Labels: 3. to review, feature: settings

#25312 do not lower case search provider names on web ui
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/views/UnifiedSearch.vue
Labels: 3. to review, backport-request, bug, feature: search

#25268 Add SGI and TGA preview support
  .mailmap
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Preview/SGI.php
  lib/private/Preview/TGA.php
  lib/private/PreviewManager.php
  resources/config/mimetypealiases.dist.json
  resources/config/mimetypemapping.dist.json
Labels: 3. to review, enhancement, feature: previews and thumbnails

#25335 Fix/app fetcher php compat comparison
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/CompareVersion.php
  tests/lib/App/CompareVersionTest.php
Labels: 3. to review, bug, feature: apps management, regression

#25189 add command to repair broken filesystem trees
  apps/files/appinfo/info.xml
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/Command/RepairTree.php
Labels: 3. to review

#25348 Add negative version comparison test for version suffixes
  tests/lib/App/CompareVersionTest.php
Labels: 4. to release, technical debt

#25090 File templates
  apps/files/appinfo/routes.php
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/js/dist/files-app-settings.js
  apps/files/js/dist/files-app-settings.js.map
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/js/dist/sidebar.js
  apps/files/js/dist/sidebar.js.map
  apps/files/js/dist/templates.js
  apps/files/js/dist/templates.js.map
  apps/files/js/newfilemenu.js
  apps/files/lib/Controller/TemplateController.php
  apps/files/lib/Controller/ViewController.php
  apps/files/lib/Event/LoadAdditionalScriptsEvent.php
  apps/files/src/components/TemplatePreview.vue
  apps/files/src/services/Templates.js
  apps/files/src/templates.js
  apps/files/src/utils/davUtils.js
  apps/files/src/utils/fileUtils.js
  apps/files/src/views/TemplatePicker.vue
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files/webpack.js
  config/config.sample.php
  core/css/css-variables.scss
  core/css/icons.scss
  core/img/actions/template-add.svg
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Files/Template/TemplateManager.php
  lib/private/Server.php
  lib/private/legacy/OC_Util.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/Files/Template/FileCreatedFromTemplateEvent.php
  lib/public/Files/Template/ICustomTemplateProvider.php
  lib/public/Files/Template/ITemplateManager.php
  lib/public/Files/Template/Template.php
  lib/public/Files/Template/TemplateFileCreator.php
Labels: 3. to review, enhancement

#25361 fix parameter provided as string not array
  apps/user_ldap/lib/Group_LDAP.php
Labels: 3. to review, backport-request, bug, feature: ldap

#25360 Update all composer autoloader files
  apps/accessibility/composer/composer/ClassLoader.php
  apps/accessibility/composer/composer/autoload_real.php
  apps/admin_audit/composer/composer/ClassLoader.php
  apps/admin_audit/composer/composer/autoload_real.php
  apps/cloud_federation_api/composer/composer/ClassLoader.php
  apps/cloud_federation_api/composer/composer/autoload_real.php
  apps/comments/composer/composer/ClassLoader.php
  apps/comments/composer/composer/autoload_real.php
  apps/contactsinteraction/composer/composer/ClassLoader.php
  apps/contactsinteraction/composer/composer/autoload_real.php
  apps/dav/composer/composer/ClassLoader.php
  apps/dav/composer/composer/autoload_real.php
  apps/encryption/composer/composer/ClassLoader.php
  apps/encryption/composer/composer/autoload_real.php
  apps/federatedfilesharing/composer/composer/ClassLoader.php
  apps/federatedfilesharing/composer/composer/autoload_real.php
  apps/federation/composer/composer/ClassLoader.php
  apps/federation/composer/composer/autoload_real.php
  apps/files/composer/composer/ClassLoader.php
  apps/files/composer/composer/autoload_real.php
  apps/files_sharing/composer/composer/ClassLoader.php
  apps/files_sharing/composer/composer/autoload_real.php
  apps/files_trashbin/composer/composer/ClassLoader.php
  apps/files_trashbin/composer/composer/autoload_real.php
  apps/files_versions/composer/composer/ClassLoader.php
  apps/files_versions/composer/composer/autoload_real.php
  apps/lookup_server_connector/composer/composer/ClassLoader.php
  apps/lookup_server_connector/composer/composer/autoload_real.php
  apps/oauth2/composer/composer/ClassLoader.php
  apps/oauth2/composer/composer/autoload_real.php
  apps/provisioning_api/composer/composer/ClassLoader.php
  apps/provisioning_api/composer/composer/autoload_real.php
  apps/settings/composer/composer/ClassLoader.php
  apps/settings/composer/composer/autoload_real.php
  apps/sharebymail/composer/composer/ClassLoader.php
  apps/sharebymail/composer/composer/autoload_real.php
  apps/systemtags/composer/composer/ClassLoader.php
  apps/systemtags/composer/composer/autoload_real.php
  apps/testing/composer/composer/ClassLoader.php
  apps/testing/composer/composer/autoload_real.php
  apps/twofactor_backupcodes/composer/composer/ClassLoader.php
  apps/twofactor_backupcodes/composer/composer/autoload_real.php
  apps/updatenotification/composer/composer/ClassLoader.php
  apps/updatenotification/composer/composer/autoload_real.php
  apps/user_ldap/composer/composer/ClassLoader.php
  apps/user_ldap/composer/composer/autoload_real.php
  apps/user_status/composer/composer/ClassLoader.php
  apps/user_status/composer/composer/autoload_real.php
  apps/workflowengine/composer/composer/ClassLoader.php
  apps/workflowengine/composer/composer/autoload_real.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_real.php
Labels: 3. to review, enhancement

#25245 21 beta8
  version.php
Labels: 2. developing, overview

#25369 The objectid is a string
  lib/private/SystemTag/SystemTagObjectMapper.php
Labels: 3. to review, backport-request, performance 🚀

#25368 20.0.7 RC1
  version.php
Labels: 2. developing, overview

#25101 LDAP: make actually use of batch read known groups
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/AccessTest.php
Labels: 3. to review, backport-request, bug, feature: ldap

#25218 do not remove valid group shares
  apps/dav/lib/Connector/Sabre/Principal.php
Labels: 3. to review, bug, feature: dav

#25377 Fix initializing the template directory on first login
  lib/private/Files/Template/TemplateManager.php
Labels: 3. to review, bug

#25302 Use RFC-compliant URL encoding for cookies
  lib/private/Http/CookieHelper.php
Labels: 3. to review, bug

#25383 Properly handle SMB ACL blocking scanning a directory
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review, bug, feature: external storage
