Repository nextcloud/server, pull requests merged in 2021-02, with the labels that each got.

#25424 Keep direct login active when redirecting
  core/Controller/LoginController.php
Labels: 4. to release, backport-request, bug

#25444 Check for generic errors at last.
  lib/private/DB/Exceptions/DbalException.php
Labels: 3. to review, bug

#25446 Avoid template creators being registered multiple times
  lib/private/Files/Template/TemplateManager.php
Labels: 3. to review, bug

#25393 add repair job for unencoded group share uris
  apps/dav/lib/DAV/Sharing/Backend.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/RepairDavShares.php
  tests/lib/Repair/RepairDavSharesTest.php
Labels: 3. to review, backport-request, bug, feature: dav

#24700 Resolves #24699, Support ES2 and ECS instance providers for S3 buckets
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 3. to review, enhancement

#25454 This is 22
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 3. to review

#25432 Emit calendar interaction events
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/Listener/CalendarContactInteractionListener.php
Labels: 3. to review, backport-request, enhancement, feature: dav, integration

#25464 Parse calendar object for attendees and emit interaction events
  apps/dav/lib/Listener/CalendarContactInteractionListener.php
  apps/dav/tests/unit/Listener/CalendarContactInteractionListenerTest.php
Labels: 3. to review, backport-request, enhancement, feature: dav, integration

#25468 Allow upgrades in Nextcloud 22 / Disallow upgrade from 20
  version.php
Labels: 4. to release

#25467 Add test for dbal exception wrapping
  tests/lib/DB/Exception/DbalExceptionTest.php
Labels: 3. to review, technical debt

#25457 Update stable21 target versions
  .drone.yml
  tests/acceptance/run-local.sh
Labels: 3. to review

#25376 21 RC1
  version.php
Labels: 2. developing, overview

#25443 Make user list pagination more tolerant
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/src/store/users.js
Labels: 3. to review, backport-request, bug, feature: users and groups

#25441 Fix duplicate tag info view registration
  apps/systemtags/js/systemtags.js
  apps/systemtags/js/systemtags.js.map
  apps/systemtags/src/filesplugin.js
Labels: 3. to review, backport-request, bug, feature: tags

#25480 [stable20] Remove stray compiled assets
  apps/settings/js/vue-settings-users-6af167634af13765ed18.js
  apps/settings/js/vue-settings-users-6af167634af13765ed18.js.map
  apps/settings/js/vue-settings-users-949e04a80c66e7d41667.js
  apps/settings/js/vue-settings-users-949e04a80c66e7d41667.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users-56bf9f00883bb2b317ca.js
  apps/settings/js/vue-vendors-settings-apps-settings-users-56bf9f00883bb2b317ca.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users-f077c891fa908a10fb34.js
  apps/settings/js/vue-vendors-settings-apps-settings-users-f077c891fa908a10fb34.js.map
  apps/settings/js/vue-vendors-settings-users-3a6581e78bc592eedd33.js
  apps/settings/js/vue-vendors-settings-users-3a6581e78bc592eedd33.js.map
  apps/settings/js/vue-vendors-settings-users-7d5a89099bb7bbf586db.js
  apps/settings/js/vue-vendors-settings-users-7d5a89099bb7bbf586db.js.map
Labels: 3. to review, technical debt

#25492 Fix CI branch for notifications app
  tests/acceptance/run-local.sh
Labels: 3. to review, bug

#25487 Log deprecation notice of GenericEventWrapper just once
  lib/private/EventDispatcher/GenericEventWrapper.php
Labels: 3. to review, backport-request, bug, technical debt

#25504 [stable20] Cleanup bundle files before checking the rebuild
  .github/workflows/node.yml
Labels: 3. to review

#25500 fix(translation): replace static error message
  lib/private/Share20/Manager.php
Labels: 3. to review, bug

#25505 dont stop expiring versions if we cant check if the source file still exists
  apps/files_versions/lib/Storage.php
Labels: 3. to review

#25503 Sharing dropdown now opens below
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingInput.vue
Labels: 3. to review, backport-request, bug, regression

#25499 Test the symfony adapter / fix missing return object
  lib/private/EventDispatcher/EventDispatcher.php
  lib/private/EventDispatcher/SymfonyAdapter.php
  tests/lib/EventDispatcher/SymfonyAdapterTest.php
Labels: 3. to review, bug, technical debt

#25542 Add .devcontainer to file-checker.php
  build/files-checker.php
Labels: 3. to review

#25535 Improve exception when auto-wiring fails
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/Console/Application.php
Labels: 4. to release

#25531 Fix the legacy dispatcher argument order
  lib/private/EventDispatcher/SymfonyAdapter.php
  tests/lib/EventDispatcher/SymfonyAdapterTest.php
Labels: 3. to review, bug, technical debt

#25549 remove ReconnectWrapper
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/DB/Connection.php
  lib/private/DB/ReconnectWrapper.php
Labels: 3. to review, technical debt

#25543 Deprecate the internal IDBConnection event name constants
  lib/public/IDBConnection.php
Labels: 3. to review, pending documentation, technical debt

#25546 Deprecate all remaining event constants
  lib/public/App/ManagerEvent.php
  lib/public/Authentication/TwoFactorAuth/IProvider.php
  lib/public/Authentication/TwoFactorAuth/IRegistry.php
  lib/public/Comments/CommentsEntityEvent.php
  lib/public/Comments/CommentsEvent.php
  lib/public/Console/ConsoleEvent.php
  lib/public/IPreview.php
  lib/public/SystemTag/ManagerEvent.php
  lib/public/SystemTag/MapperEvent.php
  lib/public/SystemTag/SystemTagsEntityEvent.php
  lib/public/WorkflowEngine/IManager.php
Labels: 3. to review, technical debt

#25550 [20] change reconect wrapper to only check connection after inactivity
  lib/private/DB/ReconnectWrapper.php
Labels: 3. to review

#25545 Corrected package name used in .devcontainer/Dockerfile (php7.4-acpu => php7.4-apcu)
  .devcontainer/Dockerfile
Labels: 3. to review

#25548 Added tests for OC\Core\Data\LoginFlowV2Credentials
  tests/Core/Data/LoginFlowV2CredentialsTest.php
Labels: 3. to review

#25554 tain-escape the cookie input
  apps/files/ajax/download.php
Labels: 3. to review, enhancement

#25435 Fix favorite dark icon
  apps/files/js/tagsplugin.js
Labels: 3. to review, bug, design

#25359 Type the service registration
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/ARegistration.php
  lib/private/AppFramework/Bootstrap/EventListenerRegistration.php
  lib/private/AppFramework/Bootstrap/ParameterRegistration.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/AppFramework/Bootstrap/ServiceAliasRegistration.php
  lib/private/AppFramework/Bootstrap/ServiceFactoryRegistration.php
  lib/private/AppFramework/Bootstrap/ServiceRegistration.php
  lib/private/Files/Template/TemplateManager.php
  lib/private/Http/WellKnown/RequestManager.php
  lib/private/Search/SearchComposer.php
  lib/private/legacy/OC_App.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  tests/lib/Http/WellKnown/RequestManagerTest.php
Labels: 4. to release, enhancement, technical debt

#25566 Fix remaining #25359
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/legacy/OC_App.php
Labels: 3. to review, regression

#25558 Deprecate the GenericEvent wrapper
  lib/public/EventDispatcher/GenericEvent.php
Labels: 3. to review, pending documentation, technical debt

#24904 Have psalm analysis directly on github
  .github/workflows/psalm-github.yml
Labels: 3. to review, enhancement

#25460 Always renew apppasswords on login
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
Labels: 3. to review, backport-request, bug

#25570 Some psalm fixes for the DashboardController
  apps/dashboard/lib/Controller/DashboardController.php
Labels: 3. to review, enhancement

#25488 Version/21/rc2
  version.php
Labels: 2. developing, overview

#25378 Improve mention matches
  apps/comments/lib/Activity/Provider.php
  apps/comments/lib/Notification/Notifier.php
  lib/private/Comments/Comment.php
  tests/lib/Comments/CommentTest.php
Labels: 4. to release, backport-request, bug, feature: comments

#25382 [stable20] do not lower case search provider names on web ui
  core/js/dist/unified-search.js
  core/js/dist/unified-search.js.map
  core/src/views/UnifiedSearch.vue
Labels: 3. to review, bug, feature: search

#25299 favicon-touch image corners
  core/img/favicon-touch.png
  core/img/favicon-touch.svg
  core/img/manifest.json
Labels: 3. to review

#25576 Fix WebP availability check
  lib/private/Preview/WebP.php
Labels: 3. to review, backport-request, bug, feature: previews and thumbnails

#25585 Micro-optimize validation of empty email addresses
  lib/private/Mail/Mailer.php
  tests/lib/Mail/MailerTest.php
Labels: 3. to review, enhancement

#25582 Do not send imip email to invalid recipients
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: 3. to review, backport-request, bug

#25563 add event for when a direct download is triggered
  apps/dav/appinfo/v2/direct.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Direct/DirectFile.php
  apps/dav/lib/Direct/DirectHome.php
  apps/dav/lib/Direct/ServerFactory.php
  apps/dav/lib/Events/BeforeFileDirectDownloadedEvent.php
  apps/dav/tests/unit/Direct/DirectFileTest.php
  apps/dav/tests/unit/Direct/DirectHomeTest.php
Labels: 4. to release

#25612 Make new result parts optional
  core/Controller/AutoCompleteController.php
Labels: 3. to review, bug

#25608 use the configured forwarded headers for the setup check
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
Labels: 3. to review

#25604 Fix hover background for dark mode
  apps/accessibility/css/dark.scss
Labels: 3. to review, bug, design, feature: accessibility

#25577 Make the app code checker a NOOP
  core/Command/App/CheckCode.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/App/CodeChecker/AbstractCheck.php
  lib/private/App/CodeChecker/CodeChecker.php
  lib/private/App/CodeChecker/DatabaseSchemaChecker.php
  lib/private/App/CodeChecker/DeprecationCheck.php
  lib/private/App/CodeChecker/EmptyCheck.php
  lib/private/App/CodeChecker/ICheck.php
  lib/private/App/CodeChecker/InfoChecker.php
  lib/private/App/CodeChecker/LanguageParseChecker.php
  lib/private/App/CodeChecker/MigrationSchemaChecker.php
  lib/private/App/CodeChecker/NodeVisitor.php
  lib/private/App/CodeChecker/PrivateCheck.php
  lib/private/App/CodeChecker/StrongComparisonCheck.php
  tests/lib/App/CodeChecker/CodeCheckerTest.php
  tests/lib/App/CodeChecker/DeprecationCheckTest.php
  tests/lib/App/CodeChecker/InfoCheckerTest.php
  tests/lib/App/CodeChecker/Mock/TestList.php
  tests/lib/App/CodeChecker/NodeVisitorTest.php
  tests/lib/App/CodeChecker/StrongComparisonCheckTest.php
Labels: 3. to review, technical debt

#25635 Use correct namespace (casing) in CalendarHome
  apps/dav/lib/CalDAV/CalendarHome.php
Labels: 3. to review, enhancement

#25580 Enhancing the dav pluginmanager
  apps/dav/lib/AppInfo/PluginManager.php
  apps/dav/tests/unit/AppInfo/PluginManagerTest.php
Labels: 3. to review, enhancement

#25644 Some psalm fixes in the settings app
  apps/settings/lib/Controller/HelpController.php
  apps/settings/lib/Mailer/NewUserMailHelper.php
Labels: 3. to review, enhancement

#25645 Some OCS result psalm fixes
  lib/private/OCS/Result.php
Labels: 3. to review, enhancement

#25646 Markdown: remove redundant int cast
  lib/private/Preview/MarkDown.php
Labels: 3. to review, enhancement

#25636 Add some closure return types
  apps/accessibility/lib/Controller/ConfigController.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJob.php
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
Labels: 3. to review, enhancement

#25625 Check substr results
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
Labels: 3. to review, enhancement

#25575 Add tests for \OC\Core\Service\LoginFlowV2Service
  tests/Core/Service/LoginFlowV2ServiceUnitTest.php
Labels: 3. to review, enhancement

#25578 Always use the cache
  apps/weather_status/lib/Service/WeatherStatusService.php
Labels: 3. to review

#25594 Use ownerDisplayName for SharingEntry Tooltip
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntry.vue
Labels: 3. to review, enhancement

#25595 Move getChangesForCalendar to QueryBuilder
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, enhancement, feature: dav

#25653 Some psalm OfflineUser fixes
  apps/user_ldap/lib/User/OfflineUser.php
Labels: 3. to review, enhancement

#25655 Fix app icon list in dark mode
  apps/accessibility/css/dark.scss
Labels: 3. to review, backport-request, bug, feature: settings

#25654 move AbstractCacheEvent into OCP
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Files/Cache/AbstractCacheEvent.php
  lib/public/Files/Cache/CacheEntryInsertedEvent.php
  lib/public/Files/Cache/CacheEntryRemovedEvent.php
  lib/public/Files/Cache/CacheEntryUpdatedEvent.php
Labels: 3. to review

#25661 Updated CRL
  resources/codesigning/root.crl
Labels: 3. to review, backport-request, enhancement

#25664 Fix some RedundantCast in dav code
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/Provisioning/Apple/AppleProvisioningPlugin.php
Labels: 3. to review, enhancement

#25669 Harden EncryptAll check for empty email
  apps/encryption/lib/Crypto/EncryptAll.php
Labels: 3. to review, enhancement

#25678 Drop \OCP\Defaults::getLogoClaim
  lib/public/Defaults.php
  themes/example/defaults.php
Labels: 4. to release, technical debt

#25440 Cache the user backend info for 5mins
  apps/user_ldap/tests/LDAPProviderTest.php
  lib/private/User/Manager.php
  tests/lib/Files/Config/UserMountCacheTest.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/Files/Stream/EncryptionTest.php
  tests/lib/User/ManagerTest.php
  tests/lib/User/SessionTest.php
Labels: 2. developing, bug, feature: users and groups, performance 🚀

#25668 Move getChangesForAddressBook to QueryBuilder
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 3. to review, enhancement, feature: dav

#25697 bump applicable version due to an intermediate release
  lib/private/Repair/RepairDavShares.php
Labels: 3. to review, backport-request, bug

#25681 Cleanup appinfo usage
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/AppsController.php
Labels: 3. to review, technical debt

#25700 Initialize \OCP\AppFramework\Http\ZipResponse::$resources
  lib/public/AppFramework/Http/ZipResponse.php
Labels: 3. to review, backport-request, bug

#25706 When coding style kicks in
  lib/private/DB/MigrationService.php
Labels: 3. to review, technical debt

#25707 Send emails on password reset to the displayname
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3. to review, bug, feature: users and groups

#25495 19.0.9 RC1
  version.php
Labels: 2. developing, overview

#25494 20.0.8 RC1
  version.php
Labels: 2. developing, overview

#24978 ReplyTo option for sharebymail Issue #24139
  apps/sharebymail/js/settings-admin.js
  apps/sharebymail/lib/Settings/Admin.php
  apps/sharebymail/lib/Settings/SettingsManager.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/templates/settings-admin.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
Labels: 4. to release, enhancement, feature: emails, feature: sharing

#25600 21 final
  version.php
Labels: 2. developing, overview

#25689 Hide update channel + button when web update is disabled
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/lib/Controller/AdminController.php
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/src/components/UpdateNotification.vue
  apps/updatenotification/templates/admin.php
  apps/updatenotification/tests/Settings/AdminTest.php
Labels: 3. to review, enhancement, feature: install and update

#25602 Avoid creating two share links when password is enforced
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/src/components/SharingEntryLink.vue
Labels: 3. to review, backport-request, bug, feature: sharing

#25680 Add expression taint source and sanitizer
  lib/public/DB/QueryBuilder/IExpressionBuilder.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  lib/public/IDBConnection.php
Labels: 3. to review, security

#25743 Disable basic PHP completion in Codespace
  .devcontainer/devcontainer.json
Labels: 4. to release, bug

#25719 20.0.8 final
  version.php
Labels: 2. developing, overview

#25720 19.0.9 final
  version.php
Labels: 2. developing, overview

#25786 Register service aliases und parameters just once
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
Labels: 3. to review, backport-request, bug, feature: apps management, feature: install and update

#24255 Add focus-visible outline for checkboxes and radio buttons
  apps/files/css/files.scss
  core/css/inputs.scss
Labels: 3. to review, bug, design
