Repository nextcloud/server, pull requests merged in 2022-11, with the labels that each got.

#34906 update 64-bit check wording
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 4. to release, backport-request

#34908 disable upgrades to 26 for 32-bit
  lib/private/Updater.php
Labels: 3. to review, backport-request, pending documentation

#34871 Fix visibility of internal expire date
  apps/files_sharing/src/components/SharingEntry.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, backport-request

#34907 remove 32-bit workarounds
  lib/private/Files/Storage/Local.php
  lib/private/Setup.php
  lib/private/Streamer.php
  lib/private/legacy/OC_Response.php
Labels: 3. to review

#34915 23.0.11
  version.php
Labels: 3. to review

#34914 24.0.7
  version.php
Labels: 3. to review

#34913 25.0.1
  version.php
Labels: 3. to review

#34852 Add remote host validation API
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Http/Client/Client.php
  lib/private/Http/Client/ClientService.php
  lib/private/Http/Client/DnsPinMiddleware.php
  lib/private/Http/Client/LocalAddressChecker.php
  lib/private/Net/HostnameClassifier.php
  lib/private/Net/IpAddressClassifier.php
  lib/private/Security/RemoteHostValidator.php
  lib/private/Server.php
  lib/public/Security/IRemoteHostValidator.php
  tests/lib/Http/Client/ClientServiceTest.php
  tests/lib/Http/Client/ClientTest.php
  tests/lib/Http/Client/LocalAddressCheckerTest.php
  tests/lib/Net/HostnameClassifierTest.php
  tests/lib/Net/IpAddressClassifierTest.php
  tests/lib/Security/RemoteHostValidatorIntegrationTest.php
  tests/lib/Security/RemoteHostValidatorTest.php
Labels: 3. to review, security

#34905 [stable25] fix NC25 for 32-bit
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
Labels: 3. to review

#33605 Use cached getDisplayName method
  apps/dav/lib/CalDAV/Activity/Provider/Base.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: 3. to review, performance 🚀

#34577 [stable25] Avoid double ldap_unbind in Wizard.php
  apps/user_ldap/lib/Wizard.php
Labels: 3. to review

#32565 Modernize the error handler
  lib/base.php
  lib/private/Log/ErrorHandler.php
  tests/lib/ErrorHandlerTest.php
Labels: 3. to review, backport-request, technical debt

#34678 Interlace all output JPEG
  lib/private/legacy/OC_Image.php
  tests/lib/ImageTest.php
Labels: 3. to review, feature: previews and thumbnails

#34934 Read encrypted session data again on reopen
  lib/private/Session/CryptoSessionData.php
Labels: bug, 4. to release, backport-request

#34954 Dump autoloaders for new IHandleImipMessage
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: bug, 4. to release

#34963 Fix invalid date in security.txt
  apps/settings/lib/WellKnown/SecurityTxtHandler.php
Labels: bug, 3. to review, backport-request

#34949 [stable24] Cleanup tempfiles after each cron job run
  cron.php
Labels: bug, 3. to review

#34950 [stable23] Cleanup tempfiles after each cron job run
  cron.php
Labels: bug, 3. to review

#34946 [stable25] Skip general login with email for non-valid addresses and LDAP
  lib/private/Authentication/Login/EmailLoginCommand.php
  tests/lib/Authentication/Login/EmailLoginCommandTest.php
Labels: bug, 3. to review

#34947 [stable24] Skip general login with email for non-valid addresses and LDAP
  lib/private/Authentication/Login/EmailLoginCommand.php
  tests/lib/Authentication/Login/EmailLoginCommandTest.php
Labels: bug, 3. to review

#34948 [stable23] Skip general login with email for non-valid addresses and LDAP
  lib/private/Authentication/Login/EmailLoginCommand.php
  tests/lib/Authentication/Login/EmailLoginCommandTest.php
Labels: bug, 3. to review

#34909 Fix duplicate event email notifications
  apps/dav/lib/CalDAV/Reminder/INotificationProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/AbstractProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/PushProviderTest.php
  apps/dav/tests/unit/CalDAV/Reminder/ReminderServiceTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
Labels: bug, 4. to release, backport-request, feature: caldav

#34844 [stable23] Fix: Prevent deadlocks during mtime/size/etag propagation
  lib/private/Files/Cache/Propagator.php
Labels: bug, 3. to review

#34834 Fix size calculation on copying the skeleton files
  lib/private/legacy/OC_Util.php
Labels: bug, 3. to review

#34702 Clean up LDAP Wizard typing
  apps/user_ldap/lib/ILDAPWrapper.php
  apps/user_ldap/lib/Wizard.php
Labels: 3. to review

#34775 Do not throw errors when invalid setTo email is provided
  lib/private/Mail/Message.php
  tests/lib/Mail/MessageTest.php
Labels: bug, 4. to release

#18210 Limit number of concurrent preview generations
  apps/settings/lib/Controller/CheckSetupController.php
  config/config.sample.php
  lib/private/Preview/Generator.php
  lib/private/PreviewManager.php
  tests/lib/Preview/GeneratorTest.php
Labels: enhancement, 2. developing, feature: previews and thumbnails, performance 🚀

#34987 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#34937 Avoid a crash when a PHP extension has no version
  lib/private/App/PlatformRepository.php
Labels: 3. to review, backport-request

#34929 Clean up and deprecate app container parameter aliases
  lib/private/AppFramework/DependencyInjection/DIContainer.php
Labels: 3. to review, technical debt

#35000 Fix cron warning with time insensitive jobs
  apps/settings/src/components/BasicSettings/BackgroundJob.vue
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
Labels: bug, 3. to review, backport-request

#35007 Fix unsuccessful token login logged as error
  lib/private/User/Session.php
Labels: bug, 3. to review, backport-request, feature: authentication

#32838 Cast to int
  apps/files/lib/Command/Scan.php
Labels: 3. to review, backport-request

#35028 Fix DNS Pin Middleware throwing for public IPs
  lib/private/Http/Client/DnsPinMiddleware.php
Labels: bug, 3. to review, 4. to release, regression

#32211 Add repair command to fix wrong share ownership
  core/Command/Maintenance/RepairShareOwnership.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 4. to release, feature: sharing, backport-request

#34613 fix checkmark for theme settings in dark mode
  apps/theming/src/components/BackgroundSettings.vue
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
Labels: design, 3. to review, backport-request

#35042 Add description for calendar uri
  lib/public/Calendar/ICalendar.php
Labels: 4. to release, feature: dav, backport-request, feature: caldav

#35052 Fix sidebar not automatically hidden in Files app
  apps/files/js/app.js
  apps/files/js/gotoplugin.js
Labels: bug, 3. to review, backport-request, feature: files

#34989 l10n: Shorten link
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review, feature: language l10n and translations

#35054 Fix HTML entities not decoded in comment just added
  apps/comments/src/services/GetComments.js
  apps/comments/src/services/NewComment.js
  apps/comments/src/utils/decodeHtmlEntities.js
  dist/comments-comments-app.js
  dist/comments-comments-app.js.LICENSE.txt
  dist/comments-comments-app.js.map
Labels: bug, 4. to release, backport-request, feature: comments

#35074 Make sure that path is normalized and then checked,
  lib/private/Files/Node/Folder.php
Labels: 3. to review, backport-request

#35049 [stable24] Fix size calculation on copying the skeleton files
  lib/private/legacy/OC_Util.php
Labels: bug, 3. to review

#35077 Fix PublicKeyTokenProviderTest import and mock
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
Labels: 4. to release, backport-request, technical debt

#35073 [stable23] Fix top margin in empty versions list
  apps/files_versions/js/files_versions.js
  apps/files_versions/js/files_versions.js.map
  apps/files_versions/src/css/versions.css
  package.json
Labels: bug, design, 4. to release

#35105 Fix distorted previews when using imaginary
  lib/private/Preview/Imaginary.php
Labels: bug, 4. to release, feature: previews and thumbnails, integration, pending documentation

#35015 Appropriate length check in Notification.php
  lib/private/Notification/Notification.php
Labels: bug, 3. to review

#34485 Fix hasBigIntConversionPendingColumns missing files_trash
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 3. to review

#34994 [Performance] Test valid path only if file info has to be retrieved
  lib/private/Files/Node/Node.php
Labels: 3. to review, performance 🚀

#34829 l10n: Improve styling
  lib/private/Support/Subscription/Assertion.php
Labels: 3. to review, feature: language l10n and translations

#34746 Add Calendar settings section
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Sections/Personal/Calendar.php
Labels: 3. to review, feature: settings, pending documentation, feature: caldav

#33482 Show version from appinfo on occ app:list
  core/Command/App/ListApps.php
Labels: bug, 3. to review, feature: apps management

#35070 [LDAP] always create instance of own user manager
  apps/user_ldap/lib/AppInfo/Application.php
Labels: bug, 4. to release, feature: ldap, backport-request, regression

#35096 Mark more config values as sensitive
  lib/private/AppConfig.php
  lib/private/SystemConfig.php
Labels: bug, 3. to review

#35093 Run integration tests on 3rdparty bump
  tests/drone-run-integration-tests.sh
Labels: 3. to review, backport-request

#34645 🐘 Support postgres15
  .drone.yml
  lib/private/Setup/PostgreSQL.php
Labels: bug, 4. to release, backport-request, feature: install and update, pending documentation

#35043 Update crl after revoke drawio.csr
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#35142 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 4. to release

#35139 Revert "Appropriate length check in Notification.php"
  lib/private/Notification/Notification.php
Labels: 3. to review

#35048 [stable25] Fix size calculation on copying the skeleton files
  lib/private/legacy/OC_Util.php
Labels: bug, 3. to review

#35075 Remove reference to Redis sentinel from configuration docs
  config/config.sample.php
Labels: 3. to review

#35157 Make sure to not pass null to DateTime::createFromFormat
  apps/dav/lib/Files/FileSearchBackend.php
  apps/files_external/lib/Lib/Storage/FTP.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/workflowengine/lib/Check/RequestTime.php
Labels: 3. to review, backport-request

#35024 Deprecate PHP7.4
  apps/settings/lib/Controller/CheckSetupController.php
  core/js/setupchecks.js
Labels: 4. to release, backport-request

#35091 Allow single character search by default
  core/src/services/UnifiedSearchService.js
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  lib/private/TemplateLayout.php
Labels: 4. to release, backport-request, feature: search, accessibility

#35014 Fix rendering of login headline
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, 3. to review, backport-request

#35173 Add test for received share in share_folder
  build/integration/features/bootstrap/SharingContext.php
  build/integration/sharing_features/sharing-v1-part3.feature
Labels: 3. to review, technical debt

#35156 Fix dynamic properties and other problems in tests for PHP 8.2
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/BackgroundJob/CleanupInvitationTokenJobTest.php
  apps/dav/tests/unit/BackgroundJob/PruneOutdatedSyncTokensJobTest.php
  apps/dav/tests/unit/CalDAV/Reminder/ReminderServiceTest.php
  apps/dav/tests/unit/CardDAV/Activity/BackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/dav/tests/unit/Controller/InvitationResponseControllerTest.php
  apps/federatedfilesharing/tests/Settings/AdminTest.php
  apps/files_sharing/tests/ShareTest.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  apps/theming/tests/Settings/PersonalTest.php
  apps/theming/tests/Themes/DyslexiaFontTest.php
  lib/private/User/Session.php
  tests/lib/DB/MigrationsTest.php
  tests/lib/Encryption/Keys/StorageTest.php
  tests/lib/Security/VerificationToken/VerificationTokenTest.php
  tests/lib/Settings/ManagerTest.php
  tests/lib/Share20/ShareTest.php
Labels: 3. to review

#35114 [stable24] use the updated mariadb10.6 container in drone
  .drone.yml
Labels: 3. to review

#35181 Fix more tests for PHP 8.2
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  apps/theming/tests/Themes/DefaultThemeTest.php
  apps/theming/tests/ThemingDefaultsTest.php
  tests/lib/AppFramework/Http/RequestStream.php
Labels: 3. to review

#35051 [stable23] Use storage filter when fetching previews to cleanup
  lib/private/Files/AppData/AppData.php
  lib/private/Preview/BackgroundCleanupJob.php
  lib/private/Preview/Storage/Root.php
Labels: bug, 3. to review, performance 🚀

#35029 Fix AppMenu icons for firefox
  core/src/components/AppMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, backport-request

#35033 fix dashboard scrolling
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: bug, 3. to review, backport-request

#35192 Fix github action "performance-8.0" when PR is from a fork.
  .github/workflows/performance.yml
Labels: bug, 2. developing

#35210 Fix settings for setting default expiration date
  apps/settings/src/admin.js
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: 4. to release, backport-request

#35184 fix s3 directory copy
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review

#34615 fix logo not correctly inverted
  apps/theming/lib/Themes/CommonThemeTrait.php
  apps/theming/lib/Util.php
  apps/theming/tests/CapabilitiesTest.php
  apps/theming/tests/IconBuilderTest.php
  apps/theming/tests/Themes/DefaultThemeTest.php
  apps/theming/tests/Themes/DyslexiaFontTest.php
  apps/theming/tests/UtilTest.php
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
  lib/private/Server.php
Labels: bug, design, 3. to review, backport-request

#35207 Fix sharing expiration date handling and saving
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 4. to release, high, feature: sharing, backport-request, regression

#35203 Default Jpeg quality to 80
  lib/private/legacy/OC_Image.php
  tests/lib/ImageTest.php
Labels: enhancement, 4. to release

#35199 [stable25] Mark more config values as sensitive
  lib/private/AppConfig.php
  lib/private/SystemConfig.php
Labels: bug, 3. to review

#35200 [stable24] Mark more config values as sensitive
  lib/private/AppConfig.php
  lib/private/SystemConfig.php
Labels: bug, 3. to review

#35202 [stable23] Mark more config values as sensitive
  lib/private/AppConfig.php
  lib/private/SystemConfig.php
Labels: bug, 3. to review

#35194 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35224 Drop deprecated node-sass
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#35009 Check quota on file copy
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
Labels: 4. to release, backport-request

#35225 Do not auto merge package-lock.json, but treat as text file
  .gitattributes
Labels: 4. to release

#35090 Close global search menu when keyboard focus leaves
  core/src/components/HeaderMenu.vue
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 4. to release, backport-request, feature: search, accessibility

#35170 User status dialog a11y: make different focus and active state
  apps/user_status/src/components/OnlineStatusSelect.vue
  apps/user_status/src/components/PredefinedStatus.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 4. to release

#35218 delay updating setup providers untill we register the mounts
  lib/private/Files/SetupManager.php
Labels: 4. to release, backport-request

#35182 generate user themed icons
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Service/JSDataService.php
  apps/theming/lib/Service/ThemeInjectionService.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/lib/Util.php
  apps/theming/tests/ThemingDefaultsTest.php
Labels: bug, 4. to release, backport-request

#35259 Also cancel XHR when cancelling uploads
  apps/files/js/file-upload.js
Labels: bug, 4. to release, backport-request

#35253 Fix warnings in dev mode on login page
  core/src/components/MainMenu.js
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 4. to release

#35256 [stable25] Fix default theming variables
  apps/theming/css/default.css
  apps/theming/css/settings-admin.css
  apps/theming/css/settings-admin.scss
  apps/theming/lib/Themes/CommonThemeTrait.php
  apps/theming/lib/Themes/DarkHighContrastTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Themes/HighContrastTheme.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/ThemingDefaultsTest.php
  core/css/guest.css
Labels: 4. to release, feature: theming, regression

#34677 optimize background image migration job
  apps/theming/lib/Jobs/MigrateBackgroundImages.php
  apps/theming/lib/Migration/InitBackgroundImagesMigration.php
Labels: 4. to release, feature: theming, feature: install and update

#35269 Remove completed comments
  apps/theming/src/components/admin/TextField.vue
  dist/theming-admin-theming.js
  dist/theming-admin-theming.js.map
Labels: 3. to review, feature: theming

#35245 [stable24] Fix JSON error when comment has no reactions
  lib/private/Comments/Manager.php
Labels: bug, 3. to review, feature: comments

#35185 Hide warning about missing apps for when shipped in the next version
  apps/updatenotification/lib/Controller/APIController.php
Labels: bug, 4. to release, backport-request

#35251 Increase the fair-use push limit to 1.000 users
  lib/private/Notification/Manager.php
  tests/lib/Notification/ManagerTest.php
Labels: bug, 4. to release, backport-request, feature: activity and notification

#35187 Fix mentions rendering in comment editor
  apps/comments/src/components/Comment.vue
  apps/comments/src/views/Comments.vue
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
Labels: enhancement, 3. to review, backport-request, feature: comments

#35241 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#34745 Extract $ignoreMaxApps from array_map callback in AppSettingsController
  apps/settings/lib/Controller/AppSettingsController.php
Labels: 4. to release, feature: apps management, performance 🚀

#35183 [stable25] Update CODEOWNERS
  .github/CODEOWNERS
Labels: 3. to review

#34528 Handle badly named version files more gracefully and log information
  apps/files_versions/lib/Storage.php
Labels: 3. to review, backport-request

#35308 Don't use quota cache through user management
  apps/provisioning_api/lib/Controller/AUserData.php
  lib/private/legacy/OC_Helper.php
Labels: bug, 4. to release, backport-request, feature: users and groups, regression

#35250 [stable24] Properly compare quota against both float/int values
  lib/private/Files/Storage/Wrapper/Quota.php
Labels: bug, 3. to review

#35318 Remove potential mismatching dav session data during login
  lib/private/User/Session.php
Labels: bug, 3. to review

#35312 [stable25] Don't use quota cache through user management
  apps/provisioning_api/lib/Controller/AUserData.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review

#35313 [stable24] Don't use quota cache through user management
  apps/provisioning_api/lib/Controller/AUserData.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review

#35226 Only setup redis connection if needed
  lib/private/Memcache/Redis.php
Labels: 3. to review, performance 🚀

#35309 Help pages: set window title for sidebar sections
  apps/settings/lib/Controller/HelpController.php
Labels: 4. to release, backport-request

#35206 Fix forwarding the object id when searching comments
  lib/private/Comments/Manager.php
Labels: bug, 3. to review, backport-request, feature: comments

#35143 Add pull request template with checklist
  .github/pull_request_template.md
Labels: 3. to review

#35299 Prevents the selection of encrypted folders when clicking on the "Select all" checkbox
  apps/files/css/files.css
  apps/files/css/files.css.map
  apps/files/css/files.scss
  apps/files/css/merged.css
  apps/files/css/merged.css.map
  apps/files/js/filelist.js
Labels: 3. to review

#35338 [stable25] Fix navigation order
  lib/private/NavigationManager.php
Labels: 3. to review

#35315 Fix border color contrast
  apps/theming/css/default.css
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
Labels: 4. to release, backport-request, accessibility

#35302 Generate proper URL for unsupported browsers page
  core/src/utils/RedirectUnsupportedBrowsers.js
  dist/core-unsupported-browser-redirect.js
  dist/core-unsupported-browser-redirect.js.map
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
Labels: bug, 4. to release

#35328 [stable24] Check quota on file copy
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
Labels: 3. to review

#35326 [stable25] optimize background image migration job
  apps/theming/lib/Jobs/MigrateBackgroundImages.php
  apps/theming/lib/Migration/InitBackgroundImagesMigration.php
Labels: 4. to release

#35327 [stable25] Handle badly named version files more gracefully and log information
  apps/files_versions/lib/Storage.php
Labels: 3. to review, backport-request

#35321 [stable24] Fix mentions rendering in comment editor
  apps/comments/src/components/Comment.vue
  apps/comments/src/views/Comments.vue
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
Labels: enhancement, 3. to review, feature: comments

#35353 Update cache when file size === 0
  lib/private/Files/View.php
Labels: bug, 4. to release, backport-request, feature: files

#35018 [stable24] Only show cron warning after 24h due to time insensitive jobs
  apps/settings/templates/settings/admin/server.php
Labels: bug, 3. to review

#35349 [stable24] Prevents the selection of encrypted folders when clicking on the "Select all" checkbox
  apps/files/css/files.scss
  apps/files/js/filelist.js
Labels: 3. to review

#35317 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35350 Fix user settings layout
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 4. to release, backport-request, feature: users and groups, feature: settings, regression

#35368 Add repair job that will ensure that secret and passwordsalt are set
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC25/AddMissingSecretJob.php
Labels: 3. to review

#35272 Add label to sharing search field
  apps/files_sharing/src/components/SharingInput.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  tests/acceptance/features/bootstrap/FilesAppSharingContext.php
Labels: 4. to release, feature: sharing, backport-request, accessibility

#35383 Fix PHP lint CI failure
  lib/private/Repair/NC25/AddMissingSecretJob.php
Labels: 3. to review, backport-request, php

#35370 Fix UX of renaming token
  apps/settings/src/components/AuthToken.vue
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
Labels: 3. to review, backport-request

#35380 fix remaining user settings issues
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
Labels: bug, 3. to review

#35335 Revert "[stable25] Fix quota type to int"
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_Util.php
Labels: 3. to review

#34642 Revert minimum length for tags
  apps/systemtags/src/systemtagsfilelist.js
  core/src/systemtags/systemtagsinputfield.js
  dist/core-systemtags.js
  dist/core-systemtags.js.map
  dist/systemtags-systemtags.js
  dist/systemtags-systemtags.js.map
Labels: bug, 3. to review, backport-request, regression

#35398 Do not check quota for non Node
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
Labels: bug, 4. to release, feature: dav, backport-request

#35027 fix missing share icon
  apps/files_sharing/css/icons.css
  apps/files_sharing/css/icons.css.map
  apps/files_sharing/css/icons.scss
  apps/user_status/css/user-status-menu.css
  apps/user_status/css/user-status-menu.css.map
  apps/user_status/css/user-status-menu.scss
Labels: bug, 4. to release, backport-request

#35228 user_ldap - Cache group display name even if it was not filled
  apps/user_ldap/lib/Group_LDAP.php
Labels: 3. to review

#35230 Log switching to LDAP backup host because main one is not available
  apps/user_ldap/lib/Connection.php
Labels: 3. to review

#35399 Fix share admin page
  apps/settings/src/admin.js
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: 4. to release, backport-request

#35407 More appropriate wording for background selection
  apps/theming/src/components/BackgroundSettings.vue
  dist/settings-vue-settings-apps-users-management.js.map
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
  dist/user_status-menu.js.map
  package-lock.json
  package.json
Labels: 3. to review

#35414 [stable25] Fix share admin page
  apps/settings/src/admin.js
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: bug, 3. to review, regression

#35415 [stable25] Fix theming tests
  tests/acceptance/features/app-theming.feature
Labels: 3. to review, backport-request, feature: theming, tests

#35334 Revert "[stable24] Fix quota type to int"
  build/psalm-baseline.xml
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_Util.php
Labels: 3. to review

#35412 [stable25] Place ```<h1>``` into main content
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: 3. to review

#35305 25.0.2 RC1
  version.php
Labels: 3. to review

#35307 23.0.12 RC1
  version.php
Labels: 3. to review

#34849 Add an hint about reasons why files can't be accessed
  apps/dav/lib/Connector/Sabre/Directory.php
Labels: 3. to review

#35337 skip files that cant be opened for FixEncryptedVersion
  apps/encryption/lib/Command/FixEncryptedVersion.php
Labels: 3. to review

#35434 fix update for 32-bit
  lib/private/Updater.php
Labels: bug, 3. to review, high, backport-request

#35403 Fix theming tests for PHP 8.2
  apps/theming/tests/ThemingDefaultsTest.php
Labels: 3. to review

#35257 Set page titel for each sidebar section through User management pages
  apps/settings/src/constants/AppsConstants.js
  apps/settings/src/router.js
  apps/settings/src/store/apps.js
  apps/settings/src/views/Apps.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.LICENSE.txt
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, accessibility

#35425 minimum desktop client that is supported is 2.3.0
  apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php
  apps/dav/tests/unit/Connector/Sabre/BlockLegacyClientPluginTest.php
  config/config.sample.php
Labels: 3. to review

#35454 [stable25] Revert "[stable25] Fix border color contrast"
  apps/theming/css/default.css
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  tests/acceptance/features/app-theming.feature
Labels: 4. to release, high

#34941 Add a Group display name cache
  apps/files_sharing/lib/AppInfo/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Group/DisplayNameCache.php
  lib/private/Group/Group.php
  lib/private/Group/Manager.php
  lib/private/Server.php
  lib/public/Group/Events/GroupChangedEvent.php
  lib/public/IGroupManager.php
  tests/lib/Group/ManagerTest.php
Labels: 3. to review, pending documentation, performance 🚀
