Repository nextcloud/server, pull requests merged in 2022-04, with the labels that each got.

#30550 l10n: Change "rain" to "rainfall"
  apps/weather_status/src/App.vue
  dist/weather_status-weather-status.js
  dist/weather_status-weather-status.js.map
Labels: enhancement, feature: language l10n and translations

#31782 Fix ldap wizard styling
  apps/user_ldap/css/settings.css
Labels: bug, 3. to review, feature: ldap

#31750 Convert deprecation warnings to exception in phpunit
  tests/phpunit-autotest.xml
Labels: 3. to review

#30438 Fix column/property types in CalDAV
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: bug, 4. to release, backport-request

#31687 Allow app passwords without login password for occ user:add-app-password
  core/Command/User/AddAppPassword.php
Labels: enhancement, 3. to review, feature: authentication

#30823 Built-in profiler
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Profiler/ProfilerPlugin.php
  apps/dav/lib/Server.php
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/DataCollector/LdapDataCollector.php
  apps/user_ldap/lib/LDAP.php
  build/psalm-baseline.xml
  config/config.sample.php
  core/templates/layout.user.php
  lib/autoloader.php
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/App.php
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/Cache/CappedMemoryCache.php
  lib/private/Cache/File.php
  lib/private/DB/Connection.php
  lib/private/DB/DbDataCollector.php
  lib/private/DB/ObjectParameter.php
  lib/private/Diagnostics/EventLogger.php
  lib/private/Memcache/APCu.php
  lib/private/Memcache/ArrayCache.php
  lib/private/Memcache/Factory.php
  lib/private/Memcache/LoggerWrapperCache.php
  lib/private/Memcache/Memcached.php
  lib/private/Memcache/NullCache.php
  lib/private/Memcache/ProfilerWrapperCache.php
  lib/private/Memcache/Redis.php
  lib/private/Profiler/FileProfilerStorage.php
  lib/private/Profiler/Profile.php
  lib/private/Profiler/Profiler.php
  lib/private/Profiler/RoutingDataCollector.php
  lib/private/Server.php
  lib/public/DataCollector/AbstractDataCollector.php
  lib/public/DataCollector/IDataCollector.php
  lib/public/ICache.php
  lib/public/Profiler/IProfile.php
  lib/public/Profiler/IProfiler.php
  tests/lib/AppFramework/AppTest.php
  tests/lib/Memcache/FactoryTest.php
Labels: 4. to release

#31776 cache storage id mapping both ways
  lib/private/Files/Cache/Storage.php
  lib/private/Files/Cache/StorageGlobal.php
Labels: 3. to review, performance 🚀

#31734 dont re-query fileinfo when getting dav quota
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, backport-request, performance 🚀

#31828 Do not ignore return value of deleteGroup from backend
  lib/private/Group/Group.php
Labels: 3. to review

#31820 Explicitly close div element
  apps/files/js/fileactions.js
  apps/files/js/files.js
  apps/files/js/sidebarpreviewtext.js
  apps/files_external/js/settings.js
  apps/files_sharing/js/public.js
  core/src/OC/eventsource.js
  core/src/components/MainMenu.js
  core/src/components/UserMenu.js
  core/src/jquery/ocdialog.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review, regression

#31827 Set oc_share_external.name column length to 4000 to remove arbitrary …
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Migration/Version24000Date20220404142216.php
Labels: 3. to review

#31773 Perform a limited filesystem setup when getting share source
  apps/files_sharing/lib/SharedStorage.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_versions/lib/Storage.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Config/MountProviderCollection.php
  lib/private/Files/Mount/Manager.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/LazyRoot.php
  lib/private/Files/Node/LazyUserFolder.php
  lib/private/Files/Node/Node.php
  lib/private/Files/Node/Root.php
  lib/private/Files/SetupManager.php
  lib/private/Files/Utils/PathHelper.php
  lib/public/Files/Config/IMountProviderCollection.php
  lib/public/Files/IRootFolder.php
  tests/lib/Files/Node/FileTest.php
  tests/lib/Files/Node/FolderTest.php
  tests/lib/Files/Node/NodeTest.php
Labels: 3. to review, performance 🚀

#31684 take permissions from multiple paths into account for share permissions
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: 2. developing, backport-request

#31838 [stable22] Fix bug with adding multiple emails in a single input box
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
Labels: bug, 4. to release, feature: settings, feature: emails

#31849 Cache account information
  lib/private/Accounts/AccountManager.php
Labels: 3. to review

#31194 Allow to disable password policy enforcement for selected groups
  apps/files_sharing/tests/CapabilitiesTest.php
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/admin.js
  apps/settings/templates/settings/admin/sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  config/config.sample.php
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
  lib/private/Share20/Manager.php
  lib/private/legacy/OC_Util.php
  lib/public/Share/IManager.php
  lib/public/Util.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release

#31594 Log in audit log federated shares events
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/tests/Controller/RequestHandlerControllerTest.php
Labels: 3. to review

#31853 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31844 only setup home mount when getting home folder
  apps/files/lib/Controller/AjaxController.php
  lib/private/Files/SetupManager.php
Labels: 4. to release, performance 🚀

#31843 Improve performance dav PROPFIND
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Connector/Sabre/Node.php
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  apps/dav/tests/unit/Connector/Sabre/ObjectTreeTest.php
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/View.php
  tests/lib/Files/Node/FolderTest.php
Labels: 3. to review, performance 🚀

#31852 Test migration of account information
  apps/settings/tests/UserMigration/AccountMigratorTest.php
  apps/settings/tests/UserMigration/assets/account-complex.json
  apps/settings/tests/UserMigration/assets/account.json
Labels: 3. to review, feature: user migration

#31833 record backtrace when profiling db requests
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/DB/BacktraceDebugStack.php
  lib/private/DB/Connection.php
  lib/private/DB/DbDataCollector.php
Labels: 3. to review

#31864 Generate small preview straight away if Imaginary is enabled
  lib/private/Preview/Generator.php
Labels: 3. to review, feature: previews and thumbnails, technical debt

#25747 Add X-Accel-Buffering header to downloads
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/tests/unit/Connector/Sabre/FilesPluginTest.php
  lib/private/Streamer.php
  lib/private/legacy/OC_Files.php
Labels: enhancement, 4. to release

#31825 Add missing doc changes and limit string length 4000 to new columns
  lib/private/DB/MigrationService.php
Labels: bug, 3. to review

#31877 Do not decorate the CLI output if it's explicitly turned off
  lib/private/Console/TimestampFormatter.php
Labels: bug, 3. to review, backport-request, feature: install and update, 22-feedback

#31673 Contacts migration
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/UserMigration/ContactsMigrator.php
  apps/dav/lib/UserMigration/ContactsMigratorException.php
  apps/dav/lib/UserMigration/InvalidAddressBookException.php
  apps/dav/tests/integration/UserMigration/CalendarMigratorTest.php
  apps/dav/tests/integration/UserMigration/ContactsMigratorTest.php
  apps/dav/tests/integration/UserMigration/assets/address_books/contact-complex.vcf
  apps/dav/tests/integration/UserMigration/assets/address_books/contact-multiple-complex.vcf
  apps/dav/tests/integration/UserMigration/assets/address_books/contact-multiple.vcf
  apps/dav/tests/integration/UserMigration/assets/address_books/contact.vcf
  apps/dav/tests/integration/UserMigration/assets/calendars/event-alarms.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-attendees.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-categories.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-complex-alarm-recurring.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-complex-recurrence.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-custom-color.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-multiple-recurring.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-multiple.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-recurring.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/event-timed.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/journal-todo-event.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/journal.ics
  apps/dav/tests/integration/UserMigration/assets/calendars/todo.ics
Labels: enhancement, 3. to review, feature: dav, feature: carddav, feature: user migration

#31847 Retrieve user status only once when displaying page
  apps/user_status/src/menu.js
  core/templates/layout.user.php
  dist/user_status-menu.js
  dist/user_status-menu.js.map
  lib/private/TemplateLayout.php
Labels: enhancement, 4. to release, feature: status

#31845 Use querybuilder for share external mountpoint
  apps/files_sharing/lib/External/MountProvider.php
Labels: 3. to review, feature: sharing, feature: federation, technical debt

#31832 fix filelist not loading after refresh in firefox
  apps/files/js/filelist.js
  apps/files/tests/js/filelistSpec.js
Labels: 4. to release

#31713 Federated share performance improvements
  apps/files_sharing/lib/External/Storage.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Propagator.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Storage/DAV.php
  lib/public/Files/Storage/IReliableEtagStorage.php
Labels: 3. to review, performance 🚀

#31871 24.0.0 beta 3
  version.php
Labels: 3. to review

#31879 update the wording of external storage deletion
  apps/files_external/js/settings.js
Labels: enhancement, 3. to review, feature: external storage

#31867 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31887 Log missing primary key until we make it a requirement
  lib/private/DB/MigrationService.php
Labels: 4. to release, technical debt

#31676 Add public API for owner based file locking
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Lock/LockManager.php
  lib/private/Server.php
  lib/public/DirectEditing/IManager.php
  lib/public/Files/Lock/ILock.php
  lib/public/Files/Lock/ILockManager.php
  lib/public/Files/Lock/ILockProvider.php
  lib/public/Files/Lock/LockContext.php
  lib/public/Files/Lock/NoLockProviderException.php
  lib/public/Files/Lock/OwnerLockedException.php
Labels: enhancement, 4. to release, high, feature: locking

#31901 Filesystem setup tweaks
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/LazyUserFolder.php
  lib/private/Files/SetupManager.php
Labels: 4. to release

#31908 Fix LDAP Dark Theme Issue
  apps/user_ldap/css/settings.css
Labels: bug, 4. to release

#31914 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31903 Fix case also when the table existed already
  apps/files_external/lib/Migration/Version1011Date20200630192246.php
Labels: bug, 3. to review, feature: install and update

#31911 Extend migrators needed for implementation of the API
  apps/dav/lib/UserMigration/CalendarMigrator.php
  apps/dav/lib/UserMigration/ContactsMigrator.php
  apps/files_trashbin/lib/UserMigration/TrashbinMigrator.php
  apps/settings/lib/UserMigration/AccountMigrator.php
  lib/public/UserMigration/IMigrator.php
Labels: 3. to review, feature: user migration

#31857 Add settings to not match userID during full match
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/admin.js
  apps/settings/templates/settings/admin/sharing.php
  build/integration/features/bootstrap/CollaborationContext.php
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
  lib/private/Collaboration/Collaborators/UserPlugin.php
Labels: 3. to review, feature: sharing, backport-request, feature: search

#31610 fix shared mount roots not being returned from `getSharesInFolder`
  lib/private/Share20/DefaultShareProvider.php
Labels: bug, 3. to review, backport-request

#31848 Don't inject Bruteforce capability info in the webui
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/CapabilitiesManager.php
  lib/private/Security/Bruteforce/Capabilities.php
  lib/private/Template/JSConfigHelper.php
  lib/public/Capabilities/IInitialStateExcludedCapability.php
Labels: 3. to review, technical debt, performance 🚀

#31925 Use Migrators id instead of class names
  apps/dav/lib/UserMigration/CalendarMigrator.php
  apps/dav/lib/UserMigration/ContactsMigrator.php
  apps/files_trashbin/lib/UserMigration/TrashbinMigrator.php
  apps/settings/lib/UserMigration/AccountMigrator.php
  apps/settings/tests/UserMigration/AccountMigratorTest.php
  lib/public/UserMigration/IImportSource.php
  lib/public/UserMigration/IMigrator.php
  lib/public/UserMigration/TMigratorBasicVersionHandling.php
Labels: 3. to review

#31931 Wrap contact search result in a link
  core/src/OC/contactsmenu/contact.handlebars
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: enhancement, 3. to review, feature: contacts menu

#31866 Test migration of avatars
  apps/settings/tests/UserMigration/AccountMigratorTest.php
  apps/settings/tests/UserMigration/assets/account-complex.jpg
  apps/settings/tests/UserMigration/assets/account.png
Labels: 4. to release, feature: user migration

#31927 Tweak tests to include shareapi_restrict_user_enumeration_full_match_userid
  apps/settings/tests/Settings/Admin/SharingTest.php
Labels: 3. to review

#31220 Temporary passwords for public non-anonymous protected shares (ie: files shared with an email recipient).
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/composer/composer/installed.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/lib/Migration/Version24000Date20220208195521.php
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  core/css/publicshareauth.css
  core/js/publicshareauth.js
  core/templates/publicshareauth.php
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  lib/private/Share20/Manager.php
  lib/private/Share20/ProviderFactory.php
  lib/private/Share20/Share.php
  lib/public/AppFramework/AuthPublicShareController.php
  lib/public/Share/IShare.php
  tests/lib/AppFramework/Controller/AuthPublicShareControllerTest.php
Labels: enhancement, 2. developing, feature: sharing

#31934 perform a setup if we can't find any mounts containing a file
  lib/private/Files/Node/Root.php
Labels: 3. to review

#31907 confirm user is internal to globalscale
  lib/private/Collaboration/Collaborators/LookupPlugin.php
  tests/lib/Collaboration/Collaborators/LookupPluginTest.php
Labels: 4. to release, backport-request

#31929 Expose ZIP stat information
  build/stubs/zip.php
  lib/private/Archive/ZIP.php
  psalm.xml
Labels: 3. to review

#31937 l10n: Remove comma
  apps/dav/lib/UserMigration/CalendarMigrator.php
Labels: 4. to release, feature: language l10n and translations

#31910 Fix accept/reject remote share action #31301
  apps/files_sharing/js/app.js
  dist/files_sharing-files_sharing.js
  dist/files_sharing-files_sharing.js.map
Labels: bug, 4. to release

#31942 Fix warning about optional parameter before required one
  apps/dav/lib/CalDAV/CalendarRoot.php
Labels: 3. to review, feature: dav, feature: caldav

#31889 Allow to autocomplete user and group ids in commands
  core/Command/Group/AddUser.php
  core/Command/Group/Delete.php
  core/Command/Group/Info.php
  core/Command/Group/RemoveUser.php
  core/Command/User/Delete.php
  core/Command/User/Disable.php
  core/Command/User/Enable.php
  core/Command/User/Info.php
  core/Command/User/LastSeen.php
  core/Command/User/ResetPassword.php
  core/Command/User/Setting.php
Labels: enhancement, 4. to release, feature: users and groups, feature: occ

#31933 update CRL after revocation of socialsharing_telegram.csr
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#31946 [23] AmazonS3: allow not implemented versioning
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review

#31965 Properly reset pw expiration
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/sharebymail/lib/ShareByMailProvider.php
  lib/private/Share20/Manager.php
Labels: bug, 4. to release, feature: sharing

#31945 Adapt user_migration APIs to have information about failures
  apps/dav/lib/UserMigration/CalendarMigrator.php
  apps/dav/lib/UserMigration/ContactsMigrator.php
  apps/files_trashbin/lib/UserMigration/TrashbinMigrator.php
  apps/settings/lib/UserMigration/AccountMigrator.php
  apps/settings/tests/UserMigration/AccountMigratorTest.php
  lib/public/UserMigration/IExportDestination.php
  lib/public/UserMigration/IImportSource.php
Labels: 4. to release

#31969 Catch avatar export separately for better failure tracing
  apps/settings/lib/UserMigration/AccountMigrator.php
Labels: 4. to release, feature: user migration

#17087 Add stale action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: 3. to review

#31453 [stable23] Run tests with primary object storage in CI + large upload fixes
  .github/workflows/s3-primary.yml
  apps/dav/lib/Connector/Sabre/File.php
  apps/files_sharing/tests/CacheTest.php
  apps/files_trashbin/tests/StorageTest.php
  lib/private/Files/Cache/Storage.php
  tests/lib/User/UserTest.php
Labels: 3. to review

#31878 [stable23] Fix incorrect if conditions in View
  lib/private/Files/View.php
Labels: 4. to release, backport-request

#31949 [stable23] Fix accept/reject remote share action
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
Labels: bug, 3. to review

#31886 Principal search by display name case insensitive
  apps/dav/lib/Connector/Sabre/Principal.php
Labels: 4. to release, backport-request, feature: caldav

#31975 Adjust settings for mail link password
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  config/config.sample.php
  lib/private/Share20/Manager.php
Labels: 4. to release

#31972 Add extra filter for file picker
  core/src/OC/dialogs.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: enhancement, 4. to release

#30860 handle notfound and notpermitted error in Smb::getDirectoryContent
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#31826 Log why the login token can't be used for credentials
  lib/private/Authentication/LoginCredentials/Store.php
Labels: bug, 3. to review, backport-request, feature: authentication

#31958 22.2.7 RC1
  version.php
Labels: 3. to review

#31961 23.0.4 RC1
  version.php
Labels: 3. to review

#31956 ⚠️ Master is now 25
  .github/dependabot.yml
  apps/accessibility/appinfo/info.xml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 2. developing

#31456 [stable22] Fix apps settings error message timeout
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users.js
  apps/settings/js/vue-vendors-settings-apps-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps.js
  apps/settings/js/vue-vendors-settings-apps.js.map
  apps/settings/js/vue-vendors-settings-users.js
  apps/settings/js/vue-vendors-settings-users.js.map
  apps/settings/src/store/apps.js
Labels: bug, 4. to release

#32009 Revert "[stable22] Fix apps settings error message timeout"
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users.js
  apps/settings/js/vue-vendors-settings-apps-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps.js
  apps/settings/js/vue-vendors-settings-apps.js.map
  apps/settings/js/vue-vendors-settings-users.js
  apps/settings/js/vue-vendors-settings-users.js.map
  apps/settings/src/store/apps.js
Labels: 3. to review

#32022 log stacktrace for 'Backends provided no user object'
  lib/private/Files/Node/Root.php
  tests/lib/Files/Node/RootTest.php
Labels: bug, 3. to review, backport-request

#32024 ignore forbidden files while scanning local storage
  lib/private/Files/Storage/Local.php
Labels: 3. to review, backport-request

#30311 Add unified search options
  core/src/services/UnifiedSearchService.js
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  lib/private/TemplateLayout.php
Labels: enhancement, 3. to review

#32021 Fix export of shared calendars
  apps/dav/lib/UserMigration/CalendarMigrator.php
  apps/dav/lib/UserMigration/ContactsMigrator.php
Labels: bug, 4. to release, feature: dav, backport-request, feature: caldav, feature: user migration

#31047 Additional index on oc_preferences to make queries without a user filter faster
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
  lib/private/AllConfig.php
Labels: enhancement, 3. to review, performance 🚀

#32042 improve optimization for SharedStorage::instanceOfStorage(Common)
  apps/files_sharing/lib/SharedStorage.php
Labels: bug, 3. to review, feature: filesystem, backport-request, performance 🚀

#32039 22.2.7
  version.php
Labels: 3. to review

#32037 23.0.4
  version.php
Labels: 3. to review

#32050 cache the share owner name for formatting cache entries
  apps/files_sharing/lib/Cache.php
Labels: 3. to review, backport-request, performance 🚀

#32049 Add known dav properties to ignore list
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: bug, 4. to release, backport-request, performance 🚀

#32048 cache storage info in memcache for 5m
  lib/private/legacy/OC_Helper.php
Labels: 4. to release, backport-request, performance 🚀

#32047 Cache display name
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Cache.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_sharing/tests/TestCase.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/User/DisplayNameCache.php
Labels: bug, 3. to review, feature: users and groups

#32045 cache fullSetupRequired locally
  lib/private/Files/SetupManager.php
Labels: 3. to review, backport-request, performance 🚀

#32053 cache the verification of the share mountpoint
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/SharedMount.php
  apps/files_sharing/tests/MountProviderTest.php
Labels: 3. to review, backport-request, performance 🚀

#32071 cache display names in local memory before external memcache
  lib/private/User/DisplayNameCache.php
Labels: 3. to review, backport-request, performance 🚀

#32063 [stable24] Add known dav properties to ignore list
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: bug, 4. to release, performance 🚀

#32051 [stable24] Fix Talk branch used by integration tests
  .drone.yml
Labels: bug, 3. to review

#32062 [stable24] cache storage info in memcache for 5m
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, performance 🚀

#32040 only register mounts that are new from providers that are new during a full setup
  lib/private/Files/Config/MountProviderCollection.php
  lib/private/Files/SetupManager.php
Labels: 3. to review, backport-request

#32076 use and cache root storage info if a share can't be resolved
  apps/dav/lib/Connector/Sabre/Directory.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, backport-request, performance 🚀

#32054 Verify that Talk could be enabled before executing the tests
  build/integration/sharing_features/sharing-v1-video-verification.feature
Labels: bug, 3. to review

#32109 Get not only time-sensitive next job from list but any when not in cron-mode
  cron.php
  lib/private/BackgroundJob/JobList.php
  tests/lib/BackgroundJob/DummyJobList.php
Labels: bug, 3. to review, backport-request

#32112 Add missing index for oc_mounts queries
  core/Migrations/Version24000Date20220202150027.php
  core/Migrations/Version24000Date20220404230027.php
  core/Migrations/Version24000Date20220425072957.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/autoload_static.php
  lib/private/Metadata/FileMetadata.php
  version.php
Labels: bug, 3. to review, feature: filesystem

#32079 optimize adding submount info to directory content
  lib/private/Files/View.php
Labels: 4. to release, backport-request, performance 🚀

#32082 use a lazy user for the file owner when listing a directory
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/View.php
  lib/private/User/LazyUser.php
Labels: 4. to release, backport-request, performance 🚀

#32070 [stable22] Do not update _lastChanged on auto-detected attributes
  apps/user_ldap/lib/Command/CreateEmptyConfig.php
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Controller/ConfigAPIController.php
Labels: bug, 3. to review, feature: ldap, backport-request

#32074 tell mysql to ignore the sort index for search queries
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Files/Cache/SearchBuilder.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
Labels: 3. to review, feature: search, performance 🚀

#32121 update description of cronjob settings to be aligned to the documenta…
  apps/settings/templates/settings/admin/server.php
Labels: enhancement, 4. to release, backport-request

#32033 Fix scanning app data with metadata
  lib/private/Metadata/FileEventListener.php
Labels: 3. to review

#32119 [stable24] Add missing index for oc_mounts queries
  core/Migrations/Version24000Date20220202150027.php
  core/Migrations/Version24000Date20220404230027.php
  core/Migrations/Version24000Date20220425072957.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Metadata/FileMetadata.php
  version.php
Labels: bug, 3. to review, feature: filesystem

#32114 fix showing of all apps are up-to-date in apps management
  apps/settings/src/components/AppList.vue
  dist/settings-apps-view-418.js
  dist/settings-apps-view-418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, backport-request, feature: apps management

#32147 Fix default fallback theme on setup any guests pages
  lib/private/TemplateLayout.php
Labels: design, 4. to release, feature: theming, regression

#32137 Give hints on correct migration versioning
  core/Command/Db/Migrations/GenerateCommand.php
Labels: 4. to release, feature: install and update, technical debt

#32115 [stable23] fix showing of all apps are up-to-date in apps management
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/src/components/AppList.vue
Labels: bug, 3. to review, backport-request, feature: apps management

#32155 Fx translations with trailing colon
  lib/private/L10N/L10NString.php
  tests/lib/L10N/L10nTest.php
Labels: bug, 4. to release, backport-request, feature: language l10n and translations

#31492 Require the secret config to be configured
  .github/workflows/s3-external.yml
  lib/private/legacy/OC_Util.php
Labels: 4. to release

#31467 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#32167 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: 3. to review, dependencies

#32154 l10n: Change apostrophe
  apps/settings/templates/settings/admin/server.php
Labels: 4. to release, backport-request, feature: language l10n and translations

#32173 l10n: Fix code
  lib/private/legacy/OC_Util.php
Labels: 4. to release, feature: language l10n and translations

#32034 Make the binary operation order explicit
  lib/private/Files/Config/UserMountCache.php
Labels: 3. to review

#32139 fix social sharing buttons
  apps/federatedfilesharing/css/settings-personal.scss
  apps/federatedfilesharing/templates/settings-personal.php
Labels: bug, design, 4. to release, backport-request

#32189 Mount Profile view after DOMContentLoaded
  core/src/profile.js
  dist/core-profile.js
  dist/core-profile.js.map
Labels: bug, 4. to release, backport-request, feature: profile

#32164 Adds uploadPartSize to config sample.
  config/config.sample.php
Labels: enhancement, 3. to review

#32172 l10n: Improve grammar of opcache message
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 4. to release, feature: language l10n and translations

#32200 l10n: Correct a typo
  lib/private/legacy/OC_Util.php
Labels: 3. to review, feature: language l10n and translations

#32195 Add system/light themes
  apps/theming/img/default-source.svg
  apps/theming/img/default.jpg
  apps/theming/img/light.jpg
  apps/theming/lib/Service/ThemesService.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Themes/LightTheme.php
  apps/theming/tests/Controller/UserThemeControllerTest.php
  apps/theming/tests/Service/ThemesServiceTest.php
  apps/theming/tests/Themes/DefaultThemeTest.php
Labels: enhancement, 3. to review, feature: theming

#32202 Fix `Undefined array key "enabledThemes"` on layout.user.php
  lib/private/TemplateLayout.php
Labels: bug, 4. to release, feature: theming

#32191 Handle processing reminders for calendar objects with an infinite number of recurrences
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
Labels: bug, 4. to release

#32207 24.0.0 RC3
  version.php
Labels: 4. to release

#32210 Remove deprecated occ app:check-code command
  core/Command/App/CheckCode.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review

#32204 Fix header logo and icons
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
  core/css/header.scss
  core/templates/layout.user.php
Labels: bug, design, 4. to release, feature: theming, regression

#32212 Make the order of reactions reliable
  lib/private/Comments/Manager.php
Labels: bug, 4. to release, feature: comments

#32218 Revert "Show the child folders in the breadcrumb menu when on a parent entry."
  apps/files/js/breadcrumb.js
  apps/files/tests/js/breadcrumbSpec.js
  core/css/styles.scss
Labels: 4. to release, backport-request, regression

#31703 Emojihelper interface
  apps/user_status/composer/composer/autoload_classmap.php
  apps/user_status/composer/composer/autoload_static.php
  apps/user_status/lib/Capabilities.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/tests/Unit/CapabilitiesTest.php
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Comments/EmojiHelper.php
  lib/private/Comments/Manager.php
  lib/private/EmojiHelper.php
  lib/private/Server.php
  lib/public/IEmojiHelper.php
  tests/lib/Comments/ManagerTest.php
  tests/lib/EmojiHelperTest.php
Labels: 3. to review, feature: comments, technical debt, feature: status

#32217 Allow to override the default theme
  apps/theming/lib/Controller/UserThemeController.php
  apps/theming/lib/Service/ThemesService.php
  apps/theming/lib/Settings/Personal.php
  apps/theming/src/UserThemes.vue
  apps/theming/src/components/ItemPreview.vue
  apps/theming/tests/Service/ThemesServiceTest.php
  apps/theming/tests/Settings/AdminSectionTest.php
  apps/theming/tests/Settings/PersonalTest.php
  config/config.sample.php
  dist/theming-theming-settings.js
  dist/theming-theming-settings.js.map
Labels: enhancement, 4. to release, feature: theming
