Repository nextcloud/server, pull requests merged in 2022-03, with the labels that each got.

#31340 Fix/31237/new button auth token setup dialogue
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
Labels: 3. to review

#31383 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31363 Delay loading user preferences until we need them
  lib/private/User/User.php
Labels: 3. to review, feature: users and groups, technical debt, performance 🚀

#31355 try to fix developer link
  apps/settings/src/views/Apps.vue
  dist/settings-apps-view-418.js
  dist/settings-apps-view-418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, backport-request, feature: apps management

#31380 Ignore errors when searching for bundled preview
  lib/private/Preview/Bundled.php
Labels: 3. to review

#31333 Improve typing in OC\Archive classes
  lib/private/Archive/Archive.php
  lib/private/Archive/TAR.php
  lib/private/Archive/ZIP.php
Labels: 3. to review

#31354 Fix caching of the user avatar
  apps/settings/templates/settings/personal/personal.info.php
  core/Controller/AvatarController.php
Labels: 3. to review, performance 🚀

#30536 Make Sabre File exception messages translatable
  apps/dav/lib/Connector/Sabre/File.php
Labels: bug, 4. to release, backport-request, feature: language l10n and translations

#31347 Fix duplicate primary email message
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 4. to release, backport-request, feature: settings, feature: emails, ux

#31390 Censor more configs
  lib/private/AppConfig.php
  lib/private/SystemConfig.php
Labels: bug, 4. to release, backport-request

#31218 Use the cache also for UserBackend::getPassword
  lib/private/User/Database.php
Labels: bug, 4. to release, feature: users and groups, technical debt, performance 🚀

#31124 Diagnostics event logging to log
  apps/dav/lib/Server.php
  config/config.sample.php
  lib/base.php
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Http/Dispatcher.php
  lib/private/DB/Connection.php
  lib/private/Diagnostics/Event.php
  lib/private/Diagnostics/EventLogger.php
  lib/private/Log.php
  lib/private/RedisFactory.php
  lib/private/Server.php
  lib/private/legacy/OC_App.php
  tests/lib/AppFramework/Bootstrap/CoordinatorTest.php
  tests/lib/AppFramework/Http/DispatcherTest.php
  tests/lib/Diagnostics/EventLoggerTest.php
Labels: enhancement, 3. to review, technical debt, performance 🚀

#31398 Also use hashed/indexed column on delete
  lib/private/BackgroundJob/JobList.php
Labels: bug, 4. to release, backport-request, performance 🚀

#31389 fix fileactions for sharing overview
  apps/files_sharing/js/app.js
  dist/files_sharing-files_sharing.js
  dist/files_sharing-files_sharing.js.map
Labels: bug, 3. to review, backport-request

#31372 prevent default right-click options when hideDownload is enabled
  apps/files_sharing/js/public.js
Labels: enhancement, 3. to review, feature: sharing, backport-request

#31359 Fix apps settings error message timeout
  apps/settings/src/store/apps.js
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, backport-request, feature: settings

#31417 Fix return type of avatar file
  lib/public/IAvatar.php
Labels: bug, 3. to review, backport-request

#31416 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31415 Fix "Nextcloud is not allowed to use the OPcache API" warning
  apps/settings/lib/Controller/CheckSetupController.php
Labels: bug, 3. to review, backport-request

#31267 Add Nextcloud docs link to OPcache recommends
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: enhancement, 3. to review, backport-request, pending documentation

#31412 [stable23] Fix duplicate primary email message
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
Labels: bug, 3. to review, feature: settings, feature: emails, ux

#31423 [stable23] fix developer link
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/src/views/Apps.vue
Labels: bug, 3. to review, backport-request

#31358 Fix settings error message timeout
  apps/settings/src/store/index.js
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, backport-request, feature: settings

#31439 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31424 [stable23] fix fileactions for sharing overview
  apps/files_sharing/js/app.js
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
Labels: bug, 3. to review, backport-request

#31413 [stable22] Fix duplicate primary email message
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
Labels: bug, 3. to review, feature: settings, feature: emails, ux

#31435 Update images in scripts to run local tests in Docker
  build/integration/run-docker.sh
  tests/acceptance/run.sh
Labels: bug, 3. to review

#31436 be conservative when reading from fresh created column
  apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
Labels: bug, 2. developing, feature: ldap

#31387 Make sure common and main core scripts are loaded first
  lib/public/Util.php
  tests/lib/UtilTest.php
Labels: bug, 4. to release, regression, feature: profile

#31266 move root mount setup to mountproviders
  .github/workflows/s3-primary.yml
  apps/dav/lib/Connector/Sabre/File.php
  apps/files_sharing/tests/CacheTest.php
  apps/files_trashbin/tests/StorageTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Avatar/AvatarManager.php
  lib/private/Files/Cache/Storage.php
  lib/private/Files/Mount/RootMountProvider.php
  lib/private/Server.php
  lib/private/legacy/OC_Util.php
  tests/lib/Files/Mount/RootMountProviderTest.php
  tests/lib/User/UserTest.php
Labels: 3. to review

#31449 Censor app config values for all integration apps
  lib/private/AppConfig.php
Labels: bug, 4. to release

#31465 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31447 Clarify that some interface are not meant to be implemented
  lib/public/DB/IPreparedStatement.php
  lib/public/DB/IResult.php
  lib/public/DB/ISchemaWrapper.php
  lib/public/Share/IManager.php
  lib/public/UserStatus/IManager.php
Labels: 4. to release

#31466 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#31426 Connectivity check: test https OR ELSE http
  apps/settings/lib/Controller/CheckSetupController.php
  config/config.sample.php
Labels: enhancement, 3. to review, feature: settings, pending documentation

#31418 Extend simple file with extension getter
  lib/private/Files/SimpleFS/NewSimpleFile.php
  lib/private/Files/SimpleFS/SimpleFile.php
  lib/public/Files/SimpleFS/ISimpleFile.php
  lib/public/Files/SimpleFS/InMemoryFile.php
Labels: enhancement, 4. to release

#30828 fix dialog new file menu
  core/css/styles.scss
  core/src/OC/dialogs.js
  core/src/jquery/css/jquery.ocdialog.scss
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, backport-request

#28227 Fix too many file download notifications when watching a video
  apps/files_sharing/lib/Activity/Providers/Base.php
  apps/files_sharing/lib/Activity/Providers/Downloads.php
  apps/files_sharing/lib/Activity/Providers/Groups.php
  apps/files_sharing/lib/Activity/Providers/PublicLinks.php
  apps/files_sharing/lib/Activity/Providers/RemoteShares.php
  apps/files_sharing/lib/Activity/Providers/Users.php
  apps/files_sharing/lib/Controller/ShareController.php
Labels: bug, 3. to review, backport-request, feature: activity and notification

#31470 improve imagick, bcmath and gmp extension warnings
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: enhancement, 4. to release

#31431 Unify/cleanup filesystem setup
  apps/dav/tests/unit/Connector/Sabre/ObjectTreeTest.php
  apps/files_external/tests/PersonalMountTest.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/lib/Updater.php
  apps/files_sharing/tests/External/ManagerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Cache/CappedMemoryCache.php
  lib/private/Files/Config/CachedMountFileInfo.php
  lib/private/Files/Config/CachedMountInfo.php
  lib/private/Files/Config/LazyStorageMountInfo.php
  lib/private/Files/Config/MountProviderCollection.php
  lib/private/Files/Filesystem.php
  lib/private/Files/Mount/Manager.php
  lib/private/Files/Node/Root.php
  lib/private/Files/SetupManager.php
  lib/private/Files/SetupManagerFactory.php
  lib/private/Files/View.php
  lib/private/Server.php
  lib/private/legacy/OC_Util.php
  lib/public/Files/Config/ICachedMountFileInfo.php
  lib/public/Files/Config/ICachedMountInfo.php
  lib/public/Files/Events/Node/FilesystemTornDownEvent.php
  lib/public/Files/Mount/IMountManager.php
  tests/lib/Cache/FileCacheTest.php
  tests/lib/Files/Cache/UpdaterLegacyTest.php
  tests/lib/Files/Cache/UpdaterTest.php
  tests/lib/Files/Config/UserMountCacheTest.php
  tests/lib/Files/Mount/ManagerTest.php
  tests/lib/Files/Node/FileTest.php
  tests/lib/Files/Node/FolderTest.php
  tests/lib/Files/Node/HookConnectorTest.php
  tests/lib/Files/Node/IntegrationTest.php
  tests/lib/Files/Node/NodeTest.php
  tests/lib/Files/Node/RootTest.php
  tests/lib/Files/PathVerificationTest.php
  tests/lib/Files/ViewTest.php
  tests/lib/HelperStorageTest.php
  tests/lib/SubAdminTest.php
  tests/lib/TestCase.php
  tests/lib/Traits/EncryptionTrait.php
  tests/lib/Traits/UserTrait.php
Labels: 4. to release

#31493 Avoid double-loading dist/core-main.js when apps have scripts named main
  lib/private/Template/JSResourceLocator.php
Labels: bug, 3. to review, regression

#31458 [stable22] Fix settings error message timeout
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users.js
  apps/settings/js/vue-vendors-settings-apps-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps.js
  apps/settings/js/vue-vendors-settings-apps.js.map
  apps/settings/js/vue-vendors-settings-users.js
  apps/settings/js/vue-vendors-settings-users.js.map
  apps/settings/src/store/index.js
Labels: bug, 4. to release

#31500 Fix alternative login buttons
  apps/theming/css/theming.scss
  core/css/guest.css
  core/css/styles.scss
Labels: bug, design, 3. to review, feature: theming, feature: authentication, feature: accessibility

#31503 Allow to set a strict-dynamic CSP through the API
  lib/private/Security/CSP/ContentSecurityPolicy.php
  lib/public/AppFramework/Http/ContentSecurityPolicy.php
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
  tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php
  tests/lib/Security/CSP/ContentSecurityPolicyManagerTest.php
Labels: enhancement, 3. to review

#31430 Validate `overwrite.cli.url` to be a url in setup check
  apps/settings/lib/Controller/CheckSetupController.php
  core/js/setupchecks.js
Labels: bug, enhancement, 3. to review, backport-request

#31494 Fix group metadata typing
  lib/private/Group/MetaData.php
Labels: 3. to review

#31122 [stable22] Background job time windows
  apps/contactsinteraction/lib/BackgroundJob/CleanupJob.php
  apps/dav/lib/BackgroundJob/UploadCleanup.php
  apps/files_external/lib/BackgroundJob/CredentialsCleanup.php
  apps/files_sharing/lib/ExpireSharesJob.php
  apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php
  config/config.sample.php
  core/Migrations/Version24000Date20220131153041.php
  cron.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/BackgroundJob/JobList.php
  lib/private/Security/Bruteforce/CleanupJob.php
  lib/public/BackgroundJob/IJob.php
  lib/public/BackgroundJob/IJobList.php
  lib/public/BackgroundJob/TimedJob.php
  tests/lib/BackgroundJob/DummyJobList.php
Labels: 4. to release, feature: settings

#31410 [stable23] Fix caching of the user avatar
  apps/settings/templates/settings/personal/personal.info.php
  core/Controller/AvatarController.php
Labels: 3. to review, backport-request

#31411 [stable22] Fix caching of the user avatar
  apps/settings/templates/settings/personal/personal.info.php
  core/Controller/AvatarController.php
Labels: 3. to review

#31504 23.0.3 RC1
  version.php
Labels: 3. to review

#31505 22.2.6 RC1
  version.php
Labels: 3. to review

#31491 Fix duplicated UUID detection when there are empty uuids
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/lib/Migration/PopulateNewlyIntroducedDatabaseFields.php
Labels: 3. to review, backport-request

#31526 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31519 Fix occ user:add-app-password
  apps/settings/lib/Activity/Provider.php
  apps/settings/lib/Listener/AppPasswordCreatedActivityListener.php
  core/Command/User/AddAppPassword.php
  core/register_command.php
Labels: bug, 3. to review, feature: occ

#31454 Fix the logger that is imported for critical actions
  apps/admin_audit/composer/composer/autoload_classmap.php
  apps/admin_audit/composer/composer/autoload_static.php
  apps/admin_audit/lib/Actions/Action.php
  apps/admin_audit/lib/AppInfo/Application.php
  apps/admin_audit/lib/AuditLogger.php
  apps/admin_audit/lib/IAuditLogger.php
  apps/admin_audit/tests/Actions/SecurityTest.php
Labels: bug, 4. to release, backport-request

#31539 Fix user status not resetting correctly after a call
  apps/user_status/lib/Service/StatusService.php
Labels: bug, 3. to review, backport-request, regression, feature: status

#31538 Only log events when enabled in debug mode
  lib/private/Diagnostics/EventLogger.php
Labels: bug, 3. to review

#31511 Allow installing unstable app versions based on channel and with `--allow-unstable` just like on updates
  core/Command/App/Install.php
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
Labels: bug, 3. to review, feature: apps management

#31531 Prevent reading key on SFTP stat bool
  apps/files_external/lib/Lib/Storage/SFTP.php
Labels: bug, 4. to release, feature: external storage, backport-request

#31274 Fix more than 1000 entries in queries exception in CardDavBackend
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: bug, 4. to release, backport-request

#31555 fix drone tests on master
  apps/settings/tests/Controller/CheckSetupControllerTest.php
Labels: bug, 3. to review

#31542 Fix psalm issue about userCounts
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  build/psalm-baseline.xml
  lib/private/Support/Subscription/Registry.php
Labels: 3. to review

#31566 Fix unit tests by importing the class
  apps/admin_audit/tests/Actions/SecurityTest.php
Labels: 3. to review

#31378 use new button component
  apps/settings/src/components/UserList.vue
  dist/settings-users-351.js
  dist/settings-users-351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review

#31397 add new button component
  apps/user_status/src/components/SetStatusModal.vue
  dist/user-status-modal-299.js
  dist/user-status-modal-299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 4. to release

#31498 AmazonS3: allow not implemented versioning
  apps/files_external/lib/Lib/Storage/AmazonS3.php
Labels: 3. to review

#31513 Enforce primary keys as they are required to be performant in MySQL c…
  lib/private/DB/MigrationService.php
  tests/lib/DB/MigrationsTest.php
Labels: 4. to release, feature: install and update, technical debt

#31573 don't error if we can't load the ExceptionSerializer for early exceptions
  lib/private/Log.php
Labels: 3. to review

#31578 try to improve s3 primary storage test reliability
  .github/workflows/s3-primary.yml
Labels: 3. to review

#31591 23.0.3 RC2
  version.php
Labels: 3. to review

#31581 Modernize comments app
  apps/comments/lib/Activity/Listener.php
  apps/comments/lib/Activity/Provider.php
  apps/comments/lib/AppInfo/Application.php
  apps/comments/lib/Collaboration/CommentersSorter.php
  apps/comments/lib/Controller/Notifications.php
  apps/comments/lib/Listener/LoadSidebarScripts.php
  apps/comments/lib/Notification/Listener.php
  apps/comments/lib/Notification/Notifier.php
  apps/comments/lib/Search/CommentsSearchProvider.php
  apps/comments/lib/Search/LegacyProvider.php
  apps/comments/tests/Unit/AppInfo/ApplicationTest.php
Labels: 3. to review

#30120 Move calendar objects between calendars
  apps/dav/appinfo/v1/caldav.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/CalendarHome.php
  apps/dav/lib/CalDAV/CalendarManager.php
  apps/dav/lib/CalDAV/CalendarObject.php
  apps/dav/lib/CalDAV/CalendarProvider.php
  apps/dav/lib/CalDAV/CalendarRoot.php
  apps/dav/lib/CalDAV/PublicCalendarRoot.php
  apps/dav/lib/Command/DeleteCalendar.php
  apps/dav/lib/Command/MoveCalendar.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CalDAV/CalendarHomeTest.php
  apps/dav/tests/unit/CalDAV/CalendarManagerTest.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/CalDAV/PublicCalendarRootTest.php
  apps/dav/tests/unit/CalDAV/PublicCalendarTest.php
  apps/dav/tests/unit/Command/DeleteCalendarTest.php
  apps/dav/tests/unit/Command/MoveCalendarTest.php
Labels: enhancement, 3. to review

#31421 user_ldap fix ldap connection resets
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/ILDAPWrapper.php
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/Group_LDAPTest.php
  apps/user_ldap/tests/User/UserTest.php
  apps/user_ldap/tests/User_LDAPTest.php
  apps/user_ldap/tests/WizardTest.php
Labels: 3. to review

#31596 Fix federated cloud share icons overlap in button
  apps/federatedfilesharing/css/settings-personal.scss
Labels: 3. to review

#31574 use the nextcloud certificate bundle for s3
  lib/private/Files/ObjectStore/S3.php
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
  lib/private/Security/CertificateManager.php
Labels: 3. to review, backport-request

#31215 handle invalid type when listing directory in smb
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 4. to release

#31487 Discard duplicate collection name from account serialization
  lib/private/Accounts/Account.php
  tests/lib/Accounts/AccountTest.php
Labels: enhancement, 4. to release

#31381 Improve performance of external storage config UI
  apps/files_external/js/settings.js
  apps/files_external/tests/js/settingsSpec.js
Labels: 4. to release

#31608 some file scanner performance improvements
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Filesystem.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Local.php
Labels: 3. to review

#31488 Add method to set all account properties from json
  lib/private/Accounts/Account.php
  lib/public/Accounts/IAccount.php
  tests/lib/Accounts/AccountTest.php
Labels: enhancement, 4. to release

#31614 Simplify comment search in special cases
  lib/private/Comments/Manager.php
Labels: bug, 3. to review, performance 🚀

#30768 Do chuncked job deletion
  lib/private/BackgroundJob/JobList.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
Labels: 3. to review

#24166 Send images to Imaginary docker to generate previews
  config/config.sample.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Http/Client/Client.php
  lib/private/Preview/Generator.php
  lib/private/Preview/GeneratorHelper.php
  lib/private/Preview/Imaginary.php
  lib/private/PreviewManager.php
  lib/private/StreamImage.php
  lib/public/IStreamImage.php
Labels: enhancement, 2. developing

#31613 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31425 Update CRL after revoke deckimportfromtrello.csr
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#31633 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#31193 Add optional WebDav propfind properties to count sub elements
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
Labels: enhancement, 3. to review, feature: dav, pending documentation

#31529 [stable23] Fix listeners declaration in case of occ usage
  lib/base.php
Labels: bug, 4. to release

#31616 l10n: Spelling unification in Transifex.
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: 2. developing, feature: language l10n and translations

#31642 Revert "[stable23] Fix listeners declaration in case of occ usage"
  lib/base.php
Labels: 3. to review

#31645 23.0.3
  version.php
Labels: 3. to review

#31585 [stable21] Fix settings error message timeout
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users.js
  apps/settings/js/vue-vendors-settings-apps-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps.js
  apps/settings/js/vue-vendors-settings-apps.js.map
  apps/settings/js/vue-vendors-settings-users.js
  apps/settings/js/vue-vendors-settings-users.js.map
  apps/settings/src/store/index.js
Labels: bug, 3. to review, feature: settings

#31650 [stable21] Update CRL after revoking some app certs
  resources/codesigning/root.crl
Labels: 3. to review

#31337 Fix #31303: Make reminder notification behaviour selectable..
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
  apps/dav/lib/Settings/CalDAVSettings.php
  apps/dav/src/settings.js
  apps/dav/src/views/CalDavSettings.spec.js
  apps/dav/src/views/CalDavSettings.vue
  apps/dav/src/views/__snapshots__/CalDavSettings.spec.js.snap
  apps/dav/tests/unit/CalDAV/Reminder/ReminderServiceTest.php
  apps/dav/tests/unit/Settings/CalDAVSettingsTest.php
  dist/dav-settings-admin-caldav.js
  dist/dav-settings-admin-caldav.js.map
Labels: enhancement, 3. to review, feature: caldav

#30336 Refine dashboard edit widget design
  apps/dashboard/src/App.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: enhancement, design, 4. to release, feature: dashboard

#31382 User account migration
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/UserMigration/AccountMigrator.php
  apps/settings/lib/UserMigration/AccountMigratorException.php
Labels: enhancement, 3. to review, feature: user migration

#31653 Run tests with MySQL/MariaDB ONLY_FULL_GROUP_BY
  .drone.yml
Labels: 3. to review, technical debt

#31639 Fix moving error for calendar object error because of missing princip…
  apps/dav/lib/CalDAV/CalendarObject.php
Labels: bug, 3. to review, feature: caldav

#31620 do not forget DB table prefix with truncate query
  apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
Labels: bug, 3. to review, feature: ldap

#31605 cache the path of the certificate bundle
  lib/private/Security/CertificateManager.php
Labels: 3. to review

#31582 Modernize accessibility app
  apps/accessibility/lib/AccessibilityProvider.php
  apps/accessibility/lib/Controller/AccessibilityController.php
  apps/accessibility/lib/Controller/ConfigController.php
  apps/accessibility/lib/Migration/RepairUserConfig.php
  apps/accessibility/lib/Service/JSDataService.php
Labels: 3. to review

#31580 Limit missing primary key fail to new tables and comment out for now
  lib/private/DB/MigrationService.php
Labels: bug, 3. to review, feature: install and update, regression

#31644 fix: button type to tertiary
  apps/user_status/src/components/SetStatusModal.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 4. to release

#31235 Extract request id handling to dedicated class so it can be injected without DB dependency
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Http/Request.php
  lib/private/AppFramework/Http/RequestId.php
  lib/private/DB/Connection.php
  lib/private/Server.php
  lib/public/IRequestId.php
  tests/Core/Middleware/TwoFactorMiddlewareTest.php
  tests/lib/AppFramework/Controller/ApiControllerTest.php
  tests/lib/AppFramework/Controller/ControllerTest.php
  tests/lib/AppFramework/Controller/OCSControllerTest.php
  tests/lib/AppFramework/DependencyInjection/DIContainerTest.php
  tests/lib/AppFramework/Http/DispatcherTest.php
  tests/lib/AppFramework/Http/RequestIdTest.php
  tests/lib/AppFramework/Http/RequestTest.php
  tests/lib/AppFramework/Middleware/MiddlewareDispatcherTest.php
  tests/lib/AppFramework/Middleware/MiddlewareTest.php
  tests/lib/AppFramework/Middleware/Security/CORSMiddlewareTest.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
  tests/lib/User/SessionTest.php
Labels: 4. to release, technical debt

#31569 Allow creating app passwords without validating the user's password a…
  core/Command/User/AddAppPassword.php
Labels: bug, 3. to review, feature: users and groups, regression, feature: occ

#31601 Add proper description for the dashboard app
  apps/dashboard/appinfo/info.xml
Labels: enhancement, 4. to release

#31668 Test disabled for now due to multiple reasons
  tests/lib/DB/MigrationsTest.php
Labels: 3. to review

#31658 Limit the length of app password names
  apps/settings/lib/Controller/AuthSettingsController.php
  core/Controller/AppPasswordController.php
  core/Controller/ClientFlowLoginController.php
  lib/private/Authentication/Token/Manager.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
  tests/lib/Authentication/TwoFactorAuth/ManagerTest.php
Labels: bug, 3. to review, feature: authentication

#31688 Automatically cut the token name on the first level
  core/Controller/AppPasswordController.php
  core/Controller/ClientFlowLoginController.php
  lib/private/Authentication/Token/IProvider.php
  lib/private/Authentication/Token/Manager.php
  tests/lib/Authentication/Token/ManagerTest.php
Labels: bug, 3. to review, feature: authentication, regression

#31655 Fix passing null to strlen
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/Contacts/ContactsMenu/Manager.php
Labels: bug, 3. to review

#31221 Don't create cards_abiduri it if already exists
  core/Command/Db/AddMissingIndices.php
Labels: bug, 3. to review, feature: owncloud migration

#31700 Allow reactions also with other combined emojis 🧑🏾‍💻
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Comments/EmojiHelper.php
  lib/private/Comments/Manager.php
  tests/lib/Comments/ManagerTest.php
Labels: bug, 4. to release, feature: comments

#30950 Add OPcache recommendations to Transifex
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 3. to review, backport-request, feature: language l10n and translations, php

#31520 focus to buttons on dashboard view
  apps/dashboard/src/App.vue
  apps/user_status/src/UserStatus.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 2. developing

#31265 Fine grained filesystem setup
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/files_external/lib/Service/StoragesService.php
  apps/files_external/lib/Service/UserGlobalStoragesService.php
  apps/files_external/lib/Service/UserStoragesService.php
  apps/files_external/tests/Service/GlobalStoragesServiceTest.php
  apps/files_external/tests/Service/StoragesServiceTest.php
  apps/files_external/tests/Service/UserGlobalStoragesServiceTest.php
  apps/files_external/tests/Service/UserStoragesServiceTest.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/SharedMount.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Config/MountProviderCollection.php
  lib/private/Files/Config/UserMountCache.php
  lib/private/Files/Filesystem.php
  lib/private/Files/Mount/Manager.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/LazyUserFolder.php
  lib/private/Files/Node/Root.php
  lib/private/Files/SetupManager.php
  lib/private/Files/SetupManagerFactory.php
  lib/public/Files/Config/IMountProviderCollection.php
  lib/public/Files/Config/IUserMountCache.php
  lib/public/Files/Events/InvalidateMountCacheEvent.php
Labels: enhancement, 4. to release, performance 🚀

#31693 24.0.0 beta 1
  version.php
Labels: 3. to review

#31708 Set max length to app token field to match backend
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
Labels: bug, 4. to release, backport-request, feature: settings

#30276 Add oauth2_clients migration for Owncloud
  apps/oauth2/lib/Migration/Version010402Date20190107124745.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/Owncloud/MigrateOauthTables.php
Labels: 3. to review, backport-request, feature: owncloud migration

#31537 show that the web updater is not recommended on big instances
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/src/components/UpdateNotification.vue
  apps/updatenotification/tests/Settings/AdminTest.php
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
Labels: bug, enhancement, 4. to release

#31736 Disable bulk upload by not advertising it
  apps/dav/lib/Capabilities.php
  apps/dav/tests/unit/CapabilitiesTest.php
Labels: 3. to review

#31696 Use getLengthExpression to measure field length instead of like
  apps/user_ldap/lib/Migration/Version1120Date20210917155206.php
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
Labels: 3. to review

#31697 fix User Counts updates on user add/remove
  apps/settings/src/store/users.js
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: users and groups

#31575 Add trashbin migrator to export and import trashbin data
  apps/files_trashbin/composer/composer/autoload_classmap.php
  apps/files_trashbin/composer/composer/autoload_static.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_trashbin/lib/UserMigration/TrashbinMigrator.php
Labels: 3. to review

#31735 migration generator also includes copyright section
  core/Command/Db/Migrations/GenerateCommand.php
Labels: 3. to review

#31592 Add direct arg to login flow
  core/Controller/ClientFlowLoginController.php
  core/templates/loginflow/authpicker.php
  core/templates/loginflow/grant.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
Labels: 2. developing, 4. to release

#31690 Skip import of current calendar on error
  apps/dav/lib/UserMigration/CalendarMigrator.php
Labels: bug, 4. to release, feature: dav, feature: caldav, feature: user migration

#31756 Fix vendor loading in user_ldap wizard
  apps/user_ldap/css/vendor/ui-multiselect/jquery.multiselect.css
  apps/user_ldap/templates/settings.php
Labels: bug, 4. to release, regression

#31739 add beta channel advice to the updatenotification section
  apps/updatenotification/src/components/UpdateNotification.vue
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
Labels: bug, enhancement, 4. to release, feature: apps management

#31683 limit ldap_dn columns to 4000
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/lib/Migration/Version1010Date20200630192842.php
  apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
  apps/user_ldap/lib/Migration/Version1130Date20220110154718.php
  apps/user_ldap/lib/Migration/Version1141Date20220323143801.php
Labels: bug, feature: ldap

#31740 [stable23] show that the web updater is not recommended on big instances
  apps/updatenotification/js/updatenotification.js
  apps/updatenotification/js/updatenotification.js.map
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/src/components/UpdateNotification.vue
  apps/updatenotification/tests/Settings/AdminTest.php
Labels: bug, enhancement, 3. to review

#31679 Ensure string column limit of 4.000 characters
  apps/files_external/appinfo/info.xml
  apps/files_external/lib/Migration/Version1011Date20200630192246.php
  apps/files_external/lib/Migration/Version1016Date20220324154536.php
  lib/private/DB/MigrationService.php
  tests/lib/DB/MigrationsTest.php
Labels: 3. to review

#31770 Change script loading order in worflowengine
  apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php
Labels: 3. to review

#31737 Wrap oauth2 migrations inside conditions
  lib/private/Repair/Owncloud/MigrateOauthTables.php
Labels: 4. to release, backport-request

#31602 Do not update _lastChanged on auto-detected attributes
  apps/user_ldap/lib/Command/CreateEmptyConfig.php
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Controller/ConfigAPIController.php
Labels: 3. to review

#31514 [stable23] user_ldap fix ldap connection resets #31421
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/ILDAPWrapper.php
  apps/user_ldap/lib/LDAP.php
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/Group_LDAPTest.php
  apps/user_ldap/tests/User/UserTest.php
  apps/user_ldap/tests/User_LDAPTest.php
  apps/user_ldap/tests/WizardTest.php
Labels: 3. to review, backport-request

#31240 l10n: Add a dot
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: feature: language l10n and translations

#31769 24.0.0 beta 2
  version.php
Labels: 3. to review
