Repository nextcloud/server, pull requests merged in 2022-12, with the labels that each got.

#35525 Faster theming tests, better colours comparison and properly follow admin theming changes
  .github/workflows/cypress.yml
  apps/theming/appinfo/routes.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/Controller/UserThemeController.php
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/src/AdminTheming.vue
  apps/theming/src/components/admin/FileInputField.vue
  cypress/e2e/theming/admin-settings.cy.ts
  cypress/e2e/theming/themingUtils.ts
  cypress/e2e/theming/user-background.cy.ts
  cypress/support/commands.ts
  dist/theming-admin-theming.js
  dist/theming-admin-theming.js.map
  package-lock.json
  package.json
Labels: bug, 4. to release, feature: theming

#35488 24.0.8 RC2
  version.php
Labels: 3. to review

#35489 23.0.12 RC2
  version.php
Labels: 3. to review

#35463 [stable22] Cap node version to 12
  package.json
Labels: 3. to review, dependencies

#35556 Revert unrelated change from #34940
  core/Controller/ClientFlowLoginV2Controller.php
Labels: 3. to review

#35566 preview: respect quality in Imaginary
  lib/private/Preview/Imaginary.php
Labels: bug, 3. to review, feature: previews and thumbnails

#34920 Added parameter to disallow calendar subscription via link
  apps/dav/lib/Server.php
Labels: 4. to release, feature: dav, feature: caldav

#35385 Fix type of PreviewController::$userId
  core/Controller/PreviewController.php
Labels: bug, 4. to release, backport-request, php

#35442 fix multiline-format-error in file-conflict modal
  apps/files/css/merged.css
  apps/files/css/upload.css
  apps/files/css/upload.scss
Labels: bug, 4. to release

#35563 Revert "Fix border color contrast"
  apps/theming/css/default.css
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
Labels: 4. to release, regression

#34232 compare cached filesize on download
  apps/dav/lib/Connector/Sabre/File.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
  lib/private/Files/Stream/SeekableHttpStream.php
Labels: 3. to review

#35271 Show success on share actions
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request, accessibility

#35560 Remove obsolete GD function overwrites
  build/psalm-baseline.xml
  lib/private/StreamImage.php
  lib/private/legacy/OC_Image.php
  lib/public/IImage.php
  tests/lib/ImageTest.php
Labels: 4. to release

#35580 downgrade ubuntu in order to fix CI
  .github/workflows/oci.yml
  .github/workflows/s3-primary.yml
Labels: 3. to review, backport-request

#35249 Set page title for each sidebar section through App management pages
  apps/settings/src/router.js
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, backport-request, accessibility

#35604 Fix default redirect on successful WebAuthn login
  core/Controller/WebAuthnController.php
  core/src/components/login/PasswordLessLoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, 3. to review, backport-request, feature: authentication

#35400 Fix name of dymanic var $mountOptions to fix PHP 8.2 compatibility
  apps/files_sharing/lib/SharedStorage.php
Labels: 3. to review

#35437 Add success popup message for copying share links
  apps/files_sharing/src/components/SharingEntryInternal.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, feature: sharing, backport-request, accessibility

#35549 Add new border color variable and adjust primary color for increased contrast
  apps/theming/css/default.css
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
Labels: 4. to release, backport-request, regression, accessibility

#35521 [BUGFIX] Prevents the selection of encrypted files at the bottom of the list(before scrolling)
  apps/files/js/filelist.js
Labels: 3. to review

#34819 Fix some phpunit test warnings
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php
  apps/dav/tests/unit/CalDAV/CalendarImplTest.php
  apps/dav/tests/unit/Controller/InvitationResponseControllerTest.php
  tests/lib/Encryption/UtilTest.php
Labels: 3. to review, tests

#35612 Adjust branding of errorlog log messages
  lib/private/Log/Errorlog.php
Labels: 3. to review

#35596 Use TimedJob from OCP instead of OC
  apps/admin_audit/lib/BackgroundJobs/Rotate.php
  apps/files/lib/BackgroundJob/CleanupDirectEditingTokens.php
  apps/files/lib/BackgroundJob/CleanupFileLocks.php
  apps/files/lib/BackgroundJob/DeleteOrphanedItems.php
  apps/files/tests/BackgroundJob/DeleteOrphanedItemsJobTest.php
  apps/files_sharing/lib/BackgroundJob/FederatedSharesDiscoverJob.php
  apps/files_sharing/lib/DeleteOrphanedSharesJob.php
  apps/files_sharing/tests/DeleteOrphanedSharesJobTest.php
  apps/updatenotification/lib/Notification/BackgroundJob.php
  apps/updatenotification/tests/Notification/BackgroundJobTest.php
  apps/user_ldap/lib/Jobs/CleanUp.php
  apps/user_ldap/tests/Jobs/CleanUpTest.php
  apps/workflowengine/lib/BackgroundJobs/Rotate.php
  lib/private/Preview/BackgroundCleanupJob.php
  tests/lib/Preview/BackgroundCleanupJobTest.php
Labels: 3. to review

#35618 Explicitly inherit stricly typed database schema closure of migrations
  lib/public/Migration/IMigrationStep.php
  lib/public/Migration/SimpleMigrationStep.php
Labels: bug, 3. to review

#35547 delete the --image-background-size variable
  apps/theming/lib/Themes/CommonThemeTrait.php
Labels: 3. to review

#35616 [stable25] Fix migration to non-empty secret
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSAPrivateKey.php
Labels: 4. to release

#35623 25.0.2 RC3
  version.php
Labels: 3. to review

#35615 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35576 Handle possible null value for file in OC\Files\SimpleFS\NewSimpleFile
  lib/private/Files/SimpleFS/NewSimpleFile.php
Labels: bug, 3. to review, feature: files

#35571 [master] Update ca-cert bundle
  build/ca-bundle-etag.txt
Labels: 3. to review, dependencies

#35222 Fix contrast of global search headings
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 4. to release, backport-request, feature: search, accessibility

#35622 Automatically build sass and sass:icons after build
  .github/workflows/command-compile.yml
  .github/workflows/node.yml
  package.json
Labels: 3. to review

#35635 Update update-psalm-baseline workflow for NC25
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#35057 Add brute force protection on all methods wrapped by PublicShareMiddleware
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/PublicShare/PublicShareMiddleware.php
  tests/lib/AppFramework/Middleware/PublicShare/PublicShareMiddlewareTest.php
Labels: 3. to review, feature: sharing, security

#35603 Document frontend sass compilation
  README.md
Labels: 3. to review

#35176 Add text/asciidoc mimetype
  lib/private/Repair/RepairMimeTypes.php
  resources/config/mimetypemapping.dist.json
Labels: 3. to review

#35653 ci: update minio image for s3 primary storage tests
  .github/workflows/s3-primary.yml
Labels: 3. to review, technical debt

#35590 Replace getSystemValue in encryption app
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/lib/Crypto/Crypt.php
  apps/encryption/tests/Crypto/CryptTest.php
Labels: 3. to review

#35649 Update the unencrypted file size when closing streams
  lib/private/Files/Stream/Encryption.php
  tests/lib/Files/Stream/EncryptionTest.php
Labels: bug, 3. to review, backport-request

#35586 Replace getSystemValue with getSystemValueString in Util.php
  lib/public/Util.php
Labels: 4. to release, technical debt

#35534 Language fixes in example config
  config/config.sample.php
Labels: bug, 4. to release

#35223 Smaller performance optimizations
  lib/base.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/L10N/Factory.php
  lib/private/Server.php
  lib/private/ServerContainer.php
  lib/private/Template/CSSResourceLocator.php
  lib/private/Template/JSResourceLocator.php
  lib/private/Template/ResourceLocator.php
  lib/private/TemplateLayout.php
  tests/lib/L10N/FactoryTest.php
  tests/lib/L10N/L10nTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/ResourceLocatorTest.php
Labels: 3. to review, performance 🚀

#35071 Add alt to the logo, adapt css for logo
  core/css/guest.css
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
  lib/private/TemplateLayout.php
Labels: bug, 4. to release, backport-request, accessibility

#35662 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
Labels: 3. to review, automated pr

#35570 [stable22] Update ca-cert bundle
  build/ca-bundle-etag.txt
Labels: 3. to review, dependencies

#35391 [stable22] Make sure that path is normalized and then checked and not the other way around
  lib/private/Files/Node/Folder.php
Labels: bug, 4. to release, backport-request

#35670 24.0.8
  version.php
Labels: 3. to review

#24574 Ldapi unix socket support
  apps/user_ldap/js/wizard/view.js
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/LDAP.php
  apps/user_ldap/lib/Wizard.php
Labels: enhancement, 3. to review, feature: ldap

#35660 Increase default global input field border contrast
  core/css/inputs.css
  core/css/inputs.scss
  core/css/server.css
Labels: 3. to review, backport-request, accessibility

#35665 Revert "Disable style override on vue-select elements"
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 4. to release, regression

#35666 Invert header if primary is bright and background disabled
  apps/theming/lib/Controller/UserThemeController.php
  apps/theming/lib/Themes/CommonThemeTrait.php
  cypress/e2e/theming/admin-settings.cy.ts
  cypress/e2e/theming/user-background.cy.ts
  cypress/support/commands.ts
Labels: bug, 4. to release, feature: theming

#35529 Improve verbosity of search description
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 4. to release, backport-request, feature: search, accessibility

#35639 [stable25] Fix contrast of global search headings
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 4. to release, feature: search, accessibility

#35686 take out stable23 from dependabot config
  .github/dependabot.yml
Labels: 3. to review

#35417 [stable24] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35705 Update sensitive config list of Talk
  lib/private/AppConfig.php
Labels: bug, 3. to review

#34477 Show group name instead of group id as recommendation
  lib/private/Share20/DefaultShareProvider.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: bug, 3. to review, feature: sharing, backport-request

#35389 Use correct filter for app icons in the right sidebar of app management
  apps/settings/src/views/Apps.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, backport-request

#35097 Improve email results for sharing
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Federation/CloudIdManager.php
  lib/private/User/Manager.php
  lib/public/IUserManager.php
Labels: bug, 4. to release, feature: sharing, backport-request

#35386 [stable23] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35689 preview: fix HEIC orientation
  lib/private/Preview/HEIC.php
Labels: bug, 3. to review, backport-request, feature: previews and thumbnails

#35724 [stable25] ci: update minio image for s3 primary storage tests
  .github/workflows/s3-primary.yml
Labels: 3. to review, backport-request, technical debt

#35714 Fix vue-select styles
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 4. to release, backport-request

#35562 Read loginName from token
  core/Controller/ClientFlowLoginV2Controller.php
Labels: bug, 3. to review

#35621 Allow additional Sabre plugins in publicwebdav.php
  apps/dav/appinfo/v1/publicwebdav.php
  lib/public/SabrePublicPluginEvent.php
Labels: enhancement, 3. to review, feature: dav, backport-request

#35745 Update README main screenshot
  README.md
Labels: 4. to release

#35641 [stable25] Add success popup message for copying share links
  apps/files_sharing/src/components/SharingEntryInternal.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, feature: sharing, accessibility

#35640 [stable25] Add new border color variable and adjust primary color for increased contrast
  apps/theming/css/default.css
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  tests/acceptance/features/app-theming.feature
Labels: 4. to release, accessibility

#35789 Rename SabrePublicPluginEvent to BeforeSabrePubliclyLoadedEvent
  apps/admin_audit/composer/composer/installed.php
  apps/cloud_federation_api/composer/composer/installed.php
  apps/comments/composer/composer/installed.php
  apps/contactsinteraction/composer/composer/installed.php
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/composer/composer/installed.php
  apps/encryption/composer/composer/installed.php
  apps/federatedfilesharing/composer/composer/installed.php
  apps/federation/composer/composer/installed.php
  apps/files/composer/composer/installed.php
  apps/files_sharing/composer/composer/installed.php
  apps/files_trashbin/composer/composer/installed.php
  apps/files_versions/composer/composer/installed.php
  apps/lookup_server_connector/composer/composer/installed.php
  apps/oauth2/composer/composer/installed.php
  apps/provisioning_api/composer/composer/installed.php
  apps/settings/composer/composer/installed.php
  apps/sharebymail/composer/composer/installed.php
  apps/systemtags/composer/composer/installed.php
  apps/testing/composer/composer/installed.php
  apps/twofactor_backupcodes/composer/composer/installed.php
  apps/updatenotification/composer/composer/installed.php
  apps/user_ldap/composer/composer/installed.php
  apps/user_status/composer/composer/installed.php
  apps/workflowengine/composer/composer/installed.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/BeforeSabrePubliclyLoadedEvent.php
Labels: bug, 3. to review, feature: dav, backport-request, pending documentation

#35779 [PHP8] check if params given to API are really an array
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: bug, 3. to review, backport-request

#35784 Make the LoginController strict
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: 4. to release, technical debt

#35780 Fix missing cast of double controller parameters
  lib/private/AppFramework/Http/Dispatcher.php
  tests/lib/AppFramework/Http/DispatcherTest.php
Labels: 3. to review, backport-request, technical debt

#35679 Catch NotFoundException as well in JSCombiner
  lib/private/Template/JSCombiner.php
Labels: bug, 3. to review, feature: caching

#35602 [stable25] Allow to set a custom timeout for ldap connections
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Connection.php
Labels: 3. to review, feature: ldap, backport-request

#35573 [stable25] Update ca-cert bundle
  build/ca-bundle-etag.txt
Labels: 3. to review, dependencies

#35492 [stable25] Rename personal Groupware settings section to "Availability"
  apps/dav/img/LICENSES.md
  apps/dav/img/schedule.svg
  apps/settings/lib/Sections/Personal/Groupware.php
Labels: 3. to review, backport-request

#35108 allow running encryption:fix-encrypted-version for all users
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
Labels: 3. to review

#34924 escape path prefix when doing cache jail search
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Search/QueryOptimizer/PathPrefixOptimizer.php
  lib/private/Files/Search/SearchComparison.php
Labels: 3. to review

#35574 [stable24] Update ca-cert bundle
  build/ca-bundle-etag.txt
Labels: 3. to review, dependencies

#34629 Fix case sensitivity of email when saving settings
  apps/settings/lib/Controller/UsersController.php
  apps/settings/tests/Controller/UsersControllerTest.php
Labels: 4. to release, backport-request

#35177 restoring clearCachedConfig()
  lib/private/AppConfig.php
Labels: 3. to review, backport-request

#34807 Compute notification parsed subject from rich subject when possible
  apps/comments/lib/Activity/Provider.php
  apps/comments/lib/Notification/Notifier.php
  apps/comments/tests/Unit/Notification/NotifierTest.php
  apps/dav/lib/CalDAV/Activity/Provider/Base.php
  apps/dav/lib/CardDAV/Activity/Provider/Base.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/BaseTest.php
  apps/federatedfilesharing/lib/Notifier.php
  apps/files/lib/Activity/FavoriteProvider.php
  apps/files/lib/Activity/Provider.php
  apps/files/lib/Notification/Notifier.php
  apps/files_sharing/lib/Activity/Providers/Base.php
  apps/files_sharing/lib/Notification/Notifier.php
  apps/settings/lib/Activity/GroupProvider.php
  apps/settings/lib/Activity/Provider.php
  apps/sharebymail/lib/Activity.php
  apps/systemtags/lib/Activity/Provider.php
  apps/updatenotification/lib/Notification/Notifier.php
  lib/private/Activity/Event.php
  lib/private/Notification/Notification.php
  lib/public/Activity/IEvent.php
  lib/public/Notification/INotification.php
Labels: 3. to review

#35496 Strict typing lib/base.php
  build/psalm-baseline.xml
  lib/base.php
  lib/private/AppFramework/Http/Request.php
  lib/public/Log/functions.php
Labels: 3. to review

#35675 [stable23] Update handlebars-loader to 1.7.3 + others
  core/js/dist/login.js
  core/js/dist/login.js.map
  package-lock.json
Labels: 3. to review

#33709 Use display name cache on getStorageInfo
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
  lib/private/legacy/OC_Helper.php
Labels: 4. to release, performance 🚀

#35231 Cache the fetched list of groups
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/AccessTest.php
Labels: 3. to review

#35614 Fix array to string conversion in errorlog writer
  lib/private/Log/Errorlog.php
  lib/private/Log/LogFactory.php
  lib/private/Log/Syslog.php
  lib/private/Log/Systemdlog.php
  lib/public/Log/IWriter.php
Labels: bug, 3. to review, backport-request

#35828 Fix PHP error on PHP >= 8.2 about dynamic property use in tests
  apps/oauth2/tests/Controller/OauthApiControllerTest.php
Labels: 4. to release

#34172 Add support for application/scim+json
  lib/private/AppFramework/Http/Request.php
  lib/public/IRequest.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3. to review, pending documentation

#35545 Add styles for #33741. Remove boards and add underlines.
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
Labels: 4. to release, backport-request

#35229 Use a dedicated LDAP host and port for background jobs if configured
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/tests/ConnectionTest.php
Labels: 3. to review

#35769 l10n: Align notification messages for server version and apps
  apps/updatenotification/lib/Notification/Notifier.php
Labels: 3. to review

#25768 Use mimetype from cache for workflow checks
  apps/workflowengine/lib/Check/FileMimeType.php
  apps/workflowengine/tests/Check/FileMimeTypeTest.php
Labels: 2. developing, backport-request, technical debt

#34772 Make sure to use AccessFactory to create Access instances and use DI
  apps/user_ldap/ajax/wizard.php
  apps/user_ldap/lib/AccessFactory.php
  apps/user_ldap/lib/Command/TestConfig.php
  apps/user_ldap/lib/Group_Proxy.php
  apps/user_ldap/lib/ILDAPUserPlugin.php
  apps/user_ldap/lib/Proxy.php
  apps/user_ldap/lib/UserPluginManager.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/tests/User_ProxyTest.php
  lib/private/User/Database.php
  lib/public/User/Backend/ICountUsersBackend.php
Labels: 3. to review

#35827 [stable25] allow running encryption:fix-encrypted-version for all users
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
Labels: 4. to release, backport-request

#34724 fix reading newly written encrypted files before their cache entry is written
  apps/encryption/lib/Command/FixEncryptedVersion.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 4. to release

#35839 Apply a longer TTL of 15min to falling back on backup server
  apps/user_ldap/lib/Connection.php
Labels: 3. to review

#35663 [stable25] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, 4. to release, automated pr

#35836 fix: remove other shares from ui when deleted
  apps/files_sharing/src/views/SharingInherited.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request, ux

#35656 docs: add design contribution guidelines
  DESIGN.md
  README.md
Labels: enhancement, design, 3. to review

#35702 [stable25] Fix default primary for user theming
  apps/theming/lib/ThemingDefaults.php
  tests/acceptance/features/app-theming.feature
Labels: bug, 4. to release, regression

#34623 Update behat and friends
  tests/acceptance/composer.json
  tests/acceptance/composer.lock
Labels: 3. to review, technical debt

#28311 Do not setup a session when not required on API requests
  apps/files/lib/Controller/ViewController.php
  lib/base.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
Labels: enhancement, 3. to review, performance 🚀

#35855 Add DESIGN.md to expected files
  build/files-checker.php
Labels: 3. to review, technical debt

#35761 Remove comment and guests option from Invitations UI
  apps/dav/lib/Controller/InvitationResponseController.php
  apps/dav/templates/schedule-response-options.php
  apps/dav/tests/unit/Controller/InvitationResponseControllerTest.php
Labels: bug, 4. to release, backport-request, pending documentation, feature: caldav

#35856 increase preview_max_memory and make it easier to debug
  config/config.sample.php
  lib/private/legacy/OC_Image.php
  tests/lib/ImageTest.php
Labels: enhancement, 4. to release, feature: previews and thumbnails

#33708 Move guest.css to scss
  core/css/animations.css
  core/css/animations.css.map
  core/css/animations.scss
  core/css/guest.css
  core/css/guest.css.map
  core/css/guest.scss
Labels: 3. to review, technical debt

#35866 fix(session): Always setup the session if a session cookie is passed
  lib/base.php
Labels: bug, 4. to release

#35785 Replace custom tooltips with native one for files sharing
  apps/files_sharing/js/files_drop.js
  apps/files_sharing/js/public.js
  apps/files_sharing/js/sharedfilelist.js
  apps/files_sharing/js/templates.js
  apps/files_sharing/js/templates/files_drop.handlebars
  apps/files_sharing/src/share.js
  dist/files_sharing-additionalScripts.js
  dist/files_sharing-additionalScripts.js.map
  dist/files_sharing-files_sharing.js
  dist/files_sharing-files_sharing.js.map
Labels: 4. to release

#35865 [stable24] allow running encryption:fix-encrypted-version for all users
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
Labels: 3. to review

#35889 Checkout current branch in cypress tests in CI
  .github/workflows/cypress.yml
  cypress/dockerNode.ts
Labels: 3. to review, tests

#35891 avatar generation - disable setimageformat
  lib/private/Avatar/Avatar.php
Labels: bug, 3. to review, backport-request

#35870 Refine file comments design
  apps/comments/src/components/Comment.vue
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
Labels: 3. to review

#35897 fix video fullscreen on public page
  apps/files_sharing/css/public.css
  apps/files_sharing/css/public.css.map
  apps/files_sharing/css/public.scss
  apps/files_sharing/css/publicView.css
  apps/files_sharing/css/publicView.css.map
Labels: bug, 3. to review, backport-request

#35881 improve sample.config.php parameter descriptions
  config/config.sample.php
Labels: 3. to review

#35913 Revert "avatar generation - disable setimageformat"
  lib/private/Avatar/Avatar.php
Labels: 3. to review, regression

#35914 Revert "[stable25] avatar generation - disable setimageformat"
  lib/private/Avatar/Avatar.php
Labels: 3. to review, regression

#35911 chore(actions): update php min supported to 8.0
  .github/workflows/command-compile.yml
  .github/workflows/ftp.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint.yml
  .github/workflows/node-tests.yml
  .github/workflows/oci.yml
  .github/workflows/psalm-github.yml
  .github/workflows/psalm-security.yml
  .github/workflows/s3-external.yml
  .github/workflows/s3-primary.yml
  .github/workflows/smb-kerberos.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/encryption/lib/Crypto/Crypt.php
  apps/files_external/lib/Lib/Storage/SFTPReadStream.php
  build/psalm-baseline.xml
  core/Command/Log/Manage.php
Labels: 3. to review

#35572 [stable23] Update ca-cert bundle
  build/ca-bundle-etag.txt
Labels: 3. to review, dependencies

#35879 [stable24] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35826 [stable22] add migration for encryption keys in wrong location
  apps/encryption/appinfo/info.xml
  apps/encryption/composer/composer/autoload_classmap.php
  apps/encryption/composer/composer/autoload_static.php
  apps/encryption/lib/Command/FixKeyLocation.php
Labels: 3. to review
