Repository nextcloud/server, pull requests merged in 2022-06, with the labels that each got.

#32371 More meaningfull message when a public authenticated share's password is wrong or has expired.
  core/templates/publicshareauth.php
  tests/acceptance/features/bootstrap/PublicShareContext.php
Labels: enhancement, 3. to review, ux

#32686 Make X-HAS-{MD5/SHA256} opt-in
  apps/dav/lib/Connector/Sabre/File.php
Labels: 3. to review, performance 🚀

#32471 Make sure activities are not created when a deleted calendar object expires
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/Listener/ActivityUpdaterListenerTest.php
Labels: bug, 3. to review, backport-request, feature: activity and notification, feature: caldav

#32696 Use Image class from public API
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/settings/lib/UserMigration/AccountMigrator.php
  core/Controller/AvatarController.php
  lib/private/Avatar/Avatar.php
  lib/private/Avatar/UserAvatar.php
  lib/private/Preview/Bitmap.php
  lib/private/Preview/Bundled.php
  lib/private/Preview/Generator.php
  lib/private/Preview/HEIC.php
  lib/private/Preview/Image.php
  lib/private/Preview/MP3.php
  lib/private/Preview/MarkDown.php
  lib/private/Preview/Movie.php
  lib/private/Preview/Office.php
  lib/private/Preview/SVG.php
  lib/private/Preview/TXT.php
Labels: 3. to review, backport-request, technical debt

#32690 Trim mount point before matching in encryption code
  lib/private/Encryption/Util.php
  tests/lib/Encryption/UtilTest.php
Labels: 3. to review, feature: encryption (server-side), feature: external storage, backport-request

#32570 Remove at() matcher from tests in federatedfilesharing
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
Labels: 3. to review, technical debt

#32662 Cleanup temporary files after finishing the write to object storage
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: bug, 3. to review, backport-request

#32702 Declare header entries in the order they are displayed
  core/templates/layout.user.php
Labels: 4. to release, feature: accessibility

#32713 Prevent button in notifications to be impacted by css rule
  core/css/header.css
  core/css/header.scss
  core/css/server.css
Labels: bug, 4. to release

#32715 Only load direct editing capabilities when required
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/AppInfo/Application.php
  apps/files/lib/Capabilities.php
  apps/files/lib/DirectEditingCapabilities.php
Labels: enhancement, 3. to review

#32716 l10n: Change to a capital letter
  apps/settings/lib/Controller/CheckSetupController.php
Labels: feature: language l10n and translations

#32435 Revert "Remove call to already default php.ini values"
  lib/base.php
Labels: 3. to review

#32620 Also reset the status on clearAt
  apps/user_status/lib/BackgroundJob/ClearOldStatusesBackgroundJob.php
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/lib/Db/UserStatusMapper.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/src/components/ClearAtSelect.vue
  apps/user_status/tests/Unit/BackgroundJob/ClearOldStatusesBackgroundJobTest.php
  apps/user_status/tests/Unit/Controller/UserStatusControllerTest.php
  apps/user_status/tests/Unit/Db/UserStatusMapperTest.php
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: bug, 3. to review, backport-request, feature: status

#26582 Add a helper function that makes it easier to log from anywhere
  composer.json
  lib/composer/composer/autoload_files.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/autoload_static.php
  lib/public/Log/functions.php
Labels: enhancement, 4. to release, pending documentation

#32481 Add docxf and form mimetypes
  core/img/filetypes/x-office-form-template.svg
  core/img/filetypes/x-office-form.svg
  core/js/mimetypelist.js
  lib/private/IntegrityCheck/Checker.php
  lib/private/Repair/RepairMimeTypes.php
  resources/config/mimetypealiases.dist.json
  tests/data/integritycheck/mimetypeListModified/core/js/mimetypelist.js
  tests/data/integritycheck/mimetypeListModified/core/signature.json
  tests/lib/IntegrityCheck/CheckerTest.php
  version.php
Labels: enhancement, 3. to review

#32744 Always log errors from sending federation api requests to ease debugging
  apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
  lib/private/Federation/CloudFederationProviderManager.php
Labels: bug, 4. to release

#32746 Add new share attributes column
  core/Migrations/Version25000Date20220515204012.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  version.php
Labels: enhancement, 3. to review, backport-request

#31981 Temporary passwords fixes 31952
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/ShareRequests.js
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  core/templates/publicshareauth.php
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review

#32697 Fix get avatar authorization
  lib/private/Avatar/AvatarManager.php
  tests/lib/Avatar/AvatarManagerTest.php
Labels: bug, 4. to release, backport-request

#32736 Augment keyboard accessibility of the contacts menu
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
  core/src/OC/contactsmenu/contact.handlebars
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: enhancement, 4. to release, feature: contacts menu, feature: accessibility

#32767 handle stream wrappers in SeekableHttpStream
  lib/private/Files/Stream/SeekableHttpStream.php
Labels: 3. to review, backport-request

#32765 Add back the deleted.png file
  core/img/actions/delete.png
Labels: bug, 2. developing, backport-request, technical debt

#32769 Specify the filter first for unified search
  core/src/services/UnifiedSearchService.js
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: enhancement, 3. to review

#32616 Augment file picker modal accessibility
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
  core/src/OC/dialogs.js
  core/src/Util/a11y.js
  core/src/jquery/css/jquery.ocdialog.scss
  core/src/jquery/ocdialog.js
  core/templates/filepicker.html
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: enhancement, 3. to review, feature: filepicker, feature: accessibility

#32728 Add matrix for psalm baseline update job
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review, technical debt

#32727 [stable22] Ignore vendor-bin
  .gitignore
Labels: 3. to review, technical debt

#32675 Validate custom dashboard background image
  apps/dashboard/lib/Service/BackgroundService.php
Labels: bug, 4. to release, backport-request, feature: dashboard

#32797 fix mounts mounted at the users home
  lib/private/Files/SetupManager.php
Labels: 3. to review, backport-request

#32794 [stable24] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32805 Avoid creating card activities for system user
  apps/dav/lib/CardDAV/Activity/Backend.php
  apps/dav/tests/unit/CardDAV/Activity/BackendTest.php
Labels: bug, 3. to review, feature: dav, feature: activity and notification, php, feature: carddav

#32768 perform onetime setup earlier to ensure wrappers are registered on time
  lib/private/Files/SetupManager.php
Labels: 3. to review, backport-request

#32723 Expose umask override value as config parameter: localstorage.umask
  config/config.sample.php
  lib/private/Files/Storage/Local.php
Labels: enhancement, 3. to review

#32800 Don't spam the log with fatals when maintenance mode is enabled or an…
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/lib/Connector/Sabre/MaintenancePlugin.php
  apps/dav/lib/Exception/ServerMaintenanceMode.php
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
Labels: bug, 3. to review, backport-request, feature: install and update

#32799 Fix exception handling when profile data is too long
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  lib/private/Accounts/AccountManager.php
Labels: bug, 3. to review, backport-request, feature: users and groups

#32748 Keep non default protocol in cloud id
  build/integration/features/bootstrap/WebDav.php
  build/integration/federation_features/federated.feature
  lib/private/User/User.php
  tests/lib/User/UserTest.php
Labels: bug, 3. to review, feature: federation

#32660 Feature: Add loglevel exported JS OC.config object
  config/config.sample.php
  lib/private/Template/JSConfigHelper.php
Labels: 3. to review, technical debt, pending documentation

#32806 Revert "Remove inefficient fed share scanner"
  apps/files_sharing/lib/External/Scanner.php
  apps/files_sharing/tests/External/ScannerTest.php
Labels: bug, 3. to review

#32741 l10n: Delete apostrophe
  apps/files/js/filelist.js
  apps/files/src/components/TransferOwnershipDialogue.vue
  apps/files/templates/list.php
  apps/files_sharing/lib/Controller/RemoteController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/templates/part.404.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/files_versions/appinfo/info.xml
  apps/settings/lib/Controller/AppSettingsController.php
  apps/settings/lib/Controller/ChangePasswordController.php
  apps/settings/src/components/BasicSettings/BackgroundJob.vue
  apps/theming/src/UserThemes.vue
  build/translation-checker.php
  dist/files-personal-settings.js
  dist/files-personal-settings.js.map
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/theming-theming-settings.js
  dist/theming-theming-settings.js.map
Labels: 3. to review, feature: language l10n and translations

#32361 Put calendar invites into the user's first available calendar
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/PublicCalendar.php
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/tests/unit/CalDAV/Schedule/PluginTest.php
Labels: 3. to review, feature: caldav

#32059 Fix issue #31692 of occ files:scan
  apps/files/lib/Command/Scan.php
Labels: bug, 3. to review, backport-request, feature: occ

#31771 Fix hook encryption with cron job
  apps/files_sharing/lib/ExpireSharesJob.php
  lib/private/Encryption/HookManager.php
Labels: 4. to release

#31622 Increase loglevel of Webcal parsing errors and modernize code
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/RefreshWebcalServiceTest.php
Labels: bug, 4. to release, php, feature: caldav

#31029 Expose additional emails in {DAV:}alternate-URI-set
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/files_versions/lib/AppInfo/Application.php
Labels: enhancement, 3. to review, feature: dav, feature: caldav

#30368 Allow DAV Object properties
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/DAV/CustomPropertiesBackend.php
  apps/dav/lib/Migration/RemoveObjectProperties.php
  apps/dav/lib/Migration/Version1024Date20211221144219.php
Labels: bug, 3. to review, feature: dav, php, feature: caldav

#32708 [24] store unencrypted size in the unencrypted_size column
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/Propagator.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/public/Files/Cache/ICacheEntry.php
  tests/lib/Files/ObjectStore/S3Test.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/HelperStorageTest.php
Labels: 4. to release

#32809 [stable22] Fix loading groupfolder info when share api is disabled
  apps/files_sharing/js/dist/additionalScripts.js
  apps/files_sharing/js/dist/additionalScripts.js.map
  apps/files_sharing/js/dist/files_sharing.js
  apps/files_sharing/js/dist/files_sharing.js.map
  apps/files_sharing/js/dist/files_sharing_tab.js
  apps/files_sharing/js/dist/files_sharing_tab.js.map
  apps/files_sharing/js/dist/main.js
  apps/files_sharing/js/dist/main.js.map
  apps/files_sharing/js/dist/personal-settings.js
  apps/files_sharing/js/dist/personal-settings.js.map
  apps/files_sharing/src/views/SharingTab.vue
Labels: bug, 4. to release

#32796 [stable22] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 4. to release, automated pr

#31345 Fix deletion of additional emails
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 4. to release, backport-request, feature: settings, feature: emails

#32833 [stable24] Fix exception handling when profile data is too long
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  lib/private/Accounts/AccountManager.php
Labels: bug, 3. to review

#32834 [stable23] Fix exception handling when profile data is too long
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  lib/private/Accounts/AccountManager.php
Labels: bug, 3. to review

#32835 [stable22] Fix exception handling when profile data is too long
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  lib/private/Accounts/AccountManager.php
Labels: bug, 4. to release

#31197 Add memcached unix socket instructions
  config/config.sample.php
Labels: 3. to review

#32774 Enable keyboard activation of legacy contacts menu
  core/src/jquery/contactsmenu.js
  dist/core-main.js
  dist/core-main.js.map
Labels: enhancement, 3. to review, feature: accessibility

#31637 Add password reset typed events and modernize LostController
  core/Controller/LostController.php
  core/Events/BeforePasswordResetEvent.php
  core/Events/PasswordResetEvent.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  tests/Core/Controller/LostControllerTest.php
Labels: enhancement, 3. to review, feature: authentication, technical debt, php

#32841 [stable24] Fix issue #31692 of occ files:scan
  apps/files/lib/Command/Scan.php
Labels: bug, 3. to review

#32848 [stable24] Revert "Remove inefficient fed share scanner"
  apps/files_sharing/lib/External/Scanner.php
  apps/files_sharing/tests/External/ScannerTest.php
Labels: 4. to release

#32847 Fix second integration test as well
  build/integration/federation_features/federated.feature
Labels: bug, 4. to release

#31966 store unencrypted size in the unencrypted_size column
  lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/MySqlExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/PgSqlExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/SqliteExpressionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/Propagator.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/public/DB/QueryBuilder/IExpressionBuilder.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  lib/public/Files/Cache/ICacheEntry.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/HelperStorageTest.php
Labels: 4. to release

#32853 Update dependencies in acceptance tests composer.lock
  tests/acceptance/composer.lock
Labels: 4. to release

#32785 24.0.2 RC1
  version.php
Labels: 3. to review

#32851 [stable22] Revert "Remove inefficient fed share scanner"
  apps/files_sharing/lib/External/Scanner.php
  apps/files_sharing/tests/External/ScannerTest.php
Labels: 4. to release

#32849 [stable23] Revert "Remove inefficient fed share scanner"
  apps/files_sharing/lib/External/Scanner.php
  apps/files_sharing/tests/External/ScannerTest.php
Labels: 4. to release

#32875 Fix 2FA setup vs set up typo
  core/templates/twofactorsetupselection.php
Labels: bug, 3. to review

#32351 Handle the move operation properly between shared calendars
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/CalDAV/Activity/Backend.php
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/lib/CalDAV/Activity/Provider/Todo.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/CalendarObject.php
  apps/dav/lib/Events/CalendarObjectMovedEvent.php
  apps/dav/lib/Listener/ActivityUpdaterListener.php
Labels: 3. to review, feature: activity and notification, feature: caldav

#32584 Make sure ResetTokenBackgroundJob doesn't execute if config is read-only
  apps/updatenotification/lib/ResetTokenBackgroundJob.php
  apps/updatenotification/tests/ResetTokenBackgroundJobTest.php
Labels: bug, 4. to release, backport-request, feature: activity and notification

#32878 Fix default toast message for failed uploads with HTTP/2
  apps/files/js/file-upload.js
Labels: bug, 3. to review, backport-request

#32876 Use {$var} instead of ${var} for PHP 8.2 compatibility
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/files/lib/Command/RepairTree.php
  lib/private/L10N/L10N.php
  lib/private/Mail/EMailTemplate.php
  lib/private/Setup/MySQL.php
Labels: 3. to review, php

#32898 Fix logger overwriting vars in some circumstances
  lib/private/Log/ExceptionSerializer.php
  tests/lib/Log/ExceptionSerializerTest.php
Labels: bug, 4. to release, backport-request

#32917 Revert "[stable22] Fix replacing external storage password during debug log"
  lib/private/Authentication/LoginCredentials/Store.php
Labels: 3. to review

#32914 22.2.9
  version.php
Labels: 3. to review

#32910 Fix profiler trying to serialize invalid utf8
  apps/user_ldap/lib/LDAP.php
Labels: bug, 3. to review, backport-request

#32719 Fix email shares not being shown to other users
  apps/sharebymail/lib/ShareByMailProvider.php
  tests/lib/Share20/ShareByMailProviderTest.php
Labels: bug, 4. to release, feature: sharing, backport-request

#32881 l10n: Spelling unification
  apps/dav/lib/CalDAV/Activity/Filter/Todo.php
  apps/dav/lib/CalDAV/Activity/Provider/Todo.php
  apps/dav/lib/CalDAV/Activity/Setting/Todo.php
Labels: feature: language l10n and translations

#32921 23.0.6
  version.php
Labels: 3. to review

#32824 [stable24] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32900 Remove at matcher in theming tests
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/IconBuilderTest.php
  apps/theming/tests/ImageManagerTest.php
  apps/theming/tests/Settings/PersonalTest.php
  apps/theming/tests/ThemingDefaultsTest.php
Labels: 3. to review, technical debt

#32861 Remove deprecated at() matcher from user_ldap tests
  apps/user_ldap/tests/LDAPProviderTest.php
  apps/user_ldap/tests/Migration/UUIDFixInsertTest.php
  apps/user_ldap/tests/User/UserTest.php
Labels: 3. to review, technical debt

#32902 do not display the buffer_size info if the size is already set to a c…
  apps/settings/lib/Controller/CheckSetupController.php
Labels: enhancement, 3. to review

#32924 Enable binary protocol again
  lib/private/Memcache/Memcached.php
Labels: bug, 3. to review, backport-request, regression

#32823 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32816 [22] handle stream wrappers in SeekableHttpStream
  lib/private/Files/Stream/SeekableHttpStream.php
Labels: 3. to review, backport-request

#31475 files: close open directory file descriptor on error path
  lib/private/Files/Storage/Common.php
Labels: bug, 4. to release

#32242 Fix logging data context to file
  lib/private/Log.php
  lib/private/Log/LogDetails.php
  tests/lib/Log/FileTest.php
  tests/lib/LoggerTest.php
Labels: bug, 4. to release

#32964 Add title to file name
  apps/files/js/filelist.js
Labels: 3. to review, papercut

#32884 Add typing to Sharing Backend
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CardDAV/AddressBook.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Command/MoveCalendar.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/lib/DAV/Sharing/IShareable.php
  apps/dav/lib/Events/CalendarShareUpdatedEvent.php
  apps/dav/tests/unit/BackgroundJob/CleanupInvitationTokenJobTest.php
  apps/dav/tests/unit/Controller/InvitationResponseControllerTest.php
  build/psalm-baseline.xml
Labels: 3. to review

#32971 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32988 Improve local domain detection
  lib/private/Http/Client/LocalAddressChecker.php
Labels: 4. to release, backport-request

#32322 [stable23] Add share search tweaks
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  build/integration/features/bootstrap/CollaborationContext.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: 3. to review, feature: sharing, backport-request, feature: search

#32962 Remove .php from url
  apps/files/appinfo/routes.php
  apps/files/js/files.js
Labels: 3. to review

#32957 Fix importing float value
  core/Command/Config/Import.php
Labels: bug, 3. to review

#32980 load dashboard widgets of enabled apps only
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Dashboard/Manager.php
  lib/public/Dashboard/IManager.php
Labels: bug, 3. to review, feature: dashboard

#32863 Add comments expire date
  apps/dav/tests/unit/Comments/CommentsNodeTest.php
  core/Migrations/Version25000Date20220602190540.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Comments/Comment.php
  lib/private/Comments/Manager.php
  lib/public/Comments/IComment.php
  lib/public/Comments/ICommentsManager.php
  tests/lib/Comments/FakeManager.php
  tests/lib/Comments/ManagerTest.php
Labels: enhancement, 4. to release, feature: comments

#32998 Rename setting name to reduce its length
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/admin.js
  apps/settings/tests/Settings/Admin/SharingTest.php
  build/integration/features/bootstrap/CollaborationContext.php
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
  lib/private/Collaboration/Collaborators/UserPlugin.php
  lib/private/Share20/Manager.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: bug, 4. to release, backport-request

#32968 [stable24] do not display the buffer_size info if the size is already set to a c…
  apps/settings/lib/Controller/CheckSetupController.php
Labels: enhancement, 3. to review, backport-request

#33029 [stable23] Rename setting name to reduce its length
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  build/integration/features/bootstrap/CollaborationContext.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  lib/private/Share20/Manager.php
  tests/lib/Collaboration/Collaborators/UserPluginTest.php
Labels: bug, 4. to release

#32960 Fix PHP 8.2 warnings about undeclared properties
  lib/private/App/Platform.php
  lib/private/App/PlatformRepository.php
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/DB/MigrationService.php
  lib/private/Files/Node/File.php
  lib/private/Files/Node/Folder.php
  tests/lib/AppFramework/Http/DispatcherTest.php
Labels: 3. to review

#32982 Fix metadata extraction
  lib/private/Files/FileInfo.php
Labels: 3. to review, backport-request

#33042 Extend email logging
  lib/private/Mail/Mailer.php
Labels: bug, 3. to review

#33034 cleanup LDAP's UpdateGroups
  apps/user_ldap/lib/Jobs/UpdateGroups.php
  apps/user_ldap/tests/Jobs/UpdateGroupsTest.php
Labels: 4. to release, feature: ldap, technical debt

#33057 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#33050 Check whether entry is of type ICacheEntry in Cache->remove()
  lib/private/Files/Cache/Cache.php
Labels: 3. to review, feature: filesystem, backport-request

#32857 Fix undefined when no tags
  core/Command/SystemTag/ListCommand.php
Labels: bug, 4. to release, backport-request

#33067 use size from cache to determine whether to skip the trashbin
  apps/files_trashbin/lib/Trashbin.php
Labels: 3. to review, feature: trashbin

#33065 Fix detection of firefox in ContentSecurityPolicyNonceManager
  lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php
Labels: 4. to release

#33074 use an en-dash for the userstatus panel
  apps/user_status/src/components/PredefinedStatus.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: design, 4. to release

#33075 Run performance testing in CI
  .github/workflows/performance.yml
  tests/blueprints/basic.toml
Labels: 3. to review
