Repository nextcloud/server, pull requests merged in 2022-08, with the labels that each got.

#32482 Add share attributes + prevent download permission
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Connector/Sabre/Node.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Controller/DirectController.php
  apps/dav/lib/DAV/ViewOnlyPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/NodeTest.php
  apps/dav/tests/unit/Controller/DirectControllerTest.php
  apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
  apps/files/js/fileinfomodel.js
  apps/files/src/services/FileInfo.js
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/PublicPreviewController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/ViewOnly.php
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/mixins/ShareRequests.js
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/models/Share.js
  apps/files_sharing/src/share.js
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/ApplicationTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/files_sharing/tests/MountProviderTest.php
  core/src/files/client.js
  core/src/files/fileinfo.js
  dist/core-files_client.js
  dist/core-files_client.js.map
  dist/core-files_fileinfo.js
  dist/core-files_fileinfo.js.map
  dist/files-sidebar.js
  dist/files-sidebar.js.map
  dist/files_sharing-additionalScripts.js
  dist/files_sharing-additionalScripts.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/private/Share20/Share.php
  lib/private/Share20/ShareAttributes.php
  lib/private/legacy/OC_Files.php
  lib/public/Files/Events/BeforeDirectFileDownloadEvent.php
  lib/public/Files/Events/BeforeZipCreatedEvent.php
  lib/public/Share/IAttributes.php
  lib/public/Share/IShare.php
  tests/lib/Share20/DefaultShareProviderTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release

#33103 [Stable23] Logging, updating status for general error in federation
  apps/dav/lib/CardDAV/SyncService.php
  apps/federation/lib/SyncFederationAddressBooks.php
  apps/federation/lib/SyncJob.php
  apps/federation/tests/SyncFederationAddressbooksTest.php
Labels: enhancement, 4. to release, feature: federation

#33408 [stable23] DAV custom props: catch Exception and rollback transaction in case
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: bug, 3. to review, feature: dav

#33432 Remove "needs info" label when the issue is not stale anymore
  .github/workflows/stale.yml
Labels: 4. to release

#33428 Improve Devices & sessions settings
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
Labels: 3. to review, accessibility

#33425 Fix dynamic property creations in test files
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
  lib/public/Files/Cache/ICache.php
  tests/lib/DirectEditing/ManagerTest.php
  tests/lib/Metadata/FileMetadataMapperTest.php
  tests/lib/Repair/RepairMimeTypesTest.php
  tests/lib/User/SessionTest.php
Labels: 4. to release

#32958 Fix file public link permissions if public upload is not enabled
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: bug, 4. to release, feature: sharing

#33407 [stable24] Handle one time and large passwords
  apps/settings/lib/Controller/ChangePasswordController.php
  config/config.sample.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
Labels: 3. to review, backport-request

#33451 Update node workflow for better error messages
  .github/workflows/node.yml
Labels: 3. to review

#32852 Revert "Revert "Remove inefficient fed share scanner""
  apps/files_sharing/lib/External/Scanner.php
  apps/files_sharing/tests/External/ScannerTest.php
Labels: 1. to develop, backport-request, performance 🚀

#32615 Support specifying IPv6 proxies in CIDR notation
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: enhancement, 3. to review

#33435 Remove at matchers from tests in oauth2 and tests/Test
  apps/oauth2/tests/Controller/SettingsControllerTest.php
  tests/Test/Repair/Owncloud/CleanPreviewsBackgroundJobTest.php
  tests/Test/Repair/Owncloud/CleanPreviewsTest.php
  tests/Test/Repair/Owncloud/UpdateLanguageCodesTest.php
Labels: 3. to review

#33447 Detect leading spaces in config files
  lib/private/Config.php
Labels: enhancement, 4. to release

#33421 23.0.8rc1
  version.php
Labels: 3. to review

#33420 24.0.4rc1
  version.php
Labels: 3. to review

#33448 Fix label for allow download share permission
  apps/files_sharing/src/components/SharingEntry.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 4. to release, backport-request

#33398 allow apps to specify methods carrying sensitive parameters
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Log.php
  lib/private/Log/ExceptionSerializer.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  tests/lib/Log/ExceptionSerializerTest.php
Labels: 3. to review, pending documentation

#33357 Fix accessibility of buttons in the external storage configuration
  apps/files_external/css/settings.css
  apps/files_external/css/settings.css.map
  apps/files_external/css/settings.scss
  apps/files_external/js/settings.js
  apps/files_external/templates/settings.php
Labels: 3. to review, accessibility

#32363 Remove OCP\App and OCP\BackgroundJob
  apps/dav/lib/Connector/Sabre/File.php
  apps/encryption/templates/mail.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/files_trashbin/lib/Trashbin.php
  apps/provisioning_api/tests/Controller/AppsControllerTest.php
  apps/user_ldap/templates/part.settingcontrols.php
  apps/user_ldap/templates/part.wizardcontrols.php
  core/Command/Maintenance/Repair.php
  core/Command/User/ResetPassword.php
  core/register_command.php
  core/templates/installation.php
  core/templates/layout.base.php
  core/templates/layout.guest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/App.php
  lib/private/Console/Application.php
  lib/private/Encryption/File.php
  lib/private/Encryption/Util.php
  lib/private/Server.php
  lib/private/URLGenerator.php
  lib/private/Updater.php
  lib/private/legacy/OC_App.php
  lib/public/App.php
  lib/public/App/IAppManager.php
  lib/public/BackgroundJob.php
  tests/lib/Encryption/UtilTest.php
  tests/lib/UrlGeneratorTest.php
Labels: 2. developing

#33415 Fix integration tests
  tests/acceptance/features/bootstrap/NotificationsContext.php
Labels: 4. to release

#33465 Fix "More" app icon in dark mode
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review

#33174 Do not redirect if requested font, style or script can not be found
  lib/base.php
Labels: bug, 4. to release

#33480 Fix workflow engine a11y and spacing of icons
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/workflowengine/src/components/Checks/FileMimeType.vue
  apps/workflowengine/src/components/Checks/RequestURL.vue
  apps/workflowengine/src/components/Event.vue
  apps/workflowengine/src/styles/operation.scss
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows, accessibility

#33442 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#33485 Do not update passwords if nothing changed
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: 4. to release, performance 🚀

#33173 Set special header for 503 maintenance mode
  lib/base.php
Labels: enhancement, 3. to review, integration

#32830 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#33497 Do not overwrite the focus-visible of vue apps
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
Labels: bug, 3. to review, feature: theming, accessibility

#33452 Fix first run wizzard
  apps/theming/lib/Themes/DefaultTheme.php
Labels: 3. to review

#33282 Buttonify comment posting
  apps/comments/src/components/Comment.vue
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
Labels: 3. to review, feature: comments, accessibility

#33477 Update npm and node engines versions
  package.json
Labels: dependencies

#33504 24.0.4
  version.php
Labels: 3. to review

#33503 23.0.8
  version.php
Labels: 3. to review

#33506 Fix trusted domain error page
  core/templates/untrustedDomain.php
Labels: bug, 4. to release, regression, accessibility

#33510 Fix unit tests for the theming app
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/tests/ImageManagerTest.php
  apps/theming/tests/Themes/DefaultThemeTest.php
Labels: 3. to review

#33513 Recover installation when creating the database user fails and improve password strength
  lib/private/Setup/MySQL.php
Labels: bug, 4. to release, backport-request, feature: install and update

#33505 25.0.0beta1
  version.php
Labels: 4. to release

#33517 Allow symlinks during webpack build
  webpack.common.js
Labels: 4. to release

#33518 fix exif metadata provider
  lib/private/Metadata/Provider/ExifProvider.php
Labels: 3. to review

#33519 l10n: Change plural to singular
  apps/dashboard/src/components/BackgroundSettings.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: 3. to review, papercut, feature: language l10n and translations

#33495 Unify initial and updated quota display
  apps/files/js/files.js
  apps/files/lib/Helper.php
  apps/files/templates/appnavigation.php
Labels: bug, 3. to review, backport-request, feature: files

#33548 Remove redundant events
  apps/files/lib/Controller/ViewController.php
  apps/files_sharing/list.php
Labels: bug, 3. to review, performance 🚀

#33556 Revert "First first run wizzard"
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/tests/ImageManagerTest.php
  apps/theming/tests/Themes/DefaultThemeTest.php
Labels: 3. to review, feature: theming, regression

#32461 expose display name cache trough a public interface
  lib/private/Files/View.php
  lib/private/Server.php
  lib/private/User/LazyUser.php
  lib/private/User/Manager.php
  lib/public/IUserManager.php
  tests/lib/User/ManagerTest.php
Labels: 3. to review

#33563 Make DisplayNameCache return null if user doesn't exists
  apps/files_sharing/lib/Cache.php
  lib/private/User/DisplayNameCache.php
  lib/private/User/LazyUser.php
  lib/private/User/Manager.php
  lib/public/IUserManager.php
Labels: 3. to review

#33559 fixed the cache searchBuilder negative map
  lib/private/Files/Cache/SearchBuilder.php
Labels: bug, 3. to review

#33549 Performance optimisation for carddav backend blob data read
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: enhancement, 4. to release, performance 🚀

#33551 don't update the folder size if we know it hasn't changed
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/ObjectStore/NoopScanner.php
  tests/lib/Files/Cache/ScannerTest.php
Labels: 2. developing, performance 🚀

#33540 fix updating cached mounts that didn't have their mount provider set previously
  lib/private/Files/Config/UserMountCache.php
  tests/lib/Files/Config/UserMountCacheTest.php
Labels: 3. to review

#33550 optimize search post-processing for jail wrapper
  lib/private/Files/Cache/Wrapper/CacheJail.php
Labels: 3. to review, performance 🚀

#33562 [24] fix updating size when folder is empty
  lib/private/Files/Cache/Cache.php
Labels: 3. to review

#32943 Revert interface changes from "store unencrypted size in the unencrypted_size column"
  lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/MySqlExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/PgSqlExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/SqliteExpressionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Propagator.php
  lib/public/DB/QueryBuilder/IExpressionBuilder.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
  tests/lib/Files/ObjectStore/S3Test.php
Labels: 3. to review

#33565 Remove time check in isFairUseOfFreePushService
  lib/private/Notification/Manager.php
  tests/lib/Notification/ManagerTest.php
Labels: 4. to release, technical debt, php

#33526 Fix duplicate ids on apps management page
  apps/settings/src/components/SvgFilterMixin.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: apps management, feature: settings, accessibility

#33558 Use bigger slice in share provider
  lib/private/Share20/DefaultShareProvider.php
Labels: 3. to review, feature: sharing

#33573 make transparent what is community maintained
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: enhancement, 3. to review

#33584 Fix font change preview update
  apps/theming/src/UserThemes.vue
  apps/theming/src/components/ItemPreview.vue
  dist/theming-theming-settings.js
  dist/theming-theming-settings.js.map
Labels: 4. to release, feature: theming, 25-feedback

#33575 further pre-filter search result before setting up share source cache
  apps/files_sharing/lib/Cache.php
Labels: 3. to review, performance 🚀

#33522 Fix/358 add missing expanded attributes
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
  apps/files/js/navigation.js
  apps/files/js/newfilemenu.js
  apps/files/templates/appnavigation.php
  apps/settings/js/federationsettingsview.js
  apps/systemtags/js/admin.js
  apps/systemtags/src/systemtagsfilelist.js
  apps/theming/js/3rdparty/jscolor/jscolor.js
  apps/theming/js/settings-admin.js
  core/src/OC/menu.js
  core/src/components/HeaderMenu.vue
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  dist/systemtags-systemtags.js
  dist/systemtags-systemtags.js.map
Labels: 4. to release, accessibility

#33617 Fix carddav activities
  apps/dav/lib/CardDAV/Activity/Backend.php
  apps/dav/lib/CardDAV/Activity/Provider/Addressbook.php
  apps/dav/lib/CardDAV/Activity/Provider/Card.php
  apps/dav/tests/unit/CardDAV/Activity/BackendTest.php
Labels: bug, 4. to release, backport-request, feature: activity and notification

#33614 Use user displayname cache for comment mentions
  apps/comments/lib/Notification/Notifier.php
  apps/comments/tests/Unit/Notification/NotifierTest.php
  lib/private/Server.php
Labels: bug, 3. to review, feature: comments, performance 🚀

#33615 Use user name cache in activity providers
  apps/comments/lib/Activity/Provider.php
  apps/dav/lib/CalDAV/Activity/Provider/Base.php
  apps/dav/lib/CardDAV/Activity/Provider/Base.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/BaseTest.php
  apps/files/lib/Activity/Provider.php
  apps/files/tests/Activity/ProviderTest.php
  apps/files_sharing/lib/Activity/Providers/Base.php
  apps/settings/lib/Activity/GroupProvider.php
  apps/settings/lib/Activity/Provider.php
  apps/sharebymail/lib/Activity.php
  apps/systemtags/lib/Activity/Provider.php
Labels: bug, 3. to review, feature: activity and notification, performance 🚀

#33610 🔢 Add css variables for blur background
  apps/dashboard/src/DashboardApp.vue
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Themes/HighContrastTheme.php
  apps/theming/tests/Themes/DefaultThemeTest.php
  core/img/app-background.jpg
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: design, 4. to release

#33592 25.0.0 beta 2
  version.php
Labels: 3. to review

#33433 Fix encryption:fix-encrypted-version command when encrypted is set to 0
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
Labels: 3. to review, backport-request

#33624 Update crl after revoke money.csr
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#33638 Request 64px avatars for the user management
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
  apps/settings/src/mixins/UserRowMixin.js
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, technical debt

#33643 Improve handling of profile page
  core/Controller/ProfilePageController.php
Labels: bug, 4. to release, feature: profile

#33001 Support iMIP invitations from Mail
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/CalendarHome.php
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/CalendarProvider.php
  apps/dav/tests/unit/CalDAV/CalendarImplTest.php
  lib/private/Calendar/Manager.php
  lib/public/Calendar/ICreateFromString.php
  lib/public/Calendar/IManager.php
  tests/lib/Calendar/ManagerTest.php
Labels: enhancement, 3. to review, feature: caldav

#33639 Fix plural usage in LDAP wizard
  apps/user_ldap/lib/Wizard.php
Labels: bug, 3. to review, feature: ldap, feature: language l10n and translations

#33607 [stable22] Add testing for mariadb10.6
  .drone.yml
Labels: 3. to review, dependencies

#33650 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#33606 [stable23] Add testing for mariadb10.6
  .drone.yml
Labels: 3. to review, dependencies

#33595 Cache ConfigProfile
  lib/private/Profile/ProfileManager.php
Labels: 3. to review, performance 🚀

#32162 Avoid locking the php session
  config/config.sample.php
  lib/base.php
  lib/private/AppFramework/Middleware/SessionMiddleware.php
  lib/private/Session/CryptoSessionData.php
  lib/private/Session/Internal.php
  lib/private/Session/Memory.php
  lib/public/ISession.php
Labels: 3. to review, performance 🚀

#33574 directly build the search filter for shared storage instead of setting up the source cache
  apps/files_sharing/lib/Cache.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
Labels: 3. to review, backport-request, performance 🚀

#33047 Deprecated ILogger from IJob
  apps/federatedfilesharing/lib/BackgroundJob/RetryJob.php
  apps/federation/lib/BackgroundJob/GetSharedSecret.php
  apps/federation/tests/BackgroundJob/GetSharedSecretTest.php
  apps/files/lib/BackgroundJob/ScanFiles.php
  apps/files/tests/BackgroundJob/ScanFilesTest.php
  apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php
  apps/files_trashbin/tests/BackgroundJob/ExpireTrashTest.php
  apps/files_versions/lib/BackgroundJob/ExpireVersions.php
  apps/files_versions/tests/BackgroundJob/ExpireVersionsTest.php
  apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php
  apps/updatenotification/tests/Settings/AdminTest.php
  apps/user_ldap/lib/Jobs/Sync.php
  apps/user_ldap/tests/Jobs/SyncTest.php
  core/BackgroundJobs/BackgroundCleanupUpdaterBackupsJob.php
  core/BackgroundJobs/CheckForUserCertificates.php
  core/BackgroundJobs/LookupServerSendCheckBackgroundJob.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/BackgroundJob/Job.php
  lib/private/BackgroundJob/Legacy/QueuedJob.php
  lib/private/BackgroundJob/Legacy/RegularJob.php
  lib/private/Log/Rotate.php
  lib/private/Migration/BackgroundRepair.php
  lib/private/Security/VerificationToken/CleanUpJob.php
  lib/public/BackgroundJob/IJob.php
  lib/public/BackgroundJob/Job.php
  lib/public/BackgroundJob/QueuedJob.php
  lib/public/BackgroundJob/TimedJob.php
  tests/lib/App/DependencyAnalyzerTest.php
  tests/lib/BackgroundJob/DummyJobList.php
  tests/lib/Migration/BackgroundRepairTest.php
Labels: 3. to review

#33651 [stable24] Fix carddav activities
  apps/dav/lib/CardDAV/Activity/Backend.php
  apps/dav/lib/CardDAV/Activity/Provider/Addressbook.php
  apps/dav/lib/CardDAV/Activity/Provider/Card.php
Labels: bug, 3. to review, backport-request, feature: activity and notification

#33663 [stable24] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#33593 Move findBinaryFinder and isFunctionEnabled away from OC_Helper
  apps/admin_audit/composer/composer/installed.php
  apps/cloud_federation_api/composer/composer/installed.php
  apps/comments/composer/composer/installed.php
  apps/contactsinteraction/composer/composer/installed.php
  apps/dav/composer/composer/installed.php
  apps/encryption/composer/composer/installed.php
  apps/federatedfilesharing/composer/composer/installed.php
  apps/federation/composer/composer/installed.php
  apps/files/composer/composer/installed.php
  apps/files_sharing/composer/composer/installed.php
  apps/files_trashbin/composer/composer/installed.php
  apps/files_versions/composer/composer/installed.php
  apps/lookup_server_connector/composer/composer/installed.php
  apps/oauth2/composer/composer/installed.php
  apps/provisioning_api/composer/composer/installed.php
  apps/settings/composer/composer/installed.php
  apps/sharebymail/composer/composer/installed.php
  apps/systemtags/composer/composer/installed.php
  apps/testing/composer/composer/installed.php
  apps/twofactor_backupcodes/composer/composer/installed.php
  apps/updatenotification/composer/composer/installed.php
  apps/user_ldap/composer/composer/installed.php
  apps/user_status/composer/composer/installed.php
  apps/workflowengine/composer/composer/installed.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/App/Platform.php
  lib/private/BinaryFinder.php
  lib/private/LargeFileHelper.php
  lib/private/Mail/Mailer.php
  lib/private/PreviewManager.php
  lib/private/Server.php
  lib/private/legacy/OC_Helper.php
  lib/public/IBinaryFinder.php
  lib/public/Util.php
  tests/lib/LargeFileHelperGetFileSizeTest.php
  tests/lib/Mail/MailerTest.php
Labels: 3. to review, performance 🚀

#33670 Update typehint for confirmDestructive
  core/src/OC/dialogs.js
  dist/core-login.js.map
  dist/core-main.js.map
Labels: 3. to review, technical debt

#33662 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#33667 [stable24] Fix plural usage in LDAP wizard
  apps/user_ldap/lib/Wizard.php
Labels: bug, 3. to review, feature: ldap, backport-request

#33569 Add config option to hide deprecated projects in sharing tab by default
  apps/files_sharing/src/views/SharingTab.vue
  config/config.sample.php
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  lib/private/Template/JSConfigHelper.php
Labels: 3. to review, feature: projects

#33602 Optimize Node::getParent and usage in previews
  lib/private/Files/Node/Folder.php
  lib/private/Files/Node/Node.php
  lib/private/Preview/ProviderV1Adapter.php
  tests/lib/Files/Node/FolderTest.php
Labels: 4. to release, performance 🚀

#33682 Fix opening Help page throwing Exception
  apps/settings/lib/Controller/HelpController.php
  lib/private/URLGenerator.php
Labels: bug, 3. to review

#33668 Fix SessionMiddlewareTest and cover new case with reopening
  tests/lib/AppFramework/Middleware/SessionMiddlewareTest.php
Labels: 3. to review, tests

#33676 [stable24] Update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#33677 [stable23] Update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#33678 [stable22] Update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#33679 [stable21] Update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#33680 [stable20] Update CRL
  resources/codesigning/root.crl
Labels: 3. to review

#33689 [stable24] logger ignore args of sharepoint-related methods
  lib/private/Log/ExceptionSerializer.php
Labels: bug, 3. to review, backport-request

#33375 Add back TokenCleanupJob to invalidate old temporary tokens
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Token/TokenCleanupJob.php
  lib/private/Repair.php
  lib/private/Repair/NC24/AddTokenCleanupJob.php
  lib/private/Setup.php
Labels: 3. to review, high, backport-request, feature: authentication

#33430 Remove broken function resetStorage from test cases
  apps/federatedfilesharing/tests/TestCase.php
  apps/files_sharing/tests/TestCase.php
Labels: 3. to review

#33285 Remake location property saving with Vue
  apps/settings/js/federationsettingsview.js
  apps/settings/lib/Settings/Personal/PersonalInfo.php
  apps/settings/src/components/PersonalInfo/LocationSection.vue
  apps/settings/src/constants/AccountPropertyConstants.js
  apps/settings/src/main-personal-info.js
  apps/settings/templates/settings/personal/personal.info.php
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: enhancement, 3. to review, feature: settings, feature: accessibility, accessibility

#33347 feature: use the viewer to render single file shares
  apps/files_sharing/css/mobile.css
  apps/files_sharing/css/mobile.css.map
  apps/files_sharing/css/mobile.scss
  apps/files_sharing/css/public.css
  apps/files_sharing/css/public.css.map
  apps/files_sharing/css/public.scss
  apps/files_sharing/css/publicView.css
  apps/files_sharing/css/publicView.css.map
  apps/files_sharing/js/public.js
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/templates/public.php
Labels: 4. to release

#33604 [24] further pre-filter search result before setting up share source cache
  apps/files_sharing/lib/Cache.php
Labels: 3. to review, backport-request

#33714 Add composer.lock for integration tests
  build/integration/composer.lock
Labels: 3. to review, technical debt

#33707 Avoid size changes on web ui update
  core/css/guest.css
Labels: bug, 3. to review

#33259 Fix various accessibility issues
  apps/dashboard/src/DashboardApp.vue
  apps/files/css/files.css
  apps/files/css/files.css.map
  apps/files/css/files.scss
  apps/files/css/merged.css
  apps/files/css/merged.css.map
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/LanguageSection/Language.vue
  apps/settings/src/components/PersonalInfo/shared/AccountPropertySection.vue
  apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
  apps/settings/src/store/users.js
  apps/settings/templates/settings/personal/security/password.php
  apps/user_status/src/components/ClearAtSelect.vue
  apps/user_status/src/components/CustomMessageInput.vue
  apps/user_status/src/components/SetStatusModal.vue
  apps/workflowengine/src/components/Check.vue
  apps/workflowengine/src/components/Workflow.vue
  core/css/guest.css
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
  core/src/OC/l10n.js
  core/src/OC/query-string.js
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js.map
  dist/dashboard-main.js
  dist/dashboard-main.js.map
  dist/settings-vue-settings-apps-users-management.js.map
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
  lib/private/Template/JSResourceLocator.php
Labels: 3. to review, feature: accessibility

#33702 Fix weather icon
  apps/weather_status/src/App.vue
  dist/weather_status-weather-status.js
  dist/weather_status-weather-status.js.map
Labels: bug, 3. to review, feature: dashboard

#33641 Fix primary element color variables
  apps/settings/css/settings.css
  apps/settings/css/settings.scss
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: bug, 4. to release

#33713 Fix copy in view-only mode
  apps/dav/lib/DAV/ViewOnlyPlugin.php
  apps/files/js/fileactions.js
  apps/files/js/fileinfomodel.js
  apps/files_sharing/src/share.js
  build/composer
  build/integration/features/bootstrap/Sharing.php
  build/integration/sharing_features/sharing-v1-part2.feature
  dist/files_sharing-additionalScripts.js
  dist/files_sharing-additionalScripts.js.map
Labels: bug, 4. to release, backport-request

#33310 Remake website property saving with Vue
  apps/settings/js/federationsettingsview.js
  apps/settings/lib/Settings/Personal/PersonalInfo.php
  apps/settings/src/components/PersonalInfo/WebsiteSection.vue
  apps/settings/src/main-personal-info.js
  apps/settings/src/utils/validate.js
  apps/settings/templates/settings/personal/personal.info.php
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: enhancement, 4. to release, feature: settings, feature: accessibility, accessibility

#33694 Make it possible to load theme/<themename>/dist
  lib/private/Template/JSResourceLocator.php
Labels: 4. to release

#33706 Fix status button background on dashboard
  apps/dashboard/src/DashboardApp.vue
  apps/user_status/src/UserStatus.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: bug, 3. to review, feature: status

#33500 add marker interface to mark system mount points for encryption
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Config/SystemMountPoint.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Encryption/Util.php
  lib/public/Files/Mount/ISystemMountPoint.php
Labels: 3. to review

#33732 Remove deprecated at matcher in tests/lib part 2
  tests/lib/L10N/FactoryTest.php
  tests/lib/Mail/MailerTest.php
  tests/lib/OCS/ProviderTest.php
  tests/lib/Repair/ClearFrontendCachesTest.php
  tests/lib/Repair/NC11/FixMountStoragesTest.php
  tests/lib/Security/CertificateManagerTest.php
  tests/lib/Security/IdentityProof/ManagerTest.php
  tests/lib/Share20/ManagerTest.php
  tests/lib/Template/JSCombinerTest.php
  tests/lib/Updater/VersionCheckTest.php
  tests/lib/User/ManagerTest.php
Labels: 3. to review

#33734 remove leading slash for search results at mountpoint root
  lib/private/Files/Node/Folder.php
Labels: 3. to review, backport-request

#33697 Improve bulk upload and add a config switch for it
  apps/dav/lib/BulkUpload/BulkUploadPlugin.php
  apps/dav/lib/Capabilities.php
  apps/dav/lib/Connector/Sabre/Node.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CapabilitiesTest.php
  config/config.sample.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Files/DavUtil.php
Labels: 3. to review

#33603 [24] optimize search post-processing for jail wrapper
  lib/private/Files/Cache/Wrapper/CacheJail.php
Labels: 3. to review, backport-request

#33746 Add a11y attributes for legacy app navigation
  apps/files/js/navigation.js
  apps/files/templates/appnavigation.php
  apps/settings/templates/help.php
  apps/settings/templates/settings/frame.php
Labels: 3. to review, accessibility

#33767 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#33770 Fix wording of undeliverable push notifications
  core/Controller/LoginController.php
  core/js/setupchecks.js
  lib/private/Notification/Manager.php
Labels: bug, 4. to release, feature: activity and notification

#33771 Fix eslint run command
  package.json
Labels: 4. to release, developer experience

#33756 add a way to open the admin settings overview directly
  apps/settings/lib/Controller/CommonSettingsTrait.php
  lib/private/NavigationManager.php
  tests/acceptance/features/access-levels.feature
  tests/acceptance/features/app-files-sharing-link.feature
  tests/acceptance/features/app-files-sharing.feature
  tests/acceptance/features/app-files-tags.feature
  tests/acceptance/features/app-theming.feature
  tests/acceptance/features/bootstrap/SettingsMenuContext.php
  tests/acceptance/features/header.feature
  tests/lib/NavigationManagerTest.php
Labels: enhancement, 4. to release

#33475 l10n: Changed grammar
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 4. to release, feature: language l10n and translations

#33778 Fix unit tests
  tests/Core/Controller/LoginControllerTest.php
  tests/lib/Notification/ManagerTest.php
Labels: 4. to release
