Repository nextcloud/server, pull requests merged in 2022-01, with the labels that each got.

#30358 Reset job disabling timer on adding the job again
  lib/private/BackgroundJob/JobList.php
Labels: bug, 3. to review

#30423 Fix uploading text position
  apps/files/css/files.scss
Labels: bug, design, 3. to review, backport-request, feature: files

#29780 Run migrations fully when reenabling an app
  lib/private/Installer.php
Labels: bug, 3. to review, backport-request, feature: install and update, feature: apps management

#30469 Improve api documentation/type hinting for file sharing external storage
  apps/files_sharing/lib/External/Storage.php
  build/psalm-baseline.xml
Labels: 3. to review

#30393 Add group_concat aggregator function
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/PgSqlFunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
Labels: enhancement, 3. to review, php

#30492 Fix passing on the parameter
  apps/files_sharing/lib/External/Scanner.php
Labels: bug, 4. to release, feature: sharing, feature: external storage

#29921 Allow to count comments with multiple verbs
  lib/private/Comments/Manager.php
  lib/public/Comments/ICommentsManager.php
  tests/lib/Comments/FakeManager.php
Labels: enhancement, 4. to release, feature: comments

#30269 [stable20] Support LDAP dns longer than 255 characters
  .drone.yml
  apps/user_ldap/appinfo/info.xml
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/user_ldap/lib/Migration/Version1010Date20200630192842.php
  apps/user_ldap/lib/Migration/Version1120Date20210917155206.php
  apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
Labels: 2. developing

#29859 Improve ldap:test-config occ command
  apps/user_ldap/lib/Command/TestConfig.php
Labels: 3. to review

#30351 [stable23] Remove iconv from dependencies and tests
  .github/workflows/ftp.yml
  .github/workflows/lint.yml
  .github/workflows/oci.yml
  .github/workflows/s3-external.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
  lib/private/App/PlatformRepository.php
  lib/private/legacy/OC_Util.php
Labels: 3. to review, backport-request, pending documentation

#30352 Remove iconv from further tests
  .github/workflows/ftp.yml
  .github/workflows/lint.yml
  .github/workflows/static-code-analysis.yml
Labels: 3. to review

#30515 [stable22] Remove iconv from dependencies and tests
  .github/workflows/lint.yml
  .github/workflows/oci.yml
  .github/workflows/s3-external.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
  lib/private/App/PlatformRepository.php
  lib/private/legacy/OC_Util.php
Labels: 3. to review, backport-request, pending documentation

#30284 l10n: Separate words and add dots
  apps/comments/lib/Notification/Notifier.php
  apps/comments/tests/Unit/Notification/NotifierTest.php
  lib/base.php
  lib/private/legacy/OC_Util.php
Labels: feature: language l10n and translations

#30522 [stable23] Fix passing on the parameter
  apps/files_sharing/lib/External/Scanner.php
Labels: bug, 3. to review, feature: federation

#30523 [stable22] Fix passing on the parameter
  apps/files_sharing/lib/External/Scanner.php
Labels: bug, 3. to review, feature: federation

#30524 [stable21] Fix passing on the parameter
  apps/files_sharing/lib/External/Scanner.php
Labels: bug, 3. to review, feature: federation

#30511 update CRL after revocation of sharerenamer.crt
  resources/codesigning/root.crl
Labels: 3. to review

#30491 Fix email verification
  lib/private/Accounts/AccountManager.php
  tests/lib/Accounts/AccountManagerTest.php
Labels: bug, 3. to review, backport-request, feature: users and groups, feature: emails

#30378 Accept multipe args on concat
  lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/PgSqlFunctionBuilder.php
  lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
  lib/public/DB/QueryBuilder/IFunctionBuilder.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
Labels: 3. to review, php

#30518 23.0.1 RC 1
  version.php
Labels: 3. to review

#30519 22.2.4 RC1
  version.php
Labels: 3. to review

#30520 21.0.8 RC1
  version.php
Labels: 3. to review

#30468 Handle LocalServerException when scanning external shares
  apps/files_sharing/lib/External/Scanner.php
Labels: 2. developing, backport-request

#30567 Use npm ci when running JS tests
  apps/files/src/files-app-settings.js
  apps/files/src/main-personal-settings.js
  apps/systemtags/js/admin.js
  autotest-js.sh
  build/package-lock.json
  build/package.json
  core/js/tests/specs/contactsmenuSpec.js
  core/js/tests/specs/jquery.contactsmenuSpec.js
  dist/core-maintenance.js.LICENSE.txt
  dist/dashboard-dashboard-main.js
  dist/dashboard-dashboard-main.js.LICENSE.txt
  dist/dashboard-dashboard-main.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files-personal-settings.js
  dist/files-personal-settings.js.map
  dist/files_sharing-collaboration.js.LICENSE.txt
  dist/files_sharing-files_sharing.js.LICENSE.txt
  dist/settings-apps-settings-apps.js
  dist/settings-apps-settings-apps.js.map
  dist/settings-users-settings-users.js
  dist/settings-users-settings-users.js.map
  dist/user-status-modal-299.js.LICENSE.txt
  dist/user-status-modal-user-status-modal.js
  dist/user-status-modal-user-status-modal.js.map
Labels: bug, 4. to release, backport-request

#30499 Remove inefficient fed share scanner
  apps/files_sharing/lib/External/Scanner.php
  apps/files_sharing/tests/External/ScannerTest.php
Labels: bug, 3. to review

#30571 fix: only use jquery once it is available
  core/js/public/publicpage.js
Labels: 3. to review, backport-request

#30580 [stable23] Use npm ci when running JS tests
  apps/files/js/dist/main.js
  apps/files/js/dist/main.js.map
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/files-app-settings.js
  apps/files/src/main-personal-settings.js
  apps/systemtags/js/admin.js
  autotest-js.sh
  build/package-lock.json
  build/package.json
  core/js/tests/specs/contactsmenuSpec.js
  core/js/tests/specs/jquery.contactsmenuSpec.js
Labels: 3. to review

#30581 [stable22] Use npm ci when running JS tests
  apps/files/js/dist/main.js
  apps/files/js/dist/main.js.map
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/files-app-settings.js
  apps/files/src/main-personal-settings.js
  apps/systemtags/js/admin.js
  autotest-js.sh
  build/package-lock.json
  build/package.json
  core/js/tests/specs/contactsmenuSpec.js
  core/js/tests/specs/jquery.contactsmenuSpec.js
Labels: 3. to review

#30582 Streamline reseting of private static properties
  lib/public/Util.php
  tests/lib/UtilTest.php
Labels: 2. developing

#30569 Default to language from request in L10N\Factory->getUserLanguage()
  lib/private/L10N/Factory.php
Labels: 3. to review, feature: language l10n and translations

#30291 Prevent loading images that would require too much memory.
  config/config.sample.php
  lib/private/legacy/OC_Image.php
  tests/data/testimage-badheader.jpg
  tests/lib/ImageTest.php
Labels: bug, 4. to release, feature: previews and thumbnails

#30533 Avoid zero division in setup checks
  apps/settings/lib/Controller/CheckSetupController.php
Labels: bug, 3. to review, high, backport-request, regression

#30583 [stable21] Use npm ci when running JS tests
  apps/files/js/dist/main.js
  apps/files/js/dist/main.js.map
  apps/files/js/dist/personal-settings.js
  apps/files/js/dist/personal-settings.js.map
  apps/files/src/files-app-settings.js
  apps/files/src/main-personal-settings.js
  apps/systemtags/js/admin.js
  autotest-js.sh
  build/package-lock.json
  build/package.json
  core/js/tests/specs/contactsmenuSpec.js
  core/js/tests/specs/jquery.contactsmenuSpec.js
Labels: 4. to release

#30588 Fix undefined/unset scope in account properties
  lib/private/Accounts/AccountProperty.php
  tests/lib/Accounts/AccountPropertyTest.php
Labels: bug, 4. to release, feature: users and groups

#30609 Fix RequestURL check for cli commands
  apps/workflowengine/lib/Check/RequestURL.php
Labels: 3. to review

#30485 Set the file's mtime from the headers in bulk upload
  apps/dav/composer/composer/ClassLoader.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/composer/composer/installed.php
  apps/dav/lib/BulkUpload/BulkUploadPlugin.php
  apps/dav/lib/Connector/Sabre/MtimeSanitizer.php
  apps/dav/lib/Connector/Sabre/Node.php
  apps/dav/tests/benchmarks/bulk_upload.sh
  build/integration/features/bootstrap/WebDav.php
  build/integration/features/webdav-related.feature
Labels: bug, 4. to release, feature: filesystem, feature: dav, backport-request

#30625 Remove shortFooter/longFooter to avoid unnecessary navigation loading
  lib/private/Template/JSConfigHelper.php
Labels: enhancement, 3. to review, feature: theming, performance 🚀

#30593 Trigger "changeDirectory" event on URL change
  apps/files/js/app.js
  apps/files/js/filelist.js
Labels: bug, 3. to review, backport-request

#30600 Fix idn emails not working in shares
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
Labels: 3. to review

#30620 Properly abort uploads
  apps/files/js/file-upload.js
Labels: bug, 4. to release, backport-request, feature: files

#30531 Optimize FileSystemTags workflow for groupfolder
  apps/workflowengine/lib/Check/FileSystemTags.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
Labels: 3. to review, performance 🚀

#30597 Fix file picker not respecting hidden files settings
  core/src/OC/dialogs.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review, backport-request

#30656 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#30530 Fix wrong unified search link to folder
  apps/files/lib/Search/FilesSearchProvider.php
Labels: bug, 3. to review, backport-request

#30568 Fix primary key change in user_ldap migration
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Migration/GroupMappingMigration.php
  apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
  apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
  apps/user_ldap/lib/Migration/Version1130Date20220110154718.php
  apps/user_ldap/lib/Migration/Version1130Date20220110154719.php
Labels: 4. to release, backport-request

#30614 Fix non-ascii characters present in the header
  lib/private/User/Session.php
Labels: 3. to review

#30363 improve accessibility settings on mobile
  apps/accessibility/css/style.scss
Labels: enhancement, 4. to release, feature: settings, feature: accessibility

#30659 [stable23] Implement multibucket shift for ObjectStore
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/ObjectStore/Mapper.php
  tests/lib/Files/Mount/ObjectHomeMountProviderTest.php
  tests/lib/Files/ObjectStore/MapperTest.php
Labels: 3. to review

#30658 [stable22] Implement multibucket shift for ObjectStore
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/ObjectStore/Mapper.php
  tests/lib/Files/Mount/ObjectHomeMountProviderTest.php
  tests/lib/Files/ObjectStore/MapperTest.php
Labels: 3. to review

#30655 Improve layout for the public download page
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/templates/public.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  core/css/public.scss
Labels: enhancement, design, 4. to release

#30275 Add version of disabled apps when available
  core/Command/App/ListApps.php
Labels: bug, 3. to review, backport-request

#29750 Don't use the deprecated method
  core/src/init.js
  dist/core-main.js
  dist/core-main.js.map
Labels: 4. to release, technical debt

#30645 New Files internal link GET param to avoid opening the file
  apps/files/lib/Controller/ViewController.php
Labels: enhancement, 3. to review, feature: sharing, backport-request, feature: files

#30661 Allow .php-cs-fixer.dist.php
  build/files-checker.php
Labels: 3. to review

#30653 Increase email main buttons width for non-english languages
  lib/private/Mail/EMailTemplate.php
Labels: 3. to review

#29866 Check if size value is set
  lib/private/Files/View.php
Labels: 3. to review, backport-request

#30680 21.0.8 RC2
  version.php
Labels: 3. to review

#30679 22.2.4 RC2
  version.php
Labels: 3. to review

#30678 23.0.1 RC2
  version.php
Labels: 3. to review

#30714 Set package-lock.json as binaries
  .gitattributes
  .gitignore
Labels: 3. to review, technical debt, dependencies

#30719 Fix loading of the text app in public shared links
  core/css/public.scss
Labels: backport-request

#30632 Unpin webpack version
  package-lock.json
  package.json
Labels: 3. to review, javascript, dependencies

#30470 Hash job argument
  core/Migrations/Version24000Date20211230140012.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/BackgroundJob/JobList.php
  version.php
Labels: enhancement, 4. to release, backport-request, performance 🚀

#30733 Load core before the update script
  lib/base.php
Labels: bug, 3. to review, high, feature: install and update, regression

#30735 Fix tests with email templates
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email.html
Labels: 3. to review

#30129 Add MariaDB 10.6 support (drop row_format=compressed)
  .drone.yml
  config/config.sample.php
  lib/private/DB/ConnectionFactory.php
  lib/private/Repair/Collation.php
Labels: bug, 3. to review, backport-request, feature: install and update, papercut

#30738 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review, backport-request

#30731 Log bruteforce throttle and blocking
  lib/private/Security/Bruteforce/Throttler.php
Labels: bug, 3. to review

#30745 Use less deprecated methods in base.php
  core/js/update.js
  lib/base.php
Labels: bug, 4. to release, feature: install and update, javascript

#30761 Change l10n directory
  apps/settings/src/components/AuthTokenSection.vue
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
Labels: 4. to release, feature: settings

#30660 [stable21] Implement multibucket shift for ObjectStore
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/ObjectStore/Mapper.php
  tests/lib/Files/Mount/ObjectHomeMountProviderTest.php
  tests/lib/Files/ObjectStore/MapperTest.php
Labels: 3. to review

#30657 [stable20] Implement multibucket shift for ObjectStore
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/ObjectStore/Mapper.php
  tests/lib/Files/Mount/ObjectHomeMountProviderTest.php
  tests/lib/Files/ObjectStore/MapperTest.php
Labels: 3. to review

#29799 [stable22] Check for disk_free_space
  lib/private/Files/Storage/Local.php
Labels: bug, 3. to review

#29798 [stable23] Check for disk_free_space
  lib/private/Files/Storage/Local.php
Labels: bug

#30471 Explicitly cast char in the query builder
  lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/MySqlExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/PgSqlExpressionBuilder.php
  lib/public/DB/QueryBuilder/IExpressionBuilder.php
Labels: bug, 3. to review

#29846 l10n: Spelling unification
  apps/settings/src/components/AuthToken.vue
  core/src/views/Profile.vue
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
Labels: 4. to release, feature: language l10n and translations

#30769 Always call flush() as getAllKeys() is broken
  lib/private/Memcache/Memcached.php
Labels: bug, 3. to review, backport-request, feature: caching

#30770 Allow changing the top-left logo link target in config.php
  config/config.sample.php
  core/templates/layout.user.php
  lib/private/TemplateLayout.php
Labels: enhancement, 3. to review, feature: theming

#30771 Convert properties value to string before passing them to database
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: bug, 3. to review, feature: dav

#29349 add KerberosApacheAuth support to files_external
  .github/workflows/smb-kerberos.yml
  apps/files_external/3rdparty/.gitignore
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/ClassLoader.php
  apps/files_external/3rdparty/composer/InstalledVersions.php
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/composer/installed.php
  apps/files_external/3rdparty/icewind/smb/README.md
  apps/files_external/3rdparty/icewind/smb/src/IShare.php
  apps/files_external/3rdparty/icewind/smb/src/KerberosApacheAuth.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php
  apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php
  apps/files_external/3rdparty/icewind/smb/src/System.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Connection.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/NotifyHandler.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/RawConnection.php
  apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Lib/Auth/SMB/KerberosApacheAuth.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/tests/setup-krb.sh
Labels: enhancement, 4. to release, feature: external storage, backport-request

#30767 21.0.8 RC3
  version.php
Labels: 3. to review

#30765 23.0.1 RC3
  version.php
Labels: 3. to review

#30123 l10n: Add dot at the end of an sentence
  apps/updatenotification/src/components/UpdateNotification.vue
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
Labels: enhancement, 4. to release, feature: language l10n and translations

#30787 Fix backport/30470/stable21
  apps/accessibility/composer/composer/ClassLoader.php
  apps/accessibility/composer/composer/InstalledVersions.php
  apps/admin_audit/composer/composer/ClassLoader.php
  apps/admin_audit/composer/composer/InstalledVersions.php
  apps/cloud_federation_api/composer/composer/ClassLoader.php
  apps/cloud_federation_api/composer/composer/InstalledVersions.php
  apps/comments/composer/composer/ClassLoader.php
  apps/comments/composer/composer/InstalledVersions.php
  apps/contactsinteraction/composer/composer/ClassLoader.php
  apps/contactsinteraction/composer/composer/InstalledVersions.php
  apps/dav/composer/composer/ClassLoader.php
  apps/dav/composer/composer/InstalledVersions.php
  apps/encryption/composer/composer/ClassLoader.php
  apps/encryption/composer/composer/InstalledVersions.php
  apps/federatedfilesharing/composer/composer/ClassLoader.php
  apps/federatedfilesharing/composer/composer/InstalledVersions.php
  apps/federation/composer/composer/ClassLoader.php
  apps/federation/composer/composer/InstalledVersions.php
  apps/files/composer/composer/ClassLoader.php
  apps/files/composer/composer/InstalledVersions.php
  apps/files_sharing/composer/composer/ClassLoader.php
  apps/files_sharing/composer/composer/InstalledVersions.php
  apps/files_trashbin/composer/composer/ClassLoader.php
  apps/files_trashbin/composer/composer/InstalledVersions.php
  apps/files_versions/composer/composer/ClassLoader.php
  apps/files_versions/composer/composer/InstalledVersions.php
  apps/lookup_server_connector/composer/composer/ClassLoader.php
  apps/lookup_server_connector/composer/composer/InstalledVersions.php
  apps/oauth2/composer/composer/ClassLoader.php
  apps/oauth2/composer/composer/InstalledVersions.php
  apps/provisioning_api/composer/composer/ClassLoader.php
  apps/provisioning_api/composer/composer/InstalledVersions.php
  apps/settings/composer/composer/ClassLoader.php
  apps/settings/composer/composer/InstalledVersions.php
  apps/sharebymail/composer/composer/ClassLoader.php
  apps/sharebymail/composer/composer/InstalledVersions.php
  apps/systemtags/composer/composer/ClassLoader.php
  apps/systemtags/composer/composer/InstalledVersions.php
  apps/testing/composer/composer/ClassLoader.php
  apps/testing/composer/composer/InstalledVersions.php
  apps/twofactor_backupcodes/composer/composer/ClassLoader.php
  apps/twofactor_backupcodes/composer/composer/InstalledVersions.php
  apps/updatenotification/composer/composer/ClassLoader.php
  apps/updatenotification/composer/composer/InstalledVersions.php
  apps/user_ldap/composer/composer/ClassLoader.php
  apps/user_ldap/composer/composer/InstalledVersions.php
  apps/user_status/composer/composer/ClassLoader.php
  apps/user_status/composer/composer/InstalledVersions.php
  apps/workflowengine/composer/composer/ClassLoader.php
  apps/workflowengine/composer/composer/InstalledVersions.php
  core/Migrations/Version24000Date20211230140012.php
  lib/composer/composer/ClassLoader.php
  version.php
Labels: bug, 3. to review

#30785 Revert "[stable21] Hash job argument"
  apps/accessibility/composer/composer/ClassLoader.php
  apps/accessibility/composer/composer/InstalledVersions.php
  apps/admin_audit/composer/composer/ClassLoader.php
  apps/admin_audit/composer/composer/InstalledVersions.php
  apps/cloud_federation_api/composer/composer/ClassLoader.php
  apps/cloud_federation_api/composer/composer/InstalledVersions.php
  apps/comments/composer/composer/ClassLoader.php
  apps/comments/composer/composer/InstalledVersions.php
  apps/contactsinteraction/composer/composer/ClassLoader.php
  apps/contactsinteraction/composer/composer/InstalledVersions.php
  apps/dav/composer/composer/ClassLoader.php
  apps/dav/composer/composer/InstalledVersions.php
  apps/encryption/composer/composer/ClassLoader.php
  apps/encryption/composer/composer/InstalledVersions.php
  apps/federatedfilesharing/composer/composer/ClassLoader.php
  apps/federatedfilesharing/composer/composer/InstalledVersions.php
  apps/federation/composer/composer/ClassLoader.php
  apps/federation/composer/composer/InstalledVersions.php
  apps/files/composer/composer/ClassLoader.php
  apps/files/composer/composer/InstalledVersions.php
  apps/files_sharing/composer/composer/ClassLoader.php
  apps/files_sharing/composer/composer/InstalledVersions.php
  apps/files_trashbin/composer/composer/ClassLoader.php
  apps/files_trashbin/composer/composer/InstalledVersions.php
  apps/files_versions/composer/composer/ClassLoader.php
  apps/files_versions/composer/composer/InstalledVersions.php
  apps/lookup_server_connector/composer/composer/ClassLoader.php
  apps/lookup_server_connector/composer/composer/InstalledVersions.php
  apps/oauth2/composer/composer/ClassLoader.php
  apps/oauth2/composer/composer/InstalledVersions.php
  apps/provisioning_api/composer/composer/ClassLoader.php
  apps/provisioning_api/composer/composer/InstalledVersions.php
  apps/settings/composer/composer/ClassLoader.php
  apps/settings/composer/composer/InstalledVersions.php
  apps/sharebymail/composer/composer/ClassLoader.php
  apps/sharebymail/composer/composer/InstalledVersions.php
  apps/systemtags/composer/composer/ClassLoader.php
  apps/systemtags/composer/composer/InstalledVersions.php
  apps/testing/composer/composer/ClassLoader.php
  apps/testing/composer/composer/InstalledVersions.php
  apps/twofactor_backupcodes/composer/composer/ClassLoader.php
  apps/twofactor_backupcodes/composer/composer/InstalledVersions.php
  apps/updatenotification/composer/composer/ClassLoader.php
  apps/updatenotification/composer/composer/InstalledVersions.php
  apps/user_ldap/composer/composer/ClassLoader.php
  apps/user_ldap/composer/composer/InstalledVersions.php
  apps/user_status/composer/composer/ClassLoader.php
  apps/user_status/composer/composer/InstalledVersions.php
  apps/workflowengine/composer/composer/ClassLoader.php
  apps/workflowengine/composer/composer/InstalledVersions.php
  core/Migrations/Version24000Date20211230140012.php
  lib/composer/composer/ClassLoader.php
  lib/private/BackgroundJob/JobList.php
Labels: bug, 3. to review, regression

#30789 l10n: Change to a capital letter
  apps/files_external/lib/Lib/Auth/SMB/KerberosApacheAuth.php
Labels: feature: language l10n and translations

#30788 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#30766 22.2.4 RC3
  version.php
Labels: 3. to review

#30379 Add comments reactions
  apps/dav/tests/unit/Comments/CommentsNodeTest.php
  build/psalm-baseline.xml
  core/Migrations/Version24000Date20211222112246.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Comments/Comment.php
  lib/private/Comments/Manager.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/public/Comments/IComment.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  tests/lib/Comments/ManagerTest.php
  tests/lib/DB/QueryBuilder/QueryBuilderTest.php
Labels: enhancement, 4. to release, feature: comments, php

#30795 Fix accessing undefined offsets
  apps/files_external/lib/Lib/Backend/SMB.php
Labels: 4. to release, backport-request

#30740 [stable23] Increase email main buttons width for non-english languages
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email.html
Labels: 3. to review

#30739 Add IConfig::getAllUserValues to get user settings for all applications
  core/Command/User/Setting.php
  core/register_command.php
  lib/private/AllConfig.php
  lib/public/IConfig.php
Labels: enhancement, 2. developing

#30763 Allow writing audit log to syslog and systemdlog
  apps/admin_audit/lib/AppInfo/Application.php
  config/config.sample.php
  lib/private/Log/Errorlog.php
  lib/private/Log/LogFactory.php
  lib/private/Log/Syslog.php
  lib/private/Log/Systemdlog.php
  lib/public/Log/ILogFactory.php
Labels: enhancement, 3. to review, feature: admin audit, feature: logging, pending documentation, performance 🚀

#30778 Supercharge Issues template
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: 4. to release

#30831 Fix OC\Files\Storage\DAV::hasUpdated when cache is not set
  lib/private/Files/Storage/DAV.php
Labels: bug, 3. to review

#30846 Fix php:cs
  apps/files_external/lib/Lib/Backend/SMB.php
Labels: backport-request

#30822 Remove createPluralFunction which is replaced by Symfony\Translations…
  lib/private/L10N/Factory.php
  lib/public/L10N/IFactory.php
Labels: bug, 3. to review

#30859 Issuetemplate - Small wording and formatting fixes
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 3. to review

#30832 Makes untrusted domain error a warning.
  lib/base.php
Labels: 4. to release

#30844 Prevent merging on EOL branches
  .github/workflows/block-merge-eol.yml
Labels: 3. to review, backport-request

#30741 [stable22] Increase email main buttons width for non-english languages
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email.html
Labels: 3. to review

#30858 Return 404 when AJAX tries to list dir content but file given
  apps/files/ajax/list.php
  lib/private/Files/Filesystem.php
Labels: bug, 3. to review, backport-request, feature: files

#30876 Add deprecation notice to script & addScript func
  lib/private/legacy/OC_Util.php
  lib/private/legacy/template/functions.php
Labels: technical debt

#30886 Fixes occ user:info when the user never logged in
  core/Command/User/Info.php
Labels: bug, 3. to review, backport-request

#30855 Fix all psalm issues in theming app
  apps/testing/lib/Controller/LockingController.php
  apps/theming/lib/Command/UpdateConfig.php
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/ImageManager.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/lib/Util.php
  build/psalm-baseline.xml
  composer.json
  lib/private/Memcache/Memcached.php
  lib/private/legacy/OC_Util.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/Util.php
Labels: 4. to release, technical debt

#30839 22.2.4 Final
  version.php
Labels: 4. to release

#30838 21.0.8 Final
  version.php
Labels: 4. to release

#30893 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#30794 Allow to get comments with a given set of verbs
  lib/private/Comments/Manager.php
  lib/public/Comments/ICommentsManager.php
  tests/lib/Comments/FakeManager.php
Labels: 3. to review, feature: comments, technical debt

#25418 Update variables.scss - Fallback font before Noto Color Emoji
  core/css/variables.scss
Labels: bug, 4. to release, backport-request

#30932 Make fewer fields mandatory in the bug reporting
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 3. to review

#30934 l10n: Change l10n directory
  apps/dav/src/views/Availability.vue
Labels: feature: language l10n and translations

#30926 Allow sub-admins to access delegated settings.
  lib/private/Settings/Manager.php
Labels: enhancement, 3. to review
