Repository nextcloud/server, pull requests merged in 2022-05, with the labels that each got.

#32196 Fix strict comparison
  core/Command/Db/Migrations/GenerateCommand.php
Labels: 3. to review, technical debt

#31752 Move away from deprecated ILogger
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Cache/File.php
  lib/private/Dashboard/Manager.php
  lib/private/DateTimeZone.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Mount/MountPoint.php
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/DAV.php
  lib/private/Files/Storage/Local.php
  lib/private/Files/View.php
  lib/private/Installer.php
  lib/private/NaturalSort.php
  lib/private/Preview/Office.php
  lib/private/Preview/SVG.php
  lib/private/Share/SearchResultSorter.php
  lib/private/Share/Share.php
  lib/private/Support/CrashReport/Registry.php
  tests/lib/Share/SearchResultSorterTest.php
Labels: 4. to release, technical debt

#32239 Revert "[stable24] Make the order of reactions reliable"
  lib/private/Comments/Manager.php
Labels: 4. to release

#31775 Migrate dav application from ILogger to LoggerInterface
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/appinfo/v1/webdav.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/BackgroundJob/BuildReminderIndexBackgroundJob.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/ICSExportPlugin/ICSExportPlugin.php
  apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/AbstractProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/CalDAV/ResourceBooking/ResourcePrincipalBackend.php
  apps/dav/lib/CalDAV/ResourceBooking/RoomPrincipalBackend.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Comments/CommentNode.php
  apps/dav/lib/Comments/EntityCollection.php
  apps/dav/lib/Comments/EntityTypeCollection.php
  apps/dav/lib/Comments/RootCollection.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/HookManager.php
  apps/dav/lib/Migration/CalDAVRemoveEmptyValue.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/Server.php
  apps/dav/tests/integration/UserMigration/CalendarMigratorTest.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CalDAV/PublicCalendarRootTest.php
  apps/dav/tests/unit/CalDAV/Publishing/PublishingTest.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/AbstractNotificationProviderTest.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/PushProviderTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/AbstractPrincipalBackendTest.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/RefreshWebcalServiceTest.php
  apps/dav/tests/unit/CardDAV/SyncServiceTest.php
  apps/dav/tests/unit/Comments/CommentsNodeTest.php
  apps/dav/tests/unit/Comments/EntityCollectionTest.php
  apps/dav/tests/unit/Comments/EntityTypeCollectionTest.php
  apps/dav/tests/unit/Comments/RootCollectionTest.php
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/RequestTest/RequestTestCase.php
  apps/dav/tests/unit/Migration/CalDAVRemoveEmptyValueTest.php
  remote.php
Labels: 3. to review, technical debt

#32213 Improve theming layout
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/src/UserThemes.vue
  apps/theming/src/components/ItemPreview.vue
  dist/theming-theming-settings.js
  dist/theming-theming-settings.js.map
Labels: enhancement, 3. to review, feature: theming

#32220 Include more emoji chars to test and fixes after include it
  lib/private/EmojiHelper.php
  tests/lib/EmojiHelperTest.php
Labels: 3. to review

#32153 [stable24] fix showing of all apps are up-to-date in apps management
  apps/settings/src/components/AppList.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, feature: apps management

#31963 Use share setting in DAV search
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
Labels: enhancement, 2. developing, feature: dav, feature: search

#32262 Remove leading "minus"
  apps/dav/lib/Server.php
Labels: bug, 3. to review, feature: dav

#32236 [stable24] Use sabre function directly rather than duplicating it
  build/psalm-baseline.xml
  lib/private/AppFramework/Http/Request.php
Labels: 4. to release

#32152 Allow compatibility wrapper on local external storage
  lib/private/Files/SetupManager.php
Labels: bug, 3. to review, backport-request

#32249 Expose shareWithDisplayNameUnique also on autocomplete endpoint
  core/Controller/AutoCompleteController.php
  tests/Core/Controller/AutoCompleteControllerTest.php
Labels: 4. to release, feature: sharing

#32259 Adjust acceptance tests to changes in notifications markup
  tests/acceptance/features/bootstrap/NotificationsContext.php
Labels: bug, 3. to review

#32279 Add hit information to profiler
  lib/private/Memcache/ProfilerWrapperCache.php
Labels: 3. to review

#32241 Revert "Revert "[stable24] Make the order of reactions reliable""
  lib/private/Comments/Manager.php
Labels: 3. to review

#32274 Fix tooltips overflow
  core/css/tooltip.scss
Labels: design, 3. to review, feature: scss

#32315 Fix preview generator trying to recreate an existing folder
  lib/private/Preview/Generator.php
Labels: 4. to release, backport-request, feature: previews and thumbnails

#32318 Increase retry delay on 'Wait for S3' CI job
  .github/workflows/s3-primary.yml
Labels: 3. to review

#31664 keyboard focus on login input fields
  core/css/guest.css
Labels: 2. developing

#31900 Add a public replacement for OC::$server->get
  apps/files/lib/App.php
  apps/files/lib/Collaboration/Resources/Listener.php
  apps/files/list.php
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/IAppContainer.php
  lib/public/IServerContainer.php
  lib/public/Server.php
Labels: 3. to review, pending documentation

#32149 fix for transferring ownership of groupfolders
  apps/files/lib/Controller/TransferOwnershipController.php
Labels: bug, 3. to review, backport-request

#32336 Add talk-poll to the ROS definitions
  lib/public/RichObjectStrings/Definitions.php
Labels: enhancement, 3. to review

#32278 Remove call to already default php.ini values
  lib/base.php
Labels: 3. to review, backport-request

#32344 Always free the DB result in QBMapper::findEntities
  lib/public/AppFramework/Db/QBMapper.php
Labels: bug, 3. to review

#32328 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32358 l10n: Delete space
  apps/user_ldap/templates/settings.php
Labels: feature: language l10n and translations

#32362 Fix buttons in workflow
  apps/workflowengine/src/components/Operation.vue
  apps/workflowengine/src/components/Rule.vue
  apps/workflowengine/src/styles/operation.scss
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: 4. to release

#32077 Cleanup lock related code
  apps/testing/lib/Locking/FakeDBLockingProvider.php
  lib/private/Lock/AbstractLockingProvider.php
  lib/private/Lock/DBLockingProvider.php
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/Lock/NoopLockingProvider.php
  lib/private/Server.php
  lib/public/Lock/ILockingProvider.php
  tests/lib/Lock/DBLockingProviderTest.php
  tests/lib/Lock/NonCachingDBLockingProviderTest.php
Labels: 3. to review

#32335 don't unjail the path when getting the storage info
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, backport-request

#32359 Use toast.scss from @nextcloud/dialogs
  core/css/server.scss
  core/css/toast.scss
Labels: technical debt, dependencies

#32250 Add stricter psalm type for CappedMemoryCache
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  apps/files_external/lib/Lib/Storage/SMB.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/SharedMount.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Helper.php
  apps/user_ldap/lib/User/Manager.php
  apps/workflowengine/lib/Manager.php
  build/psalm-baseline.xml
  lib/private/Cache/CappedMemoryCache.php
  lib/private/Diagnostics/QueryLogger.php
  lib/private/Encryption/File.php
  lib/private/Encryption/Util.php
  lib/private/Files/AppData/AppData.php
  lib/private/Files/Config/UserMountCache.php
  tests/lib/Files/Config/UserMountCacheTest.php
Labels: 3. to review, technical debt

#30863 Minor optimizations for saving user personal information
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/HookManager.php
  lib/private/Accounts/AccountManager.php
  tests/lib/Accounts/AccountManagerTest.php
Labels: 2. developing, performance 🚀

#32369 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32366 Use property name for addType
  apps/oauth2/lib/Db/Client.php
Labels: bug, 4. to release

#32376 Fix psalm warning for zip response due wrong type
  lib/public/AppFramework/Http/ZipResponse.php
Labels: 3. to review, technical debt

#32384 Improve psalm annotation to make it stricter
  build/psalm-baseline.xml
  lib/public/Server.php
Labels: 4. to release, technical debt

#31662 Modernize contacts menu backend
  build/psalm-baseline.xml
  core/Controller/ContactsMenuController.php
  lib/private/Contacts/ContactsMenu/ActionProviderStore.php
  lib/private/Contacts/ContactsMenu/Actions/LinkAction.php
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/Contacts/ContactsMenu/Entry.php
  lib/private/Contacts/ContactsMenu/Manager.php
  lib/private/Contacts/ContactsMenu/Providers/EMailProvider.php
  lib/private/Contacts/ContactsMenu/Providers/ProfileProvider.php
  lib/public/Contacts/ContactsMenu/IAction.php
  lib/public/Contacts/ContactsMenu/IContactsStore.php
  lib/public/Contacts/ContactsMenu/ILinkAction.php
  tests/Core/Controller/ContactsMenuControllerTest.php
  tests/lib/Contacts/ContactsMenu/ActionFactoryTest.php
  tests/lib/Contacts/ContactsMenu/ActionProviderStoreTest.php
  tests/lib/Contacts/ContactsMenu/Actions/LinkActionTest.php
  tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
  tests/lib/Contacts/ContactsMenu/EntryTest.php
  tests/lib/Contacts/ContactsMenu/ManagerTest.php
  tests/lib/Contacts/ContactsMenu/Providers/EMailproviderTest.php
Labels: 4. to release, technical debt, feature: contacts menu, php

#32360 [stable24] Add share search tweaks
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/admin.js
  apps/settings/templates/settings/admin/sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  build/integration/features/bootstrap/CollaborationContext.php
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
Labels: 4. to release, feature: sharing, feature: search

#32398 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32388 🔥 remove deprecated element
  apps/files/templates/list.php
Labels: 4. to release, technical debt

#32375 Show user account on grant loginflow step
  core/Controller/ClientFlowLoginController.php
  core/Controller/ClientFlowLoginV2Controller.php
  core/templates/loginflow/grant.php
  core/templates/loginflowv2/grant.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
  tests/Core/Controller/ClientFlowLoginV2ControllerTest.php
Labels: bug, 3. to review, backport-request, feature: authentication

#32305 Fix user agent trimming on installation
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
Labels: bug, 3. to review, backport-request, feature: install and update, regression

#32256 [stable24] Include more emoji chars to test and fixes after include it
  apps/user_status/tests/Unit/Service/EmojiServiceTest.php
  lib/private/Comments/EmojiHelper.php
Labels: bug, 3. to review, feature: comments, feature: status

#32323 [stable23] Fix preview generator trying to recreate an existing folder
  lib/private/Preview/Generator.php
Labels: bug, 3. to review, feature: previews and thumbnails

#32016 Use stored user for PasswordUpdatedEvent
  apps/files_external/lib/Listener/StorePasswordListener.php
Labels: bug, 3. to review, feature: external storage

#32324 [stable22] Fix preview generator trying to recreate an existing folder
  lib/private/Preview/Generator.php
Labels: bug, 3. to review, feature: previews and thumbnails

#32430 [stable22] Show user account on grant loginflow step
  core/Controller/ClientFlowLoginController.php
  core/Controller/ClientFlowLoginV2Controller.php
  core/templates/loginflow/grant.php
  core/templates/loginflowv2/grant.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
  tests/Core/Controller/ClientFlowLoginV2ControllerTest.php
Labels: bug, 4. to release, feature: authentication

#32357 remove storage wrappers when deleting the user storage
  lib/private/Authentication/Listeners/UserDeletedFilesCleanupListener.php
Labels: 3. to review

#32306 Migrate phpunit configuration to new format
  tests/phpunit-autotest.xml
Labels: 3. to review

#32418 24.0.1 RC 1
  version.php
Labels: 3. to review

#32423 23.0.5 RC1
  version.php
Labels: 3. to review

#32425 22.2.8 RC1
  version.php
Labels: 3. to review

#31623 Allow to tweak default scopes for accounts
  config/config.sample.php
  lib/private/Accounts/AccountManager.php
  lib/public/Accounts/IAccountManager.php
  tests/lib/Accounts/AccountManagerTest.php
Labels: enhancement, 3. to review, backport-request, feature: users and groups, php

#32405 [Psalm] Fix spelling for return type
  lib/public/FullTextSearch/Model/ISearchRequest.php
Labels: 3. to review, technical debt

#32216 Respect user settings in php.ini if they are big enough
  lib/base.php
Labels: bug, 3. to review

#32439 adjust wording for database checks
  apps/settings/lib/SetupChecks/SupportedDatabase.php
Labels: bug, enhancement, 3. to review

#32404 [Psalm] Drop redundanten return comment
  lib/public/IAddressBook.php
Labels: 3. to review, technical debt

#31943 Cleanup dav
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/appinfo/v1/webdav.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/BuildReminderIndexBackgroundJob.php
  apps/dav/lib/BackgroundJob/EventReminderJob.php
  apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php
  apps/dav/lib/BackgroundJob/UploadCleanup.php
  apps/dav/lib/CalDAV/BirthdayService.php
  apps/dav/lib/CalDAV/CachedSubscription.php
  apps/dav/lib/CalDAV/CachedSubscriptionObject.php
  apps/dav/lib/CalDAV/ICSExportPlugin/ICSExportPlugin.php
  apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php
  apps/dav/lib/CalDAV/Publishing/PublishPlugin.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
  apps/dav/lib/CalDAV/Reminder/Notifier.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/Connector/PublicAuth.php
  apps/dav/lib/Connector/Sabre/AppEnabledPlugin.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/BearerAuth.php
  apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php
  apps/dav/lib/Connector/Sabre/CachingTree.php
  apps/dav/lib/Connector/Sabre/ChecksumList.php
  apps/dav/lib/Connector/Sabre/ChecksumUpdatePlugin.php
  apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
  apps/dav/lib/Connector/Sabre/CopyEtagHeaderPlugin.php
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/DummyGetResponsePlugin.php
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/FileSearchBackendTest.php
  build/psalm-baseline.xml
Labels: 2. developing

#26813 Files: Extend search to also cover tags
  apps/systemtags/composer/composer/autoload_classmap.php
  apps/systemtags/composer/composer/autoload_static.php
  apps/systemtags/lib/AppInfo/Application.php
  apps/systemtags/lib/Search/TagSearchProvider.php
  apps/systemtags/src/app.js
  apps/systemtags/src/systemtagsfilelist.js
  dist/systemtags-systemtags.js
  dist/systemtags-systemtags.js.map
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Cache/SearchBuilder.php
  tests/lib/Files/Cache/SearchBuilderTest.php
Labels: enhancement, 3. to review, feature: files, feature: tags, feature: search

#32428 Add Email validation
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php
Labels: enhancement, 4. to release, backport-request

#32467 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32493 22.2.8
  version.php
Labels: 3. to review

#32442 Bye Bye chunkperf.php :wave:
  apps/dav/bin/chunkperf.php
Labels: 4. to release, technical debt

#32494 23.0.5
  version.php
Labels: 3. to review

#32495 24.0.1
  version.php
Labels: 3. to review

#32496 Fix crop condition
  lib/private/Preview/Generator.php
Labels: 3. to review, regression

#32410 Add explicit return if getSmallImagePreview fails
  lib/private/Preview/Generator.php
Labels: bug, 3. to review

#32080 [stable22] Fix apps settings error message timeout
  apps/settings/js/vue-settings-admin-security.js
  apps/settings/js/vue-settings-admin-security.js.map
  apps/settings/js/vue-settings-apps-users-management.js
  apps/settings/js/vue-settings-apps-users-management.js.map
  apps/settings/js/vue-settings-apps.js
  apps/settings/js/vue-settings-apps.js.map
  apps/settings/js/vue-settings-nextcloud-pdf.js
  apps/settings/js/vue-settings-nextcloud-pdf.js.map
  apps/settings/js/vue-settings-personal-info.js
  apps/settings/js/vue-settings-personal-info.js.map
  apps/settings/js/vue-settings-personal-security.js
  apps/settings/js/vue-settings-personal-security.js.map
  apps/settings/js/vue-settings-personal-webauthn.js
  apps/settings/js/vue-settings-personal-webauthn.js.map
  apps/settings/js/vue-settings-users.js
  apps/settings/js/vue-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps-settings-users.js
  apps/settings/js/vue-vendors-settings-apps-settings-users.js.map
  apps/settings/js/vue-vendors-settings-apps.js
  apps/settings/js/vue-vendors-settings-apps.js.map
  apps/settings/js/vue-vendors-settings-users.js
  apps/settings/js/vue-vendors-settings-users.js.map
  apps/settings/src/store/apps.js
Labels: 3. to review

#32497 Use custom PHP runtime for PHPUnit execution in autotest
  autotest.sh
Labels: bug, 3. to review, technical debt

#32406 [Psalm] Fix spelling for PreConditionNotMetException
  lib/public/IDBConnection.php
Labels: 3. to review, technical debt

#32503 Improve two factor admin settings
  apps/settings/lib/Settings/Admin/Security.php
  apps/settings/src/components/AdminTwoFactor.vue
  apps/settings/templates/settings/admin/security.php
  apps/settings/tests/Settings/Admin/SecurityTest.php
  dist/settings-vue-settings-admin-security.js
  dist/settings-vue-settings-admin-security.js.map
Labels: 3. to review

#32517 Make appName of TemplateResponse accessible in BeforeTemplateRendered…
  lib/public/AppFramework/Http/TemplateResponse.php
Labels: bug, 3. to review

#32486 [Psalm] Rename $userName to $username to align with child classes
  lib/private/Setup/AbstractDatabase.php
  lib/private/Setup/MySQL.php
Labels: 3. to review, technical debt

#32501 Cleanup admin delegation setting page
  apps/settings/lib/Settings/Admin/Delegation.php
  apps/settings/src/components/AdminDelegating.vue
  dist/settings-vue-settings-admin-delegation.js
  dist/settings-vue-settings-admin-delegation.js.map
Labels: 3. to review, technical debt

#32443 Port BackgroundJob admin settings to vue
  apps/settings/lib/Settings/Admin/Server.php
  apps/settings/src/admin.js
  apps/settings/src/components/BasicSettings/BackgroundJob.vue
  apps/settings/src/main-admin-basic-settings.js
  apps/settings/templates/settings/admin/server.php
  apps/settings/tests/Settings/Admin/ServerTest.php
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
Labels: enhancement, 4. to release, technical debt

#32539 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32519 Rename user-agent used by the Webcal Refresh Service
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
Labels: bug, 4. to release, php, feature: caldav

#32378 Fix psalm issues related to the user backend
  build/psalm-baseline.xml
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/User/Database.php
  lib/private/User/LazyUser.php
  lib/private/User/Manager.php
  lib/private/User/Session.php
  lib/private/User/User.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  lib/public/IAvatar.php
  lib/public/IUser.php
  lib/public/IUserManager.php
  lib/public/User/Backend/ICheckPasswordBackend.php
  tests/lib/User/ManagerTest.php
Labels: 3. to review

#32554 Adjust docs to the same as the implementation
  lib/public/DB/QueryBuilder/IQueryBuilder.php
Labels: 3. to review

#32560 Add API to change preferences
  apps/provisioning_api/appinfo/routes.php
  apps/provisioning_api/composer/composer/autoload_classmap.php
  apps/provisioning_api/composer/composer/autoload_static.php
  apps/provisioning_api/lib/Controller/PreferencesController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Config/BeforePreferenceDeletedEvent.php
  lib/public/Config/BeforePreferenceSetEvent.php
Labels: enhancement, 3. to review, feature: users and groups, pending documentation

#32555 Revert api break
  lib/public/IUser.php
Labels: bug, 3. to review

#32571 Remove at() matcher for tests for files app
  apps/files/tests/Command/DeleteOrphanedFilesTest.php
  apps/files/tests/Controller/ApiControllerTest.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: 3. to review, technical debt

#32558 Fix various errors reported by eslint
  .eslintignore
  apps/federatedfilesharing/src/components/AdminSettings.vue
  apps/settings/src/admin.js
  apps/settings/src/apps.js
  apps/settings/src/components/BasicSettings/BackgroundJob.vue
  apps/sharebymail/src/components/AdminSettings.vue
  apps/systemtags/src/app.js
  apps/user_status/src/menu.js
  dist/federatedfilesharing-vue-settings-admin.js
  dist/federatedfilesharing-vue-settings-admin.js.map
  dist/settings-apps.js.map
  dist/settings-legacy-admin.js.map
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/sharebymail-vue-settings-admin-sharebymail.js
  dist/sharebymail-vue-settings-admin-sharebymail.js.map
  dist/systemtags-systemtags.js.map
  dist/user_status-menu.js.map
Labels: 3. to review, technical debt

#32575 Improve warning about missing pnctl
  console.php
Labels: 3. to review

#32548 Fix return type and make type stricter
  apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
  build/psalm-baseline.xml
Labels: bug, 4. to release, regression

#32557 Modernize the dav admin settings
  apps/dav/src/views/CalDavSettings.vue
  dist/dav-settings-admin-caldav.js
  dist/dav-settings-admin-caldav.js.map
Labels: 3. to review, technical debt, feature: accessibility

#31761 Require a recent phpunit version in integration and acceptance
  build/integration/composer.json
  build/integration/features/bootstrap/AppConfiguration.php
  build/integration/features/bootstrap/CommandLine.php
  build/integration/features/bootstrap/CommandLineContext.php
  build/integration/features/bootstrap/Provisioning.php
  build/integration/features/bootstrap/Trashbin.php
  tests/acceptance/composer.json
  tests/acceptance/composer.lock
  tests/acceptance/features/bootstrap/PublicShareContext.php
Labels: 3. to review

#32580 Fix handling events without names in activities
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
Labels: bug, 4. to release, feature: dav, backport-request, feature: activity and notification

#32567 Remove at() matcher use from encryption tests
  apps/encryption/tests/Controller/SettingsControllerTest.php
  apps/encryption/tests/Crypto/EncryptAllTest.php
  apps/encryption/tests/KeyManagerTest.php
Labels: 3. to review, technical debt

#32577 Remove at() matcher in files_sharing tests
  apps/files_sharing/tests/Command/CleanupRemoteStoragesTest.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  apps/files_sharing/tests/External/ManagerTest.php
  apps/files_sharing/tests/MountProviderTest.php
Labels: 3. to review, technical debt

#32618 Fix status handling
  apps/user_status/lib/Listener/UserLiveStatusListener.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/src/components/SetStatusModal.vue
  apps/user_status/src/store/userStatus.js
  apps/user_status/tests/Unit/Listener/UserLiveStatusListenerTest.php
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: bug, 3. to review, backport-request, feature: status

#32601 Move Gd failed operations to debug level
  lib/private/legacy/OC_Image.php
Labels: 3. to review, backport-request

#32596 Add lint job for PHP8.2
  .github/workflows/lint.yml
Labels: 3. to review

#32349 Add event to load additional scripts for projects
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/list.php
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Collaboration/Resources/Listener.php
  lib/public/Collaboration/Resources/LoadAdditionalScriptsEvent.php
Labels: 3. to review, technical debt, pending documentation

#32470 [stable24] Fix backgroundjobs mode
  apps/settings/src/admin.js
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: bug, 2. developing

#32655 Handle non existing settings again
  lib/private/Settings/Manager.php
Labels: 3. to review, backport-request

#32649 [Automated] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#32591 Fix node tests ci
  apps/dav/src/views/CalDavSettings.spec.js
  apps/dav/src/views/__snapshots__/CalDavSettings.spec.js.snap
  build/files-checker.php
  jest.config.js
  package-lock.json
  package.json
  tests/jestBabelTransformer.js
  tests/jestSetup.js
Labels: bug, 3. to review

#32634 [Psalm] Fix docblock for return type
  lib/private/Files/Mount/MoveableMount.php
Labels: 3. to review, technical debt

#32206 Add a method to get estimated export size in IMigrator
  apps/dav/lib/UserMigration/CalendarMigrator.php
  apps/dav/lib/UserMigration/ContactsMigrator.php
  apps/files_trashbin/lib/UserMigration/TrashbinMigrator.php
  apps/settings/lib/UserMigration/AccountMigrator.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/UserMigration/ISizeEstimationMigrator.php
Labels: enhancement, 4. to release, backport-request, feature: user migration

#32509 Properly calculate primary element based on background luminance
  apps/theming/lib/Themes/DarkTheme.php
Labels: bug, 3. to review, feature: theming

#32663 Cleanup tempfiles after each cron job run
  cron.php
Labels: bug, 3. to review

#32587 Improve JSConfigHelper code quality a bit
  lib/private/Template/JSConfigHelper.php
  tests/lib/AppFramework/Middleware/Security/RateLimitingMiddlewareTest.php
Labels: bug, 3. to review, technical debt

#32502 Use SettingsSection in workflowengine settings
  apps/workflowengine/lib/Settings/ASettings.php
  apps/workflowengine/src/components/Workflow.vue
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: 4. to release

#32485 [Psalm] Fix docblock for addFileFromStream
  lib/private/Streamer.php
  lib/public/AppFramework/Http/ZipResponse.php
Labels: 3. to review, technical debt

#32670 Fix share permissions rendering
  apps/files_sharing/src/components/SharePermissionsEditor.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 4. to release, feature: sharing, backport-request, javascript

#32625 [stable23] Fix status handling
  apps/user_status/js/user-status-menu.js
  apps/user_status/js/user-status-menu.js.map
  apps/user_status/lib/Listener/UserLiveStatusListener.php
  apps/user_status/src/store/userStatus.js
  apps/user_status/tests/Unit/Listener/UserLiveStatusListenerTest.php
Labels: bug, 4. to release, feature: status
