Repository nextcloud/server, pull requests merged in 2023-01, with the labels that each got.

#35825 [stable23] add migration for encryption keys in wrong location
  apps/encryption/appinfo/info.xml
  apps/encryption/composer/composer/autoload_classmap.php
  apps/encryption/composer/composer/autoload_static.php
  apps/encryption/lib/Command/FixKeyLocation.php
Labels: 3. to review

#35734 [stable25] Quota value as float for 32-bit systems
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/DAV.php
  lib/private/Files/Storage/Local.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/private/LargeFileHelper.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
Labels: 3. to review, backport-request, feature: files

#28117 Align checksum dav property with desktop client parsing
  apps/dav/lib/Connector/Sabre/ChecksumList.php
  lib/public/Files/FileInfo.php
Labels: bug, 4. to release

#35820 Avoid using the word 'password' in the APP_TOKEN_CREATED activity
  apps/settings/lib/Activity/Provider.php
Labels: 3. to review

#35956 docs: trusted_proxies support IPv6 ranges
  config/config.sample.php
Labels: 3. to review

#35957 chore(CI): Improve rate limit situation when installing phpunit
  .github/workflows/ftp.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/oci.yml
  .github/workflows/performance.yml
  .github/workflows/psalm-github.yml
  .github/workflows/s3-external.yml
  .github/workflows/s3-primary.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review, backport-request, technical debt

#35943 Code fixes from PR 34997
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Provisioning/Apple/AppleProvisioningPlugin.php
  apps/files_external/tests/Backend/BackendTest.php
  apps/settings/tests/Controller/UsersControllerTest.php
  apps/user_ldap/ajax/wizard.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Mapping/AbstractMapping.php
  apps/weather_status/lib/Service/WeatherStatusService.php
  lib/private/Files/Storage/Wrapper/EncodingDirectoryWrapper.php
  lib/private/KnownUser/KnownUserMapper.php
  lib/private/LargeFileHelper.php
  lib/private/Preview/Office.php
  lib/private/legacy/OC_API.php
Labels: 3. to review

#35963 [stable25] docs: trusted_proxies support IPv6 ranges
  config/config.sample.php
Labels: 4. to release

#35969 fix link to documentation of php function
  lib/public/Files/Storage.php
Labels: 3. to review

#35876 Adding option to set Auto-Submitted email header
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/settings/lib/Mailer/NewUserMailHelper.php
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/autoload_static.php
  lib/private/Mail/Message.php
  lib/public/Mail/Headers/AutoSubmitted.php
  lib/public/Mail/IMessage.php
  tests/lib/Mail/MessageTest.php
Labels: enhancement, 3. to review

#35873 Implement occ status command via return codes v2 (Fixes: #35704)
  core/Command/Status.php
  lib/private/Console/Application.php
Labels: enhancement, 4. to release, feature: occ

#35965 Also limit the password length on reset
  core/Controller/LoginController.php
  core/Controller/LostController.php
Labels: bug, 4. to release, backport-request, feature: users and groups

#35972 appsidebar should be compact when opened on small heights
  apps/files/src/views/Sidebar.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review, regression

#35978 Fix user status icon in avatar menu
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review, backport-request, feature: status

#35987 Bump json5 from 1.0.1-1.0.2 and 2.2.0-2.2.3
  package-lock.json
Labels: 3. to review

#35975 Update crl after revoke files_bpm.csr
  resources/codesigning/root.crl
Labels: 3. to review, backport-request

#35962 [stable25] chore(CI): Improve rate limit situation when installing phpunit
  .github/workflows/ftp.yml
  .github/workflows/lint.yml
  .github/workflows/oci.yml
  .github/workflows/performance.yml
  .github/workflows/psalm-github.yml
  .github/workflows/s3-external.yml
  .github/workflows/s3-primary.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
Labels: 4. to release

#34865 Add logging to Scheduling Plugin
  apps/dav/appinfo/v1/caldav.php
  apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/Schedule/PluginTest.php
Labels: enhancement, 3. to review

#35979 Show local time in avatar menu
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Contacts/ContactsMenu/ActionProviderStore.php
  lib/private/Contacts/ContactsMenu/Providers/LocalTimeProvider.php
  tests/lib/Contacts/ContactsMenu/ActionProviderStoreTest.php
  tests/lib/Contacts/ContactsMenu/Providers/LocalTimeProviderTest.php
Labels: enhancement, 3. to review

#35981 Add a const for the max user password length
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/lib/Controller/ChangePasswordController.php
  core/Controller/LostController.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/public/IUserManager.php
Labels: 3. to review, feature: users and groups, technical debt

#35988 [stable25] Bump json5 from 1.0.1-1.0.2 and 2.2.0-2.2.3
  package-lock.json
Labels: 3. to review

#35990 [stable23] Bump json5 from 1.0.1-1.0.2 and 2.2.0-2.2.3
  package-lock.json
Labels: 3. to review

#35667 Allow target="_blank" in apps navigation items
  core/src/components/AppMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: 4. to release, backport-request, regression, feature: vue apps, javascript

#33898 PublickKeyTokenProvider: Fix password update routine with password hash
  core/Migrations/Version25000Date20220905140840.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Token/PublicKeyToken.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
  version.php
Labels: 3. to review, performance 🚀

#35817 [stable25] Allow additional Sabre plugins in publicwebdav.php
  apps/dav/appinfo/v1/publicwebdav.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/BeforeSabrePubliclyLoadedEvent.php
Labels: enhancement, 3. to review, feature: dav

#35818 [stable24] Allow additional Sabre plugins in publicwebdav.php
  apps/dav/appinfo/v1/publicwebdav.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/BeforeSabrePubliclyLoadedEvent.php
Labels: enhancement, 3. to review, feature: dav

#36007 [stable25] Allow target="_blank" in app navigation items
  core/src/components/AppMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review

#36005 Fix default phone region validation
  apps/settings/lib/Settings/Personal/PersonalInfo.php
  apps/settings/src/components/PersonalInfo/PhoneSection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 3. to review, backport-request, feature: settings

#36011 fix(ui): Fix SVG mail icon missing width/height
  core/img/actions/mail.svg
  core/img/actions/mastodon.svg
  core/img/f-droid.svg
  dist/icons.css
Labels: 3. to review

#36015 fix(CI): Check for the image-optimization binaries we want to use
  build/image-optimization.sh
Labels: 3. to review, technical debt

#32057 Fix sync errors for card creation with the same uri from different sources
  apps/dav/lib/CardDAV/Converter.php
  apps/dav/lib/CardDAV/SyncService.php
Labels: bug, 4. to release, feature: carddav

#35973 Hook into sabre event lifecycle for iMip Messages
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/tests/unit/CalDAV/CalendarImplTest.php
Labels: enhancement, 4. to release, pending documentation, feature: caldav

#36016 Add restrictions when downloading to resolve with opengraph link provider
  lib/private/Collaboration/Reference/LinkReferenceProvider.php
Labels: 3. to review, backport-request, security, integration

#36024 Fix scrolling while dragging in file list view
  apps/files/js/files.js
Labels: bug, 4. to release, backport-request, feature: files, javascript

#36029 24.0.9 RC1
  version.php
Labels: 3. to review

#36030 25.0.3 RC1
  version.php
Labels: 3. to review

#36027 fix: show toggle grid view button with open sidebar
  apps/files/css/files.css
  apps/files/css/files.scss
  apps/files/css/merged.css
Labels: bug, design, 3. to review, feature: files

#35655 Replace custom tooltips with native one in vue components and views
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryInherited.vue
  apps/files_sharing/src/components/SharingEntryInternal.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/components/SharingEntrySimple.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/utils/GeneratePassword.js
  apps/files_sharing/src/views/SharingInherited.vue
  apps/files_sharing/src/views/SharingTab.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, backport-request, blocked

#36047 fix cache key used to verify shared mountpoints
  apps/files_sharing/lib/SharedMount.php
Labels: 4. to release, backport-request

#36043 Link reference provider: Improve content-type check
  lib/private/Collaboration/Reference/LinkReferenceProvider.php
Labels: bug, 4. to release, backport-request, integration

#36062 [stable22] Update ca-cert bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#36060 [stable23] Update ca-cert bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#36059 [stable25] Update ca-cert bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#36061 [stable24] Update ca-cert bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#36026 Get rid of deprecated at matcher in dav application tests
  apps/dav/tests/unit/BackgroundJob/CleanupInvitationTokenJobTest.php
  apps/dav/tests/unit/BackgroundJob/EventReminderJobTest.php
  apps/dav/tests/unit/BackgroundJob/RegisterRegenerateBirthdayCalendarsTest.php
  apps/dav/tests/unit/CalDAV/CachedSubscriptionTest.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/PushProviderTest.php
  apps/dav/tests/unit/CalDAV/Reminder/ReminderServiceTest.php
  apps/dav/tests/unit/CalDAV/ResourceBooking/AbstractPrincipalBackendTest.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
  apps/dav/tests/unit/CalDAV/Search/SearchPluginTest.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/PluginTest.php
  apps/dav/tests/unit/CardDAV/AddressBookImplTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  apps/dav/tests/unit/CardDAV/SyncServiceTest.php
  apps/dav/tests/unit/Command/MoveCalendarTest.php
  apps/dav/tests/unit/Connector/Sabre/AuthTest.php
  apps/dav/tests/unit/Connector/Sabre/BearerAuthTest.php
  apps/dav/tests/unit/Connector/Sabre/FakeLockerPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/FilesReportPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/PrincipalTest.php
  apps/dav/tests/unit/Connector/Sabre/TagsPluginTest.php
  apps/dav/tests/unit/Controller/InvitationResponseControllerTest.php
  apps/dav/tests/unit/DAV/CustomPropertiesBackendTest.php
  apps/dav/tests/unit/DAV/GroupPrincipalTest.php
  apps/dav/tests/unit/Migration/RefreshWebcalJobRegistrarTest.php
  apps/dav/tests/unit/Migration/RemoveDeletedUsersCalendarSubscriptionsTest.php
  apps/dav/tests/unit/Provisioning/Apple/AppleProvisioningNodeTest.php
  apps/dav/tests/unit/Provisioning/Apple/AppleProvisioningPluginTest.php
  apps/dav/tests/unit/Search/EventsSearchProviderTest.php
  apps/dav/tests/unit/Upload/ChunkingPluginTest.php
Labels: 3. to review, technical debt

#35980 Remove unused legacy ajax/list.php in files app
  apps/files/ajax/list.php
  apps/files/appinfo/routes.php
  core/src/OC/dialogs.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
  tests/lib/Route/RouterTest.php
  tests/lib/UrlGeneratorTest.php
Labels: 4. to release, technical debt

#35964 IMigrationStep progress bar fix
  lib/private/Migration/ConsoleOutput.php
Labels: 3. to review

#36052 add test for shared mount conflict resolution
  apps/files_sharing/tests/SharedMountTest.php
  apps/files_sharing/tests/TestCase.php
Labels: 3. to review

#36048 fix(authentication): Only verify each hash once
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: bug, 4. to release, feature: authentication, regression, performance 🚀

#36065 Remove js navigation on alternative login click
  core/src/views/Login.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, 3. to review

#36058 [master] Update ca-cert bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, 4. to release, dependencies

#35903 Replace custom tooltips with native ones in apps page
  apps/settings/src/components/AppList/AppItem.vue
  apps/settings/src/views/Apps.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 4. to release, backport-request, accessibility

#36069 Fix theming migration repair step by passing correct type for argument
  apps/theming/lib/Jobs/MigrateBackgroundImages.php
Labels: bug, 4. to release, backport-request

#36074 Fix inability to re-enter share password after invalid input
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#36071 improve link reference content-type check
  lib/private/Collaboration/Reference/LinkReferenceProvider.php
Labels: 3. to review, integration

#36081 [stable25] Fix theming migration repair step by passing correct type for argument
  apps/theming/lib/Jobs/MigrateBackgroundImages.php
Labels: 3. to review

#36006 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35893 Replace custom tooltips with native ones in users page
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, 4. to release, backport-request, feature: users and groups, accessibility

#36079 25.0.3 RC2
  version.php
Labels: 3. to review

#36080 24.0.9 RC2
  version.php
Labels: 3. to review

#35739 Switch logical operators
  lib/private/Files/Cache/Scanner.php
Labels: 4. to release

#36095 Limit key names when uploading theme images
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/tests/Controller/ThemingControllerTest.php
Labels: 3. to review, backport-request

#36001 Validate user timezone given from login data before saving it
  lib/private/Authentication/Login/SetUserTimezoneCommand.php
Labels: 3. to review

#36054 l10n: Change to uppercase
  apps/files/src/views/Navigation.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, feature: language l10n and translations

#35844 doc: add description how BackgroundCleanupJob.getNewPreviewLocations works
  lib/private/Preview/BackgroundCleanupJob.php
Labels: 3. to review, developer experience

#36056 Differentiate share links
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/views/SharingLinkList.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, feature: sharing, backport-request, accessibility

#36121 Allow keyup enter in user status
  apps/user_status/src/components/CustomMessageInput.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: bug, 3. to review, backport-request, feature: status

#36131 Revert "Fix sync errors for card creation with the same uri from different sources"
  apps/dav/lib/CardDAV/Converter.php
  apps/dav/lib/CardDAV/SyncService.php
Labels: bug, 3. to review, regression, feature: contacts menu, feature: carddav, feature: contacts

#36130 Add always visible share label
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request, accessibility

#36067 spaces are allowed in userids
  lib/private/User/Manager.php
  tests/lib/User/ManagerTest.php
Labels: 4. to release

#36124 feat(CI): Enforce colored output for behat on drone CI
  build/integration/run.sh
Labels: 3. to review

#36136 feat(CI): Enforce colored output for acceptance tests on drone CI
  tests/acceptance/run-local.sh
Labels: 4. to release

#36143 Revert "[stable25] Allow keyup enter in user status"
  apps/user_status/src/components/CustomMessageInput.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 3. to review

#36075 Add support for s3 storage classes
  apps/files_external/lib/Lib/Backend/AmazonS3.php
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
Labels: 2. developing

#36073 Use a Generator for job list to fix background-job:list command
  core/Command/Background/ListCommand.php
  lib/private/BackgroundJob/JobList.php
  lib/public/BackgroundJob/IJobList.php
  tests/lib/BackgroundJob/DummyJobList.php
  tests/lib/BackgroundJob/JobListTest.php
Labels: bug, 3. to review

#35970 Improve exception serializing
  lib/private/Log.php
  lib/private/Log/ExceptionSerializer.php
  lib/private/Support/CrashReport/Registry.php
  lib/public/Support/CrashReport/IRegistry.php
Labels: bug, 4. to release, performance 🚀

#36161 still include the share target in the cache key for validating share mount
  apps/files_sharing/lib/SharedMount.php
Labels: 4. to release, backport-request

#36169 [stable25] still include the share target in the cache key for validating share mount
  apps/files_sharing/lib/SharedMount.php
Labels: 4. to release

#36093 Improve password generation for link shares
  apps/files_sharing/src/utils/GeneratePassword.js
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, backport-request

#36094 Only expose storage location to admins
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 3. to review, backport-request

#36140 25.0.3
  version.php
Labels: 3. to review

#36141 24.0.9
  version.php
Labels: 3. to review

#36177 [stable23] Ext storage configs default value support + enable SSL by default
  apps/files_external/js/settings.js
  apps/files_external/lib/Lib/Backend/AmazonS3.php
  apps/files_external/lib/Lib/Backend/DAV.php
  apps/files_external/lib/Lib/Backend/FTP.php
  apps/files_external/lib/Lib/Backend/OwnCloud.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/tests/DefinitionParameterTest.php
Labels: 3. to review

#36166 fix(PHP8.2): Declare Symfony Application property in console application
  lib/private/Console/Application.php
Labels: 4. to release, technical debt

#36194 Fix failed revert for #35071
  core/css/guest_BACKUP_3955473.css
  core/css/guest_BASE_3955473.css
  core/css/guest_LOCAL_3955473.css
  core/css/guest_REMOTE_3955473.css
Labels: bug, 4. to release, regression

#36204 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#35419 Fix login loop if login CSRF fails and user is not logged in
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: bug, 4. to release, backport-request, feature: authentication

#35954 [stable25] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#36175 [stable24] Ext storage configs default value support + enable SSL by default
  apps/files_external/js/settings.js
  apps/files_external/lib/Lib/Backend/AmazonS3.php
  apps/files_external/lib/Lib/Backend/DAV.php
  apps/files_external/lib/Lib/Backend/FTP.php
  apps/files_external/lib/Lib/Backend/OwnCloud.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/tests/DefinitionParameterTest.php
Labels: 4. to release

#36174 [stable25] Improve saving applicable users in ext storage
  apps/files_external/css/settings.css
  apps/files_external/css/settings.css.map
  apps/files_external/css/settings.scss
  apps/files_external/js/settings.js
  apps/files_external/templates/settings.php
  apps/files_external/tests/js/settingsSpec.js
Labels: 4. to release

#35783 Inject services into controller methods
  core/Controller/LoginController.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Http/Dispatcher.php
  tests/Core/Controller/LoginControllerTest.php
  tests/lib/AppFramework/Http/DispatcherTest.php
Labels: enhancement, 4. to release, integration, performance 🚀

#36221 Use current git branch by default when setting up cypress container
  cypress/dockerNode.ts
Labels: 3. to review, tests

#27492 Remove the CAN_INSTALL file when occ maintenance:install is complete
  core/Command/Maintenance/Install.php
  core/Controller/SetupController.php
  lib/private/Setup.php
Labels: bug, 3. to review, feature: install and update

#36219 Correct title for button on federation actions button
  apps/settings/src/components/PersonalInfo/shared/FederationControlAction.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 4. to release, regression

#36193 [stable25] Revert "Add alt to the logo, adapt css for logo"
  core/css/guest.css
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
  lib/private/TemplateLayout.php
Labels: bug, 3. to review, regression

#36225 Add check config.php for ffmpeg_path in PreviewManager.php. fix for snap no video preview
  config/config.sample.php
  lib/private/PreviewManager.php
Labels: enhancement, 3. to review

#36223 Allow interaction with encrypted folders
  apps/files/css/files.css
  apps/files/css/files.css.map
  apps/files/css/files.scss
  apps/files/css/merged.css
  apps/files/css/merged.css.map
Labels: bug, 4. to release, backport-request

#36237 Disable unreliable acceptance tests
  tests/acceptance/features/app-files-sharing.feature
Labels: 4. to release, backport-request, technical debt

#36106 [stable25] Fix inability to re-enter share password after invalid input
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 4. to release, feature: sharing

#36107 [stable24] Fix inability to re-enter share password after invalid input
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 4. to release, feature: sharing

#36123 normalize userid in user:setting
  core/Command/User/Setting.php
Labels: 4. to release

#35632 docs: document types flag for search options
  lib/private/ContactsManager.php
  lib/public/Contacts/IManager.php
Labels: 4. to release, technical debt

#36162 fix(PHP8.2): Fix deprecated string interpolation syntax
  core/Command/Maintenance/RepairShareOwnership.php
Labels: 4. to release, technical debt

#36253 chore(dav): Remove useless var tag
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/tests/unit/BackgroundJob/PruneOutdatedSyncTokensJobTest.php
  apps/dav/tests/unit/Listener/ActivityUpdaterListenerTest.php
  apps/dav/tests/unit/Settings/CalDAVSettingsTest.php
Labels: 3. to review, technical debt

#36264 fix(occ): Fix comment formatting of maintenance:repair command
  core/Command/Maintenance/Repair.php
Labels: bug, 3. to review, backport-request, regression, feature: occ

#36272 [stable25] fix(theming): fix admin images migration
  apps/theming/appinfo/info.xml
  apps/theming/lib/Migration/CleanupOldCache.php
  apps/theming/lib/Migration/MigrateAdminConfig.php
Labels: bug, 4. to release, backport-request, feature: theming, regression

#36280 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#36246 [stable25] Specify the profiler app branch to test with
  .github/workflows/performance.yml
Labels: 4. to release

#36247 Specify the profiler app branch to test with
  .github/workflows/performance.yml
Labels: 3. to review

#36269 Fix broken user:setting command unit test
  tests/Core/Command/User/SettingTest.php
Labels: bug, 4. to release

#36278 Fix interned strings buffer check if 0 free bytes
  apps/settings/lib/Controller/CheckSetupController.php
Labels: bug, 3. to review, backport-request, php

#36266 Fix double where in CustomProperiesBackendTest
  apps/dav/tests/unit/DAV/CustomPropertiesBackendTest.php
Labels: bug, 3. to review, backport-request

#36250 Add success message to personal settings clipboard button
  apps/federatedfilesharing/src/components/PersonalSettings.vue
  dist/federatedfilesharing-vue-settings-personal.js
  dist/federatedfilesharing-vue-settings-personal.js.map
Labels: 4. to release, backport-request

#36258 Fix user status message input
  apps/user_status/src/components/CustomMessageInput.vue
  apps/user_status/src/components/SetStatusModal.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 3. to review, backport-request, feature: status, accessibility

#36254 chore(dav): Make json_encode and json_decode throw on error
  apps/dav/lib/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJob.php
  apps/dav/lib/BulkUpload/BulkUploadPlugin.php
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/Comments/CommentsPlugin.php
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  apps/dav/lib/UserMigration/ContactsMigrator.php
Labels: 4. to release, technical debt

#36260 Fix WHERE condition when selecting user's availability for the status…
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
Labels: bug, 3. to review, backport-request, feature: status

#35935 [Fix]: scan-app-data conversion
  apps/files/lib/Command/ScanAppData.php
Labels: 4. to release, backport-request

#36261 fix(querybuilder): Log a warning if where() is called again on a quer…
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 3. to review, technical debt

#32572 Fix a bunch of deprecation in the phpunit for core
  autotest.sh
  tests/Core/Command/Apps/AppsDisableTest.php
  tests/Core/Command/Apps/AppsEnableTest.php
  tests/Core/Controller/LoginControllerTest.php
  tests/Core/Controller/NavigationControllerTest.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
  tests/Core/Service/LoginFlowV2ServiceUnitTest.php
Labels: 2. developing, do not merge

#36326 don't translate a variable
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/VisibilityDropdown.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 4. to release, feature: language l10n and translations

#36333 Fix default value for files_no_background_scan
  config/config.sample.php
Labels: 3. to review, backport-request

#36216 Fix user_status heartbeat response
  apps/user_status/lib/Controller/HeartbeatController.php
  apps/user_status/src/services/heartbeatService.js
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 3. to review

#35759 Add app config for default template path
  lib/private/Files/Template/TemplateManager.php
Labels: enhancement, 4. to release, pending documentation, feature: templates

#36187 ci: migrate ocp since checker to psalm
  autotest-checkers.sh
  build/OCPSinceChecker.php
  build/psalm/OcpSinceChecker.php
  lib/public/Dashboard/RegisterWidgetEvent.php
  lib/public/Files/Storage.php
  lib/public/Group/Backend/ABackend.php
  lib/public/User/Backend/ABackend.php
  psalm-ocp.xml
Labels: 3. to review, technical debt

#32798 [S3] Add option to specify an SSE-C customer provided key
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
Labels: enhancement, 3. to review, pending documentation

#36298 perf(app-framework): Make app middleware registration even lazier
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  tests/lib/AppFramework/Bootstrap/RegistrationContextTest.php
  tests/lib/AppFramework/DependencyInjection/DIContainerTest.php
Labels: 4. to release, performance 🚀

#36352 imaginary - add tiff to supported formats
  lib/private/Preview/Imaginary.php
Labels: bug, enhancement, 4. to release, backport-request

#36347 chore(autoloaders): Update autoloader files for Composer 2.5.1
  apps/admin_audit/composer/composer/ClassLoader.php
  apps/admin_audit/composer/composer/installed.php
  apps/cloud_federation_api/composer/composer/ClassLoader.php
  apps/cloud_federation_api/composer/composer/installed.php
  apps/comments/composer/composer/ClassLoader.php
  apps/comments/composer/composer/installed.php
  apps/contactsinteraction/composer/composer/ClassLoader.php
  apps/contactsinteraction/composer/composer/installed.php
  apps/dav/composer/composer/ClassLoader.php
  apps/dav/composer/composer/installed.php
  apps/encryption/composer/composer/ClassLoader.php
  apps/encryption/composer/composer/installed.php
  apps/federatedfilesharing/composer/composer/ClassLoader.php
  apps/federatedfilesharing/composer/composer/installed.php
  apps/federation/composer/composer/ClassLoader.php
  apps/federation/composer/composer/installed.php
  apps/files/composer/composer/ClassLoader.php
  apps/files/composer/composer/installed.php
  apps/files_sharing/composer/composer/ClassLoader.php
  apps/files_sharing/composer/composer/installed.php
  apps/files_trashbin/composer/composer/ClassLoader.php
  apps/files_trashbin/composer/composer/installed.php
  apps/files_versions/composer/composer/ClassLoader.php
  apps/files_versions/composer/composer/installed.php
  apps/lookup_server_connector/composer/composer/ClassLoader.php
  apps/lookup_server_connector/composer/composer/installed.php
  apps/oauth2/composer/composer/ClassLoader.php
  apps/oauth2/composer/composer/installed.php
  apps/provisioning_api/composer/composer/ClassLoader.php
  apps/provisioning_api/composer/composer/installed.php
  apps/settings/composer/composer/ClassLoader.php
  apps/settings/composer/composer/installed.php
  apps/sharebymail/composer/composer/ClassLoader.php
  apps/sharebymail/composer/composer/installed.php
  apps/systemtags/composer/composer/ClassLoader.php
  apps/systemtags/composer/composer/installed.php
  apps/testing/composer/composer/ClassLoader.php
  apps/testing/composer/composer/installed.php
  apps/twofactor_backupcodes/composer/composer/ClassLoader.php
  apps/twofactor_backupcodes/composer/composer/installed.php
  apps/updatenotification/composer/composer/ClassLoader.php
  apps/updatenotification/composer/composer/installed.php
  apps/user_ldap/composer/composer/ClassLoader.php
  apps/user_ldap/composer/composer/installed.php
  apps/user_status/composer/composer/ClassLoader.php
  apps/user_status/composer/composer/installed.php
  apps/workflowengine/composer/composer/ClassLoader.php
  apps/workflowengine/composer/composer/installed.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/platform_check.php
Labels: 4. to release

#35894 fix moving files of encrypted local storage to unencrypted local storage
  lib/private/Files/Storage/Local.php
Labels: 4. to release, backport-request

#36341 fix(app-framework): Specify return type of Middleware::beforeController
  lib/public/AppFramework/Middleware.php
Labels: 3. to review, technical debt

#36210 fix(dav): check if principal has email address before accessing it
  apps/dav/lib/Connector/Sabre/Principal.php
Labels: bug, 4. to release, backport-request, feature: caldav

#36310 feat(app-framework): Add support for global middlewares
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/MiddlewareRegistration.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  tests/lib/AppFramework/Bootstrap/RegistrationContextTest.php
  tests/lib/AppFramework/DependencyInjection/DIContainerTest.php
Labels: enhancement, 4. to release, integration

#36371 Mark compiled CSS as binary
  .gitattributes
Labels: 4. to release, feature: scss

#36370 Fix focus not returning to search icon
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: bug, 4. to release, backport-request, feature: search, accessibility

#36389 fix(CI): Install composer dependencies of Talk
  .drone.yml
Labels: 3. to review

#36402 ci(psalm): Generate base analysis on pushes so we can compare to upda…
  .github/workflows/static-code-analysis.yml
Labels: 3. to review, technical debt

#36395 FIX: This fill finish -> This will finish
  core/Command/Preview/Repair.php
Labels: 3. to review

#35557 Extend reference API for (future) frontend picker
  build/psalm-baseline.xml
  core/Controller/ReferenceApiController.php
  core/routes.php
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Collaboration/Reference/File/FileReferenceEventListener.php
  lib/private/Collaboration/Reference/ReferenceManager.php
  lib/private/Collaboration/Reference/RenderReferenceEventListener.php
  lib/public/Collaboration/Reference/ADiscoverableReferenceProvider.php
  lib/public/Collaboration/Reference/IDiscoverableReferenceProvider.php
  lib/public/Collaboration/Reference/IReferenceManager.php
  lib/public/Collaboration/Reference/ISearchableReferenceProvider.php
Labels: enhancement, 4. to release

#36363 feat(app-framework): Add UseSession attribute to replace annotation
  core/Controller/ClientFlowLoginController.php
  core/Controller/ClientFlowLoginV2Controller.php
  core/Controller/LoginController.php
  core/Controller/TwoFactorChallengeController.php
  core/Controller/WebAuthnController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Middleware/SessionMiddleware.php
  lib/public/AppFramework/Http/Attribute/UseSession.php
  tests/lib/AppFramework/Middleware/SessionMiddlewareTest.php
Labels: enhancement, 4. to release

#36394 [stable25] fix admin-disabled background and user pristine theming settings
  apps/theming/lib/Themes/CommonThemeTrait.php
Labels: bug, 4. to release, feature: theming

#36283 [stable25] l10n: Fixed grammar
  apps/theming/lib/Migration/MigrateAdminConfig.php
Labels: 3. to review, feature: language l10n and translations

#36348 Fix primary color usage in emails and federation
  apps/federatedfilesharing/lib/Settings/Personal.php
  apps/theming/lib/ThemingDefaults.php
  lib/private/Mail/EMailTemplate.php
  lib/public/Defaults.php
  tests/lib/Mail/EMailTemplateTest.php
Labels: bug, 3. to review, feature: theming

#36415 [stable25] Allow keyup enter in user status
  apps/user_status/src/components/CustomMessageInput.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: bug, 3. to review, feature: status

#36433 fix(encryption): don't throw on missing file
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: bug, 3. to review, feature: encryption (server-side)

#36420 fix the exif_read_data issue
  lib/private/Metadata/Provider/ExifProvider.php
Labels: bug, 3. to review, backport-request

#35474 Update rich-workspace visibility
  apps/files/js/newfilemenu.js
Labels: enhancement, 3. to review

#36440 perf(autoloading): Add authoritative autoloader for dashboard
  apps/dashboard/composer/autoload.php
  apps/dashboard/composer/composer.json
  apps/dashboard/composer/composer.lock
  apps/dashboard/composer/composer/ClassLoader.php
  apps/dashboard/composer/composer/InstalledVersions.php
  apps/dashboard/composer/composer/LICENSE
  apps/dashboard/composer/composer/autoload_classmap.php
  apps/dashboard/composer/composer/autoload_namespaces.php
  apps/dashboard/composer/composer/autoload_psr4.php
  apps/dashboard/composer/composer/autoload_real.php
  apps/dashboard/composer/composer/autoload_static.php
  apps/dashboard/composer/composer/installed.json
  apps/dashboard/composer/composer/installed.php
Labels: 4. to release, performance 🚀

#36445 l10n: Change admin to administrator
  apps/theming/lib/Migration/MigrateAdminConfig.php
Labels: bug, 4. to release, feature: language l10n and translations

#36331 fix(files) Call .action of local element instead of global page
  apps/files/js/filelist.js
Labels: 3. to review

#36453 Fix MigrateBackgroundImages on oracle
  apps/theming/lib/Jobs/MigrateBackgroundImages.php
  tests/lib/DB/QueryBuilder/ExpressionBuilderDBTest.php
Labels: bug, 3. to review, backport-request
