Repository nextcloud/server, pull requests merged in 2023-05, with the labels that each got.

#37980 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#37938 feat(system-tags): show inline in files
  apps/files/css/files.css
  apps/files/css/files.css.map
  apps/files/css/files.scss
  apps/files/css/merged.css
  apps/files/css/merged.css.map
  apps/files/css/mobile.css
  apps/files/css/mobile.css.map
  apps/files/css/mobile.scss
  apps/files/js/merged-index.json
  apps/files/js/systemtagsplugin.js
Labels: enhancement, 3. to review, feature: files, feature: tags

#38019 disable contacts menu features that regularly fail on drone
  build/integration/features/contacts-menu.feature
Labels: 3. to review, integration

#37962 Stopped scrollbar being hidden by rounded corners
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/server.css
  core/css/server.css.map
Labels: design, 3. to review, ux

#32866 Optimize retrieving display name when searching for users in a group
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Group_Proxy.php
  core/Command/User/ListCommand.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Group/Backend.php
  lib/private/Group/Database.php
  lib/private/Group/Group.php
  lib/private/User/LazyUser.php
  lib/private/User/Manager.php
  lib/public/Group/Backend/ISearchableGroupBackend.php
  lib/public/GroupInterface.php
  lib/public/IGroup.php
  tests/lib/Group/GroupTest.php
  tests/lib/Group/ManagerTest.php
  tests/lib/Util/Group/Dummy.php
Labels: 3. to review, performance 🚀

#37903 Fix multiple LDAP configuration support by fixing AccessFactory
  apps/user_ldap/lib/AccessFactory.php
  apps/user_ldap/lib/Jobs/Sync.php
  apps/user_ldap/tests/Jobs/SyncTest.php
Labels: bug, 4. to release, backport-request

#33106 Update expire_date column of table comments
  lib/private/Comments/Manager.php
  tests/lib/Comments/ManagerTest.php
Labels: bug, 4. to release, backport-request, feature: comments

#38024 Fix 32bits ci
  .github/workflows/phpunit-32bits.yml
  tests/lib/Template/JSResourceLocatorTest.php
Labels: 3. to review

#37943 Fix file_get_content signatures to make it clear it can return false
  lib/private/Files/Filesystem.php
  lib/private/Files/Node/File.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/private/Files/View.php
  lib/public/Files/File.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
Labels: bug, 4. to release, pending documentation

#37958 Mutualize expireDate handling when creating and updating a share
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: bug, 3. to review, feature: sharing, backport-request

#37802 Sharing: Do not show copy action when user doesn't have permissions
  apps/files_sharing/src/share.js
  dist/files_sharing-additionalScripts.js
  dist/files_sharing-additionalScripts.js.map
Labels: 3. to review

#38003 Improve translations api with detecting languages
  core/Controller/TranslationApiController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Translation/TranslationManager.php
  lib/public/Translation/CouldNotTranslateException.php
  lib/public/Translation/ITranslationManager.php
Labels: bug, 3. to review

#37937 Remove job from oc_jobs when the file is not findable
  lib/private/BackgroundJob/JobList.php
Labels: enhancement, 3. to review, php

#37787 fix: catch ManuallyLockedException and use app context
  apps/files_versions/lib/Storage.php
  apps/files_versions/lib/Versions/VersionManager.php
Labels: bug, 4. to release, backport-request

#38025 enh(contacts): write profile prop and backend prop to system addressbook
  apps/dav/lib/CardDAV/Converter.php
Labels: enhancement, 3. to review, feature: caldav

#37967 Add `aria-hidden` attr to the whole navigation depending on a sidebar state
  core/src/init.js
  dist/core-main.js
  dist/core-main.js.map
Labels: 4. to release, accessibility

#38012 Fix share input id
  apps/files_sharing/src/components/SharingInput.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, feature: sharing, accessibility

#38045 Fix app overflow menu on bright color theme
  core/src/components/AppMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 3. to review, backport-request

#38016 fix: add workaround for oci and limit queries
  lib/public/AppFramework/Db/QBMapper.php
Labels: bug, 3. to review

#38034 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#38046 fix(dav): Also throw in basic auth requests
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/Exception/TooManyRequests.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 3. to review, feature: authentication

#38051 fix(weather_status): Override the default `NcActions` aria-label
  apps/weather_status/src/App.vue
  dist/weather_status-weather-status.js
  dist/weather_status-weather-status.js.map
Labels: 3. to review, feature: accessibility

#37997 [stable24] Update crl after revoke shifts.csr
  resources/codesigning/root.crl
Labels: 3. to review

#37998 [stable23] Update crl after revoke shifts.csr
  resources/codesigning/root.crl
Labels: 3. to review

#38050 Fix "skip content"-buttons on small screen sizes
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review, backport-request, feature: accessibility

#38028 fix(settings): Increase "Edit your profile visibility button" contrast
  apps/settings/src/components/PersonalInfo/ProfileSection/EditProfileAnchorLink.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 3. to review, backport-request, feature: settings, accessibility

#37148 increase imaginary timeouts as for big files the processing could take very long
  lib/private/Preview/Imaginary.php
Labels: bug, 4. to release, backport-request

#38057 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#37865 add command to summarize space usage
  core/Command/Info/File.php
  core/Command/Info/FileUtils.php
  core/Command/Info/Space.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 4. to release

#35092 Check return value and improve error handling on certificate manager
  lib/private/Security/CertificateManager.php
Labels: bug, 3. to review, backport-request

#38073 feat(carddav): Map user's additional emails into the SAB card
  apps/dav/lib/CardDAV/Converter.php
Labels: enhancement, 4. to release, feature: carddav

#38085 fix(federation): Log address book sync exceptions
  apps/federation/lib/SyncFederationAddressBooks.php
Labels: bug, 4. to release, feature: federation

#31660 Rename setting 'sendEventRemindersToSharedGroupMembers' -> 'sendEventRemindersToSharedUsers'.
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
  apps/dav/lib/Settings/CalDAVSettings.php
  apps/dav/src/settings.js
  apps/dav/src/views/CalDavSettings.spec.js
  apps/dav/src/views/CalDavSettings.vue
  apps/dav/tests/unit/Settings/CalDAVSettingsTest.php
  dist/dav-settings-admin-caldav.js
  dist/dav-settings-admin-caldav.js.map
Labels: 3. to review

#38078 [stable26] Increase "Edit your profile visibility button" contrast
  apps/settings/src/components/PersonalInfo/ProfileSection/EditProfileAnchorLink.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 3. to review

#38063 fix(theming): unwanted variables and colours calc fixes
  apps/theming/css/default.css
  apps/theming/lib/Themes/CommonThemeTrait.php
  apps/theming/lib/Util.php
  apps/theming/src/components/BackgroundSettings.vue
  apps/theming/src/components/admin/ColorPickerField.vue
  apps/theming/tests/CapabilitiesTest.php
  apps/theming/tests/UtilTest.php
  core/css/apps.scss
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
  core/css/variables.scss
  dist/theming-admin-theming.js
  dist/theming-admin-theming.js.map
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
Labels: bug, 4. to release, feature: theming, regression

#38076 [stable26] Fix "skip content"-buttons on small screen sizes
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review

#38068 Bump hub number
  apps/settings/templates/settings/admin/overview.php
Labels: 4. to release

#38077 Remove version check for ancient libxml version
  lib/private/legacy/OC_Util.php
Labels: 4. to release, technical debt

#38102 Add messageId to richObject definition of Talk
  lib/public/RichObjectStrings/Definitions.php
Labels: enhancement, 3. to review, pending documentation

#38097 fix(translation): Don't use translation providers when from and to ar…
  lib/private/Translation/TranslationManager.php
Labels: bug, 3. to review

#36895 Fix json_decode expecting a string
  lib/private/IntegrityCheck/Checker.php
Labels: bug, 3. to review, backport-request

#38099 Remove unreachable UserStatus#clearStatus route
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/tests/Unit/Controller/UserStatusControllerTest.php
Labels: 3. to review, technical debt

#38133 feat: Add setup check warning if instance is in debug mode
  core/js/setupchecks.js
Labels: enhancement, 3. to review

#38088 fix(user): Can change display name
  lib/private/User/User.php
Labels: bug, 3. to review, feature: users and groups, feature: emails

#38125 Check if version entity is not null before delete
  apps/files_versions/lib/Storage.php
Labels: 3. to review, backport-request

#37838 log performance events for http requests
  lib/private/Http/Client/ClientService.php
  tests/lib/Http/Client/ClientServiceTest.php
Labels: 3. to review

#38069 list supported databases when provided db isn't supported
  core/Command/Maintenance/Install.php
Labels: 3. to review

#36893 Make sure to never trigger files hooks on a null path
  apps/dav/lib/Connector/Sabre/File.php
  lib/private/Files/Node/HookConnector.php
Labels: bug, 4. to release

#37944 Do not stop at the first PHP error/warning in files:scan
  apps/files/lib/Command/Scan.php
Labels: bug, enhancement, 3. to review, backport-request

#38100 Fix error on delete in ChunkingV2Plugin
  apps/dav/lib/Upload/ChunkingV2Plugin.php
Labels: bug, 3. to review

#38144 Add hidden labels for inputs while editing user row
  apps/settings/src/components/UserList/UserRow.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review

#38048 feat(dav): store scopes for properties and filter locally scoped properties for federated address book sync
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CardDAV/Converter.php
  apps/dav/lib/CardDAV/SystemAddressbook.php
  apps/dav/lib/CardDAV/UserAddressBooks.php
  apps/dav/lib/Migration/Version1027Date20230504122946.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/SystemAddressBookTest.php
  build/psalm-baseline.xml
Labels: 4. to release, feature: federation, feature: carddav

#38152 chore: Fine-tune editorconfig for build/psalm-baseline.xml
  .editorconfig
Labels: 3. to review

#31469 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#36118 Fix calendar emails to be outlook compatible
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  lib/private/Mail/Message.php
  lib/public/Mail/IMessage.php
Labels: 3. to review, pending documentation

#37971 Add commands for basic file actions
  apps/files/appinfo/info.xml
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/Command/Delete.php
  apps/files/lib/Command/Get.php
  apps/files/lib/Command/Put.php
Labels: enhancement, 4. to release

#38174 feat: Enhance template picker size and layout depending on aspect ratio
  apps/files/src/views/TemplatePicker.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, design, 3. to review

#38163 Show loading spinner until share settings are fully loaded
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  apps/settings/src/admin.js
  apps/settings/templates/settings/admin/sharing.php
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: bug, 4. to release, feature: settings

#37691 repair -1 folder sizes for object store background scan
  apps/files_sharing/lib/Scanner.php
  apps/files_sharing/tests/External/ScannerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/ObjectStore/NoopScanner.php
  lib/private/Files/ObjectStore/ObjectStoreScanner.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  tests/lib/Files/ObjectStore/ObjectStoreScannerTest.php
Labels: bug, 4. to release

#38067 fix: sort tags by name
  apps/dav/lib/SystemTag/SystemTagPlugin.php
Labels: bug, 4. to release

#38194 Fix redirect on unsupported browser warning
  core/src/views/UnsupportedBrowser.vue
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
Labels: bug, 3. to review

#37961 SystemTags endpoint to return tags used by a user with meta data
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/SystemTag/SystemTagNode.php
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  apps/dav/lib/SystemTag/SystemTagsInUseCollection.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Node/Folder.php
  lib/private/SystemTag/SystemTagsInFilesDetector.php
Labels: bug, 3. to review, feature: dav, backport-request, feature: tags

#33381 Fix typos in lib/public subdirectory
  lib/private/Preview/Generator.php
  lib/public/Accounts/IAccount.php
  lib/public/Accounts/IAccountPropertyCollection.php
  lib/public/AppFramework/PublicShareController.php
  lib/public/BackgroundJob/IJobList.php
  lib/public/Collaboration/AutoComplete/IManager.php
  lib/public/Contacts/IManager.php
  lib/public/DB/Exception.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
  lib/public/DirectEditing/IEditor.php
  lib/public/Files.php
  lib/public/Files/Cache/ICache.php
  lib/public/FullTextSearch/Model/ISearchResult.php
  lib/public/HintException.php
  lib/public/LDAP/ILDAPProvider.php
  lib/public/Share_Backend.php
  lib/public/User/Events/UserLoggedInWithCookieEvent.php
  lib/public/Util.php
  lib/public/WorkflowEngine/IEntityEvent.php
Labels: 4. to release, technical debt

#38148 also show file etag in file info
  core/Command/Info/File.php
Labels: enhancement, 4. to release

#38147 Add `autocomplete` attrs to input fields
  apps/settings/src/components/PersonalInfo/DisplayNameSection.vue
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/LocationSection.vue
  apps/settings/src/components/PersonalInfo/OrganisationSection.vue
  apps/settings/src/components/PersonalInfo/PhoneSection.vue
  apps/settings/src/components/PersonalInfo/RoleSection.vue
  apps/settings/src/components/PersonalInfo/WebsiteSection.vue
  apps/settings/src/components/PersonalInfo/shared/AccountPropertySection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 4. to release

#38159 fix too dark or bright primary element color
  apps/theming/lib/Util.php
  apps/theming/tests/CapabilitiesTest.php
  apps/theming/tests/UtilTest.php
Labels: bug, design, 3. to review

#37734 feat(dav): expose system address book
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/CardDAV/AddressBookRoot.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/CardDAV/SystemAddressbook.php
  apps/dav/lib/CardDAV/UserAddressBooks.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CardDAV/SystemAddressBookTest.php
  apps/settings/templates/settings/admin/sharing.php
Labels: 4. to release, feature: carddav

#38218 chore: Update AUTHORS for Nextcloud 27
  AUTHORS
Labels: 3. to review

#38200 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 3. to review, technical debt

#37933 fix(contactsinteraction): Read, update or insert in DB transaction
  apps/contactsinteraction/lib/Listeners/ContactInteractionListener.php
Labels: bug, 4. to release, technical debt

#38139 27.0.0 beta 2
  version.php
Labels: 2. developing

#36592 fix default values and type hints for GroupManager::search
  lib/private/Group/Database.php
  lib/private/Group/Manager.php
  lib/public/GroupInterface.php
  lib/public/IGroupManager.php
Labels: bug, 4. to release

#38222 re-add version number
  version.php
Labels: 3. to review

#38208 [stable26] Fix redirect on unsupported browser warning
  core/src/views/UnsupportedBrowser.vue
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
Labels: bug, 3. to review

#37621 fix: Wrap filesystem LockedExceptions for holding the readable path
  lib/private/Files/Storage/Common.php
Labels: bug, 3. to review

#37709 fix: Check for wrapped retriable exceptions
  lib/private/DB/Exceptions/DbalException.php
  lib/private/Files/Cache/Propagator.php
Labels: bug, 3. to review

#38195 Update icewind/streams to 0.7.7 in files_external
  apps/files_external/3rdparty/autoload.php
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/ClassLoader.php
  apps/files_external/3rdparty/composer/InstalledVersions.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/composer/installed.php
  apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php
  apps/files_external/3rdparty/icewind/streams/src/CountWrapper.php
  apps/files_external/3rdparty/icewind/streams/src/DirectoryFilter.php
  apps/files_external/3rdparty/icewind/streams/src/DirectoryWrapper.php
  apps/files_external/3rdparty/icewind/streams/src/HashWrapper.php
  apps/files_external/3rdparty/icewind/streams/src/IteratorDirectory.php
  apps/files_external/3rdparty/icewind/streams/src/Wrapper.php
  apps/files_external/3rdparty/icewind/streams/src/WrapperHandler.php
Labels: 3. to review, technical debt

#38237 fix: Do not attempt to use l10n files as sources for combined js files
  lib/private/Template/JSResourceLocator.php
Labels: bug, 4. to release, high, regression

#38080 Add an occ command to scan files for legacy file key in use and get rid of those
  apps/encryption/appinfo/info.xml
  apps/encryption/composer/composer/autoload_classmap.php
  apps/encryption/composer/composer/autoload_static.php
  apps/encryption/composer/composer/installed.php
  apps/encryption/lib/Command/DropLegacyFileKey.php
  apps/encryption/lib/Command/ScanLegacyFormat.php
  apps/encryption/lib/Crypto/Encryption.php
Labels: enhancement, 3. to review

#38236 [stable25] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#38224 Check if version has entity before trying to access it
  apps/files_versions/lib/Storage.php
Labels: bug, 3. to review, backport-request

#32961 Make it easier to debug issue #32304
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/LazyUserFolder.php
Labels: 3. to review

#38242 Fix incosistent scrolling in Firefox
  apps/files/css/files.css
  apps/files/css/files.css.map
  apps/files/css/files.scss
  apps/files/css/merged.css
  apps/files/css/merged.css.map
Labels: bug, 3. to review, backport-request

#38247 fix(carddav): Mark system address book as read-only
  apps/dav/lib/CardDAV/SystemAddressbook.php
Labels: bug, 3. to review

#38196 Get rid of more int casts in file size manipulations
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/HomeCache.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
  lib/private/Files/Storage/DAV.php
  lib/private/Files/Storage/Local.php
Labels: bug, 3. to review, backport-request

#38256 Adjust file custom picker component padding
  apps/files/src/views/FileReferencePickerElement.vue
  dist/files-reference-files.js
  dist/files-reference-files.js.map
Labels: bug, design, 3. to review, backport-request

#38265 check the username when doing external storage session auth
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
Labels: 3. to review

#38281 [26] check the username when doing external storage session auth
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
Labels: 3. to review

#38282 [25] check the username when doing external storage session auth
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
Labels: 3. to review

#38283 [24] check the username when doing external storage session auth
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
Labels: 3. to review

#38284 [23] check the username when doing external storage session auth
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
Labels: 3. to review

#38286 [21] check the username when doing external storage session auth
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
Labels: 3. to review

#38287 [20] check the username when doing external storage session auth
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
Labels: 3. to review

#38202 Convert Add group link to button
  apps/settings/src/views/Users.vue
Labels: enhancement, accessibility

#38225 disable pull-down-to-refresh for mobile
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
Labels: enhancement, design, 3. to review

#38267 fix(lostpassword): Also rate limit the setPassword endpoint
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: bug, 3. to review

#38268 [stable26] fix(lostpassword): Also rate limit the setPassword endpoint
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: bug, 3. to review

#38269 [stable25] fix(lostpassword): Also rate limit the setPassword endpoint
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: bug, 3. to review

#38270 [stable24] fix(lostpassword): Also rate limit the setPassword endpoint
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: bug, 3. to review

#38271 [stable23] fix(lostpassword): Also rate limit the setPassword endpoint
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: bug, 3. to review

#38272 [stable22] fix(lostpassword): Also rate limit the setPassword endpoint
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: bug, 3. to review

#38212 [stable26] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#38293 fix(settings): Fix `UserList` styles set to css but scss is used
  apps/settings/src/components/UserList.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review

#38274 fix(middleware): Also abort the request when reaching max delay in af…
  lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php
  tests/lib/AppFramework/Middleware/Security/BruteForceMiddlewareTest.php
Labels: bug, 3. to review

#38065 fix(mimetype): Fix returning value when finding existing mimetype in MimeType Loader
  lib/private/Files/Type/Loader.php
Labels: bug, 3. to review

#38275 [stable26] fix(middleware): Also abort the request when reaching max delay in af…
  lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php
  tests/lib/AppFramework/Middleware/Security/BruteForceMiddlewareTest.php
Labels: bug, 3. to review

#38276 [stable25] fix(middleware): Also abort the request when reaching max delay in af…
  lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php
  tests/lib/AppFramework/Middleware/Security/BruteForceMiddlewareTest.php
Labels: bug, 3. to review

#38277 [stable24] fix(middleware): Also abort the request when reaching max delay in af…
  lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php
  tests/lib/AppFramework/Middleware/Security/BruteForceMiddlewareTest.php
Labels: bug, 3. to review

#37965 fix(dav): Run system address book create-if-not-exists in transaction
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/tests/unit/CardDAV/SyncServiceTest.php
Labels: 4. to release, technical debt

#38278 [stable23] fix(middleware): Also abort the request when reaching max delay in af…
  lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php
  tests/lib/AppFramework/Middleware/Security/BruteForceMiddlewareTest.php
Labels: bug, 3. to review

#38279 [stable22] fix(middleware): Also abort the request when reaching max delay in af…
  lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php
  tests/lib/AppFramework/Middleware/Security/BruteForceMiddlewareTest.php
Labels: bug, 3. to review

#38280 [stable21] fix(middleware): Also abort the request when reaching max delay in af…
  lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php
  tests/lib/AppFramework/Middleware/Security/BruteForceMiddlewareTest.php
Labels: bug, 3. to review

#38143 Fix generated avatars cache
  lib/private/Avatar/AvatarManager.php
  lib/private/Repair/ClearGeneratedAvatarCache.php
  tests/lib/Repair/ClearGeneratedAvatarCacheTest.php
Labels: bug, 3. to review, backport-request

#38030 Wrapper method to easily retry deadlock exceptions
  lib/public/AppFramework/Db/TTransactional.php
Labels: enhancement, 3. to review, pending documentation

#38205 Add css variables for info colors (`--color-info`)
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: enhancement, design, 4. to release

#37326 feat(CardDAV): Add Sabre\DAV\IMoveTarget support to OCA\DAV\CardDAV\AddressBook
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CardDAV/AddressBook.php
  apps/dav/lib/CardDAV/Card.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Events/CardMovedEvent.php
  apps/dav/tests/unit/CardDAV/AddressBookTest.php
  build/psalm-baseline.xml
Labels: 4. to release, feature: carddav

#38115 Rename `numericStorageId` to `numericExternalStorageId` in PersonalMount.php
  apps/files_external/lib/Lib/PersonalMount.php
Labels: bug, 3. to review, backport-request

#38321 docs: add dbtableprefix to sample config
  config/config.sample.php
Labels: 3. to review

#31001 Fixed 'overwritewebroot' not work with 'overwritecondaddr'.
  lib/base.php
Labels: 3. to review

#38131 fix(login): Make login form and footer look like a dashboard panel
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/guest.css
  core/css/guest.css.map
  core/css/guest.scss
  core/css/server.css
  core/css/server.css.map
  core/src/views/Login.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: design, 4. to release, accessibility

#36692 fix(preview-generator): Throw exception before dividing by zero when generating previews
  lib/private/Preview/Generator.php
Labels: bug, 3. to review, feature: previews and thumbnails

#37720 [stable25] Fix button text
  apps/federatedfilesharing/js/external.js
Labels: 4. to release

#38327 dashboard: Adjust border radius of panels to match main content container
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: enhancement, design, 3. to review

#38328 Fix codeowners named Χριστόφορος
  .github/CODEOWNERS
Labels: 3. to review

#38337 disable contacts menu features that regularly fail on drone
  build/integration/features/contacts-menu.feature
Labels: 3. to review, integration

#38248 [stable26] fix(carddav): Mark system address book as read-only
  apps/dav/lib/CardDAV/SystemAddressbook.php
Labels: bug, 3. to review, feature: carddav

#38074 [stable25] Add required accessibility attributes to legacy files navigation
  apps/files/src/files-app-settings.js
  apps/files/templates/appnavigation.php
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, accessibility

#38341 27.0.0 RC1
  version.php
Labels: 3. to review

#38336 Master is now 28
  .github/dependabot.yml
  .github/workflows/update-cacert-bundle.yml
  .github/workflows/update-psalm-baseline.yml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/settings/lib/WellKnown/SecurityTxtHandler.php
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 3. to review

#38307 [stable26] SystemTags endpoint to return tags used by a user with meta data
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/SystemTag/SystemTagNode.php
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  apps/dav/lib/SystemTag/SystemTagsInUseCollection.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Node/Folder.php
  lib/private/SystemTag/SystemTagsInFilesDetector.php
Labels: 3. to review

#38309 [stable25] SystemTags endpoint to return tags used by a user with meta data
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/SystemTag/SystemTagNode.php
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  apps/dav/lib/SystemTag/SystemTagsInUseCollection.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Node/Folder.php
  lib/private/SystemTag/SystemTagsInFilesDetector.php
Labels: 3. to review

#38314 26.0.2 RC1
  version.php
Labels: 3. to review

#38294 Use aria-expanded correctly on toggle user actions
  apps/settings/src/components/UserList/UserRow.vue
  apps/settings/src/components/UserList/UserRowSimple.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, backport-request, accessibility

#38344 38340 fix add group broken
  apps/settings/src/views/Users.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, backport-request, feature: users and groups, regression

#38332 Remove some dead code in files app
  apps/files/js/app.js
Labels: 3. to review, technical debt, javascript

#37758 redis: use atomic operations everywhere
  lib/private/Memcache/Redis.php
  tests/lib/Memcache/RedisTest.php
Labels: 3. to review, feature: caching, performance 🚀

#38354 Make unsupported browser check asynchronous
  core/src/unsupported-browser-redirect.js
  dist/9551-9551.js
  dist/9551-9551.js.LICENSE.txt
  dist/9551-9551.js.map
  dist/core-unsupported-browser-redirect.js
  dist/core-unsupported-browser-redirect.js.LICENSE.txt
  dist/core-unsupported-browser-redirect.js.map
Labels: 3. to review, javascript, performance 🚀

#38227 Allow enforcing share passwords only when already asking for a password
  apps/settings/src/admin.js
  apps/settings/templates/settings/admin/sharing.php
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: bug, 3. to review, feature: settings

#38164 Show pending popover menu when password is enabled by default
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#38162 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#38291 fix loading custom logo image
  apps/theming/lib/Util.php
  apps/theming/tests/IconBuilderTest.php
  apps/theming/tests/UtilTest.php
Labels: 4. to release, backport-request

#38259 reload filelist when adding or removing shares
  apps/files/js/filelist.js
  apps/files_sharing/src/mixins/ShareRequests.js
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review

#38365 add imaginary_key
  config/config.sample.php
  lib/private/Preview/Imaginary.php
Labels: enhancement, 3. to review

#38400 Remove deprecated `OC.appSettings` API
  core/src/OC/appsettings.js
  core/src/OC/index.js
  dist/core-login.js
  dist/core-login.js.LICENSE.txt
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.LICENSE.txt
  dist/core-main.js.map
Labels: 3. to review, technical debt

#38393 bug-report-template - move `Official All-in-One appliance` to the bottom
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 3. to review

#38308 fix(carddav): Check if SERVER variables are set before accessing them
  apps/dav/lib/CardDAV/SystemAddressbook.php
Labels: bug, 4. to release, backport-request, feature: carddav

#38075 Add label to "default quota" multiselect
  apps/settings/src/views/Users.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review

#38413 fix(SAB): Save avatar to SAB
  apps/dav/lib/CardDAV/Converter.php
Labels: bug, 3. to review, feature: dav, backport-request, regression, feature: carddav

#37665 Refactors Command/Encryption/Enable.php to improve code readability.
  core/Command/Encryption/Enable.php
Labels: 4. to release

#36316 Log to `error_log` in fatal case
  lib/private/Log.php
Labels: 3. to review
