Repository nextcloud/server, pull requests merged in 2023-12, with the labels that each got.

#41931 techdebt(Middleware): Add more specific array types so its clickable in IDEs
  lib/private/AppFramework/Middleware/MiddlewareDispatcher.php
Labels: 4. to release, technical debt

#41957 feat(out-of-office): Add OCS endpoint to set and clear absence
  apps/dav/appinfo/routes.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Controller/AvailabilitySettingsController.php
  apps/dav/lib/Controller/OutOfOfficeController.php
  apps/dav/openapi.json
  apps/dav/src/components/AbsenceForm.vue
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
Labels: enhancement, 3. to review, feature: dav, pending documentation

#41960 fix(CI): Fix video verification tests
  .drone.yml
Labels: bug, 3. to review

#41958 fix(cypress): Adjust user columns tests
  cypress/e2e/settings/users_columns.cy.ts
Labels: bug, 3. to review, tests

#40169 enh(settings): Load from disabled users endpoint
  apps/settings/src/components/UserList.vue
  apps/settings/src/store/users.js
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
  lib/public/User/Backend/IProvideEnabledStateBackend.php
Labels: bug, 4. to release, backport-request, feature: users and groups

#41951 fix(files): Remove confusing table header labels
  apps/files/src/components/FilesListTableHeaderButton.vue
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, accessibility, files2vue

#41953 fix(files): Move aria-label for favorite icon from span to icon
  apps/files/src/components/FileEntry/FavoriteIcon.vue
  apps/files/src/components/FileEntry/FileEntryPreview.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, accessibility, files2vue

#41967 [stable28] fix(dav): Allow single-day out of office
  apps/dav/src/components/AbsenceForm.vue
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
Labels: bug, 3. to review, feature: dav, feature: caldav

#41971 feat(Updater/Admin): Clarify instructions for `upgrade.disable-web` to avoid confusion/reduce help requests/help downstream Docker image maintainers
  apps/updatenotification/src/components/UpdateNotification.vue
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
Labels: enhancement, 3. to review, feature: install and update

#41995 fix(TemplateManager): Bail early if templatedirectory is empty
  lib/private/Files/Template/TemplateManager.php
Labels: bug, 3. to review, backport-request, feature: templates

#41999 fix(security): Handle idn_to_utf8 returning false
  lib/private/Security/RemoteHostValidator.php
  tests/lib/Http/Client/ClientTest.php
  tests/lib/Security/RemoteHostValidatorTest.php
Labels: 4. to release, backport-request, security

#41997 [stable27] Fix/text processing types covariant stable27
  lib/public/TextProcessing/IProvider.php
  lib/public/TextProcessing/Task.php
Labels: 3. to review

#42004 fix(security): Update expiration date in security.txt
  apps/settings/lib/WellKnown/SecurityTxtHandler.php
Labels: 3. to review, backport-request

#42006 fix: Properly take show_hidden user setting into account for file listing
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request

#42019 +files_metadata_installed
  lib/private/FilesMetadata/FilesMetadataManager.php
Labels: 3. to review, high, backport-request, 28-feedback

#41962 fix(dav): Make current ooo info time-dependent
  apps/dav/appinfo/routes.php
  apps/dav/lib/Controller/OutOfOfficeController.php
  apps/dav/lib/ResponseDefinitions.php
  apps/dav/lib/Service/AbsenceService.php
  apps/dav/openapi.json
  lib/private/User/OutOfOfficeData.php
  lib/public/User/IOutOfOfficeData.php
Labels: bug, 4. to release, feature: dav, backport-request

#41993 fix(UnifiedSearch): Move headings out of list element (invalid HTML)
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  tsconfig.json
Labels: bug, 3. to review, backport-request, feature: search, accessibility

#41927 perf: Use more performant way to obtain and check the email as a login name with token login
  core/Application.php
  core/Migrations/Version13000Date20170718121200.php
  lib/private/AllConfig.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 2. developing, feature: authentication, performance 🚀

#41970 [stable27] fix: Show error message when CSRF check fails at login
  core/Controller/LoginController.php
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
  lib/private/Authentication/Login/LoginResult.php
Labels: bug, 3. to review, feature: authentication

#41991 [stable28] fix(files): Remove confusing table header labels
  apps/files/src/components/FilesListTableHeaderButton.vue
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files, files2vue

#41984 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#41994 fix(UnifiedSearch): Show translated text for filter label
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: bug, 3. to review, feature: search

#41989 [stable28] fix(files): Reverse logic to prevent copy to itself
  apps/files/src/actions/moveOrCopyAction.ts
  cypress/e2e/files/files_copy-move.cy.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files, files2vue

#42001 fix(dav): Improve handling and logging of bulk upload failures
  apps/dav/lib/BulkUpload/BulkUploadPlugin.php
  apps/dav/lib/BulkUpload/MultipartRequestParser.php
  apps/dav/tests/unit/Files/MultipartRequestParserTest.php
Labels: bug, 3. to review, feature: dav, backport-request

#42031 fix look of personal global credentials settings
  apps/files_external/css/settings.css
  apps/files_external/css/settings.css.map
  apps/files_external/css/settings.scss
  apps/files_external/templates/settings.php
Labels: enhancement, design, 3. to review, backport-request

#41813 [stable27] feat(LDAP): implement IIsAdmin interface
  apps/user_ldap/appinfo/info.xml
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Command/PromoteGroup.php
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Group_Proxy.php
  build/integration/ldap_features/openldap-numerical-id.feature
Labels: enhancement, 3. to review, feature: ldap

#42023 [stable28] fix: Properly take show_hidden user setting into account for file listing
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#42021 fix: Also filter out undefined entries from the file list
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request

#42033 perf: Only query the db once for trusted servers
  apps/federation/lib/TrustedServers.php
Labels: 3. to review, performance 🚀

#41976 [stable28] fix(files): Adjust table header to look like on previous versions
  apps/files/src/components/FilesListTableHeader.vue
  apps/files/src/components/FilesListTableHeaderButton.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files, files2vue, ❄️ 2023-Winter

#42011 fix(metadata): Fix copy-paste doc block throws
  lib/public/FilesMetadata/IFilesMetadataManager.php
Labels: bug, 3. to review

#42044 Fix AppSettingsController.php overwriting currentLanguage
  apps/settings/lib/Controller/AppSettingsController.php
Labels: bug, 3. to review

#41949 [stable28] enh(settings): Load from disabled users endpoint
  apps/settings/src/components/UserList.vue
  apps/settings/src/store/users.js
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
  lib/public/User/Backend/IProvideEnabledStateBackend.php
Labels: bug, 3. to review

#41948 fix(theming): Adjust dark theme to be accessible adjust cypress tests
  apps/theming/__tests__/accessibility.cy.ts
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  cypress/e2e/theming/a11y-color-contrast.cy.ts
  cypress/support/e2e.ts
Labels: bug, 3. to review, backport-request, feature: theming, accessibility

#41975 fix(files): Correctly handle dropping folders on file list
  apps/files/src/components/DragAndDropNotice.vue
  apps/files/src/services/DropService.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, files2vue

#42061 Revert "perf: Add partial index on configvalue of preferences table"
  core/Application.php
  core/Migrations/Version13000Date20170718121200.php
Labels: bug, 3. to review

#42066 fix(cypress): Wait for network requests to finish when using the FilePicker
  cypress/e2e/files/files_copy-move.cy.ts
Labels: 4. to release, feature: files, tests

#42062 Correct semantics for link opening in global search
  core/src/components/GlobalSearch/SearchResult.vue
  dist/core-global-search.js
  dist/core-global-search.js.map
Labels: enhancement, 3. to review, backport-request, feature: search

#42080 [stable26] fix(systemreport): Mask onlyoffice secret as sensitive
  lib/private/SystemConfig.php
Labels: bug, 3. to review

#42077 enh(a11y): Add navigation labels
  apps/files/src/views/Navigation.vue
  apps/settings/src/views/Apps.vue
  apps/settings/src/views/Users.vue
  dist/files-main.js
  dist/files-main.js.map
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, backport-request, accessibility

#42078 [stable27] fix(updatecheck): Don't wait 120s for a response of updater.nextcloud…
  lib/private/Updater/VersionCheck.php
Labels: bug, 3. to review

#42063 [stable27] Fix AppSettingsController.php overwriting currentLanguage
  apps/settings/lib/Controller/AppSettingsController.php
Labels: 3. to review

#42082 [stable28] fix(bruteforce-protection): Don't throw a 500 when MaxDelayReached is…
  index.php
  ocs/v1.php
Labels: bug, 3. to review

#42084 [stable26] fix(bruteforce-protection): Don't throw a 500 when MaxDelayReached is…
  index.php
  ocs/v1.php
Labels: bug, 3. to review

#42087 [stable28] fix(dav): Improve handling and logging of bulk upload failures
  apps/dav/lib/BulkUpload/BulkUploadPlugin.php
  apps/dav/lib/BulkUpload/MultipartRequestParser.php
  apps/dav/tests/unit/Files/MultipartRequestParserTest.php
Labels: bug, 3. to review, feature: dav

#42016 26.0.10 RC1
  version.php
Labels: 3. to review

#41983 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#42105 [stable28] Change global search UI text to unified search
  core/src/views/GlobalSearch.vue
  core/src/views/GlobalSearchModal.vue
  dist/core-global-search.js
  dist/core-global-search.js.map
Labels: 3. to review, feature: search

#42101 Change global search UI text to unified search
  core/src/views/GlobalSearch.vue
  core/src/views/GlobalSearchModal.vue
  dist/core-global-search.js
  dist/core-global-search.js.map
Labels: 3. to review, feature: search

#42103 [stable28] fix: Adjust reference picker code for the vue based FilePicker
  apps/files/src/views/FileReferencePickerElement.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  dist/files-reference-files.js
  dist/files-reference-files.js.LICENSE.txt
  dist/files-reference-files.js.map
  dist/files_sharing-personal-settings.js
  dist/files_sharing-personal-settings.js.map
  dist/settings-vue-settings-admin-security.js
  dist/settings-vue-settings-admin-security.js.map
  dist/sharebymail-vue-settings-admin-sharebymail.js
  dist/sharebymail-vue-settings-admin-sharebymail.js.map
Labels: bug, 3. to review, feature: filepicker, regression

#41966 28.0.0 RC3
  version.php
Labels: 3. to review, overview

#42100 fix(core): add translations on the login page
  core/Listener/BeforeTemplateRenderedListener.php
Labels: bug, 3. to review, backport-request, feature: language l10n and translations, feature: logging, accessibility

#42115 chore(deps): Update openapi-extractor
  apps/dashboard/openapi.json
  apps/files_sharing/openapi.json
  apps/theming/openapi.json
  core/openapi.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request, feature: dependencies

#42093 fix(l10n): fix translations for init scripts
  lib/public/Util.php
Labels: bug, 3. to review, backport-request, regression

#42112 enh(settings): Set main page heading
  apps/settings/src/constants/AppsConstants.js
  apps/settings/src/mixins/AppManagement.js
  apps/settings/src/views/Apps.vue
  apps/settings/src/views/Users.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, backport-request, feature: users and groups, feature: apps management, accessibility

#42111 fix(a11y): Unified search headings
  core/src/views/GlobalSearchModal.vue
  dist/core-global-search.js
  dist/core-global-search.js.map
Labels: 3. to review, backport-request, feature: search, accessibility

#42144 fix(caldav): don't reuse query builder objects
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: bug, 3. to review, backport-request

#41535 Merge sqlite check to database check
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/SupportedDatabase.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  apps/settings/tests/SetupChecks/SupportedDatabaseTest.php
  core/js/setupchecks.js
Labels: 3. to review

#42154 fix rename on live photos
  apps/files/lib/Listener/SyncLivePhotosListener.php
Labels: backport-request

#42151 chore(dav): Remove dead \OCA\DAV\Server::getSabreServer
  apps/dav/lib/Server.php
Labels: 3. to review, technical debt

#42142 fix(dav): Prevent out-of-office event time drifts
  apps/dav/lib/Listener/OutOfOfficeListener.php
  apps/dav/tests/unit/Listener/OutOfOfficeListenerTest.php
Labels: bug, 4. to release, feature: dav, backport-request, feature: caldav

#42146 28.0.0
  version.php
Labels: 3. to review

#41670 fix(papercut) - rerendered submenu actions for time sensitive actions
  apps/files_reminders/src/actions/setReminderSuggestionActions.ts
  dist/files_reminders-init.js
  dist/files_reminders-init.js.map
Labels: enhancement, 4. to release, papercut, feature: activity and notification, Nice to have

#42165 chore(deps): Bump @nextcloud/upload from 1.0.2 to 1.0.3
  dist/4454-4454.js
  dist/4454-4454.js.map
  dist/6713-6713.js
  dist/6713-6713.js.LICENSE.txt
  dist/6713-6713.js.map
  dist/files-main.js
  dist/files-main.js.LICENSE.txt
  dist/files-main.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#42126 Tooltip outside click, should abort share creation
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  dist/3638-3638.js
  dist/3638-3638.js.LICENSE.txt
  dist/6326-6326.js
  dist/6326-6326.js.LICENSE.txt
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: enhancement, 3. to review, feature: sharing

#42094 Rename "global search" to "unified search"
  core/src/components/GlobalSearch/SearchResult.vue
  core/src/components/UnifiedSearch/CustomDateRangeModal.vue
  core/src/components/UnifiedSearch/LegacySearchResult.vue
  core/src/components/UnifiedSearch/SearchFilterChip.vue
  core/src/components/UnifiedSearch/SearchResult.vue
  core/src/components/UnifiedSearch/SearchableList.vue
  core/src/legacy-unified-search.js
  core/src/services/LegacyUnifiedSearchService.js
  core/src/services/UnifiedSearchService.js
  core/src/unified-search.js
  core/src/views/GlobalSearch.vue
  core/src/views/LegacyUnifiedSearch.vue
  core/src/views/UnifiedSearch.vue
  core/src/views/UnifiedSearchModal.vue
  core/templates/layout.user.php
  dist/core-global-search.js
  dist/core-global-search.js.LICENSE.txt
  dist/core-global-search.js.map
  dist/core-legacy-unified-search.js
  dist/core-legacy-unified-search.js.LICENSE.txt
  dist/core-legacy-unified-search.js.map
  dist/core-unified-search.js
  dist/core-unified-search.js.LICENSE.txt
  dist/core-unified-search.js.map
  dist/files_sharing-personal-settings.js
  dist/files_sharing-personal-settings.js.map
  dist/settings-vue-settings-admin-security.js
  dist/settings-vue-settings-admin-security.js.map
  dist/sharebymail-vue-settings-admin-sharebymail.js
  dist/sharebymail-vue-settings-admin-sharebymail.js.map
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
  lib/private/TemplateLayout.php
  webpack.modules.js
Labels: 3. to review, backport-request, feature: search

#42167 Unified search improvements
  core/src/components/UnifiedSearch/SearchableList.vue
  core/src/services/UnifiedSearchService.js
  core/src/views/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 3. to review, feature: search

#42064 feat(settings): add occ commands to handle admin delegation
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Command/AdminDelegation/Add.php
  apps/settings/lib/Command/AdminDelegation/Remove.php
  apps/settings/lib/Command/AdminDelegation/Show.php
Labels: 3. to review, feature: settings, pending documentation

#42174 chore(comments): Drop dead code from comments app
  apps/comments/.bowerrc
  apps/comments/.l10nignore
  apps/comments/lib/Listener/LoadAdditionalScripts.php
  apps/comments/lib/Listener/LoadSidebarScripts.php
  apps/comments/src/activitytabviewplugin.js
  apps/comments/src/app.js
  apps/comments/src/comments.js
  apps/comments/src/templates.js
  apps/comments/src/templates/filesplugin.handlebars
  apps/comments/src/utils/numberUtil.js
  dist/comments-comments.js
  dist/comments-comments.js.LICENSE.txt
  dist/comments-comments.js.map
  webpack.modules.js
Labels: 3. to review, technical debt

#42198 Wrap metadata generation in try/catch
  core/BackgroundJobs/GenerateMetadataJob.php
Labels: bug, 3. to review, backport-request, php

#42183 fix(UnifiedSearch): Remove title prop from modal
  core/src/views/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: bug, 3. to review, backport-request, feature: search

#42095 fix(files): navigation exact
  apps/files/src/views/Navigation.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files

#42242 fix(files): Do not add drag handlers on rename
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntry/FileEntryName.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, files2vue

#42187 [master] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#42189 [stable26] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#42188 [stable27] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#42191 [stable24] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#42190 [stable28] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#42192 [stable23] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#42193 [stable25] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#42194 [stable22] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#41092 [stable25] Fix: non responsive app navigation toggle
  core/src/init.js
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, help wanted, 4. to release

#42124 feat(files): add batch support to copy-move
  apps/files/src/actions/moveOrCopyAction.ts
  apps/files/src/actions/moveOrCopyActionUtils.ts
  apps/files/src/init-templates.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: 4. to release, backport-request, feature: files, regression

#42147 27.1.5
  version.php
Labels: 3. to review

#42148 26.0.10
  version.php
Labels: 3. to review

#42205 Translate me-text in unified search people filter
  core/src/services/UnifiedSearchService.js
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 3. to review, feature: search

#42279 [stable28] feat(files): add batch support to copy-move
  apps/files/src/actions/moveOrCopyAction.ts
  apps/files/src/actions/moveOrCopyActionUtils.ts
  apps/files/src/init-templates.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, regression

#42201 [stable28] feat(settings): add occ commands to handle admin delegation
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Command/AdminDelegation/Add.php
  apps/settings/lib/Command/AdminDelegation/Remove.php
  apps/settings/lib/Command/AdminDelegation/Show.php
Labels: 3. to review, feature: settings

#42186 fix(files): Partly revert 32c1aeb and show correct quota again
  apps/files/src/components/NavigationQuota.vue
  apps/files/src/views/Navigation.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, regression

#42290 fix(dashboard): changed h3 elements to h2
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: 3. to review

#42132 enh(oauth2): allowed toggling of aria label
  apps/oauth2/src/components/OAuthItem.vue
  dist/oauth2-oauth2.js
  dist/oauth2-oauth2.js.map
Labels: bug, 3. to review, backport-request, feature: settings, accessibility

#42209 feat(comments): Add a meta data column for comments
  apps/dav/tests/unit/Comments/CommentsNodeTest.php
  core/Application.php
  core/Migrations/Version29000Date20231213104850.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Comments/Comment.php
  lib/private/Comments/Manager.php
  lib/public/Comments/IComment.php
  tests/lib/Comments/CommentTest.php
  tests/lib/Comments/ManagerTest.php
  version.php
Labels: enhancement, 3. to review, feature: comments, pending documentation

#42281 fix(files): fix download file encoded source
  apps/files/src/actions/downloadAction.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 2. developing, backport-request, regression

#42293 [stable28] fix(files): Partly revert 32c1aeb and show correct quota again
  apps/files/src/components/NavigationQuota.vue
  apps/files/src/views/Navigation.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, regression

#42311 [stable28] chore(deps): Bump @nextcloud/upload to 1.0.4
  dist/3338-3338.js
  dist/3338-3338.js.LICENSE.txt
  dist/3338-3338.js.map
  dist/4454-4454.js
  dist/4454-4454.js.map
  dist/files-main.js
  dist/files-main.js.LICENSE.txt
  dist/files-main.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#42307 28.0.1 RC1
  version.php
Labels: 3. to review

#42109 Clean-up and standardization of "App password"
  core/templates/loginflow/authpicker.php
  core/templates/loginflowv2/authpicker.php
Labels: bug, 3. to review, feature: language l10n and translations

#42305 fix(joblist): also reset last_run timestamp on updating an existing job
  lib/private/BackgroundJob/JobList.php
Labels: bug, 3. to review

#42304 fix(ooo): add new ooo status with new emoji
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
  apps/dav/tests/unit/BackgroundJob/UserStatusAutomationTest.php
  apps/user_status/lib/Listener/OutOfOfficeStatusListener.php
  apps/user_status/lib/Service/PredefinedStatusService.php
  apps/user_status/tests/Unit/Service/PredefinedStatusServiceTest.php
  lib/public/UserStatus/IUserStatus.php
Labels: backport-request

#42241 feat(setupcheck): Add setup check for maintenance_window_start config
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/SetupChecks/MaintenanceWindowStart.php
Labels: enhancement, 3. to review, backport-request

#42184 enh(UnifiedSearch): Keep the searchbar on top of the modal
  core/src/views/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  package-lock.json
  package.json
Labels: bug, design, feature: search

#42350 Don't query oc_properties for metadata props
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: 3. to review, backport-request, performance 🚀

#42287 fix(theming): Adjust status colors and make dark theme fully accessible
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
  apps/theming/tests/Themes/DarkThemeTest.php
Labels: bug, 3. to review, backport-request, feature: theming, accessibility

#42361 fix(manager): removed dead code
  lib/private/Share20/Manager.php
Labels: enhancement, 3. to review

#42353 Add global accessibility switch
  apps/files/src/views/FilesList.vue
  config/config.sample.php
  dist/files-main.js
  dist/files-main.js.map
  lib/private/Template/JSConfigHelper.php
  lib/private/TemplateLayout.php
Labels: 3. to review, backport-request, accessibility

#42339 fix(dav): allow multiple organizers if possible
  apps/dav/lib/CalDAV/Schedule/Plugin.php
Labels: bug, 3. to review, feature: dav, backport-request, feature: caldav

#42349 Use FileInfo's metadata for hidden prop
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
Labels: 3. to review, backport-request, performance 🚀

#41087 enh(SpeechToText): Allow providers to declare a dynamic ID instead of using className
  apps/settings/lib/Settings/Admin/ArtificialIntelligence.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/SpeechToText/SpeechToTextManager.php
  lib/public/SpeechToText/ISpeechToTextProviderWithId.php
Labels: 3. to review

#42309 fix(userstatus): set user status to 'In a meeting' if calendar is busy
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/Status/Status.php
  apps/dav/lib/CalDAV/Status/StatusService.php
  apps/dav/tests/unit/CalDAV/Status/StatusServiceTest.php
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/lib/Listener/UserLiveStatusListener.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/tests/Unit/Controller/UserStatusControllerTest.php
  apps/user_status/tests/Unit/Listener/UserLiveStatusListenerTest.php
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
Labels: 4. to release, backport-request, feature: status

#42329 fix(theming): Adjust dark high contrast to fulfill WCAG 2.1 AAA contrast
  apps/theming/css/default.css
  apps/theming/lib/Themes/CommonThemeTrait.php
  apps/theming/lib/Themes/DarkHighContrastTheme.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Util.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
  apps/theming/tests/Themes/DarkHighContrastThemeTest.php
Labels: bug, 3. to review, backport-request, feature: theming, accessibility

#42298 Don't write back .htaccess file on a RO filesystem
  lib/private/Setup.php
Labels: 3. to review

#42140 Update crl after revoke rides.csr
  resources/codesigning/root.crl
Labels: 3. to review

#42399 [stable27] Update crl after revoke rides.csr
  resources/codesigning/root.crl
Labels: 4. to release

#42398 [stable26] Update crl after revoke rides.csr
  resources/codesigning/root.crl
Labels: 4. to release

#42401 fix: Ensure app menu entries and dashboard welcome message have enough contrast
  apps/dashboard/src/DashboardApp.vue
  core/src/components/AppMenu.vue
  dist/core-main.js
  dist/core-main.js.map
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: bug, 3. to review, backport-request, accessibility

#42366 fix(files): drag and drop
  apps/files/src/components/DragAndDropNotice.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/services/DropService.ts
  dist/files-main.js
  dist/files-main.js.LICENSE.txt
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files

#42406 fix(dav): Hide less than minute diff in calendar notification title
  apps/dav/lib/CalDAV/Reminder/Notifier.php
Labels: bug, 3. to review, feature: dav, backport-request, feature: activity and notification

#42381 enh(dashboard): changed h1 to say Dashboard instead of Nextcloud
  apps/dashboard/lib/Controller/DashboardController.php
Labels: 3. to review, backport-request, accessibility

#42422 fix(dav): undeclared `$cache` property
  apps/dav/tests/unit/CalDAV/Status/StatusServiceTest.php
Labels: bug, 3. to review, feature: dav, backport-request

#42419 fix(files): Adjust ID for skip content buttons
  apps/files/lib/Controller/ViewController.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: bug, 3. to review, backport-request, feature: files, accessibility

#42417 28.0.1
  version.php
Labels: 4. to release

#42334 enh(settings): Refactor UI for session and app token management
  apps/settings/src/components/AuthToken.vue
  apps/settings/src/components/AuthTokenList.vue
  apps/settings/src/components/AuthTokenSection.vue
  apps/settings/src/components/AuthTokenSetup.vue
  apps/settings/src/components/AuthTokenSetupDialog.vue
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  apps/settings/src/main-personal-security.js
  apps/settings/src/store/authtoken.ts
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.LICENSE.txt
  dist/settings-vue-settings-personal-security.js.map
  package-lock.json
  package.json
Labels: bug, 3. to review, feature: settings

#42389 fix(cron): Reset the reserved_at when force executing from CLI
  lib/private/BackgroundJob/JobList.php
Labels: bug, 3. to review

#42424 fix(theming): Add adjusted color versions of default background
  apps/theming/img/background/kamil-porembinski-clouds.jpg
  apps/theming/img/background/preview/kamil-porembinski-clouds.jpg
Labels: 3. to review, backport-request, feature: theming, accessibility

#42369 [stable28] fix(theming): Adjust theming util to calculate primary element color based on WCAG color contrast
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
  apps/theming/tests/Themes/DarkThemeTest.php
Labels: bug, 3. to review, feature: theming, accessibility

#42292 fix(a11y): Unified search headings the sequel
  core/src/views/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: bug, 3. to review, backport-request, feature: search, accessibility

#42415 enh(files): added ability to escape out of all selection when focused
  apps/files/src/components/FileEntry/FileEntryCheckbox.vue
  apps/files/src/components/FilesListTableHeader.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, backport-request, feature: files, accessibility, files2vue

#42439 fix(theming): Invert filter should be based on primary-element
  apps/theming/lib/Themes/CommonThemeTrait.php
Labels: 3. to review, backport-request, feature: theming, accessibility

#42405 fix(LDAP): ensure stored groups are formatted as simple list
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/tests/Group_LDAPTest.php
Labels: bug, 3. to review, feature: ldap, backport-request

#37469 restore shared lock ttl to previous value when releasing
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/Memcache/LoggerWrapperCache.php
  lib/private/Memcache/ProfilerWrapperCache.php
  lib/private/Memcache/Redis.php
  lib/private/Server.php
  lib/public/IMemcacheTTL.php
  tests/lib/Lock/MemcacheLockingProviderTest.php
  tests/lib/Memcache/RedisTest.php
Labels: bug, 4. to release, backport-request

#42442 fix: Adjust focus-visible marker on appmenu
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review, backport-request, accessibility

#42319 fix(settings): Use heading for Profile and Profile picture sections
  apps/settings/src/components/PersonalInfo/AvatarSection.vue
  apps/settings/src/components/PersonalInfo/ProfileSection/ProfileSection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 3. to review, backport-request, accessibility

#42379 enh(breadcrumbs): removed unnecessary aria label
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, backport-request, accessibility

#42409 [stable28] fix(files): drag and drop
  apps/files/src/components/DragAndDropNotice.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/services/DropService.ts
  dist/files-main.js
  dist/files-main.js.LICENSE.txt
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#42452 fix(files): allow silent batch actions errors
  apps/files/src/components/FilesListTableHeaderActions.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 4. to release, backport-request, feature: files, technical debt

#42432 [stable28] Backport unified search improvments
  core/src/components/UnifiedSearch/SearchableList.vue
  core/src/services/UnifiedSearchService.js
  core/src/views/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: bug, 3. to review, ❄️ 2023-Winter

#42438 fix(theming): Adjust high contrast theme to fulfill WCAG AAA text contrast
  apps/theming/lib/Themes/HighContrastTheme.php
  apps/theming/tests/Themes/HighContrastThemeTest.php
Labels: 4. to release, backport-request, accessibility

#42457 fix(files): Allow Ctrl/Command click on file entries to open in a new tab
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntryGrid.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request

#42490 [stable28] fix(files): allow silent batch actions errors
  apps/files/src/components/FilesListTableHeaderActions.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, technical debt

#42435 [stable28] enh(files): added ability to escape out of all selection when focused
  apps/files/src/components/FileEntry/FileEntryCheckbox.vue
  apps/files/src/components/FilesListTableHeader.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 4. to release, feature: files

#41998 enh: Implement PrimaryReadReplicaConnection
  config/config.sample.php
  lib/private/DB/Connection.php
  lib/private/DB/ConnectionFactory.php
  lib/private/DB/SetTransactionIsolationLevel.php
  lib/private/Server.php
  lib/private/Setup/AbstractDatabase.php
Labels: enhancement, 3. to review, pending documentation, performance 🚀

#42487 [stable28] enh(breadcrumbs): removed unnecessary aria label
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 3. to review, low, feature: files

#42504 fix: Avoid using replicas during setup
  lib/private/Setup/AbstractDatabase.php
Labels: bug, 3. to review

#42495 [stable28] fix(settings): Use heading for Profile and Profile picture sections
  apps/settings/src/components/PersonalInfo/AvatarSection.vue
  apps/settings/src/components/PersonalInfo/ProfileSection/ProfileSection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 4. to release

#42479 AppAPI: allow to bypass Two-Factor
  core/Middleware/TwoFactorMiddleware.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  tests/lib/Authentication/TwoFactorAuth/ManagerTest.php
Labels: bug, 3. to review, backport-request

#41479 [stable27] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#41914 only do a multipart s3 copy when above the regular copy limit
  apps/files_external/tests/Storage/Amazons3MultiPartTest.php
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
Labels: 3. to review, backport-request, pending documentation

#26540 Cast datetime columns in sqlite before comparing
  lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/SqliteExpressionBuilder.php
  tests/lib/DB/QueryBuilder/ExpressionBuilderDBTest.php
Labels: enhancement, 3. to review

#42427 fix(ViewController): Properly handle non-existent fileIds (regression lead to 500 errors)
  apps/files/lib/Controller/ViewController.php
Labels: bug, 3. to review, backport-request, feature: files, regression
