Repository nextcloud/server, pull requests merged in 2023-07, with the labels that each got.

#39093 Silent `imagecreatefromstring()` errors
  lib/private/legacy/OC_Image.php
Labels: bug, 3. to review, backport-request

#39102 fix(settings): Migrate away from `NcAppNavigationCounter`
  apps/settings/src/components/GroupListItem.vue
  apps/settings/src/views/Apps.vue
  apps/settings/src/views/Users.vue
  dist/2246-2246.js
  dist/2246-2246.js.map
  dist/691-691.js
  dist/691-691.js.map
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-users-8351.js
  dist/settings-users-8351.js.LICENSE.txt
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, feature: settings

#34443 Add IProvideEnabledStateBackend interface
  apps/user_ldap/js/wizard/wizardTabAdvanced.js
  apps/user_ldap/lib/Configuration.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/User/DeletedUsersIndex.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/templates/settings.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestAttributeDetection.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestFetchUsersByLoginName.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestPaging.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserAvatar.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserCleanUp.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserDisplayName.php
  apps/user_ldap/tests/User_LDAPTest.php
  apps/user_ldap/tests/User_ProxyTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/User/User.php
  lib/public/User/Backend/IProvideEnabledStateBackend.php
Labels: enhancement, 3. to review, feature: ldap

#39096 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#39103 files_sharing: Remove orphaned file with deprecated imports
  apps/files_sharing/src/collaborationresources.js
Labels: 3. to review, feature: sharing

#39057 feat(ocp): More specific type for ICapabilities::getCapabilities
  apps/cloud_federation_api/lib/Capabilities.php
  apps/files/lib/Capabilities.php
  apps/files_sharing/lib/Capabilities.php
  apps/files_trashbin/lib/Capabilities.php
  apps/files_versions/lib/Capabilities.php
  apps/provisioning_api/lib/Capabilities.php
  apps/theming/lib/Capabilities.php
  apps/user_status/lib/Capabilities.php
  apps/weather_status/lib/Capabilities.php
  lib/private/OCS/CoreCapabilities.php
  lib/public/Capabilities/ICapability.php
Labels: enhancement, 4. to release, integration

#39120 psalm: Disable cache
  composer.json
Labels: 3. to review, technical debt

#39055 [stable27] Adjust saving of status messages
  apps/user_status/src/components/CustomMessageInput.vue
  apps/user_status/src/components/SetStatusModal.vue
  apps/user_status/src/store/predefinedStatuses.js
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: bug, 3. to review, feature: status

#38969 enh(sab): Add profileUrl to SAB
  apps/dav/lib/CardDAV/Converter.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
Labels: enhancement, 4. to release, feature: dav, integration, feature: profile, feature: carddav

#39116 psalm: Enable more/less specific errors
  build/psalm-baseline.xml
  psalm.xml
Labels: 3. to review, technical debt

#39127 Fix password confirmation master
  core/src/OC/password-confirmation.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: backport-request

#38975 Uses PHP8's constructor property promotion in remaining /core classes
  core/BackgroundJobs/BackgroundCleanupUpdaterBackupsJob.php
  core/BackgroundJobs/CheckForUserCertificates.php
  core/BackgroundJobs/CleanupLoginFlowV2.php
  core/BackgroundJobs/LookupServerSendCheckBackgroundJob.php
  core/Data/LoginFlowV2Credentials.php
  core/Data/LoginFlowV2Tokens.php
  core/Db/LoginFlowV2Mapper.php
  core/Events/BeforePasswordResetEvent.php
  core/Events/PasswordResetEvent.php
  core/Middleware/TwoFactorMiddleware.php
  core/Notification/CoreNotifier.php
  core/Service/LoginFlowV2Service.php
  core/ajax/update.php
Labels: 3. to review, technical debt

#39115 fix(sse): don't update uncached files
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: bug, 3. to review, feature: encryption (server-side), backport-request

#39119 [stable27] Reduce load of files versions preview loading
  apps/files/src/models/Tab.js
  apps/files/src/views/Sidebar.vue
  apps/files_versions/lib/Sabre/Plugin.php
  apps/files_versions/lib/Sabre/VersionFile.php
  apps/files_versions/src/components/Version.vue
  apps/files_versions/src/files_versions_tab.js
  apps/files_versions/src/utils/davRequest.js
  apps/files_versions/src/utils/versions.js
  apps/files_versions/src/views/VersionTab.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: enhancement, 3. to review, feature: versions, javascript, php

#38959 [stable25] fix: BMP image without color info causes array access on `false`
  lib/private/legacy/OC_Image.php
Labels: bug, 3. to review

#39012 [2/3] Refactors lib/private/Security
  lib/private/Security/IdentityProof/Key.php
  lib/private/Security/IdentityProof/Manager.php
  lib/private/Security/IdentityProof/Signer.php
  lib/private/Security/RateLimiting/Backend/DatabaseBackend.php
  lib/private/Security/RateLimiting/Backend/IBackend.php
  lib/private/Security/RateLimiting/Backend/MemoryCacheBackend.php
  lib/private/Security/RateLimiting/Limiter.php
  lib/private/Security/VerificationToken/CleanUpJob.php
  lib/private/Security/VerificationToken/VerificationToken.php
Labels: 3. to review, technical debt

#39086 feat(admin_audit): Migrate to non-deprecated IEventDispatcher
  apps/admin_audit/lib/Actions/Security.php
  apps/admin_audit/lib/AppInfo/Application.php
  apps/admin_audit/tests/Actions/SecurityTest.php
  apps/dav/lib/HookManager.php
  apps/dav/tests/unit/DAV/HookManagerTest.php
  console.php
  lib/private/Console/Application.php
Labels: enhancement, 3. to review, feature: admin audit

#39043 fix(ocp): Fix reference of dashboard IAPIWidget::getItems from WidgetItem
  lib/public/Dashboard/Model/WidgetItem.php
Labels: bug, 3. to review, backport-request, feature: dashboard

#38955 fix(eventdispatcher): Don't use all evaluating "or"
  lib/private/EventDispatcher/EventDispatcher.php
Labels: 3. to review

#39062 fix(TagSearchProvider): Short circuit if no tag matches the query
  apps/systemtags/lib/Search/TagSearchProvider.php
Labels: bug, 3. to review, performance 🚀

#38978 Refactors lib/private/Accounts classes
  lib/private/Accounts/Account.php
  lib/private/Accounts/AccountManager.php
  lib/private/Accounts/AccountProperty.php
  lib/private/Accounts/AccountPropertyCollection.php
  lib/private/Accounts/Hooks.php
Labels: 4. to release, technical debt

#38176 Admin audit app: optimization according to PHP 8
  apps/admin_audit/lib/Actions/Action.php
  apps/admin_audit/lib/BackgroundJobs/Rotate.php
Labels: 4. to release, feature: admin audit, technical debt

#39164 Add OCSPreconditionFailedException
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/OCS/OCSPreconditionFailedException.php
Labels: enhancement, 3. to review, php

#39165 Enable all files_versions features when groupfolders is enabled
  apps/files_versions/lib/Capabilities.php
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: enhancement, 3. to review, backport-request, javascript, php

#39154 [stable25] fix: expect interface, not a specific implementation
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/Node.php
  lib/private/Files/Node/Root.php
  lib/private/SystemTag/SystemTagsInFilesDetector.php
  lib/public/Files/IRootFolder.php
  tests/lib/Files/Node/FolderTest.php
Labels: bug, 3. to review, regression

#38663 chore: Replace \OC::$server->query with \OCP\Server::get in /lib
  lib/private/Activity/Manager.php
  lib/private/Authentication/TwoFactorAuth/ProviderLoader.php
  lib/private/Collaboration/Resources/Listener.php
  lib/private/Console/Application.php
  lib/private/DB/MigrationService.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Node/Folder.php
  lib/private/Preview/WatcherConnector.php
  lib/private/Repair.php
  lib/private/Search/Provider/File.php
  lib/private/Session/Internal.php
  lib/private/Setup.php
  lib/private/TemplateLayout.php
  lib/private/User/Database.php
  lib/private/User/User.php
  lib/private/legacy/OC_App.php
  lib/private/legacy/OC_Files.php
  lib/private/legacy/OC_Template.php
  lib/private/legacy/template/functions.php
  lib/public/AppFramework/Http/Response.php
  lib/public/Util.php
Labels: 4. to release, technical debt

#39193 [stable27] fix(TagSearchProvider): Short circuit if no tag matches the query
  apps/systemtags/lib/Search/TagSearchProvider.php
Labels: 3. to review

#39194 [stable26] fix(TagSearchProvider): Short circuit if no tag matches the query
  apps/systemtags/lib/Search/TagSearchProvider.php
Labels: 3. to review

#39195 [stable25] fix(TagSearchProvider): Short circuit if no tag matches the query
  apps/systemtags/lib/Search/TagSearchProvider.php
Labels: 3. to review

#39200 fix: Remove deprecation warning for already removed API
  core/src/OCA/index.js
  core/src/OCA/search.js
  dist/core-login.js
  dist/core-login.js.LICENSE.txt
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.LICENSE.txt
  dist/core-main.js.map
Labels: 3. to review, javascript

#39203 fix(cypress): revert only toggle
  cypress/e2e/theming/admin-settings.cy.ts
Labels: 3. to review, backport-request, regression, technical debt

#39204 docs(dav): remove outdated comment
  apps/dav/lib/Connector/Sabre/FilesReportPlugin.php
Labels: 3. to review, technical debt

#38947 [stable27] fix(sab): put location in proper address field
  apps/dav/lib/CardDAV/Converter.php
  apps/settings/src/components/PersonalInfo/LocationSection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 4. to release, feature: dav, feature: carddav

#39257 comments: Add OpenAPI spec
  apps/comments/lib/Capabilities.php
  apps/comments/lib/Controller/NotificationsController.php
  apps/comments/openapi.json
Labels: 3. to review

#39170 add command do delete orphan shares
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Command/DeleteOrphanShares.php
  apps/files_sharing/lib/OrphanHelper.php
Labels: 3. to review, backport-request

#39252 [stable26] fix(dav): Abort requests with 429 instead of waiting
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/Exception/TooManyRequests.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3. to review

#39256 [stable22] fix(dav): Abort requests with 429 instead of waiting
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/Exception/TooManyRequests.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3. to review

#39263 Add IgnoreOpenAPI attribute
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/Http/Attribute/IgnoreOpenAPI.php
Labels: 3. to review

#39032 [stable25] fix(l10n): Fix plural issue with different locale and language
  lib/private/L10N/L10N.php
  tests/lib/L10N/L10nTest.php
Labels: 3. to review

#39270 [stable26] display displayname on federated shares
  apps/federatedfilesharing/lib/Notifier.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  apps/files_sharing/lib/Activity/Providers/Base.php
  apps/files_sharing/lib/Activity/Providers/RemoteShares.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  lib/private/Federation/CloudIdManager.php
  lib/public/Federation/ICloudIdManager.php
  psalm.xml
Labels: 3. to review

#39155 [stable26] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#39031 [stable26] fix(l10n): Fix plural issue with different locale and language
  lib/private/L10N/L10N.php
  tests/lib/L10N/L10nTest.php
Labels: 3. to review

#39260 [stable26] fix(files_sharing): hide download permission for circle shares
  apps/files_sharing/src/components/SharingEntry.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, feature: circles

#39033 [stable24] fix(l10n): Fix plural issue with different locale and language
  lib/private/L10N/L10N.php
  tests/lib/L10N/L10nTest.php
Labels: 3. to review

#39142 [stable27] Fix(OC/password-confirmation): Hide the correct button
  core/src/OC/password-confirmation.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review

#39261 [stable27] fix(files_sharing): hide download permission for circle shares
  apps/files_sharing/src/components/SharingEntry.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, feature: circles

#39274 weather_status: Add OpenAPI spec
  apps/weather_status/composer/composer/autoload_classmap.php
  apps/weather_status/composer/composer/autoload_static.php
  apps/weather_status/lib/Capabilities.php
  apps/weather_status/lib/Controller/WeatherStatusController.php
  apps/weather_status/lib/ResponseDefinitions.php
  apps/weather_status/lib/Service/WeatherStatusService.php
Labels: 3. to review

#39255 [stable23] fix(dav): Abort requests with 429 instead of waiting
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/Exception/TooManyRequests.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 4. to release

#39248 preload custom properties when propfinding folders
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: 3. to review, backport-request

#39284 settings: Add OpenAPI spec
  apps/settings/lib/Controller/AdminSettingsController.php
  apps/settings/lib/Controller/AppSettingsController.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/Controller/HelpController.php
  apps/settings/lib/Controller/LogSettingsController.php
  apps/settings/lib/Controller/PersonalSettingsController.php
  apps/settings/lib/Controller/ReasonsController.php
  apps/settings/lib/Controller/UsersController.php
  apps/settings/lib/Controller/WebAuthnController.php
  apps/settings/openapi.json
Labels: 3. to review

#39265 [stable27] Enable all files_versions features when groupfolders is enabled
  apps/files_versions/lib/Capabilities.php
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: enhancement, 3. to review, javascript, php

#39287 theming: Add OpenAPI spec
  apps/theming/composer/composer/autoload_classmap.php
  apps/theming/composer/composer/autoload_static.php
  apps/theming/lib/Capabilities.php
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/Controller/UserThemeController.php
  apps/theming/lib/ResponseDefinitions.php
  apps/theming/openapi.json
Labels: 3. to review

#39254 [stable24] fix(dav): Abort requests with 429 instead of waiting
  .github/workflows/static-code-analysis.yml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/Exception/TooManyRequests.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 4. to release

#38960 [stable27] fix(systemtags): Add missing systemtags index
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review

#39272 sharebymail: Add OpenAPI spec
  apps/sharebymail/lib/Capabilities.php
  apps/sharebymail/openapi.json
Labels: 3. to review

#39190 fix(dav): Move DAV app to non deprecated event dispatcher
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: bug, 3. to review, feature: caldav, feature: carddav

#39286 dashboard: Add OpenAPI spec
  apps/dashboard/composer/composer/autoload_classmap.php
  apps/dashboard/composer/composer/autoload_static.php
  apps/dashboard/lib/Controller/DashboardApiController.php
  apps/dashboard/lib/Controller/DashboardController.php
  apps/dashboard/lib/ResponseDefinitions.php
Labels: 3. to review

#39285 [26] add command do delete orphan shares
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Command/DeleteOrphanShares.php
  apps/files_sharing/lib/OrphanHelper.php
Labels: 3. to review

#39169 Migrate files sharing to PSR LoggerInterface
  apps/files_sharing/lib/Controller/RemoteController.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/lib/Listener/ShareInteractionListener.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  apps/files_sharing/tests/MountProviderTest.php
Labels: enhancement, 3. to review

#38561 feat(request): Allow to match the client version with the IRequest::U…
  apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php
  apps/dav/tests/unit/Connector/Sabre/AuthTest.php
  apps/dav/tests/unit/Connector/Sabre/BlockLegacyClientPluginTest.php
  apps/workflowengine/tests/Check/RequestUserAgentTest.php
  lib/public/IRequest.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: enhancement, 3. to review, pending documentation

#39280 federation: Add OpenAPI spec
  apps/federation/lib/Controller/OCSAuthAPIController.php
  apps/federation/openapi.json
Labels: 3. to review

#39233 [stable25] use more efficient tag retrieval on DAV report request
  apps/dav/lib/Connector/Sabre/FilesReportPlugin.php
  apps/dav/tests/unit/Connector/Sabre/FilesReportPluginTest.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/SystemTag/SystemTagManager.php
  lib/private/SystemTag/SystemTagObjectMapper.php
  lib/public/SystemTag/ISystemTagManager.php
Labels: bug, 3. to review, feature: dav, feature: tags

#39269 [stable27] display displayname on federated shares
  apps/federatedfilesharing/lib/Notifier.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  apps/files_sharing/lib/Activity/Providers/Base.php
  apps/files_sharing/lib/Activity/Providers/RemoteShares.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  lib/private/Federation/CloudIdManager.php
  lib/public/Federation/ICloudIdManager.php
  psalm.xml
Labels: 4. to release

#38357 [stable27] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#39301 [stable27] fix(files): fix legacy router query change
  apps/files/src/router/router.js
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, regression

#39312 updatenotification: Add OpenAPI spec
  apps/updatenotification/composer/composer/autoload_classmap.php
  apps/updatenotification/composer/composer/autoload_static.php
  apps/updatenotification/lib/Controller/APIController.php
  apps/updatenotification/lib/ResponseDefinitions.php
  apps/updatenotification/openapi.json
Labels: 3. to review

#39315 dav: Add OpenAPI spec
  apps/dav/lib/Capabilities.php
  apps/dav/lib/Controller/DirectController.php
  apps/dav/lib/Controller/InvitationResponseController.php
Labels: 3. to review

#39104 [master] Fix npm audit
  package-lock.json
Labels: 4. to release, dependencies

#38920 [stable26] pruneOutdatedSyncTokens deletes all entries
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: bug, 4. to release, feature: caldav

#39325 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#39268 fix(flow): Revert invalid rename of check class for RequestTime
  apps/workflowengine/src/components/Checks/request.js
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review

#39324 ci(32bit): fix failing test setup
  .github/workflows/phpunit-32bits.yml
Labels: 3. to review, backport-request, tests, feature: 32bits

#39327 files: Add OpenAPI spec
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/Capabilities.php
  apps/files/lib/Controller/ApiController.php
  apps/files/lib/Controller/DirectEditingController.php
  apps/files/lib/Controller/DirectEditingViewController.php
  apps/files/lib/Controller/OpenLocalEditorController.php
  apps/files/lib/Controller/TemplateController.php
  apps/files/lib/Controller/TransferOwnershipController.php
  apps/files/lib/Controller/ViewController.php
  apps/files/lib/DirectEditingCapabilities.php
  apps/files/lib/ResponseDefinitions.php
  apps/files/openapi.json
  lib/public/Files/Template/TemplateFileCreator.php
Labels: 3. to review

#39334 [stable27] ci(32bit): fix failing test setup
  .github/workflows/phpunit-32bits.yml
Labels: 4. to release, tests, feature: 32bits

#39335 [stable26] ci(32bit): fix failing test setup
  .github/workflows/phpunit-32bits.yml
Labels: 3. to review, tests, feature: 32bits

#38366 add commands to copy/move files
  apps/files/appinfo/info.xml
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/Command/Copy.php
  apps/files/lib/Command/Move.php
Labels: 3. to review

#36830 fix: Avoid failing with duplicate checks
  apps/workflowengine/lib/Check/FileMimeType.php
  apps/workflowengine/tests/Check/FileMimeTypeTest.php
Labels: bug, 3. to review

#39333 [stable27] fix(files): sanitize name and ext display
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files

#38919 [stable27] pruneOutdatedSyncTokens deletes all entries
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: bug, 4. to release, feature: caldav

#39061 [stable25] Fix creating events with old (< unix time) lastoccurence
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 3. to review

#39337 fix(workflowengine): Migrate from deprecated `NcMultiselect` to `NcSelect`
  apps/workflowengine/src/components/Event.vue
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.LICENSE.txt
  dist/workflowengine-workflowengine.js.map
Labels: 3. to review, feature: workflows, javascript

#39297 fix(dav): close cursor when fetching max id
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: bug, 3. to review, feature: caldav, feature: carddav

#39320 files_trashbin: Add OpenAPI spec
  apps/files_trashbin/lib/Capabilities.php
  apps/files_trashbin/lib/Controller/PreviewController.php
  apps/files_trashbin/openapi.json
Labels: 3. to review

#39318 cloud_federation_api: Add OpenAPI spec
  apps/cloud_federation_api/composer/composer/autoload_classmap.php
  apps/cloud_federation_api/composer/composer/autoload_static.php
  apps/cloud_federation_api/lib/Capabilities.php
  apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
  apps/cloud_federation_api/lib/ResponseDefinitions.php
  apps/cloud_federation_api/openapi.json
Labels: 3. to review

#39308 [stable22] Add bruteforce protection in OauthApiController
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/tests/Controller/OauthApiControllerTest.php
Labels: enhancement, feature: authentication

#39307 [stable23] Add bruteforce protection in OauthApiController
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/tests/Controller/OauthApiControllerTest.php
Labels: enhancement, feature: authentication

#39319 files_versions: Add OpenAPI spec
  apps/files_versions/lib/Capabilities.php
  apps/files_versions/lib/Controller/PreviewController.php
  apps/files_versions/openapi.json
Labels: 3. to review

#39328 federatedfilesharing: Add OpenAPI spec
  apps/federatedfilesharing/lib/AddressHandler.php
  apps/federatedfilesharing/lib/Controller/MountPublicLinkController.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  apps/federatedfilesharing/openapi.json
  lib/public/Federation/ICloudFederationProvider.php
Labels: 3. to review

#39316 oauth2: Add OpenAPI spec
  apps/oauth2/lib/Controller/LoginRedirectorController.php
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/openapi.json
Labels: 3. to review

#39341 cloud_federation_api: Fix OpenAPI spec
  apps/cloud_federation_api/openapi.json
Labels: 3. to review

#39220 [stable25] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#39345 [stable26] chore(CI): Sign .drone.yml file
  .drone.yml
Labels: 4. to release

#39350 [stable21] chore(CI): Sign .drone.yml file
  .drone.yml
Labels: 4. to release

#39348 [stable23] chore(CI): Sign .drone.yml file
  .drone.yml
Labels: 4. to release

#39351 [stable20] chore(CI): Sign .drone.yml file
  .drone.yml
Labels: 4. to release

#39343 chore(CI): Sign .drone.yml file
  .drone.yml
Labels: 4. to release

#39060 [stable26] Fix creating events with old (< unix time) lastoccurence
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 3. to review

#39323 files_external: getStorage before remove
  apps/files_external/lib/Service/UserStoragesService.php
Labels: 3. to review, backport-request

#39356 [stable25] getStorage before remove
  apps/files_external/lib/Service/UserStoragesService.php
Labels: 3. to review

#39354 [stable27] getStorage before remove
  apps/files_external/lib/Service/UserStoragesService.php
Labels: 3. to review

#39355 [stable26] getStorage before remove
  apps/files_external/lib/Service/UserStoragesService.php
Labels: 3. to review

#39281 26.0.4 RC1
  version.php
Labels: 3. to review

#39282 27.0.1 RC1
  version.php
Labels: 3. to review

#39331 core: Add OpenAPI spec
  core/Controller/AppPasswordController.php
  core/Controller/AutoCompleteController.php
  core/Controller/AvatarController.php
  core/Controller/CSRFTokenController.php
  core/Controller/ClientFlowLoginController.php
  core/Controller/ClientFlowLoginV2Controller.php
  core/Controller/CollaborationResourcesController.php
  core/Controller/CssController.php
  core/Controller/ErrorController.php
  core/Controller/GuestAvatarController.php
  core/Controller/HoverCardController.php
  core/Controller/JsController.php
  core/Controller/LoginController.php
  core/Controller/LostController.php
  core/Controller/NavigationController.php
  core/Controller/OCJSController.php
  core/Controller/OCSController.php
  core/Controller/PreviewController.php
  core/Controller/ProfileApiController.php
  core/Controller/ProfilePageController.php
  core/Controller/RecommendedAppsController.php
  core/Controller/ReferenceApiController.php
  core/Controller/ReferenceController.php
  core/Controller/TranslationApiController.php
  core/Controller/TwoFactorChallengeController.php
  core/Controller/UnifiedSearchController.php
  core/Controller/UnsupportedBrowserController.php
  core/Controller/WalledGardenController.php
  core/Controller/WellKnownController.php
  core/Controller/WhatsNewController.php
  core/Controller/WipeController.php
  core/ResponseDefinitions.php
  core/openapi.json
  lib/private/CapabilitiesManager.php
  lib/private/Contacts/ContactsMenu/Actions/LinkAction.php
  lib/private/Contacts/ContactsMenu/Entry.php
  lib/private/Updater/ChangesCheck.php
  lib/public/Collaboration/Reference/Reference.php
  lib/public/Translation/LanguageTuple.php
  tests/Core/Controller/ClientFlowLoginV2ControllerTest.php
Labels: 3. to review

#39321 files_external: Add OpenAPI spec
  apps/files_external/composer/composer/autoload_classmap.php
  apps/files_external/composer/composer/autoload_static.php
  apps/files_external/lib/Controller/ApiController.php
  apps/files_external/lib/Lib/StorageConfig.php
  apps/files_external/lib/ResponseDefinitions.php
  apps/files_external/openapi.json
Labels: 3. to review

#39339 fix(node): non-existing folder is not searchable
  lib/private/Files/Node/NonExistingFolder.php
Labels: bug, 3. to review, backport-request

#39353 [stable25] test(psalm): ignore known reports
  build/psalm-baseline.xml
Labels: 3. to review, tests

#39389 feat: Add public event for missing indices
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/Command/Db/AddMissingIndices.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/DB/Events/AddMissingIndicesEvent.php
  lib/public/IDBConnection.php
Labels: enhancement, 4. to release, pending documentation

#39132 fix(CardDAV): catch right exception when checking for federated app classes
  apps/dav/lib/CardDAV/UserAddressBooks.php
  lib/private/AppFramework/Utility/SimpleContainer.php
Labels: bug, 4. to release, backport-request

#39401 fix(i18n) Changed grammar related to "login"
  apps/encryption/lib/Crypto/EncryptAll.php
Labels: 3. to review

#39397 [stable26] feat: Add public event for missing indices
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/Command/Db/AddMissingIndices.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/DB/Events/AddMissingIndicesEvent.php
  lib/public/IDBConnection.php
Labels: bug, 3. to review

#39406 [stable26] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#39416 fix(core): Add password confirmation requirement for getapppassword
  core/Controller/AppPasswordController.php
Labels: 4. to release

#39417 [stable27] fix(core): Add password confirmation requirement for getapppassword
  core/Controller/AppPasswordController.php
Labels: 4. to release

#39418 [stable26] fix(core): Add password confirmation requirement for getapppassword
  core/Controller/AppPasswordController.php
Labels: 4. to release

#39419 [stable25] fix(core): Add password confirmation requirement for getapppassword
  core/Controller/AppPasswordController.php
Labels: 4. to release

#39024 [stable21] Increase from 100000 to 600000 iterations for hash_pbkdf2
  apps/encryption/lib/Crypto/Crypt.php
  apps/encryption/tests/Crypto/CryptTest.php
Labels: 3. to review, backport-request

#39421 [stable23] fix(core): Add password confirmation requirement for getapppassword
  core/Controller/AppPasswordController.php
Labels: 4. to release

#39422 [stable22] fix(core): Add password confirmation requirement for getapppassword
  core/Controller/AppPasswordController.php
Labels: 4. to release

#39425 [stable19] fix(core): Add password confirmation requirement for getapppassword
  core/Controller/AppPasswordController.php
Labels: 4. to release

#39428 27.0.1 RC2
  version.php
Labels: 3. to review

#39427 26.0.4 RC2
  version.php
Labels: 3. to review

#39426 25.0.9 RC2
  version.php
Labels: 3. to review

#39432 fix: check that object store backend supports multi part uploads
  apps/dav/lib/Upload/ChunkingV2Plugin.php
Labels: bug, 3. to review, backport-request

#39378 fix: Always apply fullscreen styling to sidebar
  apps/files/src/views/Sidebar.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, design, 3. to review

#39442 chore: update codeowners for 2fa
  .github/CODEOWNERS
Labels: 4. to release

#38907 Fix: ContactManager search with fullmatch
  lib/private/ContactsManager.php
Labels: bug, 3. to review, backport-request, feature: users and groups, integration, feature: carddav

#39447 Fix sharing of encrypted files
  apps/encryption/lib/Crypto/Encryption.php
Labels: bug, 3. to review, backport-request

#39305 feat(dav): Emit a typed event to deprecate OCA\DAV\Connector\Sabre::addPlugin
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/appinfo/v1/webdav.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Events/SabrePluginAddEvent.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/RequestTest/RequestTestCase.php
Labels: enhancement, 3. to review, feature: dav, pending documentation

#39456 fix: Correctly add `module` content type to script tags with versions
  lib/private/legacy/template/functions.php
  tests/lib/TemplateFunctionsTest.php
Labels: bug, 3. to review, backport-request

#39444 fix(l10n): User manager
  apps/settings/src/components/Users/NewUserModal.vue
  apps/settings/src/components/Users/UserListHeader.vue
  apps/settings/src/components/Users/UserRow.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, feature: language l10n and translations

#39304 fix(comments): Emit CommentsEntityEvent as typed event
  apps/comments/lib/AppInfo/Application.php
  apps/dav/lib/Comments/RootCollection.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/Comments/RootCollectionTest.php
  lib/public/Comments/CommentsEntityEvent.php
Labels: enhancement, 3. to review, feature: dav, feature: comments, pending documentation

#39222 Migrate more apps to IEventDispatcher
  apps/files_trashbin/lib/Events/MoveToTrashEvent.php
  apps/files_trashbin/lib/Storage.php
  apps/files_trashbin/tests/StorageTest.php
  apps/lookup_server_connector/lib/AppInfo/Application.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/tests/ManagerTest.php
  lib/public/WorkflowEngine/IManager.php
Labels: bug, 3. to review

#39490 fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/InfoParser.php
  lib/private/Installer.php
Labels: 4. to release

#39491 [stable27] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/InfoParser.php
  lib/private/Installer.php
Labels: 4. to release

#39503 27.0.1
  version.php
Labels: 3. to review

#39492 [stable26] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/InfoParser.php
  lib/private/Installer.php
Labels: 4. to release

#39502 26.0.4
  version.php
Labels: 3. to review

#39493 [stable25] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/InfoParser.php
  lib/private/Installer.php
Labels: 4. to release

#39501 25.0.9
  version.php
Labels: 3. to review

#39494 [stable24] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/InfoParser.php
  lib/private/Installer.php
Labels: 4. to release

#39495 [stable23] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/InfoParser.php
  lib/private/Installer.php
Labels: 4. to release

#39496 [stable22] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/InfoParser.php
  lib/private/Installer.php
Labels: 4. to release

#39221 Bugfix/bulk upload empty files
  apps/dav/lib/BulkUpload/MultipartRequestParser.php
Labels: 3. to review, backport-request

#39497 [stable21] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/CodeChecker/DatabaseSchemaChecker.php
  lib/private/App/CodeChecker/InfoChecker.php
  lib/private/App/InfoParser.php
  lib/private/DB/MDB2SchemaReader.php
  lib/private/Installer.php
Labels: 4. to release

#39498 [stable20] fix(apps): Fix loading info.xml file
  lib/base.php
  lib/private/App/CodeChecker/DatabaseSchemaChecker.php
  lib/private/App/CodeChecker/InfoChecker.php
  lib/private/App/InfoParser.php
  lib/private/DB/MDB2SchemaReader.php
  lib/private/Installer.php
Labels: 4. to release

#38860 add summary of detected changes to files:scan output
  apps/files/lib/Command/Scan.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Utils/Scanner.php
Labels: 3. to review

#38930 clean failed upload chunks
  apps/dav/lib/Upload/UploadFolder.php
Labels: 3. to review

#39275 Add optional to add backtrace to log items
  config/config.sample.php
  lib/private/Log.php
Labels: 3. to review

#39367 handle more exceptions in AmazonS3::fopen
  apps/files_external/lib/Lib/Storage/AmazonS3.php
  lib/private/Files/Stream/SeekableHttpStream.php
Labels: 3. to review
