Repository nextcloud/server, pull requests merged in 2023-09, with the labels that each got.

#36068 extend fix-key-location to handle cases from broken cross-storage moves
  apps/encryption/lib/Command/FixKeyLocation.php
  lib/private/Encryption/EncryptionWrapper.php
  lib/private/Encryption/Manager.php
  lib/private/Encryption/Util.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Encryption/UtilTest.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 3. to review

#39925 fix(CardDAV): allow disabling of the system address book
  apps/dav/lib/CardDAV/UserAddressBooks.php
Labels: bug, 4. to release, backport-request, feature: carddav, 27-feedback

#40199 remove old fileUploadSpec jsunit test and fix flaky cypress files test
  apps/files/tests/js/fileUploadSpec.js
  cypress/e2e/files.cy.ts
Labels: bug, 3. to review

#38032 Imaginary WebP support
  lib/private/Preview/Generator.php
  lib/private/Preview/Imaginary.php
Labels: 4. to release, pending documentation

#26716 Fix share creation insert and get
  apps/files_sharing/tests/ApiTest.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/ProviderFactory.php
  tests/lib/Files/ViewTest.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: bug, 4. to release, feature: sharing

#40075 fix(API): Fix parameter name to match interface
  lib/private/NavigationManager.php
Labels: bug, 3. to review, technical debt

#40224 ProfileApi: Fix typo
  core/Controller/ProfileApiController.php
  core/openapi.json
Labels: 3. to review

#40189 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#39707 Allow ext storage Local to go unavailable
  apps/files_external/lib/Lib/Backend/Local.php
  lib/private/Files/Storage/Local.php
  tests/lib/Files/Storage/LocalTest.php
Labels: bug, 3. to review

#39863 move share permission logic to storage wrapper
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/CapabilitiesTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/FileInfo.php
  lib/private/Files/ObjectStore/HomeObjectStoreStorage.php
  lib/private/Files/SetupManager.php
  lib/private/Files/SetupManagerFactory.php
  lib/private/Files/Storage/Home.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  lib/private/Share20/ShareDisableChecker.php
  lib/public/Files/IHomeStorage.php
  tests/lib/Files/ViewTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, performance 🚀

#40201 change proftpd ci image
  .github/workflows/ftp.yml
Labels: 3. to review

#39864 reuse l10n and request in dav folder listing
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  apps/dav/tests/unit/Connector/Sabre/RequestTest/RequestTestCase.php
Labels: 3. to review, backport-request, performance 🚀, applied on testing

#40234 enh: skip processing for empty response
  lib/private/Http/Client/DnsPinMiddleware.php
Labels: 3. to review, performance 🚀

#40182 test(sharebymail): Improve tests
  apps/sharebymail/tests/ShareByMailProviderTest.php
Labels: 3. to review

#38150 make Node::getParent lazy
  apps/files_trashbin/lib/Trash/TrashItem.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/LazyRoot.php
  lib/private/Files/Node/LazyUserFolder.php
  lib/private/Files/Node/Node.php
  lib/public/Files/FileInfo.php
Labels: enhancement, 4. to release, performance 🚀

#35539 Cleanup psalm issues in DB/ContactsManager and Console
  lib/private/Console/Application.php
  lib/private/ContactsManager.php
  lib/private/DB/Adapter.php
  lib/private/DB/Connection.php
  lib/private/DB/ConnectionAdapter.php
  lib/private/DB/MigrationService.php
  lib/private/DB/OracleConnection.php
  lib/public/Contacts/IManager.php
  tests/lib/ContactsManagerTest.php
Labels: 2. developing

#40257 comments: Ignore endpoints in OpenAPI
  apps/comments/lib/Controller/NotificationsController.php
  apps/comments/openapi.json
Labels: 3. to review, technical debt

#39895 admin have no special rights on users' entries
  apps/files_external/lib/Controller/AjaxController.php
  apps/files_external/tests/Controller/AjaxControllerTest.php
Labels: 4. to release, backport-request

#40233 [stable25] Detect aborted connection in OC\Files\View and stop writing data to the output buffer
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/View.php
  lib/private/legacy/OC_Files.php
  lib/public/Files/ConnectionLostException.php
Labels: bug, 4. to release, backport-request

#40232 [26] move share permission logic to storage wrapper
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/CapabilitiesTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/FileInfo.php
  lib/private/Files/ObjectStore/HomeObjectStoreStorage.php
  lib/private/Files/SetupManager.php
  lib/private/Files/SetupManagerFactory.php
  lib/private/Files/Storage/Home.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  lib/private/Share20/ShareDisableChecker.php
  lib/public/Files/IHomeStorage.php
  tests/lib/Files/ViewTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review

#40076 [stable26] Do not log passwords in debug mode
  apps/user_ldap/lib/LDAP.php
Labels: 3. to review, feature: logging

#40085 [stable26] fix(cache): Remove displayname cache entry on delete
  apps/files_sharing/lib/AppInfo/Application.php
  lib/private/Group/DisplayNameCache.php
  lib/private/User/DisplayNameCache.php
Labels: bug, 3. to review, feature: users and groups

#40269 [27] change proftpd ci image
  .github/workflows/ftp.yml
Labels: 3. to review, backport-request

#40014 Create right table view
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  apps/settings/src/components/AppList.vue
  apps/settings/src/components/AppList/AppItem.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
  tests/acceptance/features/bootstrap/AppsManagementContext.php
Labels: 4. to release, accessibility

#40231 [27] move share permission logic to storage wrapper
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/CapabilitiesTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/FileInfo.php
  lib/private/Files/ObjectStore/HomeObjectStoreStorage.php
  lib/private/Files/SetupManager.php
  lib/private/Files/SetupManagerFactory.php
  lib/private/Files/Storage/Home.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  lib/private/Share20/ShareDisableChecker.php
  lib/public/Files/IHomeStorage.php
  tests/lib/Files/ViewTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review

#39861 [26] Calendar optimizations
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/CalendarHome.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/lib/DAV/Sharing/Plugin.php
Labels: 3. to review, backport-request

#39991 [stable26] fix: always use display name from correct backend
  lib/private/Accounts/AccountManager.php
Labels: 3. to review

#40184 feat: Add events for version restore
  apps/files_versions/src/views/VersionTab.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: enhancement, 3. to review, backport-request

#40293 fix(ratelimit): Only use memory cache backend for redis
  lib/private/Server.php
Labels: bug, 3. to review, backport-request, feature: caching

#40220 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#40292 fix(CalDAV): check birthday calendar owner
  apps/dav/lib/CalDAV/BirthdayCalendar/EnablePlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/BirthdayCalendar/EnablePluginTest.php
Labels: bug, 3. to review, backport-request, feature: caldav

#38808 Fix issues where unencrypted_size was being falsely used for non-encrypted home folders
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/FileInfo.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: bug, 3. to review, backport-request

#40275 change order of keyboard shortcuts settings to be at the end
  apps/theming/src/UserThemes.vue
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
Labels: enhancement, design, 3. to review

#40198 Create right list view for app store view
  apps/settings/src/components/AppList.vue
  apps/settings/src/components/AppList/AppItem.vue
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, accessibility

#40307 [stable23] fix(ratelimit): Only use memory cache backend for redis
  lib/private/Server.php
Labels: bug, 4. to release

#40308 [stable22] fix(ratelimit): Only use memory cache backend for redis
  lib/private/Server.php
Labels: bug, 3. to review

#40216 Print log message when version could not be got from updater server
  lib/private/Updater/VersionCheck.php
  tests/lib/Updater/VersionCheckTest.php
Labels: enhancement, 3. to review, feature: install and update

#40317 [stable24] fix(CalDAV): check birthday calendar owner
  apps/dav/lib/CalDAV/BirthdayCalendar/EnablePlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/BirthdayCalendar/EnablePluginTest.php
Labels: bug, 3. to review

#40311 [stable25] fix(CalDAV): check birthday calendar owner
  apps/dav/lib/CalDAV/BirthdayCalendar/EnablePlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/BirthdayCalendar/EnablePluginTest.php
Labels: bug, 3. to review

#40286 [stable27] Detect aborted connection in OC\Files\View and stop writing data to t…
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/View.php
  lib/private/legacy/OC_Files.php
  lib/public/Files/ConnectionLostException.php
Labels: bug, 4. to release

#40277 26.0.6 RC1
  version.php
Labels: 3. to review

#40036 [stable25] fix(logging): user log condition feature
  lib/private/Log.php
Labels: bug, 4. to release, feature: logging

#40276 25.0.11 RC1
  version.php
Labels: 3. to review

#40266 40172 Polish new sharing flow : accesibility, expand bahavior, click outside behaviour
  apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/2079-2079.js
  dist/2079-2079.js.LICENSE.txt
  dist/2079-2079.js.map
  dist/894-894.js
  dist/894-894.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#40298 [stable27] enable download configuration on circles shares
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review

#40318 [stable23] fix(CalDAV): check birthday calendar owner
  apps/dav/lib/CalDAV/BirthdayCalendar/EnablePlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/BirthdayCalendar/EnablePluginTest.php
Labels: bug, 3. to review

#40327 [stable27] Backport Polish new sharing flow : accesibility, expand bahavior, click outside behaviour
  apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 4. to release

#40278 27.1.0 RC2
  version.php
Labels: 3. to review

#40285 Detect aborted connection in OC\Files\View and stop writing data to t…
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/View.php
  lib/private/legacy/OC_Files.php
  lib/public/Files/ConnectionLostException.php
Labels: bug, 3. to review, performance 🚀

#40329 theming: Revert broken SVG optimization in default-source.svg
  apps/theming/img/default-source.svg
Labels: backport-request

#40296 Enable new versions feature for groupfolders
  apps/files_versions/composer/composer/autoload_classmap.php
  apps/files_versions/composer/composer/autoload_static.php
  apps/files_versions/composer/composer/installed.php
  apps/files_versions/lib/Listener/FileEventsListener.php
  apps/files_versions/lib/Storage.php
  apps/files_versions/lib/Versions/INeedSyncVersionBackend.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/lib/Versions/VersionManager.php
  apps/files_versions/src/components/Version.vue
  apps/files_versions/src/utils/versions.js
  apps/files_versions/src/views/VersionTab.vue
  dist/614-614.js
  dist/614-614.js.map
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, enhancement, 3. to review, backport-request, feature: versions, php

#40314 enh(a11y): Add search contacts label
  core/src/OC/contactsmenu.js
  core/src/OC/contactsmenu/menu.handlebars
  core/src/views/ContactsMenu.vue
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 4. to release, feature: contacts menu, accessibility

#40323 feat: Add dedicated method to load init scripts
  lib/public/Util.php
Labels: enhancement, 4. to release

#40319 [stable22] fix(CalDAV): check birthday calendar owner
  apps/dav/lib/CalDAV/BirthdayCalendar/EnablePlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/BirthdayCalendar/EnablePluginTest.php
Labels: bug, 3. to review

#39890 [stable27] Reduce the number of container queries
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/files_trashbin/lib/Storage.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
  lib/private/Files/SetupManager.php
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/legacy/OC_Helper.php
  tests/lib/Files/ViewTest.php
  tests/lib/HelperStorageTest.php
Labels: 4. to release, performance 🚀

#40342 [stable27] fix: Hide set reminder action on public shares
  apps/files/js/fileactions.js
Labels: 4. to release

#40339 [stable27] Enable new versions feature for groupfolders
  apps/files_versions/composer/composer/autoload_classmap.php
  apps/files_versions/composer/composer/autoload_static.php
  apps/files_versions/lib/Listener/FileEventsListener.php
  apps/files_versions/lib/Storage.php
  apps/files_versions/lib/Versions/INeedSyncVersionBackend.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/lib/Versions/VersionManager.php
  apps/files_versions/src/components/Version.vue
  apps/files_versions/src/utils/versions.js
  apps/files_versions/src/views/VersionTab.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, enhancement, 3. to review, feature: versions, php

#40340 Fix access to fileInfo in VersionTab.vue
  apps/files_versions/src/views/VersionTab.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review, feature: versions, javascript

#40341 fix: Hide set reminder action on public shares
  apps/files/js/fileactions.js
Labels: bug, 4. to release, feature: sharing, feature: files

#39226 Convert isset ternary to null coalescing operator
  tests/lib/Util/User/Dummy.php
  tests/lib/UtilCheckServerTest.php
Labels: 4. to release, technical debt

#39211 Add return types
  themes/example/defaults.php
Labels: 3. to review, technical debt

#40328 Fix Admin AI settings javascript error
  apps/settings/src/components/AdminAI.vue
  dist/settings-vue-settings-admin-ai.js
  dist/settings-vue-settings-admin-ai.js.map
Labels: bug, 3. to review, backport-request

#39128 fix(ldap): avatar is not being fetched
  apps/user_ldap/lib/User/User.php
  apps/user_ldap/tests/User/UserTest.php
Labels: bug, 3. to review, feature: ldap, backport-request, regression

#40360 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#40343 [stable27] 40289 fix appearance
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: design, 3. to review, 27-feedback

#40344 27.1.0 RC3
  version.php
Labels: 3. to review

#39856 feat(testing): Add fake providers for translations and text processing
  apps/testing/composer/composer/autoload_classmap.php
  apps/testing/composer/composer/autoload_static.php
  apps/testing/lib/AppInfo/Application.php
  apps/testing/lib/Provider/FakeTextProcessingProvider.php
  apps/testing/lib/Provider/FakeTranslationProvider.php
Labels: enhancement, 3. to review, tests

#40376 test: add tests for dns pin middleware
  lib/private/Http/Client/DnsPinMiddleware.php
  tests/lib/Http/Client/DnsPinMiddlewareTest.php
Labels: 3. to review, tests

#40378 add plus icon to new user button
  apps/settings/src/views/Users.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, design, 3. to review

#40372 40172 polish sharing flow bugs
  apps/files_sharing/lib/Listener/LoadSidebarListener.php
  apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
  apps/files_sharing/src/services/ConfigService.js
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/2079-2079.js
  dist/2079-2079.js.map
  dist/2785-2785.js
  dist/2785-2785.js.LICENSE.txt
  dist/2785-2785.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request

#40301 fix(caldav): add webroot to objectid for activities
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/EventTest.php
Labels: bug, 4. to release

#40321 [stable23] fix(caching): suppress static analysis warning for memcaching
  lib/private/Memcache/Memcached.php
Labels: bug, 4. to release, feature: caching

#40391 fix(settings): Undefined user count error
  apps/settings/src/components/GroupListItem.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release

#40412 [stable27] Ellipsize user status in sharing entry
  apps/files_sharing/src/components/SharingEntry.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: feature: sharing, 27-feedback

#40401 25.0.11
  version.php
Labels: 3. to review

#40400 26.0.6
  version.php
Labels: 3. to review

#40399 27.1.0 RC4
  version.php
Labels: 3. to review

#40389 Fix invite guest for new sharing flow
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryInherited.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/components/SharingEntrySimple.vue
  apps/files_sharing/src/mixins/ShareDetails.js
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/9193-9193.js
  dist/9193-9193.js.map
  dist/9794-9794.js
  dist/9794-9794.js.LICENSE.txt
  dist/9794-9794.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, feature: sharing, backport-request

#40381 [stable25] Fix issues where unencrypted_size was being falsely used for non-encrypted home folders
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/FileInfo.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: bug, 3. to review

#40416 fix: use faster method to fetch user count
  apps/dav/lib/Migration/Version1027Date20230504122946.php
Labels: bug, 4. to release, backport-request

#40380 [stable26] Fix issues where unencrypted_size was being falsely used for non-encrypted home folders
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/FileInfo.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: bug, 3. to review

#40428 Multiple bug fix in users list
  apps/settings/src/components/Users/UserRow.vue
  apps/settings/src/store/users.js
  apps/settings/src/views/Users.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: users and groups, javascript

#40437 [stable27] Correctly switch/revert from custom to bundled perms
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 4. to release, feature: sharing

#40432 27.1.0
  version.php
Labels: 3. to review

#40418 fix: don't use davtags for tag search
  apps/systemtags/lib/Search/TagSearchProvider.php
Labels: bug, 3. to review, backport-request

#40203 fix(mimetype): Fix aborted transaction on PostgreSQL when storing mimetype
  lib/private/Files/Type/Loader.php
Labels: bug, 3. to review, backport-request

#38610 Refactors "strpos" calls in /apps/dav
  apps/dav/appinfo/v1/webdav.php
  apps/dav/appinfo/v2/direct.php
  apps/dav/appinfo/v2/remote.php
  apps/dav/lib/CalDAV/Activity/Backend.php
  apps/dav/lib/CalDAV/Integration/ExternalCalendar.php
  apps/dav/lib/CalDAV/Publishing/PublishPlugin.php
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/CardDAV/HasPhotoPlugin.php
  apps/dav/lib/CardDAV/Integration/ExternalAddressBook.php
  apps/dav/lib/CardDAV/MultiGetExportPlugin.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/CardDAV/SystemAddressbook.php
  apps/dav/lib/Comments/CommentNode.php
  apps/dav/lib/Comments/CommentsPlugin.php
  apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
  apps/dav/lib/Connector/Sabre/CachingTree.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/Connector/Sabre/PropfindCompressionPlugin.php
  apps/dav/lib/DAV/GroupPrincipalBackend.php
  apps/dav/lib/DAV/PublicAuth.php
  apps/dav/lib/DAV/Sharing/Plugin.php
  apps/dav/lib/Listener/CalendarContactInteractionListener.php
  apps/dav/lib/Listener/CalendarDeletionDefaultUpdaterListener.php
  apps/dav/lib/Server.php
Labels: 4. to release, technical debt

#40421 core: Fix OpenAPI for reference API
  core/Controller/CollaborationResourcesController.php
  core/Controller/ReferenceApiController.php
  core/ResponseDefinitions.php
  core/openapi.json
  lib/public/Collaboration/Reference/IReference.php
  lib/public/Collaboration/Reference/Reference.php
Labels: 3. to review, technical debt

#40426 provisioning_api: Fix quota constants in OpenAPI
  apps/provisioning_api/lib/ResponseDefinitions.php
  apps/provisioning_api/openapi.json
Labels: 3. to review, technical debt

#40358 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#40419 Remove deprecated at matcher in tests/lib/InstallerTest.php
  tests/lib/InstallerTest.php
Labels: 3. to review

#39039 Refactors lib/private/Log
  lib/private/Log/ErrorHandler.php
  lib/private/Log/Errorlog.php
  lib/private/Log/ExceptionSerializer.php
  lib/private/Log/File.php
  lib/private/Log/LogDetails.php
  lib/private/Log/LogFactory.php
  lib/private/Log/PsrLoggerAdapter.php
  lib/private/Log/Rotate.php
  lib/private/Log/Syslog.php
  lib/private/Log/Systemdlog.php
Labels: 3. to review, technical debt

#40420 Remove last calls to deprecated at matcher in tests/Core
  tests/Core/Command/Encryption/ChangeKeyStorageRootTest.php
  tests/Core/Command/Encryption/DecryptAllTest.php
  tests/Core/Command/Encryption/EnableTest.php
  tests/Core/Command/Encryption/EncryptAllTest.php
  tests/Core/Command/Encryption/SetDefaultModuleTest.php
  tests/Core/Command/Log/FileTest.php
  tests/Core/Command/Log/ManageTest.php
  tests/Core/Command/Maintenance/Mimetype/UpdateDBTest.php
  tests/Core/Command/Preview/RepairTest.php
Labels: 3. to review

#40448 [stable27] Backport consider link shares in removeShare method in SharingTab #40440
  apps/files_sharing/src/views/SharingTab.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing

#39818 Let `occ trashbin:restore` restore also from groupfolders and add filters
  apps/files_trashbin/lib/Command/RestoreAllFiles.php
Labels: enhancement, 3. to review, feature: trashbin, feature: occ

#40474 fix(dav): report status
  apps/dav/lib/Connector/Sabre/FilesReportPlugin.php
Labels: bug, 3. to review, feature: dav

#40480 fixes Dashboard icon rendering in darkmode
  core/img/categories/dashboard.svg
Labels: bug, design, 3. to review, feature: dashboard

#40183 SFTP improvements
  .github/workflows/sftp.yml
  apps/files_external/lib/Lib/Storage/SFTP.php
  apps/files_external/lib/Lib/Storage/SFTPReadStream.php
Labels: bug, enhancement, 3. to review, feature: external storage

#40485 fix(dav): fix report tests
  apps/dav/tests/unit/Connector/Sabre/FilesReportPluginTest.php
Labels: bug, 3. to review, feature: dav

#39531 kerberos sso ci fix
  .github/workflows/smb-kerberos.yml
  apps/files_external/tests/sso-setup/apps.config.php
  apps/files_external/tests/sso-setup/client-cmd.sh
  apps/files_external/tests/sso-setup/setup-sso-nc.sh
  apps/files_external/tests/sso-setup/start-apache.sh
  apps/files_external/tests/sso-setup/start-dc.sh
  apps/files_external/tests/sso-setup/test-sso-smb.sh
  apps/files_external/tests/start-apache.sh
Labels: 3. to review

#40423 enh(db): provide database providers via IDB API
  apps/settings/lib/Controller/CheckSetupController.php
  lib/private/DB/ConnectionAdapter.php
  lib/public/IDBConnection.php
Labels: enhancement, 3. to review, pending documentation, dependencies, developer experience

#40488 fix(comments): Use provided offset in best effort when loading comments
  lib/private/Comments/Manager.php
Labels: bug, 3. to review, backport-request, feature: comments

#40481 fix: content info footer on guest pages
  core/css/guest.css
  core/css/guest.css.map
  core/css/guest.scss
  core/src/views/Login.vue
  core/templates/layout.guest.php
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, design, 3. to review, backport-request, feature: accessibility, accessibility

#40504 Remove deprectated ILogger uses from user_ldap application
  apps/user_ldap/lib/Controller/ConfigAPIController.php
  apps/user_ldap/lib/User/User.php
Labels: 3. to review, feature: ldap, technical debt

#39626 Remove litmus locks tests
  apps/dav/tests/travis/litmus-v1/script.sh
  apps/dav/tests/travis/litmus-v2/script.sh
Labels: 3. to review, technical debt

#40528 26.0.7
  version.php
Labels: 3. to review

#40429 [stable27] Fix alignments for share different share entry types.
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryInherited.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/components/SharingEntrySimple.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, 27-feedback

#40520 [stable27] fix: content info footer on guest pages
  core/css/guest.css
  core/css/guest.css.map
  core/css/guest.scss
  core/src/views/Login.vue
  core/templates/layout.guest.php
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, design, 4. to release, feature: accessibility, accessibility

#39628 Enable litmus largefile tests
  apps/dav/tests/travis/litmus-v1/script.sh
  apps/dav/tests/travis/litmus-v2/script.sh
Labels: 3. to review, technical debt

#40516 Remove 'Working with ... code' sections from README.md
  README.md
Labels: 4. to release

#39166 Refactors dav app commands.
  apps/dav/lib/Command/CreateAddressBook.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/Command/DeleteCalendar.php
  apps/dav/lib/Command/ListCalendars.php
  apps/dav/lib/Command/MoveCalendar.php
  apps/dav/lib/Command/RemoveInvalidShares.php
  apps/dav/lib/Command/RetentionCleanupCommand.php
  apps/dav/lib/Command/SendEventReminders.php
  apps/dav/lib/Command/SyncBirthdayCalendar.php
  apps/dav/lib/Command/SyncSystemAddressBook.php
Labels: 4. to release, technical debt

#40530 [stable27] Consider share type for enforced share expiry dates
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, feature: sharing

#40511 Fix dashboard widgets api
  apps/dashboard/lib/Controller/DashboardApiController.php
  apps/dashboard/openapi.json
  lib/private/Dashboard/Manager.php
  lib/public/Dashboard/IManager.php
Labels: 3. to review, backport-request, technical debt

#38989 Refactors lib/private/Avatar.
  lib/private/Avatar/AvatarManager.php
  lib/private/Avatar/GuestAvatar.php
  lib/private/Avatar/PlaceholderAvatar.php
  lib/private/Avatar/UserAvatar.php
Labels: 3. to review, technical debt

#40379 [stable27] Fix issues where unencrypted_size was being falsely used for non-encrypted home folders
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/FileInfo.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: bug, 3. to review

#40548 Add label for input field and select and adjust styles
  apps/systemtags/css/settings.css
  apps/systemtags/templates/admin.php
Labels: 3. to review

#40508 Migrate applications away from deprecated ILogger
  apps/federation/tests/Controller/OCSAuthAPIControllerTest.php
  apps/federation/tests/TrustedServersTest.php
  apps/files/lib/Controller/DirectEditingViewController.php
  apps/files_trashbin/lib/Storage.php
  apps/files_trashbin/tests/StorageTest.php
  apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php
  apps/settings/lib/Controller/WebAuthnController.php
  apps/settings/tests/Controller/UsersControllerTest.php
  apps/theming/lib/ImageManager.php
  apps/theming/tests/ImageManagerTest.php
  apps/twofactor_backupcodes/lib/Listener/ActivityPublisher.php
  apps/twofactor_backupcodes/tests/Unit/Listener/ActivityPublisherTest.php
  apps/updatenotification/lib/AppInfo/Application.php
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/tests/Unit/Controller/UserStatusControllerTest.php
  apps/weather_status/lib/Controller/WeatherStatusController.php
  apps/weather_status/lib/Service/WeatherStatusService.php
  apps/workflowengine/lib/Entity/File.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/lib/Service/Logger.php
  apps/workflowengine/tests/ManagerTest.php
  lib/private/Server.php
Labels: 3. to review, technical debt

#38633 test: add test for cache mount provider
  tests/lib/Files/Mount/CacheMountProviderTest.php
Labels: 4. to release, tests

#39216 Refactor "substr" calls in lib/private to improve code readability
  lib/private/DB/OracleMigrator.php
  lib/private/DateTimeFormatter.php
  lib/private/Files/Storage/DAV.php
  lib/private/Files/Storage/Local.php
  lib/private/L10N/Factory.php
  lib/private/Route/Router.php
  lib/private/TemplateLayout.php
  lib/private/URLGenerator.php
  lib/private/User/User.php
  lib/private/legacy/OC_API.php
Labels: 3. to review, technical debt

#40499 add wrapper for external storage to ensure we don't get an mtime that is lower than we know it is
  apps/files_external/lib/Config/ConfigAdapter.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Storage/Wrapper/KnownMtime.php
  tests/lib/Files/Storage/Wrapper/KnownMtimeTest.php
Labels: 3. to review, backport-request

#40288 feat(appframework): Expose programmatic rate limiter
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Middleware/Security/Exceptions/SecurityException.php
  lib/private/Security/RateLimiting/Exception/RateLimitExceededException.php
  lib/private/Security/RateLimiting/Limiter.php
  lib/private/Server.php
  lib/public/Security/RateLimiting/ILimiter.php
  lib/public/Security/RateLimiting/IRateLimitExceededException.php
Labels: enhancement, 4. to release, security

#40574 feat(CI): Allow apps to test with PHPUnit10
  tests/lib/TestCase.php
Labels: 3. to review, technical debt

#39013 [3/3] Refactors lib/private/Security
  lib/private/Security/Certificate.php
  lib/private/Security/CertificateManager.php
  lib/private/Security/CredentialsManager.php
  lib/private/Security/Crypto.php
  lib/private/Security/Hasher.php
  lib/private/Security/Normalizer/IpAddress.php
  lib/private/Security/RemoteHostValidator.php
  lib/private/Security/SecureRandom.php
  lib/private/Security/TrustedDomainHelper.php
Labels: 3. to review, technical debt

#39113 [1/2] Refactors lib/private/Collaboration
  lib/private/Collaboration/AutoComplete/Manager.php
  lib/private/Collaboration/Collaborators/GroupPlugin.php
  lib/private/Collaboration/Collaborators/LookupPlugin.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/private/Collaboration/Collaborators/RemoteGroupPlugin.php
  lib/private/Collaboration/Collaborators/RemotePlugin.php
  lib/private/Collaboration/Collaborators/Search.php
  lib/private/Collaboration/Collaborators/SearchResult.php
  lib/private/Collaboration/Collaborators/UserPlugin.php
Labels: 3. to review, technical debt

#40589 ci: skip cypress install
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-tests.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  package.json
Labels: 3. to review, tests

#40575 core: Fix OCM OpenAPI
  core/Controller/OCMController.php
  core/openapi.json
Labels: 3. to review, technical debt

#40552 Add labels for input fields
  apps/oauth2/src/App.vue
  dist/oauth2-oauth2.js
  dist/oauth2-oauth2.js.map
Labels: 3. to review

#40606 [stable26] Do not throw while restoring unloaded files list entries
  apps/files_trashbin/src/filelist.js
  dist/files_trashbin-files_trashbin.js
  dist/files_trashbin-files_trashbin.js.map
Labels: bug, 3. to review, backport-request, feature: trashbin

#40605 [stable27] Revert change that made `OC.Util.humanFileSize` return decimal sizes instead of binary
  core/src/OC/util.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, regression

#40562 style: Fix editorconfig indent for config/*config.php
  .editorconfig
Labels: 4. to release

#40501 Store size in int|float for 32bit support
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/ObjectStore/ObjectStoreScanner.php
Labels: bug, 3. to review, backport-request, feature: 32bits

#40620 feat(phonenumber): Add OCP wrapper for PhoneNumber utils library
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Accounts/AccountManager.php
  lib/private/PhoneNumberUtil.php
  lib/private/Server.php
  lib/public/IPhoneNumberUtil.php
  tests/lib/Accounts/AccountManagerTest.php
Labels: enhancement, 3. to review, technical debt, feature: profile

#40533 Auto set password for new email shares
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/1567-1567.js
  dist/1567-1567.js.LICENSE.txt
  dist/1567-1567.js.map
  dist/188-188.js
  dist/188-188.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: feature: sharing, 27-feedback

#40622 fix(build): Ignore `default-source.svg` from image optimization
  build/image-optimization.sh
Labels: bug, 3. to review, feature: theming, technical debt

#40541 fix(dav): expand recurrences when searching
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: bug, 4. to release, feature: dav, backport-request

#40613 Remove unneeded opacity for action button
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 3. to review

#40565 Remove deprecated methods Util::writeLog and DIContainer::log
  core/Controller/SetupController.php
  lib/autoloader.php
  lib/base.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/Tags.php
  lib/private/legacy/OC_App.php
  lib/private/legacy/OC_User.php
  lib/public/Util.php
Labels: 3. to review, technical debt

#40619 Use proper app id in Version.vue
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
  dist/weather_status-weather-status.js
  dist/weather_status-weather-status.js.map
Labels: bug, 3. to review, backport-request, feature: versions, javascript

#40584 Correct value for device name input field
  apps/settings/src/components/AuthTokenSetupDialogue.vue
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.map
Labels: 3. to review

#40614 fix(userstatus): Sync migration version number with app version
  apps/user_status/composer/composer/autoload_classmap.php
  apps/user_status/composer/composer/autoload_static.php
  apps/user_status/lib/Migration/Version1003Date20210809144824.php
Labels: 4. to release, technical debt, feature: status

#40638 [stable27] Fix jsunit tests
  apps/files/tests/js/fileUploadSpec.js
  apps/files/tests/js/filelistSpec.js
  apps/files/tests/js/filesummarySpec.js
  apps/files/tests/js/mainfileinfodetailviewSpec.js
Labels: bug, 3. to review, tests

#40639 chore: Drop vendored Composer v2.4.1
  build/composer
Labels: 4. to release, technical debt

#36742 Refactors tests/app.php to improve code readability.
  tests/apps.php
Labels: 3. to review, technical debt

#40065 fix(files): do not load legacy files app js
  apps/files/lib/Controller/ViewController.php
  apps/files/src/services/FileInfo.js
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review, feature: files, files2vue

#40649 Fix OCS-APIRequest header for OpenAPI
  apps/dashboard/openapi.json
  apps/dav/openapi.json
  apps/federatedfilesharing/openapi.json
  apps/federation/openapi.json
  apps/files/openapi.json
  apps/files_external/openapi.json
  apps/files_reminders/openapi.json
  apps/files_sharing/openapi.json
  apps/provisioning_api/openapi.json
  apps/theming/openapi.json
  apps/updatenotification/openapi.json
  apps/user_ldap/openapi.json
  apps/user_status/openapi.json
  apps/weather_status/openapi.json
  core/openapi.json
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, technical debt

#40651 refactor: Use DBAL's executeQuery instead of query (deprecated)
  lib/private/DB/Migrator.php
  lib/private/Repair/SqliteAutoincrement.php
Labels: 3. to review, technical debt

#39175 use square bracket syntax to modify array
  apps/settings/lib/Controller/UsersController.php
Labels: 3. to review, technical debt

#39213 Refactor "strpos" and "substr" calls in federatedfilesharing app to improve code readability
  apps/federatedfilesharing/lib/AddressHandler.php
  apps/federatedfilesharing/lib/Notifier.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
Labels: 3. to review, technical debt

#39236 Refactor comments app
  apps/comments/lib/Activity/Filter.php
  apps/comments/lib/Activity/Listener.php
  apps/comments/lib/Activity/Provider.php
  apps/comments/lib/Activity/Setting.php
  apps/comments/lib/Collaboration/CommentersSorter.php
  apps/comments/lib/Controller/NotificationsController.php
  apps/comments/lib/EventHandler.php
  apps/comments/lib/Listener/CommentsEntityEventListener.php
  apps/comments/lib/Listener/LoadSidebarScripts.php
  apps/comments/lib/MaxAutoCompleteResultsInitialState.php
  apps/comments/lib/Notification/Listener.php
  apps/comments/lib/Notification/Notifier.php
  apps/comments/lib/Search/CommentsSearchProvider.php
  apps/comments/lib/Search/LegacyProvider.php
  apps/comments/lib/Search/Result.php
Labels: 4. to release, technical debt

#40642 [stable27] fix: encode uri for trashbin delete
  apps/files_trashbin/src/actions/restoreAction.ts
  apps/files_trashbin/src/services/trashbin.ts
  dist/files_trashbin-main.js
  dist/files_trashbin-main.js.map
Labels: bug, 4. to release
