Repository nextcloud/server, pull requests merged in 2023-03, with the labels that each got.

#36930 fix(theming): logo missing on login page
  core/css/guest.css
  core/css/guest.css.map
  core/css/guest.scss
Labels: bug, design, 3. to review, feature: theming, regression

#36471 feat(theming): Only convert a background image if it benefits from it
  apps/theming/lib/ImageManager.php
  apps/theming/tests/ImageManagerTest.php
  tests/data/testimage-large.jpg
  tests/data/testimage.webp
Labels: enhancement, 4. to release, feature: theming

#36890 fix(translation): Allow regular users to use translation api endpoints
  core/Controller/TranslationApiController.php
Labels: bug, 3. to review

#36785 Add back authentication checkbox for mailer settings
  apps/settings/templates/settings/admin/additional-mail.php
Labels: 3. to review, regression, feature: emails

#36998 Fix share select dropdown not opening when viewer is open
  apps/files_sharing/src/components/SharingInput.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#36594 fix(caldav): Correctly handle calendar recreation for invitations when the current calendar is in the trashbin
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/tests/unit/CalDAV/Schedule/PluginTest.php
Labels: bug, 4. to release, feature: dav, feature: caldav

#36803 [db]: Remove not supported column comments for SQLite
  lib/private/DB/SQLiteMigrator.php
  tests/lib/DB/MigratorTest.php
Labels: bug, 3. to review, backport-request

#36935 fix(caldav): harden null handling of iMip scheduling method
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CalDAV/Schedule/IMipService.php
Labels: bug, 3. to review, feature: caldav

#36999 Various unified search fixes
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: bug, design, 4. to release, backport-request, feature: search, regression, technical debt

#37002 26.0.0 RC1
  version.php
Labels: 3. to review

#36173 Use a PHP implementation of openssl_seal that allows to use modern ciphers
  apps/encryption/lib/Crypto/Crypt.php
Labels: enhancement, 3. to review

#36847 fix right-click img tags
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review, backport-request

#36884 [CI] Update update-psalm-baseline workflow to solve warnings
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#37021 feat: Add notes as recommended app
  core/img/apps/notes.svg
  core/src/components/setup/RecommendedApps.vue
  dist/core-recommendedapps.js
  dist/core-recommendedapps.js.map
Labels: 3. to review

#37023 Master is now 27
  .drone.yml
  .github/dependabot.yml
  .github/workflows/update-cacert-bundle.yml
  apps/admin_audit/appinfo/info.xml
  apps/cloud_federation_api/appinfo/info.xml
  apps/comments/appinfo/info.xml
  apps/contactsinteraction/appinfo/info.xml
  apps/dashboard/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/lookup_server_connector/appinfo/info.xml
  apps/oauth2/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/settings/appinfo/info.xml
  apps/settings/lib/WellKnown/SecurityTxtHandler.php
  apps/sharebymail/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theming/appinfo/info.xml
  apps/twofactor_backupcodes/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  apps/user_ldap/appinfo/info.xml
  apps/user_status/appinfo/info.xml
  apps/weather_status/appinfo/info.xml
  apps/workflowengine/appinfo/info.xml
  version.php
Labels: 3. to review, backport-request

#37024 [stable26] Test against matching Talk version on stable branch
  .drone.yml
Labels: 4. to release

#36941 Split the comments ids by chunks
  lib/private/Comments/Manager.php
  tests/lib/Comments/ManagerTest.php
Labels: 3. to review, backport-request, feature: comments, php, skill:backend

#37028 Add distraction free backgrounds for Nextcloud 26
  apps/dashboard/README.md
  apps/theming/README.md
  apps/theming/img/background/hannah-maclean-soft-floral.jpg
  apps/theming/img/background/preview/hannah-maclean-soft-floral.jpg
  apps/theming/img/background/preview/stefanus-martanto-setyo-husodo-underwater-ocean.jpg
  apps/theming/img/background/preview/ted-moravec-morning-fog.jpg
  apps/theming/img/background/preview/zoltan-voros-rhythm-and-blues.jpg
  apps/theming/img/background/stefanus-martanto-setyo-husodo-underwater-ocean.jpg
  apps/theming/img/background/ted-moravec-morning-fog.jpg
  apps/theming/img/background/zoltan-voros-rhythm-and-blues.jpg
  apps/theming/lib/Service/BackgroundService.php
Labels: design, 4. to release, backport-request

#36736 Use proc_open to avoid spawning a shell
  lib/private/Preview/Movie.php
Labels: enhancement, 3. to review

#36740 Add avatar contact img description
  core/src/OC/contactsmenu.js
  core/src/OC/contactsmenu/contact.handlebars
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 4. to release, backport-request, feature: contacts menu, accessibility

#37048 update wording for disabled web updater
  core/ajax/update.php
Labels: bug, 3. to review, backport-request

#37040 techdebt(workflowengine): Remove transition event classes
  apps/workflowengine/lib/AppInfo/Application.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/autoload_static.php
  lib/public/WorkflowEngine/IEntityCompat.php
  lib/public/WorkflowEngine/IOperationCompat.php
Labels: 3. to review, technical debt

#35872 feat(appframework): ⌚ Make ITimeFactory extend \PSR\Clock\ClockInterface
  lib/private/AppFramework/Utility/TimeFactory.php
  lib/private/Server.php
  lib/public/AppFramework/Utility/ITimeFactory.php
  tests/lib/AppFramework/Utility/TimeFactoryTest.php
Labels: enhancement, 3. to review, pending documentation

#36886 [stable25] fix(CI): Run repair steps against Oracle DB
  .github/workflows/oci.yml
  apps/dav/lib/Migration/RemoveObjectProperties.php
  core/Command/Maintenance/Repair.php
  lib/private/AppConfig.php
  lib/private/Repair/NC21/ValidatePhoneNumber.php
Labels: bug, 3. to review

#36888 [stable24] fix(CI): Run repair steps against Oracle DB
  .github/workflows/oci.yml
  core/Command/Maintenance/Repair.php
  lib/private/AppConfig.php
  lib/private/Repair/NC21/ValidatePhoneNumber.php
Labels: 3. to review

#36904 fix(files): Fix controller setup for guests
  apps/files/lib/Service/TagService.php
Labels: bug, 3. to review, feature: files, feature: tags

#36189 [stable23] Ext storage configs default value support + enable SSL by default
  apps/files_external/js/settings.js
  apps/files_external/lib/Lib/Backend/AmazonS3.php
  apps/files_external/lib/Lib/Backend/DAV.php
  apps/files_external/lib/Lib/Backend/FTP.php
  apps/files_external/lib/Lib/Backend/OwnCloud.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/tests/DefinitionParameterTest.php
Labels: 3. to review

#36683 [stable25] Fix missing files:navigation:changed when clicking on a dir in the favorites view
  apps/files/js/app.js
Labels: bug, 2. developing, feature: files

#36772 Add label and switch ocdialog close button to button element
  core/src/jquery/css/jquery.ocdialog.scss
  core/src/jquery/ocdialog.js
  dist/core-main.js
  dist/core-main.js.map
Labels: 4. to release, backport-request, feature: filepicker, accessibility

#34835 Run WebDAV integration tests against S3
  .github/workflows/s3-primary-integration.yml
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
  apps/provisioning_api/lib/Controller/UsersController.php
  lib/private/Files/View.php
  lib/private/User/User.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, tests

#37068 [stable26] ci(performance): Use proper profiler branch for 26
  .github/workflows/performance.yml
Labels: 3. to review

#37026 fix: Avoid log spam on 404 routes not using GET
  lib/base.php
Labels: bug, 3. to review, backport-request

#37069 fix(CI): Fix acceptance test password field selector after @nextcloud…
  tests/acceptance/features/bootstrap/FilesAppSharingContext.php
Labels: bug, 3. to review, feature: sharing, backport-request

#36640 Create headings for apps, users, settings pages
  apps/settings/lib/Controller/AppSettingsController.php
  apps/settings/lib/Controller/UsersController.php
  apps/settings/src/router.js
  apps/settings/tests/Controller/AppSettingsControllerTest.php
  core/src/OCP/accessibility.js
  core/templates/layout.user.php
  dist/core-main.js
  dist/core-main.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.LICENSE.txt
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, backport-request, pending documentation

#32038 Add transaction around mass mounts operations
  lib/private/Files/Config/UserMountCache.php
Labels: bug, 3. to review, feature: filesystem

#37121 fix(docs): Fix URL to docs of deprecated function humanFileSize
  core/src/OC/util.js
  dist/core-login.js.map
  dist/core-main.js.map
Labels: bug, 3. to review, backport-request

#37124 Added .weba mime type mapping.
  resources/config/mimetypemapping.dist.json
Labels: enhancement, 3. to review

#37070 add a check for disk_free_space in Config.php
  lib/private/Config.php
Labels: bug, 3. to review, backport-request

#37126 fix white scrollbar corner in dark mode
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
Labels: bug, 3. to review, backport-request

#37140 imaginary - fix autorotate for heic and improve the logic
  lib/private/Preview/Imaginary.php
Labels: bug, 3. to review, backport-request

#37078 26.0.0 RC2
  version.php
Labels: 4. to release

#37167 fix(dav): Handle no next potential toggle in availability detection
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
Labels: bug, 3. to review, feature: status

#36800 apps/dav: add some OSX specific quirks.
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/AppleQuirksPlugin.php
  apps/dav/lib/Server.php
Labels: 3. to review, feature: dav, feature: caldav

#36852 fix(user_status): Fix the user status automation on the day availablity rules are adjusted
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
  apps/dav/tests/unit/BackgroundJob/UserStatusAutomationTest.php
Labels: bug, 3. to review, feature: dav, backport-request, feature: status

#37173 [stable23] fix possible PHP warning
  apps/workflowengine/lib/Check/FileSystemTags.php
Labels: bug, 3. to review

#35677 Introduced app enable/disable/update typed events
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/App/AppManager.php
  lib/private/Server.php
  lib/private/legacy/OC_App.php
  lib/public/App/Events/AppDisableEvent.php
  lib/public/App/Events/AppEnableEvent.php
  lib/public/App/Events/AppUpdateEvent.php
  tests/lib/App/AppManagerTest.php
  tests/lib/AppTest.php
Labels: 4. to release, feature: apps management, technical debt, php

#37029 Add chunking in SystemTagObjectMapper::getTagIdsForObjects
  lib/private/SystemTag/SystemTagObjectMapper.php
  tests/lib/SystemTag/SystemTagObjectMapperTest.php
Labels: bug, 3. to review, backport-request, feature: tags

#37010 Fix Cache-Control header of non-versioned assets
  .htaccess
Labels: enhancement, 3. to review, backport-request

#37168 fix(files_sharing): Allow file actions other than download for hide download shares
  apps/files_sharing/js/public.js
Labels: bug, 3. to review, backport-request

#37192 Don't try to hash a nonexisting password
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: bug, 3. to review, backport-request

#36744 [stable23] Fix login loop if login CSRF fails and user is not logged in
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: bug, 4. to release

#37166 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#37199 [stable26] fix(dav): Handle no next potential toggle in availability detection
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
Labels: bug, feature: status

#33061 Paths added to messages and message cleanup
  lib/private/Files/Node/Folder.php
Labels: 4. to release

#37216 [stable25] Add chunking in SystemTagObjectMapper::getTagIdsForObjects
  lib/private/SystemTag/SystemTagObjectMapper.php
  tests/lib/SystemTag/SystemTagObjectMapperTest.php
Labels: bug, 3. to review

#37200 [stable25] fix(dav): Handle no next potential toggle in availability detection
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
Labels: bug, feature: status

#37221 Save some CI time
  .github/workflows/cypress.yml
  .github/workflows/ftp.yml
  .github/workflows/node-tests.yml
  .github/workflows/oci.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-32bits.yml
  .github/workflows/s3-external.yml
  .github/workflows/s3-primary-integration.yml
  .github/workflows/s3-primary.yml
  .github/workflows/smb-kerberos.yml
  .github/workflows/stale.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review, backport-request

#37222 chore(psalm): Update psalm baseline also on stable26
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#37224 [stable26] Save some CI time
  .github/workflows/cypress.yml
  .github/workflows/ftp.yml
  .github/workflows/node-tests.yml
  .github/workflows/oci.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-32bits.yml
  .github/workflows/s3-external.yml
  .github/workflows/s3-primary.yml
  .github/workflows/smb-kerberos.yml
  .github/workflows/stale.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#37225 [stable25] Save some CI time
  .github/workflows/ftp.yml
  .github/workflows/node-tests.yml
  .github/workflows/oci.yml
  .github/workflows/performance.yml
  .github/workflows/s3-external.yml
  .github/workflows/s3-primary.yml
  .github/workflows/smb-kerberos.yml
  .github/workflows/stale.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
Labels: 3. to review

#35610 Add a command to update the 3rdparty submodule to the same branch as …
  .github/workflows/command-pull-3rdparty.yml
  README.md
Labels: 2. developing, do not merge

#36033 [master] invalidate existing tokens when deleting an oauth client
  apps/oauth2/lib/Controller/SettingsController.php
  apps/oauth2/tests/Controller/SettingsControllerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Token/Manager.php
  lib/private/Server.php
  lib/public/Authentication/Token/IProvider.php
  tests/lib/Authentication/Token/ManagerTest.php
Labels: 3. to review

#35650 [stable25] Add brute force protection on all methods wrapped by PublicShareMiddleware
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/PublicShare/PublicShareMiddleware.php
  tests/lib/AppFramework/Middleware/PublicShare/PublicShareMiddlewareTest.php
Labels: 4. to release, feature: sharing

#35652 [stable23] Add brute force protection on all methods wrapped by PublicShareMiddleware
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/PublicShare/PublicShareMiddleware.php
  tests/lib/AppFramework/Middleware/PublicShare/PublicShareMiddlewareTest.php
Labels: 4. to release, feature: sharing

#35651 [stable24] Add brute force protection on all methods wrapped by PublicShareMiddleware
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/PublicShare/PublicShareMiddleware.php
  tests/lib/AppFramework/Middleware/PublicShare/PublicShareMiddlewareTest.php
Labels: 4. to release, feature: sharing

#37218 [stable26] fix(user_status): Fix the user status automation on the day availablity rules are adjusted
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
  apps/dav/tests/unit/BackgroundJob/UserStatusAutomationTest.php
Labels: bug, 3. to review

#37197 Do not send a pagination control with size = 0 if cookie is empty
  apps/user_ldap/lib/LDAP.php
Labels: bug, 3. to review, backport-request, 26-feedback

#36899 [stable25] fix(SystemTagManager): Truncate overlong tag names
  lib/private/SystemTag/SystemTagManager.php
  tests/lib/SystemTag/SystemTagManagerTest.php
Labels: 3. to review

#36900 [stable24] fix(SystemTagManager): Truncate overlong tag names
  lib/private/SystemTag/SystemTagManager.php
  tests/lib/SystemTag/SystemTagManagerTest.php
Labels: 3. to review

#37212 [stable26] Add chunking in SystemTagObjectMapper::getTagIdsForObjects
  lib/private/SystemTag/SystemTagObjectMapper.php
  tests/lib/SystemTag/SystemTagObjectMapperTest.php
Labels: bug, 3. to review

#37227 chore: use local variable for remote address
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 4. to release, backport-request

#35561 Create the users from database backend in a transaction
  lib/private/User/Database.php
Labels: bug, 4. to release, feature: users and groups, skill:backend

#37239 Extend list
  lib/public/IRequest.php
Labels: 3. to review, backport-request

#37242 Reduce list
  lib/public/IRequest.php
Labels: 4. to release, backport-request

#37256 [stable24] fix(workflow): Check tag attribute
  apps/workflowengine/lib/Check/FileSystemTags.php
Labels: 3. to review, feature: workflows

#37255 [stable25] fix(workflow): Check tag attribute
  apps/workflowengine/lib/Check/FileSystemTags.php
Labels: 3. to review, feature: workflows

#37152 Use native tooltip for version's date
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review, backport-request

#36661 Invitation mail: Change subject if event got updated
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CalDAV/Schedule/IMipService.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: 4. to release

#37202 26.0.0 RC3
  version.php
Labels: 3. to review

#37232 Set <h1> headings for navigation through files app
  apps/files/js/navigation.js
Labels: 3. to review

#37262 Fix controller class import for autocomplete
  core/Controller/AutoCompleteController.php
Labels: 3. to review

#37174 Set `<h1>` headings for navigation through files app
  apps/files/src/views/Navigation.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 4. to release, backport-request

#37257 [stable23] fix(workflow): Check tag attribute
  apps/workflowengine/lib/Check/FileSystemTags.php
Labels: 4. to release, feature: workflows

#37258 [stable22] fix(workflow): Check tag attribute
  apps/workflowengine/lib/Check/FileSystemTags.php
Labels: 3. to review, feature: workflows

#37260 [stable20] fix(workflow): Check tag attribute
  apps/workflowengine/lib/Check/FileSystemTags.php
Labels: 4. to release, feature: workflows

#37244 Replace custom tooltips with native ones and add description to all e…
  apps/user_ldap/js/wizard/view.js
  apps/user_ldap/templates/part.wizard-groupfilter.php
  apps/user_ldap/templates/part.wizard-loginfilter.php
  apps/user_ldap/templates/part.wizard-server.php
  apps/user_ldap/templates/part.wizard-userfilter.php
  apps/user_ldap/templates/renewpassword.php
  apps/user_ldap/templates/settings.php
Labels: 4. to release, backport-request

#36114 perf(autoloader): Drop legacy class autoloader
  lib/private/legacy/OC_App.php
Labels: 3. to review, technical debt, pending documentation, performance 🚀

#37204 24.0.11 RC1
  version.php
Labels: 3. to review

#37203 25.0.5 RC1
  version.php
Labels: 3. to review

#37269 fix: add important to css hidden files class
  apps/files/css/files.css
  apps/files/css/files.css.map
  apps/files/css/files.scss
  apps/files/css/merged.css
  apps/files/css/merged.css.map
Labels: 4. to release, backport-request, papercut

#37271 Fix description for icons in dashboard widgets
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: 3. to review, backport-request, accessibility

#36591 Refactor app loading
  lib/private/App/AppManager.php
  lib/private/legacy/OC_App.php
  lib/public/App/IAppManager.php
  tests/lib/Preview/BackgroundCleanupJobTest.php
Labels: 3. to review, performance 🚀

#37006 also unmark deleted ldap user when checking the ldap entry
  apps/user_ldap/lib/User_LDAP.php
Labels: bug, 3. to review, feature: ldap, backport-request

#37310 [stable26] fix(session): Fix DAVx5 sync problems by partial reverting session ch…
  lib/base.php
Labels: bug, 4. to release, feature: dav, feature: caldav

#36701 Add parent index on filecache
  core/Application.php
  core/Command/Db/AddMissingIndices.php
  core/Migrations/Version13000Date20170718121200.php
Labels: 4. to release, backport-request, php

#37306 fix(session): Fix DAVx5 sync problems by partial reverting session changes
  lib/base.php
Labels: bug, 4. to release, feature: dav, backport-request, feature: authentication

#37313 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#37312 26.0.0
  version.php
Labels: 3. to review

#37305 fix(security): Log failing strict cookie check
  lib/base.php
Labels: 4. to release, security, technical debt

#36057 Allow apps to include module js / ES6 scripts
  .htaccess
  lib/private/Template/JSResourceLocator.php
  lib/private/legacy/template/functions.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/TemplateFunctionsTest.php
Labels: enhancement, 3. to review

#37334 fix(security): Mark recording_servers key appconfig as private as it …
  lib/private/AppConfig.php
Labels: bug, 3. to review, backport-request

#36665 Always set displayname and display-name for user data
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/UsersController.php
  lib/public/Accounts/IAccountManager.php
Labels: 3. to review, integration, pending documentation

#37354 25.0.5
  version.php
Labels: 4. to release

#36636 fix OC_Image: Prevent E_WARNING from getimagesize*
  lib/private/legacy/OC_Image.php
Labels: bug, 3. to review, backport-request, technical debt

#37234 Fix the typo in comments
  lib/private/Share/Share.php
Labels: 4. to release

#37265 l10n: Spelling unification
  apps/dashboard/appinfo/info.xml
  apps/encryption/appinfo/info.xml
  apps/settings/src/components/PersonalInfo/AvatarSection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 3. to review, feature: language l10n and translations

#37361 Adjust provisioning API tests after #36665
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
Labels: 3. to review, feature: users and groups, tests

#37363 Fix alt attrs for images in files versions
  apps/files_versions/src/templates/item.handlebars
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: 3. to review

#37337 [stable25] Fix/36908 set aria hidden for default shipped widgets icons
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: 4. to release, accessibility

#36580 [stable24] fix(user-management): Fix deleting user in hidden group(s)
  apps/settings/src/store/users.js
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: users and groups

#37338 [stable26] Fix/36908 set aria hidden for default shipped widgets icons
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: 3. to review

#37211 Create `<h3>` headings for profile page. Replace `<label>` which have…
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  apps/settings/js/federationsettingsview.js
  apps/settings/src/components/PersonalInfo/AvatarSection.vue
  apps/settings/src/components/PersonalInfo/DetailsSection.vue
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/ProfileVisibilitySection.vue
  apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 4. to release, backport-request

#37384 ci(psalm): Install ftp+ldap extension for security scans
  .github/workflows/static-code-analysis.yml
Labels: 3. to review, security, technical debt

#37340 fix(mailer): remove value comparison for smtp_authtype as there is only one option
  apps/settings/templates/settings/admin/additional-mail.php
Labels: 3. to review, backport-request, feature: emails, 26-feedback

#36810 do onetime user setup before getting any mount from providers
  lib/private/Files/SetupManager.php
Labels: 3. to review, backport-request

#37397 check-setup: recommend exif extension
  apps/settings/lib/Controller/CheckSetupController.php
Labels: 4. to release

#37416 Add back missing dashboard version
  apps/dashboard/appinfo/info.xml
Labels: 3. to review, high, regression

#37217 [stable26] Don't try to hash a nonexisting password
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: bug, 3. to review

#36605 [stable25] fix: Make sure to reopen session before cleaning
  lib/private/Session/CryptoSessionData.php
Labels: bug, 3. to review

#37364 Ask for Nextcloud version on issue reporting
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 3. to review

#37421 Change contactsmenu structure to a list
  core/src/OC/contactsmenu.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review, backport-request

#37198 fix(references): Do not log errors on 404 responses of opengraph image fetching
  lib/private/Collaboration/Reference/LinkReferenceProvider.php
Labels: bug, 3. to review, backport-request

#37437 fix(docs): Fix RST parsing of the sample config
  config/config.sample.php
Labels: 3. to review, backport-request

#37440 [stable26] fix(references): Do not log errors on 404 responses of opengraph image fetching
  lib/private/Collaboration/Reference/LinkReferenceProvider.php
Labels: bug, 3. to review

#37431 Backport/stable26/jerome herbinet/patch 15
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
Labels: bug, 3. to review, backport-request, javascript

#37405 Send Clear-Site-Data header and let browsers ignore it if unsupported
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: enhancement, 4. to release

#37449 Fix/36917 the statuses list was implemented semantically incorrectly
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: backport-request

#37423 Replace custom tooltips with native ones of entries in contacts menu.
  core/src/OC/contactsmenu.js
  core/src/OC/contactsmenu/contact.handlebars
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review, backport-request

#36667 Fix OCM validation errors
  lib/public/Federation/Exceptions/BadRequestException.php
Labels: 3. to review

#37435 Add label for logo link
  core/templates/layout.user.php
  lib/private/App/AppManager.php
  lib/private/TemplateLayout.php
  lib/private/URLGenerator.php
  lib/public/App/IAppManager.php
  tests/lib/App/AppManagerTest.php
  tests/lib/UrlGeneratorTest.php
Labels: 4. to release, backport-request, accessibility

#37425 Fix version number in phpdoc for app loading refactor
  lib/private/legacy/OC_App.php
  lib/public/App/IAppManager.php
Labels: enhancement, 3. to review, pending documentation

#37378 fix the avatar generation on Alpine Linux
  lib/private/Avatar/Avatar.php
Labels: bug, 3. to review, backport-request

#37452 Add missing interface methods
  apps/dav/lib/CalDAV/CachedSubscription.php
  apps/dav/lib/CardDAV/AddressBook.php
  apps/provisioning_api/lib/Controller/AUserData.php
  core/Controller/LoginController.php
  lib/private/Collaboration/Resources/Collection.php
  lib/private/NavigationManager.php
  lib/private/Repair/NC16/ClearCollectionsAccessCache.php
  lib/private/Updater.php
Labels: 4. to release

#37483 [stable25] Change contactsmenu structure to a list
  core/src/OC/contactsmenu.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review

#37486 fix default_language doc
  config/config.sample.php
Labels: bug, 4. to release, backport-request

#37485 [stable26] Change contactsmenu structure to a list
  core/src/OC/contactsmenu.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review

#37478 String fix
  .gitignore
  apps/encryption/appinfo/info.xml
Labels: 3. to review

#37497 Improve handling of profile fields
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
  apps/settings/src/components/PersonalInfo/LanguageSection/Language.vue
  apps/settings/src/components/PersonalInfo/LocaleSection/Locale.vue
  apps/settings/src/components/PersonalInfo/ProfileSection/ProfileCheckbox.vue
  apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/VisibilityDropdown.vue
  apps/settings/src/components/PersonalInfo/shared/AccountPropertySection.vue
  apps/settings/src/components/PersonalInfo/shared/FederationControl.vue
  apps/settings/src/utils/handlers.js
  core/Controller/ProfileApiController.php
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 3. to review, backport-request
