Repository nextcloud/server, pull requests merged in 2023-11, with the labels that each got.

#40733 ci: skip puppeteer chrome download
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-tests.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
Labels: 4. to release, technical debt

#40819 Catch Imaginary processing errors
  lib/private/Preview/Imaginary.php
Labels: 4. to release, backport-request

#40946 [stable26] Fix download URL for versions
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review, feature: versions

#41224 [stable26] fix(files): race condition on web files view change
  apps/files/js/app.js
  apps/files/js/filelist.js
  apps/files/src/views/Navigation.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files, regression

#41230 fix: add index on migration only if needed
  core/Migrations/Version28000Date20230803221055.php
Labels: 3. to review, backport-request

#40899 refactor: Unify running a dev server (for automated testing)
  composer.json
Labels: 4. to release, pending documentation

#40859 fix(session): Log why session renewal failed
  lib/private/User/Session.php
Labels: 4. to release, backport-request

#40665 fix(dav): Reduce CalDAV backend memory footprint
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: bug, 3. to review, backport-request

#41228 chore: 28.0.0 beta 1
  version.php
Labels: 3. to review, automated, ❄️ 2023-Winter

#41246 fix(upgrade): files_rightclick is deprecated
  core/shipped.json
Labels: bug, 3. to review

#41137 chore(cypress): Migrate access-level tests from Behat to Cypress
  .drone.yml
  cypress/e2e/core/header_access-levels.cy.ts
  cypress/e2e/login/login.cy.ts
  cypress/e2e/settings/access-levels.cy.ts
  cypress/e2e/settings/usersUtils.ts
  cypress/e2e/settings/users_disable.cy.ts
  cypress/e2e/settings/users_modify.cy.ts
  cypress/support/commonUtils.ts
  tests/acceptance/features/access-levels.feature
  tests/acceptance/features/header.feature
Labels: 3. to review, tests, CI

#40597 fix(theming): Make sure the footer is hidden if no content is rendered
  apps/theming/lib/ThemingDefaults.php
  core/css/guest.css
  core/css/guest.css.map
  core/css/guest.scss
  core/templates/layout.guest.php
  core/templates/layout.public.php
  themes/example/defaults.php
Labels: bug, design, 3. to review, backport-request

#41250 fix(cypress): Add timeout for waiting on Nextcloud server
  cypress/dockerNode.ts
  package-lock.json
  package.json
Labels: bug, 3. to review, CI

#41265 feat(dependencyinjection): Allow optional (nullable) services
  lib/private/AppFramework/Utility/SimpleContainer.php
  tests/lib/AppFramework/Utility/SimpleContainerTest.php
Labels: enhancement, 3. to review

#41256 add descriptions for background pictures
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/src/components/BackgroundSettings.vue
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
Labels: 3. to review, accessibility

#41263 fix semaphore unguarding
  build/psalm-baseline.xml
  lib/private/Preview/Generator.php
Labels: bug, 3. to review, high, backport-request

#40995 optimize cache jail creation
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Storage/Wrapper/Jail.php
Labels: 3. to review, performance 🚀

#41059 fix(theming): Correctly expose user and admin theming
  apps/theming/lib/Capabilities.php
  apps/theming/tests/CapabilitiesTest.php
Labels: bug, 3. to review

#41151 [stable26] fix(OCM): Make the public API only rely on OCP
  lib/private/OCM/Model/OCMProvider.php
  lib/private/OCM/Model/OCMResource.php
  lib/public/OCM/IOCMProvider.php
  lib/public/OCM/IOCMResource.php
Labels: bug, 3. to review, feature: federation

#41173 fix: Delete ghost versions of non-existing files
  apps/files_versions/lib/Storage.php
Labels: bug, 3. to review, feature: versions

#41078 Update openapi extractor
  apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
  apps/cloud_federation_api/lib/ResponseDefinitions.php
  apps/files/appinfo/routes.php
  apps/files_external/lib/Controller/ApiController.php
  apps/files_external/lib/Lib/StorageConfig.php
  apps/files_external/lib/ResponseDefinitions.php
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
  apps/files_sharing/lib/Controller/RemoteController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/Controller/ShareInfoController.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/lib/ResponseDefinitions.php
  apps/provisioning_api/lib/Controller/AUserData.php
  apps/provisioning_api/lib/Controller/AppsController.php
  apps/provisioning_api/lib/Controller/GroupsController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/lib/ResponseDefinitions.php
  apps/settings/appinfo/routes.php
  apps/sharebymail/openapi.json
  apps/updatenotification/lib/Controller/APIController.php
  apps/updatenotification/lib/ResponseDefinitions.php
  apps/user_status/openapi.json
  build/openapi-checker.sh
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, dependencies

#41289 [stable27] fix semaphore unguarding
  build/psalm-baseline.xml
  lib/private/Preview/Generator.php
Labels: bug, 3. to review, high

#41190 chore(cypress): Migrate header contacts menu tests from Behat to Cypress
  .drone.yml
  cypress/e2e/core/header_contacts-menu.cy.ts
  cypress/support/commands.ts
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/ThemingAppContext.php
  tests/acceptance/features/header.feature
Labels: 3. to review, tests, CI

#41081 Add a command to run the setup checks from CLI
  core/Command/SetupChecks.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review, pending documentation

#41251 fix: Only highlight profile entry when viewing own profile
  core/Controller/ProfilePageController.php
Labels: bug, 4. to release

#40876 fix(scheduling): don't send iMIP emails to rooms / resources
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CalDAV/Schedule/IMipService.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: bug, 3. to review, backport-request, feature: caldav

#40809 Update README.md
  README.md
Labels: 3. to review

#41106 [stable27] fix(ldap): store last known user groups
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Group_Proxy.php
  apps/user_ldap/tests/Group_LDAPTest.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestAttributeDetection.php
Labels: bug, 3. to review, feature: ldap

#41175 Add OpenAPI attribute to allow multiple scopes
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/Http/Attribute/IgnoreOpenAPI.php
  lib/public/AppFramework/Http/Attribute/OpenAPI.php
Labels: enhancement, 3. to review, pending documentation

#41214 fix(install): Make installing more verbose
  core/Command/Maintenance/Install.php
  lib/private/Console/TimestampFormatter.php
  lib/private/DB/MigrationService.php
  lib/private/Installer.php
  lib/private/Migration/ConsoleOutput.php
  lib/private/Migration/SimpleOutput.php
  lib/private/Repair.php
  lib/private/Setup.php
  lib/private/Setup/AbstractDatabase.php
  lib/public/Migration/IOutput.php
Labels: bug, 3. to review, feature: install and update

#41083 Improve setup checks naming and improve database version check
  apps/dav/lib/SetupChecks/NeedsSystemAddressBookSync.php
  apps/settings/lib/SetupChecks/CheckUserCertificates.php
  apps/settings/lib/SetupChecks/DefaultPhoneRegionSet.php
  apps/settings/lib/SetupChecks/LegacySSEKeyFormat.php
  apps/settings/lib/SetupChecks/PhpDefaultCharset.php
  apps/settings/lib/SetupChecks/PhpOutdated.php
  apps/settings/lib/SetupChecks/PhpOutputBuffering.php
  apps/settings/lib/SetupChecks/ReadOnlyConfig.php
  apps/settings/lib/SetupChecks/SupportedDatabase.php
  apps/user_ldap/lib/SetupChecks/LdapInvalidUuids.php
Labels: enhancement, 3. to review

#41270 Fix styles for input fields on focus state
  core/src/views/ContactsMenu.vue
  core/src/views/UnifiedSearch.vue
  dist/core-main.js
  dist/core-main.js.map
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 3. to review

#41294 Update supported versions on issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 3. to review

#41298 fix description of sharing toggle
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files_sharing/src/actions/sharingStatusAction.ts
  dist/files-main.js
  dist/files-main.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 4. to release, feature: sharing, feature: files, papercut

#41311 Improve setup checks API
  apps/settings/lib/SetupChecks/PhpModules.php
  core/Command/SetupChecks.php
  lib/private/SetupCheck/SetupCheckManager.php
  lib/public/SetupCheck/ISetupCheck.php
  lib/public/SetupCheck/SetupResult.php
Labels: bug, 3. to review

#40761 IFilesMetadata
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Files/FileSearchBackend.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/FileSearchBackendTest.php
  apps/files/lib/Command/Scan.php
  apps/files_trashbin/lib/Trash/TrashItem.php
  core/Command/FilesMetadata/Get.php
  core/Migrations/Version28000Date20231004103301.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/Node.php
  lib/private/Files/Search/QueryOptimizer/PathPrefixOptimizer.php
  lib/private/Files/Search/SearchComparison.php
  lib/private/Files/Search/SearchOrder.php
  lib/private/FilesMetadata/FilesMetadataManager.php
  lib/private/FilesMetadata/Job/UpdateSingleMetadata.php
  lib/private/FilesMetadata/Listener/MetadataDelete.php
  lib/private/FilesMetadata/Listener/MetadataUpdate.php
  lib/private/FilesMetadata/Model/FilesMetadata.php
  lib/private/FilesMetadata/Model/MetadataQuery.php
  lib/private/FilesMetadata/Model/MetadataValueWrapper.php
  lib/private/FilesMetadata/Service/IndexRequestService.php
  lib/private/FilesMetadata/Service/MetadataRequestService.php
  lib/private/Server.php
  lib/public/Files/FileInfo.php
  lib/public/Files/Search/ISearchComparison.php
  lib/public/Files/Search/ISearchOrder.php
  lib/public/FilesMetadata/AMetadataEvent.php
  lib/public/FilesMetadata/Event/MetadataBackgroundEvent.php
  lib/public/FilesMetadata/Event/MetadataLiveEvent.php
  lib/public/FilesMetadata/Exceptions/FilesMetadataException.php
  lib/public/FilesMetadata/Exceptions/FilesMetadataKeyFormatException.php
  lib/public/FilesMetadata/Exceptions/FilesMetadataNotFoundException.php
  lib/public/FilesMetadata/Exceptions/FilesMetadataTypeException.php
  lib/public/FilesMetadata/IFilesMetadataManager.php
  lib/public/FilesMetadata/Model/IFilesMetadata.php
  lib/public/FilesMetadata/Model/IMetadataQuery.php
  lib/public/FilesMetadata/Model/IMetadataValueWrapper.php
Labels: enhancement, 2. developing, pending documentation, ❄️ 2023-Winter

#41303 chore(cypress): Migrate apps acceptance tests to Cypress
  .drone.yml
  cypress/e2e/login/login.cy.ts
  cypress/e2e/settings/apps.cy.ts
  tests/acceptance/composer.json
  tests/acceptance/composer.lock
  tests/acceptance/config/behat.yml
  tests/acceptance/config/firefox-profiles/css-grid-enabled.zip
  tests/acceptance/features/app-comments.feature
  tests/acceptance/features/apps.feature
  tests/acceptance/features/bootstrap/AppNavigationContext.php
  tests/acceptance/features/bootstrap/AppSettingsContext.php
  tests/acceptance/features/bootstrap/AppsManagementContext.php
  tests/acceptance/features/bootstrap/CommentsAppContext.php
  tests/acceptance/features/bootstrap/ContactsMenuContext.php
  tests/acceptance/features/bootstrap/DialogContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FileListAncestorSetter.php
  tests/acceptance/features/bootstrap/FileListContext.php
  tests/acceptance/features/bootstrap/FilesAppContext.php
  tests/acceptance/features/bootstrap/FilesAppSharingContext.php
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/bootstrap/PublicShareContext.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/SettingsContext.php
  tests/acceptance/features/bootstrap/SettingsMenuContext.php
  tests/acceptance/features/bootstrap/ToastContext.php
  tests/acceptance/features/bootstrap/WaitFor.php
  tests/acceptance/features/core/Actor.php
  tests/acceptance/features/core/ActorAware.php
  tests/acceptance/features/core/ActorAwareInterface.php
  tests/acceptance/features/core/ActorContext.php
  tests/acceptance/features/core/ElementFinder.php
  tests/acceptance/features/core/ElementWrapper.php
  tests/acceptance/features/core/Locator.php
  tests/acceptance/features/core/NextcloudTestServerContext.php
  tests/acceptance/features/core/NextcloudTestServerHelper.php
  tests/acceptance/features/core/NextcloudTestServerLocalApacheHelper.php
  tests/acceptance/features/core/NextcloudTestServerLocalBuiltInHelper.php
  tests/acceptance/features/core/NoSuchElementException.php
  tests/acceptance/features/core/Utils.php
  tests/acceptance/installAndConfigureServer.sh
  tests/acceptance/run-local.sh
  tests/acceptance/run.sh
Labels: 3. to review, tests, CI

#41329 fix(files): Do not encode the path twice (and do not use undefined method)
  apps/files/src/actions/moveOrCopyAction.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, files2vue

#39109 Refactors /Metadata, /Migration, and /Net namespaces in /lib/private/
  lib/private/Metadata/Capabilities.php
  lib/private/Metadata/FileEventListener.php
  lib/private/Metadata/MetadataManager.php
  lib/private/Metadata/Provider/ExifProvider.php
  lib/private/Migration/BackgroundRepair.php
  lib/private/Migration/ConsoleOutput.php
  lib/private/Migration/SimpleOutput.php
  lib/private/Net/HostnameClassifier.php
  lib/private/Net/IpAddressClassifier.php
Labels: 3. to review, technical debt

#38995 Refactors lib/private/SystemTag
  lib/private/SystemTag/ManagerFactory.php
  lib/private/SystemTag/SystemTag.php
  lib/private/SystemTag/SystemTagManager.php
  lib/private/SystemTag/SystemTagObjectMapper.php
  lib/private/SystemTag/SystemTagsInFilesDetector.php
Labels: 3. to review, technical debt

#41107 [stable26] fix(ldap): store last known user groups
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Group_Proxy.php
  apps/user_ldap/tests/Group_LDAPTest.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestAttributeDetection.php
Labels: bug, 3. to review, feature: ldap

#41328 Fix styles for input field and textarea on focus, hover and active state
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
Labels: 3. to review

#40767 feat(dav): implement personal absence settings
  apps/dav/appinfo/routes.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Controller/AvailabilitySettingsController.php
  apps/dav/lib/Settings/AvailabilitySettings.php
  apps/dav/src/components/AbsenceForm.vue
  apps/dav/src/components/AvailabilityForm.vue
  apps/dav/src/utils/date.js
  apps/dav/src/views/Availability.vue
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.LICENSE.txt
  dist/dav-settings-personal-availability.js.map
Labels: enhancement, 3. to review, feature: dav

#41331 fix(files): add missing `Overwrite: F` header in renaming
  apps/files/src/components/FileEntry/FileEntryName.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files

#41215 [stable27] fix(install): Make installing more verbose
  core/Command/Maintenance/Install.php
  lib/private/Console/TimestampFormatter.php
  lib/private/DB/MigrationService.php
  lib/private/Installer.php
  lib/private/Migration/ConsoleOutput.php
  lib/private/Migration/SimpleOutput.php
  lib/private/Repair.php
  lib/private/Setup.php
  lib/private/Setup/AbstractDatabase.php
  lib/public/Migration/IOutput.php
Labels: bug, 3. to review, feature: install and update

#40996 reuse sharing disabled state when listing folder content
  lib/private/Files/View.php
Labels: 3. to review, performance 🚀

#40799 fix: Show error message when CSRF check fails at login
  core/Controller/LoginController.php
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
  lib/private/Authentication/Login/LoginResult.php
Labels: bug, 4. to release, backport-request, feature: authentication

#40964 Support dynamic metadata request on PROPFIND requests
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Files/FileSearchBackend.php
  apps/dav/tests/unit/Connector/Sabre/FilesPluginTest.php
  apps/files/lib/Command/Scan.php
  apps/files_trashbin/lib/Trashbin.php
  core/Application.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/FilesMetadata/FilesMetadataManager.php
  lib/private/FilesMetadata/Listener/MetadataUpdate.php
  lib/private/FilesMetadata/Model/FilesMetadata.php
  lib/private/FilesMetadata/Service/IndexRequestService.php
  lib/private/Metadata/Capabilities.php
  lib/private/Metadata/FileEventListener.php
  lib/private/Metadata/FileMetadata.php
  lib/private/Metadata/FileMetadataMapper.php
  lib/private/Metadata/IMetadataManager.php
  lib/private/Metadata/IMetadataProvider.php
  lib/private/Metadata/MetadataManager.php
  lib/private/Metadata/Provider/ExifProvider.php
  lib/private/Server.php
  lib/public/FilesMetadata/IFilesMetadataManager.php
  lib/public/FilesMetadata/Model/IFilesMetadata.php
  tests/lib/Metadata/FileMetadataMapperTest.php
Labels: 2. developing, feature: files, php, pending documentation

#41054 get children from dav node when preloading system tags
  apps/dav/lib/SystemTag/SystemTagPlugin.php
Labels: 3. to review, performance 🚀

#41119 optimize builtin storage wrappers
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/External/Mount.php
  apps/files_sharing/lib/ISharedMountPoint.php
  apps/files_sharing/lib/SharedMount.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Mount/HomeMountPoint.php
  lib/private/Files/Mount/LocalHomeMountProvider.php
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/SetupManager.php
  tests/lib/Files/FileInfoTest.php
Labels: 3. to review, performance 🚀

#41266 feat(contactsmenu): Sort by user status
  apps/user_status/lib/ContactsMenu/StatusProvider.php
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/Contacts/ContactsMenu/Entry.php
  lib/private/Contacts/ContactsMenu/Manager.php
  lib/public/Contacts/ContactsMenu/IEntry.php
  tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
  tests/lib/Contacts/ContactsMenu/EntryTest.php
  tests/lib/Contacts/ContactsMenu/ManagerTest.php
Labels: enhancement, 4. to release, feature: contacts menu

#41351 fix(migration): Fix files metadata migration
  core/Migrations/Version28000Date20231004103301.php
  version.php
Labels: 3. to review, feature: install and update, regression

#41349 fix(settings): Pass user object to user row actions
  apps/settings/src/components/Users/UserRow.vue
  apps/settings/src/components/Users/UserRowActions.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, feature: settings, regression

#41295 fix(JobList#hasReservedJob): Break tie when multiple jobs are reserved
  lib/private/BackgroundJob/JobList.php
  lib/public/BackgroundJob/IJobList.php
Labels: backport-request

#41339 Add two more translations for `CalendarAvailability`
  apps/dav/src/components/AvailabilityForm.vue
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
Labels: bug, 4. to release, feature: language l10n and translations

#39582 Simplify IP address normalizer with IP masks
  lib/private/Security/Normalizer/IpAddress.php
Labels: enhancement

#40653 feat: Add out-of-office message API
  apps/dav/appinfo/routes.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Controller/OutOfOfficeController.php
  apps/dav/lib/Db/Absence.php
  apps/dav/lib/ResponseDefinitions.php
  apps/dav/lib/Service/AbsenceService.php
  apps/dav/openapi.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/User/AvailabilityCoordinator.php
  lib/private/User/OutOfOfficeData.php
  lib/public/User/Events/OutOfOfficeChangedEvent.php
  lib/public/User/Events/OutOfOfficeClearedEvent.php
  lib/public/User/Events/OutOfOfficeScheduledEvent.php
  lib/public/User/IAvailabilityCoordinator.php
  lib/public/User/IOutOfOfficeData.php
  tests/lib/User/AvailabilityCoordinatorTest.php
Labels: 3. to review, feature: users and groups, integration, pending documentation

#40615 feat(user status): automate user status for events
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/FreeBusy/FreeBusyGenerator.php
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/lib/CalDAV/Status/Status.php
  apps/dav/lib/CalDAV/Status/StatusService.php
  apps/dav/tests/unit/CalDAV/Status/StatusServiceTest.php
  apps/user_status/lib/Db/UserStatusMapper.php
  apps/user_status/lib/Listener/UserLiveStatusListener.php
  apps/user_status/lib/Service/PredefinedStatusService.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/src/mixins/OnlineStatusMixin.js
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
  dist/user_status-menu.js
  dist/user_status-menu.js.map
  lib/public/UserStatus/IUserStatus.php
Labels: enhancement, 3. to review, pending documentation, feature: status, feature: caldav

#41333 fix(LDAP): prevent incomplete displaynames…
  apps/user_ldap/lib/Group_LDAP.php
Labels: bug, 3. to review, feature: ldap, backport-request

#41357 [stable26] Fix type in BeforeMessageLoggedEvent
  lib/public/Log/BeforeMessageLoggedEvent.php
Labels: bug, 4. to release

#41365 fix(events): Make sure all `\OCP\Files::…` events are emitted with th…
  lib/private/Files/Node/Node.php
Labels: bug, 4. to release, feature: filesystem, backport-request, feature: workflows

#41354 fix: Validate that we have a proper distributed cache configured
  apps/dav/lib/Upload/ChunkingV2Plugin.php
Labels: bug, 3. to review, backport-request

#40618 Advanced search: backend allows multiples terms to search
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Search/ContactsSearchProvider.php
  apps/dav/lib/Search/EventsSearchProvider.php
  apps/dav/lib/Search/TasksSearchProvider.php
  apps/dav/tests/unit/Search/ContactsSearchProviderTest.php
  apps/dav/tests/unit/Search/EventsSearchProviderTest.php
  apps/dav/tests/unit/Search/TasksSearchProviderTest.php
  apps/files/lib/Search/FilesSearchProvider.php
  core/Controller/UnifiedSearchController.php
  core/ResponseDefinitions.php
  core/openapi.json
  lib/composer/composer/InstalledVersions.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/installed.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/Search/Filter/BooleanFilter.php
  lib/private/Search/Filter/DateTimeFilter.php
  lib/private/Search/Filter/FloatFilter.php
  lib/private/Search/Filter/GroupFilter.php
  lib/private/Search/Filter/IntegerFilter.php
  lib/private/Search/Filter/StringFilter.php
  lib/private/Search/Filter/StringsFilter.php
  lib/private/Search/Filter/UserFilter.php
  lib/private/Search/FilterCollection.php
  lib/private/Search/FilterFactory.php
  lib/private/Search/SearchComposer.php
  lib/private/Search/SearchQuery.php
  lib/private/Search/UnsupportedFilter.php
  lib/public/Search/FilterDefinition.php
  lib/public/Search/IFilter.php
  lib/public/Search/IFilterCollection.php
  lib/public/Search/IFilteringProvider.php
  lib/public/Search/ISearchQuery.php
Labels: 2. developing, pending documentation

#41314 28.0.0 beta 2
  version.php
Labels: 3. to review

#41302 Lower log level about invalid session token
  lib/private/User/Session.php
Labels: 3. to review, backport-request

#41385 Chore/update twitter to x in personal settings
  apps/settings/src/components/PersonalInfo/TwitterSection.vue
  apps/settings/src/constants/AccountPropertyConstants.js
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 4. to release

#41041 Updated visible 'Twitter' name to 'X' in Personal info
  apps/settings/src/components/PersonalInfo/TwitterSection.vue
  apps/settings/src/constants/AccountPropertyConstants.js
Labels: 3. to review

#41318 fix(session): Do not log fresh/empty session as error
  lib/private/Session/CryptoSessionData.php
Labels: 3. to review, regression

#41374 feat(search): Seach for persons as event attendees and organizers
  apps/dav/lib/Search/EventsSearchProvider.php
  apps/dav/tests/unit/Search/EventsSearchProviderTest.php
Labels: enhancement, 4. to release, feature: caldav

#41271 enh(TextProcessing): Add two new provider interfaces
  core/Controller/TextProcessingApiController.php
  core/Migrations/Version28000Date20231103104802.php
  core/ResponseDefinitions.php
  core/openapi.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/TextProcessing/Db/Task.php
  lib/private/TextProcessing/Manager.php
  lib/public/TextProcessing/Exception/TaskFailureException.php
  lib/public/TextProcessing/IManager.php
  lib/public/TextProcessing/IProviderWithExpectedRuntime.php
  lib/public/TextProcessing/IProviderWithUserId.php
  lib/public/TextProcessing/Task.php
Labels: pending documentation

#41404 fix(workflow): Fix "Call to a member function getUID() on null" with …
  apps/workflowengine/lib/Entity/File.php
Labels: bug, 3. to review, feature: workflows, applied on testing

#41407 fix(userstatus): Do not override message timestamp for default messages
  apps/user_status/lib/Service/StatusService.php
Labels: bug, 3. to review, feature: status

#41406 fix(log): Log exception class when message is empty
  lib/private/Log.php
Labels: bug, 3. to review, applied on testing

#41412 Fix default icon: should be white instead of black
  core/img/places/default-app-icon.svg
Labels: 3. to review

#41417 fix(workflowengine): use andWhere() not second where()
  apps/workflowengine/lib/Manager.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: bug, 4. to release, backport-request, feature: workflows

#41233 [stable26] Catch Imaginary processing errors
  lib/private/Preview/Imaginary.php
Labels: 3. to review

#41405 Close participants filter after click
  core/src/components/GlobalSearch/SearchableList.vue
  dist/core-global-search.js
  dist/core-global-search.js.map
Labels: bug, 3. to review

#41416 fix: Only reset preview src if it used to fail before
  apps/files/src/components/FileEntry/FileEntryPreview.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#41426 Use background to increase overlay contrast
  apps/files/src/components/FileEntry/FileEntryPreview.vue
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, javascript

#41443 fix(files): Show Collectives icon in Collectives folders
  apps/files/src/components/FileEntry/CollectivesIcon.vue
  apps/files/src/components/FileEntry/FileEntryPreview.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, regression, javascript, files2vue

#41413 Fix apps search provider order
  apps/settings/lib/Search/AppSearch.php
Labels: 3. to review

#41447 fix(backupcodes): Remove old notifications before creating a new remi…
  apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php
Labels: bug, 3. to review, backport-request, feature: activity and notification

#41086 Migrate memory_limit check to new SetupCheck API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/PhpMemoryLimit.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#41446 moving IMetadataQuery
  apps/dav/lib/Files/FileSearchBackend.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/FilesMetadata/FilesMetadataManager.php
  lib/private/FilesMetadata/MetadataQuery.php
  lib/public/FilesMetadata/IFilesMetadataManager.php
  lib/public/FilesMetadata/IMetadataQuery.php
Labels: 4. to release, pending documentation

#41436 Add `inAppSearch` for advanced search providers
  core/ResponseDefinitions.php
  core/openapi.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Search/SearchComposer.php
  lib/public/Search/IInAppSearch.php
Labels: 4. to release, pending documentation

#41455 fix(files): Use `color-primary-element-text` for files/folders overlay icons
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: design, 3. to review, files2vue, 28-feedback, ❄️ 2023-Winter

#41442 ignore metadata if migration to 28 is not done
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/FilesMetadata/FilesMetadataManager.php
  lib/public/FilesMetadata/IFilesMetadataManager.php
Labels: 3. to review

#41390 Metadata must be set a editable for PROPPATCH
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  lib/private/FilesMetadata/FilesMetadataManager.php
  lib/private/FilesMetadata/MetadataQuery.php
  lib/private/FilesMetadata/Model/FilesMetadata.php
  lib/private/FilesMetadata/Model/MetadataValueWrapper.php
  lib/public/FilesMetadata/IFilesMetadataManager.php
  lib/public/FilesMetadata/Model/IFilesMetadata.php
  lib/public/FilesMetadata/Model/IMetadataValueWrapper.php
Labels: 2. developing, 3. to review

#41432 Fix search providers icons
  apps/settings/img/settings.svg
  apps/settings/img/settings_apps.svg
  apps/settings/img/users-white.svg
  apps/settings/img/users.svg
  lib/private/Search/SearchComposer.php
Labels: 3. to review

#41387 fix(cypress): Do not install calendar app from app store for testing
  cypress/e2e/theming/navigation-bar-settings.cy.ts
  cypress/fixtures/testapp/appinfo/info.xml
  cypress/fixtures/testapp/appinfo/routes.php
  cypress/fixtures/testapp/img/app.svg
  cypress/fixtures/testapp/lib/AppInfo/Application.php
  cypress/fixtures/testapp/lib/Controller/PageController.php
  cypress/fixtures/testapp/templates/main.php
  cypress/support/commonUtils.ts
Labels: 3. to review, tests, CI

#41176 fix: encode uri for trashbin delete (the second one)
  apps/files/src/actions/deleteAction.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#41457 feat(search): allow contacts person search
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Search/ContactsSearchProvider.php
Labels: enhancement, 4. to release, feature: search, feature: contacts

#41398 fix(cypress): Adjust admin theming tests for new `@nextcloud/vue` release
  cypress/e2e/theming/admin-settings.cy.ts
  cypress/tsconfig.json
  tsconfig.json
Labels: bug, 3. to review, tests

#41453 Improve shared status button
  apps/files/src/components/FileEntry/FileEntryActions.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: design, 3. to review, ❄️ 2023-Winter

#41341 fix: Allow to set app order on navigation entries added by closures
  apps/theming/lib/Listener/BeforePreferenceListener.php
  apps/theming/src/components/AppOrderSelector.vue
  apps/theming/src/components/UserAppMenuSection.vue
  dist/theming-admin-theming.js
  dist/theming-admin-theming.js.map
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
  lib/private/App/AppManager.php
  lib/private/NavigationManager.php
  lib/public/App/IAppManager.php
  lib/public/INavigationManager.php
  tests/lib/App/AppManagerTest.php
  tests/lib/NavigationManagerTest.php
Labels: bug, 3. to review, ❄️ 2023-Winter

#41384 Enhancements : improve most recent global search UI
  core/src/components/GlobalSearch/SearchFilterChip.vue
  core/src/components/GlobalSearch/SearchableList.vue
  core/src/views/GlobalSearchModal.vue
  dist/core-global-search.js
  dist/core-global-search.js.map
Labels: 4. to release, ❄️ 2023-Winter

#41379 28.0.0 beta 3
  version.php
Labels: 3. to review

#38622 Replace if/else with return match
  lib/private/Files/FileInfo.php
Labels: 4. to release

#41366 fix(s3): support SSE-C headers for the MultipartCopy call
  lib/private/Files/ObjectStore/S3ObjectTrait.php
Labels: 3. to review

#41212 [stable27] fix(twofactor): avoid DB error on Twofactor (en/dis)abled event
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
Labels: 3. to review

#41213 [stable26] fix(twofactor): avoid DB error on Twofactor (en/dis)abled event
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
Labels: 3. to review

#40042 (enh) Change `occ background-job:list` limit default 10->500
  core/Command/Background/ListCommand.php
Labels: 3. to review, feature: occ

#41439 Add link for opening app details
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  apps/settings/src/components/AppList/AppItem.vue
  apps/settings/src/components/AppList/AppScore.vue
  cypress/e2e/settings/apps.cy.ts
  dist/settings-apps-view-7418.js
  dist/settings-apps-view-7418.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, accessibility

#40935 add some support for rename on case insensitive local filesystems
  lib/private/Files/Storage/Local.php
Labels: 3. to review, backport-request

#41495 fix(ocp): register IAvailabilityCoordinator service alias
  lib/private/Server.php
Labels: 3. to review

#37959 Check for open_basedir before reading /proc
  lib/private/Preview/Generator.php
Labels: 3. to review, feature: previews and thumbnails

#41474 refactor(carddav): Use even earlier return and SQL's WHERE IN
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 4. to release, feature: dav, feature: carddav

#41501 feat(dav): Enable OOO UI and expose enabled via OCP
  apps/dav/lib/Settings/AvailabilitySettings.php
  lib/private/User/AvailabilityCoordinator.php
  lib/public/User/IAvailabilityCoordinator.php
  tests/lib/User/AvailabilityCoordinatorTest.php
Labels: 3. to review, feature: dav, integration, pending documentation, feature: caldav

#41489 Move delete share button into the scrolling container
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/7642-7642.js
  dist/7642-7642.js.LICENSE.txt
  dist/9911-9911.js
  dist/9911-9911.js.LICENSE.txt
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review

#41264 [stable26] Show proper warning on 0 quota
  apps/files/js/files.js
Labels: bug, 3. to review

#41356 [stable27] fix(files): prevent redirect on heading column sort
  apps/files/js/filelist.js
Labels: bug, 3. to review, backport-request, feature: files

#41506 Correct spelling
  core/src/components/GlobalSearch/CustomDateRangeModal.vue
  dist/core-global-search.js
  dist/core-global-search.js.map
Labels: bug, 4. to release, feature: language l10n and translations

#41486 Fix invalid users/groups handling in advanced search
  core/Controller/UnifiedSearchController.php
  lib/private/Search/Filter/GroupFilter.php
  lib/private/Search/Filter/UserFilter.php
Labels: 3. to review

#41520 Finish password confirmation
  apps/workflowengine/lib/Controller/AWorkflowController.php
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/src/store.js
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows

#41521 [stable27] Finish password confirmation
  apps/workflowengine/lib/Controller/AWorkflowController.php
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/src/store.js
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows

#41522 [stable26] Finish password confirmation
  apps/workflowengine/lib/Controller/AWorkflowController.php
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/src/store.js
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows

#41524 [stable24] Finish password confirmation
  apps/workflowengine/lib/Controller/AWorkflowController.php
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/src/store.js
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows

#41525 [stable23] Finish password confirmation
  apps/workflowengine/js/workflowengine.js
  apps/workflowengine/js/workflowengine.js.map
  apps/workflowengine/lib/Controller/AWorkflowController.php
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/src/store.js
Labels: bug, 3. to review, feature: workflows

#41485 fix(files): Sort list ASC by default
  apps/files/src/mixins/filesSorting.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files, regression, files2vue

#41523 [stable25] Finish password confirmation
  apps/workflowengine/lib/Controller/AWorkflowController.php
  apps/workflowengine/lib/Controller/UserWorkflowsController.php
  apps/workflowengine/src/store.js
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows

#41526 Reverse X-Forwarded-For list to read the correct proxy remote address
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: bug, 3. to review

#41527 [stable27] Reverse X-Forwarded-For list to read the correct proxy remote address
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: bug, 3. to review

#41528 [stable26] Reverse X-Forwarded-For list to read the correct proxy remote address
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: bug, 3. to review

#41529 [stable25] Reverse X-Forwarded-For list to read the correct proxy remote address
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: bug, 3. to review

#41530 [stable24] Reverse X-Forwarded-For list to read the correct proxy remote address
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: bug, 3. to review

#41363 [27] optimize builtin storage wrappers
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/External/Mount.php
  apps/files_sharing/lib/ISharedMountPoint.php
  apps/files_sharing/lib/SharedMount.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Mount/HomeMountPoint.php
  lib/private/Files/Mount/LocalHomeMountProvider.php
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/SetupManager.php
  tests/lib/Files/FileInfoTest.php
Labels: 3. to review, performance 🚀

#41511 Enhancements for advanced search API
  lib/private/Search/FilterFactory.php
  lib/private/Search/SearchComposer.php
  lib/public/Search/IFilter.php
  lib/public/Search/ISearchQuery.php
Labels: 3. to review

#41505 [stable26] add some support for rename on case insensitive local filesystems
  lib/private/Files/Storage/Local.php
Labels: 3. to review

#41502 [stable27] add some support for rename on case insensitive local filesystems
  lib/private/Files/Storage/Local.php
Labels: 3. to review

#41480 [stable26] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#41512 fix(userstatus): Only track message timestamp for values
  apps/user_status/lib/Db/UserStatus.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
Labels: bug, 4. to release, feature: status

#41057 optimize UserMountCache::registerStorage
  lib/private/Files/Config/CachedMountInfo.php
  lib/private/Files/Config/LazyStorageMountInfo.php
  lib/private/Files/Config/UserMountCache.php
  lib/public/Files/Config/ICachedMountInfo.php
  tests/lib/Files/Config/UserMountCacheTest.php
Labels: 3. to review, performance 🚀

#41545 [stable27] optimize UserMountCache::registerStorage
  lib/private/Files/Config/CachedMountInfo.php
  lib/private/Files/Config/LazyStorageMountInfo.php
  lib/private/Files/Config/UserMountCache.php
  lib/public/Files/Config/ICachedMountInfo.php
  tests/lib/Files/Config/UserMountCacheTest.php
Labels: 3. to review, performance 🚀

#41519 fix(files): Ensure folders and favorites are sorted first regardless of sorting mode
  apps/files/src/views/FilesList.vue
  cypress/e2e/files/files.cy.ts
  cypress/e2e/files/files_sorting.cy.ts
  cypress/support/commands.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, files2vue

#41555 Bump Hub 6 -> Hub 7
  apps/settings/templates/settings/admin/overview.php
Labels: 4. to release

#41431 26.0.9 RC1
  version.php
Labels: 3. to review

#41541 Serve .flac audio files
  lib/private/Setup.php
Labels: bug, 3. to review, backport-request

#41430 27.1.4 RC1
  version.php
Labels: 3. to review

#41477 28.0.0 beta 4
  version.php
Labels: 3. to review

#41334 fix(component): utilized NcDateTime component
  apps/files/src/components/FileEntry.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 4. to release, feature: files, files2vue

#41561 fix(settings): User row text field styles
  apps/settings/src/components/Users/UserRow.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: users and groups, feature: settings

#41560 fix(a11y): Focus on sharing quick permission radio
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/4997-4997.js
  dist/4997-4997.js.LICENSE.txt
  dist/7642-7642.js
  dist/7642-7642.js.LICENSE.txt
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, accessibility

#41571 Allow setting `strict-dynamic` on `strict-src-elem` and set it by default
  lib/private/Security/CSP/ContentSecurityPolicy.php
  lib/public/AppFramework/Http/ContentSecurityPolicy.php
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
  tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php
  tests/lib/AppFramework/Http/EmptyContentSecurityPolicyTest.php
  tests/lib/Security/CSP/ContentSecurityPolicyManagerTest.php
Labels: 3. to review, security

#41399 fix(cypress): Make new-users test less flaky by using test isolation
  cypress/e2e/settings/users.cy.ts
Labels: bug, 3. to review, tests

#41573 fix(files): avoid sending thumbnail URL for directory as none exists
  apps/files/lib/Search/FilesSearchProvider.php
Labels: bug, 3. to review

#41577 fix(files): make files list valid table layout
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/components/VirtualList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 2. developing, feature: files, accessibility, files2vue

#41569 fix(2fa-backupcodes): Don't remember disabled and deleted users over …
  apps/twofactor_backupcodes/lib/BackgroundJob/CheckBackupCodes.php
  apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php
  apps/twofactor_backupcodes/tests/Unit/BackgroundJob/CheckBackupCodeTest.php
  apps/twofactor_backupcodes/tests/Unit/BackgroundJob/RememberBackupCodesJobTest.php
Labels: bug, 3. to review

#41583 fix(CSP): Only add `strict-dynamic` when using nonce
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
  tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php
  tests/lib/AppFramework/Http/EmptyContentSecurityPolicyTest.php
  tests/lib/Security/CSP/ContentSecurityPolicyManagerTest.php
Labels: high, regression, 28-feedback

#41579 fix: Be less strict about action exec return value
  apps/files/src/components/FileEntry/FileEntryActions.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, files2vue, 28-feedback

#41475 fix: Add docxf/oform to mimetypemapping
  resources/config/mimetypemapping.dist.json
Labels: bug, 3. to review
