Repository nextcloud/server, pull requests merged in 2024-09, with the labels that each got.

#47666 [stable30] fix(files): Node loading information should be accessible
  apps/files/src/components/FileEntry/FileEntryCheckbox.vue
  cypress/e2e/files/files-renaming.cy.ts
  cypress/support/e2e.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#47640 fix: Run migration sql as statement so that the primary db node is used
  lib/private/DB/Migrator.php
Labels: bug, 2. developing, backport-request

#47651 [stable30] fix(settings): Hide forbidden UI elements for group managers
  apps/settings/src/components/UserList.vue
  apps/settings/src/views/UserManagementNavigation.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, backport-request, feature: user migration

#47627 [LinkReferenceProvider] Better size check
  lib/public/Collaboration/Reference/LinkReferenceProvider.php
Labels: enhancement, 3. to review, backport-request, feature: previews and thumbnails

#47670 fix: Properly calculate intermediate icon for touch icon generation
  apps/theming/lib/IconBuilder.php
Labels: bug, 3. to review, feature: theming

#47680 chore: Update `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: 3. to review

#47678 chore(IConfig): Adjust type of `getUsersForUserValue`
  lib/private/AllConfig.php
  lib/public/IConfig.php
Labels: 3. to review, php

#47676 fix(OCP): Fix Image interface
  lib/private/Image.php
  lib/private/StreamImage.php
  lib/public/IImage.php
  lib/public/Image.php
Labels: bug, 3. to review

#47671 test(cypress): Await promise in response to prevent timeout
  cypress/e2e/files/files-renaming.cy.ts
Labels: 3. to review, tests, CI

#47665 fix(files): Correctly parse external shares for files UI
  apps/files_sharing/src/services/SharingService.spec.ts
  apps/files_sharing/src/services/SharingService.ts
  dist/6353-6353.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, backport-request, feature: files

#47687 [stable29] fix(settings): Hide forbidden UI elements for group managers
  apps/settings/src/components/UserList.vue
  apps/settings/src/views/UserManagementNavigation.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release

#47693 [stable30] fix(css): make scrollbar visible again
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkHighContrastTheme.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Themes/HighContrastTheme.php
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
Labels: bug, design, 3. to review

#47650 chore: Cleanup app framework middleware
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/CSPMiddleware.php
  lib/private/AppFramework/Middleware/Security/SameSiteCookieMiddleware.php
  tests/lib/AppFramework/Middleware/Security/CSPMiddlewareTest.php
Labels: 3. to review, php, ♻️ refactor

#47695 [stable30] [LinkReferenceProvider] Better size check
  lib/public/Collaboration/Reference/LinkReferenceProvider.php
Labels: enhancement, 3. to review, feature: previews and thumbnails

#47697 [stable28] [LinkReferenceProvider] Better size check
  lib/private/Collaboration/Reference/LinkReferenceProvider.php
Labels: enhancement, 3. to review, feature: previews and thumbnails

#47691 [stable30] fix(files): Correctly parse external shares for files UI
  apps/files_sharing/src/services/SharingService.spec.ts
  apps/files_sharing/src/services/SharingService.ts
  dist/8707-8707.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, feature: sharing, feature: files

#47659 Followup: fix(settings): Don't display built-in task types in AI settings TextProcessing
  apps/settings/src/components/AdminAI.vue
  dist/settings-vue-settings-admin-ai.js
  dist/settings-vue-settings-admin-ai.js.map
Labels: bug, 2. developing, backport-request, feature: settings

#47692 [stable29] fix(files): Correctly parse external shares for files UI
  apps/files_sharing/src/services/SharingService.spec.ts
  apps/files_sharing/src/services/SharingService.ts
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, feature: sharing, backport-request, feature: files

#47674 fix(settings): Fix sharing exclude groups from password requirement option not working
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/components/AdminSettingsSharingForm.vue
  apps/settings/tests/Settings/Admin/SharingTest.php
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
Labels: bug, 3. to review, backport-request

#47412 feat(files_sharing): reminder for link shares with expiration date
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Migration/Version31000Date20240821142813.php
  apps/files_sharing/lib/SharesReminderJob.php
  apps/files_sharing/tests/SharesReminderJobTest.php
  apps/sharebymail/lib/ShareByMailProvider.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Share.php
  lib/public/Share/IShare.php
Labels: 4. to release, feature: sharing, feature: emails

#47679 chore(IGetRealUIDBackend): Fix typo in doc block
  lib/public/User/Backend/IGetRealUIDBackend.php
Labels: 3. to review, developer experience

#47714 [stable28] fix(settings): Fix sharing exclude groups from password requirement option not working
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/components/AdminSettingsSharingForm.vue
  apps/settings/tests/Settings/Admin/SharingTest.php
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
Labels: bug, 4. to release

#47715 [stable29] fix(settings): Fix sharing exclude groups from password requirement option not working
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/components/AdminSettingsSharingForm.vue
  apps/settings/tests/Settings/Admin/SharingTest.php
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
Labels: bug, 4. to release

#47158 fix(files): Fix navigating with breadcrumbs not highlighting navigation entry
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#47716 [stable30] fix(settings): Fix sharing exclude groups from password requirement option not working
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/components/AdminSettingsSharingForm.vue
  apps/settings/tests/Settings/Admin/SharingTest.php
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
Labels: bug, 4. to release

#47675 chore(db): Make the query more simple to read
  lib/private/DB/Adapter.php
Labels: 4. to release, ♻️ refactor, feature: database

#47285 fix: Do not throw if appstore is unavailable during upgrade
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: bug, 4. to release, backport-request

#39242 (occ db:convert-type) Add support for UNIX sockets
  core/Command/Db/ConvertType.php
Labels: enhancement, 2. developing

#47155 fix(jobs): Switch to executeStatement() while deleting rows
  lib/private/BackgroundJob/JobList.php
Labels: 4. to release, backport-request, technical debt

#47690 chore(theming): Increase app version
  apps/theming/appinfo/info.xml
Labels: 3. to review, feature: theming

#40164 Translate all share exceptions
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: bug, 4. to release, feature: language l10n and translations

#47724 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47729 [stable30] chore: Improve isEncrypted description
  lib/public/Files/FileInfo.php
Labels: 3. to review, feature: encryption (server-side), php

#46859 Fix status check and saving of external storages
  apps/files_external/css/settings.css
  apps/files_external/css/settings.css.map
  apps/files_external/css/settings.scss
  apps/files_external/js/settings.js
  apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
  apps/files_external/lib/Lib/Auth/Password/UserProvided.php
  apps/files_external/templates/settings.php
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/ExternalStorage.php
  build/integration/features/bootstrap/FeatureContext.php
  build/integration/files_features/external-storage.feature
  build/integration/run.sh
Labels: bug, 3. to review, feature: external storage, backport-request

#47696 [stable29] [LinkReferenceProvider] Better size check
  lib/public/Collaboration/Reference/LinkReferenceProvider.php
Labels: enhancement, 3. to review, feature: previews and thumbnails

#47732 [stable28] fix(dav): adjust usages of webdav.customRequest
  apps/dav/src/service/CalendarService.js
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
Labels: bug, 4. to release

#47703 [stable27] [oauth2] Store hashed secret instead of encrypted
  apps/oauth2/appinfo/info.xml
  apps/oauth2/composer/composer/autoload_classmap.php
  apps/oauth2/composer/composer/autoload_static.php
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/lib/Controller/SettingsController.php
  apps/oauth2/lib/Migration/Version011901Date20240829164356.php
  apps/oauth2/lib/Settings/Admin.php
  apps/oauth2/src/App.vue
  apps/oauth2/src/components/OAuthItem.vue
  apps/oauth2/tests/Controller/OauthApiControllerTest.php
  apps/oauth2/tests/Controller/SettingsControllerTest.php
  apps/oauth2/tests/Settings/AdminTest.php
  dist/oauth2-oauth2.js
  dist/oauth2-oauth2.js.map
Labels: enhancement, 3. to review, feature: authentication

#47698 [stable27] [LinkReferenceProvider] Better size check
  lib/private/Collaboration/Reference/LinkReferenceProvider.php
Labels: enhancement, 3. to review, feature: previews and thumbnails

#47738 fix(files): undefined sidebar
  apps/files/src/views/Sidebar.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 4. to release, backport-request, feature: files, feature: file sidebar

#47417 fix(files): Create non-existent parents of mountpoints
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
Labels: bug, 3. to review, backport-request

#47745 [stable29] fix(files): undefined displayname for outdated `@nextcloud/files`<3.6.0 apps
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, high, backport-request, feature: files, regression

#47754 fix(appstore): Cache apps.json also on dev instances
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: enhancement, 3. to review, feature: apps management, technical debt, developer experience

#47769 fix: Use sha256 to hash arguments of background jobs
  core/Migrations/Version28000Date20240828142927.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/BackgroundJob/JobList.php
Labels: enhancement, 3. to review, backport-request, php

#47519 feat(transfer-ownership): Correctly react to encrypted files
  apps/files/lib/Service/OwnershipTransferService.php
Labels: bug, 3. to review, backport-request

#47761 fix: Fix missing footer on public pages
  lib/public/AppFramework/Http/Template/PublicTemplateResponse.php
Labels: bug, 3. to review, regression

#47770 fix(dav): Always respond custom error page on exceptions
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Files/ErrorPagePlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/travis/caldavtest/tests/CalDAV/sync-report.xml
  apps/dav/tests/unit/DAV/ErrorPagePluginTest.php
  build/integration/dav_features/caldav.feature
  build/integration/dav_features/carddav.feature
  core/templates/xml_exception.php
Labels: bug, 3. to review, feature: dav, backport-request, php

#47757 30.0.0 RC4
  version.php
Labels: 3. to review

#47758 29.0.7 RC1
  version.php
Labels: 3. to review

#47759 28.0.10 RC1
  version.php
Labels: 3. to review

#47789 chore: adjust code to adhere to coding standard
  .git-blame-ignore-revs
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
  apps/dav/lib/CalDAV/BirthdayCalendar/EnablePlugin.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/CalendarHome.php
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/EventComparisonService.php
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CalDAV/Schedule/IMipService.php
  apps/dav/lib/CalDAV/Status/StatusService.php
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/lib/Migration/Version1027Date20230504122946.php
  apps/dav/lib/Migration/Version1029Date20221114151721.php
  apps/files/lib/Command/Delete.php
  apps/files/lib/Controller/ViewController.php
  apps/files_external/tests/Storage/SmbTest.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_trashbin/lib/Command/RestoreAllFiles.php
  apps/files_trashbin/lib/Listeners/SyncLivePhotosListener.php
  apps/settings/lib/Settings/Admin/ArtificialIntelligence.php
  apps/theming/lib/Service/ThemeInjectionService.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/LDAP.php
  apps/user_status/lib/Listener/OutOfOfficeStatusListener.php
  apps/user_status/lib/Listener/UserLiveStatusListener.php
  apps/user_status/lib/Service/StatusService.php
  apps/webhook_listeners/lib/Service/PHPMongoQuery.php
  build/integration/features/bootstrap/Sharing.php
  core/Command/Db/Migrations/PreviewCommand.php
  core/Controller/TextProcessingApiController.php
  core/Controller/TextToImageApiController.php
  lib/private/AppConfig.php
  lib/private/Comments/Manager.php
  lib/private/DB/QueryBuilder/Sharded/AutoIncrementHandler.php
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/Migration/MetadataManager.php
  lib/private/Search/SearchQuery.php
  lib/private/Security/Ip/Address.php
  lib/private/Share20/Manager.php
  lib/private/TaskProcessing/Manager.php
  lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
  lib/private/Template/JSConfigHelper.php
  lib/private/TextToImage/Manager.php
  lib/private/TextToImage/RemoveOldTasksBackgroundJob.php
  lib/private/User/Manager.php
  tests/lib/Files/Search/SearchIntegrationTest.php
  tests/lib/TaskProcessing/TaskProcessingTest.php
Labels: 3. to review, ♻️ refactor

#47756 fix(files): Check if target path is a descendant of the shared folder
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
Labels: bug, 4. to release, backport-request

#47784 fix(FileInfo): correctly implement `\ArrayAccess::offsetGet`
  lib/private/Files/FileInfo.php
Labels: bug, 3. to review, technical debt

#47731 chore(storage): refactor some code portions
  lib/private/Files/Storage/DAV.php
Labels: 3. to review, technical debt, ♻️ refactor

#47649 fix: Fix inaccessible content on public pages due to overlapping footer
  core/Listener/BeforeTemplateRenderedListener.php
  core/css/public.css
  core/css/public.css.map
  core/css/public.scss
  core/css/server.css
  core/css/server.css.map
  core/src/public.ts
  dist/core-public.js
  dist/core-public.js.license
  dist/core-public.js.map
  dist/core-public.js.map.license
  webpack.modules.js
Labels: bug, 3. to review, feature: sharing, feature: files

#47801 fix(TaskProcessing): increase error_message column length
  core/Migrations/Version30000Date20240906095113.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/TaskProcessing/Manager.php
Labels: 3. to review, backport-request

#47802 fix(files): Fallback icons should fill the container
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, design, 3. to review

#47806 chore(files_sharing): Do not use files source files but directly the library
  apps/files_sharing/src/files_views/publicFileShare.ts
  dist/files_sharing-init-public.js
  dist/files_sharing-init-public.js.map
Labels: 3. to review

#47808 chore(i18n): Spelling of ID
  lib/private/Share20/Manager.php
Labels: bug, 3. to review, feature: language l10n and translations

#43281 enh: update desktop client unsupported version (403) error message
  apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php
  apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/BlockLegacyClientPluginTest.php
Labels: 4. to release, client: 💻 desktop

#47824 chore(i18n): adapted lowercase
  apps/settings/src/components/AdminAI.vue
  dist/settings-vue-settings-admin-ai.js
  dist/settings-vue-settings-admin-ai.js.map
Labels: 3. to review, backport-request, feature: language l10n and translations

#47837 fix(files): Never return a null ETag in DAV
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/DAV.php
  lib/private/Files/Storage/Local.php
Labels: bug, 3. to review

#47805 fix: Replace conflicting tags in `xml_exception` template
  core/templates/xml_exception.php
Labels: bug, 3. to review, backport-request, regression

#47803 chore(files_sharing): Add migration attribute for `share.reminder_sent` column
  apps/files_sharing/lib/Migration/Version31000Date20240821142813.php
Labels: 3. to review, feature: database

#47841 fix(files_sharing): Open single-file-share by default
  apps/files_sharing/lib/DefaultPublicShareTemplateProvider.php
  apps/files_sharing/src/init-public.ts
  dist/files_sharing-init-public.js
  dist/files_sharing-init-public.js.map
Labels: bug, 3. to review, feature: sharing

#47523 Use NavigationManager instead of AppManager to handle custom apps order
  apps/files/lib/App.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/Settings/Admin.php
  apps/theming/lib/Settings/Personal.php
  apps/theming/src/components/UserAppMenuSection.vue
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/Settings/AdminTest.php
  apps/theming/tests/Settings/PersonalTest.php
  config/config.sample.php
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
  lib/private/App/AppManager.php
  lib/private/NavigationManager.php
  lib/private/TemplateLayout.php
  lib/private/URLGenerator.php
  lib/public/App/IAppManager.php
  lib/public/INavigationManager.php
  tests/lib/App/AppManagerTest.php
  tests/lib/NavigationManagerTest.php
Labels: bug, 3. to review, feature: theming

#47845 Add an endpoint to remove all webhook registrations from an app
  apps/webhook_listeners/lib/Controller/WebhooksController.php
  apps/webhook_listeners/lib/Db/WebhookListenerMapper.php
  apps/webhook_listeners/openapi.json
Labels: 3. to review, backport-request

#47816 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47737 fix(caldav, carddav): also allow unsharing of circle shares
  apps/dav/lib/DAV/Sharing/Backend.php
Labels: 4. to release, backport-request

#47860 fix: Only write once to template instead of create/copy
  lib/private/Files/Template/TemplateManager.php
Labels: bug, 3. to review, backport-request

#47858 fix(preview): gracefully handle file not being opened in ProviderV2
  lib/private/Preview/ProviderV2.php
Labels: bug, 3. to review, backport-request, feature: previews and thumbnails

#47834 fix(appstore): return if appstore is manually disabled
  lib/private/App/AppStore/Fetcher/AppFetcher.php
Labels: 4. to release, backport-request

#47797 [stable28] fix(files): Correctly parse external shares for files UI
  apps/files_sharing/src/services/SharingService.spec.ts
  apps/files_sharing/src/services/SharingService.ts
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, feature: sharing, feature: files

#47662 fix(RichObjectStrings/Validator): Validate key value types of rich object parameters
  apps/files_sharing/lib/Notification/Notifier.php
  lib/private/Activity/Event.php
  lib/private/RichObjectStrings/Validator.php
  lib/public/Activity/IEvent.php
  lib/public/Notification/INotification.php
  lib/public/SetupCheck/SetupResult.php
  tests/lib/RichObjectStrings/ValidatorTest.php
Labels: bug, 3. to review

#47848 fix(files): Reset context menu position on close
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files

#47884 chore: Add another coding standard commit to the git blame ignore
  .git-blame-ignore-revs
Labels: 3. to review

#47881 fix(settings): Add back create group icon
  apps/settings/src/views/UserManagementNavigation.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, design, 3. to review, regression

#47339 fix: Display 'Leave share' instead of 'Delete'
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/ResponseDefinitions.php
  apps/files_sharing/openapi.json
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/integration/sharing_features/sharing-v1-part4.feature
Labels: bug, 4. to release, backport-request, feature: files

#47891 fix(files): Make `openMenu` watcher null safe
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#47586 fix(theming): Add migration to restore primary color after separating primary and background
  apps/theming/composer/composer/autoload_classmap.php
  apps/theming/composer/composer/autoload_static.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
  apps/theming/lib/Migration/Version2006Date20240905111627.php
  apps/theming/lib/Service/BackgroundService.php
  apps/theming/lib/ThemingDefaults.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/ThemingDefaultsTest.php
  lib/private/DB/QueryBuilder/Partitioned/PartitionedQueryBuilder.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
  lib/private/Server.php
  lib/public/DB/QueryBuilder/IQueryBuilder.php
Labels: bug, 3. to review, backport-request, feature: theming

#47913 fix: Add whiteboard to education and public sector bundle
  lib/private/App/AppStore/Bundles/EducationBundle.php
  lib/private/App/AppStore/Bundles/PublicSectorBundle.php
  tests/lib/App/AppStore/Bundles/EducationBundleTest.php
Labels: 3. to review, backport-request

#47914 fix(LDAP): check index before accessing it
  apps/user_ldap/lib/Access.php
Labels: bug, 3. to review, feature: ldap, backport-request

#47886 28.0.10
  version.php
Labels: 3. to review

#47887 29.0.7
  version.php
Labels: 3. to review

#47685 fix: Move OC_API into \OC\ApiHelper in standard namespace
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/OCS/ApiHelper.php
  lib/private/OCS/Exception.php
  lib/private/OCS/Result.php
  lib/private/legacy/OC_API.php
  ocs/v1.php
  tests/lib/APITest.php
  tests/lib/AppFramework/OCS/BaseResponseTest.php
  tests/lib/AppFramework/OCS/V2ResponseTest.php
  tests/lib/OCS/ApiHelperTest.php
  tests/lib/OCS/MapStatusCodeTest.php
Labels: 3. to review, technical debt, pending documentation

#47890 30.0.0 RC5
  version.php
Labels: 3. to review

#47527 fix(files_external): Handling in SFTP UI for custom ports
  apps/files_external/lib/Lib/Backend/SFTP.php
Labels: bug, 3. to review, feature: external storage, backport-request

#47526 fix(files_external): Handling in FTP UI for custom ports
  apps/files_external/lib/Lib/Backend/FTP.php
Labels: bug, 3. to review, feature: external storage, backport-request

#47926 30.0.0
  version.php
Labels: overview

#47854 fix(appstore): Ensure returned apps from AppStore are valid
  lib/private/App/AppStore/Fetcher/AppFetcher.php
Labels: 3. to review, backport-request, feature: apps management

#47932 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47933 fix(config): Throw PreconditionException always when it didn't match
  lib/private/AllConfig.php
  tests/lib/AllConfigTest.php
Labels: bug, 3. to review

#47883 fix(setup-checks): Ensure URL with webroot works
  apps/settings/lib/SetupChecks/CheckServerResponseTrait.php
  apps/settings/lib/SetupChecks/DataDirectoryProtected.php
  apps/settings/lib/SetupChecks/WellKnownUrls.php
  apps/settings/tests/SetupChecks/CheckServerResponseTraitImplementation.php
  apps/settings/tests/SetupChecks/CheckServerResponseTraitTest.php
  apps/settings/tests/SetupChecks/DataDirectoryProtectedTest.php
  lib/base.php
  lib/private/URLGenerator.php
Labels: bug, 3. to review, backport-request, feature: settings

#47865 Move admin_audit to proper event listeners v2
  apps/admin_audit/composer/composer/autoload_classmap.php
  apps/admin_audit/composer/composer/autoload_static.php
  apps/admin_audit/lib/Actions/AppManagement.php
  apps/admin_audit/lib/Actions/Auth.php
  apps/admin_audit/lib/Actions/Console.php
  apps/admin_audit/lib/Actions/Files.php
  apps/admin_audit/lib/Actions/GroupManagement.php
  apps/admin_audit/lib/Actions/Security.php
  apps/admin_audit/lib/Actions/Sharing.php
  apps/admin_audit/lib/Actions/UserManagement.php
  apps/admin_audit/lib/AppInfo/Application.php
  apps/admin_audit/lib/AuditLogger.php
  apps/admin_audit/lib/Listener/AppManagementEventListener.php
  apps/admin_audit/lib/Listener/AuthEventListener.php
  apps/admin_audit/lib/Listener/ConsoleEventListener.php
  apps/admin_audit/lib/Listener/CriticalActionPerformedEventListener.php
  apps/admin_audit/lib/Listener/FileEventListener.php
  apps/admin_audit/lib/Listener/GroupManagementEventListener.php
  apps/admin_audit/lib/Listener/SecurityEventListener.php
  apps/admin_audit/lib/Listener/SharingEventListener.php
  apps/admin_audit/lib/Listener/UserManagementEventListener.php
  apps/admin_audit/tests/Listener/SecurityEventListenerTest.php
  apps/user_ldap/ajax/clearMappings.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/AccessFactory.php
  apps/user_ldap/lib/Jobs/Sync.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/Jobs/SyncTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Console/Application.php
  lib/private/Preview/Generator.php
  lib/public/Preview/BeforePreviewFetchedEvent.php
  lib/public/User/Events/BeforeUserIdUnassignedEvent.php
  lib/public/User/Events/UserIdAssignedEvent.php
  lib/public/User/Events/UserIdUnassignedEvent.php
  tests/lib/Preview/GeneratorTest.php
Labels: 4. to release, technical debt, pending documentation

#47945 fix(files_external): broken credentials dialog
  apps/files_external/appinfo/routes.php
  apps/files_external/lib/Controller/ApiController.php
  apps/files_external/src/actions/enterCredentialsAction.ts
  apps/files_external/src/views/CredentialsDialog.vue
  dist/4076-4076.js
  dist/4076-4076.js.license
  dist/4076-4076.js.map
  dist/4076-4076.js.map.license
  dist/files_external-init.js
  dist/files_external-init.js.map
Labels: bug, 3. to review, feature: external storage, regression

#47927 Migrate away from OC_App to IAppManager
  apps/provisioning_api/lib/Controller/AppConfigController.php
  apps/provisioning_api/tests/Controller/AppConfigControllerTest.php
  apps/settings/lib/Controller/AppSettingsController.php
  apps/theming/tests/UtilTest.php
  core/Command/App/Enable.php
  core/Command/App/GetPath.php
  core/Command/App/Update.php
  core/Command/Db/Migrations/GenerateCommand.php
  core/Command/Db/Migrations/GenerateMetadataCommand.php
  core/Command/L10n/CreateJs.php
  lib/private/App/AppManager.php
  lib/private/Authentication/TwoFactorAuth/ProviderLoader.php
  lib/private/IntegrityCheck/Checker.php
  lib/private/IntegrityCheck/Helpers/AppLocator.php
  lib/private/L10N/Factory.php
  lib/private/Route/Router.php
  lib/private/Server.php
  lib/private/legacy/OC_App.php
  lib/public/App/IAppManager.php
  remote.php
  tests/apps.php
  tests/lib/App/AppManagerTest.php
  tests/lib/InfoXmlTest.php
  tests/lib/IntegrityCheck/CheckerTest.php
  tests/lib/IntegrityCheck/Helpers/AppLocatorTest.php
  tests/lib/Route/RouterTest.php
Labels: 3. to review, technical debt

#47954 fix(files): Adjust Cache::searchQuery() parameter name to match interface
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
Labels: 3. to review, backport-request, technical debt

#47961 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47968 fix(files_external): Check key exists before accessing it
  apps/files_external/lib/Lib/Storage/SFTP.php
Labels: bug, 3. to review, feature: external storage, backport-request

#47293 feat(PsrLoggerAdapter): Allow to use `Psr\Log\LogLevel` for `log` method
  lib/private/Log/PsrLoggerAdapter.php
  tests/lib/Log/PsrLoggerAdapterTest.php
Labels: enhancement, 3. to review, technical debt, feature: logging

#47971 fix: Do not try to set HTTP response code on already closed connection
  lib/private/legacy/OC_Files.php
Labels: 3. to review, backport-request

#47928 fix(a11y): Update OpenDyslexic from 0.920 to 2.001
  .reuse/dep5
  apps/theming/fonts/OpenDyslexic-Bold.otf
  apps/theming/fonts/OpenDyslexic-Bold.ttf
  apps/theming/fonts/OpenDyslexic-Bold.woff
  apps/theming/fonts/OpenDyslexic-Regular.otf
  apps/theming/fonts/OpenDyslexic-Regular.ttf
  apps/theming/fonts/OpenDyslexic-Regular.woff
  apps/theming/lib/Themes/DyslexiaFont.php
  apps/theming/tests/Themes/DyslexiaFontTest.php
Labels: 3. to review, feature: theming, accessibility

#47920 feat: Reset route if neither the Viewer of the Sidebar is open
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 2. developing, feature: files, javascript, feature: file sidebar

#47990 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47999 fix(ci): Use latest buildjet version
  .github/workflows/cypress.yml
Labels: performance 🚀, dependencies, tests

#48003 fix: Restore missing dot in FilesListVirtual.vue
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, javascript

#48015 fix(Storage\Local): Do not call getSourcePath() on SplFileInfo
  lib/private/Files/Storage/Local.php
Labels: bug, 3. to review, backport-request

#48017 fix(Comment): Initialize childrenCount as integer
  lib/private/Comments/Comment.php
Labels: bug, 3. to review, backport-request

#48014 fix(Tags): Return boolean for userHasTags()
  lib/private/Tags.php
Labels: bug, 3. to review, backport-request

#48013 fix(BaseResponse): Cast XML element values to string
  lib/private/AppFramework/OCS/BaseResponse.php
Labels: bug, 3. to review, backport-request

#48016 fix(S3ConfigTrait): Allow proxy field to take false
  lib/private/Files/ObjectStore/S3ConfigTrait.php
Labels: bug, 3. to review, backport-request

#48037 fix: correct link to trademark
  LICENSES/LicenseRef-NextcloudTrademarks.txt
Labels: 4. to release, backport-request

#47916 feat(caldav): create subscriptions via occ
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Command/CreateSubscription.php
Labels: 3. to review

#48041 refactor: migrate dirname to __DIR__ constants
  apps/theming/tests/IconBuilderTest.php
  lib/private/TempManager.php
Labels: 3. to review, technical debt

#47989 [stable30] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47987 [stable29] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47988 [stable28] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#48010 feat(db): switch from settype to casts
  lib/private/Tagging/Tag.php
  lib/public/AppFramework/Db/Entity.php
  tests/lib/AppTest.php
  tests/lib/Comments/ManagerTest.php
  tests/lib/Files/Cache/UpdaterLegacyTest.php
Labels: enhancement, 3. to review, performance 🚀, feature: database

#48045 fix(dav): set string type for sanitizeMtime
  apps/dav/lib/Connector/Sabre/Node.php
Labels: bug, 3. to review, feature: dav, backport-request

#47973 Add missing Nextcloud v30 to issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: bug, 3. to review

#48046 refactor: Replace __CLASS__ with ::class references
  apps/user_ldap/lib/LoginListener.php
  apps/user_ldap/lib/Service/UpdateGroupsService.php
  lib/private/Security/Bruteforce/Backend/MemoryCacheBackend.php
  lib/private/Security/RateLimiting/Backend/MemoryCacheBackend.php
  lib/public/Files/LockNotAcquiredException.php
  lib/public/HintException.php
  tests/lib/AppFramework/Utility/ControllerMethodReflectorTest.php
Labels: 3. to review

#48043 fix(dav): imip service test expects integers for last occurence
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: bug, 3. to review, backport-request, feature: caldav, tests

#48028 fix(user_ldap): Use %n in plural translation to avoid a crash in L10N
  apps/user_ldap/lib/SetupChecks/LdapConnection.php
Labels: bug, 3. to review, backport-request

#48060 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#48042 refactor: Use the elvis operator + fix: Handle null checks with the ?? operator
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/files_external/lib/Controller/StoragesController.php
  apps/files_sharing/lib/External/Manager.php
  apps/updatenotification/tests/BackgroundJob/UpdateAvailableNotificationsTest.php
  apps/user_ldap/lib/User/User.php
  apps/weather_status/lib/Service/WeatherStatusService.php
  lib/private/Log/LogDetails.php
  lib/private/User/Database.php
Labels: 3. to review, technical debt

#48018 feat: add verbose mode to cron.php
  cron.php
Labels: enhancement, 3. to review

#48059 [stable30] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#48057 [stable29] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#48031 fix(filesreport): cast fileId to integer
  apps/dav/lib/Connector/Sabre/FilesReportPlugin.php
Labels: bug, 3. to review, feature: dav, backport-request

#48030 fix(dav): cast parameters to string
  apps/dav/lib/Provisioning/Apple/AppleProvisioningPlugin.php
Labels: bug, 3. to review, feature: dav, backport-request

#48029 fix(dav): cast content length to interger
  apps/dav/lib/BulkUpload/MultipartRequestParser.php
Labels: bug, 3. to review, feature: dav, backport-request

#48008 fix(Entity): Fix magic setter call for custom strong typed setters
  lib/public/AppFramework/Db/Entity.php
  tests/lib/AppFramework/Db/EntityTest.php
Labels: bug, 3. to review, backport-request

#48044 test: cast node name and data to string
  apps/dav/tests/unit/Upload/AssemblyStreamTest.php
Labels: bug, 3. to review, feature: dav, backport-request, tests

#47792 chore(files): Use public API where possible
  apps/files/lib/Helper.php
  build/psalm-baseline.xml
Labels: 3. to review, technical debt

#47948 fix(collaboration): Reduce timeouts to 3s for link reference connects
  lib/public/Collaboration/Reference/LinkReferenceProvider.php
Labels: bug, 3. to review, feature: previews and thumbnails, performance 🚀

#48063 fix(a11y): Add OTF font loading check
  .htaccess
  apps/settings/lib/SetupChecks/Woff2Loading.php
  lib/private/Setup.php
Labels: 3. to review, backport-request, feature: settings, accessibility

#48050 fix(weather_status): Fix search address errors when offline
  apps/weather_status/lib/Service/WeatherStatusService.php
Labels: bug, 3. to review, backport-request

#48081 chore(1i8n): Fixed grammar and improved wording
  apps/files_external/src/views/CredentialsDialog.vue
  dist/4076-4076.js
  dist/4076-4076.js.map
  dist/4076-4076.js.map.license
  dist/5203-5203.js
  dist/5203-5203.js.license
  dist/5203-5203.js.map
  dist/5203-5203.js.map.license
  dist/files_external-init.js
  dist/files_external-init.js.map
Labels: 3. to review, backport-request, feature: language l10n and translations

#47924 🥅 — Catch MaxInstancesExceededException on calendar events
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: bug, 4. to release, backport-request

#47947 feat: Make `CheckServerResponseTrait` public and provide as `OCP\SetupCheck\CheckServerResponseTrait`
  apps/dav/lib/SetupChecks/WebdavEndpoint.php
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/SetupChecks/DataDirectoryProtected.php
  apps/settings/lib/SetupChecks/JavaScriptModules.php
  apps/settings/lib/SetupChecks/JavaScriptSourceMaps.php
  apps/settings/lib/SetupChecks/OcxProviders.php
  apps/settings/lib/SetupChecks/SecurityHeaders.php
  apps/settings/lib/SetupChecks/WellKnownUrls.php
  apps/settings/lib/SetupChecks/Woff2Loading.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/SetupCheck/CheckServerResponseTrait.php
  tests/lib/SetupCheck/CheckServerResponseTraitImplementation.php
  tests/lib/SetupCheck/CheckServerResponseTraitTest.php
Labels: enhancement, 3. to review

#47316 fix: Prevent crash when refreshing metadata for files without an owner
  lib/private/FilesMetadata/FilesMetadataManager.php
Labels: bug, 3. to review, feature: external storage, backport-request, feedback-requested

#46140 fix(config): Add missing handling for `envCache` in `getKeys()`
  lib/private/Config.php
  tests/lib/ConfigTest.php
Labels: bug, 3. to review, backport-request

#46218 Ensure that the hash method does not return null
  lib/private/Files/Storage/Local.php
  lib/private/Files/Storage/Wrapper/Availability.php
Labels: bug, 3. to review, backport-request, feature: files, php

#46480 fix(Mailer): Fix sendmail binary fallback
  apps/settings/lib/Settings/Admin/Mail.php
  apps/settings/tests/Settings/Admin/MailTest.php
  lib/private/Mail/Mailer.php
  tests/lib/Mail/MailerTest.php
Labels: bug, 2. developing, backport-request, feature: emails

#48009 fix: Remove OCP\Files\Storage interface deprecated since version 9
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  apps/dav/tests/unit/Connector/Sabre/NodeTest.php
  apps/encryption/tests/Crypto/EncryptionTest.php
  apps/encryption/tests/KeyManagerTest.php
  apps/encryption/tests/UtilTest.php
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/StorageModifierTrait.php
  apps/files_sharing/lib/External/Storage.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/files_sharing/tests/SharedStorageTest.php
  apps/files_trashbin/lib/Trashbin.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Home.php
  lib/private/Files/Storage/Storage.php
  lib/private/Files/Storage/StorageFactory.php
  lib/private/Files/Storage/Temporary.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
  lib/public/Files/Storage/IStorageFactory.php
  tests/lib/Encryption/DecryptAllTest.php
  tests/lib/Encryption/EncryptionWrapperTest.php
  tests/lib/Files/Mount/MountPointTest.php
  tests/lib/Files/Node/FolderTest.php
  tests/lib/Files/Node/NodeTest.php
  tests/lib/Files/Storage/Storage.php
  tests/lib/Files/Storage/StorageFactoryTest.php
  tests/lib/Lockdown/Filesystem/NullStorageTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, technical debt, pending documentation

#48115 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#48110 chore: Remove deprecated aliases from dependency injection
  lib/private/Server.php
  lib/private/legacy/template/functions.php
Labels: 3. to review

#48114 fix(appstoreFetcher): get list from a custom store and remove unnecessary warning
  lib/private/App/AppStore/Fetcher/AppFetcher.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: bug, 2. developing

#48090 fix(settings): disable Discover when appstore is disabled
  apps/settings/src/router/routes.ts
  apps/settings/src/views/AppStoreNavigation.vue
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, backport-request, feature: settings

#48094 fix(Storage): Document getOwner() can return false
  apps/dav/lib/Storage/PublicOwnerWrapper.php
  apps/files_sharing/lib/External/Storage.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  lib/private/Files/Node/Folder.php
  lib/private/Files/Node/Root.php
  lib/private/Files/ObjectStore/HomeObjectStoreStorage.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Home.php
  lib/private/Files/Storage/Wrapper/Availability.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/private/Files/View.php
  lib/private/Lockdown/Filesystem/NullStorage.php
  lib/private/legacy/OC_Helper.php
  lib/public/Files/Storage/IStorage.php
  tests/lib/Lockdown/Filesystem/NullStorageTest.php
Labels: bug, 3. to review, backport-request

#48080 fix(Storage): Fix method docs inheritance
  apps/files_sharing/lib/External/Storage.php
  apps/files_sharing/lib/SharedStorage.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Home.php
  lib/private/Files/Storage/Local.php
  lib/private/Files/Storage/Storage.php
  lib/private/Files/Storage/Wrapper/Availability.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/PermissionsMask.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
Labels: 3. to review, backport-request, technical debt
