Repository nextcloud/server, pull requests merged in 2024-04, with the labels that each got.

#44369 fix: csrf check failed on public share with password
  core/src/main.js
  core/templates/publicshareauth.php
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review, feature: sharing, feature: files

#44612 fix(tests): Fix tests when daytime saving time change happened recently
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, backport-request, tests

#44610 [stable28] fix(files): Fix translation of "Delete file"
  apps/files/src/actions/deleteAction.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: 3. to review

#44619 chore(bug-report-template): update list of nc versions
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 3. to review

#44332 fix(dav): Fix quota check for chunk upload
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
  apps/dav/tests/unit/Connector/Sabre/QuotaPluginTest.php
Labels: bug, 3. to review, feature: dav, backport-request

#44621 fix(SetupChecks): Add hint about dns/firewall if `mjs` check can't run
  apps/settings/lib/SetupChecks/JavaScriptModules.php
Labels: enhancement, 3. to review, backport-request, feature: settings

#44625 fix(federation): ICloudId->getRemote() should contain the protocol
  lib/private/Federation/CloudIdManager.php
  tests/lib/Federation/CloudIdManagerTest.php
Labels: bug, 3. to review, feature: federation, regression

#44511 perf(dav): skip non-calendar requests in webcal caching plugin
  apps/dav/lib/CalDAV/WebcalCaching/Plugin.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/PluginTest.php
Labels: 3. to review, performance 🚀

#44604 fix(encryption): Clicking default module in UI sets bogus value
  apps/settings/src/components/Encryption.vue
  dist/settings-vue-settings-admin-security.js
  dist/settings-vue-settings-admin-security.js.map
Labels: bug, 4. to release, feature: encryption (server-side), backport-request

#44642 fix(appconfig): compare with original value
  lib/private/AppConfig.php
Labels: bug, 3. to review, backport-request

#44306 fix(settings): show warning for indexToReplace as part of missing indices
  apps/settings/lib/SetupChecks/DatabaseHasMissingIndices.php
Labels: bug, 3. to review, feature: settings, feature: occ

#43808 [master] Update psalm-baseline.xml
  .github/workflows/update-psalm-baseline.yml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#44663 fix(DateTimeFormatter): Adjust invalid doc blocks
  lib/private/DateTimeFormatter.php
Labels: 3. to review, php

#44607 feat: drop support for php 8.0
  .drone.yml
  .github/workflows/files-external-ftp.yml
  .github/workflows/files-external-s3.yml
  .github/workflows/files-external-sftp.yml
  .github/workflows/files-external-smb.yml
  .github/workflows/files-external-webdav.yml
  .github/workflows/files-external.yml
  .github/workflows/integration-s3-primary.yml
  .github/workflows/lint-php.yml
  .github/workflows/object-storage-azure.yml
  .github/workflows/object-storage-s3.yml
  .github/workflows/object-storage-swift.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-32bits.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-memcached.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-nodb.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-psalm-baseline.yml
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/settings/lib/SetupChecks/PhpOutdated.php
  build/psalm-baseline.xml
  composer.json
  lib/composer/composer/platform_check.php
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
  lib/private/DB/QueryBuilder/Literal.php
  lib/private/DB/QueryBuilder/Parameter.php
  lib/private/DB/QueryBuilder/QueryFunction.php
  lib/private/Diagnostics/Event.php
  lib/private/legacy/OC_Image.php
  lib/public/Files/LockNotAcquiredException.php
  lib/versioncheck.php
Labels: 3. to review, pending documentation

#44343 [stable28] Fix default text processing provider in AI settings
  apps/settings/lib/Settings/Admin/ArtificialIntelligence.php
Labels: bug, 3. to review, 4. to release, feature: text processing

#44705 fix(Blurhash): Suppress imagecreatefromstring() E_WARNING
  lib/private/Blurhash/Listener/GenerateBlurhashMetadata.php
Labels: bug, 3. to review, backport-request

#44717 fix(oc-dialog): Get rid of the overlay
  core/src/jquery/css/jquery.ocdialog.scss
  core/src/jquery/ocdialog.js
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, backport-request

#43640 fix(styles): Adjust heading styles
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/server.css
  core/css/server.css.map
Labels: design, 2. developing, pending documentation

#44726 fix(AppFramework): Fix error message about 204 not allowing custom headers
  lib/public/AppFramework/Http/Response.php
Labels: 3. to review, technical debt

#44707 chore(RichObjectStrings): Add missing newlines
  lib/public/RichObjectStrings/Definitions.php
Labels: 3. to review

#44216 feat(core): Include core capabilities in OpenAPI
  apps/dav/openapi.json
  apps/federatedfilesharing/openapi.json
  apps/federation/openapi.json
  apps/files/openapi.json
  apps/files_sharing/openapi.json
  apps/provisioning_api/openapi-full.json
  apps/provisioning_api/openapi.json
  apps/settings/openapi-full.json
  apps/settings/openapi.json
  apps/theming/openapi.json
  apps/user_ldap/openapi.json
  apps/user_status/openapi.json
  core/openapi.json
  lib/private/OCS/CoreCapabilities.php
  vendor-bin/openapi-extractor/composer.lock
Labels: enhancement, 2. developing, backport-request

#44714 Call davGetFavoritesReport after the registration of propfind properties
  apps/files/src/services/Favorites.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review, backport-request, feature: files, javascript

#44738 [stable28] fix: Fix avatar images
  lib/private/Avatar/AvatarManager.php
  tests/lib/Avatar/AvatarManagerTest.php
Labels: 3. to review

#44739 [stable27] fix: Fix avatar images
  lib/private/Avatar/AvatarManager.php
  tests/lib/Avatar/AvatarManagerTest.php
Labels: 3. to review

#44730 fix: use proper jailed patch in watcher
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/Wrapper/JailWatcher.php
  lib/private/Files/Storage/Wrapper/Jail.php
  tests/lib/Files/Cache/Wrapper/CacheJailTest.php
Labels: 3. to review

#44294 fix: Pass the mountpoint target user to storages without owner
  apps/files_external/lib/Config/ConfigAdapter.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/public/Files/Storage/IStorage.php
Labels: bug, 4. to release

#44753 feat(occ): Add --disabled option to occ user:list
  core/Command/User/ListCommand.php
Labels: 3. to review, feature: users and groups, feature: occ

#44736 fix: Fix avatar images
  lib/private/Avatar/AvatarManager.php
  tests/lib/Avatar/AvatarManagerTest.php
Labels: 3. to review

#44756 fix: Add deprecation to `OC.dialogs.fileexists`
  core/src/OC/dialogs.js
  dist/core-login.js.map
  dist/core-main.js.map
Labels: bug, 3. to review, backport-request

#44746 docs: Adjust branding in IDBConnection::prepare doc block
  lib/public/IDBConnection.php
Labels: 4. to release

#44450 fix(breadcrumbs): improved rendering of breadcrumb progress bar
  apps/files/src/components/BreadCrumbs.vue
  apps/files/src/views/FilesList.vue
  cypress/e2e/files/FilesUtils.ts
  cypress/e2e/files/live_photos.cy.ts
  cypress/e2e/files_versions/version_cross_share_move_and_copy.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 2. developing, backport-request, feature: files

#44350 fix(LDAP): escape DN on check-user
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Command/CheckUser.php
  apps/user_ldap/lib/Helper.php
Labels: bug, 4. to release, feature: ldap, backport-request

#44771 fix(federation): give some time to prepare both servers
  apps/federation/lib/BackgroundJob/RequestSharedSecret.php
  apps/federation/tests/BackgroundJob/RequestSharedSecretTest.php
Labels: bug, 3. to review, feature: federation

#44773 29.0.0 RC4
  version.php
Labels: 3. to review

#44799 fix(capabilities): Expose if mod-rewrite is working via capabilities
  core/openapi.json
  lib/private/OCS/CoreCapabilities.php
Labels: bug, 3. to review, backport-request

#44770 fix(notifications): Improved notification exceptions
  lib/composer/composer/LICENSE
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Notification/Action.php
  lib/private/Notification/Manager.php
  lib/private/Notification/Notification.php
  lib/public/Notification/IAction.php
  lib/public/Notification/IApp.php
  lib/public/Notification/IDismissableNotifier.php
  lib/public/Notification/INotification.php
  lib/public/Notification/INotifier.php
  lib/public/Notification/IncompleteNotificationException.php
  lib/public/Notification/IncompleteParsedNotificationException.php
  lib/public/Notification/InvalidValueException.php
  lib/public/Notification/UnknownNotificationException.php
Labels: 3. to review, feature: activity and notification, technical debt, pending documentation

#44827 chore(deps): Update openapi-extractor
  apps/files/openapi.json
  apps/files_sharing/openapi.json
  apps/provisioning_api/openapi-administration.json
  apps/provisioning_api/openapi-full.json
  apps/provisioning_api/openapi.json
  apps/settings/openapi-full.json
  apps/settings/openapi.json
  apps/sharebymail/openapi.json
  apps/user_status/openapi.json
  apps/weather_status/openapi.json
  core/openapi.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request

#44810 chore(db): move to OCP\Server
  lib/private/DB/Connection.php
Labels: 3. to review

#44823 [stable27] Fix opening "Remote shares" dialog even if Notifications is available
  apps/federatedfilesharing/js/external.js
Labels: bug, 3. to review, feature: sharing, feature: federation

#38933 feat: remove orphaned entries from filecache_extended
  apps/files/lib/Command/DeleteOrphanedFiles.php
  apps/files/tests/Command/DeleteOrphanedFilesTest.php
Labels: 3. to review, technical debt

#44834 fix(files): Inherit some node attributes when creating new nodes to preserve shared state
  apps/files/src/actions/downloadAction.ts
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/newMenu/newFolder.ts
  apps/files/src/newMenu/newFromTemplate.ts
  apps/files/src/views/TemplatePicker.vue
  dist/2382-2382.js
  dist/2382-2382.js.map
  dist/9558-9558.js
  dist/9558-9558.js.LICENSE.txt
  dist/9558-9558.js.map
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files

#44806 chore(files): Switch widget icon to primary color
  apps/files/src/views/ReferenceFileWidget.vue
  dist/files-reference-files.js
  dist/files-reference-files.js.map
Labels: design, 3. to review, backport-request

#44847 fix(files): Focus filename input in new-node dialog when opened
  apps/files/src/components/NewNodeDialog.vue
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review, backport-request, feature: files

#44658 fix: Remove obsolete resource typing
  apps/files_external/lib/Lib/Storage/FtpConnection.php
  apps/theming/lib/ImageManager.php
  apps/user_ldap/lib/Access.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Group_LDAP.php
  apps/user_ldap/lib/Group_Proxy.php
  apps/user_ldap/lib/IGroupLDAP.php
  apps/user_ldap/lib/ILDAPWrapper.php
  apps/user_ldap/lib/IUserLDAP.php
  apps/user_ldap/lib/LDAP.php
  apps/user_ldap/lib/LDAPProvider.php
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/lib/Wizard.php
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/ConnectionTest.php
  apps/user_ldap/tests/LDAPProviderTest.php
  apps/user_ldap/tests/User_LDAPTest.php
  apps/user_ldap/tests/WizardTest.php
  build/stubs/ftp.php
  build/stubs/gd.php
  build/stubs/imagick.php
  build/stubs/ldap.php
  lib/private/Avatar/Avatar.php
  lib/private/legacy/OC_Image.php
  lib/public/IStreamImage.php
Labels: 3. to review, technical debt

#44741 [stable25] fix: Fix avatar images
  lib/private/Avatar/AvatarManager.php
  tests/lib/Avatar/AvatarManagerTest.php
Labels: 3. to review

#44742 [stable24] fix: Fix avatar images
  lib/private/Avatar/AvatarManager.php
  tests/lib/Avatar/AvatarManagerTest.php
Labels: 3. to review

#44737 [stable29] fix: Fix avatar images
  lib/private/Avatar/AvatarManager.php
  tests/lib/Avatar/AvatarManagerTest.php
Labels: 3. to review

#44870 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#44869 fix(systemtags): Use built-in input label to satisfy a11y check of NcSelect
  apps/systemtags/src/components/SystemTags.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review, backport-request

#44878 fix(status): Update status time when reverting to it manually
  apps/user_status/lib/Service/StatusService.php
Labels: 3. to review, backport-request

#44882 fix(files): Clear search filter when changing directory or view
  apps/files/src/views/FilesList.vue
  core/src/views/UnifiedSearchModal.vue
  cypress/e2e/core-utils.ts
  cypress/e2e/files/files-searching.cy.ts
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files, regression

#44644 fix(appconfig): format app values
  lib/private/AppConfig.php
  lib/private/AppFramework/Services/AppConfig.php
  lib/public/AppFramework/Services/IAppConfig.php
  lib/public/IAppConfig.php
  tests/lib/AppConfigTest.php
Labels: 3. to review, backport-request

#43574 enh(metadata): migrate metadata to lazy appconfig
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/CacheQueryBuilder.php
  lib/private/Files/Cache/QuerySearchHelper.php
  lib/private/FilesMetadata/FilesMetadataManager.php
  lib/private/FilesMetadata/MetadataQuery.php
  lib/public/FilesMetadata/IFilesMetadataManager.php
  lib/public/FilesMetadata/IMetadataQuery.php
Labels: 3. to review, backport-request, performance 🚀

#44868 fix(comments): Fix issues thrown by comments sidebar tab code
  apps/comments/src/comments-tab.js
  apps/comments/src/views/Comments.vue
  apps/files/src/views/Sidebar.vue
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
  dist/comments-comments-tab.js
  dist/comments-comments-tab.js.map
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review, backport-request

#44805 fix(files): Display selected files count
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, backport-request, feature: files, regression

#44838 fix: avoid douple `expireDate` parsing
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: 3. to review, feature: sharing

#44640 fix(appconfig): returns correct value on details
  core/Command/Config/App/SetConfig.php
  lib/private/AppConfig.php
  tests/lib/AppConfigTest.php
Labels: bug, 3. to review, backport-request

#44886 fix(activity): Improved activity exceptions
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Activity/Event.php
  lib/private/Activity/Manager.php
  lib/public/Activity/Exceptions/FilterNotFoundException.php
  lib/public/Activity/Exceptions/IncompleteActivityException.php
  lib/public/Activity/Exceptions/InvalidValueException.php
  lib/public/Activity/Exceptions/SettingNotFoundException.php
  lib/public/Activity/Exceptions/UnknownActivityException.php
  lib/public/Activity/IEvent.php
  lib/public/Activity/IManager.php
  lib/public/Activity/IProvider.php
  tests/lib/Activity/ManagerTest.php
Labels: 3. to review, feature: activity and notification, technical debt

#44907 [stable29] fix(appconfig): returns correct value on details
  core/Command/Config/App/SetConfig.php
  lib/private/AppConfig.php
  tests/lib/AppConfigTest.php
Labels: 3. to review, backport-request

#44889 fix(files): Also skip cross storage move with access control
  lib/private/Files/Storage/Local.php
Labels: bug, 3. to review, feature: filesystem

#44859 feat(user_ldap): Add setup check to verify connection configuration
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/AppInfo/Application.php
  apps/user_ldap/lib/SetupChecks/LdapConnection.php
Labels: enhancement, 3. to review, feature: ldap

#44839 fix(sharingDetails): Show correct share target
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/4997-4997.js
  dist/4997-4997.js.map
  dist/6364-6364.js
  dist/6364-6364.js.LICENSE.txt
  dist/6364-6364.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request

#44916 fix(sharing): Don't change the type of the controller argument
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: bug, 3. to review, feature: sharing

#44904 fix(files): Also restore shares after ownership transfer for object storage
  apps/files/lib/Service/OwnershipTransferService.php
Labels: bug, 3. to review, backport-request, feature: files

#44039 fix: regression with updating read-only config
  lib/private/Config.php
Labels: 3. to review, backport-request

#44874 28.0.5 RC1
  version.php
Labels: 3. to review

#44875 27.1.9 RC1
  version.php
Labels: 3. to review

#44915 fix: Use static_types in ClearGeneratedAvatarCacheCommand.php
  core/Command/User/ClearGeneratedAvatarCacheCommand.php
Labels: 3. to review

#44860 fix(user_ldap): Remove unicode character from log lines
  apps/user_ldap/lib/LoginListener.php
  apps/user_ldap/lib/Service/UpdateGroupsService.php
Labels: bug, 4. to release, feature: ldap

#44861 chore: Fix update-psalm-baseline to use correct php version depending on branch
  psalm.xml
Labels: backport-request, CI

#44928 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#44884 feat: add request id as comment to all queries
  config/config.sample.php
  lib/private/DB/Connection.php
Labels: 3. to review, backport-request

#44025 Migrate away from OC_App and toward IAppManager.
  apps/settings/lib/Controller/AppSettingsController.php
  console.php
  core/Command/App/Enable.php
  core/Command/App/GetPath.php
  core/Command/App/Install.php
  core/Command/App/Remove.php
  core/Command/App/Update.php
  core/Command/L10n/CreateJs.php
  lib/autoloader.php
  lib/private/App/AppManager.php
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/Console/Application.php
  lib/private/Installer.php
  lib/private/L10N/Factory.php
  lib/private/Route/CachingRouter.php
  lib/private/Route/Router.php
  lib/private/Server.php
  lib/private/legacy/OC_App.php
  tests/lib/App/AppManagerTest.php
  tests/lib/AppFramework/Bootstrap/CoordinatorTest.php
  tests/lib/AppFramework/Routing/RoutingTest.php
  tests/lib/AppTest.php
  tests/lib/L10N/FactoryTest.php
  tests/lib/L10N/L10nTest.php
  tests/lib/Route/RouterTest.php
Labels: 3. to review

#44858 Support multiple scopes in DAV search
  apps/dav/lib/Files/FileSearchBackend.php
Labels: enhancement, 3. to review, feature: dav, feature: files, php

#44794 fix(memcache): remove double $$ to fix error
  lib/private/Memcache/LoggerWrapperCache.php
Labels: 4. to release, backport-request

#44973 feat: Add legal notice and privacy policy links to help page
  apps/settings/lib/Controller/HelpController.php
  apps/settings/templates/help.php
  lib/private/NavigationManager.php
Labels: enhancement, 3. to review, privacy

#44982 fix(provisioning_api): Show warning but do not fail when listing accounts in case of users removed from backend but still in database
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: bug, 3. to review, backport-request

#44923 fix: Fix truncation on public page
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
  core/templates/layout.public.php
Labels: bug, design, 3. to review

#44643 feat(trashbin): Add deleted by properties
  apps/files_trashbin/composer/composer/autoload_classmap.php
  apps/files_trashbin/composer/composer/autoload_static.php
  apps/files_trashbin/lib/Helper.php
  apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
  apps/files_trashbin/lib/Sabre/AbstractTrash.php
  apps/files_trashbin/lib/Sabre/ITrash.php
  apps/files_trashbin/lib/Sabre/TrashbinPlugin.php
  apps/files_trashbin/lib/Trash/ITrashItem.php
  apps/files_trashbin/lib/Trash/LegacyTrashBackend.php
  apps/files_trashbin/lib/Trash/TrashItem.php
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/lib/UserMigration/TrashbinMigrator.php
Labels: enhancement, 3. to review, feature: trashbin

#45000 fix(migration): Bump files_trashbin version to trigger migration
  apps/files_trashbin/appinfo/info.xml
Labels: bug, 3. to review

#44955 [stable26] fix(sharing): store link expire date when enabling
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing

#45010 [stable23] fix(files): Also skip cross storage move with access control
  lib/private/Files/Storage/Local.php
Labels: 3. to review

#45005 28.0.5
  version.php
Labels: 3. to review

#45035 fix: chunked upload leading to 0-byte files
  .htaccess
Labels: bug, 3. to review, backport-request

#44496 feat: support "s3-accelerate" endpoint
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: 3. to review

#44670 fix(session): Do not update authtoken last_check for passwordless
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 4. to release, backport-request, feature: authentication, performance 🚀

#45065 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#45066 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#44586 perf(core): add index on name
  core/Application.php
Labels: 3. to review, php, performance 🚀

#44952 perf(templates): Emit RegisterTemplateCreatorEvent to register template creators more lazy
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Template/TemplateManager.php
  lib/public/Files/Template/RegisterTemplateCreatorEvent.php
Labels: 3. to review, performance 🚀

#44996 fix(files): Use OCP\Util::getForbiddenFileNameChars instead of directaccess to system config
  apps/files/lib/Controller/ViewController.php
  apps/files/src/components/FileEntry/FileEntryName.vue
  apps/files/tests/Controller/ViewControllerTest.php
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#45105 [stable29] fix(files): Fix ownership transfer encrypted files detection
  apps/files/lib/Service/OwnershipTransferService.php
Labels: 3. to review, backport-request

#45106 [stable29] fix(setupchecks): Fix opcache buffer check
  apps/settings/lib/SetupChecks/PhpOpcacheSetup.php
Labels: 3. to review, backport-request

#45107 [stable29] fix: Fix default values for ini var in lib/base.php
  lib/base.php
Labels: 3. to review, backport-request

#45108 [stable29] fix(user_ldap): Fix a var name
  apps/user_ldap/lib/Connection.php
Labels: 3. to review, backport-request

#44871 feat: include file id in audit logs
  apps/admin_audit/lib/Actions/Files.php
  apps/admin_audit/lib/AppInfo/Application.php
Labels: enhancement, 3. to review, feature: admin audit

#45117 chore: remove unnecessary ini_set
  lib/base.php
Labels: 3. to review, technical debt

#43412 [stable28] Update psalm-baseline.xml
  build/psalm-baseline.xml
  psalm-ocp.xml
  psalm.xml
Labels: 3. to review, automated pr

#45129 fix(core): add fs_name_hash index to migration
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review, php
