Repository nextcloud/server, pull requests merged in 2024-12, with the labels that each got.

#49587 fix(maintenance): Show a success message on data-fingerprint command
  core/Command/Maintenance/DataFingerprint.php
Labels: bug, 3. to review, backport-request, feature: occ

#49588 fix(setupcheck): Make the Memcache setupcheck use the cache
  apps/settings/lib/SetupChecks/MemcacheConfigured.php
Labels: bug, 3. to review, backport-request, feature: occ

#49558 chore: remove legacy action to test remote endpoint
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/lib/Controller/ExternalSharesController.php
  apps/files_sharing/openapi.json
  apps/files_sharing/tests/Controller/ExternalShareControllerTest.php
Labels: 3. to review, feature: sharing, php, pending documentation

#49568 feat(templates): make second click as confirmation on templates picker
  apps/files/src/components/TemplatePreview.vue
  apps/files/src/views/TemplatePicker.vue
  dist/5421-5421.js
  dist/5421-5421.js.license
  dist/5421-5421.js.map
  dist/5421-5421.js.map.license
  dist/694-694.js
  dist/694-694.js.map
  dist/694-694.js.map.license
  dist/files-init.js
  dist/files-init.js.map
Labels: 3. to review

#49398 fix(files): properly update paths and folder children on node move
  apps/files/src/store/files.ts
  apps/files/src/store/paths.spec.ts
  apps/files/src/store/paths.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, regression

#49527 chore(config): set min supported desktop to `2.7.0`
  apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php
  config/config.sample.php
Labels: 3. to review, technical debt, client: 💻 desktop

#49570 chore: check enums for since and experimental comments
  build/psalm/NcuExperimentalChecker.php
  build/psalm/OcpSinceChecker.php
  lib/unstable/Config/ValueType.php
Labels: 3. to review, technical debt

#49569 perf: improve performance of SharedStorage::getWatcher
  apps/files_sharing/lib/SharedStorage.php
Labels: 3. to review, performance 🚀

#49232 Add an error log message that notifications app isn't enabled at file…
  apps/files_reminders/appinfo/info.xml
  apps/files_reminders/lib/Listener/LoadAdditionalScriptsListener.php
Labels: bug, 4. to release, backport-request, feature: files, feature: activity and notification, feedback-requested

#49291 fix: don't set 'name' on null metadata
  lib/private/Files/Storage/Wrapper/Encoding.php
Labels: 3. to review

#49265 feat(trashbin): Add backend dav property
  apps/files_trashbin/lib/Sabre/TrashbinPlugin.php
Labels: enhancement, 4. to release, feature: dav, feature: trashbin

#49167 feat(files): Update caption for screen readers when uploading is not possible
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/views/FilesList.vue
  cypress/e2e/files_sharing/public-share/view_view-only-no-download.cy.ts
  cypress/e2e/files_sharing/public-share/view_view-only.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, design, 4. to release, accessibility

#49633 fix(setupcheck): Disable PhpMaxFileSize setupcheck for now
  apps/settings/lib/AppInfo/Application.php
Labels: bug, 3. to review, backport-request

#45979 Signed requests
  apps/cloud_federation_api/lib/Capabilities.php
  apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
  apps/cloud_federation_api/openapi.json
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Notifications.php
  apps/files_sharing/lib/External/Storage.php
  build/integration/features/bootstrap/FederationContext.php
  build/integration/federation_features/cleanup-remote-storage.feature
  core/Controller/OCMController.php
  core/Migrations/Version31000Date20240101084401.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Federation/CloudFederationProviderManager.php
  lib/private/OCM/Model/OCMProvider.php
  lib/private/OCM/OCMDiscoveryService.php
  lib/private/OCM/OCMSignatoryManager.php
  lib/private/Security/IdentityProof/Manager.php
  lib/private/Security/Signature/Db/SignatoryMapper.php
  lib/private/Security/Signature/Model/IncomingSignedRequest.php
  lib/private/Security/Signature/Model/OutgoingSignedRequest.php
  lib/private/Security/Signature/Model/SignedRequest.php
  lib/private/Security/Signature/SignatureManager.php
  lib/private/Server.php
  lib/public/OCM/IOCMProvider.php
  lib/unstable/Security/Signature/Enum/DigestAlgorithm.php
  lib/unstable/Security/Signature/Enum/SignatoryStatus.php
  lib/unstable/Security/Signature/Enum/SignatoryType.php
  lib/unstable/Security/Signature/Enum/SignatureAlgorithm.php
  lib/unstable/Security/Signature/Exceptions/IdentityNotFoundException.php
  lib/unstable/Security/Signature/Exceptions/IncomingRequestException.php
  lib/unstable/Security/Signature/Exceptions/InvalidKeyOriginException.php
  lib/unstable/Security/Signature/Exceptions/InvalidSignatureException.php
  lib/unstable/Security/Signature/Exceptions/SignatoryConflictException.php
  lib/unstable/Security/Signature/Exceptions/SignatoryException.php
  lib/unstable/Security/Signature/Exceptions/SignatoryNotFoundException.php
  lib/unstable/Security/Signature/Exceptions/SignatureElementNotFoundException.php
  lib/unstable/Security/Signature/Exceptions/SignatureException.php
  lib/unstable/Security/Signature/Exceptions/SignatureNotFoundException.php
  lib/unstable/Security/Signature/IIncomingSignedRequest.php
  lib/unstable/Security/Signature/IOutgoingSignedRequest.php
  lib/unstable/Security/Signature/ISignatoryManager.php
  lib/unstable/Security/Signature/ISignatureManager.php
  lib/unstable/Security/Signature/ISignedRequest.php
  lib/unstable/Security/Signature/Model/Signatory.php
  version.php
Labels: 3. to review

#49637 fix: Correct wording when attempting to remove a disabled app
  core/Command/App/Remove.php
Labels: bug, 3. to review, feature: apps management, feature: occ

#44555 Handle errors in encryption:migrate-key-storage-format
  core/Command/Encryption/MigrateKeyStorage.php
Labels: 3. to review, feature: encryption (server-side)

#49643 feat(files_external): Enable ownerless shares
  apps/files_external/lib/Config/SystemMountPoint.php
Labels: enhancement, feature: sharing

#48651 fix(files): Correctly copy the cache information during copy operations
  lib/private/Files/Cache/Updater.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/View.php
  lib/public/Files/Cache/IUpdater.php
  tests/lib/Files/ViewTest.php
Labels: bug, 3. to review, feature: encryption (server-side), feature: files, php

#49293 fix: Handle copy of folders containing live photos
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/files/lib/Listener/SyncLivePhotosListener.php
  apps/files_versions/lib/Listener/VersionStorageMoveListener.php
  cypress/e2e/files/FilesUtils.ts
  cypress/e2e/files/LivePhotosUtils.ts
  cypress/e2e/files/live_photos.cy.ts
  lib/private/Files/Node/HookConnector.php
Labels: 2. developing, backport-request, feature: live photos

#49288 fix: smb: don't fail hard if we can't load acls for a file
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3. to review

#49551 fix: don't propagate future mtimes
  lib/private/Files/Cache/Propagator.php
Labels: 3. to review, backport-request

#48769 Fix incorrect permissions when copying shared files
  apps/files_sharing/tests/SharedStorageTest.php
  lib/private/Files/Cache/Cache.php
Labels: 3. to review

#48793 fix: log which file cannot be opened
  apps/dav/lib/Connector/Sabre/File.php
Labels: 4. to release

#49644 fix(files_sharing): List of share type during recipient lookup
  apps/files_sharing/src/components/SharingInput.vue
  dist/3608-3608.js
  dist/3608-3608.js.map
  dist/3608-3608.js.map.license
  dist/6391-6391.js
  dist/6391-6391.js.license
  dist/6391-6391.js.map
  dist/6391-6391.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, backport-request, regression

#49665 30.0.3
  version.php
Labels: 3. to review

#49666 29.0.10
  version.php
Labels: 3. to review

#49667 28.0.13
  version.php
Labels: 3. to review

#49404 fix(user_ldap): retrieve from LDAP first "email shaped" value instead…
  apps/user_ldap/lib/User/User.php
Labels: bug, 4. to release, feature: ldap, feedback-requested

#49262 fix: don't do same-storage move optimization with encryption wrappers
  lib/private/Files/Storage/Common.php
Labels: 3. to review

#49677 fix(db): Create the systag_by_objectid index for new installations
  core/Migrations/Version13000Date20170718121200.php
Labels: bug, 3. to review, backport-request, feature: database

#49646 fix(signed-request): trigger metadata insert with default value manually
  apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/OCM/OCMDiscoveryService.php
  lib/private/Security/Signature/SignatureManager.php
  lib/unstable/Federation/ISignedCloudFederationProvider.php
  lib/unstable/Security/Signature/Model/Signatory.php
Labels: bug, 3. to review, feature: federation, regression

#49352 improve handling of large single-part s3 uploads
  apps/dav/lib/Upload/AssemblyStream.php
  apps/dav/tests/unit/Upload/AssemblyStreamTest.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
Labels: 2. developing

#49295 feat(systemtags): add color support
  apps/dav/lib/SystemTag/SystemTagNode.php
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  apps/dav/lib/SystemTag/SystemTagsInUseCollection.php
  apps/dav/tests/unit/SystemTag/SystemTagNodeTest.php
  apps/systemtags/appinfo/info.xml
  apps/systemtags/composer/composer/autoload_classmap.php
  apps/systemtags/composer/composer/autoload_static.php
  apps/systemtags/lib/Migration/Version31000Date20241018063111.php
  apps/systemtags/lib/Migration/Version31000Date20241114171300.php
  apps/systemtags/src/components/SystemTagPicker.vue
  apps/systemtags/src/css/fileEntryInlineSystemTags.scss
  apps/systemtags/src/event-bus.d.ts
  apps/systemtags/src/files_actions/inlineSystemTagsAction.spec.ts
  apps/systemtags/src/files_actions/inlineSystemTagsAction.ts
  apps/systemtags/src/services/api.ts
  apps/systemtags/src/types.ts
  apps/systemtags/src/utils/colorUtils.ts
  core/Command/SystemTag/Edit.php
  core/Migrations/Version31000Date20241018063111.php
  dist/226-226.js
  dist/226-226.js.license
  dist/226-226.js.map
  dist/226-226.js.map.license
  dist/8114-8114.js
  dist/8114-8114.js.license
  dist/8114-8114.js.map
  dist/8114-8114.js.map.license
  dist/core-common.js.license
  dist/files-sidebar.js
  dist/files-sidebar.js.license
  dist/files-sidebar.js.map
  dist/systemtags-admin.js
  dist/systemtags-admin.js.license
  dist/systemtags-admin.js.map
  dist/systemtags-init.js
  dist/systemtags-init.js.license
  dist/systemtags-init.js.map
  dist/theming-admin-theming.js
  dist/theming-admin-theming.js.map
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/installed.php
  lib/private/SystemTag/SystemTag.php
  lib/private/SystemTag/SystemTagManager.php
  lib/public/SystemTag/ISystemTag.php
  lib/public/SystemTag/ISystemTagManager.php
  package-lock.json
  package.json
  tests/Core/Command/SystemTag/EditTest.php
  tests/lib/SystemTag/SystemTagManagerTest.php
Labels: enhancement, design, 4. to release, feature: tags

#49477 fix(migration): Check if table exists
  core/Migrations/Version30000Date20240906095113.php
Labels: 3. to review, backport-request

#49688 fix(activity): make emails for link share uploads true by default
  apps/files_sharing/lib/Activity/Settings/PublicLinksUpload.php
Labels: bug, 3. to review, feature: sharing, backport-request, feature: activity and notification, feature: emails

#49442 fix(files_sharing): Stop infinite loop blocking link share requests
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/282-282.js
  dist/282-282.js.license
  dist/282-282.js.map
  dist/282-282.js.map.license
  dist/6391-6391.js
  dist/6391-6391.js.map
  dist/6391-6391.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: backport-request

#49737 30.0.4 RC1
  version.php
Labels: 3. to review

#49740 fix(federation): Restore compatibility with Nextcloud 30 servers
  lib/private/OCM/Model/OCMProvider.php
Labels: bug, 3. to review, feature: federation

#49693 fix(files): cancel renaming on enter if no file name changes
  apps/files/src/components/FileEntry/FileEntryName.vue
  cypress/e2e/files/files-renaming.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files

#49750 fix(federation): Allow Oracles empty strings
  lib/unstable/Security/Signature/Model/Signatory.php
Labels: bug, 3. to review, feature: federation

#49503 fix(CalDAV): disable both iTip and iMip messages
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
  apps/dav/tests/unit/CalDAV/Schedule/PluginTest.php
Labels: 4. to release, backport-request

#49747 Disable/hide share edit options when user can not edit the share
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
  dist/282-282.js
  dist/282-282.js.map
  dist/282-282.js.map.license
  dist/4005-4005.js
  dist/4005-4005.js.license
  dist/4005-4005.js.map
  dist/4005-4005.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, backport-request

#49695 fix: only do cache copy in updater if the parent folder should be in cache
  lib/private/Files/Cache/Updater.php
Labels: 3. to review

#49685 fix(files): failsafe when executing actions methods
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files

#49694 fix: Fix ServiceWorker scope when Nextcloud installed in subfolder
  apps/files/src/services/ServiceWorker.js
  dist/files-init.js
  dist/files-init.js.map
Labels: 3. to review, feature: files

#49789 [stable27] Hide share edit options when user can not edit the share
  apps/files_sharing/src/components/SharingEntry.vue
  apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review

#49739 chore: cleanup leftover debug statement
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
Labels: 3. to review

#49815 fix(files_sharing): also submit new share on password submit
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/3537-3537.js
  dist/3537-3537.js.map
  dist/3537-3537.js.map.license
  dist/9701-9701.js
  dist/9701-9701.js.license
  dist/9701-9701.js.map
  dist/9701-9701.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, regression, feature: file sidebar

#49366 fix(files_sharing): Do not wrap password policy exception into a generic one
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 4. to release

#47342 fix: don't recalculate folder size in Cache::delete if the entry didn't exist
  lib/private/Files/Cache/Updater.php
Labels: 3. to review

#49730 feat(dashboard): wish happy birthday
  apps/dashboard/lib/Controller/DashboardController.php
  apps/dashboard/lib/Service/DashboardService.php
  apps/dashboard/src/DashboardApp.vue
  apps/dashboard/tests/DashboardServiceTest.php
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: enhancement, 3. to review

#49843 fix(files_external): wrong type for external mount id
  apps/files_external/lib/Command/StorageAuthBase.php
Labels: bug, 3. to review, backport-request, php

#49839 fix: return 204 instead of 404
  apps/dav/lib/CardDAV/ImageExportPlugin.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
Labels: 3. to review, backport-request

#49668 [stable29] fix(migration): Correctly sort migrations by version number
  lib/private/DB/MigrationService.php
Labels: bug, 3. to review, feature: install and update

#49451 fix(TemplateManager): Make sure TemplateFolder is a Folder
  lib/private/Files/Template/TemplateManager.php
Labels: bug, 3. to review, backport-request, feature: templates

#49867 refactor: Use Http framework where possible
  apps/dav/lib/CalDAV/BirthdayCalendar/EnablePlugin.php
  apps/dav/lib/CalDAV/Publishing/PublishPlugin.php
  apps/dav/lib/CalDAV/Search/SearchPlugin.php
  apps/dav/lib/CardDAV/ImageExportPlugin.php
  apps/dav/lib/CardDAV/MultiGetExportPlugin.php
  apps/dav/lib/Comments/CommentsPlugin.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Connector/Sabre/BearerAuth.php
  apps/dav/lib/Connector/Sabre/ChecksumUpdatePlugin.php
  apps/dav/lib/Connector/Sabre/DummyGetResponsePlugin.php
  apps/dav/lib/Connector/Sabre/FakeLockerPlugin.php
  apps/dav/lib/Connector/Sabre/FilesReportPlugin.php
  apps/dav/lib/DAV/Sharing/Plugin.php
  apps/dav/lib/Provisioning/Apple/AppleProvisioningPlugin.php
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  apps/dav/lib/Upload/ChunkingPlugin.php
  apps/dav/lib/Upload/ChunkingV2Plugin.php
Labels: 3. to review, ♻️ refactor

#49874 Revert "fix: don't recalculate folder size in Cache::delete if the en…
  build/psalm-baseline.xml
  lib/private/Files/Cache/Updater.php
Labels: bug, 3. to review

#49731 fix(calendar): Fix getting the permissions of the user
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/tests/unit/CalDAV/CalendarImplTest.php
  lib/public/Calendar/ICalendar.php
Labels: bug, 3. to review, pending documentation, feature: caldav

#49801 fix(ReferenceApiController): Bump rate limit for public resolve endpoint
  core/Controller/ReferenceApiController.php
Labels: bug, 3. to review, backport-request

#49880 fix(View): Catch exceptions when executing mkdir for non-existent parents
  lib/private/Files/View.php
Labels: bug, 3. to review, backport-request

#49833 chore: ignore vendor-bin for coverage
  .github/workflows/files-external.yml
  tests/phpunit-autotest.xml
Labels: 3. to review

#49900 [stable30] fix: make sure we have a valid scheme when testing ocm urls
  lib/private/OCM/OCMDiscoveryService.php
Labels: bug, 3. to review, feature: sharing, feature: federation, backport-request

#49577 fix(occ): `occ integrity:check-app` and Admin panel "rescan" deliver inconsistent results
  core/Command/Integrity/CheckApp.php
Labels: bug, 3. to review, feature: apps management, feature: settings, feature: occ, feedback-requested

#49797 Harden user_status API
  apps/user_status/lib/Controller/StatusesController.php
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/lib/ResponseDefinitions.php
  apps/user_status/openapi.json
Labels: bug, 3. to review, technical debt

#49917 fix(files): Only register preview service worker once when the instance is hosted at the root path
  apps/files/src/services/ServiceWorker.js
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review, backport-request

#49904 feat(Navigation): emit dedicated event for loading additional entries
  apps/files/lib/App.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/NavigationManager.php
  lib/public/Navigation/Events/LoadAdditionalEntriesEvent.php
  tests/lib/NavigationManagerTest.php
Labels: enhancement, 3. to review

#49924 fix(share): render conflict modal in public shares
  core/src/jquery/octemplate.js
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, 30-feedback

#49895 fix: Fix copying to the root of another mountpoint
  lib/private/Files/Cache/Updater.php
Labels: 3. to review

#49915 fix(navigation): Create a gap between dashboard and files
  apps/dashboard/appinfo/info.xml
Labels: 3. to review

#49681 add sse_c_key from S3 object storage properties config to list of sensitive values
  lib/private/SystemConfig.php
Labels: 3. to review, feedback-requested

#49929 fix(files_sharing): Hide file request if public uploads disabled
  apps/files_sharing/src/files_newMenu/newFileRequest.ts
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, feature: sharing, backport-request, feature: files

#49208 fix: Redirect user to login if session is terminated
  core/src/utils/xhr-request.js
  cypress/e2e/login/login-redirect.cy.ts
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, backport-request, feature: authentication

#48662 feat(dav): introduce paginate with custom headers
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Paginate/LimitedCopyIterator.php
  apps/dav/lib/Paginate/PaginateCache.php
  apps/dav/lib/Paginate/PaginatePlugin.php
  apps/dav/lib/Server.php
  apps/dav/lib/SystemTag/SystemTagList.php
Labels: 3. to review, feature: dav, php, pending documentation

#49961 chore(github): Update groupware code owners
  .github/CODEOWNERS
Labels: 3. to review

#49847 fix(shares): Remove noisy text from email
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  lib/private/Share20/DefaultShareProvider.php
Labels: 3. to review, backport-request

#49887 fix: don't skip scanner users filesystem if they have a mountpoint at /<user>/files/
  build/psalm-baseline.xml
  lib/private/Files/Utils/Scanner.php
Labels: 3. to review
