Repository nextcloud/server, pull requests merged in 2024-05, with the labels that each got.

#45122 fix(querybuilder): Remove temporary internal method executeUpdate()
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 3. to review, technical debt

#45138 retry smb notify test a few times
  apps/files_external/tests/Storage/SmbTest.php
Labels: 3. to review, backport-request

#45131 chore: Remove All files prefix from original location
  apps/files_trashbin/src/columns.ts
  dist/files_trashbin-main.js
  dist/files_trashbin-main.js.map
Labels: 3. to review, feature: trashbin

#45125 fix(deps): Drop `ical.js` from dependencies
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
  package-lock.json
  package.json
  webpack.common.js
Labels: bug, 3. to review, dependencies

#45149 fix(github): Add a security info to the PR template
  .github/pull_request_template.md
Labels: 3. to review

#39247 add option to add backtrace to the query logger
  lib/private/DB/Connection.php
Labels: 4. to release

#45134 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
Labels: 3. to review, automated pr

#44819 fix(files): apply the renaming when leaving the input field
  apps/files/src/components/FileEntry/FileEntryName.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, design, 4. to release, feedback-requested

#45136 feat(webauthn): submit device name by pressing enter
  apps/settings/src/components/WebAuthn/AddDevice.vue
  dist/settings-vue-settings-personal-webauthn.js
  dist/settings-vue-settings-personal-webauthn.js.map
Labels: enhancement, 3. to review

#38670 Wordings : Enhancement of background and UI color change thanks to better title and description
  apps/theming/src/UserThemes.vue
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
Labels: bug, 4. to release, feature: theming

#45140 fix: fix FileAccess::getByFileId(InStorage)
  lib/private/Files/Cache/FileAccess.php
Labels: 3. to review, backport-request

#45096 fix(files): Add missing properties and fix Typescript errors in `FileEntryName`
  apps/files/src/components/FileEntry/FileEntryName.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#45159 fix(tests): Replace deprecated methods in `FileTest`
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
Labels: bug, 3. to review, tests

#45067 Update license header how-to for use of SPDX header
  contribute/HowToApplyALicense.md
Labels: 3. to review, technical debt

#45163 fix(icons): Update files icon
  core/img/places/files.svg
  dist/icons.css
Labels: bug, 3. to review, backport-request

#45086 Update devcontainer PHP dependencies to 8.3
  .devcontainer/Dockerfile
Labels: 3. to review, developer experience

#45160 fix: Changes the color of the "Delete User" and "X" exit buttons on hover.
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 4. to release

#45093 fix(session): Avoid race condition for cache::get() vs. cache::hasKey()
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: bug, 3. to review, backport-request, feature: authentication

#45177 fix(ci): Update `node-test` workflow and drop unneeded `cypress:version` output
  .github/workflows/node-test.yml
Labels: bug, 3. to review

#30359 Allow calling cron jobs background job class with occ
  core/Command/Background/JobBase.php
  core/Command/Background/JobWorker.php
  core/register_command.php
  cron.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/BackgroundJob/JobList.php
  lib/public/BackgroundJob/IJobList.php
  tests/lib/BackgroundJob/DummyJobList.php
Labels: enhancement, 3. to review

#45196 fix(OC_Image): Set correct return type for exif_imagetype stub
  lib/private/legacy/OC_Image.php
Labels: 3. to review, backport-request, technical debt

#45088 fix(User\Manager): Avoid future collisions with updater/audit logs
  lib/private/User/Manager.php
Labels: enhancement, 3. to review, backport-request, feature: users and groups

#44939 fix(settings): Save one HTTP request on enabling an app
  apps/settings/src/store/apps.js
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/server.css
  core/css/server.css.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, backport-request

#45055 fix(userstatus): catch unique constrain violation on revert
  apps/dav/lib/CalDAV/Status/StatusService.php
Labels: bug, 3. to review, backport-request, feature: status

#44564 [stable29] Update psalm-baseline.xml
  apps/dav/lib/CalDAV/CalDavBackend.php
  build/psalm-baseline.xml
  lib/private/Authentication/TwoFactorAuth/Db/ProviderUserAssignmentDao.php
  lib/private/DateTimeFormatter.php
  lib/public/DB/IResult.php
Labels: 3. to review, automated pr

#45133 [stable28] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#44786 Reduce app container border radius
  core/css/apps.scss
Labels: enhancement, design, 3. to review

#45209 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#45208 [stable29] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#44797 fix(Router): Stop loading routes of disabled apps
  lib/private/Route/Router.php
Labels: bug, 3. to review, backport-request

#42973 Expose dashboard layout and statuses API
  apps/dashboard/appinfo/routes.php
  apps/dashboard/composer/composer/autoload_classmap.php
  apps/dashboard/composer/composer/autoload_static.php
  apps/dashboard/lib/Controller/DashboardApiController.php
  apps/dashboard/lib/Controller/DashboardController.php
  apps/dashboard/lib/Controller/LayoutApiController.php
  apps/dashboard/lib/Service/DashboardService.php
  apps/dashboard/openapi.json
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: enhancement, 4. to release, feature: dashboard

#45240 fix(issue_template): Add security reporting redirect to bug report form
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement, 3. to review

#45244 Add SPDX header - batch #1
  .reuse/dep5
  AUTHORS.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  COPYING-README.md
  DESIGN.md
  LICENSES/AGPL-3.0-only.txt
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  SECURITY.md
  __tests__/FileSystemAPIUtils.ts
  __tests__/jest-setup.ts
  apps/federatedfilesharing/src/components/AdminSettings.vue
  apps/federatedfilesharing/src/components/PersonalSettings.vue
  apps/federatedfilesharing/src/main-admin.js
  apps/federatedfilesharing/src/main-personal.js
  babel.config.js
  build/build.xml
  build/files-checker.php
  build/integration/features/bootstrap/SetupContext.php
  build/psalm/AppFrameworkTainter.php
  build/psalm/OcpSinceChecker.php
  codecov.yml
  config/config.sample.php
  contribute/HowToApplyALicense.md
  core/Command/Background/Ajax.php
  core/Command/Background/Base.php
  core/Command/Background/Cron.php
  core/Command/Background/WebCron.php
  core/Command/Info/File.php
  core/Migrations/Version23000Date20210721100600.php
  core/Migrations/Version23000Date20210906132259.php
  core/Migrations/Version24000Date20220202150027.php
  core/Migrations/Version24000Date20220404230027.php
  core/Migrations/Version29000Date20240131122720.php
  core/ajax/update.php
  core/css/animations.css
  core/css/animations.css.map
  core/css/animations.scss
  core/css/guest.css
  core/css/guest.css.map
  custom.d.ts
  cypress.config.ts
  cypress.d.ts
  dist/federatedfilesharing-vue-settings-admin.js
  dist/federatedfilesharing-vue-settings-admin.js.LICENSE.txt
  dist/federatedfilesharing-vue-settings-admin.js.map
  dist/federatedfilesharing-vue-settings-personal.js
  dist/federatedfilesharing-vue-settings-personal.js.map
  jest.config.ts
  psalm-ocp.xml
  psalm.xml
  version.php
  webpack.common.js
  webpack.config.js
  webpack.modules.js
Labels: 3. to review, technical debt

#45250 Revert rename
  AUTHORS
  COPYING-README
Labels: 4. to release, technical debt

#45256 Revert rename changes
  build/files-checker.php
Labels: bug, 3. to review

#45255 fix(ci): Align mariadb versions with list of supported versions
  .github/workflows/phpunit-mariadb.yml
Labels: bug, 3. to review, CI

#45270 refactor(provisioning_api): Add types for user details scopes
  apps/provisioning_api/lib/ResponseDefinitions.php
  apps/provisioning_api/openapi-full.json
  apps/provisioning_api/openapi.json
  lib/private/Accounts/AccountProperty.php
  lib/public/Accounts/IAccountProperty.php
Labels: 3. to review

#45241 fix(setupChecks): update db version checks
  .github/workflows/phpunit-pgsql.yml
  apps/settings/lib/SetupChecks/SupportedDatabase.php
Labels: bug, 3. to review, feature: install and update, feature: settings, CI

#45272 feat(SetupChecks): Refactor DatabaseHasMissingIndices
  apps/settings/lib/SetupChecks/DatabaseHasMissingIndices.php
Labels: enhancement, 3. to review, feature: install and update, feature: settings

#45254 fix: Move hint about firewall issues to common helper string
  apps/settings/lib/SetupChecks/CheckServerResponseTrait.php
  apps/settings/lib/SetupChecks/JavaScriptModules.php
Labels: bug, 3. to review

#43794 fix(files): handle multidimensional arrays in scanner
  lib/private/Files/Cache/Scanner.php
Labels: bug, 3. to review, feature: filesystem, backport-request, feature: files, feature: occ

#45258 fix: getMountsForFileId may return an unordered list
  core/Command/Info/FileUtils.php
Labels: bug, 3. to review

#45233 fix: Avoid updating size when calling touch on a file
  lib/private/Files/View.php
Labels: 3. to review, feature: filesystem, performance 🚀

#45242 fix(setupCheck): Only warn when memcache present w/o memcached
  apps/settings/lib/SetupChecks/MemcacheConfigured.php
Labels: bug, 3. to review, backport-request, feature: settings, regression

#45262 fix(SetupChecks): Detect CLI mode in HTTPS / URL generator check
  apps/settings/lib/SetupChecks/HttpsUrlGeneration.php
Labels: bug, 3. to review, backport-request, feature: settings

#45218 Update pdf icon
  core/img/filetypes/application-pdf.svg
Labels: 3. to review, regression

#44791 fix: consider all paths the user has for a share source when considering max permissions
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review

#45309 fix(caldav): loop through all events for busy events
  apps/dav/lib/CalDAV/CalendarObject.php
Labels: bug, 3. to review, backport-request, feature: caldav

#45288 docs(preview): Improve API parameter descriptions
  core/Controller/PreviewController.php
  core/openapi.json
Labels: 3. to review

#45245 feat: Split display name and username columns
  apps/settings/src/components/Users/UserListHeader.vue
  apps/settings/src/components/Users/UserRow.vue
  apps/settings/src/components/Users/shared/styles.scss
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, design, 3. to review, feature: users and groups

#45227 fix: Remove reminder action from trash
  apps/files_reminders/src/actions/setReminderCustomAction.ts
  apps/files_reminders/src/actions/setReminderMenuAction.ts
  apps/files_reminders/src/actions/setReminderSuggestionActions.ts
  dist/files_reminders-init.js
  dist/files_reminders-init.js.map
Labels: bug, 3. to review, feature: trashbin

#45302 Revert: "Check datadirectory owner, not config owner."
  console.php
  cron.php
Labels: bug, 3. to review, regression

#45237 perf(deleteAction): Queue delete requests
  apps/files/src/actions/deleteAction.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: 3. to review, feature: dav, backport-request, performance 🚀

#45057 feat(exception-template): allow to link to specific documentation for how to retreive server log
  config/config.sample.php
  core/templates/exception.php
  lib/private/legacy/OC_Template.php
Labels: enhancement, 3. to review

#45321 fix: Correctly check result of function
  lib/private/Installer.php
  lib/private/Security/IdentityProof/Signer.php
Labels: bug, 3. to review

#44710 fix(preview): check mime type before processing with Imagick
  lib/private/Preview/Bitmap.php
  lib/private/Preview/Font.php
  lib/private/Preview/HEIC.php
  lib/private/Preview/Illustrator.php
  lib/private/Preview/PDF.php
  lib/private/Preview/Photoshop.php
  lib/private/Preview/Postscript.php
  lib/private/Preview/SGI.php
  lib/private/Preview/SVG.php
  lib/private/Preview/TGA.php
  lib/private/Preview/TIFF.php
  lib/private/PreviewManager.php
Labels: 3. to review, feature: previews and thumbnails, php, feedback-requested

#45317 fix(search): Limit maximum number of search results
  core/Controller/UnifiedSearchController.php
  core/openapi.json
Labels: bug, 3. to review, feature: search

#45340 fix: Extend SVG reference check
  lib/private/Preview/SVG.php
  tests/lib/Preview/SVGTest.php
Labels: bug, 3. to review, feature: previews and thumbnails

#45026 Avoid updating the same oc_authtoken row twice
  config/config.sample.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
Labels: enhancement, 3. to review, feature: authentication, performance 🚀

#45345 fix(IRegistrationContext): Add missing TaskProcessing methods
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
Labels: bug, 3. to review

#45357 fix: add ldap_exop_passwd function to sensitive value
  apps/user_ldap/lib/LDAP.php
Labels: 3. to review, backport-request

#45355 fix: delete user credentials stored in storages_credentials when user gets deleted
  lib/private/User/Listeners/BeforeUserDeletedListener.php
Labels: 3. to review, backport-request

#45236 Hide 'updater.server.url' As It May Contain Enterprise Key
  lib/private/SystemConfig.php
Labels: bug, 4. to release, backport-request

#45346 Fix setOwner since doc
  lib/public/Files/Storage/IStorage.php
Labels: 4. to release, php

#45336 29.0.1 RC1
  version.php
Labels: 3. to review

#45335 28.0.6 RC1
  version.php
Labels: 3. to review

#45374 feat: Add `forbidden_filename_characters` to JSConfig for use in frontend libraries
  lib/private/Template/JSConfigHelper.php
Labels: enhancement, 3. to review, backport-request

#45334 27.1.10 RC1
  version.php
Labels: 3. to review

#45354 docs(TaskProcessingApi): Cleanup endpoint descriptions
  core/Controller/TaskProcessingApiController.php
  core/openapi.json
Labels: 3. to review

#45376 [stable27] perf(deleteAction): Queue delete requests
  apps/files/src/actions/deleteAction.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: 4. to release, feature: dav, performance 🚀

#44460 refactor: remove non-shallow getSharesInFolder
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/files_sharing/lib/Updater.php
  apps/sharebymail/lib/ShareByMailProvider.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
Labels: 3. to review

#45375 Move EventSource to `OC` namespace
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/EventSource.php
  lib/private/EventSourceFactory.php
  lib/public/IEventSource.php
Labels: 3. to review, technical debt

#45422 [stable27] fix(theming): stable 27 disable accessible color config switch
  apps/theming/lib/Util.php
Labels: bug, design, 4. to release, feature: theming

#45415 fix(login-mask): remove `Login with` from label
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, 3. to review

#45406 fix(contactsmenu): empty content margin
  core/src/views/ContactsMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 3. to review, backport-request, feature: contacts menu

#45390 fix: Mark more configs as sensitive
  lib/private/SystemConfig.php
Labels: bug, 3. to review, backport-request

#45400 fix(db): Prevent data loss by temporarily disabling `db:convert-type`
  core/Command/Db/ConvertType.php
Labels: bug, 3. to review, high, backport-request, regression

#45429 Add SPDX header - Batch 3
  .reuse/dep5
  COPYING-README
  tests/data/app/description-multi-lang.xml
  tests/data/app/description-single-lang.xml
  tests/data/app/expected-info.json.license
  tests/data/app/invalid-info.xml
  tests/data/app/navigation-one-item.json.license
  tests/data/app/navigation-one-item.xml
  tests/data/app/navigation-two-items.json.license
  tests/data/app/navigation-two-items.xml
  tests/data/app/valid-info.xml
  tests/data/integritycheck/SomeApp.crt.license
  tests/data/integritycheck/SomeApp.key.license
  tests/data/integritycheck/core.crt.license
  tests/data/integritycheck/core.key.license
  tests/data/integritycheck/root.crt.license
  tests/data/integritycheck/root.key.license
  tests/data/svg/files-app-red.svg
  tests/data/svg/mixed-red.svg
  tests/data/svg/mixed-source.svg
  tests/data/svg/rect-black.svg
  tests/data/svg/rect-red.svg
  tests/data/svg/settings-admin-red.svg
  tests/data/testimage.webp
  tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
  tests/lib/TaskProcessing/TaskProcessingTest.php
  tests/lib/Template/data/combine.json.license
  tests/objectstore/start-swift-ceph.sh
  tests/objectstore/stop-swift-ceph.sh
  tests/objectstore/wait-for-connection
  tests/travis/before_install.sh
  tests/travis/changed_app.sh
  tests/travis/custom.ini
  tests/travis/install.sh
Labels: 4. to release, technical debt

#45394 refactor(files): Fix some ESLint and Typescript issues in FilesList
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#45344 [stable27] fix: Keep download action for files and hide only for relevant files
  apps/files/js/fileactions.js
  apps/files/js/fileactionsmenu.js
  apps/files_sharing/js/sharedfilelist.js
  apps/files_sharing/src/share.js
  dist/files_sharing-additionalScripts.js
  dist/files_sharing-additionalScripts.js.map
  dist/files_sharing-files_sharing.js
  dist/files_sharing-files_sharing.js.map
Labels: bug, 4. to release

#45417 feat(files): refresh preview on etag change
  apps/files/src/components/FileEntry/FileEntryPreview.vue
  apps/files/src/views/Sidebar.vue
  dist/6364-6364.js
  dist/6364-6364.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files-sidebar.js
  dist/files-sidebar.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: enhancement, 4. to release, backport-request, feature: files, feature: previews and thumbnails, technical debt

#45370 feat: Add back searching in disabled user list
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/openapi-full.json
  apps/provisioning_api/openapi.json
  apps/settings/src/components/UserList.vue
  apps/settings/src/store/users.js
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
  lib/private/User/Manager.php
  lib/public/IUserManager.php
  lib/public/User/Backend/IProvideEnabledStateBackend.php
Labels: 3. to review, feature: users and groups

#45032 Replaces "Time:" with "Date and time:" in calendar e-mail notification
  apps/dav/lib/CalDAV/Schedule/IMipService.php
Labels: enhancement, 4. to release, feature: activity and notification, feature: caldav

#44485 Respect empty `expiryDate` value in server
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/openapi.json
  build/integration/features/bootstrap/Sharing.php
  build/integration/sharing_features/sharing-v1.feature
  lib/private/Share20/Manager.php
  lib/private/Share20/Share.php
  lib/public/Share/IShare.php
Labels: 3. to review, feature: sharing, backport-request, 27-feedback, 28-feedback, feedback-requested

#45467 28.0.6
  version.php
Labels: 3. to review

#45506 fix(db): Log long transaction times at debug level
  lib/private/DB/Connection.php
Labels: bug, 3. to review, backport-request, feature: logging

#45521 chore: update .jshintrc
  .jshintrc
Labels: 3. to review

#45014 fix: forbid moving a folder into a subfolder of itself
  lib/private/Files/View.php
Labels: 3. to review, backport-request

#45466 27.1.10 RC2
  version.php
Labels: 3. to review

#45419 fix(files): Implement `SortingService` to fix sorting of files
  apps/files/src/services/SortingService.spec.ts
  apps/files/src/services/SortingService.ts
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.license
  dist/files-main.js.map
  package-lock.json
  package.json
Labels: bug, 3. to review, backport-request, feature: files

#39589 set Doctrine to use nest transactions with savepoints
  lib/private/DB/Connection.php
Labels: enhancement, 3. to review

#45537 fix(files): Adjust type import and usage for removed dependency
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#45013 fix(db): Prevent two connections for single node databases
  lib/private/DB/Connection.php
  tests/lib/DB/ConnectionTest.php
Labels: bug, 3. to review, backport-request, regression

#44664 fix(dav): Rate limit address book creation
  apps/dav/appinfo/v1/carddav.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CardDAV/Security/CardDavRateLimitingPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CardDAV/Security/CardDavRateLimitingPluginTest.php
Labels: bug, 4. to release, feature: dav, feature: carddav

#45295 Add temporary variable for border radius
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: enhancement, 2. developing

#45411 fix(auth): Update authtoken activity selectively
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/User/Session.php
Labels: bug, 3. to review

#45559 add mapping for lock wait timeout
  lib/private/DB/Exceptions/DbalException.php
  lib/public/DB/Exception.php
  tests/lib/DB/Exception/DbalExceptionTest.php
Labels: enhancement, 3. to review

#45562 fix(ShareApiClients): Maintain meaning of `''` and null for share api cli…
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review, feature: sharing

#45550 29.0.2 RC1
  version.php
Labels: 3. to review

#45247 Add variable for inputs border width
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: enhancement, 4. to release

#45472 [stable26] fix(dav): Make `createCalendarObject` atomic
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: bug

#45564 29.0.2 RC2
  version.php
Labels: 3. to review

#45222 CalDAV fix search with limit and time range
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/misc/caldav-search-limit-timerange-1.ics
  apps/dav/tests/misc/caldav-search-limit-timerange-2.ics
  apps/dav/tests/misc/caldav-search-limit-timerange-3.ics
  apps/dav/tests/misc/caldav-search-limit-timerange-4.ics
  apps/dav/tests/misc/caldav-search-limit-timerange-5.ics
  apps/dav/tests/misc/caldav-search-limit-timerange-6.ics
  apps/dav/tests/misc/caldav-search-missing-start-1.ics
  apps/dav/tests/misc/caldav-search-missing-start-2.ics
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  lib/public/Calendar/ICalendar.php
Labels: bug, 4. to release, feature: caldav

#44272 Show upload menu in folders' emptycontent
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 3. to review

#45508 fix:Ensure security.txt file ends with a newline character
  apps/settings/lib/WellKnown/SecurityTxtHandler.php
Labels: bug, 3. to review

#45480 fix(theming): replace standard generic package icon by material design
  core/img/filetypes/package-x-generic.svg
Labels: design, 3. to review, feature: files, papercut

#45565 27.1.10
  version.php
Labels: 3. to review

#44906 feat(files): Use receiving users language for the ownership transfer target folder
  apps/files/lib/Service/OwnershipTransferService.php
  build/integration/features/bootstrap/CommandLineContext.php
  build/integration/files_features/transfer-ownership.feature
Labels: enhancement, 3. to review, feature: files

#45121 fix: Return a file element even if the rendered list does not contained one
  apps/files/js/filelist.js
  apps/files/tests/js/filelistSpec.js
Labels: bug, 3. to review, feature: files

#40207 Refactor `OC\Server::getAvatarManager` in dav app
  apps/dav/lib/Avatars/RootCollection.php
Labels: 4. to release, technical debt

#40137 Refactor `OC\Server::getHTTPClientService`
  build/integration/features/bootstrap/RemoteContext.php
  lib/private/Files/Storage/DAV.php
  lib/private/Share20/ProviderFactory.php
  lib/private/legacy/OC_Util.php
  tests/lib/InstallerTest.php
Labels: 4. to release, technical debt

#40119 Refactor `OC\Server::getContactsManager`
  lib/public/Contacts/IManager.php
Labels: 4. to release, technical debt

#40151 Refactor `OC\Server::getMailer`
  lib/private/Mail/Mailer.php
  lib/private/Share20/ProviderFactory.php
  lib/public/Mail/IMailer.php
  lib/public/Util.php
Labels: 4. to release, technical debt

#40206 Refactor `OC\Server::getAvatarManager` in user_ldap app
  apps/user_ldap/lib/Jobs/Sync.php
  apps/user_ldap/tests/Integration/AbstractIntegrationTest.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserAvatar.php
Labels: 4. to release, technical debt

#36942 unmark deleted users if their last login date is more recent than deleted date
  apps/user_ldap/lib/User/DeletedUsersIndex.php
Labels: bug, 4. to release, feature: ldap

#40141 Refactor `OC\Server::getL10NFactory`
  lib/private/Share20/ProviderFactory.php
  lib/private/TemplateLayout.php
  lib/private/legacy/OC_Util.php
  lib/public/Util.php
  tests/lib/L10N/L10nTest.php
Labels: 4. to release, technical debt

#45413 fix(files): Try to create dir only if it not exists
  lib/private/Files/Node/Folder.php
Labels: 3. to review

#45315 fix(settings): Move new user modal to dialog + minor refactoring
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/Users/NewUserDialog.vue
  apps/settings/src/components/Users/UserListFooter.vue
  apps/settings/src/components/Users/UserListHeader.vue
  apps/settings/src/components/Users/UserRow.vue
  cypress/e2e/settings/users.cy.ts
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: users and groups

#40120 Refactor `OC\Server::getCsrfTokenManager`
  lib/private/User/Session.php
  lib/public/Util.php
Labels: 4. to release, technical debt

#45594 fix(files): Ensure active file list entry is highlighted
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files

#45585 refactor(files): Adjust some Typescript code in virtual files list
  apps/files/src/components/FilesListTableFooter.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/mixins/filesListWidth.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, feature: files

#40124 Refactor `OC\Server::getSecureRandom`
  lib/private/Cache/File.php
  lib/private/DB/Connection.php
  lib/private/Security/SecureRandom.php
  lib/private/Setup/PostgreSQL.php
  lib/private/Share20/ProviderFactory.php
  lib/private/legacy/OC_Util.php
  lib/public/Security/ISecureRandom.php
  tests/lib/DB/MigratorTest.php
  tests/lib/TestCase.php
Labels: 4. to release, technical debt

#40147 Refactor `OC\Server::getNotificationManager`
  core/Application.php
  lib/private/Repair.php
  lib/private/User/User.php
Labels: 4. to release, technical debt
