Repository nextcloud/server, pull requests merged in 2024-08, with the labels that each got.

#46768 fix(files): Provide default file action for file entry name (on click action)
  apps/files/src/actions/downloadAction.spec.ts
  apps/files/src/actions/downloadAction.ts
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/components/FileEntry/FileEntryName.vue
  apps/files/src/components/FileEntryMixin.ts
  apps/files/src/components/FilesListVirtual.vue
  cypress.config.ts
  cypress/e2e/files/files-download.cy.ts
  cypress/e2e/files_sharing/file-request.cy.ts
  cypress/e2e/files_sharing/files-shares-view.cy.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  package-lock.json
  package.json
Labels: bug, 3. to review, backport-request, feature: files

#46901 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#46925 Add small font size variable
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: enhancement, 3. to review

#46873 chore(core): wrap initial state into hidden container
  core/templates/layout.base.php
  core/templates/layout.guest.php
  core/templates/layout.initial-state.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: 4. to release, technical debt

#46810 refactor(files_sharing): Replace security annotations with respective attributes
  apps/files_sharing/lib/Controller/AcceptController.php
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
  apps/files_sharing/lib/Controller/ExternalSharesController.php
  apps/files_sharing/lib/Controller/PublicPreviewController.php
  apps/files_sharing/lib/Controller/RemoteController.php
  apps/files_sharing/lib/Controller/SettingsController.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/lib/Controller/ShareInfoController.php
  apps/files_sharing/lib/Controller/ShareesAPIController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46804 refactor(encryption): Replace security annotations with respective attributes
  apps/encryption/lib/Controller/RecoveryController.php
  apps/encryption/lib/Controller/SettingsController.php
  apps/encryption/lib/Controller/StatusController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46930 fix(core): app menu notification should be in the top right
  core/src/components/AppMenuIcon.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 4. to release

#46942 fix(activity): regroup Files and split sharing activity
  apps/comments/lib/Activity/Setting.php
  apps/files_sharing/lib/Activity/Settings/ShareActivitySettings.php
  apps/systemtags/lib/Activity/Setting.php
  lib/private/Activity/ActivitySettingsAdapter.php
Labels: 3. to review, feature: activity and notification, ♻️ refactor

#46943 fix(AdminSettings/AI): show pref list of only the enabled translation providers
  apps/settings/lib/Settings/Admin/ArtificialIntelligence.php
Labels: 3. to review, backport-request

#40163 Audit the tag creator
  apps/admin_audit/composer/composer/autoload_classmap.php
  apps/admin_audit/composer/composer/autoload_static.php
  apps/admin_audit/lib/Actions/TagManagement.php
  apps/admin_audit/lib/AppInfo/Application.php
Labels: enhancement, 4. to release, feature: admin audit

#45950 chore: Remove deprecated legacy search backend
  apps/comments/lib/AppInfo/Application.php
  apps/files/lib/AppInfo/Application.php
  build/integration/comments_features/comments-search.feature
  core/Controller/SearchController.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Search.php
  lib/private/Search/Provider/File.php
  lib/private/Search/Result/Audio.php
  lib/private/Search/Result/File.php
  lib/private/Search/Result/Folder.php
  lib/private/Search/Result/Image.php
  lib/private/Server.php
  lib/public/ISearch.php
  lib/public/IServerContainer.php
  tests/lib/ServerTest.php
Labels: 3. to review, technical debt, pending documentation

#46918 fix(files): Correctly create Nodes from WebDAV result in "recent"-view
  apps/files/src/services/Files.ts
  apps/files/src/services/Recent.ts
  cypress/e2e/files/recent-view.cy.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files, regression

#46550 fix(dav): drop unwanted RemoteException class
  public.php
  remote.php
Labels: bug, 3. to review, backport-request

#46807 refactor(files): Replace security annotations with respective attributes
  apps/files/lib/Controller/ApiController.php
  apps/files/lib/Controller/DirectEditingController.php
  apps/files/lib/Controller/DirectEditingViewController.php
  apps/files/lib/Controller/OpenLocalEditorController.php
  apps/files/lib/Controller/TemplateController.php
  apps/files/lib/Controller/TransferOwnershipController.php
  apps/files/lib/Controller/ViewController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46864 fix: don't persist previews used during blurhash generation - take 2
  lib/private/Blurhash/Listener/GenerateBlurhashMetadata.php
Labels: bug, 3. to review, backport-request, feature: previews and thumbnails, performance 🚀

#46881 fix: try to find non-recursive share source
  apps/files_sharing/lib/SharedStorage.php
Labels: bug, 3. to review, high

#46287 fix(userstatus): add missing parenthesis
  apps/dav/lib/CalDAV/Status/StatusService.php
Labels: 3. to review, backport-request

#46353 fix(setupchecks): Skip checking for OPcache settings if running checks from CLI
  apps/settings/lib/SetupChecks/PhpOpcacheSetup.php
Labels: 4. to release, backport-request, feedback-requested

#46956 fix(LDAP): remove unneeded dependencies
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/lib/User_Proxy.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestAttributeDetection.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestFetchUsersByLoginName.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestPaging.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserAvatar.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserCleanUp.php
  apps/user_ldap/tests/Integration/Lib/User/IntegrationTestUserDisplayName.php
  apps/user_ldap/tests/User_LDAPTest.php
  apps/user_ldap/tests/User_ProxyTest.php
Labels: 3. to review, backport-request, technical debt

#46923 Feat: update border radius variables
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/tests/Themes/DefaultThemeTest.php
Labels: enhancement, design, 3. to review, feature: theming, pending documentation

#46963 fix(files): cancel move-copy action should not be handled as an error
  apps/files/src/actions/moveOrCopyAction.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files

#46958 fix(files): Minimize `min-height` of dialog form
  apps/files/src/components/NewNodeDialog.vue
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 4. to release, feature: files

#45487 fix: Reset notification email when deleting additonal email
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 3. to review, feature: emails

#46989 fix(files): show folder sharing overlay on received shares
  apps/files/src/components/FileEntry/FileEntryPreview.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, regression, 28-feedback, 29-feedback, 30-feedback

#46886 fix: ensure array returned from getMountsForFileId is continious
  lib/private/Files/Config/UserMountCache.php
Labels: 3. to review

#46890 fix: Update documentation for Mail Provider Send
  lib/public/Mail/Provider/IMessageSend.php
Labels: 3. to review

#46975 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#47015 fix(files): Correctly handle open file URL query
  apps/files/lib/Controller/ViewController.php
  apps/files/src/composables/useRouteParameters.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#46919 fix(caldav): allow listing of room and resource principals
  apps/dav/lib/RootCollection.php
Labels: bug, 3. to review

#42800 enh(metadata): Introduce a memory limit for metadata generation
  config/config.sample.php
  core/BackgroundJobs/GenerateMetadataJob.php
Labels: 4. to release, backport-request, feature: previews and thumbnails

#46931 fix: fix passing additional db connection parameters in factory
  lib/private/DB/ConnectionFactory.php
Labels: 3. to review, backport-request

#46534 fix: Add direct parameter to flow auth v2
  core/Controller/ClientFlowLoginV2Controller.php
  core/templates/loginflowv2/authpicker.php
  core/templates/loginflowv2/grant.php
Labels: bug, 3. to review, backport-request

#39217 Refactor "substr" calls in lib/public to improve code readability
  lib/public/AppFramework/AuthPublicShareController.php
Labels: 2. developing, technical debt, stale

#46924 fix(files_sharing): filter out invalid shareWith in sharee API
  apps/files_sharing/lib/Controller/ShareesAPIController.php
Labels: bug, 3. to review

#46880 fix: Make account menu follow the design (use nextcloud-vue components)
  apps/user_status/src/UserStatus.vue
  core/src/components/AccountMenu/AccountMenuEntry.vue
  core/src/components/AccountMenu/AccountMenuProfileEntry.vue
  core/src/components/UserMenu.js
  core/src/components/UserMenu/ProfileUserMenuEntry.vue
  core/src/components/UserMenu/UserMenuEntry.vue
  core/src/views/AccountMenu.vue
  core/src/views/UserMenu.vue
  cypress/e2e/settings/access-levels.cy.ts
  dist/core-main.js
  dist/core-main.js.map
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.license
  dist/user_status-menu.js.map
Labels: design, 3. to review

#46926 tests: don't reuse the query builder for multiple tables in CardDavBackendTest
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
Labels: 3. to review

#46953 chore: delete repair step for 8y old oc_mounts issue
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC11/FixMountStorages.php
  tests/lib/Repair/NC11/FixMountStoragesTest.php
Labels: 3. to review

#45091 Education "bundle"
  cypress/e2e/settings/apps.cy.ts
  lib/private/App/AppStore/Bundles/EducationBundle.php
  tests/lib/App/AppStore/Bundles/EducationBundleTest.php
Labels: 3. to review, feature: apps management, feature: language l10n and translations, feature: recommended apps

#46974 feat(migrations): add metadata to existing migrations
  apps/dav/lib/Migration/Version1031Date20240610134258.php
  apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
  core/Migrations/Version30000Date20240429122720.php
  core/Migrations/Version30000Date20240708160048.php
  core/Migrations/Version30000Date20240717111406.php
Labels: enhancement, 3. to review, feature: install and update, php, 🍂 2024-Autumn

#47043 fix(inherited-shares): ignore top root folder
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: backport-request

#46710 fix: Use timestamp instead of revision id in files_versions metadata API
  apps/files_versions/lib/Sabre/VersionFile.php
Labels: bug, 3. to review, backport-request, feature: files, php

#45054 fix(caldav): Add sharee to address list when calendar is shared
  apps/dav/lib/CalDAV/Schedule/Plugin.php
  apps/dav/tests/unit/CalDAV/Schedule/PluginTest.php
Labels: 3. to review

#46985 feat(sharebymail): improve share email format
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email-single-button.html
  tests/data/emails/new-account-email.html
Labels: 3. to review, feature: sharing, feature: emails

#47065 fix: Ensure database connection is setup when getting group details
  lib/private/Group/Database.php
Labels: bug, 3. to review, backport-request

#47048 fix: Do not log link reference exceptions as error
  lib/public/Collaboration/Reference/LinkReferenceProvider.php
Labels: bug, 3. to review

#38364 fix(previews): Don't crash on animated WEBP images
  lib/private/legacy/OC_Image.php
Labels: bug, 3. to review, backport-request, feature: previews and thumbnails

#40427 feat: Adding the displayname to the output of occ group:list --info
  core/Command/Group/ListCommand.php
Labels: 4. to release, feature: users and groups, feature: occ, stale

#47061 fix(webhook_listeners): Avoid collision between two identical calls at the same second
  apps/webhook_listeners/lib/Listener/WebhooksEventListener.php
Labels: bug, 3. to review

#47083 fix: Fix failing test for group listing
  tests/Core/Command/Group/ListCommandTest.php
Labels: bug, 3. to review

#46983 [stable29] fix(files_sharing): add missing subtitle on search for share recipients
  apps/files_sharing/src/components/SharingInput.vue
  dist/4605-4605.js
  dist/4605-4605.js.map
  dist/6475-6475.js
  dist/6475-6475.js.LICENSE.txt
  dist/6475-6475.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 2. developing, feature: sharing

#47070 fix(share): Rename Circle to Team
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review, backport-request

#46229 fix(config): Clarify smtp debugging config option usage
  config/config.sample.php
Labels: bug, 3. to review, backport-request

#45879 feat: add command to export certificate bundle
  core/Command/Security/ExportCertificates.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: enhancement, 3. to review, feature: occ

#45193 docs: added customclient_fdroid key to the config.sample.php file
  config/config.sample.php
Labels: bug, 4. to release, backport-request, feedback-requested

#46982 [stable28] fix(files_sharing): add missing subtitle on search for share recipients
  apps/files_sharing/src/components/SharingInput.vue
  dist/3535-3535.js
  dist/3535-3535.js.map
  dist/3761-3761.js
  dist/3761-3761.js.LICENSE.txt
  dist/3761-3761.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 2. developing, feature: sharing

#47090 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#44666 occ: Improve and make consistent `user:lastseen` and `user:info` timestamps
  core/Command/User/LastSeen.php
Labels: enhancement, 4. to release, feature: users and groups, feature: occ, feedback-requested

#47095 fix(theming): make cache buster depend on the app version
  apps/theming/lib/Util.php
Labels: bug, 4. to release, high, backport-request, feature: theming, feature: caching

#46945 feat(activity): add share link upload notifications
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/Activity/Settings/PublicLinksUpload.php
Labels: 3. to review, feature: sharing, feature: activity and notification

#47071 fix(admin_audit): Do not log errors for new files
  apps/admin_audit/lib/Actions/Files.php
Labels: bug, 3. to review, 30-feedback

#46106 fix(session): Log when session_* calls are slow
  cron.php
  lib/base.php
  lib/private/Server.php
  lib/private/Session/Internal.php
  lib/private/Session/Memory.php
  lib/private/Session/Session.php
  tests/lib/Session/CryptoSessionDataTest.php
  tests/lib/Session/MemoryTest.php
  tests/lib/User/SessionTest.php
Labels: 4. to release, backport-request, performance 🚀

#47069 fix(migration-preview): display a message if no attributes set
  core/Command/Db/Migrations/PreviewCommand.php
  lib/private/Migration/MetadataManager.php
Labels: 3. to review

#46623 fix(caldav): fixed initial sync and double processing
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: bug, 3. to review

#45841 feat(dav): add regex to match Gnome and KDE calendar user-agents
  apps/dav/lib/CalDAV/WebcalCaching/Plugin.php
Labels: enhancement, 4. to release, feature: dav, feedback-requested

#47106 fix(files): file name and header sort buttons alignments
  apps/files/src/components/FilesListTableHeaderButton.vue
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, regression, 30-feedback

#46395 fix: set default TTL for APCu cache as per docs
  lib/private/Memcache/APCu.php
  lib/private/Memcache/Redis.php
  lib/public/ICache.php
  lib/public/IMemcache.php
  psalm.xml
Labels: 3. to review

#47044 fix(encryption): Fix mountpoint check to accept if several are found
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: bug, 4. to release, feature: encryption (server-side), backport-request

#47031 fix: Ensure app overflow menu is rendered centered
  core/src/components/AppMenu.vue
  core/src/components/AppMenuEntry.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 3. to review

#47034 fix: Make app menu overflow entries vertically aligned
  core/src/components/AppMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 3. to review

#47116 fix(migration): Add column only if it does not exist
  core/Migrations/Version13000Date20170718121200.php
Labels: 3. to review, backport-request

#47120 fix(systemtags): Correctly load tagged files in "tags"-files-view
  apps/systemtags/src/services/systemtags.ts
  dist/systemtags-init.js
  dist/systemtags-init.js.map
Labels: bug, 3. to review, backport-request, feature: tags, regression

#46624 fix(caldav): test for null and blank value
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
  apps/dav/tests/unit/CalDAV/Reminder/ReminderServiceTest.php
Labels: bug, 2. developing

#47121 fix(systemtags): Make inline tags list fully accessible
  apps/systemtags/src/files_actions/inlineSystemTagsAction.spec.ts
  apps/systemtags/src/files_actions/inlineSystemTagsAction.ts
  apps/systemtags/src/files_views/systemtagsView.ts
  apps/systemtags/src/init.ts
  cypress/e2e/systemtags/files-inline-action.cy.ts
  cypress/e2e/systemtags/files-sidebar.cy.ts
  dist/systemtags-init.js
  dist/systemtags-init.js.map
Labels: bug, 3. to review, feature: files, feature: tags, accessibility

#47140 fix: Make focused app menu entry wider to see full name
  core/src/components/AppMenu.vue
  core/src/components/AppMenuEntry.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 3. to review

#46456 fix(SetupCheck): Properly check public access to data directory
  apps/settings/lib/SetupChecks/DataDirectoryProtected.php
  apps/settings/tests/SetupChecks/DataDirectoryProtectedTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC30/RemoveLegacyDatadirFile.php
  lib/private/Setup.php
  lib/private/Updater.php
  lib/private/User/Manager.php
  lib/private/legacy/OC_Util.php
  tests/lib/UtilCheckServerTest.php
  tests/lib/UtilTest.php
Labels: bug, 3. to review, ♻️ refactor

#47147 fix(files): trim names on new node creation
  apps/files/src/components/NewNodeDialog.vue
  apps/files/src/newMenu/newFolder.ts
  apps/files/src/newMenu/newFromTemplate.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 4. to release, backport-request, feature: files

#47135 fix(systemtags): Sub folders should be opened in files
  apps/systemtags/src/files_actions/openInFilesAction.spec.ts
  apps/systemtags/src/files_actions/openInFilesAction.ts
  apps/systemtags/src/init.ts
  dist/systemtags-init.js
  dist/systemtags-init.js.map
Labels: bug, 3. to review, feature: files, feature: tags

#47152 fix(styles): Guest layout should follow the new design
  core/css/guest.css
  core/css/guest.css.map
  core/css/guest.scss
Labels: bug, design, 3. to review

#47153 fix: fix getting the folder node from the dav response
  apps/files_trashbin/src/services/trashbin.ts
  dist/files_trashbin-init.js
  dist/files_trashbin-init.js.map
Labels: bug, 3. to review, backport-request, feature: trashbin

#46987 fix(dav): Ensure share properties are also set on public remote endpoint
  apps/dav/appinfo/v2/publicremote.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Connector/Sabre/Node.php
  apps/dav/lib/DAV/ViewOnlyPlugin.php
  apps/dav/lib/Storage/PublicShareWrapper.php
  apps/dav/tests/unit/Connector/Sabre/NodeTest.php
  apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
  apps/files_sharing/lib/ISharedStorage.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  build/integration/dav_features/dav-v2-public.feature
  build/integration/features/bootstrap/WebDav.php
  build/integration/run-docker.sh
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Files/Storage/ISharedStorage.php
Labels: bug, 3. to review, feature: dav

#47177 [Task processing] Fix preferred providers
  apps/testing/composer/composer/autoload_classmap.php
  apps/testing/composer/composer/autoload_static.php
  apps/testing/lib/AppInfo/Application.php
  apps/testing/lib/TaskProcessing/FakeContextWriteProvider.php
  apps/testing/lib/TaskProcessing/FakeTextToImageProvider.php
  apps/testing/lib/TaskProcessing/FakeTextToTextProvider.php
  apps/testing/lib/TaskProcessing/FakeTranscribeProvider.php
  apps/testing/lib/TaskProcessing/FakeTranslateProvider.php
  lib/private/TaskProcessing/Manager.php
  lib/private/TaskProcessing/SynchronousBackgroundJob.php
  lib/public/TaskProcessing/IManager.php
Labels: bug, 3. to review, feature: text processing

#47130 28.0.9 RC1
  version.php
Labels: 3. to review

#47188 fix(avatar): Fix icon-color for action-router contacts menu options
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review

#47181 fix(files): Add messages when "new folder" fails or gets cancelled
  apps/files/src/newMenu/newFolder.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review, feature: files

#47180 Apply group limit on remove from group
  cypress/e2e/files_sharing/limit_to_same_group.cy.ts
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/ProviderFactory.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 3. to review, backport-request

#41740 fix(dav): Handle duplicate event reminder
  apps/dav/lib/CalDAV/Reminder/Backend.php
  apps/dav/lib/CalDAV/Reminder/ReminderService.php
  apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php
Labels: bug, 4. to release, feature: caldav

#47189 chore: Ship twofactor_nextcloud_notification
  core/shipped.json
Labels: 3. to review

#47195 fix(federation): Return the used userID to allow the inviting server …
  apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
  apps/cloud_federation_api/lib/ResponseDefinitions.php
  apps/cloud_federation_api/openapi.json
Labels: bug, 3. to review, feature: federation

#45786 fix(caldav): allow VJOURNAL if no supported component set is specified
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
Labels: bug, 4. to release, feature: caldav

#43573 Fix for ignored `CSP_NONCE` in ContentSecurity Header
  core/templates/layout.base.php
  core/templates/layout.guest.php
  core/templates/layout.initial-state.php
  core/templates/layout.public.php
  core/templates/layout.user.php
  lib/private/AppFramework/Middleware/Security/CSPMiddleware.php
  lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php
  lib/private/Template/Base.php
  lib/private/legacy/OC_Template.php
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
  tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php
  tests/lib/AppFramework/Http/EmptyContentSecurityPolicyTest.php
  tests/lib/AppFramework/Middleware/Security/CSPMiddlewareTest.php
  tests/lib/Security/CSP/ContentSecurityPolicyNonceManagerTest.php
Labels: bug, 3. to review, security

#47200 fix: test variables before returning
  apps/dav/lib/CalDAV/EventReaderRRule.php
Labels: bug, 3. to review

#45435 feat(dav): Add an API for upcoming events
  apps/dav/appinfo/routes.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/UpcomingEvent.php
  apps/dav/lib/CalDAV/UpcomingEventsService.php
  apps/dav/lib/Controller/UpcomingEventsController.php
  apps/dav/lib/ResponseDefinitions.php
  apps/dav/openapi.json
  apps/dav/tests/unit/Controller/UpcomingEventsControllerTest.php
  apps/dav/tests/unit/Service/UpcomingEventsServiceTest.php
  lib/private/Calendar/Manager.php
Labels: 3. to review, feature: dav

#46723 feat(webcal): only update modified and deleted events from webcal calendars
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/WebcalCaching/Connection.php
  apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/ConnectionTest.php
  apps/dav/tests/unit/CalDAV/WebcalCaching/RefreshWebcalServiceTest.php
Labels: 4. to release, performance 🚀, feature: caldav

#46888 feat: enable bruteforcesettings app by default
  core/shipped.json
Labels: enhancement, 3. to review

#47209 chore(i18n): Improved grammar
  apps/files/src/newMenu/newFolder.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: 4. to release, feature: files, feature: language l10n and translations

#47207 fix(files): Fix non-sticky sticky views in files nav
  apps/files/src/views/Navigation.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, regression

#46821 refactor(updatenotification): Replace security annotations with respective attributes
  apps/updatenotification/lib/Controller/ChangelogController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46816 refactor(settings): Replace security annotations with respective attributes
  apps/settings/lib/Controller/AISettingsController.php
  apps/settings/lib/Controller/AdminSettingsController.php
  apps/settings/lib/Controller/AppSettingsController.php
  apps/settings/lib/Controller/AuthSettingsController.php
  apps/settings/lib/Controller/ChangePasswordController.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/Controller/HelpController.php
  apps/settings/lib/Controller/LogSettingsController.php
  apps/settings/lib/Controller/MailSettingsController.php
  apps/settings/lib/Controller/PersonalSettingsController.php
  apps/settings/lib/Controller/ReasonsController.php
  apps/settings/lib/Controller/UsersController.php
  apps/settings/lib/Controller/WebAuthnController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46814 refactor(oauth2): Replace security annotations with respective attributes
  apps/oauth2/lib/Controller/LoginRedirectorController.php
  apps/oauth2/lib/Controller/OauthApiController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46806 refactor(federation): Replace security annotations with respective attributes
  apps/federation/lib/Controller/OCSAuthAPIController.php
  apps/federation/lib/Controller/SettingsController.php
Labels: 3. to review, technical debt, ♻️ refactor

#47016 refactor(files): Drop unneeded initial state
  apps/files/lib/Controller/ViewController.php
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, feature: files, ♻️ refactor

#46812 refactor(files_trashbin): Replace security annotations with respective attributes
  apps/files_trashbin/lib/Controller/PreviewController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46813 refactor(files_versions): Replace security annotations with respective attributes
  apps/files_versions/lib/Controller/PreviewController.php
Labels: 3. to review, technical debt, ♻️ refactor

#46887 fix(files_versions): Catch constraint error on version insertion
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
Labels: bug, 3. to review

#47201 fix(userstatus): run user status automation job for start and end events
  apps/user_status/lib/AppInfo/Application.php
  apps/user_status/lib/Listener/OutOfOfficeStatusListener.php
Labels: bug, 3. to review, backport-request, feature: status

#47211 fix(core): Limit valid avatar sizes
  core/Controller/AvatarController.php
  core/Controller/GuestAvatarController.php
  core/openapi-full.json
  core/openapi.json
Labels: 3. to review, technical debt

#46809 refactor(files_external): Replace security annotations with respective attributes
  apps/files_external/lib/Controller/AjaxController.php
  apps/files_external/lib/Controller/ApiController.php
  apps/files_external/lib/Controller/UserGlobalStoragesController.php
  apps/files_external/lib/Controller/UserStoragesController.php
Labels: 4. to release, technical debt, ♻️ refactor

#47235 chore(branchoff): Test against stable30 branches
  .github/workflows/integration-sqlite.yml
  .github/workflows/performance.yml
  README.md
  build/update-apps.sh
  build/update.sh
  codecov.yml
Labels: 3. to review

#47203 fix(AppMenu): Prevent menu entries from jumping on hover
  core/src/components/AppMenu.vue
  core/src/components/AppMenuEntry.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 4. to release, regression

#47240 fix(webauthn): Increase database column for public key id
  core/Migrations/Version19000Date20200211083441.php
  core/Migrations/Version30000Date20240814180800.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: bug, 3. to review, backport-request, feature: authentication

#47252 fix(adminaudit): Don't crash when creating folder
  apps/admin_audit/lib/Actions/Files.php
Labels: bug, 3. to review, backport-request

#47258 Don't save translated predefined user status as custom status
  apps/user_status/src/components/SetStatusModal.vue
  dist/user-status-modal-5133.js
  dist/user-status-modal-5133.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: bug, 3. to review, backport-request, papercut, regression, feature: status

#39692 Refactor encryption app commands
  apps/encryption/lib/Command/DisableMasterKey.php
  apps/encryption/lib/Command/DropLegacyFileKey.php
  apps/encryption/lib/Command/EnableMasterKey.php
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/lib/Command/FixKeyLocation.php
  apps/encryption/lib/Command/RecoverUser.php
  apps/encryption/lib/Command/ScanLegacyFormat.php
Labels: 4. to release, technical debt

#37761 invalidate oauth2 tokens only for seen users
  apps/oauth2/lib/Controller/SettingsController.php
  apps/oauth2/tests/Controller/SettingsControllerTest.php
Labels: bug, 4. to release, feature: authentication

#38857 (base) Give a hint in web interface if SimpleXML (php-xml) is missing
  lib/base.php
Labels: bug, 4. to release

#38630 Fix remaining readdir() calls in loops with undesirable false evaluation potential
  apps/files_external/lib/Lib/Storage/Swift.php
  apps/files_trashbin/lib/Trashbin.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/PolyFill/CopyDirectory.php
  tests/apps.php
  tests/lib/Files/Storage/Storage.php
  tests/lib/Files/Storage/Wrapper/EncodingTest.php
  tests/lib/Files/Storage/Wrapper/JailTest.php
Labels: 4. to release, technical debt

#47248 fix: Adjust legacy CSS styles for new Nextcloud 30 design
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/inputs.css
  core/css/inputs.css.map
  core/css/inputs.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, design, 3. to review, backport-request

#38750 fix #38749, postgresql GRANT user's permission after createDatabase, …
  lib/private/Setup/PostgreSQL.php
Labels: bug, 4. to release

#35867 Modify user_ldap checkPassword to not fetch records from ldap each time because of extremely high CPU usage!
  apps/user_ldap/lib/User_LDAP.php
  apps/user_ldap/tests/User_LDAPTest.php
Labels: 4. to release, performance 🚀

#39611 Add `occ user:welcome` command to send user welcome email from CLI
  core/Command/User/Welcome.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 4. to release, feature: occ, stale

#47277 [occ:bg-job:worker] Add 'stop_after' option
  core/Command/Background/JobWorker.php
Labels: enhancement, 3. to review, backport-request

#47287 fix: Access node owner by top level `owner` property
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/newMenu/newFolder.ts
  apps/files_sharing/src/actions/sharingStatusAction.ts
  apps/files_sharing/src/components/FileListFilterAccount.vue
  apps/files_sharing/src/views/FilesHeaderNoteToRecipient.vue
  cypress/e2e/files_sharing/files-inline-action.cy.ts
  dist/5804-5804.js
  dist/5804-5804.js.map
  dist/5804-5804.js.map.license
  dist/9196-9196.js
  dist/9196-9196.js.license
  dist/9196-9196.js.map
  dist/9196-9196.js.map.license
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, feature: sharing, backport-request, feature: files

#47182 perf: improve cleanup of tags/comments
  apps/files/lib/BackgroundJob/DeleteOrphanedItems.php
Labels: 3. to review, backport-request, performance 🚀

#47332 fix(caldav): allow renaming of birthday calendars
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/Command/DeleteCalendarTest.php
Labels: 3. to review, backport-request

#47346 store the mountpoint of storages in the mount options and use it to find the encryption keys
  lib/private/Files/SetupManager.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3. to review, backport-request

#47327 Remerge: [stable28] Apply group limit on remove from group""
  cypress/e2e/files_sharing/limit_to_same_group.cy.ts
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/ProviderFactory.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 4. to release

#47350 chore(build): Remove old Drone CI signed-off checker
  build/signed-off-checker.php
Labels: 3. to review, technical debt

#47351 fix(build): Allow update-apps.sh script to work with non-master branches
  build/update-apps.sh
Labels: bug, 3. to review

#47356 chore: Add webhook_listeners to list of shipped apps
  .github/CODEOWNERS
  .tx/config
  build/translation-checker.php
  core/shipped.json
Labels: 3. to review, backport-request

#47358 Bump Hub 8 -> Hub 9
  apps/settings/templates/settings/admin/overview.php
Labels: 3. to review, backport-request

#47378 [stable29] fix(setupcheck): Fix mimetype server version check in backport
  lib/private/Repair/RepairMimeTypes.php
Labels: 3. to review

#47331 fix: adding blurhash to definitions
  lib/public/RichObjectStrings/Definitions.php
Labels: 2. developing, backport-request, technical debt

#47377 [stable28] fix(setupcheck): Fix mimetype server version check in backport
  lib/private/Repair/RepairMimeTypes.php
Labels: 3. to review

#47372 fix: `FilenameValidator::isForbidden` should only check forbidden files
  config/config.sample.php
  lib/private/Files/FilenameValidator.php
  tests/lib/Files/FilenameValidatorTest.php
Labels: bug, 3. to review, backport-request, 🍂 2024-Autumn

#47381 chore(deps): Update openapi-extractor to v1.0.0
  apps/dashboard/openapi.json
  apps/dav/openapi.json
  apps/federation/openapi.json
  apps/files/openapi.json
  apps/files_sharing/openapi.json
  apps/files_trashbin/openapi.json
  apps/files_versions/openapi.json
  apps/oauth2/openapi.json
  apps/provisioning_api/openapi-administration.json
  apps/provisioning_api/openapi-full.json
  apps/provisioning_api/openapi.json
  apps/theming/openapi.json
  apps/updatenotification/openapi.json
  apps/user_ldap/openapi.json
  apps/user_status/openapi.json
  apps/webhook_listeners/openapi.json
  core/openapi-ex_app.json
  core/openapi-full.json
  core/openapi.json
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request, dependencies

#47352 fix(TaskProcessing/ContextWrite): Fix wording "ContextWrite" -> "Context write"
  lib/public/TaskProcessing/TaskTypes/ContextWrite.php
Labels: 3. to review, backport-request, feature: language l10n and translations

#47370 fix(files): Move loading icon before grid toggle
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, design, 3. to review, backport-request, feature: files

#46991 fix(ProvisioningAPI): set typed config values by via API
  apps/provisioning_api/lib/Controller/AppConfigController.php
  apps/provisioning_api/tests/Controller/AppConfigControllerTest.php
Labels: bug, 3. to review

#47388 ci: Skip flaky test on PHP 8.3
  tests/lib/Files/ObjectStore/S3Test.php
Labels: 3. to review

#47259 feat: add negative compare-and-delete to imemcache
  lib/private/Memcache/CADTrait.php
  lib/private/Memcache/LoggerWrapperCache.php
  lib/private/Memcache/NullCache.php
  lib/private/Memcache/ProfilerWrapperCache.php
  lib/private/Memcache/Redis.php
  lib/public/IMemcache.php
  tests/lib/Memcache/Cache.php
Labels: 3. to review, backport-request

#47363 fix: use empty template by default when pressing enter
  apps/files/src/components/TemplatePreview.vue
  apps/files/src/views/TemplatePicker.vue
  dist/6113-6113.js
  dist/6113-6113.js.license
  dist/6113-6113.js.map
  dist/6113-6113.js.map.license
  dist/7493-7493.js
  dist/7493-7493.js.map
  dist/7493-7493.js.map.license
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 4. to release, backport-request, javascript

#47409 fix(provisioning): Support setting new app configs as well
  apps/provisioning_api/lib/Controller/AppConfigController.php
  apps/provisioning_api/tests/Controller/AppConfigControllerTest.php
Labels: bug, 3. to review, regression

#47413 fix(caldav): limit property length
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, backport-request

#47379 fix(cypress): improve cypress performances
  .github/workflows/cypress.yml
  cypress/dockerNode.ts
  cypress/e2e/settings/personal-info.cy.ts
  cypress/support/commands.ts
Labels: 3. to review, performance 🚀, developer experience

#47415 fix: Trusted server icon recovery without addressbook change
  apps/federation/lib/BackgroundJob/GetSharedSecret.php
  apps/federation/lib/BackgroundJob/RequestSharedSecret.php
  apps/federation/lib/SyncFederationAddressBooks.php
  apps/federation/tests/SyncFederationAddressbooksTest.php
Labels: backport-request

#47408 fix(dashboard): Adjust widget border radius
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: bug, design, 3. to review, backport-request, regression, feature: dashboard

#47407 fix(files_versions): Migrate version name dialog from NcModal to NcDialog
  apps/files_versions/src/components/VersionLabelDialog.vue
  apps/files_versions/src/components/VersionLabelForm.vue
  apps/files_versions/src/views/VersionTab.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.license
  dist/files_versions-files_versions.js.map
Labels: bug, design, 3. to review, backport-request, feature: versions

#47419 fix(migration): Add missing migration attributes
  core/Migrations/Version30000Date20240815080800.php
Labels: 3. to review, backport-request

#47403 feat(Security): Allow defining a password context for password validation and generation
  apps/files_sharing/lib/Controller/ShareController.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Security/Events/GenerateSecurePasswordEvent.php
  lib/public/Security/Events/ValidatePasswordPolicyEvent.php
  lib/public/Security/PasswordContext.php
  tests/lib/Security/Events/GenerateSecurePasswordEventTest.php
  tests/lib/Security/Events/ValidatePasswordPolicyEventTest.php
Labels: enhancement, 3. to review, pending documentation

#47204 fix(files): Respect "Show hidden files" setting in tree
  apps/files/src/services/FolderTree.ts
  apps/files/src/views/folderTree.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review, backport-request, feature: files
