Repository nextcloud/server, pull requests merged in 2024-06, with the labels that each got.

#45494 fix(core): unsupported browser redirect url
  core/Controller/UnsupportedBrowserController.php
  core/src/views/UnsupportedBrowser.vue
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
Labels: bug, 4. to release

#45623 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies

#45235 fix(caldav): automatically delete outdated scheduling objects
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/BackgroundJob/DeleteOutdatedSchedulingObjects.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/Migration/DeleteSchedulingObjects.php
  apps/dav/lib/Migration/Version1004Date20170825134824.php
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/SetupChecks/SchedulingTableSize.php
  core/Application.php
  lib/private/Repair.php
Labels: 3. to review, backport-request, performance 🚀, feature: caldav

#45632 fix(core): Add missing null value possibility to Resource and Reference richObject
  core/ResponseDefinitions.php
  core/openapi.json
Labels: bug, 3. to review, backport-request

#45455 fix(INavigationManager): Fix psalm alias not set in the right place
  core/ResponseDefinitions.php
  core/openapi.json
  lib/private/NavigationManager.php
  lib/public/INavigationManager.php
Labels: 3. to review, backport-request, technical debt

#45629 feat(db): remove workaround for pqsql 9.4 and older
  lib/private/DB/AdapterPgSql.php
Labels: 4. to release, technical debt

#44897 fix(files): Close sidebar and update fileid when current node is deleted
  apps/files/src/actions/deleteAction.ts
  apps/files/src/store/paths.ts
  apps/files/src/views/FilesList.vue
  apps/files/src/views/Sidebar.vue
  cypress/e2e/files/files-sidebar.cy.ts
  cypress/support/commands.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 4. to release, backport-request, feature: files

#45570 fix(Mailer): Allow to enforce strict email format
  lib/private/Mail/Mailer.php
  tests/lib/Mail/MailerTest.php
  tests/lib/UtilTest.php
Labels: bug, 3. to review

#45586 fix(files): Only execute default action if there is an action to perform
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files

#40133 Refactor `OC\Server::getEncryptionKeyStorage`
  lib/private/Encryption/EncryptionWrapper.php
Labels: 3. to review, technical debt

#45581 fix(files): reset menu pos when opening in grid mode
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files, papercut

#40122 Refactor `OC\Server::getEncryptionFilesHelper`
  lib/private/Encryption/EncryptionWrapper.php
  lib/private/Encryption/HookManager.php
Labels: 4. to release, technical debt

#45664 [stable27] fix(dialogs): Make sure conflict dialog is loaded before adding conflicts
  core/src/OC/dialogs.js
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, feature: files, 27-feedback

#45687 29.0.2
  version.php
Labels: 3. to review

#45679 fix(files_sharing): usage of NcTextField in SelectShareFolderDialogue
  apps/files_sharing/src/components/SelectShareFolderDialogue.vue
  dist/files_sharing-personal-settings.js
  dist/files_sharing-personal-settings.js.map
Labels: bug, 3. to review, feature: sharing, backport-request, javascript

#45424 feat(RichObjectStrings): Add missing Talk 'file' metadata fields
  lib/public/RichObjectStrings/Definitions.php
Labels: enhancement, 3. to review

#45347 fix: Only list remnants as disabled if option is enabled
  apps/user_ldap/lib/User_Proxy.php
Labels: 3. to review, feature: ldap

#45352 fix(login): Disable login button when already logging in
  core/src/components/login/LoginButton.vue
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, 4. to release, feature: authentication

#45686 feat(settings): Add user row action enabled callback
  apps/settings/src/components/Users/UserRowActions.vue
  apps/settings/src/views/UserManagement.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, 3. to review, feature: users and groups

#45684 feat(settings): Support svg user row action icons
  apps/settings/src/components/Users/UserRowActions.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
  package-lock.json
  package.json
Labels: enhancement, 3. to review, feature: users and groups

#43942 fix(Session): avoid password confirmation on SSO
  apps/settings/lib/Controller/AuthSettingsController.php
  apps/settings/tests/Controller/AuthSettingsControllerTest.php
  apps/settings/tests/Settings/Personal/Security/AuthtokensTest.php
  core/Controller/OCJSController.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php
  lib/private/Authentication/Token/PublicKeyToken.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/Lockdown/LockdownManager.php
  lib/private/Template/JSConfigHelper.php
  lib/private/TemplateLayout.php
  lib/private/legacy/OC_User.php
  lib/public/Authentication/Token/IToken.php
  tests/lib/AppFramework/Middleware/Security/Mock/PasswordConfirmationMiddlewareController.php
  tests/lib/AppFramework/Middleware/Security/PasswordConfirmationMiddlewareTest.php
  tests/lib/Authentication/Token/PublicKeyTokenTest.php
  tests/lib/Lockdown/Filesystem/NoFSTest.php
  tests/lib/Lockdown/LockdownManagerTest.php
Labels: bug, 3. to review, backport-request, feature: authentication

#45706 Updated images for Material icons and added SPDX info
  .reuse/dep5
  LICENSES/CC-BY-SA-3.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/LicenseRef-CollaboraTrademarks.txt
  core/img/apps/notes.svg
  core/img/apps/richdocuments.svg
  core/img/caldav/attendees.png
  core/img/caldav/attendees.svg
  core/img/caldav/description.png
  core/img/caldav/description.svg
  core/img/caldav/link.png
  core/img/caldav/link.svg
  core/img/caldav/location.png
  core/img/caldav/location.svg
  core/img/caldav/organizer.png
  core/img/caldav/organizer.svg
  core/img/caldav/time.png
  core/img/caldav/time.svg
  core/img/caldav/title.png
  core/img/caldav/title.svg
  core/img/categories/auth.svg
  core/img/categories/bundles.svg
  core/img/categories/customization.svg
  core/img/categories/files.svg
  core/img/categories/games.svg
  core/img/categories/integration.svg
  core/img/categories/monitoring.svg
  core/img/categories/multimedia.svg
  core/img/categories/office.svg
  core/img/categories/organization.svg
  core/img/categories/social.svg
  core/img/categories/workflow.svg
  core/img/clients/desktop.svg
  core/img/clients/phone.svg
  core/img/clients/tablet.svg
  core/img/facebook.svg
  core/img/mail.svg
  core/img/places/calendar-dark.png
  core/img/places/calendar.png
  core/img/places/calendar.svg
  core/img/places/contacts-dark.png
  core/img/places/contacts.svg
  core/img/places/default-app-icon.svg
  core/img/places/files.svg
  core/img/places/home.svg
  core/img/places/link.svg
  core/img/places/music.svg
  core/img/places/picture.svg
  core/img/rss.svg
  core/img/twitter.svg
Labels: design, 4. to release, technical debt

#45712 fix(dist): Make sure changed icons are compiled
  .github/workflows/node.yml
  dist/icons.css
Labels: bug, 3. to review, regression

#45711 fix(files): Correctly type virtual files list ref type
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#45710 fix(actions): Harden workflows when using variables in strings
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-outdated-3rdparty.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-pull-3rdparty.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/files-external-s3.yml
  .github/workflows/files-external-sftp.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-cacert-bundle.yml
  .github/workflows/update-code-signing-crl.yml
  .github/workflows/update-psalm-baseline.yml
Labels: 4. to release

#45619 ci: Migrate Litmus and CalDAVTester from drone to GitHub
  .drone.yml
  .github/workflows/integration-dav.yml
  .github/workflows/integration-litmus.yml
  build/files-checker.php
Labels: 3. to review, backport-request, CI

#45611 fix(files): Make sure files are opened when using `open-in-files` action(s) or at lease are scrolled into view
  apps/files/src/actions/openInFilesAction.spec.ts
  apps/files/src/actions/openInFilesAction.ts
  apps/files/src/actions/sidebarAction.ts
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/components/FileEntryMixin.ts
  apps/files/src/components/VirtualList.vue
  apps/files_sharing/src/actions/openInFilesAction.spec.ts
  apps/files_sharing/src/actions/openInFilesAction.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 4. to release, backport-request, feature: files

#45735 [stable28] ci(eol): update workflow from template
  .github/workflows/block-merge-eol.yml
Labels: 3. to review, CI

#45120 fix(dav): Don't log access control as error
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
Labels: bug, 3. to review, feature: dav

#44967 perf(files_sharing): Move events to listener classes and registration instead of boot
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Listener/BeforeDirectFileDownloadListener.php
  apps/files_sharing/lib/Listener/BeforeZipCreatedListener.php
  apps/files_sharing/tests/ApplicationTest.php
Labels: 3. to review, performance 🚀

#45734 [stable29] ci(eol): update workflow from template
  .github/workflows/block-merge-eol.yml
Labels: 3. to review, CI

#45737 fix(AppManager): Name correct method in error + show error string
  lib/private/App/AppManager.php
Labels: 3. to review, feature: apps management

#45736 [stable27] ci(eol): update workflow from template
  .github/workflows/block-merge-eol.yml
Labels: 3. to review, CI

#45765 fix(settings): Use axios directly for health check to preven URL sanitizing
  apps/settings/src/store/apps.js
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: backport-request

#45669 fix: Autodetect legacy filekey instead of trusting the header for legacy header
  apps/encryption/lib/Crypto/Encryption.php
  apps/encryption/lib/KeyManager.php
  apps/encryption/tests/Crypto/EncryptionTest.php
Labels: 3. to review, feature: encryption (server-side), backport-request

#45779 fix(CI): Update PHP requirement in dev dependencies
  .github/workflows/openapi.yml
  composer.lock
  lib/private/AppFramework/ScopedPsrLogger.php
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: bug, 3. to review

#45781 fix(search): tags redirect route
  apps/systemtags/lib/Search/TagSearchProvider.php
Labels: bug, 3. to review, backport-request, feature: files, feature: tags, regression

#45719 [stable28] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#45475 feat: Add support for webhook listeners
  .gitignore
  apps/dav/composer/composer/autoload_static.php
  apps/webhook_listeners/appinfo/info.xml
  apps/webhook_listeners/composer/autoload.php
  apps/webhook_listeners/composer/composer.json
  apps/webhook_listeners/composer/composer.lock
  apps/webhook_listeners/composer/composer/ClassLoader.php
  apps/webhook_listeners/composer/composer/InstalledVersions.php
  apps/webhook_listeners/composer/composer/LICENSE
  apps/webhook_listeners/composer/composer/autoload_classmap.php
  apps/webhook_listeners/composer/composer/autoload_namespaces.php
  apps/webhook_listeners/composer/composer/autoload_psr4.php
  apps/webhook_listeners/composer/composer/autoload_real.php
  apps/webhook_listeners/composer/composer/autoload_static.php
  apps/webhook_listeners/composer/composer/installed.json
  apps/webhook_listeners/composer/composer/installed.php
  apps/webhook_listeners/img/app-dark.svg
  apps/webhook_listeners/img/app.svg
  apps/webhook_listeners/lib/AppInfo/Application.php
  apps/webhook_listeners/lib/BackgroundJobs/WebhookCall.php
  apps/webhook_listeners/lib/Command/ListWebhooks.php
  apps/webhook_listeners/lib/Controller/WebhooksController.php
  apps/webhook_listeners/lib/Db/AuthMethod.php
  apps/webhook_listeners/lib/Db/WebhookListener.php
  apps/webhook_listeners/lib/Db/WebhookListenerMapper.php
  apps/webhook_listeners/lib/Listener/WebhooksEventListener.php
  apps/webhook_listeners/lib/Migration/Version1000Date20240527153425.php
  apps/webhook_listeners/lib/ResponseDefinitions.php
  apps/webhook_listeners/lib/Service/PHPMongoQuery.php
  apps/webhook_listeners/lib/Settings/Admin.php
  apps/webhook_listeners/openapi.json
  apps/webhook_listeners/tests/Db/WebhookListenerMapperTest.php
  apps/webhook_listeners/tests/Service/PHPMongoQueryTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_psr4.php
  lib/composer/composer/autoload_static.php
  lib/public/EventDispatcher/IWebhookCompatibleEvent.php
  lib/public/EventDispatcher/JsonSerializer.php
  lib/public/Files/Events/Node/AbstractNodeEvent.php
  lib/public/Files/Events/Node/AbstractNodesEvent.php
  psalm.xml
  tests/enable_all.php
Labels: 2. developing

#45749 Manual/backport/44910/stable27
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: feature: sharing

#43776 [stable27] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#45775 fix(caldav): event links in shared calendar notifications
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/lib/CalDAV/Activity/Provider/Todo.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/EventTest.php
Labels: bug, 4. to release, backport-request, feature: activity and notification, feature: caldav

#45794 chore(composer): composer install --no-dev
  lib/composer/composer/autoload_psr4.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/installed.json
  lib/composer/composer/installed.php
Labels: 3. to review

#45780 [stable24] fix: delete user credentials stored in storages_credentials when user gets deleted
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Server.php
  lib/private/User/Listeners/BeforeUserDeletedListener.php
Labels: 3. to review

#45764 [stable29] fix(files): handling numbered type owner name & id
  apps/files/src/services/Files.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/systemtags-init.js
  dist/systemtags-init.js.map
Labels: bug, 4. to release, backport-request

#45789 fix(files): Use `data-cy` (data attribute) instead of `cy-data`
  apps/files/src/views/Sidebar.vue
  cypress/e2e/files/FilesUtils.ts
  cypress/e2e/files/files-sidebar.cy.ts
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review, feature: files

#45768 Use isRetryable to catch retryable exceptions
  lib/private/Files/Cache/Cache.php
Labels: bug, 3. to review, backport-request, feature: files, php

#45804 fix(cron): Log long running jobs
  cron.php
Labels: bug, 3. to review

#45698 fix(files_sharing): fix parsing of remote shares
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
  apps/files/src/actions/moveOrCopyActionUtils.ts
  apps/files/src/components/FileEntry.vue
  apps/files_sharing/src/actions/sharingStatusAction.ts
  apps/files_sharing/src/services/SharingService.spec.ts
  apps/files_sharing/src/services/SharingService.ts
  core/Controller/AvatarController.php
  core/Controller/GuestAvatarController.php
  core/openapi.json
  dist/857-857.js
  dist/857-857.js.map
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.license
  dist/files_sharing-init.js.map
  lib/private/Share20/Manager.php
  tests/Core/Controller/AvatarControllerTest.php
Labels: bug, 2. developing, feature: sharing, feature: files

#45811 test: add tests for ProfilePageController
  core/Controller/ProfilePageController.php
  tests/Core/Controller/ProfilePageControllerTest.php
Labels: 3. to review, technical debt

#45571 fix(files): also trigger new tab on file name middle click
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntry/FileEntryName.vue
  apps/files/src/components/FileEntryGrid.vue
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, papercut, regression

#45809 [stable29] fix(Token): make new scope future compatible
  lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php
  lib/private/Template/JSConfigHelper.php
  lib/private/legacy/OC_User.php
  tests/lib/AppFramework/Middleware/Security/PasswordConfirmationMiddlewareTest.php
Labels: bug, 3. to review

#45828 fix(ShareEntryLinkedList): Correctly propagate share data
  apps/files_sharing/src/views/SharingLinkList.vue
  core/css/server.css
  core/css/server.css.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: feature: sharing

#45251 fix(files): do not rely on unique fileid
  apps/files/src/components/BreadCrumbs.vue
  apps/files/src/components/FileEntry/FileEntryCheckbox.vue
  apps/files/src/components/FileEntryMixin.ts
  apps/files/src/components/FilesListTableHeader.vue
  apps/files/src/components/FilesListTableHeaderActions.vue
  apps/files/src/store/dragging.ts
  apps/files/src/store/files.ts
  apps/files/src/store/paths.ts
  apps/files/src/store/selection.ts
  apps/files/src/types.ts
  apps/files/src/utils/hashUtils.ts
  apps/files/src/views/FilesList.vue
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, technical debt

#45649 fix(ObjectStore): Fix regression when hostname is empty
  lib/private/Files/ObjectStore/S3ConnectionTrait.php
Labels: bug, 4. to release, backport-request, feature: object storage

#45530 fix(cron): Log excess memory usage at debug and info levels
  cron.php
Labels: bug, 4. to release, backport-request, feature: logging, feedback-requested

#43531 get child ids for folder in a separate query during move
  lib/private/Files/Cache/Cache.php
Labels: bug, 3. to review, backport-request

#45172 feat: add option to disable scanner transactions
  lib/private/Files/Cache/Scanner.php
Labels: 3. to review

#45810 Add SPDX header - batch 16
  .reuse/dep5
  LICENSES/CC-BY-SA-2.0.txt
  LICENSES/LicenseRef-freepikLicense.txt
  apps/files_sharing/lib/Listener/BeforeDirectFileDownloadListener.php
  apps/files_sharing/lib/Listener/BeforeZipCreatedListener.php
  apps/settings/tests/UserMigration/assets/account-complex.jpg
  apps/settings/tests/UserMigration/assets/account.png
  apps/webhook_listeners/appinfo/info.xml
  apps/webhook_listeners/img/app-dark.svg
  apps/webhook_listeners/img/app.svg
  apps/webhook_listeners/openapi.json.license
  core/img/breadcrumb.svg
  core/img/desktopapp.svg
  core/img/manifest.json.license
Labels: 4. to release, technical debt

#45681 [27] feat: add option to disable scanner transactions
  lib/private/Files/Cache/Scanner.php
Labels: 3. to review

#45867 fix(comments): Use proper icon components instead of icon classes to fix dark mode
  apps/comments/src/components/Comment.vue
  apps/comments/src/views/ActivityCommentEntry.vue
  dist/3920-3920.js
  dist/3920-3920.js.map
  dist/7462-7462.js
  dist/7462-7462.js.map
  dist/7888-7888.js
  dist/7888-7888.js.map
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
  dist/comments-comments-tab.js
  dist/comments-comments-tab.js.map
Labels: bug, 4. to release, backport-request, feature: comments

#45819 Feat: reduce border radius element to 8 px
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: design, 3. to review

#45818 Feat: add new clickable area variables
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: design, 3. to review

#45861 fix(files): Ignore right click for default action
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, javascript

#45024 [stable28] fix(files_sharing): Add one string for every share type + fix(sharingDetails): Show correct share target
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/5552-5552.js
  dist/5552-5552.js.LICENSE.txt
  dist/5552-5552.js.map
  dist/6797-6797.js
  dist/6797-6797.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request, 28-feedback

#45795 29.0.3 RC1
  version.php
Labels: 3. to review

#45796 28.0.7 RC1
  version.php
Labels: 3. to review

#45872 fix(git): Ignore the updater/ directory from diffs
  .gitignore
Labels: 3. to review, technical debt

#45883 tests(settings): Fix AccountMigratorTest when using PNG avatars
  apps/settings/tests/UserMigration/assets/account.png
Labels: bug, 4. to release, regression, tests

#45797 27.1.11 RC1
  version.php
Labels: 3. to review

#45893 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#45875 fix(theming): also apply enforced theme for guests
  apps/theming/lib/Service/ThemesService.php
  apps/theming/tests/Service/ThemesServiceTest.php
Labels: 3. to review, backport-request, feature: theming, technical debt

#45884 fix(files): Properly handle denied ownership transfers
  apps/files/lib/Controller/TransferOwnershipController.php
  apps/files/lib/Notification/Notifier.php
Labels: bug, 3. to review, backport-request, feature: files

#45902 fix(deleteAction): Bump up delete requests concurrency to 5
  apps/files/src/actions/deleteAction.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: backport-request, performance 🚀

#45901 [master] Update psalm-baseline.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#45900 fix(files_versions): Use `NcDateTime` for proper translated version dates
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review, backport-request, feature: versions, javascript

#45908 [stable27] fix(deleteAction): Bump up delete requests concurrency to 5
  apps/files/src/actions/deleteAction.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, performance 🚀

#45582 delete background jobs by id when cleaning up
  lib/private/BackgroundJob/JobList.php
  lib/public/BackgroundJob/IJobList.php
  lib/public/BackgroundJob/QueuedJob.php
  tests/lib/BackgroundJob/DummyJobList.php
Labels: 3. to review

#45917 fix: Adjust icon generation to bring back themed icons
  core/src/icons.js
  dist/icons.css
Labels: bug, 3. to review, regression

#45913 29.0.3 RC2
  version.php
Labels: 3. to review

#45933 [stable28] fix(files): correctly import WebDAV client in files store
  apps/files/src/store/files.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files, regression

#45914 28.0.7 RC2
  version.php
Labels: 3. to review

#33581 use LazyUser in DefaultShareProvider
  lib/private/Share20/DefaultShareProvider.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 2. developing, performance 🚀

#45916 Align app icon for versions with right sidebar used icon
  apps/files_versions/img/app-dark.svg
  apps/files_versions/img/app.svg
Labels: 3. to review

#45866 fix(preview): don't create folder structure when previews are disabled
  lib/private/PreviewManager.php
Labels: bug, 4. to release

#45894 test(cypress): don't apply changes in CI
  cypress.config.ts
Labels: 3. to review, performance 🚀, tests, CI

#45889 fix(cypress): Check for local changes before trying to apply them
  cypress/dockerNode.ts
Labels: 3. to review, CI

#45945 perf: Avoid reusing previous migration steps
  lib/private/Repair.php
  lib/private/legacy/OC_App.php
Labels: 3. to review, performance 🚀

#45228 fix(settings): define a 'heartbeat' route, so SecurityHeaders can handle redirected root
  core/routes.php
  tests/lib/Route/RouterTest.php
Labels: bug, 3. to review, backport-request, feature: settings, feedback-requested

#45830 [stable25] test: add tests for ProfilePageController
  core/Controller/ProfilePageController.php
  tests/Core/Controller/ProfilePageControllerTest.php
Labels: 4. to release, technical debt

#45812 [stable26] fix(Session): avoid password confirmation on SSO
  core/Controller/OCJSController.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/Template/JSConfigHelper.php
  lib/private/TemplateLayout.php
  lib/private/legacy/OC_User.php
  tests/lib/AppFramework/Middleware/Security/Mock/PasswordConfirmationMiddlewareController.php
  tests/lib/AppFramework/Middleware/Security/PasswordConfirmationMiddlewareTest.php
Labels: bug, 4. to release

#45685 feat(settings): Emit loaded event for user management
  apps/settings/src/views/UserManagement.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, 3. to review, feature: users and groups

#45957 perf: Tell browsers to cache storage stats endpoint as it is cached
  apps/files/lib/Controller/ApiController.php
Labels: 3. to review, performance 🚀

#45930 fix: move repair mimetype repair step to the expensive steps
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/SetupChecks/MimeTypeMigrationAvailable.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Migration/NullOutput.php
  lib/private/Repair.php
  lib/private/Repair/RepairMimeTypes.php
  tests/lib/Repair/RepairMimeTypesTest.php
Labels: 3. to review, backport-request, pending documentation

#45963 Rename openFileInfo to fileInfo
  apps/files/lib/Controller/ViewController.php
  apps/files/src/components/FilesListVirtual.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files, regression

#45968 fix(dav): Limit number of UPDATES for sync token created_at
  apps/dav/lib/Migration/Version1025Date20240308063933.php
Labels: bug, 3. to review, feature: dav, backport-request, feature: install and update, feature: caldav, feature: carddav

#45972 Update copy icon to Material Design icon and checkmark in non-bold
  apps/files_sharing/src/components/SharingEntryInternal.vue
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/5733-5733.js
  dist/5733-5733.js.license
  dist/5733-5733.js.map
  dist/5733-5733.js.map.license
  dist/8821-8821.js
  dist/8821-8821.js.map
  dist/8821-8821.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review

#45845 fix: rename split into two as before rename and after rename
  apps/admin_audit/lib/Actions/Files.php
  apps/admin_audit/lib/AppInfo/Application.php
Labels: 3. to review

#45958 fix(files_versions): renaming file version when its not a string
  apps/files_versions/src/utils/versions.ts
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review

#45980 fix(theming): properly apply warning style to update output
  apps/theming/lib/Command/UpdateConfig.php
Labels: bug, 3. to review

#45688 Show non writable folders during move or copy
  apps/files/src/actions/moveOrCopyAction.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, javascript

#45207 fix(dav): Try basic auth for ajax WebDAV requests
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/tests/unit/Connector/Sabre/AuthTest.php
Labels: bug, 3. to review, feature: dav, feedback-requested

#46003 Add missing ContextWrite default task type in task processing manager
  lib/private/TaskProcessing/Manager.php
Labels: bug, 3. to review, feature: text processing

#46005 27.1.11 RC3
  version.php
Labels: 3. to review

#46006 28.0.7 RC3
  version.php
Labels: 3. to review

#46008 29.0.3 RC3
  version.php
Labels: 3. to review

#45999 fix(caldav): encode calendar URIs with umlauts for activities
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/dav/tests/unit/CalDAV/Activity/Provider/EventTest.php
Labels: bug, 4. to release, backport-request, feature: activity and notification, feature: caldav

#45984 Don't trigger action when renaming
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, javascript

#39825 Increase debounce delay when saving account properties
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/shared/AccountPropertySection.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 4. to release, technical debt

#45514 fix: use different file name for generated dark avatars
  lib/private/Avatar/UserAvatar.php
Labels: bug, 3. to review

#46017 fix: also use optimized getFirstNodeyIdInPath for Folder::getFirstNodeById
  lib/private/Files/Node/Folder.php
Labels: 3. to review, performance 🚀

#46032 29.0.3 RC4
  version.php
Labels: 3. to review

#46033 28.0.7 RC4
  version.php
Labels: 3. to review

#45973 chore: remove chunking-v1
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/lib/Connector/Sabre/LockPlugin.php
  apps/dav/lib/Connector/Sabre/ObjectTree.php
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  apps/dav/tests/unit/Connector/Sabre/ObjectTreeTest.php
  apps/dav/tests/unit/Connector/Sabre/QuotaPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/RequestTest/UploadTest.php
  build/integration/dav_features/webdav-related.feature
  build/integration/features/bootstrap/ChecksumsContext.php
  build/integration/features/bootstrap/WebDav.php
  build/integration/federation_features/federated.feature
  build/integration/files_features/checksums.feature
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/legacy/OC_FileChunking.php
  tests/lib/FileChunkingTest.php
Labels: 3. to review

#46048 [master] Update psalm-baseline.xml
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
Labels: 3. to review, automated pr

#45938 fix: Do not log an error when connecting to SFTP without a logged in user
  apps/files_external/lib/Lib/Storage/SFTP.php
Labels: bug, 3. to review, feature: external storage, backport-request

#45877 fix: don't use custom certificate bundle if no customer certificates are configured
  lib/private/Security/CertificateManager.php
Labels: 3. to review, backport-request

#46062 feat(CI): Speed up cs:check with parallelism
  .php-cs-fixer.dist.php
Labels: 3. to review, technical debt, standardisation

#45860 fix(files): Bring back handling of failed files
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/components/FileEntry/FileEntryName.vue
  apps/files/src/components/FileEntryGrid.vue
  apps/files/src/components/FileEntryMixin.ts
  apps/files/src/utils/hashUtils.ts
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#45876 fix: Avoid throwing errors for teams are unavailable
  lib/private/Teams/TeamManager.php
Labels: bug, 3. to review

#44931 Better wordings in the new user modal
  apps/settings/src/components/Users/NewUserDialog.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: design, 3. to review, feature: users and groups

#46075 [stable29] fix(Token): add FILESYSTEM scope with SCOPE_SKIP_PASSWORD_VALIDATION
  lib/private/legacy/OC_User.php
Labels: bug, 3. to review, backport-request

#46073 fix: allows admin to edit global credentials
  apps/files_external/lib/Controller/AjaxController.php
Labels: bug, backport-request, php

#46079 fix(settings): make trailing slash for caldav/carddav redirects optional
  apps/settings/lib/SetupChecks/WellKnownUrls.php
Labels: bug, 3. to review, backport-request, feature: settings, 29-feedback

#46077 fix(userstatus): Fix user status automation in real-life scenario
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
  apps/dav/tests/unit/BackgroundJob/UserStatusAutomationTest.php
  apps/user_status/lib/Service/StatusService.php
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
Labels: bug, 3. to review, feature: dav, backport-request, papercut, feature: status

#46063 29.0.3
  version.php
Labels: 3. to review

#46064 28.0.7
  version.php
Labels: 3. to review

#46065 27.1.11
  version.php
Labels: 3. to review

#46104 build(deps): disable dependabot for EOL 27
  .github/dependabot.yml
Labels: 4. to release, dependencies

#46095 feat(notifications): Migrate server INotifiers to new exceptions
  apps/comments/lib/Notification/Notifier.php
  apps/comments/tests/Unit/Notification/NotifierTest.php
  apps/dav/lib/CalDAV/Reminder/Notifier.php
  apps/dav/tests/unit/CalDAV/Reminder/NotifierTest.php
  apps/federatedfilesharing/lib/Notifier.php
  apps/files/lib/Notification/Notifier.php
  apps/files_reminders/lib/Notification/Notifier.php
  apps/files_sharing/lib/Notification/Notifier.php
  apps/twofactor_backupcodes/lib/Notifications/Notifier.php
  apps/updatenotification/lib/Notification/AppUpdateNotifier.php
  apps/updatenotification/lib/Notification/Notifier.php
  apps/user_ldap/lib/Notification/Notifier.php
  core/Notification/CoreNotifier.php
  lib/private/Authentication/Notifications/Notifier.php
Labels: 3. to review, feature: activity and notification, technical debt

#45532 feat: implement public OCP api to update resources and rooms
  apps/dav/lib/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJob.php
  apps/dav/tests/unit/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJobTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Calendar/Resource/Manager.php
  lib/private/Calendar/ResourcesRoomsUpdater.php
  lib/private/Calendar/Room/Manager.php
  lib/public/Calendar/Resource/IManager.php
  lib/public/Calendar/Room/IManager.php
  tests/lib/Calendar/Resource/ManagerTest.php
  tests/lib/Calendar/ResourcesRoomsUpdaterTest.php
  tests/lib/Calendar/Room/ManagerTest.php
Labels: enhancement, 3. to review, pending documentation, feature: caldav

#46002 Use guzzle for addressbook federation
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/tests/unit/CardDAV/SyncServiceTest.php
Labels: 3. to review, technical debt

#46127 feat(files): increase max copy-move concurrency to 5
  apps/files/src/actions/moveOrCopyActionUtils.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 4. to release, backport-request, feature: files, performance 🚀

#45977 Update favorites navigation list on folder renames
  apps/files/src/eventbus.d.ts
  apps/files/src/views/favorites.spec.ts
  apps/files/src/views/favorites.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review, feature: files, javascript

#46097 fix(files_sharing): Also set the expiration date timezone during validation
  apps/files_sharing/lib/Controller/ShareAPIController.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
Labels: bug, 3. to review, feature: sharing, backport-request, php

#44893 fix(caldav): When message is a reply compare the message sender not the recipient
  apps/dav/lib/CalDAV/Schedule/IMipService.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipServiceTest.php
Labels: bug, 3. to review, backport-request

#46036 fix(dav): add missing database index for dav_shares
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/Listener/AddMissingIndicesListener.php
  apps/dav/lib/Migration/Version1004Date20170825134824.php
Labels: 3. to review, feature: dav, backport-request, performance 🚀

#46143 fix(SharingEntryLink): Show enforced password input label
  apps/files_sharing/src/components/SharingEntryLink.vue
  dist/1345-1345.js
  dist/1345-1345.js.map
  dist/1345-1345.js.map.license
  dist/8913-8913.js
  dist/8913-8913.js.license
  dist/8913-8913.js.map
  dist/8913-8913.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request

#46154 [stable29] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46155 [stable28] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46158 [master] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46159 [stable27] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46153 [stable26] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46160 [stable25] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46156 [stable24] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46161 [stable23] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46157 [stable22] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#46059 perf(session): remove useless session open
  apps/files/lib/Controller/ViewController.php
Labels: enhancement, 3. to review, php, performance 🚀

#45655 feat(dbal): insert ignore conflict method for MySQL and SQLite
  lib/private/DB/AdapterMySQL.php
  lib/private/DB/AdapterSqlite.php
  tests/lib/DB/AdapterTest.php
Labels: 3. to review

#46164 [stable28] fix(openapi): Regenerate OpenAPI after server changes
  .github/workflows/openapi.yml
  core/openapi.json
Labels: 3. to review, backport-request
