Repository nextcloud/server, pull requests merged in 2024-01, with the labels that each got.

#42538 Fix log rotation notification level (warning->info)
  lib/private/Log/Rotate.php
Labels: bug, 3. to review, backport-request, feature: logging

#42548 [26] restore shared lock ttl to previous value when releasing
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/Memcache/LoggerWrapperCache.php
  lib/private/Memcache/ProfilerWrapperCache.php
  lib/private/Memcache/Redis.php
  lib/private/Server.php
  lib/public/IMemcacheTTL.php
  tests/lib/Lock/MemcacheLockingProviderTest.php
  tests/lib/Memcache/RedisTest.php
Labels: 3. to review

#42549 [27] restore shared lock ttl to previous value when releasing
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/Memcache/LoggerWrapperCache.php
  lib/private/Memcache/ProfilerWrapperCache.php
  lib/private/Memcache/Redis.php
  lib/private/Server.php
  lib/public/IMemcacheTTL.php
  tests/lib/Lock/MemcacheLockingProviderTest.php
  tests/lib/Memcache/RedisTest.php
Labels: 3. to review

#42443 fix(files): focus file name on renaming also initially
  apps/files/src/components/FileEntry/FileEntryName.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, accessibility, files2vue

#42553 [stable28] fix(files): focus file name on renaming also initially
  apps/files/src/components/FileEntry/FileEntryName.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, accessibility, files2vue

#42500 fix(files): open menu on right click position
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntry/FileEntryActions.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files, regression

#39174 refactor lib/private/Notification
  lib/private/Notification/Action.php
  lib/private/Notification/Manager.php
  lib/private/Notification/Notification.php
Labels: 3. to review, technical debt

#42570 enh(settings): removed background-gradient to ensure contrast ratio a11y requirements
  apps/settings/src/components/PersonalInfo/ProfileSection/ProfilePreviewCard.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: enhancement, 3. to review, backport-request, feature: settings, ux, accessibility

#42576 Fix upgrade of user_ldap when oc_group_members contains duplicated uids
  apps/user_ldap/lib/Migration/Version1190Date20230706134108.php
Labels: bug, 3. to review, feature: ldap, backport-request

#42578 initialize variables
  lib/private/Notification/Notification.php
Labels: 3. to review

#42513 enh(files): made breadcrumb component lang=ts
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 4. to release, feature: files, files2vue

#42586 Fix SVG's for social media links
  apps/settings/templates/settings/personal/development.notice.php
Labels: 3. to review, backport-request

#42559 Remove unneeded styles: everything is handled by NcVue
  core/css/server.css
  core/css/server.css.map
  core/css/styles.css
  core/css/styles.css.map
  core/css/styles.scss
Labels: 3. to review

#42507 Fix/files/42460/breadcrumb conditional rendering
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 3. to review, backport-request, feature: files, accessibility, files2vue

#42566 fix(files): Fix unresponsive file click to download
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntryGrid.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files, regression

#42428 fix(files_external): add back js config files
  apps/files_external/js/oauth1.js
  apps/files_external/js/oauth2.js
  apps/files_external/js/public_key.js
Labels: bug, 3. to review, feature: external storage, backport-request, regression

#42602 chore(package): bumped nc-calendar to 2.0.1
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
  package-lock.json
  package.json
Labels: 3. to review, backport-request, ux, accessibility

#42544 Fix Slow logout on Chrome-like browsers
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: bug, 3. to review

#42560 debug logs on huge metadata
  lib/private/FilesMetadata/FilesMetadataManager.php
Labels: 3. to review, backport-request

#42629 [stable28] chore(package): bumped nc-calendar to 2.0.1
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
  package-lock.json
  package.json
Labels: 3. to review, feature: install and update, feature: vue apps, feature: accessibility, ux, accessibility, files2vue

#42622 [stable28] enh(settings): removed background-gradient to ensure contrast ratio a…
  apps/settings/src/components/PersonalInfo/ProfileSection/ProfilePreviewCard.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: 3. to review, ux, accessibility

#42630 [stable28] fix(files): add visible label to webdav URL in settings
  apps/files/src/views/Settings.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, feature: files, accessibility

#41547 Migrate opcache check to new SetupCheck API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/PhpOpcacheSetup.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42632 [stable28] fix(files): kept only first and last breadcrumb titles
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, feature: files, feature: accessibility, ux, accessibility, files2vue

#42634 Include grid view toggle in accessibility switch
  apps/files/src/views/Settings.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, backport-request, javascript, accessibility

#42176 Migrate app dir owner check to new SetupCheck API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/AppDirsWithDifferentOwner.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  apps/settings/tests/SetupChecks/AppDirsWithDifferentOwnerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42643 fix(core): enhanced contrast when UserMenuItem is focused
  core/src/views/UserMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review, backport-request, ux, accessibility

#42633 Fix tests after slow logout fix
  tests/Core/Controller/LoginControllerTest.php
Labels: 3. to review, php, tests

#42636 enh(core): replaced previous native a element with NcButton
  core/src/components/Profile/PrimaryActionButton.vue
  dist/core-profile.js
  dist/core-profile.js.map
Labels: 3. to review, backport-request, feature: profile, accessibility

#42664 [stable28] fix(core): enhanced contrast when UserMenuItem is focused
  core/src/views/UserMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: 3. to review, accessibility

#42608 [stable27] fix(files): service worker
  apps/files/lib/Controller/ApiController.php
  apps/files/lib/Controller/ViewController.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: bug, 3. to review

#42666 chore(deps): Update openapi-extractor
  apps/files/openapi.json
  apps/files_sharing/openapi.json
  apps/files_trashbin/openapi.json
  apps/theming/openapi.json
  apps/user_ldap/openapi.json
  core/openapi.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request

#42532 fix(user_status): Allow setting custom message with icon only
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/tests/Unit/Controller/UserStatusControllerTest.php
Labels: bug, 3. to review

#42391 feat(cron): Warn on excessive memory consumption in background jobs
  cron.php
  lib/public/BackgroundJob/Job.php
Labels: enhancement, 3. to review, performance 🚀

#42563 Update crl after revoke integration_homeassistant.csr
  resources/codesigning/root.crl
Labels: 3. to review

#42488 fix(Update): Handle upstream exception scenario cleanly
  core/Command/App/Update.php
Labels: bug, 3. to review, backport-request, feature: apps management

#42590 Add settings section type attribute on settings app-content section
  apps/settings/lib/Controller/CommonSettingsTrait.php
  apps/settings/templates/settings/frame.php
Labels: bug, enhancement, 3. to review, feature: settings

#42377 Fix(text2image): Return providers as indexed array
  lib/private/TextToImage/Manager.php
  lib/public/TextToImage/IManager.php
Labels: backport-request

#42527 feat(user_status): Add online status type for OpenAPI
  apps/user_status/lib/Controller/StatusesController.php
  apps/user_status/lib/Controller/UserStatusController.php
  apps/user_status/lib/ResponseDefinitions.php
  apps/user_status/openapi.json
Labels: 3. to review, backport-request

#42558 use deletion time instead of mtime in trashbin handling
  apps/files_trashbin/lib/Sabre/TrashFile.php
  apps/files_trashbin/lib/Sabre/TrashFolder.php
Labels: 3. to review

#41972 fix(files): move actions for selected file out from table header
  apps/files/src/components/FilesListTableHeader.vue
  apps/files/src/components/FilesListTableHeaderActions.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/components/VirtualList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, accessibility, files2vue

#42690 fix(files): switched native input to NcButton
  apps/files/src/components/TransferOwnershipDialogue.vue
  dist/files-personal-settings.js
  dist/files-personal-settings.js.map
Labels: 3. to review, backport-request, accessibility

#42533 fix(weather_status): Fix forecast format in OpenAPI
  apps/weather_status/lib/ResponseDefinitions.php
  apps/weather_status/openapi.json
Labels: bug, 2. developing, backport-request

#42402 Remove display name ellipsis in user menu
  core/src/views/UserMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: design, 3. to review, backport-request, 28-feedback

#42651 [stable28] perf: Use more performant way to obtain and check the email as a login name with token login
  lib/private/AllConfig.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 3. to review, performance 🚀

#42652 [stable27] perf: Use more performant way to obtain and check the email as a login name with token login
  lib/private/AllConfig.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 3. to review, performance 🚀

#42653 [stable26] perf: Use more performant way to obtain and check the email as a login name with token login
  lib/private/AllConfig.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 3. to review, performance 🚀

#42654 [stable25] perf: Use more performant way to obtain and check the email as a login name with token login
  lib/private/AllConfig.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 3. to review, performance 🚀

#42679 fix(quota): automatically detect chunk quota with `OC-Total-Length` header
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
Labels: bug, 3. to review, feature: dav, technical debt

#42680 Improve view only error message
  apps/dav/lib/DAV/ViewOnlyPlugin.php
Labels: enhancement, 3. to review, feature: files, php

#42658 fix(systemreport): Mark more configs as sensitive
  lib/private/AppConfig.php
  lib/private/SystemConfig.php
Labels: bug, 3. to review, backport-request

#42705 fix(openapi): Make OpenAPI CI green again
  core/Controller/ProfilePageController.php
Labels: 3. to review

#42177 Migrate PHP imagick module check to new SetupCheck API
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  apps/theming/composer/composer/autoload_classmap.php
  apps/theming/composer/composer/autoload_static.php
  apps/theming/lib/AppInfo/Application.php
  apps/theming/lib/SetupChecks/PhpImagickModule.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42382 Refresh FileList on current folder update
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: 4. to release, backport-request, feature: files, technical debt

#42585 Add RichObject support for SetupCheck descriptions
  core/Command/SetupChecks.php
  core/js/setupchecks.js
  lib/public/SetupCheck/SetupResult.php
Labels: enhancement, 3. to review

#42655 [stable27] fix: Always apply fullscreen styling to sidebar
  apps/files/src/views/Sidebar.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review

#42713 fix(a11y): Aria-hide contacts menu icon images
  core/src/components/ContactsMenu/Contact.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 4. to release, backport-request, feature: contacts menu, accessibility

#42700 fix styling of development-notice
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
Labels: design, 3. to review, backport-request, accessibility

#42640 Always catch OCP versions of authentication exceptions
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/lib/Migration/SetTokenExpiration.php
  apps/settings/lib/Controller/AuthSettingsController.php
  apps/settings/lib/Settings/Personal/Security/Authtokens.php
  core/Controller/AppPasswordController.php
  core/Controller/ClientFlowLoginController.php
  core/Controller/ClientFlowLoginV2Controller.php
  core/Controller/WipeController.php
  core/Service/LoginFlowV2Service.php
  lib/private/Authentication/Events/AppPasswordCreatedEvent.php
  lib/private/Authentication/LoginCredentials/Store.php
  lib/private/Authentication/Token/IProvider.php
  lib/private/Authentication/Token/Manager.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/private/Authentication/Token/RemoteWipe.php
  lib/private/Authentication/TwoFactorAuth/Manager.php
  lib/private/Session/Internal.php
  lib/private/User/Session.php
Labels: 3. to review, backport-request

#42667 better users cycle
  core/BackgroundJobs/GenerateMetadataJob.php
Labels: bug, 3. to review, backport-request

#42712 fix header-elements being not shown correctly
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
  core/src/components/AppMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, design, 3. to review, backport-request, regression

#42718 Remove unneeded role="radiogroup" from "Predefined statuses"
  apps/user_status/src/components/PredefinedStatusesList.vue
  dist/user-status-modal-8299.js
  dist/user-status-modal-8299.js.map
  dist/user_status-menu.js
  dist/user_status-menu.js.map
Labels: 3. to review, backport-request

#42711 [stable28] fix(files): switched native input to NcButton
  apps/files/src/components/TransferOwnershipDialogue.vue
  dist/files-personal-settings.js
  dist/files-personal-settings.js.map
Labels: 3. to review, accessibility

#42716 fix(files): use `getSummaryFor` for better files summary translations
  apps/files/src/components/FilesListVirtual.vue
  dist/614-614.js
  dist/614-614.js.map
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: 4. to release, backport-request, technical debt, feature: language l10n and translations

#42719 [stable28] Refresh FileList on current folder update
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, feature: files, technical debt

#42723 fix(settings): set default or unlimited user quota
  apps/settings/src/components/Users/UserRow.vue
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 4. to release, backport-request, regression

#42598 fix(files): use backend error message if provided
  apps/files/src/views/FilesList.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files

#42345 feat: Track dirty table writes and long transactions
  lib/private/DB/Connection.php
Labels: enhancement, 3. to review, pending documentation, performance 🚀

#42676 enh(comments): Add visual labels for editor
  apps/comments/src/components/Comment.vue
  dist/6826-6826.js
  dist/6826-6826.js.map
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
  dist/comments-comments-tab.js
  dist/comments-comments-tab.js.map
Labels: 3. to review, accessibility

#41819 Regular db pings to reconnect after timed out connections
  lib/private/DB/Connection.php
Labels: enhancement, 3. to review

#42619 fix(dav): Fix user status "Undefined array key 0 at StatusService.php…
  apps/dav/lib/CalDAV/Status/StatusService.php
  apps/dav/tests/unit/CalDAV/Status/StatusServiceTest.php
Labels: 3. to review, feature: dav, backport-request, feature: status

#42660 fix(share): use user timezone to parse share expiration date
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/openapi.json
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: bug, 3. to review, backport-request

#42740 [26] actually throttle restore
  apps/files_trashbin/src/filelist.js
  dist/files_trashbin-files_trashbin.js
  dist/files_trashbin-files_trashbin.js.map
Labels: 3. to review

#42734 [stable28] fix(files): use getSummaryFor for better files summary translations
  apps/files/src/components/FilesListVirtual.vue
  dist/614-614.js
  dist/614-614.js.map
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: 3. to review, technical debt, feature: language l10n and translations

#42670 occ background-job:delete
  core/Command/Background/Delete.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: enhancement, 3. to review, feature: occ

#42768 (dashboard): Lower error to info log message
  lib/private/Dashboard/Manager.php
Labels: 3. to review, backport-request, feature: dashboard

#41290 [stable26] fix semaphore unguarding
  build/psalm-baseline.xml
  lib/private/Preview/Generator.php
Labels: bug, 3. to review

#42790 Fix AppDirsWithDifferentOwnerTest
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  apps/settings/tests/SetupChecks/AppDirsWithDifferentOwnerTest.php
Labels: 3. to review

#42775 [stable26] fix: handle exif metadata read errors gracefully
  lib/private/Metadata/Provider/ExifProvider.php
Labels: bug, 3. to review

#42781 Fix crash of login in case of duplicated group membership
  apps/user_ldap/lib/Group_Proxy.php
Labels: 3. to review

#42436 enh(settings): Add SetupCheck to ensure webserver correctly serves `.mjs` files
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/js/esm-test.mjs
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/SetupChecks/JavaScriptModules.php
Labels: enhancement, 3. to review, feature: settings

#42774 [stable27] fix: handle exif metadata read errors gracefully
  lib/private/Metadata/Provider/ExifProvider.php
Labels: bug, 3. to review

#42739 [stable28] fix(a11y): Aria-hide contacts menu icon images
  core/src/components/ContactsMenu/Contact.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, accessibility

#42727 fix(l10n): Add context note for table footers
  apps/files/src/components/FilesListTableFooter.vue
  apps/settings/src/components/Users/UserListFooter.vue
  dist/614-614.js
  dist/614-614.js.map
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 4. to release, backport-request, feature: language l10n and translations

#41312 Migrate code integrity to SetupCheck API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/CodeIntegrity.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  lib/private/RichObjectStrings/Validator.php
Labels: 4. to release

#41755 Lazy grouping within IAppConfig
  apps/provisioning_api/lib/Controller/AppConfigController.php
  apps/provisioning_api/tests/Controller/AppConfigControllerTest.php
  core/Command/Config/App/GetConfig.php
  core/Command/Config/App/SetConfig.php
  core/Command/Config/ListConfigs.php
  core/Command/Upgrade.php
  core/Migrations/Version29000Date20231126110901.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AllConfig.php
  lib/private/AppConfig.php
  lib/private/SystemConfig.php
  lib/private/legacy/OC_App.php
  lib/public/Exceptions/AppConfigException.php
  lib/public/Exceptions/AppConfigIncorrectTypeException.php
  lib/public/Exceptions/AppConfigTypeConflictException.php
  lib/public/Exceptions/AppConfigUnknownKeyException.php
  lib/public/IAppConfig.php
  lib/public/IConfig.php
  tests/Core/Command/Config/App/GetConfigTest.php
  tests/Core/Command/Config/App/SetConfigTest.php
  tests/lib/AppConfigTest.php
  tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
Labels: 3. to review, pending documentation, performance 🚀

#42796 Migrate overwrite.cli.url setup check to new API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/OverwriteCliUrl.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42742 Complete `<h1>` settings heading
  apps/theming/src/UserThemes.vue
  core/templates/layout.user.php
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
Labels: 3. to review, backport-request

#42437 fix(files): Fix reference picker not working
  apps/files/src/views/FileReferencePickerElement.vue
  dist/files-reference-files.js
  dist/files-reference-files.js.LICENSE.txt
  dist/files-reference-files.js.map
Labels: bug, 3. to review

#42720 use showError in TransferOwnershipDialogue
  apps/files/src/components/TransferOwnershipDialogue.vue
  dist/files-personal-settings.js
  dist/files-personal-settings.js.map
Labels: design, 3. to review, accessibility

#42802 Migrate cron setup checks to new API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/CronErrors.php
  apps/settings/lib/SetupChecks/CronInfo.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42795 [stable28] Migrate setup checks to new SetupCheck API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/AppDirsWithDifferentOwner.php
  apps/settings/lib/SetupChecks/DatabasePendingBigIntConversions.php
  apps/settings/lib/SetupChecks/PhpOpcacheSetup.php
  apps/settings/lib/SetupChecks/SupportedDatabase.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  apps/settings/tests/SetupChecks/AppDirsWithDifferentOwnerTest.php
  apps/settings/tests/SetupChecks/SupportedDatabaseTest.php
  apps/theming/composer/composer/autoload_classmap.php
  apps/theming/composer/composer/autoload_static.php
  apps/theming/lib/AppInfo/Application.php
  apps/theming/lib/SetupChecks/PhpImagickModule.php
  core/Command/Db/ConvertFilecacheBigInt.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42837 refactor(core): remove `sudo-login-form` layout
  core/templates/layout.user.php
Labels: 3. to review, technical debt

#42735 [stable28] fix(files_sharing): fix sharing status indicator side after component…
  apps/files_sharing/src/actions/sharingStatusAction.scss
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, 4. to release, feature: files

#42805 fix(userstatus): catch unique constraint violation
  apps/user_status/lib/Listener/UserLiveStatusListener.php
  apps/user_status/tests/Unit/Listener/UserLiveStatusListenerTest.php
Labels: bug, 4. to release, backport-request, feature: status, 28-feedback

#42834 chore(theming): fix warning of incorrect `NcCheckboxRadioSwitch` usage
  apps/theming/src/UserThemes.vue
  dist/theming-personal-theming.js
  dist/theming-personal-theming.js.map
Labels: 3. to review, feature: theming

#42744 fix(update-section): changed span to an interactive element
  apps/updatenotification/src/components/UpdateNotification.vue
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
Labels: enhancement, 4. to release, backport-request, accessibility

#42607 fix(session): Avoid useless authtoken DB queries for anonymous requests
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: bug, 3. to review, backport-request, feature: authentication, performance 🚀

#42853 fix(dav): ajax request check on public remote endpoints
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/appinfo/v2/publicremote.php
Labels: bug, 4. to release, feature: dav, regression, 28-feedback

#42864 [stable28] fix(manifest): Check if app exists instead of accessing null as an array
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/openapi.json
  apps/theming/tests/Controller/IconControllerTest.php
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: bug, 3. to review, feature: theming

#42862 fix(manifest): Check if app exists instead of accessing null as an array
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/openapi.json
  apps/theming/tests/Controller/IconControllerTest.php
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: bug, 3. to review, backport-request, feature: theming

#42807 Remove obsolete check of curl SSL version
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
Labels: 3. to review

#42865 [stable27] fix(manifest): Check if app exists instead of accessing null as an array
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/openapi.json
  apps/theming/tests/Controller/IconControllerTest.php
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: bug, 3. to review, feature: theming

#42866 [stable26] fix(manifest): Check if app exists instead of accessing null as an array
  apps/theming/lib/Controller/IconController.php
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/tests/Controller/IconControllerTest.php
  core/templates/layout.guest.php
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: bug, 3. to review, feature: theming

#42840 fix(files): prevent dragging previews and appear as an external files DnD
  apps/files/src/components/DragAndDropNotice.vue
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FilesListVirtual.vue
  dist/614-614.js
  dist/614-614.js.map
  dist/core-unsupported-browser.js
  dist/core-unsupported-browser.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, 28-feedback

#42887 fix(theming): Make sure `color-border-maxcontrast` fulfills 3:1 contrast
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkHighContrastTheme.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Themes/HighContrastTheme.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
Labels: bug, 3. to review, backport-request, accessibility

#42856 enh(a11y): improved contrast on user menu
  core/src/views/UserMenu.vue
  dist/core-main.js
  dist/core-main.js.map
Labels: enhancement, 4. to release, accessibility

#42860 Update ContactsStore: Avoid exceptions on empties
  lib/private/Contacts/ContactsMenu/ContactsStore.php
Labels: bug, 4. to release, backport-request, feature: contacts menu, feature: contacts

#42859 [stable28] fix(update-section): changed span to an interactive element
  apps/updatenotification/src/components/UpdateNotification.vue
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
Labels: enhancement, 3. to review, accessibility

#42697 [stable28] Fix/add settings section type attribute
  apps/settings/lib/Controller/CommonSettingsTrait.php
  apps/settings/templates/settings/frame.php
Labels: bug, 3. to review

#42847 exceptions on their own
  lib/private/AppConfig.php
Labels: bug, 3. to review, technical debt

#42850 fix(CalDAV): set acls for DeletedCalendarObjectsCollection
  apps/dav/lib/CalDAV/Trashbin/DeletedCalendarObjectsCollection.php
Labels: bug, 4. to release, backport-request

#42908 [stable26] fix(CalDAV): set acls for DeletedCalendarObjectsCollection
  apps/dav/lib/CalDAV/Trashbin/DeletedCalendarObjectsCollection.php
Labels: bug, 3. to review, feature: caldav

#42891 Improve path resolution in files_version hooks
  apps/files_versions/lib/Listener/FileEventsListener.php
Labels: bug, 3. to review, backport-request, php

#41067 Fix for previews not being generated sometimes
  lib/private/Preview/Watcher.php
Labels: bug, 3. to review, feature: previews and thumbnails

#42923 fix(build): Do not generated OpenAPI for non-shipped apps or apps without OpenAPI support
  apps/admin_audit/.noopenapi
  apps/contactsinteraction/.noopenapi
  apps/encryption/.noopenapi
  apps/lookup_server_connector/.noopenapi
  apps/systemtags/openapi.json
  apps/testing/.noopenapi
  apps/twofactor_backupcodes/.noopenapi
  apps/workflowengine/.noopenapi
  build/openapi-checker.sh
Labels: 3. to review, backport-request, technical debt

#42812 Migrate memcached PHP module setup check to new API
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/MemcacheConfigured.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42882 [stable28] fix(dav): ajax request check on public remote endpoints
  apps/dav/appinfo/v1/publicwebdav.php
Labels: bug, 3. to review, regression, 28-feedback

#42808 [stable26] fix(share): use user timezone to parse share expiration date
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
Labels: 3. to review

#42787 26.0.11 RC1
  version.php
Labels: 3. to review

#42788 27.1.6 RC1
  version.php
Labels: 3. to review

#42789 28.0.2 RC1
  version.php
Labels: 3. to review

#42814 Migrate set_time_limit setup check to new API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/PhpDisabledFunctions.php
  apps/settings/lib/SetupChecks/PhpModules.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review

#42922 fix(db): Remove very verbose dirty query logs
  lib/private/DB/Connection.php
Labels: bug, 4. to release

#42955 fix(a11y): Fix avatar menu icon color in dark mode
  core/css/apps.css
  core/css/apps.css.map
  core/css/apps.scss
  core/css/server.css
  core/css/server.css.map
Labels: bug, 3. to review, backport-request, feature: theming, regression, accessibility

#42974 fix(build): Fix OpenAPI diff on non-default specs
  build/openapi-checker.sh
Labels: bug, 3. to review

#42949 fix(files): Fix checkbox state semantics
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FileEntry/FileEntryCheckbox.vue
  apps/files/src/components/FileEntryGrid.vue
  apps/files/src/components/FilesListTableHeader.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files, accessibility

#42950 fix(files): fixed aria-desciption logic for last breadcrumb
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, accessibility

#42889 enh(files): Allow to copy files into same directory
  apps/files/src/actions/moveOrCopyAction.ts
  apps/files/src/init-templates.ts
  apps/files/src/init.ts
  apps/files/src/newMenu/newFolder.ts
  apps/files/src/types.ts
  apps/files/src/utils/fileUtils.ts
  cypress/e2e/files/files_copy-move.cy.ts
  dist/files-init.js
  dist/files-init.js.LICENSE.txt
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files_versions-files_versions.js.map
Labels: bug, 4. to release, backport-request, feature: files, regression

#41136 Update security policy to match new project-wide default one
  SECURITY.md
Labels: 3. to review, security

#42987 chore(cypress): add 3 more runners
  .github/workflows/cypress.yml
Labels: 3. to review

#42996 fix(weather_status): Fix location format for OpenAPI
  apps/weather_status/lib/Controller/WeatherStatusController.php
  apps/weather_status/lib/ResponseDefinitions.php
  apps/weather_status/lib/Service/WeatherStatusService.php
  apps/weather_status/openapi.json
Labels: bug, 3. to review, backport-request

#42971 fix(auth): Fix logging in with email and app password
  lib/private/User/Session.php
Labels: bug, 4. to release, backport-request, feature: authentication, regression

#42821 Remove disputed bz2 check
  apps/settings/lib/SetupChecks/PhpModules.php
Labels: 4. to release, backport-request

#42963 fix header inversion bug
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
Labels: bug, 4. to release, backport-request, regression

#42965 feat(CI): Automatically update the root.crl from the appstore
  .github/CODEOWNERS
  .github/workflows/update-code-signing-crl.yml
Labels: 3. to review

#43017 [master] Fix npm audit
  core/css/server.css
  core/css/server.css.map
Labels: 3. to review, dependencies

#42909 [stable25] fix(CalDAV): set acls for DeletedCalendarObjectsCollection
  apps/dav/lib/CalDAV/Trashbin/DeletedCalendarObjectsCollection.php
Labels: bug, 4. to release, feature: caldav

#42910 [stable24] fix(CalDAV): set acls for DeletedCalendarObjectsCollection
  apps/dav/lib/CalDAV/Trashbin/DeletedCalendarObjectsCollection.php
Labels: bug, 4. to release, feature: caldav

#42911 [stable23] fix(CalDAV): set acls for DeletedCalendarObjectsCollection
  apps/dav/lib/CalDAV/Trashbin/DeletedCalendarObjectsCollection.php
Labels: bug, 4. to release, feature: caldav

#43019 [stable26] Make OAuth2 authorization code expire
  apps/oauth2/appinfo/info.xml
  apps/oauth2/composer/composer/autoload_classmap.php
  apps/oauth2/composer/composer/autoload_static.php
  apps/oauth2/lib/BackgroundJob/CleanupExpiredAuthorizationCode.php
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/lib/Db/AccessToken.php
  apps/oauth2/lib/Db/AccessTokenMapper.php
  apps/oauth2/lib/Migration/Version011603Date20230620111039.php
  apps/oauth2/tests/Controller/OauthApiControllerTest.php
  core/Controller/ClientFlowLoginController.php
Labels: enhancement, 3. to review, feature: authentication

#43020 [stable27] Make OAuth2 authorization code expire
  apps/oauth2/appinfo/info.xml
  apps/oauth2/composer/composer/autoload_classmap.php
  apps/oauth2/composer/composer/autoload_static.php
  apps/oauth2/lib/BackgroundJob/CleanupExpiredAuthorizationCode.php
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/lib/Db/AccessToken.php
  apps/oauth2/lib/Db/AccessTokenMapper.php
  apps/oauth2/lib/Migration/Version011603Date20230620111039.php
  apps/oauth2/tests/Controller/OauthApiControllerTest.php
  apps/oauth2/tests/Db/AccessTokenMapperTest.php
  core/Controller/ClientFlowLoginController.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
Labels: enhancement, 3. to review, feature: authentication

#43022 26.0.11 RC2
  version.php
Labels: 3. to review

#42822 fix(settings): set viewBox on SVG icons
  apps/settings/img/settings.svg
  apps/settings/img/settings_apps.svg
  apps/settings/img/users-white.svg
  apps/settings/img/users.svg
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: settings

#43028 Correct values and attributes
  apps/settings/src/components/AdminSettingsSharingForm.vue
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
Labels: bug, 3. to review, backport-request, accessibility

#42890 fix(db): Fix replica password example config
  config/config.sample.php
Labels: bug, 4. to release

#42929 fix(db): Do not log transacted reads as dirty read
  lib/private/DB/Connection.php
Labels: bug, 4. to release

#43032 [stable28] fix(theming): Apply same logic on capabilities for primary color as done on themes
  apps/theming/lib/Capabilities.php
  apps/theming/tests/CapabilitiesTest.php
Labels: bug, 4. to release, feature: theming

#43045 fix(apps): Fix type information of app manager
  lib/private/App/AppManager.php
  lib/public/App/IAppManager.php
Labels: bug, 3. to review

#42829 Merge gmp and bcmath module checks with the existing PHP modules setupcheck
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/PhpModules.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: 3. to review
