Repository nextcloud/server, pull requests merged in 2024-03, with the labels that each got.

#43896 Do not create a new version for empty files
  apps/files_versions/lib/Listener/FileEventsListener.php
Labels: bug, 3. to review, feature: versions, php

#43665 feat: Restore unified search filtering in files view
  apps/files/src/legacy/filelistSearch.js
  apps/files/src/views/FilesList.vue
  core/src/views/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: 4. to release, feature: files, feature: search

#43057 feat(perf): add cache for authtoken lookup
  lib/private/Authentication/Token/PublicKeyTokenMapper.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  tests/lib/Authentication/Token/PublicKeyTokenMapperTest.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
Labels: enhancement, 3. to review, performance 🚀

#43841 [stable28] chore(deps): Bump calendar-availability-vue from 2.1.0 to 2.2.0
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#43962 in text: "bruteforce" > "brute force"
  config/config.sample.php
Labels: 3. to review, feature: language l10n and translations

#43959 fix(IUrlGenerator): Add `throws` documentation for `imagePath` function
  lib/public/IURLGenerator.php
Labels: bug, 3. to review, backport-request

#43972 fix: Fetch custom app store url without internet connection
  lib/private/App/AppStore/Fetcher/Fetcher.php
  tests/lib/App/AppStore/Fetcher/CategoryFetcherTest.php
  tests/lib/App/AppStore/Fetcher/FetcherBase.php
Labels: bug, 3. to review

#43791 Share api cleanup
  apps/files_sharing/tests/UpdaterTest.php
  lib/private/Files/View.php
  lib/private/Share/Share.php
  lib/public/Share.php
  tests/lib/Share/Backend.php
Labels: 3. to review

#43906 feat(settings): Migrate SSL access and URL generation check to SetupCheck API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/Controller/CheckSetupController.php
  apps/settings/lib/SetupChecks/HttpsUrlGeneration.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
Labels: enhancement, 3. to review, feature: settings

#43971 [stable27] Use table prefix in metadata migration
  core/BackgroundJobs/MetadataMigrationJob.php
  lib/private/Repair/AddMetadataMigrationJob.php
Labels: bug, 3. to review, php

#43898 Improve files version listing
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
Labels: bug, 3. to review, feature: versions, php

#43975 Handle more cases in the MergeDistributive search query optimizer
  lib/private/Files/Search/QueryOptimizer/MergeDistributiveOperations.php
  lib/private/Files/Search/QueryOptimizer/ReplacingOptimizerStep.php
  tests/lib/Files/Search/QueryOptimizer/CombinedTests.php
Labels: 3. to review, performance 🚀

#43989 Fix/breadrcrumbs not showing on fixed view width
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: files

#43855 Implement team provider api
  core/Controller/TeamsApiController.php
  core/ResponseDefinitions.php
  core/openapi.json
  lib/composer/composer/LICENSE
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/installed.json
  lib/composer/composer/installed.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Server.php
  lib/private/Teams/TeamManager.php
  lib/public/AppFramework/Bootstrap/IRegistrationContext.php
  lib/public/Teams/ITeamManager.php
  lib/public/Teams/ITeamResourceProvider.php
  lib/public/Teams/Team.php
  lib/public/Teams/TeamResource.php
  psalm.xml
Labels: enhancement, 3. to review

#43904 fix(dav): Fix atomic calendar/subscription updates
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: bug, 3. to review, feature: dav, feature: caldav

#44001 fix(settings): Migrate logger to TypeScript
  apps/settings/src/components/AdminDelegation/GroupSelect.vue
  apps/settings/src/components/BasicSettings/ProfileSettings.vue
  apps/settings/src/components/UserList.vue
  apps/settings/src/components/Users/VirtualList.vue
  apps/settings/src/components/WebAuthn/AddDevice.vue
  apps/settings/src/components/WebAuthn/Section.vue
  apps/settings/src/logger.ts
  apps/settings/src/main-admin-basic-settings.js
  apps/settings/src/store/users.js
  apps/settings/src/utils/handlers.js
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.LICENSE.txt
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/settings-vue-settings-admin-delegation.js
  dist/settings-vue-settings-admin-delegation.js.LICENSE.txt
  dist/settings-vue-settings-admin-delegation.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.LICENSE.txt
  dist/settings-vue-settings-apps-users-management.js.map
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
  dist/settings-vue-settings-personal-security.js
  dist/settings-vue-settings-personal-security.js.LICENSE.txt
  dist/settings-vue-settings-personal-security.js.map
  dist/settings-vue-settings-personal-webauthn.js
  dist/settings-vue-settings-personal-webauthn.js.LICENSE.txt
  dist/settings-vue-settings-personal-webauthn.js.map
Labels: bug, 3. to review, feature: settings

#43903 fix(dav): Fix atomic addressbook update
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: bug, 3. to review, feature: dav, feature: carddav

#43252 fix(sharing): Avoid (dead)locking during orphan deletion
  apps/files_sharing/lib/DeleteOrphanedSharesJob.php
  apps/files_sharing/tests/DeleteOrphanedSharesJobTest.php
Labels: bug, 4. to release, feature: sharing, backport-request, feature: files

#43944 fix(settings): emails actions a11y and design
  apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
  apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
  apps/settings/src/components/PersonalInfo/shared/FederationControl.vue
  apps/settings/src/components/PersonalInfo/shared/FederationControlActions.vue
  cypress/e2e/settings/personal-info.cy.ts
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, design, 3. to review, backport-request, feature: settings, accessibility

#43998 fix(migrations): Help developers to add description and copyright info
  apps/user_ldap/lib/Migration/Version1190Date20230706134108.php
  apps/user_ldap/lib/Migration/Version1190Date20230706134109.php
  core/Command/Db/Migrations/GenerateCommand.php
  core/Migrations/Version27000Date20220613163520.php
Labels: bug, 3. to review

#44014 fix: Remove unused endpoint from base.php
  lib/base.php
Labels: 3. to review

#44016 fix(settings): Disable app again if it breaks the files app
  apps/settings/src/store/apps.js
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, backport-request, feature: apps management

#43999 fix(user_ldap): Catch DB Exceptions when updating group memberships
  apps/user_ldap/lib/LoginListener.php
  apps/user_ldap/lib/Service/UpdateGroupsService.php
Labels: 3. to review

#44019 [stable28] fix(files): Open new file when created from template
  apps/files/src/views/TemplatePicker.vue
  dist/3222-3222.js
  dist/3222-3222.js.map
  dist/448-448.js
  dist/448-448.js.LICENSE.txt
  dist/448-448.js.map
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review

#44007 feat: Rename circles to teams
  apps/files_sharing/src/components/SharingInput.vue
  core/img/apps/circles.svg
  core/src/icons.js
  dist/4889-4889.js
  dist/4889-4889.js.map
  dist/506-506.js
  dist/506-506.js.LICENSE.txt
  dist/506-506.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
  dist/icons.css
Labels: enhancement, 3. to review

#44023 chore(IURLGenerater): Document changes to `URL_REGEX_NO_MODIFIERS`
  lib/public/IURLGenerator.php
Labels: 3. to review

#44031 fix(settings): Allow to limit markdown heading levels to ensure correct hierarchy
  apps/settings/src/components/AppDetails.vue
  apps/settings/src/components/Markdown.vue
  apps/settings/src/views/Apps.vue
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review

#43263 Cleanup versions entities in versions:clean command
  apps/files_versions/lib/Command/CleanUp.php
  apps/files_versions/lib/Db/VersionsMapper.php
  apps/files_versions/tests/Command/CleanupTest.php
  tests/Core/Command/TwoFactorAuth/CleanupTest.php
Labels: bug, 3. to review, backport-request, feature: versions, php

#44015 fix: Remove calls to deprecated OC_JSON::encode
  lib/private/legacy/OC_API.php
  lib/private/legacy/OC_EventSource.php
  lib/private/legacy/OC_JSON.php
Labels: 3. to review, technical debt

#44000 cleanup: remove long depricated share code
  apps/files_sharing/lib/ShareBackend/Folder.php
  lib/private/Share/Share.php
  lib/public/Share.php
  tests/lib/Share/ShareTest.php
Labels: 3. to review

#44022 feat(settings): add JavaScript Source Maps support `.js.map` setup check
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/SetupChecks/JavaScriptSourceMaps.php
Labels: enhancement, 3. to review, feature: settings

#43437 use lazy user in UserMountCache for getting user for cached mount instead of duplicating logic
  lib/private/Files/Config/UserMountCache.php
  tests/lib/Files/Config/UserMountCacheTest.php
Labels: 3. to review

#43804 fix(settings): Split group lists
  apps/settings/src/views/Users.vue
  cypress/e2e/settings/users_groups.cy.ts
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, backport-request, feature: users and groups, accessibility

#43882 feat: Allow registration of advanced external share actions
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/services/ExternalShareActions.js
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/556-556.js
  dist/556-556.js.map
  dist/8670-8670.js
  dist/8670-8670.js.LICENSE.txt
  dist/8670-8670.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 4. to release, feature: sharing

#44041 Revert change in TwoFactorAuth CleanupTest.php
  tests/Core/Command/TwoFactorAuth/CleanupTest.php
Labels: bug, 3. to review, tests

#43996 feat: Store last known quota usage for a user
  lib/private/legacy/OC_Helper.php
Labels: enhancement, 4. to release

#44042 fix(user_ldap): Early failure for empty password login attempt
  apps/user_ldap/lib/Access.php
Labels: 3. to review, feature: ldap, backport-request

#44034 feat(theming): Provide CSS variable for favorite color and adjust for dark mode
  apps/files/src/components/FileEntry/FavoriteIcon.vue
  apps/theming/css/default.css
  apps/theming/css/theming.css
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Themes/HighContrastTheme.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
  apps/weather_status/src/App.vue
  dist/files-main.js
  dist/files-main.js.map
  dist/weather_status-weather-status.js
  dist/weather_status-weather-status.js.map
Labels: enhancement, design, 2. developing, feature: theming

#32163 don't perform an explicit setup when using the file cache
  lib/private/Cache/File.php
  lib/private/Files/Config/UserMountCache.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/SetupManager.php
Labels: 3. to review, stale, performance 🚀

#25109 add command to scan external storages directly
  apps/files_external/appinfo/info.xml
  apps/files_external/composer/composer/autoload_classmap.php
  apps/files_external/composer/composer/autoload_static.php
  apps/files_external/lib/Command/Notify.php
  apps/files_external/lib/Command/Scan.php
  apps/files_external/lib/Command/StorageAuthBase.php
Labels: enhancement, 3. to review

#44040 feat: Ship downloadlimit
  core/shipped.json
Labels: 3. to review

#43939 feat(settings): Migrate `.well-known` tests to `SetupCheck`
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/SetupChecks/CheckServerResponseTrait.php
  apps/settings/lib/SetupChecks/WellKnownUrls.php
  apps/settings/src/admin.js
  apps/settings/tests/SetupChecks/WellKnownUrlsTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
  lib/private/Http/Client/Client.php
  lib/public/Http/Client/IClient.php
Labels: enhancement, 3. to review, php

#44059 fix(settings): Drop deprecated code from app level badge
  apps/settings/src/components/AppList/AppLevelBadge.vue
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: settings

#44061 Revert "don't perform an explicit setup when using the file cache"
  lib/private/Cache/File.php
  lib/private/Files/Config/UserMountCache.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/SetupManager.php
Labels: bug, 4. to release, feature: filesystem, regression

#43824 fix(db): db-convert supports disabled apps but not removed ones
  core/Command/Db/ConvertType.php
Labels: 3. to review, backport-request, feature: occ

#44070 Bump Hub 7 -> Hub 8
  apps/settings/templates/settings/admin/overview.php
Labels: 3. to review

#44066 files_versions: add missing null check
  apps/files_versions/lib/Listener/FileEventsListener.php
Labels: bug, 3. to review

#43991 29.0.0 beta 1
  version.php
Labels: 3. to review

#43982 fix(filecache): Move from array_merge to avoid memory exhaustion on large scans
  lib/private/Files/Cache/Cache.php
Labels: 4. to release, feature: files

#44062 fix(files): properly reset preview component
  apps/files/src/components/FileEntry/FileEntryPreview.vue
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, technical debt

#43992 fix: Avoid clear cache with prefix
  lib/private/Collaboration/Reference/ReferenceManager.php
Labels: bug, 4. to release, backport-request, performance 🚀

#43983 Use the proper path to check if a file needs to be copied/moved to the actual target storage
  apps/dav/lib/Upload/ChunkingV2Plugin.php
Labels: bug, 3. to review, backport-request

#44082 fix(settings): Adjust order of parameters for `runRequest`
  apps/settings/lib/SetupChecks/CheckServerResponseTrait.php
  apps/settings/lib/SetupChecks/WellKnownUrls.php
Labels: bug, 3. to review, regression

#44064 refactor: depricate getNumberOfUnreadCommentsForFolder and redo it's …
  lib/private/Comments/Manager.php
  lib/public/Comments/ICommentsManager.php
  tests/lib/Comments/ManagerTest.php
Labels: 3. to review

#44083 Revert "files_versions: add missing null check"
  apps/files_versions/lib/Listener/FileEventsListener.php
Labels: 4. to release, feature: versions

#43778 Fix CSP for script-src with nonce on edge
  lib/private/AppFramework/Http/Request.php
  lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php
  lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php
Labels: bug, 3. to review

#43425 enh(appconfig): only try to insert new value if in doubt
  lib/private/AppConfig.php
Labels: enhancement, 2. developing, php

#44089 [stable28] fix(settings): users settings cypress
  apps/settings/src/views/Users.vue
  cypress/e2e/settings/users_groups.cy.ts
  dist/settings-users-8351.js
  dist/settings-users-8351.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review

#44073 fix(AppManager): Allow to query dark **or** bright icon
  apps/updatenotification/lib/Notification/AppUpdateNotifier.php
  lib/private/App/AppManager.php
  lib/public/App/IAppManager.php
  tests/lib/App/AppManagerTest.php
Labels: bug, 3. to review, 🍀 2024-Spring

#44095 [stable28] fix(UpdateNotifications): Handle numeric user ids
  apps/updatenotification/lib/Notification/BackgroundJob.php
Labels: bug, 3. to review, backport-request, feature: activity and notification

#43946 fix: changed login-page to reflect correct LDAP settings
  core/Controller/LoginController.php
  core/src/components/login/LoginForm.vue
  core/src/views/Login.vue
  dist/core-login.js
  dist/core-login.js.map
  tests/Core/Controller/LoginControllerTest.php
Labels: bug, 2. developing, feature: ldap, backport-request, feature: settings, applied on testing

#42628 deprecated sysconfig 'enable_file_metadata'
  config/config.sample.php
Labels: 2. developing, backport-request

#42707 enh(metadata): store current file etag
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  lib/private/Blurhash/Listener/GenerateBlurhashMetadata.php
  lib/private/FilesMetadata/Model/FilesMetadata.php
  lib/private/FilesMetadata/Model/MetadataValueWrapper.php
  lib/private/FilesMetadata/Service/MetadataRequestService.php
  lib/public/FilesMetadata/Model/IFilesMetadata.php
  lib/public/FilesMetadata/Model/IMetadataValueWrapper.php
Labels: enhancement, 3. to review

#44119 fix(theming): fix incorrectly inverted favicons
  apps/theming/lib/IconBuilder.php
Labels: bug, design, 3. to review, feature: theming

#43907 feat(appconfig): storing integrity check result as a lazy config value
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/IntegrityCheck/Checker.php
  lib/private/Repair.php
  lib/private/Repair/AddAppConfigLazyMigration.php
  lib/private/Server.php
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: 3. to review, performance 🚀

#39990 add some recrusive detection/prevention
  apps/files_external/tests/Storage/SmbTest.php
  apps/files_sharing/lib/SharedStorage.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
Labels: 2. developing, feature: sharing

#44149 [stable22] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44147 [stable23] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44146 [stable25] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44143 [stable24] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44144 [stable26] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44145 [stable27] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44148 [stable28] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44142 [master] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#44140 fix(settings): Fix always empty disabled users list for subadmins
  apps/provisioning_api/lib/Controller/UsersController.php
Labels: bug, 3. to review, backport-request, feature: users and groups

#44151 fix: Call execute until it is removed for Job class
  core/Command/Background/Job.php
  cron.php
Labels: 3. to review

#44117 test(dav): Add unit test for no calendars/subscription limit
  apps/dav/tests/unit/CalDAV/Security/RateLimitingPluginTest.php
Labels: 4. to release

#44138 docs(config.sample.php): Warn that `updatedirectory` will break updates if set to a value within the installation folder
  config/config.sample.php
Labels: 3. to review, backport-request, feature: install and update

#44011 feat: Adding PublicSectorBundle
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/App/AppStore/Bundles/BundleFetcher.php
  lib/private/App/AppStore/Bundles/PublicSectorBundle.php
  tests/lib/App/AppStore/Bundles/BundleFetcherTest.php
Labels: 4. to release

#44165 fix(updatenotification): spread the use of new iappconfig
  apps/settings/lib/Settings/Admin/Server.php
  apps/settings/lib/SetupChecks/CronInfo.php
  apps/settings/tests/Settings/Admin/ServerTest.php
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/tests/Settings/AdminTest.php
  core/ajax/update.php
  lib/private/Setup.php
  lib/private/Updater.php
  lib/private/Updater/VersionCheck.php
  tests/lib/Updater/VersionCheckTest.php
  tests/lib/UpdaterTest.php
Labels: bug, 3. to review, feature: settings, regression

#43334 fix(settings): `posix_getpwuid` can return `false` which should not be accessed like an array
  apps/settings/lib/Settings/Admin/Server.php
Labels: bug, 4. to release, backport-request, php

#41189 Respect custom webroot in setup form
  core/templates/installation.php
Labels: bug, 3. to review, feature: install and update

#44178 fix(Navigation): ensure NavManager is inited when adding an entry
  lib/private/NavigationManager.php
Labels: bug, 3. to review, feature: theming

#39669 occ: Add `--all` support to `user:lastseen`
  core/Command/User/LastSeen.php
Labels: enhancement, 3. to review, feature: occ, pending documentation

#43877 fix(provisioning_api): Fix AppInfo schema for OpenAPI
  apps/provisioning_api/lib/Controller/AppsController.php
  apps/provisioning_api/lib/ResponseDefinitions.php
  apps/provisioning_api/openapi-administration.json
  apps/provisioning_api/openapi-full.json
Labels: bug, 3. to review, backport-request

#44132 fix: don't return null for SharedStorage::getWrapperStorage with share recursion
  apps/files_sharing/lib/SharedStorage.php
Labels: bug, 3. to review

#44069 Split live photo listener to extract trashbin specific code into its own listener
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/AppInfo/Application.php
  apps/files/lib/Listener/SyncLivePhotosListener.php
  apps/files/lib/Service/LivePhotosService.php
  apps/files/src/views/Settings.vue
  apps/files/src/views/Sidebar.vue
  apps/files_trashbin/composer/composer/autoload_classmap.php
  apps/files_trashbin/composer/composer/autoload_static.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_trashbin/lib/Listeners/SyncLivePhotosListener.php
  cypress.config.ts
  cypress/dockerNode.ts
  cypress/e2e/files/FilesUtils.ts
  cypress/e2e/files/live_photos.cy.ts
  cypress/e2e/files_sharing/filesSharingUtils.ts
  cypress/e2e/files_versions/version_restoration.cy.ts
  cypress/support/commands.ts
  dist/files-main.js
  dist/files-main.js.map
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review, feature: files, php, tests

#44067 Migrate header check to setupcheck API
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/SetupChecks/OcxProviders.php
  apps/settings/lib/SetupChecks/SecurityHeaders.php
  apps/settings/src/admin.js
  apps/settings/tests/SetupChecks/OcxProvicersTest.php
  apps/settings/tests/SetupChecks/SecurityHeadersTest.php
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: 3. to review, feature: settings

#43516 chore: Migrate samba `files_external` test from drone to github
  .drone.yml
  .github/workflows/files-external-smb.yml
Labels: 2. developing, CI

#44094 fix(cron): Fix Cron misrepresenting itself as console
  cron.php
Labels: bug, 4. to release, feature: logging, feature: occ

#43652 Fixes for getting the filename in the FileInfo class
  lib/private/Files/FileInfo.php
Labels: 3. to review

#44191 fix(CI): Add missing generic files_external tests
  .github/workflows/files-external.yml
Labels: bug, 3. to review, CI

#44203 fix: avoid scanning a non existing directory
  lib/private/Files/Storage/Local.php
Labels: 3. to review, backport-request, php

#36252 Modernize mime typeloader
  lib/private/Files/Cache/SearchBuilder.php
  lib/private/Files/Type/Loader.php
  lib/public/Files/IMimeTypeLoader.php
  tests/lib/Files/Type/LoaderTest.php
Labels: 4. to release, feature: files, technical debt, pending documentation

#44171 [stable27] fix(comments): move new comment instructions placeholder to description
  apps/comments/src/components/Comment.vue
  apps/comments/src/views/Comments.vue
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
Labels: bug, 3. to review, feature: comments

#40144 Refactor `OC\Server::getLockingProvider`
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Utils/Scanner.php
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
  tests/lib/TestCase.php
Labels: 4. to release, technical debt

#40142 Refactor `OC\Server::getLazyRootFolder`
  lib/private/Share20/ProviderFactory.php
Labels: 4. to release, technical debt

#40143 Refactor `OC\Server::getLockdownManager`
  lib/private/Server.php
  tests/lib/Lockdown/Filesystem/NoFSTest.php
Labels: 4. to release, technical debt

#40123 Refactor `OC\Server::getRootFolder`
  lib/private/Streamer.php
  lib/private/legacy/OC_Files.php
  tests/lib/Preview/BackgroundCleanupJobTest.php
  tests/lib/Preview/Provider.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 3. to review, technical debt

#40136 Refactor `OC\Server::getGetRedisFactory`
  lib/private/Memcache/Redis.php
Labels: 4. to release, technical debt

#40127 Refactor `OC\Server::getTwoFactorAuthManager`
  lib/private/User/Session.php
  lib/private/legacy/OC_JSON.php
  lib/private/legacy/OC_Util.php
Labels: 4. to release, technical debt

#40138 Refactor `OC\Server::getHasher`
  lib/private/Security/Hasher.php
  lib/private/Share20/ProviderFactory.php
  lib/private/User/Database.php
  lib/public/Security/IHasher.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
Labels: 4. to release, technical debt

#40116 Refactor `OC\Server::getCloudFederationFactory`
  lib/private/Share20/ProviderFactory.php
Labels: 4. to release, technical debt

#40131 Refactor `OC\Server::getShareManager`
  lib/private/Share20/Hooks.php
  lib/private/Template/JSConfigHelper.php
  lib/public/Util.php
  tests/lib/Files/ViewTest.php
  tests/lib/Share20/DefaultShareProviderTest.php
  tests/lib/Share20/LegacyHooksTest.php
Labels: 4. to release, technical debt

#40115 Refactor `OC\Server::getCapabilitiesManager`
  lib/private/TemplateLayout.php
Labels: 4. to release, technical debt

#43993 Fix default text processing provider in AI settings
  apps/settings/lib/Settings/Admin/ArtificialIntelligence.php
  apps/testing/lib/Provider/FakeTextProcessingProvider.php
  apps/testing/lib/Provider/FakeTextProcessingProviderSync.php
Labels: bug, 3. to review, feature: text processing

#44162 fix(files): fixed breadcrumbs dissapearing on narrow screens
  apps/files/src/components/BreadCrumbs.vue
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 4. to release, backport-request, feature: files

#44202 fix: Migrate WebDAV endpoint check to SetupCheck API
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/SetupChecks/WebdavEndpoint.php
  apps/settings/src/admin.js
  core/js/setupchecks.js
  core/js/tests/specs/setupchecksSpec.js
  dist/settings-legacy-admin.js
  dist/settings-legacy-admin.js.map
Labels: enhancement, 3. to review

#34115 Allow to specify allowed groups to share instead of excluded groups
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/components/AdminSettingsSharingForm.vue
  apps/settings/tests/Settings/Admin/SharingTest.php
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
  lib/private/Contacts/ContactsMenu/ContactsStore.php
  lib/private/Share20/ShareDisableChecker.php
  tests/lib/Share20/ManagerTest.php
Labels: enhancement, 4. to release, feature: sharing

#40125 Refactor `OC\Server::getThemingDefaults`
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/Console/Application.php
  lib/private/Server.php
  lib/private/URLGenerator.php
  lib/public/Defaults.php
Labels: 4. to release, technical debt

#40117 Refactor `OC\Server::getCommentsManager`
  lib/private/User/User.php
  tests/lib/Comments/ManagerTest.php
  tests/lib/ServerTest.php
Labels: 4. to release, technical debt

#44223 fix(files_sharing): ShareesAPI - Return empty response when user is not allowed to share
  apps/files_sharing/lib/Controller/ShareesAPIController.php
  apps/files_sharing/tests/Controller/ShareesAPIControllerTest.php
Labels: bug, 4. to release

#41684 Add mimetype for ReStructuredText
  core/js/mimetypelist.js
  lib/private/Repair/RepairMimeTypes.php
  resources/config/mimetypealiases.dist.json
  resources/config/mimetypemapping.dist.json
  tests/data/integritycheck/mimetypeListModified/core/js/mimetypelist.js
  tests/data/integritycheck/mimetypeListModified/core/signature.json
  version.php
Labels: enhancement, 4. to release

#43862 Add ability to cancel a scheduled transcription
  lib/private/SpeechToText/SpeechToTextManager.php
  lib/public/SpeechToText/ISpeechToTextManager.php
Labels: enhancement, 4. to release, feature: text processing

#44109 feat: author displayname and avatar on versions
  apps/files_versions/src/components/Version.vue
  apps/files_versions/src/utils/versions.ts
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: enhancement, 3. to review, feature: versions, ux

#44226 fix(files): provide onDestroy callback for interactive widgets
  apps/files/src/reference-files.ts
  dist/files-reference-files.js
  dist/files-reference-files.js.map
Labels: bug, 4. to release, feature: files

#40161 More comprehensive wording for devices wipe action
  apps/settings/src/components/Users/UserRow.vue
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 4. to release, feature: users and groups, feature: language l10n and translations

#43446 feat: add `PATCH` HTTP Verb Support To `IClient` Interface & its HTTP Client Implementation
  lib/private/Http/Client/Client.php
  lib/public/Http/Client/IClient.php
Labels: enhancement, 4. to release, pending documentation

#43534 minor syntax update
  lib/private/Log.php
Labels: 4. to release, php

#43613 fix: fallback from guessing the owner from path in versioning
  apps/files_versions/lib/Listener/FileEventsListener.php
Labels: 4. to release, backport-request, feature: versions

#44004 perf: improve performance of resolving group shares
  lib/private/Share20/DefaultShareProvider.php
Labels: 4. to release, performance 🚀

#44189 Do not throw an exception if the etag is not set in metadata
  lib/private/FilesMetadata/Model/FilesMetadata.php
Labels: bug, 3. to review, feature: files, php

#44258 fix: getLogLevel return type
  lib/private/Log.php
Labels: 3. to review, regression

#44262 fix(Logger): Warn on invalid `loglevel` configuration option
  lib/private/Log.php
Labels: bug, 4. to release, feature: logging

#44251 [stable28]fix: List specific share permissions as subline
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/5709-5709.js
  dist/5709-5709.js.LICENSE.txt
  dist/5709-5709.js.map
  dist/8284-8284.js
  dist/8284-8284.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, 28-feedback

#44255 fix: Correctly add search event listener to make searching the app list work again
  apps/settings/src/components/AppList.vue
  apps/settings/src/views/Apps.vue
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: apps management

#44254 fix(files): Adjust dropservice to work with Blink engine
  apps/files/src/components/DragAndDropNotice.vue
  apps/files/src/services/DropService.ts
  cypress/e2e/files/drag-n-drop.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, regression

#44259 feat(settings): Allow app discover section links to open app routes or the appstore page
  apps/settings/src/app-types.ts
  apps/settings/src/components/AppStoreDiscover/AppLink.vue
  apps/settings/src/components/AppStoreDiscover/PostType.vue
  apps/settings/src/components/AppStoreSidebar/AppReleasesTab.vue
  apps/settings/src/router/routes.ts
  apps/settings/src/store/apps-store.ts
  apps/settings/src/views/AppStoreNavigation.vue
  apps/settings/src/views/AppStoreSidebar.vue
  dist/8484-8484.js
  dist/8484-8484.js.map
  dist/8753-8753.js
  dist/8753-8753.js.map
  dist/9923-9923.js
  dist/9923-9923.js.LICENSE.txt
  dist/9923-9923.js.map
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, 3. to review, feature: apps management

#44279 fix: ensure nested mount points are handled in the correct order
  lib/private/Files/View.php
Labels: 3. to review, backport-request

#33546 added --enabled and --disabled options to occ app:list
  core/Command/App/ListApps.php
Labels: enhancement, 4. to release, feature: apps management, feature: occ, pending documentation

#37953 feat: Reword login form disabled warning #37949
  core/src/views/Login.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, design, 4. to release

#44260 docs: added codespace link
  .devcontainer/README.md
Labels: 3. to review, developer experience

#44154 Added rate limit bypass for app_api requests
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/RateLimitingMiddleware.php
  tests/lib/AppFramework/Middleware/Security/RateLimitingMiddlewareTest.php
Labels: bug, 2. developing, security

#44305 fix(federatedfilesharing): Use correct language file to render notifi…
  apps/federatedfilesharing/lib/Notifier.php
  apps/files_sharing/lib/Notification/Notifier.php
Labels: bug, 3. to review, feature: federation, backport-request, feature: language l10n and translations

#44281 fix(AppDiscoverFetcher): Do not remove entries as expired that have no expiry date
  apps/settings/lib/Controller/AppSettingsController.php
  lib/private/App/AppStore/Fetcher/AppDiscoverFetcher.php
  tests/lib/App/AppStore/Fetcher/AppDiscoverFetcherTest.php
Labels: bug, 3. to review, feature: apps management, 🍀 2024-Spring

#44316 fix(sharing): resolveGroupShares setPermissions on null
  lib/private/Share20/DefaultShareProvider.php
Labels: bug, 4. to release, feature: sharing, regression

#44236 fix(settings): apps list layout
  apps/settings/css/settings.css
  apps/settings/css/settings.css.map
  apps/settings/css/settings.scss
  apps/settings/src/components/AppList.vue
  apps/settings/src/components/AppList/AppItem.vue
  apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue
  apps/settings/src/router/routes.ts
  cypress/e2e/settings/apps.cy.ts
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: settings, regression

#44282 fix(settings): Support `order` property on App Discover elements and hide future elements
  apps/settings/src/components/AppStoreDiscover/AppStoreDiscoverSection.vue
  apps/settings/src/constants/AppDiscoverTypes.ts
  apps/settings/src/utils/appDiscoverParser.spec.ts
  apps/settings/src/utils/appDiscoverParser.ts
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: apps management, 🍀 2024-Spring

#44286 fix(settings): Ensure media for app discover section is scaled correctly
  apps/settings/src/components/AppStoreDiscover/AppStoreDiscoverSection.vue
  apps/settings/src/components/AppStoreDiscover/PostType.vue
  dist/1019-1019.js
  dist/1019-1019.js.LICENSE.txt
  dist/1019-1019.js.map
  dist/3865-3865.js
  dist/3865-3865.js.map
  dist/9923-9923.js
  dist/9923-9923.js.map
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, feature: apps management, 🍀 2024-Spring

#44328 feat(settings): Implement `showcase` type for App Discover section
  apps/settings/src/components/AppList/AppItem.vue
  apps/settings/src/components/AppStoreDiscover/AppStoreDiscoverSection.vue
  apps/settings/src/components/AppStoreDiscover/AppType.vue
  apps/settings/src/components/AppStoreDiscover/PostType.vue
  apps/settings/src/components/AppStoreDiscover/ShowcaseType.vue
  apps/settings/src/constants/AppDiscoverTypes.ts
  dist/1019-1019.js
  dist/1019-1019.js.map
  dist/1544-1544.js
  dist/1544-1544.js.LICENSE.txt
  dist/1544-1544.js.map
  dist/3865-3865.js
  dist/3865-3865.js.LICENSE.txt
  dist/3865-3865.js.map
  dist/8630-8630.js
  dist/8630-8630.js.map
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, 3. to review, feature: apps management, 🍀 2024-Spring

#44333 fix(db): remove redundant index in cards
  core/Application.php
Labels: bug, 4. to release

#44276 fix(config): Make sure user keys are strings
  lib/private/AllConfig.php
  tests/lib/AllConfigTest.php
Labels: bug, 3. to review

#44339 fix(share): use share owner to get ownership
  lib/private/Share20/Manager.php
Labels: 3. to review

#44297 Forbid tagging readonly files
  apps/dav/lib/SystemTag/SystemTagMappingNode.php
  apps/dav/lib/SystemTag/SystemTagsObjectMappingCollection.php
  apps/dav/lib/SystemTag/SystemTagsObjectTypeCollection.php
  apps/dav/lib/SystemTag/SystemTagsRelationsCollection.php
  apps/dav/tests/unit/SystemTag/SystemTagMappingNodeTest.php
  apps/dav/tests/unit/SystemTag/SystemTagsObjectMappingCollectionTest.php
  apps/dav/tests/unit/SystemTag/SystemTagsObjectTypeCollectionTest.php
Labels: 4. to release

#44295 Allow injecting the user temporarily for direct editing
  apps/files_external/lib/Migration/DummyUserSession.php
  lib/private/DirectEditing/Manager.php
  lib/private/User/Session.php
  lib/private/legacy/OC_User.php
  lib/public/IUserSession.php
Labels: bug, 3. to review

#44363 Rename MetadataFileEvents to VersionAuthorListener
  apps/files_versions/composer/composer/autoload_classmap.php
  apps/files_versions/composer/composer/autoload_static.php
  apps/files_versions/lib/AppInfo/Application.php
  apps/files_versions/lib/Listener/VersionAuthorListener.php
Labels: 3. to review, feature: versions, technical debt, php

#44376 fix(dav): ACLs for shared addressbooks
  apps/dav/lib/CardDAV/AddressBook.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/tests/unit/CardDAV/AddressBookTest.php
Labels: bug, 4. to release, feature: dav, feature: carddav

#44218 feat: Limit email input to 255 chars
  core/Controller/LoginController.php
  core/Controller/LostController.php
  core/src/components/login/LoginForm.vue
  core/src/components/login/ResetPassword.vue
  core/src/mixins/auth.js
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, 2. developing

#44381 fix(workflowengine): Use correct event names to make search for groups work again
  apps/workflowengine/src/components/Checks/RequestUserGroup.vue
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows, regression

#44368 feat: Add new mdi New file menu icons
  apps/files/lib/ResponseDefinitions.php
  apps/files/openapi.json
  apps/files/src/newMenu/newFromTemplate.ts
  apps/files/src/types.ts
  core/img/actions/add-folder-description.svg
  core/img/filetypes/text.svg
  core/img/filetypes/x-office-document.svg
  core/img/filetypes/x-office-drawing.svg
  core/img/filetypes/x-office-presentation.svg
  core/img/filetypes/x-office-spreadsheet.svg
  core/src/icons.js
  dist/files-init.js
  dist/files-init.js.map
  dist/icons.css
  lib/public/Files/Template/TemplateFileCreator.php
Labels: enhancement, design, 3. to review, feature: files, 🍀 2024-Spring
