Repository nextcloud/server, pull requests merged in 2025-05, with the labels that each got.

#52575 fix(notification): Notification in activity shows "Rich subject or a …
  apps/files/lib/Activity/FavoriteProvider.php
Labels: backport-request

#52568 chore: ignore coding-standard PRs from git blame
  .git-blame-ignore-revs
Labels: 3. to review, ♻️ refactor

#52542 fix: Forward 'extra' argument when optimizing query
  lib/private/Files/Search/QueryOptimizer/OrEqualsToIn.php
  lib/private/Files/Search/QueryOptimizer/SplitLargeIn.php
Labels: bug, 3. to review, feature: search, php

#52584 fix(CI): fix CI in documentation repository
  config/config.sample.php
Labels: bug, 3. to review

#52588 test: Finish migrating tests/Core/ to PHPUnit 10 compatible code
  tests/Core/Command/Apps/AppsDisableTest.php
  tests/Core/Command/Apps/AppsEnableTest.php
  tests/Core/Command/Config/ImportTest.php
  tests/Core/Command/Config/ListConfigsTest.php
  tests/Core/Command/Config/System/DeleteConfigTest.php
  tests/Core/Command/Config/System/GetConfigTest.php
  tests/Core/Command/Config/System/SetConfigTest.php
  tests/Core/Command/Encryption/ChangeKeyStorageRootTest.php
  tests/Core/Command/Encryption/DecryptAllTest.php
  tests/Core/Command/Encryption/DisableTest.php
  tests/Core/Command/Encryption/EncryptAllTest.php
  tests/Core/Command/Encryption/SetDefaultModuleTest.php
  tests/Core/Command/Group/InfoTest.php
  tests/Core/Command/Group/ListCommandTest.php
  tests/Core/Command/Maintenance/Mimetype/UpdateDBTest.php
  tests/Core/Command/Maintenance/ModeTest.php
  tests/Core/Command/Preview/RepairTest.php
  tests/Core/Command/SystemTag/AddTest.php
  tests/Core/Command/SystemTag/DeleteTest.php
  tests/Core/Command/SystemTag/EditTest.php
  tests/Core/Command/SystemTag/ListCommandTest.php
  tests/Core/Command/User/AddTest.php
  tests/Core/Command/User/DeleteTest.php
  tests/Core/Command/User/LastSeenTest.php
  tests/Core/Command/User/SettingTest.php
  tests/Core/Controller/AutoCompleteControllerTest.php
  tests/Core/Controller/ClientFlowLoginControllerTest.php
  tests/Core/Controller/LoginControllerTest.php
  tests/Core/Controller/LostControllerTest.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
  tests/Core/Controller/WipeControllerTest.php
  tests/Core/Middleware/TwoFactorMiddlewareTest.php
  tests/Core/Service/LoginFlowV2ServiceUnitTest.php
  tests/lib/Collaboration/Collaborators/LookupPluginTest.php
  tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
  tests/lib/Contacts/ContactsMenu/ManagerTest.php
  tests/lib/DirectEditing/ManagerTest.php
  tests/lib/Encryption/DecryptAllTest.php
  tests/lib/Encryption/Keys/StorageTest.php
  tests/lib/Files/Mount/ObjectHomeMountProviderTest.php
  tests/lib/Files/Storage/Wrapper/AvailabilityTest.php
  tests/lib/Files/Type/DetectionTest.php
  tests/lib/Files/ViewTest.php
  tests/lib/Http/Client/ClientTest.php
  tests/lib/IntegrityCheck/CheckerTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, technical debt

#52587 fix(loginflow): Fix type error when password could not be decrypted
  core/Service/LoginFlowV2Service.php
  tests/Core/Service/LoginFlowV2ServiceUnitTest.php
Labels: bug, 3. to review, backport-request, feature: authentication

#52628 fix(files_external): Mark password fields for LoginCredentials and SessionCredentials as hidden and optional
  apps/files_external/lib/Command/Backends.php
  apps/files_external/lib/Lib/Auth/OAuth1/OAuth1.php
  apps/files_external/lib/Lib/Auth/OAuth2/OAuth2.php
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Backend/LegacyBackend.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/src/settings.js
  apps/files_external/templates/settings.php
  apps/files_external/tests/Backend/LegacyBackendTest.php
  apps/files_external/tests/DefinitionParameterTest.php
  dist/files_external-settings.js
  dist/files_external-settings.js.map
Labels: bug, 3. to review, backport-request

#52630 fix(files): Fix non-string values for activity rich object strings
  apps/files/lib/Activity/Provider.php
  apps/files/tests/Activity/ProviderTest.php
Labels: bug, 3. to review

#51608 feat(files): add command to automatically rename filenames
  apps/files/appinfo/info.xml
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/Command/SanitizeFilenames.php
  apps/files/lib/Command/WindowsCompatibleFilenames.php
  apps/files/lib/Settings/DeclarativeAdminSettings.php
  build/integration/files_features/windows_compatibility.feature
Labels: enhancement, 3. to review, feature: files, 🍂 2025-Autumn

#52048 fix(workflowengine): fix group not shown in Group membership check
  apps/workflowengine/src/components/Checks/RequestUserGroup.vue
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, backport-request, feature: workflows

#52621 add lexicon support to files_external
  apps/files_external/composer/composer/autoload_classmap.php
  apps/files_external/composer/composer/autoload_static.php
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/ConfigLexicon.php
  apps/files_external/lib/Listener/LoadAdditionalListener.php
  apps/files_external/lib/Service/BackendService.php
  apps/files_external/tests/Service/BackendServiceTest.php
Labels: 3. to review

#52583 fix(apps): Sort names separately from active/update state
  apps/settings/src/components/AppList.vue
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, backport-request

#52645 [stable30] fix(files_external): Mark password fields for LoginCredentials and SessionCredentials as hidden and optional
  apps/files_external/lib/Command/Backends.php
  apps/files_external/lib/Lib/Auth/OAuth1/OAuth1.php
  apps/files_external/lib/Lib/Auth/OAuth2/OAuth2.php
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Backend/LegacyBackend.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/src/settings.js
  apps/files_external/templates/settings.php
  apps/files_external/tests/Backend/LegacyBackendTest.php
  apps/files_external/tests/DefinitionParameterTest.php
  dist/files_external-settings.js
  dist/files_external-settings.js.map
Labels: bug, 3. to review

#52642 fix(TaskProcessing): increase task cleanup delay
  lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
Labels: backport-request

#51924 feat: Calendar Export
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/Export/ExportService.php
  apps/dav/lib/Command/ExportCalendar.php
  apps/dav/lib/Listener/AddMissingIndicesListener.php
  apps/dav/lib/Migration/Version1006Date20180628111625.php
  apps/dav/tests/unit/CalDAV/CalendarImplTest.php
  apps/dav/tests/unit/CalDAV/Export/ExportServiceTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Calendar/CalendarExportOptions.php
  lib/public/Calendar/ICalendarExport.php
Labels: enhancement, 4. to release, pending documentation, feature: caldav

#52641 [stable30] fix(workflowengine): fix group not shown in Group membership check
  apps/workflowengine/src/components/Checks/RequestUserGroup.vue
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows

#52646 [stable29] fix(files_external): Mark password fields for LoginCredentials and SessionCredentials as hidden and optional
  apps/files_external/lib/Command/Backends.php
  apps/files_external/lib/Lib/Auth/OAuth1/OAuth1.php
  apps/files_external/lib/Lib/Auth/OAuth2/OAuth2.php
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Backend/LegacyBackend.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/src/settings.js
  apps/files_external/templates/settings.php
  apps/files_external/tests/Backend/LegacyBackendTest.php
  apps/files_external/tests/DefinitionParameterTest.php
  dist/files_external-settings.js
  dist/files_external-settings.js.map
Labels: bug, 3. to review

#52647 [stable28] fix(files_external): Mark password fields for LoginCredentials and SessionCredentials as hidden and optional
  apps/files_external/js/settings.js
  apps/files_external/lib/Command/Backends.php
  apps/files_external/lib/Lib/Auth/OAuth1/OAuth1.php
  apps/files_external/lib/Lib/Auth/OAuth2/OAuth2.php
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Backend/LegacyBackend.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/templates/settings.php
  apps/files_external/tests/Backend/LegacyBackendTest.php
  apps/files_external/tests/DefinitionParameterTest.php
Labels: bug, 3. to review

#52648 [stable27] fix(files_external): Mark password fields for LoginCredentials and SessionCredentials as hidden and optional
  apps/files_external/js/settings.js
  apps/files_external/lib/Command/Backends.php
  apps/files_external/lib/Lib/Auth/OAuth1/OAuth1.php
  apps/files_external/lib/Lib/Auth/OAuth2/OAuth2.php
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Backend/LegacyBackend.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/templates/settings.php
  apps/files_external/tests/Backend/LegacyBackendTest.php
  apps/files_external/tests/DefinitionParameterTest.php
  apps/files_external/tests/js/settingsSpec.js
Labels: bug, 3. to review

#52649 [stable26] fix(files_external): Mark password fields for LoginCredentials and SessionCredentials as hidden and optional
  apps/files_external/js/settings.js
  apps/files_external/lib/Command/Backends.php
  apps/files_external/lib/Lib/Auth/OAuth1/OAuth1.php
  apps/files_external/lib/Lib/Auth/OAuth2/OAuth2.php
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Backend/LegacyBackend.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/DefinitionParameter.php
  apps/files_external/templates/settings.php
  apps/files_external/tests/Backend/LegacyBackendTest.php
  apps/files_external/tests/DefinitionParameterTest.php
  apps/files_external/tests/js/settingsSpec.js
Labels: bug, 3. to review

#51779 store original path in object metadata
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/ObjectStore/S3.php
  lib/private/Files/ObjectStore/S3ObjectTrait.php
  lib/public/Files/ObjectStore/IObjectStoreMetaData.php
Labels: 3. to review

#52441 fix: better error message when trying to scan a folder that is already being scanned
  apps/files/lib/Command/Scan.php
  apps/files_external/lib/Command/Scan.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Utils/Scanner.php
  lib/public/Lock/LockedException.php
Labels: 3. to review

#52047 fix: don't construct storage when checking if a sub-mount is applicable
  lib/private/Files/View.php
Labels: 3. to review

#52511 feat(files_sharing): Add toggle to control display area for federated shares
  apps/files_sharing/composer/composer/autoload_classmap.php
  apps/files_sharing/composer/composer/autoload_static.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Config/ConfigLexicon.php
  apps/files_sharing/lib/Listener/LoadSidebarListener.php
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/services/ConfigService.ts
  apps/files_sharing/src/views/SharingTab.vue
  dist/1092-1092.js
  dist/1092-1092.js.license
  dist/1092-1092.js.map
  dist/1092-1092.js.map.license
  dist/9134-9134.js
  dist/9134-9134.js.map
  dist/9134-9134.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: feature: sharing, pending documentation

#52640 [stable31] fix(workflowengine): fix group not shown in Group membership check
  apps/workflowengine/src/components/Checks/RequestUserGroup.vue
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: bug, 3. to review, feature: workflows

#52639 30.0.11 RC1
  version.php
Labels: 3. to review

#52638 31.0.5 RC1
  version.php
Labels: 3. to review

#52586 fix(throttler): Always use the sleepDelayOrThrowOnMax instead of deprecated sleepDelay
  apps/dav/lib/Connector/Sabre/PublicAuth.php
  apps/dav/lib/Direct/DirectHome.php
  apps/dav/lib/Files/BrowserErrorPagePlugin.php
  apps/dav/tests/unit/Direct/DirectHomeTest.php
  lib/private/AppFramework/Middleware/PublicShare/PublicShareMiddleware.php
  lib/private/Security/Bruteforce/Throttler.php
Labels: bug, 3. to review, feature: sharing, feature: files

#52623 iAppConfig: getValueType() get data from lexicon if available
  lib/private/AppConfig.php
Labels: 3. to review

#52438 fix(files): middle click & ctrl new tab
  apps/files/src/components/FileEntryMixin.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, regression

#52636 test: add e2e tests for multiple-files download
  cypress/e2e/files/files-download.cy.ts
Labels: 3. to review, tests

#52543 fix(share): assume download enabled on federated share
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: backport-request

#52634 perf(Share20): Add interface to query all shares in a folder without filtering by user
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/sharebymail/lib/ShareByMailProvider.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/public/Share/IShareProviderSupportsAllSharesInFolder.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review, pending documentation, performance 🚀

#52699 fix(webhooks_listener): correctly set userId from event
  apps/webhook_listeners/lib/BackgroundJobs/WebhookCall.php
  apps/webhook_listeners/lib/Listener/WebhooksEventListener.php
Labels: backport-request

#51081 fix(CalDAV): add calendar enable
  apps/dav/lib/CalDAV/CachedSubscriptionImpl.php
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/CalendarProvider.php
  apps/dav/lib/Db/PropertyMapper.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/Calendar/ICalendarIsEnabled.php
Labels: 4. to release, backport-request, feature: caldav

#52690 Spelling standardization
  apps/files_sharing/src/views/SharingTab.vue
  dist/1092-1092.js
  dist/1092-1092.js.map
  dist/1092-1092.js.map.license
  dist/4589-4589.js
  dist/4589-4589.js.license
  dist/4589-4589.js.map
  dist/4589-4589.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: feature: language/translations (l10n/i18n)

#52707 fix: throw a better error if we can't get the encrypted header size
  apps/encryption/lib/Command/FixEncryptedVersion.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/public/Encryption/Exceptions/InvalidHeaderException.php
Labels: 3. to review

#52703 chore(cypress): add setup tests
  .github/workflows/cypress.yml
  core/src/components/setup/RecommendedApps.vue
  cypress.config.ts
  cypress/dockerNode.ts
  cypress/e2e/core/setup.ts
  dist/core-recommendedapps.js
  dist/core-recommendedapps.js.map
Labels: 3. to review, technical debt, tests

#52665 fix: create mountpoint folder even if the user has a quota of 0
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/Files/View.php
Labels: 3. to review

#52706 feat: add more encryption checks to info:file
  core/Command/Info/File.php
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3. to review

#52693 feat: allow setting system config values with json value
  core/Command/Config/System/SetConfig.php
Labels: 3. to review

#52686 fix(files_external): Safely check if the timestamp is numeric
  apps/files_external/lib/Lib/Storage/Swift.php
Labels: 3. to review, feature: external storage

#52771 fix(updatenotification): respect `updatechecker` config
  apps/updatenotification/lib/BackgroundJob/UpdateAvailableNotifications.php
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/tests/BackgroundJob/UpdateAvailableNotificationsTest.php
  apps/updatenotification/tests/Settings/AdminTest.php
Labels: bug, 3. to review, backport-request

#51920 fix: improve handling of newFolder race condition handling
  lib/private/Files/Node/Folder.php
Labels: 3. to review

#52681 feat: add command to check files_external dependencies
  apps/files_external/appinfo/info.xml
  apps/files_external/composer/composer/autoload_classmap.php
  apps/files_external/composer/composer/autoload_static.php
  apps/files_external/lib/Command/Dependencies.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/MissingDependency.php
  apps/files_external/lib/Service/BackendService.php
Labels: 3. to review

#52785 feat(dav): allow uploading folders to public shares
  apps/dav/lib/Connector/Sabre/ChecksumUpdatePlugin.php
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Files/Sharing/FilesDropPlugin.php
  apps/dav/tests/unit/Files/Sharing/FilesDropPluginTest.php
  build/integration/features/bootstrap/FilesDropContext.php
  build/integration/features/bootstrap/WebDav.php
  build/integration/filesdrop_features/filesdrop.feature
Labels: enhancement, 3. to review, feature: sharing, feature: dav, feature: files, 🍂 2025-Autumn

#52778 fix: check if properties exist before using them
  lib/private/Calendar/Manager.php
  tests/lib/Calendar/ManagerTest.php
Labels: 3. to review, backport-request

#52688 feat(FilenameValidator): allow to sanitize filenames
  apps/files/lib/Command/SanitizeFilenames.php
  lib/private/Files/FilenameValidator.php
  lib/public/Files/IFilenameValidator.php
  tests/lib/Files/FilenameValidatorTest.php
Labels: enhancement, 3. to review, 🍂 2025-Autumn

#52694 fix(files_versions): Folder should not be hardcoded
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
Labels: bug, 4. to release, backport-request, feature: versions

#52046 Introduce own method for calendar unsharing
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Command/ClearCalendarUnshares.php
  apps/dav/lib/Command/ListCalendarShares.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/lib/DAV/Sharing/SharingMapper.php
  apps/dav/lib/DAV/Sharing/SharingService.php
  apps/dav/lib/Events/CalendarShareUpdatedEvent.php
  apps/dav/tests/integration/DAV/Sharing/CalDavSharingBackendTest.php
  apps/dav/tests/integration/DAV/Sharing/SharingMapperTest.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/Command/ListCalendarSharesTest.php
  apps/dav/tests/unit/DAV/Sharing/BackendTest.php
  apps/dav/tests/unit/DAV/Sharing/SharingServiceTest.php
Labels: bug, 4. to release

#52378 feat: add option to include external storage when transfering files
  apps/files/lib/Command/TransferOwnership.php
  apps/files/lib/Service/OwnershipTransferService.php
Labels: 3. to review

#52802 chore: deprecate \OC_Helper::canExecute
  lib/private/Files/Type/Detection.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, pending documentation, ♻️ refactor

#52798 fix: log requests exceeding the rate limiting
  lib/private/Security/RateLimiting/Limiter.php
  tests/lib/Security/RateLimiting/LimiterTest.php
Labels: bug, 4. to release, backport-request

#52775 fix unjailedroot of nested jails if there are other wrappers in between
  apps/files_sharing/lib/Cache.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  tests/lib/Files/Cache/Wrapper/CacheJailTest.php
Labels: 3. to review

#52817 chore(deps): Update rector to ^2.0
  .github/dependabot.yml
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/Connector/Sabre/Principal.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Events/CalendarShareUpdatedEvent.php
  apps/dav/templates/settings-example-content.php
  apps/dav/tests/integration/DAV/Sharing/CalDavSharingBackendTest.php
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
  apps/files_sharing/lib/External/Scanner.php
  apps/files_trashbin/lib/Command/CleanUp.php
  apps/files_trashbin/lib/Command/Size.php
  apps/files_trashbin/tests/TrashbinTest.php
  apps/files_versions/lib/Listener/FileEventsListener.php
  apps/files_versions/tests/VersioningTest.php
  apps/settings/lib/Settings/Admin/Mail.php
  apps/settings/lib/Settings/Personal/PersonalInfo.php
  apps/user_ldap/lib/User/User.php
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
Labels: 3. to review, dependencies, ♻️ refactor

#48560 feat(encryption): Migrate from hooks to events
  apps/admin_audit/lib/Actions/Files.php
  apps/admin_audit/lib/AppInfo/Application.php
  apps/files_sharing/tests/EncryptedSizePropagationTest.php
  apps/files_sharing/tests/TestCase.php
  apps/files_trashbin/tests/TrashbinTest.php
  apps/files_versions/lib/Listener/FileEventsListener.php
  apps/files_versions/tests/VersioningTest.php
  build/psalm-baseline.xml
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Encryption/EncryptionEventListener.php
  lib/private/Encryption/EncryptionWrapper.php
  lib/private/Encryption/HookManager.php
  lib/private/Encryption/Update.php
  lib/private/Encryption/Util.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Encryption/UpdateTest.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/Files/ViewTest.php
Labels: 3. to review

#52684 fix(db): Store last insert id before reconnect
  lib/private/DB/Adapter.php
  lib/private/DB/AdapterOCI8.php
  lib/private/DB/AdapterPgSql.php
  lib/private/DB/Connection.php
  tests/lib/Comments/ManagerTest.php
Labels: bug, 3. to review

#52812 chore: move `rmdirr` implementation from OC legacy to OCP\Files
  core/BackgroundJobs/BackgroundCleanupUpdaterBackupsJob.php
  lib/private/Files/Storage/Temporary.php
  lib/private/Installer.php
  lib/private/Repair/MoveUpdaterStepFile.php
  lib/private/TempManager.php
  lib/private/legacy/OC_Helper.php
  lib/public/Files.php
Labels: 3. to review, ♻️ refactor

#52544 chore(IAccountManager): remove deprecated visibility constants
  build/integration/features/contacts-menu.feature
  build/integration/features/provisioning-v1.feature
  lib/private/Accounts/AccountManager.php
  lib/private/Accounts/AccountProperty.php
  lib/public/Accounts/IAccountManager.php
  tests/lib/Accounts/AccountPropertyTest.php
Labels: 3. to review, technical debt, pending documentation, ♻️ refactor

#52359 feat(files): allow showing file type (mime) column
  apps/files/lib/Service/UserConfig.php
  apps/files/src/components/FileEntry.vue
  apps/files/src/components/FilesListTableFooter.vue
  apps/files/src/components/FilesListTableHeader.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/store/renaming.ts
  apps/files/src/store/userconfig.ts
  apps/files/src/types.ts
  apps/files/src/views/Settings.vue
  dist/7950-7950.js
  dist/7950-7950.js.map
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 3. to review, feature: files

#52841 chore: remove reviewers from dependendabot - its deprecated
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: 3. to review, CI

#52667 Improve init profiling
  build/psalm-baseline.xml
  build/rector.php
  lib/autoloader.php
  lib/base.php
  lib/private/AppFramework/Bootstrap/Coordinator.php
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/Route/Router.php
  lib/private/ServerContainer.php
  status.php
Labels: 3. to review

#52669 refactor(updatenotification): cleanup and remove deprecated usage
  apps/updatenotification/composer/autoload.php
  apps/updatenotification/composer/composer/autoload_classmap.php
  apps/updatenotification/composer/composer/autoload_static.php
  apps/updatenotification/lib/AppInfo/Application.php
  apps/updatenotification/lib/BackgroundJob/UpdateAvailableNotifications.php
  apps/updatenotification/lib/Command/Check.php
  apps/updatenotification/lib/Controller/APIController.php
  apps/updatenotification/lib/Controller/AdminController.php
  apps/updatenotification/lib/Manager.php
  apps/updatenotification/lib/Migration/Version011901Date20240305120000.php
  apps/updatenotification/lib/Notification/Notifier.php
  apps/updatenotification/lib/Settings/Admin.php
  apps/updatenotification/lib/UpdateChecker.php
  apps/updatenotification/tests/Notification/NotifierTest.php
  apps/updatenotification/tests/Settings/AdminTest.php
Labels: 3. to review, ♻️ refactor

#52813 fix(files_sharing): Show note if note exists on share
  apps/files_sharing/src/views/SharingDetailsTab.vue
  cypress/e2e/files_sharing/note-to-recipient.cy.ts
  dist/3982-3982.js
  dist/3982-3982.js.license
  dist/3982-3982.js.map
  dist/3982-3982.js.map.license
  dist/4589-4589.js
  dist/4589-4589.js.map
  dist/4589-4589.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: feature: sharing

#52822 feat(core): add human readable mimes
  LICENSES/GPL-2.0-only.txt
  core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php
  core/Command/Maintenance/Mimetype/UpdateJS.php
  core/js/mimetypelist.js
  lib/private/Files/Type/Detection.php
  lib/private/IntegrityCheck/Checker.php
  lib/public/Files/IMimeTypeDetector.php
  resources/config/freedesktop.org.xml
  resources/config/freedesktop.org.xml.license
  resources/config/mimetypenames-update.sh
  resources/config/mimetypenames.dist.json
  resources/config/mimetypenames.dist.json.license
  tests/data/integritycheck/mimetypeListModified/core/js/mimetypelist.js
  tests/data/integritycheck/mimetypeListModified/core/signature.json
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: enhancement, 3. to review, feature: files

#52853 refactor: Extend rector to all top-level files
  build/rector.php
  console.php
  cron.php
  ocs/providers.php
  ocs/v1.php
  public.php
  remote.php
Labels: 4. to release, ♻️ refactor

#52860 feat(psalm): Mark all usage of deprecated code as error
  build/psalm-baseline.xml
  psalm.xml
Labels: 3. to review, technical debt

#51818 feat: add command to get basic storage info
  core/Command/Info/FileUtils.php
  core/Command/Info/Storage.php
  core/Command/Info/Storages.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review

#42678 refactor(App): Remove registerRoutes method
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Routing/RouteConfig.php
  lib/private/AppFramework/Routing/RouteParser.php
  lib/private/Route/Router.php
  lib/public/AppFramework/App.php
  tests/lib/AppFramework/Routing/RouteParserTest.php
  tests/lib/AppFramework/Routing/RoutingTest.php
Labels: 3. to review, technical debt, pending documentation, ♻️ refactor

#52870 chore!(\OCP\Files): remove deprecated static `getStorage` method
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
  lib/private/legacy/OC_App.php
  lib/public/Files.php
Labels: 3. to review, pending documentation, ♻️ refactor

#52862 feat(files): show readable mime if available
  apps/files/src/components/FileEntry.vue
  core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php
  core/js/mimetypelist.js
  dist/files-main.js
  dist/files-main.js.map
  resources/config/mimetypenames-update.sh
  resources/config/mimetypenames.dist.json
  tests/data/integritycheck/mimetypeListModified/core/js/mimetypelist.js
  tests/data/integritycheck/mimetypeListModified/core/signature.json
Labels: enhancement, 3. to review, feature: files

#52846 refactor: cleanup public code and clean psalm baseline
  build/psalm-baseline-ocp.xml
  build/psalm-baseline.xml
  lib/public/AppFramework/ApiController.php
  lib/public/AppFramework/App.php
  lib/public/AppFramework/Http/RedirectToDefaultAppResponse.php
  lib/public/AppFramework/Http/Response.php
  lib/public/Defaults.php
  lib/public/Diagnostics/IQueryLogger.php
  lib/public/EventDispatcher/GenericEvent.php
  lib/public/Files.php
  lib/public/Files_FullTextSearch/Model/AFilesDocument.php
  lib/public/L10N/ILanguageIterator.php
  lib/public/Mail/IMailer.php
  lib/public/Profiler/IProfile.php
  lib/public/Security/ICrypto.php
  lib/public/Security/IHasher.php
  lib/public/Security/ISecureRandom.php
  lib/public/Util.php
Labels: 3. to review, ♻️ refactor

#52533 fix: do not show account filter for public shares
  apps/files_sharing/src/files_filters/AccountFilter.ts
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#52886 chore: ignore 3rdparty while psalm linting
  build/psalm-baseline.xml
  psalm.xml
Labels: 3. to review, tests, CI

#52871 fix(previews): lower log level when cached preview isn't found
  lib/private/Preview/Generator.php
Labels: bug, 4. to release, backport-request, feature: logging

#52772 fix(unified_search): Maintain filters when loading more results
  core/src/components/UnifiedSearch/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: backport-request

#52894 chore: move implementation to non-deprecated OCP\Util from OC_Helper
  lib/private/legacy/OC_Helper.php
  lib/public/Util.php
Labels: 3. to review, ♻️ refactor

#52708 fix(dav): add repair step to queue job to update rooms and resources
  apps/dav/appinfo/info.xml
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/Migration/RegisterUpdateCalendarResourcesRoomBackgroundJob.php
Labels: bug, 3. to review, feature: dav, backport-request, feature: caldav

#52885 fix(OCP\Color): use correct doc block type
  build/psalm-baseline.xml
  lib/public/Color.php
Labels: bug, 3. to review

#52881 [stable30] fix(ratelimit): Allow to bypass rate-limit from bruteforce allowlist
  build/psalm-baseline.xml
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/RateLimitingMiddleware.php
  lib/private/Security/Bruteforce/Throttler.php
  lib/private/Security/Ip/BruteforceAllowList.php
  tests/lib/AppFramework/Middleware/Security/RateLimitingMiddlewareTest.php
  tests/lib/Security/Bruteforce/ThrottlerTest.php
  tests/lib/Security/Ip/BruteforceAllowListTest.php
Labels: enhancement, 3. to review

#52516 [stable30] fix: Create `download` attribute when toggling checkbox
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/3821-3821.js
  dist/3821-3821.js.map
  dist/3821-3821.js.map.license
  dist/7248-7248.js
  dist/7248-7248.js.license
  dist/7248-7248.js.map
  dist/7248-7248.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request

#52893 chore: remove files file templates deprecated since v18 and provided by richdocuments
  apps/files/lib/AppInfo/Application.php
  build/psalm-baseline.xml
  core/templates/filetemplates/template.odp
  core/templates/filetemplates/template.ods
  core/templates/filetemplates/template.odt
Labels: 3. to review, feature: files, ♻️ refactor

#52821 fix(dav): handle uploading folders with names of existing file for file drop plugin
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/appinfo/v2/publicremote.php
  apps/dav/lib/Files/Sharing/FilesDropPlugin.php
  apps/dav/tests/unit/Files/Sharing/FilesDropPluginTest.php
  build/integration/filesdrop_features/filesdrop.feature
Labels: bug, 3. to review, feature: sharing, feature: dav

#52905 test: restore .htaccess file after running unit tests
  autotest.sh
Labels: 3. to review, tests

#52911 chore: deprecate OC_Helper::copyr
  build/psalm-baseline.xml
  lib/private/Installer.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, pending documentation, ♻️ refactor

#52918 test: Migrate settings and provisioning_api to PHPUnit10
  apps/provisioning_api/tests/CapabilitiesTest.php
  apps/provisioning_api/tests/Controller/AppConfigControllerTest.php
  apps/provisioning_api/tests/Controller/AppsControllerTest.php
  apps/provisioning_api/tests/Controller/GroupsControllerTest.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  apps/provisioning_api/tests/Middleware/ProvisioningApiMiddlewareTest.php
  apps/settings/tests/Activity/SecurityFilterTest.php
  apps/settings/tests/Activity/SecurityProviderTest.php
  apps/settings/tests/Activity/SecuritySettingTest.php
  apps/settings/tests/AppInfo/ApplicationTest.php
  apps/settings/tests/Controller/AppSettingsControllerTest.php
  apps/settings/tests/Controller/AuthSettingsControllerTest.php
  apps/settings/tests/Controller/CheckSetupControllerTest.php
  apps/settings/tests/Controller/DelegationControllerTest.php
  apps/settings/tests/Controller/MailSettingsControllerTest.php
  apps/settings/tests/Controller/TwoFactorSettingsControllerTest.php
  apps/settings/tests/Controller/UsersControllerTest.php
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  apps/settings/tests/Middleware/SubadminMiddlewareTest.php
  apps/settings/tests/Settings/Admin/MailTest.php
  apps/settings/tests/Settings/Admin/SecurityTest.php
  apps/settings/tests/Settings/Admin/ServerTest.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  apps/settings/tests/Settings/Personal/Security/AuthtokensTest.php
  apps/settings/tests/Settings/Personal/Security/PasswordTest.php
  apps/settings/tests/SetupChecks/AppDirsWithDifferentOwnerTest.php
  apps/settings/tests/SetupChecks/CodeIntegrityTest.php
  apps/settings/tests/SetupChecks/DataDirectoryProtectedTest.php
  apps/settings/tests/SetupChecks/ForwardedForHeadersTest.php
  apps/settings/tests/SetupChecks/LoggingLevelTest.php
  apps/settings/tests/SetupChecks/OcxProvicersTest.php
  apps/settings/tests/SetupChecks/PhpDefaultCharsetTest.php
  apps/settings/tests/SetupChecks/PhpOutputBufferingTest.php
  apps/settings/tests/SetupChecks/SecurityHeadersTest.php
  apps/settings/tests/SetupChecks/SupportedDatabaseTest.php
  apps/settings/tests/SetupChecks/WellKnownUrlsTest.php
  apps/settings/tests/UserMigration/AccountMigratorTest.php
Labels: 3. to review, tests

#52912 chore!: remove legacy functions from `OC_Helper` deprecated before v10
  lib/private/legacy/OC_Helper.php
  lib/public/Template.php
  tests/lib/Files/FilesystemTest.php
  tests/lib/Files/Storage/CommonTest.php
  tests/lib/Files/Storage/HomeTest.php
  tests/lib/Files/Storage/LocalTest.php
  tests/lib/Files/Storage/Wrapper/QuotaTest.php
  tests/lib/Files/Storage/Wrapper/WrapperTest.php
  tests/lib/FilesTest.php
  tests/lib/HelperStorageTest.php
  tests/lib/LegacyHelperTest.php
  tests/lib/Preview/OfficeTest.php
  tests/lib/TempManagerTest.php
  tests/lib/UtilTest.php
Labels: 3. to review, technical debt, pending documentation, ♻️ refactor

#52890 chore: move streamCopy implementation from `OC_Helper` to `OCP\Files`
  apps/dav/lib/Connector/Sabre/File.php
  apps/files_versions/lib/Storage.php
  build/psalm-baseline.xml
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/LocalTempFileTrait.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/private/Files/View.php
  lib/private/legacy/OC_Helper.php
  lib/public/Files.php
Labels: 3. to review, ♻️ refactor

#50591 [stable31] fix(files_sharing): Disable folder upload on file drop shares for now
  apps/files/src/views/FilesList.vue
  apps/files_sharing/src/views/FilesViewFileDropEmptyContent.vue
  cypress/e2e/files_sharing/public-share/view_file-drop.cy.ts
  dist/201-201.js
  dist/201-201.js.license
  dist/201-201.js.map
  dist/201-201.js.map.license
  dist/9087-9087.js
  dist/9087-9087.js.map
  dist/9087-9087.js.map.license
  dist/files-main.js
  dist/files-main.js.map
  dist/files_sharing-init-public.js
  dist/files_sharing-init-public.js.map
Labels: bug, 3. to review, feature: sharing, backport-request, 31-feedback

#52937 fix(files_versions): only close stream if still open, fixing S3
  apps/files_versions/lib/Storage.php
Labels: bug, 3. to review, feature: versions, feature: object storage

#52848 fix: Remove deprecated getters in IServerContainer
  build/psalm-baseline.xml
  build/rector.php
  lib/private/Server.php
  lib/private/Share20/ProviderFactory.php
  lib/public/IServerContainer.php
  lib/public/Security/IContentSecurityPolicyManager.php
  lib/public/Share/IProviderFactory.php
  tests/lib/Files/Cache/CacheTest.php
  tests/lib/Files/FilesystemTest.php
  tests/lib/Files/Node/HookConnectorTest.php
  tests/lib/Files/Utils/ScannerTest.php
  tests/lib/Files/ViewTest.php
  tests/lib/Traits/MountProviderTrait.php
Labels: 3. to review, technical debt

#52901 chore(files): remove dead code from the helper class
  apps/files/lib/Helper.php
  apps/files/tests/HelperTest.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  build/psalm-baseline.xml
Labels: 3. to review, ♻️ refactor

#52503 fix(files_sharing): Filter own shares that are reshares
  apps/files_sharing/lib/MountProvider.php
  build/integration/files_features/transfer-ownership.feature
Labels: bug, 3. to review, backport-request

#52930 chore: deprecate `OC_Helper::isReadOnlyConfigEnabled`
  lib/base.php
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_Util.php
Labels: 3. to review, technical debt, pending documentation, ♻️ refactor

#50157 feat(UserMountCache): Emit events for added, removed and updated mounts
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Config/UserMountCache.php
  lib/public/Files/Config/Event/UserMountAddedEvent.php
  lib/public/Files/Config/Event/UserMountRemovedEvent.php
  lib/public/Files/Config/Event/UserMountUpdatedEvent.php
  tests/lib/Files/Config/UserMountCacheTest.php
Labels: enhancement, 3. to review, pending documentation

#52879 Add command to clear dav's photo cache
  apps/dav/appinfo/info.xml
  apps/dav/appinfo/v1/carddav.php
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/CardDAV/PhotoCache.php
  apps/dav/lib/Command/ClearContactsPhotoCache.php
  apps/dav/lib/Server.php
  lib/private/Repair.php
  lib/private/Repair/NC16/CleanupCardDAVPhotoCache.php
Labels: enhancement, 3. to review

#52514 feat: only get template fields once selected
  apps/files/appinfo/routes.php
  apps/files/lib/Controller/TemplateController.php
  apps/files/openapi.json
  apps/files/src/services/Templates.js
  apps/files/src/views/TemplatePicker.vue
  dist/4052-4052.js
  dist/4052-4052.js.license
  dist/4052-4052.js.map
  dist/4052-4052.js.map.license
  dist/7950-7950.js
  dist/7950-7950.js.map
  dist/7950-7950.js.map.license
  dist/files-init.js
  dist/files-init.js.map
  lib/private/Files/Template/TemplateManager.php
  lib/public/Files/Template/BeforeGetTemplatesEvent.php
  lib/public/Files/Template/ITemplateManager.php
  openapi.json
Labels: enhancement, 3. to review, feature: files, javascript, php, pending documentation, performance 🚀, feature: templates

#52859 fix: Throw exception in PreviewManager when preview is not available
  lib/private/PreviewManager.php
Labels: 4. to release, backport-request

#52982 chore: Set correct version for new UserMount events
  lib/public/Files/Config/Event/UserMountAddedEvent.php
  lib/public/Files/Config/Event/UserMountRemovedEvent.php
  lib/public/Files/Config/Event/UserMountUpdatedEvent.php
Labels: 3. to review

#52972 fix(SetupManager): Include home and root providers when registering mounts
  lib/private/Files/Config/MountProviderCollection.php
  lib/private/Files/SetupManager.php
Labels: bug, 3. to review, performance 🚀

#52943 feat(Http): Add RequestHeader attribute
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/public/AppFramework/Http/Attribute/RequestHeader.php
Labels: enhancement, 3. to review, pending documentation

#52933 test: Migrate files_versions to PHPUnit 10
  apps/files_versions/tests/BackgroundJob/ExpireVersionsTest.php
  apps/files_versions/tests/Command/CleanupTest.php
  apps/files_versions/tests/Command/ExpireTest.php
  apps/files_versions/tests/Controller/PreviewControllerTest.php
  apps/files_versions/tests/ExpirationTest.php
  apps/files_versions/tests/StorageTest.php
  apps/files_versions/tests/VersioningTest.php
  apps/files_versions/tests/Versions/VersionManagerTest.php
Labels: 3. to review, tests

#52927 test: Prepare files_external for PHPUnit10
  apps/files_external/tests/Auth/AuthMechanismTest.php
  apps/files_external/tests/Auth/Password/GlobalAuthTest.php
  apps/files_external/tests/Backend/BackendTest.php
  apps/files_external/tests/Backend/LegacyBackendTest.php
  apps/files_external/tests/Command/ApplicableTest.php
  apps/files_external/tests/Command/CommandTestCase.php
  apps/files_external/tests/Command/ListCommandTest.php
  apps/files_external/tests/Config/UserPlaceholderHandlerTest.php
  apps/files_external/tests/Controller/AjaxControllerTest.php
  apps/files_external/tests/Controller/GlobalStoragesControllerTest.php
  apps/files_external/tests/Controller/StoragesControllerTestCase.php
  apps/files_external/tests/Controller/UserStoragesControllerTest.php
  apps/files_external/tests/DefinitionParameterTest.php
  apps/files_external/tests/FrontendDefinitionTraitTest.php
  apps/files_external/tests/LegacyDependencyCheckPolyfillTest.php
  apps/files_external/tests/Listener/StorePasswordListenerTest.php
  apps/files_external/tests/OwnCloudFunctionsTest.php
  apps/files_external/tests/PersonalMountTest.php
  apps/files_external/tests/Service/BackendServiceTest.php
  apps/files_external/tests/Service/DBConfigServiceTest.php
  apps/files_external/tests/Service/GlobalStoragesServiceTest.php
  apps/files_external/tests/Service/StoragesServiceTestCase.php
  apps/files_external/tests/Service/UserGlobalStoragesServiceTest.php
  apps/files_external/tests/Service/UserStoragesServiceTest.php
  apps/files_external/tests/Settings/AdminTest.php
  apps/files_external/tests/Settings/SectionTest.php
  apps/files_external/tests/Storage/Amazons3MultiPartTest.php
  apps/files_external/tests/Storage/Amazons3Test.php
  apps/files_external/tests/Storage/FtpTest.php
  apps/files_external/tests/Storage/OwncloudTest.php
  apps/files_external/tests/Storage/SFTP_KeyTest.php
  apps/files_external/tests/Storage/SftpTest.php
  apps/files_external/tests/Storage/SmbTest.php
  apps/files_external/tests/Storage/SwiftTest.php
  apps/files_external/tests/Storage/WebdavTest.php
  apps/files_external/tests/StorageConfigTest.php
Labels: 3. to review, tests

#53005 fix(theming): Instead of expecting a warning handle it properly
  apps/theming/lib/IconBuilder.php
  apps/theming/tests/IconBuilderTest.php
Labels: bug, 3. to review, backport-request, feature: theming

#53020 [stable23] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53019 [stable28] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53018 [stable22] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53017 [stable30] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53016 [stable29] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53014 [stable27] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53015 [stable25] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53013 [stable31] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53012 [master] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53011 [stable26] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53010 [stable24] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#52932 test: Speed up comments test
  lib/private/DB/Adapter.php
  lib/private/DB/AdapterOCI8.php
  lib/private/DB/AdapterPgSql.php
  lib/private/DB/Connection.php
  tests/lib/Comments/ManagerTest.php
Labels: 3. to review, feature: comments

#53007 test: Migrate theming and sharebymail to PHPUnit10
  apps/sharebymail/tests/CapabilitiesTest.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  apps/theming/tests/CapabilitiesTest.php
  apps/theming/tests/Controller/IconControllerTest.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  apps/theming/tests/Controller/UserThemeControllerTest.php
  apps/theming/tests/IconBuilderTest.php
  apps/theming/tests/ImageManagerTest.php
  apps/theming/tests/Service/ThemesServiceTest.php
  apps/theming/tests/ServicesTest.php
  apps/theming/tests/Settings/AdminSectionTest.php
  apps/theming/tests/Settings/AdminTest.php
  apps/theming/tests/Settings/PersonalTest.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
  apps/theming/tests/Themes/DarkHighContrastThemeTest.php
  apps/theming/tests/Themes/DarkThemeTest.php
  apps/theming/tests/Themes/DefaultThemeTest.php
  apps/theming/tests/Themes/DyslexiaFontTest.php
  apps/theming/tests/Themes/HighContrastThemeTest.php
  apps/theming/tests/ThemingDefaultsTest.php
  apps/theming/tests/UtilTest.php
Labels: 3. to review, tests

#52810 fix: Move CSRF check from base to PublicAuth for public.php
  apps/dav/appinfo/v2/publicremote.php
  apps/dav/lib/Connector/Sabre/PublicAuth.php
  apps/dav/tests/unit/Connector/Sabre/PublicAuthTest.php
  apps/files_sharing/lib/DefaultPublicShareTemplateProvider.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
  cypress/e2e/files_sharing/public-share/header-menu.cy.ts
  lib/base.php
Labels: bug, 3. to review, feature: sharing, feature: dav, php

#52833 fix(settings): Send update request when clearing user manager
  apps/settings/src/components/Users/UserRow.vue
  apps/settings/src/store/users.js
  cypress/e2e/settings/users_manager.cy.ts
  cypress/e2e/settings/users_modify.cy.ts
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: bug, 3. to review, backport-request, feature: users and groups

#53045 feat(IUser): add `getQuotaBytes` method to get machine readable quota
  lib/private/Files/SetupManager.php
  lib/private/User/LazyUser.php
  lib/private/User/User.php
  lib/private/legacy/OC_Helper.php
  lib/private/legacy/OC_Util.php
  lib/public/IUser.php
  tests/lib/User/UserTest.php
Labels: enhancement, 3. to review, pending documentation

#53056 GH action sync
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/files-external-ftp.yml
  .github/workflows/files-external-s3.yml
  .github/workflows/files-external-sftp.yml
  .github/workflows/files-external-smb.yml
  .github/workflows/files-external-webdav.yml
  .github/workflows/files-external.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/object-storage-azure.yml
  .github/workflows/object-storage-s3.yml
  .github/workflows/object-storage-swift.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-memcached.yml
  .github/workflows/phpunit-mysql-sharding.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-nodb.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, CI

#53067 [stable28] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53066 [stable29] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53065 [stable23] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53064 [stable22] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53063 [stable30] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53062 [stable26] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53061 [stable25] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53060 [stable27] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53059 [stable24] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53058 [master] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53071 fix(autoloader): Fix location of class to be autoloadable
  core/Listener/FeedBackHandler.php
  core/ajax/update.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review, technical debt

#52914 fix: hide guests group from principal backend
  apps/dav/lib/DAV/GroupPrincipalBackend.php
Labels: bug, 3. to review

#53069 ci(gh): Sync actions
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-outdated-3rdparty.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-pull-3rdparty.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/files-external-ftp.yml
  .github/workflows/files-external-s3.yml
  .github/workflows/files-external-sftp.yml
  .github/workflows/files-external-smb-kerberos.yml
  .github/workflows/files-external-smb.yml
  .github/workflows/files-external-webdav.yml
  .github/workflows/files-external.yml
  .github/workflows/integration-dav.yml
  .github/workflows/integration-litmus.yml
  .github/workflows/integration-s3-primary.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/object-storage-azure.yml
  .github/workflows/object-storage-s3.yml
  .github/workflows/object-storage-swift.yml
  .github/workflows/openapi.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-32bits.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-memcached.yml
  .github/workflows/phpunit-mysql-sharding.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-nodb.yml
  .github/workflows/phpunit-object-store-primary.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
  .github/workflows/stale.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-cacert-bundle.yml
  .github/workflows/update-code-signing-crl.yml
  .github/workflows/update-min-supported-desktop.yml
Labels: 3. to review, CI

#52897 Replace "remove" wording with "delete"
  apps/settings/src/components/GroupListItem.vue
  cypress/e2e/settings/users_groups.cy.ts
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, design, 3. to review, feature: users and groups

#53117 [stable31] ci: Update comments and correctly skip the "pull 3rdparty" command
  .github/workflows/block-outdated-3rdparty.yml
  .github/workflows/command-pull-3rdparty.yml
  .github/workflows/files-external-s3.yml
  .github/workflows/generate-release-changelog.yml
Labels: 3. to review, CI

#53110 [stable30] Sync workflow updates
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-outdated-3rdparty.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-pull-3rdparty.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/files-external-ftp.yml
  .github/workflows/files-external-s3.yml
  .github/workflows/files-external-sftp.yml
  .github/workflows/files-external-smb-kerberos.yml
  .github/workflows/files-external-smb.yml
  .github/workflows/files-external-webdav.yml
  .github/workflows/files-external.yml
  .github/workflows/generate-release-changelog.yml
  .github/workflows/integration-dav.yml
  .github/workflows/integration-litmus.yml
  .github/workflows/integration-s3-primary.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/object-storage-azure.yml
  .github/workflows/object-storage-s3.yml
  .github/workflows/object-storage-swift.yml
  .github/workflows/openapi.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-32bits.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-memcached.yml
  .github/workflows/phpunit-mysql-sharding.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-nodb.yml
  .github/workflows/phpunit-object-store-primary.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
  .github/workflows/stale.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/update-cacert-bundle.yml
  .github/workflows/update-code-signing-crl.yml
Labels: 3. to review, CI

#53124 fix(log): map all warnings to warn log level, notice to info
  lib/private/Log/ErrorHandler.php
Labels: bug, 3. to review, backport-request

#53120 perf: improve query to determine which users need a background scan
  apps/files/lib/BackgroundJob/ScanFiles.php
Labels: 3. to review

#52945 chore: Remove useless legacy autoloader for tests
  lib/autoloader.php
  lib/base.php
  tests/lib/AutoLoaderTest.php
  tests/lib/Files/Storage/Wrapper/QuotaTest.php
Labels: 3. to review, pending documentation

#53150 test: Migrate User LDAP to phpunit 10
  apps/user_ldap/tests/AccessTest.php
  apps/user_ldap/tests/ConfigurationTest.php
  apps/user_ldap/tests/ConnectionTest.php
  apps/user_ldap/tests/GroupLDAPPluginTest.php
  apps/user_ldap/tests/Group_LDAPTest.php
  apps/user_ldap/tests/HelperTest.php
  apps/user_ldap/tests/Integration/Lib/IntegrationTestAttributeDetection.php
  apps/user_ldap/tests/Jobs/CleanUpTest.php
  apps/user_ldap/tests/Jobs/SyncTest.php
  apps/user_ldap/tests/LDAPGroupPluginDummy.php
  apps/user_ldap/tests/LDAPProviderTest.php
  apps/user_ldap/tests/LDAPTest.php
  apps/user_ldap/tests/LDAPUserPluginDummy.php
  apps/user_ldap/tests/Mapping/AbstractMappingTestCase.php
  apps/user_ldap/tests/Mapping/GroupMappingTest.php
  apps/user_ldap/tests/Mapping/UserMappingTest.php
  apps/user_ldap/tests/Migration/AbstractUUIDFixTestCase.php
  apps/user_ldap/tests/Migration/UUIDFixGroupTest.php
  apps/user_ldap/tests/Migration/UUIDFixInsertTest.php
  apps/user_ldap/tests/Migration/UUIDFixUserTest.php
  apps/user_ldap/tests/Service/BirthdateParserServiceTest.php
  apps/user_ldap/tests/Service/UpdateGroupsServiceTest.php
  apps/user_ldap/tests/Settings/AdminTest.php
  apps/user_ldap/tests/Settings/SectionTest.php
  apps/user_ldap/tests/User/DeletedUsersIndexTest.php
  apps/user_ldap/tests/User/ManagerTest.php
  apps/user_ldap/tests/User/OfflineUserTest.php
  apps/user_ldap/tests/User/UserTest.php
  apps/user_ldap/tests/UserLDAPPluginTest.php
  apps/user_ldap/tests/User_LDAPTest.php
  apps/user_ldap/tests/User_ProxyTest.php
  apps/user_ldap/tests/WizardTest.php
Labels: 3. to review, tests

#52996 fix(node): emit hooks on `Node::copy()`
  apps/files/lib/Listener/SyncLivePhotosListener.php
  lib/private/Files/View.php
Labels: bug, 3. to review, feature: filesystem, backport-request

#53047 fix: recommended apps button test
  core/src/components/setup/RecommendedApps.vue
  cypress/e2e/core/setup.ts
  dist/core-recommendedapps.js
  dist/core-recommendedapps.js.map
Labels: bug, 3. to review, backport-request, regression

#53171 fix(files): do nothing if `view local` dialog was just closed
  apps/files/src/actions/openLocallyAction.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: bug, 3. to review, backport-request, feature: files

#41065 fix(dashboard): performance and refactoring
  apps/dashboard/src/DashboardApp.vue
  dist/dashboard-main.js
  dist/dashboard-main.js.map
Labels: bug, 3. to review, performance 🚀, feature: dashboard

#53175 test: Migrate Federation and Files_Trashbin to PHPUnit 10
  apps/federation/tests/BackgroundJob/GetSharedSecretTest.php
  apps/federation/tests/BackgroundJob/RequestSharedSecretTest.php
  apps/federation/tests/Controller/OCSAuthAPIControllerTest.php
  apps/federation/tests/Controller/SettingsControllerTest.php
  apps/federation/tests/DAV/FedAuthTest.php
  apps/federation/tests/DbHandlerTest.php
  apps/federation/tests/Settings/AdminTest.php
  apps/federation/tests/SyncFederationAddressbooksTest.php
  apps/federation/tests/TrustedServersTest.php
  apps/files_trashbin/tests/BackgroundJob/ExpireTrashTest.php
  apps/files_trashbin/tests/CapabilitiesTest.php
  apps/files_trashbin/tests/Command/CleanUpTest.php
  apps/files_trashbin/tests/Command/ExpireTest.php
  apps/files_trashbin/tests/Controller/PreviewControllerTest.php
  apps/files_trashbin/tests/ExpirationTest.php
  apps/files_trashbin/tests/Sabre/TrashbinPluginTest.php
  apps/files_trashbin/tests/StorageTest.php
  apps/files_trashbin/tests/TrashbinTest.php
  lib/private/User/Manager.php
Labels: 3. to review, tests

#53147 fix(files_versions): "undefined restored" on restore
  apps/files_versions/src/views/VersionTab.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: 3. to review, backport-request, feature: versions

#53179 test: Migrate federated file sharing to PHPUnit 10
  apps/federatedfilesharing/tests/AddressHandlerTest.php
  apps/federatedfilesharing/tests/Controller/MountPublicLinkControllerTest.php
  apps/federatedfilesharing/tests/Controller/RequestHandlerControllerTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federatedfilesharing/tests/NotificationsTest.php
  apps/federatedfilesharing/tests/Settings/AdminTest.php
  apps/federatedfilesharing/tests/TestCase.php
  apps/federatedfilesharing/tests/TokenHandlerTest.php
  apps/files/tests/Activity/Filter/GenericTest.php
  apps/files/tests/Activity/ProviderTest.php
  apps/files/tests/Activity/Setting/GenericTest.php
  apps/files/tests/AdvancedCapabilitiesTest.php
  apps/files/tests/BackgroundJob/DeleteOrphanedItemsJobTest.php
  apps/files/tests/BackgroundJob/ScanFilesTest.php
  apps/files/tests/Command/DeleteOrphanedFilesTest.php
  apps/files/tests/Controller/ApiControllerTest.php
  apps/files/tests/Controller/ConversionApiControllerTest.php
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files/tests/HelperTest.php
  apps/files/tests/Service/TagServiceTest.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  tests/lib/TextProcessing/TextProcessingTest.php
Labels: 3. to review, tests

#53188 [stable22] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53190 [stable24] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies
