Repository nextcloud/server, pull requests merged in 2025-07, with the labels that each got.

#53304 fix(files_sharing): Hide own reshares
  apps/files/lib/Command/TransferOwnership.php
  apps/files/lib/Service/OwnershipTransferService.php
  apps/files_sharing/lib/MountProvider.php
  build/integration/features/bootstrap/CommandLineContext.php
  build/integration/files_features/transfer-ownership.feature
Labels: bug, 3. to review, backport-request

#53648 fix: don't try to get fileid for non exising nodes when serializing events file
  lib/public/EventDispatcher/JsonSerializer.php
Labels: 3. to review, backport-request, pending documentation

#53429 feat(settings): simplify OPcache checks
  apps/settings/lib/SetupChecks/PhpOpcacheSetup.php
Labels: enhancement, 3. to review, feature: settings, feedback-requested

#53671 feat(files_sharing): allow viewing files with download disabled
  apps/dav/lib/DAV/ViewOnlyPlugin.php
  apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
  apps/files/lib/Controller/ApiController.php
  apps/files/tests/Controller/ApiControllerTest.php
  apps/files_sharing/lib/Controller/PublicPreviewController.php
  apps/files_sharing/tests/Controller/PublicPreviewControllerTest.php
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/components/AdminSettingsSharingForm.vue
  build/integration/features/bootstrap/SharingContext.php
  build/integration/sharing_features/sharing-v1-part2.feature
  core/Controller/PreviewController.php
  cypress/e2e/files_sharing/files-download.cy.ts
  cypress/e2e/files_versions/version_download.cy.ts
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
  lib/private/Share20/Manager.php
  lib/private/Share20/Share.php
  lib/public/Share/IManager.php
  lib/public/Share/IShare.php
  tests/Core/Controller/PreviewControllerTest.php
Labels: enhancement, 2. developing, feature: sharing, feature: dav, feature: files, pending documentation

#53715 [stable31] fix(files_sharing): add mime fallback to public preview too
  apps/files_sharing/lib/Controller/PublicPreviewController.php
  apps/files_sharing/openapi.json
  apps/files_sharing/tests/Controller/PublicPreviewControllerTest.php
Labels: bug, 3. to review, feature: sharing, feature: files, regression, feature: previews and thumbnails

#53772 [stable31] fix(cypress): add missing PublicShareUtils.ts
  cypress/e2e/files_sharing/public-share/PublicShareUtils.ts
Labels: 3. to review, CI

#53764 Feat(taskprocessing): add toggle for AI guest restriction
  apps/settings/lib/Controller/AISettingsController.php
  apps/settings/lib/Settings/Admin/ArtificialIntelligence.php
  apps/settings/src/components/AdminAI.vue
  dist/settings-vue-settings-admin-ai.js
  dist/settings-vue-settings-admin-ai.js.map
  lib/private/TaskProcessing/Manager.php
  lib/public/TaskProcessing/IManager.php
  psalm.xml
  tests/lib/TaskProcessing/TaskProcessingTest.php
Labels: backport-request

#53418 Fix TimedJob execution time to allow job execution exactly when scheduled
  apps/dav/lib/BackgroundJob/UserStatusAutomation.php
  apps/dav/lib/Listener/UserEventsListener.php
  apps/dav/tests/unit/DAV/Listener/UserEventsListenerTest.php
  apps/user_status/lib/BackgroundJob/ClearOldStatusesBackgroundJob.php
Labels: bug, 3. to review, backport-request, feedback-requested

#53787 fix(l10n): our default language is American English so adjust the spelling
  lib/private/Profile/ProfileManager.php
Labels: bug, 3. to review, feature: language/translations (l10n/i18n)

#53788 fix(profile): add max width for the user actions
  apps/profile/src/views/Profile.vue
  dist/profile-main.js
  dist/profile-main.js.map
Labels: bug, 3. to review, backport-request, feature: profile

#53800 [master] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53804 [stable31] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53805 [stable27] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53806 [stable29] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53808 [stable23] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53820 feat(files): add "search everywhere" button within the filters row
  apps/files/src/components/FileListFilter/FileListFilterToSearch.vue
  apps/files/src/filters/FilenameFilter.ts
  apps/files/src/filters/SearchFilter.ts
  apps/files/src/init.ts
  apps/files/src/store/search.ts
  cypress/e2e/files/search.cy.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: enhancement, 3. to review, feature: files, 🍂 2025-Autumn

#53718 [master] Fix npm audit
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.license
  dist/dav-settings-personal-availability.js.map
  package-lock.json
Labels: 3. to review, dependencies

#53832 chore: use constants for metadata
  apps/files_versions/lib/Listener/VersionAuthorListener.php
  apps/files_versions/lib/Sabre/Plugin.php
Labels: enhancement, regression

#53845 chore(AccountManager): adjust code style for cs-fixer
  lib/private/Accounts/AccountManager.php
Labels: 3. to review, ♻️ refactor

#53759 [TaskProcessing] Add audio-to-audio chat task type
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/TaskProcessing/Manager.php
  lib/public/TaskProcessing/TaskTypes/AudioToAudioChat.php
Labels: enhancement, 3. to review, feature: text processing

#53833 feat(files_versions): get revision for a node
  apps/files_versions/lib/Listener/FileEventsListener.php
  apps/files_versions/lib/Listener/VersionAuthorListener.php
  apps/files_versions/lib/Versions/IVersionBackend.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/lib/Versions/VersionManager.php
Labels: enhancement, 3. to review, pending documentation

#53767 fix(files_reminders): Don't load if disabled for user
  apps/files_reminders/lib/Listener/LoadAdditionalScriptsListener.php
Labels: bug, 3. to review, backport-request, feature: files, performance 🚀

#53840 fix(federatedfilesharing): Fix external share being deleted when accepting share
  apps/federatedfilesharing/src/external.js
  dist/federatedfilesharing-external.js
  dist/federatedfilesharing-external.js.map
Labels: bug, 3. to review, backport-request

#53523 chore: Cleanup DIContainer class
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
  apps/settings/tests/AppInfo/ApplicationTest.php
  build/psalm-baseline.xml
  lib/private/AppFramework/App.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Http/Dispatcher.php
  lib/private/AppFramework/Http/Output.php
  lib/private/AppFramework/Middleware/Security/SameSiteCookieMiddleware.php
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/EventDispatcher/EventDispatcher.php
  lib/private/EventDispatcher/ServiceEventListener.php
  lib/private/Server.php
  lib/private/Support/CrashReport/Registry.php
  tests/lib/AppFramework/AppTest.php
  tests/lib/AppFramework/DependencyInjection/DIContainerTest.php
  tests/lib/Support/CrashReport/RegistryTest.php
  tests/lib/TestCase.php
Labels: 2. developing, technical debt

#53863 Revert "fix(dav): only consider user's principal for unsharing entries"
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: bug, 3. to review, backport-request

#53892 fix: Move getInstallPath to Installer class
  lib/private/Installer.php
  lib/private/legacy/OC_App.php
  lib/private/legacy/OC_Util.php
  tests/lib/InstallerTest.php
Labels: 3. to review, technical debt

#53893 Migrate calls to OC_App::loadApp to the IAppManager
  apps/dav/lib/AppInfo/Application.php
  apps/dav/tests/unit/bootstrap.php
  apps/user_ldap/tests/Integration/ExceptionOnLostConnection.php
  apps/user_status/tests/bootstrap.php
  build/psalm-baseline.xml
  core/Command/Db/ConvertType.php
  lib/private/Files/SetupManager.php
  lib/private/Files/SetupManagerFactory.php
  ocs/v1.php
  tests/bootstrap.php
  tests/lib/Traits/EncryptionTrait.php
Labels: 2. developing, technical debt

#53501 fix: Fix theming for disabled accounts
  .github/workflows/integration-sqlite.yml
  build/integration/config/behat.yml
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/Theming.php
  build/integration/theming_features/theming.feature
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/User/DisabledUserException.php
  lib/private/User/Session.php
  lib/private/legacy/OC_User.php
Labels: bug, 3. to review, backport-request, feature: theming

#53904 fix(comments): Adjust interface with implementation
  lib/public/Comments/ICommentsManager.php
  tests/lib/Comments/FakeManager.php
Labels: bug, 3. to review, feature: comments, pending documentation

#53887 fix: force lowercase emails
  apps/provisioning_api/lib/Controller/AUserDataOCSController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  build/psalm-baseline.xml
  core/Command/User/Setting.php
  lib/private/User/User.php
Labels: bug, 2. developing, 3. to review, feature: users and groups, feature: emails

#53857 fix(theming): Correctly generate CSS for font themes
  apps/theming/lib/Controller/ThemingController.php
Labels: backport-request

#53860 [stable30] fix(federatedfilesharing): Fix external share being deleted when accepting share
  apps/federatedfilesharing/src/external.js
  dist/federatedfilesharing-external.js
  dist/federatedfilesharing-external.js.map
Labels: bug, 3. to review

#53859 feat: add Context Chat OCP API
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/ContextChat/ContentManager.php
  lib/private/Server.php
  lib/public/ContextChat/ContentItem.php
  lib/public/ContextChat/Events/ContentProviderRegisterEvent.php
  lib/public/ContextChat/IContentManager.php
  lib/public/ContextChat/IContentProvider.php
  lib/public/ContextChat/Type/UpdateAccessOp.php
  psalm.xml
Labels: enhancement, 3. to review, php

#53961 [stable31] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53959 [stable26] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53958 [stable22] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53960 [stable25] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53956 [stable27] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53957 [stable29] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53955 [stable30] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53954 [master] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#53449 feat(lexicon): configurable presets
  core/Command/Config/Preset.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppConfig.php
  lib/private/Config/ConfigManager.php
  lib/private/Config/UserConfig.php
  lib/unstable/Config/Lexicon/ConfigLexiconEntry.php
  lib/unstable/Config/Lexicon/Preset.php
  tests/lib/AppConfigTest.php
  tests/lib/Config/LexiconTest.php
  tests/lib/Config/TestConfigLexicon_E.php
Labels: enhancement, 3. to review, developer experience

#53964 fix: Fix clearing unified search when modal is closed
  core/src/components/UnifiedSearch/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: bug, 3. to review, backport-request, feature: search

#53984 fix(files): show hidden new file name warning
  apps/files/src/components/NewNodeDialog.vue
  dist/files-init.js
  dist/files-init.js.map
Labels: enhancement, 3. to review, feature: files, papercut

#53986 fix(update): Correctly trigger update for auto-disabled local apps
  lib/private/Updater.php
Labels: bug, 3. to review, backport-request, feature: install and update

#54016 fix: group imip log messages by removing principal and uri
  lib/private/Calendar/Manager.php
  tests/lib/Calendar/ManagerTest.php
Labels: bug, 4. to release, backport-request

#54057 enforce comma-dangle and vue/html-self-closing
  .eslintrc.js
  apps/dav/src/components/AbsenceForm.vue
  apps/dav/src/components/ExampleContentDownloadButton.vue
  apps/dav/src/components/ExampleEventSettings.vue
  apps/dav/src/settings-example-content.js
  apps/dav/src/views/ExampleContentSettingsSection.vue
  dist/dav-settings-example-content.js
  dist/dav-settings-example-content.js.map
  dist/dav-settings-personal-availability.js
  dist/dav-settings-personal-availability.js.map
Labels: 3. to review, developer experience

#54055 fix(files_sharing): restore state when updating share failed
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/views/SharingDetailsTab.vue
  dist/2210-2210.js
  dist/2210-2210.js.map
  dist/2210-2210.js.map.license
  dist/9780-9780.js
  dist/9780-9780.js.license
  dist/9780-9780.js.map
  dist/9780-9780.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#54086 chore(OCP): Migrate lib/Config/ to new attributes
  build/psalm/OcpSinceChecker.php
  lib/public/Config/BeforePreferenceDeletedEvent.php
  lib/public/Config/BeforePreferenceSetEvent.php
  lib/public/Config/Exceptions/IncorrectTypeException.php
  lib/public/Config/Exceptions/TypeConflictException.php
  lib/public/Config/Exceptions/UnknownKeyException.php
  lib/public/Config/IUserConfig.php
  lib/public/Config/Lexicon/Entry.php
  lib/public/Config/Lexicon/ILexicon.php
  lib/public/Config/Lexicon/Preset.php
  lib/public/Config/Lexicon/Strictness.php
  lib/public/Config/ValueType.php
Labels: 3. to review, technical debt

#53898 ci: test against MariaDB 11.8 (latest LTS)
  .github/workflows/phpunit-mariadb.yml
  apps/settings/lib/SetupChecks/SupportedDatabase.php
Labels: enhancement, 3. to review, pending documentation, CI

#54027 fix(ConnectionFactory): Apply Oracle connection fix to primary and replica params as well
  lib/private/DB/ConnectionFactory.php
Labels: bug, 3. to review, backport-request, feature: database

#54051 fix(session): log when ephemeral sessions are closed
  lib/private/AppFramework/Middleware/FlowV2EphemeralSessionsMiddleware.php
Labels: bug, 3. to review, backport-request

#54068 fix(cron): Fix infinite loop on ParallelAware blocked jobs
  lib/private/BackgroundJob/JobList.php
Labels: bug, 4. to release, backport-request

#53944 chore: Fix all method calls with too many arguments
  apps/dav/lib/Connector/Sabre/FilesReportPlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/encryption/lib/Session.php
  apps/files_external/lib/Command/Verify.php
  apps/files_external/lib/Controller/GlobalStoragesController.php
  apps/files_external/lib/Controller/StoragesController.php
  apps/files_external/lib/Controller/UserGlobalStoragesController.php
  apps/files_external/lib/Controller/UserStoragesController.php
  apps/files_external/lib/MountConfig.php
  build/psalm-baseline.xml
  core/Command/Config/ListConfigs.php
  lib/private/App/AppStore/Fetcher/Fetcher.php
  lib/private/Files/Filesystem.php
  lib/private/Lockdown/Filesystem/NullStorage.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  tests/Core/Command/Config/ListConfigsTest.php
Labels: 3. to review, technical debt

#54026 feat: add ICloudIdResolver
  apps/federatedfilesharing/tests/AddressHandlerTest.php
  apps/federatedfilesharing/tests/Controller/MountPublicLinkControllerTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/files_sharing/tests/External/CacheTest.php
  apps/files_sharing/tests/External/ManagerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Federation/CloudIdManager.php
  lib/private/Server.php
  lib/public/Federation/ICloudIdManager.php
  lib/public/Federation/ICloudIdResolver.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Collaboration/Collaborators/RemotePluginTest.php
  tests/lib/Federation/CloudIdManagerTest.php
Labels: enhancement, 3. to review, 🍂 2025-Autumn

#54111 chore: add type to issue templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: enhancement, 3. to review

#54064 feat(preset): add lexicon entry for custom share tokens
  core/AppInfo/ConfigLexicon.php
  core/Command/Base.php
  core/Command/Config/App/GetConfig.php
  core/Command/Config/App/SetConfig.php
  lib/private/AppConfig.php
  lib/private/Share20/Manager.php
  lib/public/Config/Lexicon/Entry.php
  lib/public/IAppConfig.php
Labels: 3. to review

#53946 Add missing methods to IShare and IShareProvider
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/sharebymail/lib/ShareByMailProvider.php
  build/psalm-baseline.xml
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/LegacyHooks.php
  lib/private/Share20/Manager.php
  lib/private/Share20/Share.php
  lib/public/Share/IShare.php
  lib/public/Share/IShareProvider.php
Labels: 3. to review, technical debt

#54082 fix(userconfig): duplicate core lexicon
  core/AppInfo/ConfigLexicon.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppFramework/Bootstrap/RegistrationContext.php
  lib/private/Config/Lexicon/CoreConfigLexicon.php
Labels: bug, 3. to review

#53746 feat(file-versions): #53151 add VersionCreatedEvent event
  apps/files_versions/composer/composer/autoload_classmap.php
  apps/files_versions/composer/composer/autoload_static.php
  apps/files_versions/lib/Events/VersionCreatedEvent.php
  apps/files_versions/lib/Versions/INeedSyncVersionBackend.php
  apps/files_versions/lib/Versions/LegacyVersionsBackend.php
  apps/files_versions/lib/Versions/VersionManager.php
Labels: enhancement, 3. to review, pending documentation

#54005 fix: Do not show password dialog when user can not validate password
  lib/private/Template/JSConfigHelper.php
Labels: bug, 3. to review, backport-request

#54119 Show nice label when searching in root
  apps/files/src/plugins/search/folderSearch.ts
  dist/files-search.js
  dist/files-search.js.map
Labels: enhancement, 3. to review, feature: search

#54085 enh(files): Replace "All folders" with "Folder tree structure"
  apps/files/src/views/folderTree.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: enhancement, 3. to review, feature: files, papercut

#54179 fix: spelling mistake
  apps/dav/lib/CalDAV/EventReader.php
Labels: 3. to review, backport-request
