Repository nextcloud/server, pull requests merged in 2025-10, with the labels that each got.

#55449 [stable28] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#55445 [stable32] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#55444 [stable22] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#51145 feat: Add appconfig to disable fixed userfolder permissions optimization
  apps/files/composer/composer/autoload_classmap.php
  apps/files/composer/composer/autoload_static.php
  apps/files/lib/AppInfo/Application.php
  apps/files/lib/ConfigLexicon.php
  apps/files_external/appinfo/info.xml
  apps/files_external/composer/composer/autoload_classmap.php
  apps/files_external/composer/composer/autoload_static.php
  apps/files_external/lib/Migration/Version1025Date20250228162604.php
  apps/files_external/lib/Service/DBConfigService.php
  apps/files_external/lib/Service/StoragesService.php
  apps/files_external/lib/Service/UserGlobalStoragesService.php
  apps/files_external/lib/Service/UserStoragesService.php
  apps/files_external/tests/Service/GlobalStoragesServiceTest.php
  apps/files_external/tests/Service/StoragesServiceTestCase.php
  apps/files_external/tests/Service/UserGlobalStoragesServiceTest.php
  apps/files_external/tests/Service/UserStoragesServiceTest.php
  cypress/e2e/files_external/StorageUtils.ts
  cypress/e2e/files_external/home-folder-root-mount-permissions.cy.ts
  lib/private/Files/Node/LazyUserFolder.php
  lib/private/Files/Node/Root.php
  lib/private/Server.php
  tests/lib/Files/Node/FileTest.php
  tests/lib/Files/Node/FolderTest.php
  tests/lib/Files/Node/HookConnectorTest.php
  tests/lib/Files/Node/IntegrationTest.php
  tests/lib/Files/Node/NodeTestCase.php
  tests/lib/Files/Node/RootTest.php
Labels: 3. to review

#55467 refactor: Remove old unused js files for federation settings
  apps/settings/js/federationscopemenu.js
  apps/settings/js/federationsettingsview.js
  apps/settings/js/settings/personalInfo.js
  apps/settings/templates/settings/personal/personal.info.php
Labels: 3. to review

#55491 chore(i18n): id -> ID
  apps/settings/src/components/AdminSettingsSharingForm.vue
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
Labels: bug, 3. to review, backport-request, feature: language/translations (l10n/i18n)

#55499 [stable30] refactor(ShareApiController): Add more error handling
  apps/files_sharing/lib/Controller/ShareAPIController.php
Labels: 3. to review, backport-request

#55475 fix(user_ldap): Fix configuration creation and copy
  apps/user_ldap/ajax/getNewServerConfigPrefix.php
Labels: 3. to review, feature: ldap, backport-request

#55522 fix(user_ldap): Do not translate technical strings
  apps/user_ldap/src/components/SettingsTabs/AdvancedTab.vue
  dist/user_ldap-main.js
  dist/user_ldap-main.js.map
Labels: bug, 3. to review, feature: ldap, javascript

#55434 fix(unified-search): Remove hard-coded search result limit
  core/AppInfo/ConfigLexicon.php
  core/Controller/UnifiedSearchController.php
  core/openapi-full.json
  core/openapi.json
  openapi.json
Labels: 3. to review, feature: search

#55472 refactor: fix psalm issues from encryption commands
  apps/encryption/lib/Command/DisableMasterKey.php
  apps/encryption/lib/Command/DropLegacyFileKey.php
  apps/encryption/lib/Command/EnableMasterKey.php
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/lib/Command/FixKeyLocation.php
  apps/encryption/lib/Command/ScanLegacyFormat.php
  apps/encryption/lib/Crypto/EncryptAll.php
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
  apps/encryption/tests/Command/TestEnableMasterKey.php
  apps/encryption/tests/Crypto/EncryptAllTest.php
  build/psalm-baseline.xml
Labels: 3. to review, technical debt

#55566 fix(IGroupManager): Use correct return type in getUserGroupIds method
  lib/private/Group/Manager.php
  lib/public/IGroupManager.php
Labels: 3. to review, technical debt

#55564 fix(files): Always return a valid mimetype
  apps/files_trashbin/lib/Trash/TrashItem.php
  lib/private/Files/Cache/CacheEntry.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Node/LazyFolder.php
  lib/private/Files/Node/Node.php
  lib/private/Files/Node/NonExistingFile.php
  lib/public/Files/Cache/ICacheEntry.php
  lib/public/Files/File.php
  lib/public/Files/FileInfo.php
Labels: bug, 3. to review

#55442 test: migrate `LoginForm` component test to vitest
  core/src/components/login/LoginForm.cy.ts
  core/src/components/login/LoginForm.vue
  core/src/tests/components/Login/LoginForm.spec.ts
  dist/core-login.js
  dist/core-login.js.map
  eslint.config.mjs
  package-lock.json
  package.json
Labels: 3. to review, tests, ♻️ refactor

#55576 fix(ldap): Fix copying and creating LDAP configuration
  apps/user_ldap/lib/Helper.php
Labels: 4. to release, feature: ldap, backport-request

#55573 fix(TaskProcessing): Make sure list command int filter parameters are parsed as ints
  core/Command/TaskProcessing/ListCommand.php
Labels: 3. to review, backport-request

#55574 chore: Explicitely mark \OC\Files\View as internal
  build/psalm-baseline.xml
  core/Command/Info/File.php
  lib/private/Files/View.php
Labels: 3. to review, technical debt

#55577 fix(RepairTree): Update files:repair-tree description
  apps/files/lib/Command/RepairTree.php
Labels: 3. to review

#55529 fix: make share recursion error more informative
  apps/files_sharing/lib/SharedStorage.php
Labels: 4. to release

#55557 refactor: use IEmailValidator.isValid instead of IMailer.validateEmailAddress
  apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/lib/Listener/CalendarContactInteractionListener.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginCharsetTest.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
  apps/dav/tests/unit/Listener/CalendarContactInteractionListenerTest.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/sharebymail/tests/ShareByMailProviderTest.php
  build/psalm-baseline.xml
  core/Command/User/Add.php
  lib/private/Collaboration/Collaborators/MailPlugin.php
  lib/public/Util.php
  tests/Core/Command/User/AddTest.php
  tests/lib/Collaboration/Collaborators/MailPluginTest.php
  tests/lib/Share20/ShareByMailProviderTest.php
Labels: 4. to release, ♻️ refactor

#55600 [stable31] fix(TaskProcessing): Increase MAX_TASK_AGE to 6 months
  lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
Labels: backport-request

#55514 refactor: Port away from more IQueryBuilder::execute
  apps/testing/lib/Locking/FakeDBLockingProvider.php
  build/psalm-baseline.xml
  core/Command/Db/ConvertType.php
  core/Migrations/Version13000Date20170718121200.php
  core/Migrations/Version14000Date20180404140050.php
  core/Migrations/Version16000Date20190427105638.php
  core/Migrations/Version18000Date20190920085628.php
  core/Migrations/Version20000Date20201109081918.php
Labels: 4. to release

#55623 fix(caldav): encoding inconsistencies in event search provider
  apps/dav/lib/Search/EventsSearchProvider.php
  apps/dav/tests/unit/Search/EventsSearchProviderTest.php
Labels: bug, 3. to review, backport-request, feature: search, feature: caldav

#54543 perf(preview): Split preview data to new table
  apps/files/lib/Command/ScanAppData.php
  build/psalm-baseline.xml
  build/stubs/php-polyfill.php
  core/BackgroundJobs/MovePreviewJob.php
  core/Command/Preview/Repair.php
  core/Command/Preview/ResetRenderedTexts.php
  core/Migrations/Version33000Date20250819110529.php
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Cache/LocalRootScanner.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Mount/ObjectStorePreviewCacheMountProvider.php
  lib/private/Files/ObjectStore/PrimaryObjectStoreConfig.php
  lib/private/Preview/BackgroundCleanupJob.php
  lib/private/Preview/Db/Preview.php
  lib/private/Preview/Db/PreviewMapper.php
  lib/private/Preview/Generator.php
  lib/private/Preview/GeneratorHelper.php
  lib/private/Preview/PreviewService.php
  lib/private/Preview/Storage/IPreviewStorage.php
  lib/private/Preview/Storage/LocalPreviewStorage.php
  lib/private/Preview/Storage/ObjectStorePreviewStorage.php
  lib/private/Preview/Storage/PreviewFile.php
  lib/private/Preview/Storage/Root.php
  lib/private/Preview/Storage/StorageFactory.php
  lib/private/Preview/Watcher.php
  lib/private/PreviewManager.php
  lib/private/Repair.php
  lib/private/Repair/AddMovePreviewJob.php
  lib/private/Server.php
  lib/private/Setup.php
  lib/public/AppFramework/Db/QBMapper.php
  lib/public/Preview/BeforePreviewFetchedEvent.php
  lib/public/Preview/IVersionedPreviewFile.php
  psalm.xml
  tests/Core/Command/Preview/RepairTest.php
  tests/lib/Files/Mount/ObjectStorePreviewCacheMountProviderTest.php
  tests/lib/Files/ObjectStore/PrimaryObjectStoreConfigTest.php
  tests/lib/Files/Storage/Storage.php
  tests/lib/Preview/BackgroundCleanupJobTest.php
  tests/lib/Preview/GeneratorTest.php
  tests/lib/Preview/MovePreviewJobTest.php
  tests/lib/Preview/PreviewMapperTest.php
  tests/lib/Preview/PreviewServiceTest.php
  version.php
Labels: 3. to review, performance 🚀
