Repository nextcloud/server, pull requests merged in 2025-08, with the labels that each got.

#54187 chore(files_sharing): remove leftover of legacy files ui
  apps/files_sharing/css/icons.css
  apps/files_sharing/css/icons.css.map
  apps/files_sharing/css/icons.scss
  apps/files_sharing/css/mobile.css
  apps/files_sharing/css/mobile.css.map
  apps/files_sharing/css/mobile.css.map.license
  apps/files_sharing/css/mobile.scss
  apps/files_sharing/css/public.css
  apps/files_sharing/css/public.css.map
  apps/files_sharing/css/public.css.map.license
  apps/files_sharing/css/public.scss
  apps/files_sharing/css/publicView.css
  apps/files_sharing/css/publicView.css.map
  apps/files_sharing/css/publicView.css.map.license
  apps/files_sharing/css/publicView.scss
  apps/files_sharing/templates/public.php
  build/psalm-baseline.xml
Labels: 3. to review, technical debt, ♻️ refactor

#54138 feat(core): Hide header in PWA
  core/css/header.css
  core/css/header.css.map
  core/css/header.scss
  core/css/server.css
  core/css/server.css.map
Labels: enhancement, 3. to review

#54192 fix: incorrect DELETE on federated-share acceptance
  apps/federatedfilesharing/src/external.js
  dist/federatedfilesharing-external.js
  dist/federatedfilesharing-external.js.map
Labels: bug, 4. to release, backport-request

#50258 Implement Directory Check
  apps/workflowengine/composer/composer/autoload_classmap.php
  apps/workflowengine/composer/composer/autoload_static.php
  apps/workflowengine/lib/Check/Directory.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/src/components/Checks/file.js
  apps/workflowengine/tests/Check/DirectoryTest.php
  build/psalm-baseline.xml
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: enhancement, 4. to release, feature: workflows, feedback-requested

#52285 fix(CardDAV): do not ignore move command object target uri
  apps/dav/lib/CardDAV/AddressBook.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/tests/unit/CardDAV/AddressBookTest.php
Labels: 4. to release, backport-request

#54193 ci(codeql): convert codeql integration into a workflow
  .github/codeql-config.yml
  .github/workflows/codeql.yml
Labels: 3. to review

#54159 fix(files_sharing): ensure password or date is enabled by default to be enforced
  apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
  apps/settings/src/components/AdminSettingsSharingForm.vue
  dist/2911-2911.js
  dist/2911-2911.js.license
  dist/2911-2911.js.map
  dist/2911-2911.js.map.license
  dist/519-519.js
  dist/519-519.js.map
  dist/519-519.js.map.license
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#54250 Revert "feat: Implement Directory Check"
  apps/workflowengine/composer/composer/autoload_classmap.php
  apps/workflowengine/composer/composer/autoload_static.php
  apps/workflowengine/lib/Check/Directory.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/src/components/Checks/file.js
  apps/workflowengine/tests/Check/DirectoryTest.php
  build/psalm-baseline.xml
  dist/workflowengine-workflowengine.js
  dist/workflowengine-workflowengine.js.map
Labels: 3. to review

#54240 fix(caldav): get UID value
  apps/dav/lib/CalDAV/Schedule/IMipService.php
Labels: bug, 3. to review, backport-request, feature: caldav

#54196 [TaskProcessing] Load and store some config keys lazily
  apps/settings/lib/Controller/AISettingsController.php
  apps/settings/lib/Settings/Admin/ArtificialIntelligence.php
  build/psalm-baseline.xml
  core/Command/TaskProcessing/EnabledCommand.php
  lib/private/TaskProcessing/Manager.php
  lib/public/TaskProcessing/IManager.php
  tests/lib/TaskProcessing/TaskProcessingTest.php
Labels: enhancement, 3. to review, performance 🚀, feature: text processing

#54230 fix(logging): Fix query logging with DateTimeImmutable parameters
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: bug, 4. to release, backport-request, feature: database

#54239 refactor(AppFramework): drop unused spreed/Talk fallback
  lib/private/AppFramework/App.php
Labels: 3. to review, feature: apps management, integration, ♻️ refactor

#54233 fix(encryption): Ignore shared files in encrypt-all command
  apps/encryption/lib/Crypto/EncryptAll.php
  apps/encryption/tests/Crypto/EncryptAllTest.php
  tests/Core/Command/Encryption/EncryptAllTest.php
Labels: 4. to release, feature: encryption (server-side)

#54077 refactor(IMimeTypeDetector): streamline + minor tidying
  lib/private/Files/Type/Detection.php
Labels: 3. to review, feature: files, php, ♻️ refactor

#54259 [stable31] fix(caldav): get UID value
  apps/dav/lib/CalDAV/Schedule/IMipService.php
Labels: bug, 3. to review, backport-request, feature: caldav

#54165 fix(core): ensure unique vcategory
  core/Listener/AddMissingIndicesListener.php
  core/Migrations/Version13000Date20170718121200.php
  core/Migrations/Version32000Date20250731062008.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Tags.php
  version.php
Labels: bug, 3. to review, backport-request, feature: tags, technical debt

#54043 fix(db): use `caching_sha2_password` for MySQL
  lib/private/Setup/MySQL.php
Labels: bug, 3. to review, feature: database

#54049 fix(files_sharing): only show "shared with me" information if shared
  apps/files_sharing/src/views/SharingTab.vue
  dist/1025-1025.js
  dist/1025-1025.js.map
  dist/1025-1025.js.map.license
  dist/2453-2453.js
  dist/2453-2453.js.license
  dist/2453-2453.js.map
  dist/2453-2453.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#54289 [stable24] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#54291 [stable25] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#53950 fix: Fix button alignment for email templates in Outlook
  apps/settings/tests/Mailer/NewUserMailHelperTest.php
  lib/private/Mail/EMailTemplate.php
  tests/data/emails/new-account-email-custom.html
  tests/data/emails/new-account-email.html
Labels: bug, help wanted, 3. to review, backport-request, feature: emails

#54285 [master] fix(security): Update code signing revocation list
  resources/codesigning/root.crl
Labels: 3. to review, dependencies

#54298 fix(dav): calculate permissions based on addressbook principal
  apps/dav/lib/CardDAV/AddressBookImpl.php
  apps/dav/tests/unit/CardDAV/AddressBookImplTest.php
Labels: bug, 4. to release, backport-request

#54309 fix: use correct return value for `has-preview` dav property
  apps/files_trashbin/lib/Sabre/TrashbinPlugin.php
  apps/files_versions/lib/Sabre/Plugin.php
Labels: bug, 3. to review, backport-request, feature: versions, feature: trashbin

#54279 fix(systemtags): outline icon css selector
  apps/systemtags/src/components/SystemTagPicker.vue
  dist/2474-2474.js
  dist/2474-2474.js.map
  dist/2474-2474.js.map.license
  dist/9498-9498.js
  dist/9498-9498.js.license
  dist/9498-9498.js.map
  dist/9498-9498.js.map.license
  dist/systemtags-init.js
  dist/systemtags-init.js.map
Labels: bug, design, 3. to review, feature: tags, regression

#54238 feat: allow admins to configure additional sensitive config values
  lib/private/SystemConfig.php
Labels: enhancement, 3. to review

#54260 fix: Remove redundant toast notifications
  apps/files/src/actions/deleteAction.ts
  apps/files/src/actions/moveOrCopyAction.ts
  apps/files/src/newMenu/newFolder.ts
  apps/files_trashbin/src/files_listActions/emptyTrashAction.spec.ts
  apps/files_trashbin/src/files_listActions/emptyTrashAction.ts
  apps/systemtags/src/components/SystemTagPicker.vue
  dist/3596-3596.js
  dist/3596-3596.js.license
  dist/3596-3596.js.map
  dist/3596-3596.js.map.license
  dist/9498-9498.js
  dist/9498-9498.js.license
  dist/9498-9498.js.map
  dist/9498-9498.js.map.license
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files_trashbin-init.js
  dist/files_trashbin-init.js.map
  dist/systemtags-init.js
  dist/systemtags-init.js.map
Labels: enhancement, 3. to review, feature: files

#54069 feature: add bluesky to accounts
  REUSE.toml
  apps/federatedfilesharing/src/components/PersonalSettings.vue
  apps/provisioning_api/lib/Controller/AUserDataOCSController.php
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/provisioning_api/lib/ResponseDefinitions.php
  apps/provisioning_api/openapi-administration.json
  apps/provisioning_api/openapi-full.json
  apps/provisioning_api/openapi.json
  apps/provisioning_api/tests/Controller/UsersControllerTest.php
  apps/settings/lib/Controller/UsersController.php
  apps/settings/lib/Settings/Personal/PersonalInfo.php
  apps/settings/src/components/PersonalInfo/BlueskySection.vue
  apps/settings/src/constants/AccountPropertyConstants.ts
  apps/settings/src/main-personal-info.js
  apps/settings/templates/settings/personal/personal.info.php
  apps/settings/tests/Controller/UsersControllerTest.php
  build/integration/features/provisioning-v1.feature
  build/psalm-baseline.xml
  core/img/actions/bluesky.svg
  core/img/bluesky.svg
  dist/federatedfilesharing-vue-settings-personal.js
  dist/federatedfilesharing-vue-settings-personal.js.map
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Accounts/AccountManager.php
  lib/private/Profile/Actions/BlueskyAction.php
  lib/private/Profile/ProfileManager.php
  lib/public/Accounts/IAccountManager.php
  lib/public/Profile/IProfileManager.php
  openapi.json
  tests/lib/Accounts/AccountManagerTest.php
  tests/lib/Accounts/AccountTest.php
Labels: enhancement, 4. to release, feature: users and groups, feature: profile

#54312 enh(unified-search): Smarter load more
  core/src/components/UnifiedSearch/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: enhancement, 4. to release, feature: search

#54303 refactor(App): \OC\AppFramework\App clean-up
  lib/private/AppFramework/App.php
Labels: 3. to review, feature: apps management, ♻️ refactor

#54158 feat(preset): profile visibility
  core/Command/Config/Preset.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/AppConfig.php
  lib/private/Config/ConfigManager.php
  lib/private/Config/PresetManager.php
  lib/private/Config/UserConfig.php
  lib/private/Profile/ProfileManager.php
  tests/lib/AppConfigTest.php
  tests/lib/Config/LexiconTest.php
  tests/lib/Config/UserConfigTest.php
Labels: enhancement, 3. to review

#54339 fix(container): Reduce general deprecation spam on all requests
  apps/twofactor_backupcodes/lib/Provider/BackupCodesProvider.php
  apps/twofactor_backupcodes/tests/Unit/Provider/BackupCodesProviderTest.php
  build/psalm-baseline.xml
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/InitialStateService.php
  lib/private/UserStatus/Manager.php
  lib/public/IInitialStateService.php
Labels: 3. to review

#54357 fix: increase how long we cache display names
  lib/private/User/DisplayNameCache.php
Labels: 3. to review, performance 🚀

#54200 test: add env option to disable loading all installed apps during tests
  tests/bootstrap.php
Labels: 3. to review, tests

#54354 chore(CODEOWNERS): ensure every file change has at least 2 reviewers
  .github/CODEOWNERS
Labels: 3. to review

#54310 fix(files_sharing): Implement conditional federation placeholder
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/src/services/ConfigService.ts
  apps/files_sharing/src/views/SharingTab.vue
  apps/files_sharing/tests/CapabilitiesTest.php
  dist/2261-2261.js
  dist/2261-2261.js.map
  dist/2261-2261.js.map.license
  dist/9283-9283.js
  dist/9283-9283.js.license
  dist/9283-9283.js.map
  dist/9283-9283.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: enhancement, feature: sharing, backport-request

#54367 views/UnifiedSearch: trigger on `f` input rather than qwerty keycode
  core/src/views/UnifiedSearch.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 4. to release

#54371 fix: Fix getting trusted server other than the first
  apps/federation/lib/TrustedServers.php
  apps/federation/tests/TrustedServersTest.php
Labels: bug, 3. to review, feature: federation, backport-request, regression

#54401 fix(ZipFolderPlugin): set mtime of directories in archive
  apps/dav/lib/Connector/Sabre/ZipFolderPlugin.php
  lib/private/Streamer.php
Labels: bug, 3. to review, backport-request, hotspot: file time handling

#53756 feat(settings): Deploy daemon selection support during ExApp installation
  apps/settings/src/app-types.ts
  apps/settings/src/components/AppAPI/DaemonSelectionDialog.vue
  apps/settings/src/components/AppAPI/DaemonSelectionEntry.vue
  apps/settings/src/components/AppAPI/DaemonSelectionList.vue
  apps/settings/src/components/AppList/AppItem.vue
  apps/settings/src/components/AppStoreSidebar/AppDeployOptionsModal.vue
  apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue
  apps/settings/src/mixins/AppManagement.js
  apps/settings/src/store/app-api-store.ts
  dist/8737-8737.js
  dist/8737-8737.js.license
  dist/8737-8737.js.map
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.license
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: enhancement, 2. developing, feature: apps management

#54413 perf: render sharing tab sections only once
  apps/files_sharing/src/services/TabSections.js
  apps/files_sharing/src/views/SharingTab.vue
  dist/6348-6348.js
  dist/6348-6348.js.license
  dist/6348-6348.js.map
  dist/6348-6348.js.map.license
  dist/7639-7639.js
  dist/7639-7639.js.map
  dist/7639-7639.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: enhancement, 3. to review, performance 🚀

#54389 [stable24] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54390 [stable26] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54396 [stable28] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54394 [stable29] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54393 [master] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54382 [stable30] fix: use the join function for merging davRootPath and path
  apps/files/src/services/Files.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review

#54411 perf: ignore any custom property in the nc/oc namespace that isn't explicitly allowed
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: 3. to review, performance 🚀

#54120 fix(search): Fix SearchComposer.php filtering logic
  lib/private/Search/SearchComposer.php
  tests/lib/Search/SearchComposerTest.php
Labels: backport-request, feedback-requested

#54420 perf(calendar): Disable custom properties for individual calendar events
  apps/dav/lib/DAV/CustomPropertiesBackend.php
Labels: 3. to review, performance 🚀, feature: caldav

#54418 fix: add more transparency to the header icon gradient
  apps/theming/css/default.css
  apps/theming/lib/Themes/DefaultTheme.php
Labels: bug, design, 3. to review

#54370 chore: drop unused ocs/providers.php
  ocs/providers.php
Labels: 3. to review, feature: sharing, feature: federation, ♻️ refactor

#54272 feat(taskprocessing): add cleanup flag to tasks
  core/Command/TaskProcessing/Cleanup.php
  core/Command/TaskProcessing/EnabledCommand.php
  core/Command/TaskProcessing/GetCommand.php
  core/Command/TaskProcessing/ListCommand.php
  core/Command/TaskProcessing/Statistics.php
  core/Controller/TaskProcessingApiController.php
  core/Migrations/Version32000Date20250806110519.php
  core/ResponseDefinitions.php
  core/openapi-ex_app.json
  core/openapi-full.json
  core/openapi.json
  core/register_command.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/TaskProcessing/Db/Task.php
  lib/private/TaskProcessing/Db/TaskMapper.php
  lib/private/TaskProcessing/Manager.php
  lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
  lib/public/TaskProcessing/IManager.php
  lib/public/TaskProcessing/Task.php
  openapi.json
  tests/lib/TaskProcessing/TaskProcessingTest.php
  version.php
Labels: enhancement, 3. to review, pending documentation, feature: text processing

#54318 Feat/54115/emit preload collection event
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/CalDAV/EmbeddedCalDavServer.php
  apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
  apps/dav/lib/Connector/Sabre/PropFindMonitorPlugin.php
  apps/dav/lib/Connector/Sabre/PropFindPreloadNotifyPlugin.php
  apps/dav/lib/Connector/Sabre/Server.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  apps/dav/lib/Connector/Sabre/TagsPlugin.php
  apps/dav/lib/DAV/Sharing/Plugin.php
  apps/dav/lib/Server.php
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  apps/dav/tests/unit/Connector/Sabre/PropFindMonitorPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/PropFindPreloadNotifyPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
  apps/dav/tests/unit/Connector/Sabre/TagsPluginTest.php
  apps/files_reminders/lib/Dav/PropFindPlugin.php
Labels: 4. to release, performance 🚀

#54229 perf: join array_merge calls in MountProvider::getMountsForUser()
  apps/files_sharing/lib/MountProvider.php
Labels: 4. to release, performance 🚀

#54419 fix: catch and log exception from share events
  lib/private/Share20/Manager.php
Labels: 3. to review

#54494 fix: typos in cache and app config
  config/config.sample.php
  lib/private/AppConfig.php
  lib/private/Memcache/Factory.php
Labels: bug, 3. to review

#54503 fix(workflows): also exclude beta in block-merge-freeze
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review

#54492 feat: add CSS variables for status border and text
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkHighContrastTheme.php
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/lib/Themes/HighContrastTheme.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
Labels: enhancement, design, 3. to review, pending documentation

#54058 feat(preset): load apps on preset change
  lib/private/Config/PresetManager.php
  tests/lib/Config/LexiconTest.php
Labels: enhancement, 3. to review, 🍂 2025-Autumn

#54440 fix(caldav): encode calendar URLs properly when formatting search results
  apps/dav/lib/Search/EventsSearchProvider.php
  apps/dav/tests/unit/Search/EventsSearchProviderTest.php
Labels: bug, 3. to review, backport-request, feature: search, feature: caldav

#54408 feat(preset): share link expiration date
  apps/files_sharing/tests/CapabilitiesTest.php
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/tests/Settings/Admin/SharingTest.php
  core/AppInfo/ConfigLexicon.php
  lib/private/Share/Helper.php
  lib/private/Share20/Manager.php
  lib/private/Template/JSConfigHelper.php
  tests/lib/Share20/ManagerTest.php
Labels: 3. to review

#54414 feat(preset): compare default for all preset
  apps/settings/appinfo/routes.php
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Controller/PresetController.php
  core/Command/Config/Preset.php
  lib/private/AppConfig.php
  lib/private/Config/PresetManager.php
Labels: enhancement, 3. to review

#54523 fix: changelog generation workflow
  .github/workflows/generate-release-changelog.yml
Labels: 3. to review

#53752 fix: fix trashbin restore events
  apps/files_trashbin/lib/Trashbin.php
Labels: 3. to review, backport-request

#54532 fix(theming): Document correct response schema if app is not enabled
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/openapi.json
  openapi.json
Labels: bug, 3. to review

#54530 Change "core.ProfilePage.index" to lowercase
  lib/private/Route/Router.php
Labels: 3. to review, php

#54266 [stable29] fix(lib): get fileinfo before locking
  lib/private/legacy/OC_Files.php
Labels: bug, 3. to review, feature: sharing, feature: filesystem

#54541 fix(AppManager): Argument must be of type array|object
  lib/private/App/AppManager.php
Labels: bug, 3. to review, backport-request

#54535 fix(caldav): public calendars are always read-only
  apps/dav/lib/CalDAV/CalDavBackend.php
Labels: 3. to review, feature: caldav

#54552 Config value to allow to extend .user.ini on update
  config/config.sample.php
Labels: enhancement, 3. to review, feature: install and update

#54545 Dispatch new event when invalidating an authentication token
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Authentication/Token/PublicKeyTokenProvider.php
  lib/public/Authentication/Events/TokenInvalidatedEvent.php
  tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php
Labels: enhancement, 3. to review, feature: authentication, pending documentation

#54519 fix: Fix unique constraint violation in oc_vcategory migration
  core/Migrations/Version32000Date20250731062008.php
Labels: 3. to review, backport-request

#54554 feat(theming): add new default background for Nextcloud 32
  REUSE.toml
  apps/theming/README.md
  apps/theming/REUSE.toml
  apps/theming/css/default.css
  apps/theming/img/background/jo-myoung-hee-fluid-dark.webp
  apps/theming/img/background/jo-myoung-hee-fluid.webp
  apps/theming/img/background/preview/jenna-kim-the-globe.jpg
  apps/theming/img/background/preview/jenna-kim-the-globe.webp
  apps/theming/img/background/preview/jo-myoung-hee-fluid.webp
  apps/theming/lib/Service/BackgroundService.php
  cypress/e2e/theming/themingUtils.ts
Labels: enhancement, design, 3. to review

#54575 fix: use appropriate user agent string when syncing Outlook calendar subscriptions
  apps/dav/lib/CalDAV/WebcalCaching/Connection.php
Labels: bug, 4. to release, backport-request, feature: caldav

#53503 fix(sharing): fix json decoding the list of groups excluded from sharing
  lib/private/Share20/ShareDisableChecker.php
Labels: bug, 3. to review, feature: sharing, backport-request, feature: users and groups

#54608 tests: Update testing certificates that expired after 10 years
  tests/data/certificates/Readme.md
  tests/data/certificates/badCertificate.crt
  tests/data/certificates/goodCertificate.crt
  tests/lib/Security/CertificateTest.php
Labels: 3. to review, backport-request

#54607 fix(encryption): Fix TypeError when trying to decrypt unencrypted file
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Files/ViewTest.php
Labels: 3. to review

#54621 fix(settings): adjust colors used by legacy setup checks ui
  apps/settings/css/settings.scss
Labels: bug, design, 3. to review

#54617 test: Fix double space
  tests/lib/Security/CertificateTest.php
Labels: 3. to review, tests

#54520 feat(preset): compare userconfig lexicon entries
  core/Command/Config/Preset.php
  lib/private/AppConfig.php
  lib/private/Config/PresetManager.php
  lib/private/Config/UserConfig.php
Labels: 3. to review

#54632 fix(trashbin): Fix errors in the log on MOVE operations
  apps/files_trashbin/lib/Sabre/TrashbinPlugin.php
Labels: 3. to review

#54618 fix(oauth2): Limit allowed grant_type values in getToken
  apps/oauth2/lib/Controller/OauthApiController.php
  apps/oauth2/openapi.json
  openapi.json
Labels: 4. to release, technical debt

#54538 Do not always check password checkbox when sharing without password
  apps/files_sharing/src/mixins/SharesMixin.js
  dist/6894-6894.js
  dist/6894-6894.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: bug, 3. to review, feature: sharing

#54671 chore(version): Hub 10 -> Hub 25 Autumn
  apps/settings/templates/settings/admin/overview.php
Labels: 4. to release

#54533 fix(caldav): show confidential event if writable
  apps/dav/lib/CalDAV/CalendarObject.php
  apps/dav/tests/unit/CalDAV/CalendarObjectTest.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/CalDAV/PublicCalendarObjectTest.php
  apps/dav/tests/unit/CalDAV/PublicCalendarTest.php
Labels: bug, 3. to review, backport-request, feature: caldav

#54654 fix(core): more understandable guest avatar menu notice
  core/src/views/PublicPageUserMenu.vue
  cypress/e2e/files_sharing/public-share/header-avatar.cy.ts
  dist/core-public-page-user-menu.js
  dist/core-public-page-user-menu.js.map
Labels: design, 3. to review, feature: sharing, feature: language/translations (l10n/i18n)

#54679 feat(theming): provide Nextcloud Assistant theming colors
  apps/theming/css/default.css
  apps/theming/lib/Themes/DarkTheme.php
  apps/theming/lib/Themes/DefaultTheme.php
  apps/theming/tests/Themes/AccessibleThemeTestCase.php
Labels: enhancement, 3. to review, pending documentation, 🍂 2025-Autumn

#54666 chore(rector): Apply current rector config
  apps/dav/lib/CalDAV/CalendarImpl.php
  apps/dav/lib/CalDAV/EmbeddedCalDavServer.php
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files_sharing/tests/Controller/ShareAPIControllerTest.php
  apps/files_trashbin/tests/Command/ExpireTrashTest.php
  core/AppInfo/Capabilities.php
  core/Command/TaskProcessing/Cleanup.php
  tests/lib/Avatar/GuestAvatarTest.php
  tests/lib/Files/Cache/FileAccessTest.php
  tests/lib/Files/ObjectStore/PrimaryObjectStoreConfigTest.php
Labels: 3. to review, ♻️ refactor

#53458 fix(profiler): set default values for fputcsv arguments to avoid depreciation warning
  lib/private/Profiler/FileProfilerStorage.php
Labels: 3. to review, developer experience

#54438 perf(caldav): also cache empty share arrays
  apps/dav/lib/DAV/Sharing/Backend.php
Labels: enhancement, 4. to release, performance 🚀, feature: caldav

#54696 [stable30] chore: pin NPM to at least `^10.5.1` to prevent bugs with `corepack`
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#54721 fix: make bucket mapper work with new multi-object-store config
  lib/private/Files/ObjectStore/Mapper.php
  lib/private/Files/ObjectStore/PrimaryObjectStoreConfig.php
  tests/lib/Files/ObjectStore/MapperTest.php
Labels: 3. to review

#54728 fix(files_versions): ensure users IDs are strings
  apps/files_versions/src/utils/versions.ts
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review, backport-request, feature: versions, regression

#54733 fix(files_versions): author and label parsing fallback
  apps/files_versions/src/utils/versions.ts
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review, feature: versions

#54767 [stable31] fix(files_versions): ensure IDs, Author and Label are strings
  apps/files_versions/src/utils/versions.ts
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: 3. to review, feature: versions
