Repository nextcloud/server, pull requests merged in 2025-09, with the labels that each got.

#54744 [stable31] fix: cast fileid to string in getMountsForFileId
  lib/private/Files/Config/UserMountCache.php
Labels: 3. to review, backport-request

#54774 Replace filled icon with outlined variant
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: design, 3. to review

#54775 fix(lostpassord): Delete lost password token on password change
  core/AppInfo/Application.php
  core/Listener/PasswordUpdatedListener.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: backport-request

#54785 chore(flake): update haze to 2.1.1
  flake.lock
Labels: 3. to review, backport-request

#54800 fix: Remove intro from presets
  lib/private/Config/PresetManager.php
Labels: bug, 3. to review, feature: settings, php

#53831 feat: Meeting Proposals
  lib/private/Calendar/Manager.php
  lib/public/Calendar/IManager.php
  tests/lib/Calendar/ManagerTest.php
Labels: enhancement, 3. to review, pending documentation, feature: caldav

#54794 fix: add missing listener
  apps/contactsinteraction/composer/composer/autoload_classmap.php
  apps/contactsinteraction/composer/composer/autoload_static.php
  apps/contactsinteraction/lib/AppInfo/Application.php
  apps/contactsinteraction/lib/Db/RecentContactMapper.php
  apps/contactsinteraction/lib/Listeners/UserDeletedListener.php
Labels: bug, 4. to release, backport-request

#54789 fix(theming): adjust assistant icon color on dark theme
  apps/theming/lib/Themes/DarkTheme.php
Labels: bug, design, 3. to review, 🍂 2025-Autumn

#54801 fix(dav): ensure moving or copying a file is possible
  apps/dav/lib/Connector/Sabre/SharesPlugin.php
  build/integration/sharing_features/sharing-v1-part4.feature
Labels: bug, 3. to review, backport-request

#54424 fix(dav): clean up user's addressbook shares on deletion
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Listener/UserEventsListener.php
  apps/dav/tests/unit/DAV/Listener/UserEventsListenerTest.php
Labels: bug, 4. to release, feature: dav, backport-request

#54820 test: add cypress tests for the systemtags files view
  cypress/e2e/systemtags/files-view.cy.ts
Labels: 3. to review, tests

#54832 fix(theming): Remove header-icon-mask in dark-mode high-contrast as well
  apps/theming/lib/Themes/DarkHighContrastTheme.php
Labels: bug, design, 3. to review

#54838 fix(l10n): use `productName` instead of hardcoded 'Nextcloud' where possible
  apps/dashboard/src/DashboardApp.vue
  apps/federatedfilesharing/src/components/PersonalSettings.vue
  apps/files_external/src/settings.js
  apps/files_sharing/src/views/SharingTab.vue
  apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue
  apps/settings/src/components/Encryption/sharedTexts.ts
  apps/settings/src/components/Users/UserRow.vue
  apps/settings/src/mixins/AppManagement.js
  apps/settings/src/views/AdminSettingsSetupChecks.vue
  apps/settings/src/views/AppStore.vue
  apps/updatenotification/src/components/UpdateNotification.vue
  dist/5056-5056.js
  dist/5056-5056.js.license
  dist/5056-5056.js.map
  dist/5056-5056.js.map.license
  dist/7033-7033.js
  dist/7033-7033.js.map
  dist/7033-7033.js.map.license
  dist/dashboard-main.js
  dist/dashboard-main.js.map
  dist/federatedfilesharing-vue-settings-personal.js
  dist/federatedfilesharing-vue-settings-personal.js.map
  dist/files_external-settings.js
  dist/files_external-settings.js.map
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-users-3239.js
  dist/settings-users-3239.js.map
  dist/settings-vue-settings-admin-overview.js
  dist/settings-vue-settings-admin-overview.js.map
  dist/settings-vue-settings-admin-security.js
  dist/settings-vue-settings-admin-security.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
  dist/updatenotification-updatenotification.js
  dist/updatenotification-updatenotification.js.map
Labels: bug, design, 3. to review, feature: theming, feature: language/translations (l10n/i18n)

#54839 perf(users): Create lazy users in IUserManager::getSeenUsers
  lib/private/User/Manager.php
Labels: 3. to review, performance 🚀

#54507 fix: propfind query monitor breaking removeListener and removeAllList…
  apps/dav/lib/Connector/Sabre/Server.php
  apps/dav/tests/unit/Connector/ServerTest.php
Labels: 3. to review

#54447 feat(config): Add common audio and video MIME type aliases
  core/js/mimetype.js
  core/js/mimetypelist.js
  core/js/tests/specs/mimeTypeSpec.js
  resources/config/mimetypealiases.dist.json
  resources/config/mimetypealiases.dist.json.license
  resources/config/mimetypemapping.dist.json
  resources/config/mimetypemapping.dist.json.license
  resources/config/mimetypenames.dist.json
  resources/config/mimetypenames.dist.json.license
  tests/data/integritycheck/mimetypeListModified/core/js/mimetypelist.js
  tests/data/integritycheck/mimetypeListModified/core/signature.json
Labels: enhancement, 2. developing, feedback-requested

#54853 fix: TypeError: this.fetchDisplayName is not a function
  apps/files_versions/src/components/Version.vue
  dist/files_versions-files_versions.js
  dist/files_versions-files_versions.js.map
Labels: bug, 3. to review, backport-request

#54870 fix: remove executable flag from source files
  apps/admin_audit/lib/BackgroundJobs/Rotate.php
  apps/user_ldap/tests/.htaccess
  apps/webhook_listeners/lib/Migration/Version1000Date20240527153425.php
  apps/webhook_listeners/lib/Migration/Version1001Date20240716184935.php
  core/js/mimetype.js
  core/js/mimetypelist.js
  core/js/tests/specs/mimeTypeSpec.js
  lib/private/LargeFileHelper.php
  lib/private/Template/ResourceLocator.php
  resources/config/mimetypealiases.dist.json
  resources/config/mimetypealiases.dist.json.license
  resources/config/mimetypemapping.dist.json
  resources/config/mimetypemapping.dist.json.license
  resources/config/mimetypenames-update.sh
  resources/config/mimetypenames.dist.json
  resources/config/mimetypenames.dist.json.license
  tests/data/integritycheck/mimetypeListModified/core/js/mimetypelist.js
  tests/data/integritycheck/mimetypeListModified/core/signature.json
Labels: 3. to review

#54907 chore(flake): update haze to 2.1.2
  flake.lock
Labels: 3. to review, backport-request

#54848 Add task processing manager method to get the list of available task type IDs
  lib/private/TaskProcessing/Manager.php
  lib/public/TaskProcessing/IManager.php
  tests/lib/TaskProcessing/TaskProcessingTest.php
Labels: enhancement, 3. to review, backport-request, performance 🚀, feature: text processing

#54914 test(BinaryFinder): Make sure the test is portable between systems
  tests/lib/BinaryFinderTest.php
Labels: 3. to review, technical debt

#54920 fix: ensure all object store configuration have distict bucket names
  lib/private/Files/ObjectStore/PrimaryObjectStoreConfig.php
  tests/lib/Files/ObjectStore/PrimaryObjectStoreConfigTest.php
Labels: 3. to review, backport-request

#54957 fix: remove loading removed script
  apps/settings/templates/settings/frame.php
Labels: bug, 3. to review, backport-request

#54822 chore(config.sample.php): apply Nc coding standard
  .php-cs-fixer.dist.php
  config/config.sample.php
Labels: 3. to review, technical debt, ♻️ refactor

#54919 fix: don't show object size warning if we can't determine the object size
  core/Command/Info/File.php
Labels: 3. to review, backport-request

#54997 [stable31] Revert "fix(files_trashbin): Fix size propagation when moving file to trash"
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/tests/TrashbinTest.php
Labels: 3. to review

#54982 [stable32] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54991 [stable31] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54993 [stable29] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54983 [stable24] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54989 [stable28] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#54986 [stable26] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#55016 fix: update transifex link
  apps/settings/src/components/PersonalInfo/LanguageSection/Language.vue
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
Labels: bug, 3. to review, backport-request

#55014 feat(ZipFolderPlugin): always use the parent folder name as archive name
  apps/dav/lib/Connector/Sabre/ZipFolderPlugin.php
  cypress/e2e/files_sharing/public-share/PublicShareUtils.ts
  cypress/e2e/files_sharing/public-share/download.cy.ts
Labels: enhancement, 3. to review, backport-request, 🍂 2025-Autumn

#55013 fix(auth): allow access to dynamic js files during 2FA
  core/Controller/JsController.php
Labels: bug, 3. to review, backport-request, feature: authentication

#55130 [stable30] fix(auth): Fix invalid unique constraint violation catch
  lib/private/Authentication/Token/Manager.php
  tests/lib/Authentication/Token/ManagerTest.php
Labels: bug, 3. to review, feature: authentication

#54916 feat(test): Run behat tests as www-data
  build/integration/run-docker.sh
Labels: 3. to review, tests

#55085 Port away from IQueryBuilder::execute in apps/
  apps/dav/lib/BackgroundJob/CleanupInvitationTokenJob.php
  apps/dav/lib/CalDAV/ResourceBooking/AbstractPrincipalBackend.php
  apps/dav/lib/Migration/BuildSocialSearchIndex.php
  apps/dav/lib/Migration/RefreshWebcalJobRegistrar.php
  apps/dav/lib/Migration/RemoveDeletedUsersCalendarSubscriptions.php
  apps/dav/lib/Migration/Version1008Date20181105104826.php
  apps/dav/lib/Migration/Version1008Date20181105110300.php
  apps/dav/tests/unit/BackgroundJob/CleanupInvitationTokenJobTest.php
  apps/dav/tests/unit/Migration/RefreshWebcalJobRegistrarTest.php
  apps/dav/tests/unit/Migration/RemoveDeletedUsersCalendarSubscriptionsTest.php
  apps/federatedfilesharing/lib/Migration/Version1011Date20201120125158.php
  apps/files/lib/Command/RepairTree.php
  apps/files_external/lib/Command/Notify.php
  apps/files_external/lib/Migration/Version1015Date20211104103506.php
  apps/files_external/lib/Service/DBConfigService.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/lib/Migration/OwncloudGuestShareType.php
  apps/files_sharing/lib/Migration/SetPasswordColumn.php
  apps/files_sharing/lib/Migration/Version11300Date20201120141438.php
  apps/files_sharing/lib/ShareBackend/Folder.php
  apps/files_sharing/tests/External/ManagerTest.php
  apps/settings/lib/Settings/Admin/Server.php
  apps/twofactor_backupcodes/lib/Db/BackupCodeMapper.php
  apps/twofactor_backupcodes/lib/Migration/Version1002Date20170607113030.php
  apps/user_status/tests/Unit/Service/StatusServiceTest.php
  apps/workflowengine/lib/Manager.php
  build/psalm-baseline.xml
Labels: 4. to release, technical debt, ♻️ refactor

#54736 fix: always use english name for recently contacted category
  apps/contactsinteraction/appinfo/info.xml
  apps/contactsinteraction/composer/composer/autoload_classmap.php
  apps/contactsinteraction/composer/composer/autoload_static.php
  apps/contactsinteraction/lib/Listeners/ContactInteractionListener.php
  apps/contactsinteraction/lib/Migration/FixVcardCategory.php
Labels: bug, 3. to review, backport-request

#55136 test(integration): Check ocs share permission for correct folder
  build/integration/sharing_features/sharing-v1-part3.feature
Labels: 3. to review, integration, tests

#55141 fix(Updater): Lower deadlock log level from warning to info
  lib/private/Files/Cache/Updater.php
Labels: 3. to review, feature: logging, php

#55142 fix: Allow hyphen in appid
  lib/private/App/AppManager.php
  tests/lib/App/AppManagerTest.php
Labels: bug, 3. to review, backport-request

#55139 fix(userconfig): set 'mail' as indexed
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/AppInfo/Application.php
  apps/settings/lib/ConfigLexicon.php
  lib/private/App/AppManager.php
  lib/private/Config/ConfigManager.php
  lib/private/Config/UserConfig.php
  lib/private/Repair/ConfigKeyMigration.php
  tests/lib/Config/LexiconTest.php
  tests/lib/Config/TestLexicon_UserIndexed.php
  tests/lib/Config/TestLexicon_UserIndexedRemove.php
Labels: 3. to review, backport-request

#55183 fix(trashbin): Translate Nextcloud exception to Sabre exception
  apps/files_trashbin/lib/Sabre/TrashFile.php
Labels: bug, 3. to review, backport-request, feature: trashbin

#55180 fix(comments): add inline container size query to comment body
  apps/comments/src/components/Comment.vue
  dist/7462-7462.js
  dist/7462-7462.js.map
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
  dist/comments-comments-tab.js
  dist/comments-comments-tab.js.map
Labels: bug, 3. to review, backport-request

#55237 fix(github): add labels and milestone to PR checklist
  .github/pull_request_template.md
Labels: enhancement, 3. to review, backport-request

#55172 fix: added bluesky link
  apps/settings/templates/settings/personal/development.notice.php
Labels: 3. to review, backport-request

#55248 [stable31] fix(github): add labels and milestone to PR checklist
  .github/pull_request_template.md
Labels: enhancement, 3. to review

#55241 fix(http): handle getHttpProtocol being unset in $_SERVER['SERVER_PROTOCOL'] if called from occ
  lib/private/AppFramework/Http/Request.php
Labels: bug, 3. to review, feature: occ

#55140 refactor(psalm): Fix most issues with the workflowengine
  apps/workflowengine/lib/BackgroundJobs/Rotate.php
  apps/workflowengine/lib/Check/AbstractStringCheck.php
  apps/workflowengine/lib/Check/FileSize.php
  apps/workflowengine/lib/Check/RequestRemoteAddress.php
  apps/workflowengine/lib/Check/TFileCheck.php
  apps/workflowengine/lib/Controller/GlobalWorkflowsController.php
  apps/workflowengine/lib/Entity/File.php
  apps/workflowengine/lib/Helper/LogContext.php
  apps/workflowengine/lib/Helper/ScopeContext.php
  apps/workflowengine/lib/Manager.php
  apps/workflowengine/lib/Service/Logger.php
  apps/workflowengine/lib/Service/RuleMatcher.php
  apps/workflowengine/lib/Settings/ASettings.php
  apps/workflowengine/lib/Settings/Section.php
  apps/workflowengine/tests/ManagerTest.php
  build/psalm-baseline.xml
  lib/public/Util.php
  lib/public/WorkflowEngine/IManager.php
Labels: 3. to review, ♻️ refactor

#55275 fix(comments): explicitly return limbo status of comment
  apps/comments/src/store/deletedCommentLimbo.js
  dist/7462-7462.js
  dist/7462-7462.js.map
  dist/comments-comments-app.js
  dist/comments-comments-app.js.map
  dist/comments-comments-tab.js
  dist/comments-comments-tab.js.map
Labels: bug, 3. to review, backport-request, feature: comments

#55282 fix: create room/resource calendar synchronously
  lib/private/Calendar/ResourcesRoomsUpdater.php
Labels: 3. to review, feature: caldav

#55134 fix(core): Stop abusing the cache for avatar upload
  apps/settings/src/components/PersonalInfo/AvatarSection.vue
  build/integration/features/avatar.feature
  build/integration/features/bootstrap/Avatar.php
  core/Controller/AvatarController.php
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
  tests/Core/Controller/AvatarControllerTest.php
Labels: bug, 3. to review, backport-request

#55289 fix(ocm): ignore cache if not setup
  lib/private/OCM/OCMDiscoveryService.php
Labels: bug, 3. to review, backport-request

#55311 fix: add missing sharing options to ui and add full-match results
  apps/settings/lib/Settings/Admin/Sharing.php
  apps/settings/src/components/AdminSettingsSharingForm.vue
  dist/settings-vue-settings-admin-sharing.js
  dist/settings-vue-settings-admin-sharing.js.map
  lib/private/Collaboration/Collaborators/UserPlugin.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
Labels: bug, 3. to review, feature: sharing, backport-request

#55319 [stable29] fix(dav): clean up user's addressbook shares on deletion
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/HookManager.php
Labels: bug, 4. to release, feature: dav, feature: carddav

#55358 feat(test-case): allow to use PHPUnit Group attributes to mark tests requiring database
  tests/lib/TestCase.php
Labels: 3. to review, tests, developer experience

#55261 fix(admin): Hide empty section for users admin delegation
  apps/settings/appinfo/info.xml
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/Sections/Admin/Users.php
  apps/settings/lib/Settings/Admin/Delegation.php
  apps/settings/lib/Settings/Admin/Users.php
  apps/webhook_listeners/appinfo/info.xml
  apps/webhook_listeners/composer/composer/autoload_classmap.php
  apps/webhook_listeners/composer/composer/autoload_static.php
  apps/webhook_listeners/lib/Settings/Admin.php
  apps/webhook_listeners/lib/Settings/AdminSection.php
  lib/private/App/AppManager.php
  lib/private/App/InfoParser.php
  lib/private/Settings/Manager.php
  lib/public/Settings/IManager.php
  resources/app-info-shipped.xsd
  resources/app-info.xsd
Labels: 3. to review, feature: settings

#55372 refactor: Remove old TemplateManager
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Type/TemplateManager.php
  lib/private/legacy/OC_Helper.php
Labels: 3. to review, technical debt, ♻️ refactor

#55375 fix: Do not try to create lazy ghosts for PHP internal classes
  lib/private/AppFramework/Utility/SimpleContainer.php
Labels: 3. to review

#55388 chore: Remove unused deprecated methods from OC_User and Filesystem
  lib/private/Files/Filesystem.php
  lib/private/legacy/OC_User.php
Labels: 3. to review, technical debt, pending documentation

#55065 [stable30] fix(Apps): fix install command check on existing apps
  core/Command/App/Install.php
Labels: bug, 3. to review

#55387 fix: Delete legacy OC_Response
  lib/base.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/legacy/OC_Response.php
Labels: 3. to review, technical debt, pending documentation, ♻️ refactor

#55355 fix: Fix spacing of adming delegation entries
  apps/settings/src/components/AdminDelegating.vue
  dist/settings-vue-settings-admin-delegation.js
  dist/settings-vue-settings-admin-delegation.js.map
Labels: design, 3. to review

#55374 fix(files): Stop overwriting scan_permissions
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Wrapper/CachePermissionsMask.php
  lib/private/Files/Storage/Wrapper/PermissionsMask.php
Labels: bug, 3. to review, backport-request

#55288 [stable31] feat: move primary object store configuration to a single place
  build/psalm-baseline.xml
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Files/Mount/ObjectHomeMountProvider.php
  lib/private/Files/Mount/RootMountProvider.php
  lib/private/Files/ObjectStore/PrimaryObjectStoreConfig.php
  lib/private/Server.php
  tests/lib/Files/Mount/ObjectHomeMountProviderTest.php
  tests/lib/Files/Mount/RootMountProviderTest.php
  tests/lib/TestCase.php
Labels: 3. to review, backport-request

#55412 chore: update webhook_listeners description
  apps/webhook_listeners/appinfo/info.xml
  apps/webhook_listeners/openapi.json
Labels: enhancement, 3. to review, feature: webhooks

#55421 local: admin-delegation occ - add output option for show command to support JSON formats
  apps/settings/lib/Command/AdminDelegation/Show.php
Labels: 2. developing

#55404 Fix type and other psalm issues in lib/private/Template
  build/psalm-baseline.xml
  build/rector.php
  lib/private/L10N/L10N.php
  lib/private/Server.php
  lib/private/Template/Base.php
  lib/private/Template/CSSResourceLocator.php
  lib/private/Template/JSCombiner.php
  lib/private/Template/JSConfigHelper.php
  lib/private/Template/JSResourceLocator.php
  lib/private/Template/ResourceLocator.php
  lib/private/Template/ResourceNotFoundException.php
  lib/private/Template/TemplateManager.php
  lib/private/TemplateLayout.php
  lib/private/legacy/OC_App.php
  lib/public/IL10N.php
  tests/lib/Template/CSSResourceLocatorTest.php
  tests/lib/Template/JSCombinerTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/ResourceLocatorTest.php
  tests/lib/TemplateLayoutTest.php
Labels: 2. developing

#55426 test: mock appstore response in Cypress tests
  REUSE.toml
  cypress/e2e/core/setup.ts
  cypress/fixtures/appstore/apps.json
Labels: 3. to review, backport-request, tests

#55422 fix(appstore): Also catch ClientException and ServerException
  lib/private/App/AppStore/Fetcher/Fetcher.php
Labels: 3. to review, backport-request, feature: apps management

#55370 refactor(files_external): migrate Ajax with `OC_JSON` to proper controller
  apps/files_external/ajax/applicable.php
  apps/files_external/ajax/oauth2.php
  apps/files_external/appinfo/routes.php
  apps/files_external/lib/Controller/AjaxController.php
  apps/files_external/src/settings.js
  apps/files_external/tests/Controller/AjaxControllerTest.php
  build/psalm-baseline.xml
  dist/files_external-settings.js
  dist/files_external-settings.js.map
  tests/lib/UrlGeneratorTest.php
Labels: 3. to review, technical debt, ♻️ refactor
