Repository nextcloud/server, pull requests merged in 2025-02, with the labels that each got.

#50069 Fix OCM implementation has wrong parameter names
  lib/private/Federation/CloudFederationShare.php
Labels: bug, 3. to review, feature: federation, technical debt, feedback-requested

#50576 fix(files): Fix folder preview for favorites widget
  apps/files/lib/Dashboard/FavoriteWidget.php
Labels: bug, 3. to review, backport-request

#50260 chore : Comprehensive e2e testing for public sharing
  apps/files_sharing/src/components/SharingEntryLink.vue
  cypress/e2e/files_sharing/ShareOptionsType.ts
  cypress/e2e/files_sharing/public-share/required-before-create.cy.ts
  cypress/e2e/files_sharing/public-share/setup-public-share.ts
  dist/18-18.js
  dist/18-18.js.map
  dist/18-18.js.map.license
  dist/4590-4590.js
  dist/4590-4590.js.license
  dist/4590-4590.js.map
  dist/4590-4590.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: enhancement, 3. to review

#49016 Add the option to provide a groupname and only see its' members in occ group:list
  core/Command/Group/ListCommand.php
Labels: enhancement, 3. to review, feedback-requested

#50592 fix(unified-search): filteredProviders now inherits all provider props
  core/src/components/UnifiedSearch/UnifiedSearchModal.vue
  dist/core-unified-search.js
  dist/core-unified-search.js.map
Labels: 3. to review, backport-request, feature: search

#50638 ci(cypress): Bump upload action to latest v4 (again)
  .github/workflows/cypress.yml
Labels: 4. to release, technical debt

#50635 chore(files): Adjust wording
  apps/files/src/views/Navigation.vue
  apps/files/src/views/personal-files.ts
  cypress/e2e/files/files-filtering.cy.ts
  cypress/pages/FilesNavigation.ts
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: design, 3. to review, backport-request

#50657 fix(theming): high contrast themes scrollbar
  apps/theming/lib/Themes/DarkHighContrastTheme.php
  apps/theming/lib/Themes/HighContrastTheme.php
Labels: bug, design, 3. to review, backport-request, feature: theming, regression

#50582 fix(files): Correctly scroll selected file into view
  apps/files/src/components/FilesListTableFooter.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/components/VirtualList.vue
  cypress/e2e/core-utils.ts
  cypress/e2e/files/FilesUtils.ts
  cypress/e2e/files/files-renaming.cy.ts
  cypress/e2e/files/scrolling.cy.ts
  cypress/support/commands.ts
  cypress/support/cypress-e2e.d.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, design, 3. to review, feature: files

#50193 fix(oauth2): adjust db schemas when migrating from owncloud
  lib/private/Repair.php
  lib/private/Repair/Owncloud/MigrateOauthTables.php
Labels: bug, 4. to release, backport-request, feature: authentication, feature: owncloud migration

#40105 don't believe sftp when it tells us the mtime is less than we know it is
  apps/files_external/lib/Lib/Storage/SFTP.php
Labels: bug, 3. to review

#50673 29.0.12 RC1
  version.php
Labels: 3. to review

#50671 31.0.0 RC3
  version.php
Labels: 3. to review

#50666 feat(theming): allow to disable standalone windows
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/tests/Controller/ThemingControllerTest.php
  config/config.sample.php
Labels: enhancement, 3. to review, backport-request, feature: theming, customization

#50567 Add LDAP test settings command
  apps/user_ldap/appinfo/info.xml
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Command/TestUserSettings.php
  apps/user_ldap/lib/Group_Proxy.php
  apps/user_ldap/lib/Proxy.php
  apps/user_ldap/lib/User_Proxy.php
Labels: enhancement, 3. to review, feature: ldap

#50655 enh: Fix display default expire date, add tests & tiny refactors
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_sharing/src/components/SharingEntryLink.vue
  apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
  apps/files_sharing/src/components/SharingInput.vue
  apps/files_sharing/src/mixins/SharesMixin.js
  apps/files_sharing/src/views/SharingDetailsTab.vue
  cypress/e2e/files_sharing/public-share/setup-public-share.ts
  dist/4915-4915.js
  dist/4915-4915.js.license
  dist/4915-4915.js.map
  dist/4915-4915.js.map.license
  dist/512-512.js
  dist/512-512.js.map
  dist/512-512.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
Labels: 3. to review, feature: sharing, backport-request

#50678 fix(AccountProperty): better validation of twitter and fediverse handles
  apps/provisioning_api/lib/Controller/UsersController.php
  apps/settings/lib/Controller/UsersController.php
  apps/settings/src/components/PersonalInfo/FediverseSection.vue
  apps/settings/src/components/PersonalInfo/TwitterSection.vue
  apps/settings/src/constants/AccountPropertyConstants.ts
  apps/settings/src/service/PersonalInfo/EmailService.js
  apps/settings/src/service/PersonalInfo/PersonalInfoService.js
  apps/settings/src/utils/validate.js
  apps/settings/tests/UserMigration/AccountMigratorTest.php
  apps/settings/tests/UserMigration/assets/account-complex.json
  build/integration/features/bootstrap/BasicStructure.php
  build/integration/features/bootstrap/FeatureContext.php
  build/integration/features/provisioning-v1.feature
  build/psalm-baseline.xml
  cypress/e2e/settings/personal-info.cy.ts
  dist/settings-vue-settings-admin-basic-settings.js
  dist/settings-vue-settings-admin-basic-settings.js.map
  dist/settings-vue-settings-personal-info.js
  dist/settings-vue-settings-personal-info.js.map
  lib/private/Accounts/AccountManager.php
  lib/private/Profile/Actions/FediverseAction.php
  tests/lib/Accounts/AccountManagerTest.php
  tests/lib/Profile/Actions/FediverseActionTest.php
Labels: bug, 3. to review, backport-request, feature: profile

#48674 fix(updater): make clean-up job more robust / easier to debug
  core/BackgroundJobs/BackgroundCleanupUpdaterBackupsJob.php
Labels: enhancement, 3. to review, feature: install and update, ♻️ refactor

#49955 fix: when already upgrading, don't instruct to run `occ upgrade`
  lib/private/Console/Application.php
Labels: enhancement, 3. to review, feature: install and update, papercut

#50697 feat(admin_audit): write admin audit log for AnyLoginFailedEvent
  apps/admin_audit/lib/AppInfo/Application.php
  apps/admin_audit/lib/Listener/AuthEventListener.php
  lib/public/Authentication/Events/AnyLoginFailedEvent.php
Labels: enhancement, 3. to review, feature: admin audit

#50364 fix(files): support submenu in batch actions header too
  apps/files/src/actions/moveOrCopyAction.ts
  apps/files/src/components/FileEntry/FileEntryActions.vue
  apps/files/src/components/FilesListTableHeaderActions.vue
  apps/files/src/mixins/actionsMixin.ts
  apps/files/src/store/filters.ts
  apps/files_sharing/src/files_actions/sharingStatusAction.ts
  cypress/e2e/files/FilesUtils.ts
  cypress/e2e/files/files-actions.cy.ts
  cypress/e2e/files_sharing/FilesSharingUtils.ts
  cypress/e2e/files_sharing/files-copy-move.cy.ts
  cypress/e2e/files_sharing/note-to-recipient.cy.ts
  cypress/e2e/systemtags/files-bulk-action.cy.ts
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, backport-request, feature: files

#50680 fix(files): only send config update requests if user is logged in
  apps/files/src/eventbus.d.ts
  apps/files/src/store/userconfig.ts
  apps/files/src/store/viewConfig.ts
  apps/files/src/types.ts
  apps/files/src/views/Navigation.vue
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: sharing, backport-request, feature: files

#50735 fix(setupcheck): Update setup check for PHP version to be more accurate
  apps/settings/lib/SetupChecks/PhpOutdated.php
Labels: 3. to review, backport-request

#50753 fix(transifex): Adjust check for translation of apps
  build/translation-checker.php
Labels: bug, 3. to review, feature: language l10n and translations

#50739 feat(sharing): Allow to set default view mode for public shares
  apps/files_sharing/src/eventbus.d.ts
  apps/files_sharing/src/init-public.ts
  apps/files_sharing/src/views/SharingDetailsTab.vue
  cypress/e2e/files_sharing/public-share/default-view.cy.ts
  dist/1031-1031.js
  dist/1031-1031.js.license
  dist/1031-1031.js.map
  dist/1031-1031.js.map.license
  dist/4915-4915.js
  dist/4915-4915.js.map
  dist/4915-4915.js.map.license
  dist/files_sharing-files_sharing_tab.js
  dist/files_sharing-files_sharing_tab.js.map
  dist/files_sharing-init-public.js
  dist/files_sharing-init-public.js.map
Labels: enhancement, 3. to review, feature: sharing, backport-request, 🍀 2025-Spring

#50324 fix: don't use cached root info from shared cache if the watcher has detected an update
  apps/files_sharing/lib/Cache.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_sharing/tests/CacheTest.php
  lib/private/Files/Cache/Watcher.php
  lib/private/Files/Cache/Wrapper/JailWatcher.php
  lib/public/Files/Cache/IWatcher.php
Labels: 3. to review

#50498 Don't rethrow a type error
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/Server.php
  lib/private/Files/View.php
Labels: bug, 3. to review, backport-request

#50757 29.0.12 RC2
  version.php
Labels: 3. to review

#50081 fix(core): Fix undefined "application" array key error
  core/templates/layout.public.php
  core/templates/layout.user.php
Labels: bug, 3. to review, backport-request

#50692 fix(emailTemplate): use instance Name instead of Url in subject
  apps/settings/lib/Hooks.php
Labels: enhancement, 3. to review, backport-request, feature: emails

#50602 fix: template field title
  apps/files/src/components/TemplateFiller.vue
  apps/files/src/components/TemplateFiller/TemplateCheckboxField.vue
  apps/files/src/components/TemplateFiller/TemplateRichTextField.vue
  dist/4341-4341.js
  dist/4341-4341.js.license
  dist/4341-4341.js.map
  dist/4341-4341.js.map.license
  dist/465-465.js
  dist/465-465.js.map
  dist/465-465.js.map.license
  dist/files-init.js
  dist/files-init.js.map
Labels: 3. to review, backport-request, feature: templates

#50689 fix(dav): Migrate from hooks to user events
  apps/dav/composer/composer/autoload_classmap.php
  apps/dav/composer/composer/autoload_static.php
  apps/dav/lib/AppInfo/Application.php
  apps/dav/lib/HookManager.php
  apps/dav/lib/Listener/UserEventsListener.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/DAV/HookManagerTest.php
  apps/dav/tests/unit/DAV/Listener/UserEventsListenerTest.php
  build/psalm-baseline.xml
  tests/lib/User/UserTest.php
Labels: 3. to review, technical debt

#49648 Clarify app manager method names
  apps/comments/lib/Activity/Listener.php
  apps/comments/tests/Unit/Activity/ListenerTest.php
  apps/dav/lib/AppInfo/PluginManager.php
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/tests/unit/AppInfo/PluginManagerTest.php
  apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php
  apps/files_sharing/lib/Controller/ShareAPIController.php
  apps/files_trashbin/lib/AppInfo/Application.php
  apps/files_versions/lib/AppInfo/Application.php
  apps/settings/lib/Controller/AppSettingsController.php
  apps/systemtags/lib/Activity/Listener.php
  apps/updatenotification/lib/BackgroundJob/UpdateAvailableNotifications.php
  apps/updatenotification/lib/Command/Check.php
  apps/updatenotification/lib/Controller/APIController.php
  apps/updatenotification/tests/BackgroundJob/UpdateAvailableNotificationsTest.php
  apps/webhook_listeners/lib/BackgroundJobs/WebhookCall.php
  core/Command/App/Disable.php
  core/Command/App/Enable.php
  core/Command/App/Install.php
  core/Command/App/ListApps.php
  core/Command/App/Remove.php
  core/Command/Db/Migrations/GenerateMetadataCommand.php
  core/Command/Maintenance/Repair.php
  lib/base.php
  lib/private/App/AppManager.php
  lib/private/Console/Application.php
  lib/private/Migration/MetadataManager.php
  lib/private/NavigationManager.php
  lib/private/Server.php
  lib/private/TaskProcessing/Manager.php
  lib/private/Template/JSConfigHelper.php
  lib/private/Updater.php
  lib/private/legacy/OC_App.php
  lib/public/App/IAppManager.php
  public.php
  remote.php
  tests/Core/Command/Apps/AppsEnableTest.php
  tests/lib/App/AppManagerTest.php
  tests/lib/NavigationManagerTest.php
Labels: enhancement, 3. to review, technical debt

#50770 31.0.0 RC4
  version.php
Labels: 3. to review

#50771 30.0.6
  version.php
Labels: 3. to review

#50772 29.0.12
  version.php
Labels: 3. to review

#50781 perf(files): faster query to fetch incomplete directories
  lib/private/Files/Cache/Cache.php
  lib/private/Files/ObjectStore/ObjectStoreScanner.php
Labels: backport-request, performance 🚀

#50794 fix: Only keep allowed characters in appid, and flag the method as escaping
  lib/private/App/AppManager.php
  lib/public/App/IAppManager.php
Labels: 3. to review, backport-request

#48738 perf: Log requests using high amount of memory as warning
  lib/base.php
Labels: 3. to review, performance 🚀

#50784 fix: Fix regression in calendar invitation sending
  apps/dav/lib/CalDAV/Schedule/IMipService.php
Labels: 3. to review

#50769 fix(SharedStorage): Check if storage ID is set on cache
  apps/files_sharing/lib/SharedStorage.php
Labels: bug, 3. to review, regression

#50809 fix(repair): PHP8.3 deprecation warning
  lib/private/Repair/Owncloud/MigrateOauthTables.php
Labels: 3. to review, backport-request

#50791 chore(filecache): remove index fs_id_storage_size
  core/Application.php
  core/Migrations/Version31000Date20250213102442.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: 3. to review

#50816 fix(transferownership): Allow searching new owner by email
  apps/files/src/components/TransferOwnershipDialogue.vue
  dist/files-settings-personal.js
  dist/files-settings-personal.js.map
Labels: bug, 3. to review, feature: files

#50798 fix(login): only show error state on login box if user interacted
  core/src/components/login/LoginForm.vue
  dist/core-login.js
  dist/core-login.js.map
Labels: bug, design, 3. to review, backport-request, feature: authentication

#49872 Update & Expand Meta Tags
  apps/files_sharing/lib/DefaultPublicShareTemplateProvider.php
Labels: 3. to review, feedback-requested

#50860 fix(activity): Fix activity parameter types
  apps/dav/lib/CardDAV/Activity/Provider/Base.php
  apps/systemtags/lib/Activity/Provider.php
Labels: bug, 3. to review, feature: activity and notification

#50800 fix: Fix psalm taint errors
  apps/admin_audit/lib/Actions/Action.php
  build/psalm-baseline-security.xml
  lib/private/AppFramework/OCS/BaseResponse.php
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/Config.php
  lib/private/L10N/Factory.php
  lib/private/Setup/MySQL.php
  lib/private/SystemConfig.php
  lib/private/TaskProcessing/Manager.php
  lib/private/legacy/OC_JSON.php
  lib/private/legacy/OC_Template.php
  lib/public/AppFramework/Http/JSONResponse.php
Labels: 3. to review

#50807 fix(files): properly forward open params from short urls
  apps/files/lib/Controller/ViewController.php
  apps/files/src/components/FilesListVirtual.vue
  apps/files/src/views/FilesList.vue
  apps/files/tests/Controller/ViewControllerTest.php
  cypress/e2e/files/files.cy.ts
  dist/files-main.js
  dist/files-main.js.map
  lib/private/Route/Router.php
Labels: bug, 3. to review, backport-request, feature: files

#50864 fix: Fix psalm taint false-positives by small refactorings
  apps/files_external/lib/Config/ConfigAdapter.php
  apps/provisioning_api/lib/Controller/AppsController.php
  apps/theming/lib/Util.php
  build/psalm-baseline-security.xml
  core/Controller/SetupController.php
  lib/private/Config.php
  lib/private/Server.php
  lib/private/Session/CryptoWrapper.php
Labels: 3. to review

#50873 fix(files_sharing): block downloading if needed
  apps/files_sharing/lib/Controller/ShareController.php
  apps/files_sharing/tests/Controller/ShareControllerTest.php
Labels: bug, 3. to review, feature: sharing, backport-request

#50814 fix(systemtags): do not hide if no tags
  apps/files/src/sidebar.ts
  apps/files/src/views/Sidebar.vue
  apps/systemtags/src/components/SystemTags.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
  webpack.modules.js
Labels: bug, 3. to review, backport-request, feature: files, regression, feature: file sidebar

#50888 [stable30] fix(systemtags): do not hide if no tags
  apps/systemtags/src/components/SystemTags.vue
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: bug, 3. to review, feature: files, regression, feature: file sidebar

#50896 fix(cron): Keep job class limitation when searching for the next job
  lib/private/BackgroundJob/JobList.php
Labels: bug, 3. to review, backport-request

#50904 fix(files): do not show extension warning for folders renaming
  apps/files/src/store/renaming.ts
  cypress/e2e/files/files-renaming.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files, hotspot: filename handling

#50920 Revert "fix(files): updateAll method"
  AUTHORS
  apps/settings/src/components/AppList.vue
  dist/settings-apps-view-4529.js
  dist/settings-apps-view-4529.js.map
  dist/settings-vue-settings-apps-users-management.js
  dist/settings-vue-settings-apps-users-management.js.map
Labels: 3. to review, high, feature: apps management, regression

#50922 fix(files_sharing): Also list deleted team shares
  apps/files_sharing/lib/Controller/DeletedShareAPIController.php
Labels: bug, 3. to review, feature: sharing, backport-request

#50711 fix(files_reminders): Only allow updating reminders if the file is accessible
  apps/files_reminders/lib/Controller/ApiController.php
  apps/files_reminders/lib/Service/ReminderService.php
Labels: bug, 3. to review, feature: files

#50912 31.0.0 RC5
  version.php
Labels: 3. to review

#50910 fix(files_external): request strict password auth on credentials enter action
  apps/files_external/src/actions/enterCredentialsAction.ts
  apps/files_external/src/actions/inlineStorageCheckAction.ts
  apps/files_external/src/actions/openInFilesAction.ts
  apps/files_external/src/css/fileEntryStatus.scss
  apps/files_external/src/views/CredentialsDialog.vue
  cypress/dockerNode.ts
  cypress/e2e/files/FilesUtils.ts
  cypress/e2e/files/files-actions.cy.ts
  cypress/e2e/files_external/StorageUtils.ts
  cypress/e2e/files_external/files-user-credentials.cy.ts
  dist/4040-4040.js
  dist/4040-4040.js.license
  dist/4040-4040.js.map
  dist/4040-4040.js.map.license
  dist/9973-9973.js
  dist/9973-9973.js.license
  dist/9973-9973.js.map
  dist/9973-9973.js.map.license
  dist/files_external-init.js
  dist/files_external-init.js.license
  dist/files_external-init.js.map
Labels: bug, 4. to release, feature: external storage, backport-request, feature: files, regression

#50918 fix(files_sharing): Map sharee information for `shared-by-you` view
  apps/files_sharing/src/services/SharingService.spec.ts
  apps/files_sharing/src/services/SharingService.ts
  dist/9452-9452.js.map
  dist/files_sharing-init.js
  dist/files_sharing-init.js.map
Labels: bug, 3. to review, feature: sharing, backport-request

#50053 fix: Change UserAgent to *cloud
  apps/workflowengine/tests/Check/RequestUserAgentTest.php
  lib/public/IRequest.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: bug, 4. to release, backport-request

#50943 fix(files): handle failed node properly
  apps/files/src/components/FileEntryMixin.ts
  cypress/e2e/files_external/files-external-failed.cy.ts
  cypress/e2e/files_external/files-user-credentials.cy.ts
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, feature: external storage, backport-request, feature: files

#50946 fix(l10n): Fix triple dot in translation
  apps/files_external/src/actions/inlineStorageCheckAction.ts
  dist/files_external-init.js
  dist/files_external-init.js.map
Labels: bug, 3. to review, feature: external storage, backport-request, feature: language l10n and translations

#50949 ci(autochecks): Run some autochecks also on non-PHP files
  .github/workflows/autocheckers.yml
  build/files-checker.php
  build/htaccess-checker.php
  build/translation-checker.php
  build/triple-dot-checker.php
Labels: 4. to release, backport-request

#50942 fix(cron): Ignore time sensitivity when a class was explicitely scheduled
  cron.php
Labels: bug, 3. to review

#50244 perf(files_reminders): Reduce db queries on propfind
  apps/files_reminders/composer/composer/autoload_classmap.php
  apps/files_reminders/composer/composer/autoload_static.php
  apps/files_reminders/lib/Controller/ApiController.php
  apps/files_reminders/lib/Dav/PropFindPlugin.php
  apps/files_reminders/lib/Db/ReminderMapper.php
  apps/files_reminders/lib/Exception/ReminderNotFoundException.php
  apps/files_reminders/lib/Service/ReminderService.php
Labels: 4. to release, feature: files, performance 🚀

#50927 feat(setupcheck): check logging level for validity
  apps/settings/composer/composer/autoload_classmap.php
  apps/settings/composer/composer/autoload_static.php
  apps/settings/lib/SetupChecks/LoggingLevel.php
  apps/settings/tests/SetupChecks/LoggingLevelTest.php
Labels: enhancement, 3. to review

#50992 fix(admin_audit): Fix incorrect truncation of files path in admin audit log
  apps/admin_audit/lib/Actions/Files.php
  apps/admin_audit/lib/Listener/FileEventListener.php
Labels: 3. to review, backport-request

#50956 fix: wipe local storages on log out
  core/src/utils/xhr-request.js
  core/src/views/Login.vue
  dist/core-login.js
  dist/core-login.js.map
  dist/core-main.js
  dist/core-main.js.map
Labels: bug, 3. to review, feature: authentication

#50957 fix: rename 'edit locally' to 'open locally'
  apps/files/src/actions/openLocallyAction.spec.ts
  apps/files/src/actions/openLocallyAction.ts
  apps/files/src/init.ts
  dist/files-init.js
  dist/files-init.js.map
Labels: design, 3. to review, feature: files

#50958 Fix: NotFoundException for anonymous users
  apps/files_versions/lib/Listener/FileEventsListener.php
Labels: bug, 3. to review, backport-request, feature: versions

#50985 fix: validate account properties as a repair step
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC21/ValidatePhoneNumber.php
  lib/private/Repair/NC29/SanitizeAccountProperties.php
  lib/private/Repair/NC29/SanitizeAccountPropertiesJob.php
  tests/lib/Repair/NC29/SanitizeAccountPropertiesJobTest.php
  tests/lib/Repair/NC29/SanitizeAccountPropertiesTest.php
Labels: bug, 3. to review, backport-request

#51007 31.0.0
  version.php
Labels: 3. to review

#51011 31.0.0
  version.php
Labels: 3. to review

#50874 fix: Initialize lastConnectionCheck after first connection
  lib/private/DB/Connection.php
Labels: bug, 3. to review, php, feature: database

#50979 feat(files): allow to ignore warning to change file type
  apps/files/lib/Service/UserConfig.php
  apps/files/src/components/FileEntry/FileEntryName.vue
  apps/files/src/eventbus.d.ts
  apps/files/src/store/renaming.ts
  apps/files/src/store/userconfig.ts
  apps/files/src/types.ts
  apps/files/src/views/DialogConfirmFileExtension.cy.ts
  apps/files/src/views/DialogConfirmFileExtension.vue
  apps/files/src/views/Settings.vue
  cypress/e2e/files/files-renaming.cy.ts
  dist/7807-7807.js
  dist/7807-7807.js.license
  dist/7807-7807.js.map
  dist/7807-7807.js.map.license
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: enhancement, 3. to review, backport-request, 🍀 2025-Spring

#50903 fix(files_versions): Do not expire versions newer than min age
  apps/files_versions/lib/Expiration.php
  apps/files_versions/lib/Storage.php
Labels: bug, 3. to review, backport-request, feature: versions, php

#48795 feat: support migrating an instance to sharding
  lib/private/DB/Connection.php
  lib/private/DB/QueryBuilder/Sharded/AutoIncrementHandler.php
  lib/private/DB/QueryBuilder/Sharded/ShardConnectionManager.php
  lib/private/DB/QueryBuilder/Sharded/ShardDefinition.php
  lib/private/DB/QueryBuilder/Sharded/ShardQueryRunner.php
  tests/lib/DB/QueryBuilder/Sharded/SharedQueryBuilderTest.php
Labels: 3. to review, feature: database

#50764 Update doc comment for prefixTableName
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 3. to review, documentation

#50475 Improve error detail when saving an incorrect LDAP config
  apps/user_ldap/ajax/testConfiguration.php
  apps/user_ldap/composer/composer/autoload_classmap.php
  apps/user_ldap/composer/composer/autoload_static.php
  apps/user_ldap/lib/Connection.php
  apps/user_ldap/lib/Exceptions/ConfigurationIssueException.php
  lib/private/DB/QueryBuilder/QueryBuilder.php
Labels: 3. to review, feature: ldap

#51046 [stable30] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51045 [stable25] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51044 [stable23] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51043 [master] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51042 [stable29] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51040 [stable28] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51041 [stable31] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51036 [stable24] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51037 [stable26] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51038 [stable27] fix(security): Update CA certificate bundle
  build/ca-bundle-etag.txt
  resources/config/ca-bundle.crt
Labels: 3. to review, dependencies

#51049 fix(l10n): Improve english source strings
  apps/files/src/components/DragAndDropNotice.vue
  apps/files/src/components/FilesListTableHeaderActions.vue
  apps/files/src/components/FilesListVirtual.vue
  apps/files/templates/list.php
  apps/settings/lib/SetupChecks/AllowedAdminRanges.php
  apps/settings/lib/SetupChecks/DatabaseHasMissingIndices.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/user_ldap/lib/Access.php
  core/Command/Maintenance/Install.php
  dist/files-main.js
  dist/files-main.js.map
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  lib/private/Setup.php
Labels: bug, 3. to review, backport-request, feature: language l10n and translations

#51050 fix: Report duplicated extra files in integrity check
  lib/private/IntegrityCheck/Checker.php
Labels: bug, 3. to review, backport-request, php

#51068 [stable29] fix(l10n): Improve english source strings
  apps/files/src/components/DragAndDropNotice.vue
  apps/files/src/components/FilesListTableHeaderActions.vue
  apps/files/templates/list.php
  apps/sharebymail/lib/ShareByMailProvider.php
  apps/user_ldap/lib/Access.php
  core/Command/Maintenance/Install.php
  dist/files-main.js
  dist/files-main.js.map
  lib/private/Setup.php
Labels: 3. to review

#51071 fix(translation): Fix string concatenation in LDAP endpoint
  apps/user_ldap/ajax/wizard.php
Labels: bug, 3. to review, feature: ldap, backport-request, feature: language l10n and translations

#51069 Fix SQL query so that it is ansi safe fixing #51067
  apps/settings/lib/SetupChecks/MysqlRowFormat.php
Labels: bug, 3. to review

#51077 files: fix exception when share-attributes is undefined
  apps/files/src/services/FileInfo.ts
  dist/files-sidebar.js
  dist/files-sidebar.js.map
Labels: 3. to review, feature: files

#50990 refactor: move version rollback hook to event
  apps/files_versions/composer/composer/autoload_classmap.php
  apps/files_versions/composer/composer/autoload_static.php
  apps/files_versions/lib/AppInfo/Application.php
  apps/files_versions/lib/Events/VersionRestoredEvent.php
  apps/files_versions/lib/Listener/LegacyRollbackListener.php
  apps/files_versions/lib/Versions/VersionManager.php
  apps/files_versions/tests/Versions/VersionManagerTest.php
Labels: 3. to review, technical debt, php, ♻️ refactor

#51019 fix(files_external): Move definition parameter to the correct place
  apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php
  apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php
  apps/files_external/lib/Lib/Backend/OwnCloud.php
Labels: bug, 3. to review, backport-request

#47513 fix: remove caching in fetchListOfGroups
  apps/user_ldap/lib/Access.php
  apps/user_ldap/tests/AccessTest.php
  build/integration/openldap_features/openldap-uid-username.feature
Labels: bug, 3. to review

#51094 chore: auto sync min desktop version with last supported version
  .github/workflows/update-min-supported-desktop.yml
  config/config.sample.php
Labels: 2. developing, technical debt, client: 💻 desktop, developer experience

#51006 [stable29] fix: validate account properties as a repair step
  apps/dav/composer/composer/autoload_static.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/private/Repair.php
  lib/private/Repair/NC21/ValidatePhoneNumber.php
  lib/private/Repair/NC29/SanitizeAccountProperties.php
  lib/private/Repair/NC29/SanitizeAccountPropertiesJob.php
  tests/lib/Repair/NC29/SanitizeAccountPropertiesJobTest.php
  tests/lib/Repair/NC29/SanitizeAccountPropertiesTest.php
Labels: bug, 4. to release

#50999 fix: Replace OC_App calls by IAppManager
  apps/dav/lib/CalDAV/Activity/Provider/Event.php
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files_sharing/tests/UpdaterTest.php
  core/Command/Maintenance/Repair.php
  lib/base.php
  lib/private/Migration/BackgroundRepair.php
  lib/private/Route/Router.php
  lib/private/Server.php
  public.php
  tests/lib/Migration/BackgroundRepairTest.php
  tests/lib/Route/RouterTest.php
Labels: 3. to review, technical debt

#33545 make it possible to run occ as root
  occ
Labels: 3. to review, feature: occ

#51079 fix(files_reminders): Do not attempt to send reminders after a user has left a share
  apps/files_reminders/lib/Notification/Notifier.php
Labels: bug, 3. to review, backport-request, feature: files, feature: activity and notification

#50452 chore: update php intl stub and fix type issues
  apps/files_external/lib/Command/Notify.php
  build/psalm-baseline.xml
  build/stubs/intl.php
  lib/private/legacy/OC_Util.php
Labels: 3. to review, technical debt, php, ♻️ refactor

#50991 chore: Automated request for reviews of pull request
  .github/workflows/request-reviews.yml
Labels: feature: workflows, CI

#50881 fix(dav): Handle end of stream in `File::put`
  apps/dav/lib/Connector/Sabre/File.php
Labels: bug, 3. to review, feature: dav, backport-request

#50919 fix(files): Ensure the filter instance is mounted
  apps/files/src/eventbus.d.ts
  apps/files/src/filters/HiddenFilesFilter.ts
  apps/files/src/filters/TypeFilter.ts
  apps/files/src/store/filters.ts
  apps/files/src/views/FilesList.vue
  dist/files-init.js
  dist/files-init.js.map
  dist/files-main.js
  dist/files-main.js.map
Labels: bug, 3. to review, backport-request, feature: files

#51135 ci: fix request-reviews workflow
  .github/workflows/request-reviews.yml
Labels: 3. to review, CI

#51126 fix(cypress): wait for toast to appear
  cypress/e2e/files/files.cy.ts
Labels: bug, 2. developing

#51092 feat(PWA): add `display_override` to set the display-mode to `minimal-ui` on supported browsers
  apps/theming/lib/Controller/ThemingController.php
  apps/theming/openapi.json
  apps/theming/tests/Controller/ThemingControllerTest.php
  core/img/manifest.json
Labels: enhancement, 3. to review
